;;; all-theorems.scm -- THE BOOK OF ALL PROVEN THEOREMS (the user's roadmap,
;;; notes-57 (d), 2026-10-03): every proven theorem's statement, grouped by the
;;; file that proves it in load order, without the tactics, with the file as the
;;; chapter and a link to it.  Written at every load to reference/all-theorems.tex;
;;; docs/all-theorems.tex is the standalone wrapper (`make all-theorems' in docs/,
;;; part of `make all').
;;;
;;; The statement rendering is major-theorems.scm's: `mt--statement-tex' --
;;; flattened antecedents, single-letter bound variables, the TeX printer of
;;; tex-output.scm -- so the two documents cannot disagree.  Loads after
;;; major-theorems.
;;;
;;; WHAT IS LISTED: every name whose provenance is proven or certified, in the
;;; order the proofs were installed (*proven-theorem-names*, newest first, so
;;; reversed), minus the machine-minted companions (the -rev of a macete, the view
;;; specialisations).  WHAT IS NOT: axioms, definitions and supports, which have
;;; THEOREMS.md and PSS.md.  A chapter is a source file; its abstract is the first
;;; paragraph of the file's header comment.
;;;
;;; THE GRAPH VIEW: the entry names the theorem; in Emacs, `vnb-graph-browse-theorem'
;;; (the `t' key of the graph buffer) replays its page and opens the deduction graph
;;; on it (`graph-of', interactive.scm) -- for a theorem whose proof ran in this
;;; image; a certified one says so.

(define (at--listed-names)
  (filter (lambda (n)
            (and (memq (provenance-of n) '(proven certified))
                 (not (rev-companion-source n))
                 (not (view-specialized-source n))
                 (hash-table-ref/default *theorem-table* n #f)))
          (reverse *proven-theorem-names*)))

;;; consecutive names with the same source file -> ((file name ...) ...)
(define (at--group-by-file names)
  (let loop ((ns names) (cur #f) (acc '()) (out '()))
    (cond ((null? ns)
           (reverse (if cur (cons (cons cur (reverse acc)) out) out)))
          (#t
           (let ((f (or (mt--source-rel (car ns)) "(no file recorded)")))
             (if (and cur (string=? f cur))
                 (loop (cdr ns) cur (cons (car ns) acc) out)
                 (loop (cdr ns) f (list (car ns))
                       (if cur (cons (cons cur (reverse acc)) out) out))))))))

;;; The first paragraph of a file's header comment (the leading ;;; lines up to
;;; the first blank one), as one string; "" when there is none.
(define (at--abstract rel)
  (let ((path (string-append *prover-dir* rel)))
    (if (not (file-exists? path))
        ""
        (call-with-input-file path
          (lambda (port)
            (let loop ((acc '()) (n 0))
              (let ((line (read-line port)))
                (cond ((or (eof-object? line) (>= n 4)) (at--cap (mt--join (reverse acc) " ")))
                      ((and (>= (string-length line) 3) (string=? (string-head line 3) ";;;"))
                       (let ((body (string-trim (string-tail line 3))))
                         (if (and (pair? acc) (string=? body ""))
                             (at--cap (mt--join (reverse acc) " "))
                             (loop (if (string=? body "") acc (cons body acc)) (+ n 1)))))
                      (#t (at--cap (mt--join (reverse acc) " ")))))))))))

;;; at most 320 characters, cut at a word
(define (at--cap s)
  (if (<= (string-length s) 320)
      s
      (let loop ((i 320))
        (if (or (= i 0) (char=? (string-ref s i) #\space))
            (string-append (string-head s i) " ...")
            (loop (- i 1))))))

(define (at--bill-note name)
  (let ((b (mt--bill-line name)))
    (if (string-search-forward "modulo 0" b 0)
        ""
        (string-append "\\par{\\small\\textit{Bill: } " b "}"))))

(define (write-all-theorems-tex! out-path)
  (let* ((names  (at--listed-names))
         (groups (at--group-by-file names))
         (out    (mt--abs-path out-path)))
    (with-output-to-file out
      (lambda ()
        (display "% all-theorems.tex -- GENERATED by (write-all-theorems-tex! ...) at load.\n")
        (display "% Every proven theorem, grouped by the file that proves it, in load order.\n")
        (display "% Do not hand-edit.\n")
        (display mt--macro-block)
        (display "\\providecommand{\\vnbentry}[2]{\\par\\medskip\\noindent\\textbf{#1}\\par\\nopagebreak#2\\par}\n")
        ;; the section title IS the link to the file (hyperref's \href; file: URLs open in most viewers)
        (display "\\providecommand{\\vnbfile}[2]{\\section*{\\href{file:../#2}{\\texttt{#1}}}\\addcontentsline{toc}{section}{\\texttt{#1}}}\n")
        (display "\\noindent ") (display (number->string (length names)))
        (display " theorems in ") (display (number->string (length groups)))
        (display " files, in load order.  Each entry is the statement as the library holds it, ")
        (display "with the bill when it is not \\texttt{modulo 0}; the section is the file that ")
        (display "proves it (its path is a link).  Open the proof's graph from Emacs with ")
        (display "\\texttt{M-x vnb-graph-browse-theorem}.\n\n\\tableofcontents\n\n")
        (for-each
          (lambda (g)
            (let ((file (car g)))
              (display "\\vnbfile{") (display (mt--escape-tt file)) (display "}{") (display file) (display "}\n")
              (let ((ab (at--abstract file)))
                (if (> (string-length ab) 0)
                    (begin (display "\\noindent{\\small ") (display (mt--escape-tex ab)) (display "}\\par\n"))))
              (for-each
                (lambda (n)
                  (display "\\vnbentry{") (display (mt--tt-breakable (symbol->string n))) (display "}{")
                  (display (mt--statement-tex (mt--formula n)))
                  (display (at--bill-note n))
                  (display "}\n"))
                (cdr g))
              (display "\n")))
          groups)))
    (display ";; all-theorems: ") (display (length names)) (display " theorems in ")
    (display (length groups)) (display " files -> ") (display out-path) (newline)
    out-path))
