;;; scratch-fs2.scm -- dev: finsum-congruence

(define (last-node) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (refocus! n) (set-proof-state-focus! *ps* n))
(define (S v t f) (subst-free v t f))
(define (probe tag)
  (display ";; --- ") (display tag) (display " ---") (newline)
  (display "GOAL: ")
  (display (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
  (newline)
  (display "OPEN: ")
  (display (length (dg-ungrounded-nodes (proof-state-dg *ps*))))
  (newline))

;;; finsum-congruence:  f, g agree on S  =>  FINSUM(ag,f,S) = FINSUM(ag,g,S).
(sp (make-wff
     '(FORALL ag (IMPLIES (IS-ABELIAN-GROUP ag)
        (FORALL S (IMPLIES (IN S SET) (IMPLIES (IN (CARD S) NN)
        (FORALL f (IMPLIES (IN f (FUN S (A ag)))
        (FORALL g (IMPLIES (IN g (FUN S (A ag)))
        (IMPLIES (FORALL z (IMPLIES (IN z S) (= (f z) (g z))))
          (= (FINSUM ag f S) (FINSUM ag g S))))))))))))))
(define c0 *fresh-counter*)
(define agv (eigen-name 'ag c0))
(define Sv  (eigen-name 'S  (+ c0 1)))
(define fv  (eigen-name 'f  (+ c0 2)))
(define gv  (eigen-name 'g  (+ c0 3)))
(di)(di)(di)(di)(di)(di)(di)
(probe "after peel")

(define osn   `(ORD-SEGMENT (CARD ,Sv)))
(define feS   `(FIN-ENUM ,Sv))
(define ncard `(CARD ,Sv))
(define EFf `(ENUM-FAM ,agv ,fv ,feS ,ncard))
(define EFg `(ENUM-FAM ,agv ,gv ,feS ,ncard))

;; enum-fam-in-fun chain (shared prefix; f-slot varies)
(define EF '(FORALL n (IMPLIES (IN n NN)
   (FORALL ag (IMPLIES (IS-GROUP ag)
   (FORALL S (FORALL phi (IMPLIES (IN phi (FUN (ORD-SEGMENT n) S))
   (FORALL f (IMPLIES (IN f (FUN S (A ag)))
     (IN (ENUM-FAM ag f phi n) (FUN NN (A ag)))))))))))))
(define EFn  (S 'n ncard (caddr EF)))
(define EX1  (caddr EFn))
(define EFag (S 'ag agv (caddr EX1)))
(define EX2  (caddr EFag))
(define EFS  (S 'S Sv (caddr EX2)))
(define EFphi (S 'phi feS (caddr EFS)))
(define EX3   (caddr EFphi))

;; sum-ag-congruence chain
(define SC '(FORALL m (IMPLIES (IN m NN)
   (FORALL ag (FORALL g (FORALL gp
   (IMPLIES (IS-ABELIAN-GROUP ag)
   (IMPLIES (IN g (FUN NN (A ag)))
   (IMPLIES (IN gp (FUN NN (A ag)))
   (IMPLIES (FORALL i (IMPLIES (IN i (ORD-SEGMENT m)) (= (g i) (gp i))))
            (= (SUM-AG ag g m) (SUM-AG ag gp m))))))))))))
(define SCm  (S 'm ncard (caddr SC)))
(define SCX1 (caddr SCm))
(define SCag (S 'ag agv (caddr SCX1)))
(define SCg  (S 'g EFf (caddr SCag)))
(define SCgp (S 'gp EFg (caddr SCg)))
(define SCT2 (caddr SCgp))
(define SCT3 (caddr SCT2))
(define SCT4 (caddr SCT3))

;; helpers
(define (feb-inline)
  (ta 'fin-enum-is-bijection)
  (inst '(FORALL S (IMPLIES (IN S SET) (IMPLIES (IN (CARD S) NN)
            (IN (FIN-ENUM S) (BIJECTION (ORD-SEGMENT (CARD S)) S))))) Sv)
  (cut `(IMPLIES (IN (CARD ,Sv) NN)
           (IN (FIN-ENUM ,Sv) (BIJECTION (ORD-SEGMENT (CARD ,Sv)) ,Sv))))
  (let ((u (last-node)))
    (bc `(IMPLIES (IN ,Sv SET)
            (IMPLIES (IN (CARD ,Sv) NN)
               (IN (FIN-ENUM ,Sv) (BIJECTION (ORD-SEGMENT (CARD ,Sv)) ,Sv)))))
    (ass)
    (refocus! u)
    (bc `(IMPLIES (IN (CARD ,Sv) NN)
            (IN (FIN-ENUM ,Sv) (BIJECTION (ORD-SEGMENT (CARD ,Sv)) ,Sv))))
    (ass)))
(define (isg-inline)
  (ta 'abelian-group-is-group)
  (inst '(FORALL s (IMPLIES (IS-ABELIAN-GROUP s) (IS-GROUP s))) agv)
  (bc `(IMPLIES (IS-ABELIAN-GROUP ,agv) (IS-GROUP ,agv)))
  (ass))
(define (bij-in-fun-inline pt)
  (ta 'bijection-in-fun)
  (inst '(FORALL X (FORALL Y (FORALL phi
            (IMPLIES (IN phi (BIJECTION X Y)) (IN phi (FUN X Y)))))) osn)
  (inst `(FORALL Y (FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osn Y)) (IN phi (FUN ,osn Y))))) Sv)
  (inst `(FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osn ,Sv)) (IN phi (FUN ,osn ,Sv)))) pt)
  (bc `(IMPLIES (IN ,pt (BIJECTION ,osn ,Sv)) (IN ,pt (FUN ,osn ,Sv)))))
;; proves goal (IN (ENUM-FAM agv fterm feS ncard) (FUN NN (A agv)))
(define (ef-in-fun-proof fterm)
  (let ((EFf2 (S 'f fterm (caddr EX3))))
    (ta 'enum-fam-in-fun)
    (inst EF ncard)
    (cut EX1) (let ((u (last-node))) (bc EFn) (ass) (refocus! u))
    (inst EX1 agv)
    (cut EX2) (let ((u (last-node))) (bc EFag) (isg-inline) (refocus! u))
    (inst EX2 Sv)
    (inst EFS feS)
    (cut EX3) (let ((u (last-node)))
                (bc EFphi) (bij-in-fun-inline feS) (feb-inline) (refocus! u))
    (inst EX3 fterm)
    (bc (S 'f fterm (caddr EX3)))
    (ass)))

;; ---- proof ----
;; FACT-feSfun: (IN feS (FUN osn Sv))
(cut `(IN ,feS (FUN ,osn ,Sv)))
(define u-ff (last-node))
  (bij-in-fun-inline feS)
  (feb-inline)
(refocus! u-ff)
;; FACT-ef-f
(cut `(IN ,EFf (FUN NN (A ,agv))))
(define u-eff (last-node))
  (ef-in-fun-proof fv)
(refocus! u-eff)
;; FACT-ef-g
(cut `(IN ,EFg (FUN NN (A ,agv))))
(define u-efg (last-node))
  (ef-in-fun-proof gv)
(refocus! u-efg)

(mac 'FINSUM)
(probe "after mac FINSUM")
;; goal: (= (SUM-AG agv EFf ncard) (SUM-AG agv EFg ncard))

(ta 'sum-ag-congruence)
(inst SC ncard)
(cut SCX1) (define uX1 (last-node)) (bc SCm) (ass) (refocus! uX1)
(inst SCX1 agv)
(inst SCag EFf)
(inst SCg EFg)
(cut SCT2) (define uT2 (last-node)) (bc SCgp) (ass) (refocus! uT2)
(cut SCT3) (define uT3 (last-node)) (bc SCT2) (ass) (refocus! uT3)
(cut SCT4) (define uT4 (last-node)) (bc SCT3) (ass) (refocus! uT4)
(bc SCT4)
;; goal: AGREE' = (FORALL i (IMPLIES (IN i osn) (= (EFf i) (EFg i))))
(define ic *fresh-counter*)
(define iv (eigen-name 'i ic))
(di)
;; goal: (= (EFf iv) (EFg iv))
(mac 'ENUM-FAM)
(lam-b)
(probe "agreement after enum-fam+beta")
;; goal: (= (IF (IN iv osn) (fv (feS iv)) (E agv)) (IF (IN iv osn) (gv (feS iv)) (E agv)))
(if-true `(IF (IN ,iv ,osn) (,fv (,feS ,iv)) (E ,agv)))
(define u-lt (last-node))
  (ass)
(refocus! u-lt)
(subst `(= (IF (IN ,iv ,osn) (,fv (,feS ,iv)) (E ,agv)) (,fv (,feS ,iv))))
(if-true `(IF (IN ,iv ,osn) (,gv (,feS ,iv)) (E ,agv)))
(define u-rt (last-node))
  (ass)
(refocus! u-rt)
(subst `(= (IF (IN ,iv ,osn) (,gv (,feS ,iv)) (E ,agv)) (,gv (,feS ,iv))))
;; goal: (= (fv (feS iv)) (gv (feS iv)))
;; FACT-fsi: (IN (feS iv) Sv)
(cut `(IN (,feS ,iv) ,Sv))
(define u-fsi (last-node))
  (ta 'fun-apply-type)
  (inst '(FORALL f (FORALL A (FORALL B (FORALL x
            (IMPLIES (AND (IN f (FUN A B)) (IN x A)) (IN (f x) B)))))) feS)
  (inst `(FORALL A (FORALL B (FORALL x
            (IMPLIES (AND (IN ,feS (FUN A B)) (IN x A)) (IN (,feS x) B)))))
        osn)
  (inst `(FORALL B (FORALL x
            (IMPLIES (AND (IN ,feS (FUN ,osn B)) (IN x ,osn)) (IN (,feS x) B))))
        Sv)
  (inst `(FORALL x (IMPLIES (AND (IN ,feS (FUN ,osn ,Sv)) (IN x ,osn))
                            (IN (,feS x) ,Sv))) iv)
  (bc `(IMPLIES (AND (IN ,feS (FUN ,osn ,Sv)) (IN ,iv ,osn))
                (IN (,feS ,iv) ,Sv)))
  (di)
  (define u-fsia (last-node))
    (ass)
  (refocus! u-fsia)
    (ass)
(refocus! u-fsi)
;; use congruence hypothesis at z := (feS iv)
(inst `(FORALL z (IMPLIES (IN z ,Sv) (= (,fv z) (,gv z)))) `(,feS ,iv))
(bc `(IMPLIES (IN (,feS ,iv) ,Sv) (= (,fv (,feS ,iv)) (,gv (,feS ,iv)))))
(ass)

(probe "finsum-congruence DONE")
(display (if (proof-done? *ps*) ";; finsum-congruence OK\n" ";; finsum-congruence OPEN\n"))
