;;; suggest.scm -- assumption-pattern scanner for forward-move discovery.
;;;
;;; Macetes rewrite conclusions only; there is no automatic forward modus
;;; ponens.  When the user has an assumption of a recognisable shape (e.g.
;;; a pointwise equality that licenses `fun-domain-extensionality'), the
;;; opportunity is invisible unless the user spots it.  This module walks
;;; the current proof state's assumptions, runs each against a small
;;; catalog of patterns, and produces a human-readable report.
;;;
;;; Public entry points:
;;;   (suggest-forward-moves)       -> list of match records
;;;   (write-suggestions-md path)   -> writes the report to PATH (markdown)
;;;
;;; The pattern catalog is intentionally short.  Add rules in
;;; `*forward-move-patterns*' as recurring shapes turn up.

;;; --- pattern catalog ------------------------------------------------

;;; Each pattern entry:
;;;   (name predicate->result render-hint)
;;; where  predicate->result : sexpr -> #f or arbitrary match record,
;;;   and  render-hint        : (assumption match) -> string (markdown)

;;; (forall v (implies (in v ?dom) (= (?f v) (?g v))))
;;; Returns (list 'fn-ext dom f g) or #f.
(define (suggest--fn-ext-pattern e)
  (and (pair? e)
       (eq? (car e) 'forall)
       (= (length e) 3)
       (let ((var (cadr e)) (body (caddr e)))
         (and (pair? body) (eq? (car body) 'implies) (= (length body) 3)
              (let ((hyp (cadr body)) (concl (caddr body)))
                (and (pair? hyp) (eq? (car hyp) 'in) (= (length hyp) 3)
                     (eq? (cadr hyp) var)
                     (pair? concl) (eq? (car concl) '=) (= (length concl) 3)
                     (let ((lhs (cadr concl)) (rhs (caddr concl))
                           (dom (caddr hyp)))
                       (and (pair? lhs) (= (length lhs) 2) (eq? (cadr lhs) var)
                            (pair? rhs) (= (length rhs) 2) (eq? (cadr rhs) var)
                            (list 'fn-ext dom (car lhs) (car rhs))))))))))

(define (suggest--render-fn-ext asm match)
  asm   ; unused here; kept in the signature for the uniform (asm match) render-fn convention
  (let ((dom (cadr match)) (f (caddr match)) (g (cadddr match)))
    (string-append
      "**`fun-domain-extensionality` applies.**\n\n"
      "    a := " (expression->string dom) "\n"
      "    f := " (expression->string f) "\n"
      "    g := " (expression->string g) "\n\n"
      "Would derive:  `" (expression->string f) " = " (expression->string g) "`\n\n"
      "Sketch: cite `fun-domain-extensionality`, instantiate at "
      "`a`, `f`, `g`, then backchain off the pointwise hypothesis.\n")))

(define *forward-move-patterns*
  `((fn-ext ,suggest--fn-ext-pattern ,suggest--render-fn-ext)))

;;; --- scanner --------------------------------------------------------

;;; Walk *ps*'s focus sequent assumptions.  For each, try every pattern.
;;; Returns a list of (assumption-index assumption-sexpr pattern-name
;;; match-record render-fn).
;;; *ps* is defined in interactive.scm (initially #f); since suggest.scm
;;; loads after interactive.scm, the binding is always in scope here.
(define (suggest-forward-moves)
  (cond
    ((not *ps*) '())
    (else
     (let* ((sqn  (proof-state-focus *ps*))
            (seq  (and sqn (sequent-node-sequent sqn)))
            (asms (if seq (map wff-formula (sequent-assumptions seq)) '())))
       (let loop ((i 1) (asms asms) (acc '()))
         (cond
           ((null? asms) (reverse acc))
           (else
            (let* ((asm (car asms))
                   (hits (filter-map
                           (lambda (p)
                             (let ((m ((cadr p) asm)))
                               (and m (list i asm (car p) m (caddr p)))))
                           *forward-move-patterns*)))
              (loop (+ i 1) (cdr asms) (append acc hits))))))))))

;;; --- markdown writer ------------------------------------------------

(define (write-suggestions-md path)
  (let ((suggestions (suggest-forward-moves)))
    (with-output-to-file path
      (lambda ()
        (display "# Forward-move suggestions\n\n")
        (display "Auto-generated by `(write-suggestions-md)` after scanning ")
        (display "the current proof state's assumptions.  ")
        (display "Macetes rewrite conclusions only — this report flags ")
        (display "assumption shapes that *license* a forward derivation ")
        (display "via a foundational axiom.\n\n")
        (cond
          ((not *ps*)
           (display "*No proof in progress.*\n"))
          ((null? suggestions)
           (display "*No assumption-pattern matches in the current proof state.*\n\n")
           (display "## Patterns currently scanned\n\n")
           (display "- `forall v in S. (f v) = (g v)` → `fun-domain-extensionality`\n"))
          (else
           (for-each
             (lambda (s)
               (let ((i (car s)) (asm (cadr s)) (pname (caddr s))
                     (m (cadddr s)) (renderfn (list-ref s 4)))
                 (display "## Assumption ") (display i)
                 (display " — pattern `") (display pname) (display "`\n\n")
                 (display "    ") (display (expression->string asm))
                 (newline) (newline)
                 (display (renderfn asm m))
                 (newline)))
             suggestions)))))
    path))

;;; -----------------------------------------------------------------------
;;; (suggest-backchain) -- index-driven candidate lemmas for the focus goal.
;;;
;;; bc* applies a lemma by MATCHING its conclusion against the goal (one-sided:
;;; only the lemma's schema vars flex; the goal -- including eigenvariables --
;;; is rigid).  So a lemma is a candidate iff its conclusion fingerprint
;;; SUBSUMES the goal fingerprint: at every path the lemma key is `·' (a schema
;;; var, covers anything) or equals the goal key.  This is sound as a FILTER --
;;; same-depth fingerprints give no false negatives (if match-expr would
;;; succeed, the lemma key is `·'-or-equal everywhere); match-expr is still the
;;; real check on the survivors.  Read-only: suggests, never applies.
;;;
;;; -rev companions are NOT collapsed here (unlike the display index): a flipped
;;; goal `b = a' is matched by `X-rev', not `X', so both orientations are live
;;; retrieval targets.

;;; The focus goal formula, or #f if no proof is in progress.
(define (suggest--current-goal)
  (and *ps*
       (let ((sqn (proof-state-focus *ps*)))
         (and sqn (wff-formula (sequent-node-assertion sqn))))))

;;; Does fingerprint P (a lemma conclusion key) subsume T (the goal key)?
;;; `·' in P covers anything; a var-HEADED P (car `·', the *match-var-head*
;;; case) covers any head of equal arity; otherwise heads/arities must agree
;;; and arguments subsume pointwise.
(define (fingerprint-subsumes? p t)
  (cond
    ((eq? p *fingerprint-wild*) #t)
    ((and (pair? p) (pair? t)
          (= (length p) (length t))
          (or (eq? (car p) *fingerprint-wild*) (eq? (car p) (car t))))
     (let loop ((ps (cdr p)) (ts (cdr t)))
       (or (null? ps)
           (and (fingerprint-subsumes? (car ps) (car ts))
                (loop (cdr ps) (cdr ts))))))
    ((and (symbol? p) (symbol? t)) (eq? p t))
    (else #f)))

;;; Count of concrete (non-`·') nodes in a fingerprint -- a specificity score
;;; for ranking: more-specific lemmas matched fewer goals by luck, rank first.
(define (fingerprint-specificity fp)
  (cond ((eq? fp *fingerprint-wild*) 0)
        ((symbol? fp) 1)
        ((pair? fp) (apply + (map fingerprint-specificity fp)))
        (else 0)))

;;; #t iff a fingerprint's top head is a wildcard (the near-universal
;;; var-headed lemmas, e.g. fun-apply-type's (f x)).
(define (fingerprint-var-headed? fp)
  (and (pair? fp) (eq? (car fp) *fingerprint-wild*)))

(define (suggest--occurs? sym e)
  (cond ((eq? e sym) #t)
        ((pair? e) (or (suggest--occurs? sym (car e)) (suggest--occurs? sym (cdr e))))
        (else #f)))

;;; Schema vars bc* would peel that do NOT occur in the matched conclusion --
;;; bc* cannot discover these from the goal, so they need explicit ((v val)).
(define (suggest--undetermined-vars name)
  (call-with-values
    (lambda () (bc*--peel (lookup-theorem name)))
    (lambda (svars concl)
      (filter (lambda (v) (not (suggest--occurs? v concl))) svars))))

;;; Candidate (name . lemma-fingerprint) pairs for GOAL, ranked specific-first.
(define (suggest-backchain-candidates goal . opt-depth)
  (let* ((depth (if (pair? opt-depth) (car opt-depth) *fingerprint-default-depth*))
         (gfp   (conclusion-fingerprint goal depth))
         (cands '()))
    (for-each
      (lambda (n)
        (let ((lfp (conclusion-fingerprint (lookup-theorem n) depth)))
          (when (fingerprint-subsumes? lfp gfp)
            (set! cands (cons (cons n lfp) cands)))))
      (hash-table-keys *theorem-table*))
    (sort cands
          (lambda (a b)
            (let ((sa (fingerprint-specificity (cdr a)))
                  (sb (fingerprint-specificity (cdr b))))
              (if (= sa sb)
                  (string<? (symbol->string (car a)) (symbol->string (car b)))
                  (> sa sb)))))))

;;; Names only (ranked, most-specific first) of the bc* candidates for the
;;; current focus goal -- the read-able list an interactive front end seeds its
;;; completion with (the Focus `B' prompt).  '() if no proof or no candidate.
(define (suggest-backchain-names . opt-depth)
  (let ((goal (suggest--current-goal)))
    (if (not goal)
        '()
        (map car (apply suggest-backchain-candidates goal opt-depth)))))

;;; REPL entry point: print the focus goal, its fingerprint, and the ranked
;;; bc* candidates (each tagged with undetermined vars / wildcard-head).
(define (suggest-backchain . opt-depth)
  (let ((goal (suggest--current-goal)))
    (cond
      ((not goal) (display ";; suggest-backchain: no proof in progress\n"))
      (else
       (let* ((depth (if (pair? opt-depth) (car opt-depth) *fingerprint-default-depth*))
              (gfp   (conclusion-fingerprint goal depth))
              (cands (apply suggest-backchain-candidates goal opt-depth)))
         (display ";; goal: ") (display (expression->string goal)) (newline)
         (display ";; fingerprint: ") (display (fingerprint->string gfp)) (newline)
         (display ";; ") (display (length cands))
         (display " bc* candidate(s), most specific first:\n")
         (for-each
           (lambda (c)
             (let* ((n (car c)) (lfp (cdr c)) (undet (suggest--undetermined-vars n)))
               (display ";;   ") (display n)
               (display "  [") (display (fingerprint->string lfp)) (display "]")
               (when (fingerprint-var-headed? lfp) (display "  (wildcard head)"))
               (unless (null? undet)
                 (display "  needs ((")
                 (let loop ((vs undet) (first #t))
                   (unless (null? vs)
                     (unless first (display ") ("))
                     (display (car vs)) (display " ?")
                     (loop (cdr vs) #f)))
                 (display "))"))
               (newline)))
           cands)
         (length cands))))))

;;; -----------------------------------------------------------------------
;;; what-now -- the proof copilot's first pass (block 2, the proof-assistance
;;; analogue of `what-is').  During a live proof, fingerprint the OPEN SUBGOAL's
;;; conclusion and list the backchain lemmas whose conclusion is compatible,
;;; most-specific first, as literal (bc* 'name) calls you can paste -- each
;;; shown with the conclusion it would apply and a hint when bc* needs extra
;;; bindings.  A clean surface over suggest-backchain-candidates: (suggest-
;;; backchain) is the same ranking with fingerprints exposed; (tt) folds it into
;;; a wider tactic menu.  FIRST PASS ONLY -- conclusion fingerprint, backchain
;;; lane; no rewrite (mac) lane and no AC normalization yet.
;;;
;;; BESIDES PRINTING, what-now RETURNS the suggested moves as a list of runnable
;;; tactic forms -- e.g. ((di) (crs) (rs)), ((rfl)), or ((bc* 'n1) (bc* 'n2) ...)
;;; -- so it can feed an automated "throw everything at the wall, keep what
;;; sticks" tactic (try each on a saved state; keep the ones that close/reduce).

(define *what-now-limit* 15)

;;; The lemma's conclusion (foralls stripped, hypotheses peeled) -- the part
;;; that fingerprinted to the goal -- for a compact display, not the whole stmt.
(define (what-now--conclusion formula)
  (call-with-values
    (lambda () (strip-foralls (prenex-positive formula)))
    (lambda (vars core) (peel-implies core))))

;;; Goal-kind classifier (the "which lane?" step).  Runs on the prenex-
;;; normalised conclusion (`what-now--conclusion' = prenex-positive, then strip
;;; foralls + peel hypotheses -- the same peeling conclusion-fingerprint uses,
;;; so it sees through the alternating forall/implies that `[x in cc, y in cc]'
;;; expands to).  An algebraic = goal routes to the closer lane ((crs)/(arith)/(rfl)),
;;; not the backchain flood; a structured-predicate / set-or-fun = / comparison
;;; goal routes to the backchain lane (where bc* candidates actually apply).

;;; A term built only from arithmetic operators over atoms/numerals -- the
;;; shape (crs) decides.  Bare atoms count, but a *ring equality* needs at least
;;; one compound side (else `a = b' is just two opaque names -> backchain).
(define (what-now--arith-term? e)
  (or (not (pair? e))
      (and (memq (car e) '(+ * - / ^ power expt negate binplus bintimes binneg))
           (let loop ((xs (cdr e)))
             (or (null? xs)
                 (and (what-now--arith-term? (car xs)) (loop (cdr xs))))))))

(define (what-now--classify core)
  (cond
    ((not (pair? core)) 'predicate)
    ((and (eq? (car core) '=) (= (length core) 3))
     (cond
       ((equal? (cadr core) (caddr core)) 'reflexive)
       ((and (arith-eval-term (cadr core)) (arith-eval-term (caddr core))) 'ground-arith)
       ((and (what-now--arith-term? (cadr core))
             (what-now--arith-term? (caddr core))
             (or (pair? (cadr core)) (pair? (caddr core))))
        'ring-equality)
       (else 'equality-other)))            ; set / function / structure equality
    ((memq (car core) '(<= < > >=)) 'comparison)
    (else 'predicate)))                     ; membership, defined predicate, ...

;;; Print the ranked (bc* ...) candidate list for GOAL (the backchain lane);
;;; RETURN the candidate names (most-specific first) so the caller can turn
;;; them into (bc* 'name) moves.
(define (what-now--show-backchain goal opt-depth)
  (let* ((cands (apply suggest-backchain-candidates goal opt-depth))
         (names (map car cands))
         (n     (length cands)))
    (cond
      ((null? cands)
       (display ";; backchain lane: no lemma conclusion fingerprints to this goal.") (newline)
       (display ";; try (suggest-rewrite) for rewrites, or (tt) for the full menu.") (newline))
      (else
       (display ";; backchain lane -- ") (display n)
       (display " (bc* ...) candidate(s), most-specific first")
       (when (> n *what-now-limit*)
         (display " (showing ") (display *what-now-limit*) (display ")"))
       (display ":") (newline)
       (let loop ((cs cands) (k 0))
         (when (and (pair? cs) (< k *what-now-limit*))
           (let* ((name  (caar cs))
                  (undet (suggest--undetermined-vars name)))
             (display ";;   (bc* '") (display name) (display ")")
             (unless (null? undet)
               (display "   -- needs bindings for ")
               (let iloop ((vs undet) (first #t))
                 (unless (null? vs)
                   (unless first (display ", "))
                   (display (car vs))
                   (iloop (cdr vs) #f))))
             (newline)
             (display ";;        concludes  ")
             (display (expression->string
                       (what-now--conclusion (lookup-theorem name))))
             (newline))
           (loop (cdr cs) (+ k 1))))
       (when (> n *what-now-limit*)
         (display ";;   ... ") (display (- n *what-now-limit*))
         (display " more -- (suggest-backchain) for the full ranking.") (newline))))
    names))

(define (what-now . opt-depth)
  (let ((goal (suggest--current-goal)))
    (cond
      ((not goal)
       (display ";; what-now: no proof in progress -- start one, then ask again.")
       (newline)
       '())
      (else
       (let* ((core     (what-now--conclusion goal))   ; prenex-normalised conclusion
              (kind     (what-now--classify core))
              (needs-di (and (pair? goal)
                             (memq (car goal) '(forall forsome implies and iff not))))
              (moves    '()))                  ; the tactic forms, returned for automation
         (display ";; what-now -- open goal:") (newline)
         (display ";;   ") (display (expression->string goal)) (newline)
         (case kind
           ((reflexive)
            (set! moves '((rfl)))
            (display ";; both sides are identical -> (rfl).") (newline))
           ((ground-arith)
            (set! moves '((arith) (crs)))
            (display ";; ground arithmetic equality -> (arith)   (or (crs)).") (newline))
           ((ring-equality)
            (set! moves (if needs-di '((di) (crs) (rs)) '((crs) (rs))))
            (display ";; ring / arithmetic equality -- closer lane, NOT backchain:") (newline)
            (when needs-di
              (display ";;   (di)    -- introduce the bound variables / hypotheses first, then:") (newline))
            (display ";;   (crs)   -- commutative-ring decision procedure   ((rs) if non-commutative)") (newline)
            (display ";; (backchain suppressed: an = goal floods with generic equality lemmas; (suggest-backchain) to see them.)") (newline))
           ((comparison)
            (display ";; comparison goal -- (ineq i1 i2 ...) from named ordering assumptions, or backchain:") (newline)
            ;; polynomial inequality (both sides arithmetic, <=): also offer the
            ;; sum-of-squares lane, which ineq (linear only) cannot reach.
            (when (and (memq (car core) '(<= >=))
                       (what-now--arith-term? (cadr core))
                       (what-now--arith-term? (caddr core))
                       (or (pair? (cadr core)) (pair? (caddr core))))
              (display ";;   (sos \"c1\" \"c2\" ...) -- polynomial inequality via a sum-of-squares") (newline)
              (display ";;     certificate (supply the squares; run BEFORE di so c_i use the goal vars).") (newline))
            (set! moves (map (lambda (nm) (list 'bc* (list 'quote nm)))
                             (what-now--show-backchain goal opt-depth))))
           (else                                ; equality-other, predicate
            (set! moves (map (lambda (nm) (list 'bc* (list 'quote nm)))
                             (what-now--show-backchain goal opt-depth)))))
         (when (and needs-di (memq kind '(comparison equality-other predicate)))
           (display ";; (goal has binders/structure -- (di) first if you'd rather introduce them.)") (newline))
         (display ";; first pass: goal-kind classifier + backchain lane (no rewrite/mac lane yet).")
         (newline)
         moves)))))                             ; <- return the move list (besides printing)

;;; Capture a what-now answer to PATH (consumed by the elisp `vnb-what-now',
;;; which shows it in the What-Now workspace instead of the REPL).  Reads the
;;; live *ps*, same as (what-now).
(define (write-what-now path . opt-depth)
  (with-output-to-file path (lambda () (apply what-now opt-depth)))
  path)

;;; -----------------------------------------------------------------------
;;; (suggest-rewrite) -- index-driven candidate REWRITE rules for the focus.
;;;
;;; The rewrite analogue of suggest-backchain.  bc* matches a lemma's
;;; CONCLUSION against the whole goal; `mac' instead matches a rule's LHS
;;; PATTERN against SOME SUBTERM of the goal (or, for `mac-h', of an
;;; assumption) and rewrites it to the RHS.  So the candidate test is
;;; different: a rule X is a candidate iff its core is a symmetric form
;;; (=/IFF/==) and the fingerprint of its LHS SUBSUMES the fingerprint of at
;;; least one subterm of the target.  Same one-sided direction as bc*: the
;;; rule's schema vars flex, the target subterm is rigid.
;;;
;;; `-rev' companions are NOT collapsed (as in suggest-backchain): X rewrites
;;; L->R, X-rev rewrites R->L, and both are legitimate `mac' targets, so a
;;; goal subterm shaped like either side surfaces the matching orientation.
;;;
;;; Scope: only theorem-table rules (equations, biconditionals, defined-
;;; PREDICATE unfolds).  Pure functoid/macete-table unfolds with no theorem
;;; entry are out of scope here, exactly as for suggest-backchain.

;;; Every pair-subterm of E (E itself included), pre-order.  Non-pairs (atoms,
;;; the empty list) contribute nothing.  Recurs through EVERY element -- args
;;; and a compound head alike -- so a rewriteable position anywhere is seen.
(define (suggest--subterms e)
  (if (pair? e)
      (cons e (append-map suggest--subterms e))
      '()))

;;; The rewrite-LHS fingerprint of theorem FORMULA at DEPTH, or #f if FORMULA's
;;; core (under FORALLs and at-most-one IMPLIES) is not a symmetric =/IFF/==
;;; rule.  `mac' rewrites that core's LHS (the second element) to its RHS.
(define (suggest--rewrite-lhs-fingerprint formula depth)
  (let-values (((vars core) (strip-foralls (prenex-positive formula))))
    (let ((c (peel-implies core)))
      (and (pair? c)
           (memq (car c) *symmetric-core-heads*)
           (= (length c) 3)
           (fingerprint-expr (cadr c) depth vars)))))

;;; Candidate (name . lhs-fingerprint) pairs whose LHS pattern can fire on some
;;; subterm of TARGET, ranked specific-first.  A fully-wild LHS (a bare schema
;;; var, which would "match" everything) is dropped -- it is never a useful
;;; rewrite suggestion.
(define (suggest-rewrite-candidates target . opt-depth)
  (let* ((depth  (if (pair? opt-depth) (car opt-depth) *fingerprint-default-depth*))
         (subfps (map (lambda (s) (fingerprint-expr s depth '()))
                      (suggest--subterms target)))
         (cands  '()))
    (for-each
      (lambda (n)
        (let ((lfp (suggest--rewrite-lhs-fingerprint (lookup-theorem n) depth)))
          (when (and lfp
                     (not (eq? lfp *fingerprint-wild*))
                     (any (lambda (sfp) (fingerprint-subsumes? lfp sfp)) subfps))
            (set! cands (cons (cons n lfp) cands)))))
      (hash-table-keys *theorem-table*))
    (sort cands
          (lambda (a b)
            (let ((sa (fingerprint-specificity (cdr a)))
                  (sb (fingerprint-specificity (cdr b))))
              (if (= sa sb)
                  (string<? (symbol->string (car a)) (symbol->string (car b)))
                  (> sa sb)))))))

;;; Names only (ranked) of the rewrite rules that can fire on the current focus
;;; GOAL -- the completion seed for the Focus `mac' (Rewrite goal) prompt.
(define (suggest-rewrite-names . opt-depth)
  (let ((goal (suggest--current-goal)))
    (if (not goal)
        '()
        (map car (apply suggest-rewrite-candidates goal opt-depth)))))

;;; Names only (ranked) of the rewrite rules that can fire on the ASSUMPTION
;;; named by SEL (an assumption index as shown, or its formula) -- the
;;; completion seed for the Focus `mac-h' (Rewrite hypothesis) prompt.  '() if
;;; no proof, or SEL does not resolve to an assumption.
(define (suggest-rewrite-names-asm sel . opt-depth)
  (if (not *ps*)
      '()
      (let ((raw (->raw-formula/idx sel)))
        (if (vnb-warning? raw)
            '()
            (map car (apply suggest-rewrite-candidates raw opt-depth))))))

;;; The pool of all installed rewrite-rule names (symmetric-core theorems),
;;; sorted -- the completion fallback for `mac'/`mac-h' when no suggestion
;;; matches (the rewrite analogue of `theorem-names', which `ta' uses).
(define (rewrite-names . opt-depth)
  (let ((depth (if (pair? opt-depth) (car opt-depth) *fingerprint-default-depth*)))
    (sort
      (filter (lambda (n)
                (suggest--rewrite-lhs-fingerprint (lookup-theorem n) depth))
              (hash-table-keys *theorem-table*))
      (lambda (a b) (string<? (symbol->string a) (symbol->string b))))))

;;; REPL entry point (parity with suggest-backchain): print the focus goal and
;;; the ranked rewrite candidates that can fire on one of its subterms.
(define (suggest-rewrite . opt-depth)
  (let ((goal (suggest--current-goal)))
    (cond
      ((not goal) (display ";; suggest-rewrite: no proof in progress\n"))
      (else
       (let ((cands (apply suggest-rewrite-candidates goal opt-depth)))
         (display ";; goal: ") (display (expression->string goal)) (newline)
         (display ";; ") (display (length cands))
         (display " rewrite candidate(s), most specific first:\n")
         (for-each
           (lambda (c)
             (let ((n (car c)) (lfp (cdr c)))
               (display ";;   ") (display n)
               (display "  [LHS ") (display (fingerprint->string lfp)) (display "]")
               (when (fingerprint-var-headed? lfp) (display "  (wildcard head)"))
               (newline)))
           cands)
         (length cands))))))

;;; -----------------------------------------------------------------------
;;; (find-mac SUBSTR) / (find-thm SUBSTR) -- REPL name search.
;;;
;;; The s-expr-surface counterpart to the Focus name completers: when you are
;;; TYPING a `(mac '...' or `(bc* '...' form and only half-remember a name, you
;;; want to grep the pool.  find-mac searches the rewrite-rule pool, find-thm
;;; the full theorem pool, for names CONTAINING substr (a string or symbol).
;;; When a proof is in progress, each hit the index calls relevant to the
;;; current goal -- fires on it (find-mac) / backchains it (find-thm) -- is
;;; tagged `*' and floated to the top, so the same ranking the buttons use
;;; shows up here too.  Returns the matching names, relevant ones first.

(define (find--name-search needle pool relevant)
  (let* ((s      (if (symbol? needle) (symbol->string needle) needle))
         (hits   (filter (lambda (n)
                           (string-search-forward s (symbol->string n) 0))
                         pool))
         (ranked (sort hits
                       (lambda (a b)
                         (let ((ra (if (memq a relevant) 0 1))
                               (rb (if (memq b relevant) 0 1)))
                           (if (= ra rb)
                               (string<? (symbol->string a) (symbol->string b))
                               (< ra rb)))))))
    (display ";; ") (display (length ranked))
    (display " match(es) for \"") (display s) (display "\"")
    (if (pair? relevant)
        (display "  (* = relevant to current goal):")
        (display ":"))
    (newline)
    (for-each (lambda (n)
                (display ";;   ") (display (if (memq n relevant) "* " "  "))
                (display n) (newline))
              ranked)
    ranked))

(define (find-mac substr)
  (find--name-search substr (rewrite-names)
                     (if *ps* (suggest-rewrite-names) '())))

(define (find-thm substr)
  (find--name-search substr (theorem-names)
                     (if *ps* (suggest-backchain-names) '())))

;;; -----------------------------------------------------------------------
;;; B+ -- the saturating closer.
;;;
;;; From the current proof, sweep EVERY open goal (all goals under the start
;;; node) and close everything it can DECISIVELY close:
;;;   - ass-all: goals already discharged by their own context;
;;;   - a cite of the top fingerprint-ranked backchain lemma, but ONLY when
;;;     bc*-can-close? confirms (purely, no mutation) that all the lemma's
;;;     hypotheses are already assumptions -- so cite + ass-all lands the goal.
;;; Each goal is first peeled (bc*-reduce-goal!) to expose its conclusion.
;;; The loop repeats until a pass closes nothing.  Because the dg has no undo
;;; (rules mutate in place), B+ never makes a speculative move it can't see
;;; through -- it closes the mechanical/plumbing goals and STOPS at anything
;;; needing a real choice, rather than polluting the tree with dead ends.
;;; (The speculative, backtracking variant is the deferred v2.)
;;;
;;; Optional arg = how many ranked candidates to examine per goal (default 8).
(define (bplus . opt)
  (vnb--require-proof!)
  (let ((k (if (pair? opt) (car opt) 8)))
    (define (open) (dg-ungrounded-nodes (proof-state-dg *ps*)))
    (define (focus-goal)
      (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
    (quietly
     (lambda ()
       (let sweep ()
         (let ((before (length (open))))
           (ass-all)                                   ; free closes
           (for-each
             (lambda (g)
               (when (not (sequent-node-grounded? g))
                 (set-proof-state-focus! *ps* g)
                 (bc*-reduce-goal!)                    ; peel leading FORALL/IMPLIES
                 (let ((cands (let ((c (map car (suggest-backchain-candidates
                                                  (focus-goal)))))
                                (if (> (length c) k) (list-head c k) c))))
                   (let try ((cs cands))
                     (when (pair? cs)
                       (let ((subst (bc*-can-close? (car cs))))
                         (if subst
                             (bc*-apply (car cs) subst)   ; cite; hyps spawn + close
                             (try (cdr cs)))))))))
             (open))
           (ass-all)                                   ; close freshly-spawned hyps
           (when (< (length (open)) before) (sweep))))))
    ;; Land the focus on a remaining open goal so the user has somewhere to go.
    (let ((rest (open)))
      (when (pair? rest) (set-proof-state-focus! *ps* (car rest))))
    (show)
    (let ((n (length (open))))
      (if (proof-done? *ps*)
          (display ";; B+ closed the proof.\n")
          (begin (display ";; B+ stalled: ") (display n)
                 (display " open goal(s) it could not decisively close")
                 (display " (focus is on the first).\n"))))
    (length (open))))

;;; -----------------------------------------------------------------------
;;; (things-to-try) -- a unified "what can I do at the current focus?" menu.
;;;
;;; As the tactic and macete sets grow, this is the single front door: it
;;; aggregates the cheap SHAPE-based tactic checks (closers, decomposition,
;;; simplifiers, the +/binplus surface bridges) with the two index-driven
;;; suggesters (rewrite macetes, backchaining lemmas) and the forward-move
;;; scan.  Each line is a command you can paste; nothing is applied -- it is
;;; advice, ranked cheaply by category.  (tt) is the short alias.
;;; -----------------------------------------------------------------------

;;; Does SYM occur as the head of E or any subterm?
(define (ttry--has-head? sym e)
  (and (pair? e)
       (or (eq? (car e) sym)
           (let lp ((xs e))
             (and (pair? xs)
                  (or (ttry--has-head? sym (car xs)) (lp (cdr xs))))))))

;;; The goal's CORE: strip leading universals, then one IMPLIES antecedent.
(define (ttry--core g)
  (let-values (((vs c) (strip-foralls g))) (peel-implies c)))

(define (things-to-try)
  (if (not *ps*)
      (display ";; things-to-try: no proof in progress\n")
      (let* ((sqn   (proof-state-focus *ps*))
             (g     (wff-formula (sequent-node-assertion sqn)))
             (asms  (map wff-formula (sequent-node-assumptions sqn)))
             (core  (ttry--core g))
             (groups '()))
        (define (add! label cmd why)
          (let ((cell (assoc label groups)))
            (if cell
                (set-cdr! cell (cons (cons cmd why) (cdr cell)))
                (set! groups (cons (list label (cons cmd why)) groups)))))
        (define (take ns k) (if (> (length ns) k) (list-head ns k) ns))
        ;; ---- closers ----
        (when (or (member g asms) (equal? g '(TRUTH)))
          (add! "Close" "(ass)" "goal is already an assumption / TRUTH"))
        (when (and (pair? core) (eq? (car core) '=) (= (length core) 3))
          (when (equal? (cadr core) (caddr core))
            (add! "Close" "(rfl)" "both sides identical"))
          (if (and (arith-eval-term (cadr core)) (arith-eval-term (caddr core)))
              (add! "Close" "(arith)" "ground arithmetic -- evaluate")
              (begin
                (add! "Close" "(crs)" "ring equation? -- commutative-ring decision procedure")
                (add! "Close" "(rs)"  "ring equation? -- non-commutative"))))
        (when (and (pair? core) (memq (car core) '(<= < > >=)))
          (add! "Close" "(ineq i1 i2 ...)" "linear RR inequality from named assumptions"))
        ;; ---- decompose ----
        (when (and (pair? g) (memq (car g) '(FORALL FORSOME IMPLIES AND IFF NOT)))
          (add! "Decompose" "(di)"
                (string-append "goal head is " (symbol->string (car g)))))
        ;; ---- simplify / surface ----
        (when (find-cring-redex g #f)
          (add! "Simplify" "(simp)" "a commutative-ring subterm is non-canonical"))
        (when (or (ttry--has-head? '+ g) (ttry--has-head? '* g))
          (add! "Surface" "(to-binary)"
                "push +/* onto the binplus/bintimes structure surface"))
        (when (or (ttry--has-head? 'binplus g) (ttry--has-head? 'bintimes g)
                  (ttry--has-head? 'binneg g))
          (add! "Surface" "(to-nary)" "bring binplus/bintimes back to +/*"))
        ;; ---- rewrite (index-driven) ----
        (for-each (lambda (n)
                    (add! "Rewrite (mac)"
                          (string-append "(mac '" (symbol->string n) ")") ""))
                  (take (suggest-rewrite-names) 6))
        ;; ---- backchain (index-driven) ----
        (for-each (lambda (n)
                    (add! "Backchain (bc*/ta)"
                          (string-append "(bc* '" (symbol->string n) ")") ""))
                  (take (suggest-backchain-names) 6))
        ;; ---- forward ----
        (let ((fm (suggest-forward-moves)))
          (when (pair? fm)
            (add! "Forward" "(suggest-forward-moves)"
                  (string-append (number->string (length fm))
                                 " applicable assumption move(s) (fact/detach!)"))))
        ;; ---- print ----
        (display ";; things to try at the focus:\n")
        (display ";;   goal: ") (display (expression->string g)) (newline)
        (if (null? groups)
            (display ";;   (nothing obvious -- try (find-thm \"..\") / (find-mac \"..\"))\n")
            (for-each
              (lambda (grp)
                (display ";; ") (display (car grp)) (display ":\n")
                (for-each
                  (lambda (cw)
                    (display ";;   ") (display (car cw))
                    (unless (string=? (cdr cw) "")
                      (display "   -- ") (display (cdr cw)))
                    (newline))
                  (reverse (cdr grp))))
              (reverse groups))))))

(define (tt) (things-to-try))
