;;; suggest.scm -- assumption-pattern scanner for forward-move discovery.
;;;
;;; Macetes rewrite conclusions only; there is no automatic forward modus
;;; ponens.  When the user has an assumption of a recognisable shape (e.g.
;;; a pointwise equality that licenses `fun-domain-extensionality'), the
;;; opportunity is invisible unless the user spots it.  This module walks
;;; the current proof state's assumptions, runs each against a small
;;; catalog of patterns, and produces a human-readable report.
;;;
;;; Public entry points:
;;;   (suggest-forward-moves)       -> list of match records
;;;   (write-suggestions-md path)   -> writes the report to PATH (markdown)
;;;
;;; The pattern catalog is intentionally short.  Add rules in
;;; `*forward-move-patterns*' as recurring shapes turn up.

;;; --- pattern catalog ------------------------------------------------

;;; Each pattern entry:
;;;   (name predicate->result render-hint)
;;; where  predicate->result : sexpr -> #f or arbitrary match record,
;;;   and  render-hint        : (assumption match) -> string (markdown)

;;; (forall v (implies (in v ?dom) (= (?f v) (?g v))))
;;; Returns (list 'fn-ext dom f g) or #f.
(define (suggest--fn-ext-pattern e)
  (and (pair? e)
       (eq? (car e) 'forall)
       (= (length e) 3)
       (let ((var (cadr e)) (body (caddr e)))
         (and (pair? body) (eq? (car body) 'implies) (= (length body) 3)
              (let ((hyp (cadr body)) (concl (caddr body)))
                (and (pair? hyp) (eq? (car hyp) 'in) (= (length hyp) 3)
                     (eq? (cadr hyp) var)
                     (pair? concl) (eq? (car concl) '=) (= (length concl) 3)
                     (let ((lhs (cadr concl)) (rhs (caddr concl))
                           (dom (caddr hyp)))
                       (and (pair? lhs) (= (length lhs) 2) (eq? (cadr lhs) var)
                            (pair? rhs) (= (length rhs) 2) (eq? (cadr rhs) var)
                            (list 'fn-ext dom (car lhs) (car rhs))))))))))

(define (suggest--render-fn-ext asm match)
  (let ((dom (cadr match)) (f (caddr match)) (g (cadddr match)))
    (string-append
      "**`fun-domain-extensionality` applies.**\n\n"
      "    a := " (expression->string dom) "\n"
      "    f := " (expression->string f) "\n"
      "    g := " (expression->string g) "\n\n"
      "Would derive:  `" (expression->string f) " = " (expression->string g) "`\n\n"
      "Sketch: cite `fun-domain-extensionality`, instantiate at "
      "`a`, `f`, `g`, then backchain off the pointwise hypothesis.\n")))

(define *forward-move-patterns*
  `((fn-ext ,suggest--fn-ext-pattern ,suggest--render-fn-ext)))

;;; --- scanner --------------------------------------------------------

;;; Walk *ps*'s focus sequent assumptions.  For each, try every pattern.
;;; Returns a list of (assumption-index assumption-sexpr pattern-name
;;; match-record render-fn).
;;; *ps* is defined in interactive.scm (initially #f); since suggest.scm
;;; loads after interactive.scm, the binding is always in scope here.
(define (suggest-forward-moves)
  (cond
    ((not *ps*) '())
    (else
     (let* ((sqn  (proof-state-focus *ps*))
            (seq  (and sqn (sequent-node-sequent sqn)))
            (asms (if seq (map wff-formula (sequent-assumptions seq)) '())))
       (let loop ((i 1) (asms asms) (acc '()))
         (cond
           ((null? asms) (reverse acc))
           (else
            (let* ((asm (car asms))
                   (hits (filter-map
                           (lambda (p)
                             (let ((m ((cadr p) asm)))
                               (and m (list i asm (car p) m (caddr p)))))
                           *forward-move-patterns*)))
              (loop (+ i 1) (cdr asms) (append acc hits))))))))))

;;; --- markdown writer ------------------------------------------------

(define (write-suggestions-md path)
  (let ((suggestions (suggest-forward-moves)))
    (with-output-to-file path
      (lambda ()
        (display "# Forward-move suggestions\n\n")
        (display "Auto-generated by `(write-suggestions-md)` after scanning ")
        (display "the current proof state's assumptions.  ")
        (display "Macetes rewrite conclusions only — this report flags ")
        (display "assumption shapes that *license* a forward derivation ")
        (display "via a foundational axiom.\n\n")
        (cond
          ((not *ps*)
           (display "*No proof in progress.*\n"))
          ((null? suggestions)
           (display "*No assumption-pattern matches in the current proof state.*\n\n")
           (display "## Patterns currently scanned\n\n")
           (display "- `forall v in S. (f v) = (g v)` → `fun-domain-extensionality`\n"))
          (else
           (for-each
             (lambda (s)
               (let ((i (car s)) (asm (cadr s)) (pname (caddr s))
                     (m (cadddr s)) (renderfn (list-ref s 4)))
                 (display "## Assumption ") (display i)
                 (display " — pattern `") (display pname) (display "`\n\n")
                 (display "    ") (display (expression->string asm))
                 (newline) (newline)
                 (display (renderfn asm m))
                 (newline)))
             suggestions)))))
    path))
