;;; ideal.scm -- ideals, principal ideals, and principal-ideal domains over a
;;; commutative ring.  The vocabulary the Euclidean-ring => PID stress test
;;; needs (theorem-library/euclidean-ring-pid.scm).
;;;
;;; An ideal is a SUBSET of the carrier, not a structure of its own, so IS-IDEAL
;;; is a two-place predicate IS-IDEAL(s, I) rather than a def-structure shape.
;;; The principal ideal generated by `a' is the concrete set CARR(s).a; the
;;; universal property ("smallest ideal containing a") is a THEOREM about that
;;; concrete object, never the definition.  [[feedback-concrete-universal-property]]
;;;
;;; Dependencies: ring.scm (A, ADD, MUL, NEG, ZERO), commutative-ring.scm
;;; (IS-COMMUTATIVE-RING), integral-domain.scm (IS-INTEGRAL-DOMAIN), the set
;;; kernel (SEP, SUBSET, IN), number-systems (NN, succ, <=).

;;; -----------------------------------------------------------------------
;;; IS-IDEAL(s, I): I is an ideal of the commutative ring s.
;;;   * I is a subset of the carrier,
;;;   * 0 in I (so I is nonempty),
;;;   * I is closed under addition,
;;;   * I is closed under additive inverse,
;;;   * I absorbs multiplication by ANY ring element  (r in A, a in I => r.a in I).
;;; NEG-closure is kept as an explicit conjunct rather than derived from
;;; absorption via (-1).a, because the I-subset-(b) step of the PID proof needs
;;; a - q.b in I directly.
(def-predicate 'IS-IDEAL '(s I)
  '(AND (IS-COMMUTATIVE-RING s)
   (AND (SUBSET I (CARR s))
   (AND (IN (ZERO s) I)
   (AND (FORALL a (IMPLIES (IN a I)
          (FORALL b (IMPLIES (IN b I)
            (IN ((ADD s) a b) I)))))
   (AND (FORALL a (IMPLIES (IN a I)
            (IN ((NEG s) a) I)))
        (FORALL r (IMPLIES (IN r (CARR s))
          (FORALL a (IMPLIES (IN a I)
            (IN ((MUL s) r a) I)))))))))))

;;; -----------------------------------------------------------------------
;;; PRINCIPAL-IDEAL(s, a): the ideal generated by a, concretely  CARR(s).a =
;;;   { x in CARR(s) : x = r.a for some r in CARR(s) }.  Written as a SEP, so its
;;; membership law is the kernel separation rule sep-me.
(def-functoid 'PRINCIPAL-IDEAL '(s a)
  '(SEP x (CARR s) (FORSOME r (AND (IN r (CARR s)) (= x ((MUL s) r a))))))

;;; principal-ideal-membership: x in (a) iff x in CARR(s) and x = r.a for some
;;; r in CARR(s).  Direct from SEP membership (cf. preimage-membership); recorded
;;; so proofs can rewrite by name rather than unfolding the SEP each time.
(theory-add-axiom! *current-theory* 'principal-ideal-membership
  '(FORALL s (FORALL a (FORALL x
     (IFF (IN x (PRINCIPAL-IDEAL s a))
          (AND (IN x (CARR s))
               (FORSOME r (AND (IN r (CARR s)) (= x ((MUL s) r a))))))))))

;;; -----------------------------------------------------------------------
;;; IS-PID(s): s is a principal-ideal domain -- an integral domain in which
;;; every ideal is principal.
(def-predicate 'IS-PID '(s)
  '(AND (IS-INTEGRAL-DOMAIN s)
        (FORALL I (IMPLIES (IS-IDEAL s I)
          (FORSOME a (AND (IN a (CARR s))
                          (= I (PRINCIPAL-IDEAL s a))))))))

;;; Associated proper class PID = { s | IS-PID(s) }, mirroring INTEGRAL-DOMAIN.
(theory-add-axiom! *current-theory* 'pid-class
  '(FORALL s (IFF (IN s PID) (IS-PID s))))

(register-definitional-structure! 'PID 'INTEGRAL-DOMAIN)

;;; -----------------------------------------------------------------------
;;; nn-least-element (the well-ordering of NN -- the math content of the PID
;;; proof's minimal-degree step) is NOT asserted here.  It is PROVEN in
;;; theorem-library/nn-least-element.scm from ord-well-ordered (ordinals.scm),
;;; the canonical home of the well-ordering principle.  ideal.scm loads before
;;; ordinals.scm, and nothing here depends on nn-least-element at load time
;;; (it is named only in the euclidean-ideal-has-generator warrant below).

;;; -----------------------------------------------------------------------
;;; The three lemmas the Euclidean-ring => PID proof leans on.  Antecedents
;;; are curried (nested IMPLIES, not a single AND) so the `fact' forward-
;;; assembly tactic can detach them one at a time against the live context.
;;;
;;; The stress-test finding (theorem-library/euclidean-ring-pid.scm): once
;;; these three are in hand, the theorem itself is pure set-extensionality
;;; glue -- ALL the mathematical content lives in euclidean-ideal-has-
;;; generator (well-ordering of degrees + Euclidean division); the other two
;;; are immediate ideal algebra.

;;; ideal-elt-in-carrier: an element of an ideal lies in the carrier.
;;; Immediate from the SUBSET I (CARR s) conjunct of IS-IDEAL.
(support 'ideal-elt-in-carrier
  '(FORALL s (FORALL I (FORALL x
     (IMPLIES (IS-IDEAL s I) (IMPLIES (IN x I) (IN x (CARR s))))))))
(warrant! 'ideal-elt-in-carrier 'proof
  "IS-IDEAL(s,I) has SUBSET I (CARR s) as a conjunct; apply subset-def at x.")

;;; principal-ideal-in-ideal: if b lies in the ideal I then the whole
;;; principal ideal (b) is contained in I -- the easy inclusion (b) subset I.
(support 'principal-ideal-in-ideal
  '(FORALL s (FORALL I (FORALL b
     (IMPLIES (IS-IDEAL s I) (IMPLIES (IN b I)
       (FORALL x (IMPLIES (IN x (PRINCIPAL-IDEAL s b)) (IN x I)))))))))
(warrant! 'principal-ideal-in-ideal 'proof
  "x in (b) gives x = r.b for some r in A (principal-ideal-membership); IS-IDEAL's multiplicative-absorption conjunct then puts r.b in I.")

;;; euclidean-ideal-has-generator: THE mathematical core.  Every ideal of a
;;; Euclidean ring has a generator b in I with I subset (b) -- i.e. every
;;; element of I is a multiple of b.  (Combined with principal-ideal-in-ideal
;;; this gives I = (b).)
;;; It used to be ASSERTED here with a 'proof warrant whose text was the proof
;;; sketch.  It is now PROVEN, in theorem-library/euclidean-ideal-generator-proof.scm:
;;; the sketch's "choose a nonzero b of least degree" is one `minimize!' call
;;; (minimize.scm), and the rest is Euclidean division plus ideal closure.
;;; The proof uses no choice -- see minimize.scm on why well-ordering a SEP set
;;; hands back the witness without it.
