;;; list-recursion.scm -- CONS, and the recursive characterization of LENGTH.
;;;
;;; WHY THIS FILE EXISTS.  library.scm gave TUPLES three axioms -- `length-of-empty',
;;; `length-in-nn', `nth-in-range' -- and then said, in a comment beside them
;;; (library.scm:637):
;;;
;;;   (Recursive characterization of length requires a CONS/PREPEND constructor
;;;    and a TUPLES induction principle, both pending.)
;;;
;;; Both were still pending, and the cost was paid one literal at a time.
;;; `theorem-library/makeset-basics.scm' writes the two-element case out by hand
;;; -- ms-index-2, ms-nth-2, makeset2-membership, makeset2-split, card-pair --
;;; and its header says why: a general law "wants a LIST recursion the theory
;;; does not have".  So `card({a,b})' is a theorem and `card({a,b,c})' is not,
;;; and the ladder would have to be climbed again for every arity.
;;;
;;; This file supplies the missing constructor and the missing generation
;;; principle.  The induction principle is NOT asserted here: it is PROVEN, in
;;; theorem-library/tuples-induction.scm, from these axioms and `nn-induction'
;;; by induction on the length.  That is the point of stating generation rather
;;; than induction -- the two say the same thing about TUPLES, but generation is
;;; a concrete decomposition that an existing induction principle can consume,
;;; and it leaves the tree with one fewer asserted induction schema.
;;;
;;; WHAT IS DEFINITIONAL AND WHAT IS ASSERTED, and the line between them:
;;;
;;;   definitional -- the four equations that say what CONS DOES.  CONS is a new
;;;     head; equations constraining a new symbol add no consequence about the
;;;     old vocabulary, exactly as `binary-minus-def' (number-systems.scm) adds
;;;     none about `-'.  They pin CONS down to the extent tuples are pinned down
;;;     by their length and their entries, which is what the kernel's
;;;     `tuple-equality-decompose' rule takes a tuple to be.
;;;
;;;   asserted + warrant! -- the two GENERATION axioms, which are claims about
;;;     TUPLES, not about CONS: that the only tuple of length 0 is the empty one,
;;;     and that every longer tuple is a CONS.  Together they say TUPLES(A) is
;;;     generated by [] and CONS, which is the content of "a tuple is a FINITE
;;;     sequence".  A case can be made that this is what TUPLES *is* and belongs
;;;     on the primitive shelf beside the ordinal axioms; that is a foundational
;;;     decision and is left to the user rather than taken here.  Until it is
;;;     taken, every proof by list induction will carry these two in its bill,
;;;     which is the honest report.
;;;
;;; The typing axioms (`empty-in-tuples', `cons-in-tuples') are the closure
;;; facts any constructor owes and are stamped `definitional' with the
;;; equations: they say CONS lands where its arguments came from.

;;; -----------------------------------------------------------------------
;;; The defining equations of CONS.
;;;
;;; CONS x L is the tuple whose first entry is x and whose remaining entries are
;;; those of L.  NTH is 1-based here, as everywhere in the tree (`nth-in-range'
;;; guards 1 <= i <= LENGTH L), so the entry equations split at index 1.
;;; -----------------------------------------------------------------------

(fluid-let ((*current-provenance* 'definitional))

  ;; [] is a tuple over anything; CONS lands back in TUPLES(A).
  (add-axiom! *library* 'empty-in-tuples
    '(FORALL A (IN (LIST) (TUPLES A))))

  (add-axiom! *library* 'cons-in-tuples
    '(FORALL A (FORALL x (FORALL L
        (IMPLIES (AND (IN x A) (IN L (TUPLES A)))
                 (IN (CONS x L) (TUPLES A)))))))

  ;; length(cons(x,L)) = succ(length(L))  -- the recursion the file is named for.
  (add-axiom! *library* 'length-cons
    '(FORALL x (FORALL L (= (LENGTH (CONS x L)) (succ (LENGTH L))))))

  ;; The head, and the shift on the tail.
  (add-axiom! *library* 'nth-cons-1
    '(FORALL x (FORALL L (= (NTH 1 (CONS x L)) x))))

  (add-axiom! *library* 'nth-cons-succ
    '(FORALL i (FORALL x (FORALL L
        (IMPLIES (AND (IN i NN) (AND (<= 1 i) (<= i (LENGTH L))))
                 (= (NTH (succ i) (CONS x L)) (NTH i L)))))))

  ;; The bridge to brace notation: {x} u {the rest}.  PAIR x x is the singleton,
  ;; written that way to match `card-insert' (cardinality.scm), which is what
  ;; every cardinality argument over a literal set will meet next.
  (add-axiom! *library* 'makeset-cons
    '(FORALL x (FORALL L
        (= (MAKE-SET (CONS x L))
           (UNION (PAIR x x) (MAKE-SET L))))))

  )   ; end definitional

;;; -----------------------------------------------------------------------
;;; Generation: TUPLES(A) is generated by [] and CONS.
;;;
;;; These two are the claims about TUPLES.  Stated as a decomposition rather
;;; than as an induction schema, so that `nn-induction' can do the induction:
;;; see theorem-library/tuples-induction.scm, where the schema is derived.
;;;
;;; THEY ARE FOUNDATIONAL, and are installed as such (user's decision,
;;; 2026-09-15).  Both were asserted PSS supports whose own warrants nominated
;;; them for this shelf; they are now `primitive' provenance (proof-debt.scm:12,
;;; the trusted-base tier that contributes {} to every bill), beside the ordinal
;;; axioms (ordinals.scm) and replacement (injection.scm).
;;;
;;; THE CLAIM THE STAMP MAKES, written down because a `primitive' fact is
;;; invisible to the debt ledger: that TUPLES(A) contains NOTHING BUT the
;;; finite sequences over A -- every tuple of length 0 is [], and every tuple
;;; of length succ n is a CONS onto a tuple of length n.  That is the content
;;; of "a tuple is a finite sequence", and nothing else in this tree says it:
;;; TUPLES has no other defining characterisation, so these are not facts the
;;; library could owe an argument for -- they are what the constructor means.
;;; The test CLAUDE.md sets for the shelf is whether a mathematician would
;;; answer "because that is what a finite sequence is"; here they would.
;;;
;;; They are NOT `warrant!'s.  A warrant moves a fact from `none' to
;;; `well-known' -- a better tier of DEBT; `primitive' says it is not debt.
;;; Note the one thing the stamp does NOT license: it says tuples are generated
;;; by [] and CONS, and says nothing about whether a given class IS a TUPLES.
;;; -----------------------------------------------------------------------

(fluid-let ((*current-provenance* 'primitive))

(add-axiom! *library* 'tuple-length-zero
  '(FORALL A (FORALL L
      (IMPLIES (AND (IN L (TUPLES A)) (= (LENGTH L) 0))
               (= L (LIST))))))


(add-axiom! *library* 'tuple-cons-decompose
  '(FORALL A (FORALL n (FORALL L
      (IMPLIES (AND (IN n NN) (AND (IN L (TUPLES A)) (= (LENGTH L) (succ n))))
               (FORSOME x (AND (IN x A)
                               (FORSOME M (AND (IN M (TUPLES A))
                                               (AND (= (LENGTH M) n)
                                                    (= L (CONS x M))))))))))))


)   ; end (fluid-let ((*current-provenance* 'primitive)) ...) -- 2 axioms

(topic! 'tuple-length-zero 'combinatorial)
(topic! 'tuple-cons-decompose 'combinatorial)
