;;; measure.scm -- OUTER MEASURES, CARATHEODORY MEASURABILITY, MEASURES.
;;; Vocabulary plus the statements of the Caratheodory construction.  Nothing
;;; here is proved; every asserted fact carries a warrant naming the numbered
;;; result and page it comes from.
;;;
;;; SOURCES.  Thayer, Construction of Measures: Def. 1.15 (countably additive
;;; measure, p. 4), Def. 1.16 (measure space, p. 4), Prop. 1.17 / 1.18
;;; (continuity from below / above, pp. 4-5), Sec. 1.4 (measurable mappings,
;;; p. 5), Def. 1.9 (the sigma-algebra generated by a family, p. 2), and all of
;;; Chapter 4, Sec. 1: Def. 4.1 (outer measure, p. 30), Def. 4.2 (mu*-measurable
;;; set, p. 30), Remark 4.3 (null sets are measurable, p. 30), Prop. 4.4 (the
;;; Caratheodory theorem, pp. 30-32).  Rudin, Real and Complex Analysis:
;;; Def. 1.3 (sigma-algebra and measurable mapping, p. 8), Thm. 1.10 (generated
;;; sigma-algebra, p. 12), Def. 1.18 (positive measure, p. 16), Thm. 1.19
;;; (elementary properties, p. 17).
;;;
;;; WHICH SOURCE VNB FOLLOWS, AND WHERE THEY DIFFER.
;;;
;;;   * THE APPROACH is Caratheodory's -- outer measure first, the measurable
;;;     sets carved out of it by the splitting condition.  That is Thayer
;;;     Chapter 4 and Munroe's whole book.  RUDIN DOES NOT DO THIS: his
;;;     Chapter 1 takes a measure on a sigma-algebra as given and builds
;;;     Lebesgue measure in Chapter 2 by the Riesz representation theorem.  So
;;;     the Caratheodory statements below cite Thayer alone; there is no Rudin
;;;     number to give and saying so is more useful than inventing one.
;;;
;;;   * mu(EMPTY-SET) = 0 IS PART OF THE DEFINITION of a measure here, as in
;;;     Thayer Def. 1.15.  Rudin Def. 1.18 does not put it in the definition:
;;;     he assumes instead that mu(A) is finite for at least one A and DERIVES
;;;     mu(empty) = 0 as Thm. 1.19(a).  VNB follows Thayer, so the reader should
;;;     not expect `measure-empty' to appear as a citable consequence.
;;;
;;;   * "COUNTABLE" is rendered as a union or sum over a SEQUENCE -- a function
;;;     in FUN(NN, ...) applied by juxtaposition, unioned with BIG-UNION and
;;;     summed with ESUM.  This is exactly the idiom sigma-algebra.scm settled
;;;     on, and it is how both sources write countable operations.  Repetitions
;;;     are admitted, so finite and empty subfamilies are covered too and no
;;;     separate countability predicate is needed.
;;;
;;;   * A PREIMAGE is written as a SEP, not with the PREIMAGE head: PREIMAGE
;;;     (metric-open-sets.scm) reads a topological/metric STRUCTURE for its
;;;     point set, and a measurable space is not one of those.  The SEP form
;;;     { x in omega : f(x) in b } is the same set and needs no bridge.
;;;
;;; ARGUMENT ORDER.  Ambient set first, then the structure over it, then the
;;; object -- IS-SIGMA-ALGEBRA(omega, cA) is the pattern, and
;;; IS-MEASURE(omega, cA, mu) and IS-CARATHEODORY-MEASURABLE(omega, mu, es)
;;; extend it.  An outer measure needs no sigma-algebra (it is defined on ALL
;;; of POWER(omega)), so IS-OUTER-MEASURE has only the two arguments.
;;;
;;; NOT STATED (deliberately): monotone classes and the monotone class theorem
;;; (Thayer Def. 1.12, Thm. 1.13); the push-forward of a measure (Prop. 1.19,
;;; p. 6) and its functoriality; the pull-back (Prop. 1.22, p. 6); completion
;;; of a measure and product measures (Chapter 3); metric outer measures and
;;; Hausdorff measure (Chapter 4, Secs. 3-4).  Each is a clean statement in
;;; this vocabulary and none is needed by the integral, which is the next rung.
;;;
;;; Dependencies: sigma-algebra.scm (IS-SIGMA-ALGEBRA), extended-reals-pos.scm
;;; (RR-POS-STAR, ESUP, eplus), extended-arith.scm (EINF), compose.scm (COMPOSE),
;;; injection.scm (IMAGE), theorem-library/extended-sum.scm (ESUM),
;;; theorem-library/prod-of-sums.scm (DIFFERENCE), and the kernel (POWER, SEP,
;;; BIG-UNION, RES, FUN, NN, EMPTY-SET).
;;; ====================================================================

;;; -----------------------------------------------------------------------
;;; SIGMA-GENERATED(omega, cE) -- the sigma-algebra generated by a family.
;;;
;;; Thayer Def. 1.9 (p. 2) and Rudin Thm. 1.10 (p. 12) both define it as the
;;; SMALLEST sigma-algebra containing cE, and both justify the definition by
;;; the observation that an intersection of sigma-algebras is one.  VNB writes
;;; that intersection directly, as separation over POWER(omega): a is in the
;;; generated algebra exactly when it lies in EVERY sigma-algebra on omega that
;;; contains cE.  POWER(omega) is itself such a sigma-algebra, so the family
;;; quantified over is never empty and the definition is not vacuous.

(def-functoid 'SIGMA-GENERATED '(omega cE)
  '(SEP a_ (POWER omega)
     (FORALL cB_
       (IMPLIES (AND (IS-SIGMA-ALGEBRA omega cB_) (SUBSET cE cB_))
                (IN a_ cB_)))))

;;; The membership law.  `def-functoid' installs only a rewrite macete, so
;;; `mac-h' cannot unfold SIGMA-GENERATED in an ASSUMPTION; a constructor whose
;;; members get read out of the context needs the membership iff stated beside
;;; it.  It is the functoid unfold composed with the SEP separation schema,
;;; both trusted base -- exactly the iff `def-predicate' would have generated
;;; had this been a predicate -- so it is stamped `definitional' and costs
;;; nothing.  Same treatment and same reasoning as span-membership (mod-seq.scm)
;;; and principal-ideal-membership (ideal.scm).
(fluid-let ((*current-provenance* 'definitional))
  (theory-add-axiom! *current-theory* 'sigma-generated-membership
    '(FORALL omega (FORALL cE (FORALL a_
       (IFF (IN a_ (SIGMA-GENERATED omega cE))
            (AND (IN a_ (POWER omega))
                 (FORALL cB_
                   (IMPLIES (AND (IS-SIGMA-ALGEBRA omega cB_) (SUBSET cE cB_))
                            (IN a_ cB_))))))))))

(notation! 'SIGMA-GENERATED 'kind 'functoid 'arity 2
           'english "the sigma-algebra of subsets of $1 generated by $2")

;;; -----------------------------------------------------------------------
;;; IS-OUTER-MEASURE(omega, mu) -- Thayer Def. 4.1 (p. 30).
;;;
;;; mu is defined on ALL of POWER(omega) -- that is the point of an outer
;;; measure -- takes values in [0,+inf], vanishes on the empty set, is monotone,
;;; and is countably subadditive.  The three numbered clauses of Def. 4.1 are
;;; the last three conjuncts, in the source's order.

(def-predicate 'IS-OUTER-MEASURE '(omega mu)
  (conjuncts->and
    (list
      '(IN omega SET)
      '(IN mu (FUN (POWER omega) RR-POS-STAR))
      '(= (mu EMPTY-SET) 0)                                ; Def. 4.1(1)
      (forall-guarded '(a_ b_)                             ; Def. 4.1(2)
                      '((IN a_ (POWER omega))
                        (IN b_ (POWER omega))
                        (SUBSET a_ b_))
        '(<= (mu a_) (mu b_)))
      (forall-guarded '(f_)                                ; Def. 4.1(3)
                      '((IN f_ (FUN NN (POWER omega))))
        '(<= (mu (BIG-UNION n_ NN (f_ n_)))
             (ESUM (VNB-LAMBDA n_ NN (mu (f_ n_)))))))))

(notation! 'IS-OUTER-MEASURE 'kind 'predicate 'arity 2
           'english "$2 is an outer measure on $1")

;;; -----------------------------------------------------------------------
;;; IS-CARATHEODORY-MEASURABLE(omega, mu, es) -- Thayer Def. 4.2, Eq. (74),
;;; p. 30: es splits every test set additively.
;;;
;;; The parameter is named `es' rather than the source's E: single capitals are
;;; the case-fold danger zone in this tree, and `e' would read as a bare symbol
;;; in every printed instance of the definition.
;;;
;;; The test set a_ ranges over POWER(omega) -- the source says "for every
;;; A subset of X", and mu is defined exactly there.  A \ E is the DIFFERENCE
;;; head (difference-membership, prod-of-sums.scm); the addition is `eplus',
;;; since both summands live in [0,+inf] and either may be +inf.

(def-predicate 'IS-CARATHEODORY-MEASURABLE '(omega mu es)
  (conjuncts->and
    (list
      '(SUBSET es omega)
      (forall-guarded '(a_) '((IN a_ (POWER omega)))
        '(= (mu a_)
            (eplus (mu (INTERSECTION a_ es)) (mu (DIFFERENCE a_ es))))))))

(notation! 'IS-CARATHEODORY-MEASURABLE 'kind 'predicate 'arity 3
           'english "$3 is Caratheodory measurable for the outer measure $2 on $1")

;;; -----------------------------------------------------------------------
;;; CARATHEODORY-SETS(omega, mu) -- the class A of Thayer Prop. 4.4 (p. 30):
;;; the mu-measurable subsets of omega.

(def-functoid 'CARATHEODORY-SETS '(omega mu)
  '(SEP es_ (POWER omega) (IS-CARATHEODORY-MEASURABLE omega mu es_)))

;;; Membership law -- same status and same reasoning as
;;; sigma-generated-membership above: the SEP read-off, stamped definitional.
(fluid-let ((*current-provenance* 'definitional))
  (theory-add-axiom! *current-theory* 'caratheodory-sets-membership
    '(FORALL omega (FORALL mu (FORALL es_
       (IFF (IN es_ (CARATHEODORY-SETS omega mu))
            (AND (IN es_ (POWER omega))
                 (IS-CARATHEODORY-MEASURABLE omega mu es_))))))))

(notation! 'CARATHEODORY-SETS 'kind 'functoid 'arity 2
           'english "the $2-measurable subsets of $1")

;;; -----------------------------------------------------------------------
;;; IS-MEASURE(omega, cA, mu) -- Thayer Def. 1.15 (p. 4) together with
;;; Def. 1.16 (p. 4): the triple (X, A, mu) is a measure space.
;;;
;;; Countable additivity is stated over a sequence of PAIRWISE DISJOINT members
;;; of cA, exactly as the source writes it.  Disjointness is the explicit
;;; i /= j clause; nothing forces the terms distinct, so a sequence that is
;;; eventually empty is admitted and finite additivity is a special case.

(def-predicate 'IS-MEASURE '(omega cA mu)
  (conjuncts->and
    (list
      '(IS-SIGMA-ALGEBRA omega cA)
      '(IN mu (FUN cA RR-POS-STAR))
      '(= (mu EMPTY-SET) 0)                                ; Def. 1.15, Eq. (5)
      (forall-guarded '(f_)                                ; Def. 1.15, Eq. (6)
                      (list '(IN f_ (FUN NN cA))
                            (forall-guarded '(i_ j_)
                                            '((IN i_ NN) (IN j_ NN) (NOT (= i_ j_)))
                              '(= (INTERSECTION (f_ i_) (f_ j_)) EMPTY-SET)))
        '(= (mu (BIG-UNION n_ NN (f_ n_)))
            (ESUM (VNB-LAMBDA n_ NN (mu (f_ n_)))))))))

(notation! 'IS-MEASURE 'kind 'predicate 'arity 3
           'english "$3 is a countably additive measure on the sigma-algebra $2 of subsets of $1")

;;; -----------------------------------------------------------------------
;;; IS-MEASURABLE-MAP(omega, cA, omega2, cB, f) -- Thayer Sec. 1.4 (p. 5),
;;; Rudin Def. 1.3(c) (p. 8): a map between measurable spaces whose preimages
;;; of measurable sets are measurable.
;;;
;;; This is the GENERAL definition, and it is here so that the [0,+inf]-valued
;;; predicate IS-MEASURABLE-FN (integral.scm) has an honest anchor to be
;;; compared against.  IS-MEASURABLE-FN is NOT an instance of it, and cannot be
;;; made one: it would need a sigma-algebra on RR-POS-STAR, i.e. a POWER(RR-POS-STAR), and
;;; RR-POS-STAR has no sethood fact in this tree (extended-reals.scm asserts none for
;;; RR-STAR).  See the note at IS-MEASURABLE-FN.

(def-predicate 'IS-MEASURABLE-MAP '(omega cA omega2 cB f)
  (conjuncts->and
    (list
      '(IS-SIGMA-ALGEBRA omega cA)
      '(IS-SIGMA-ALGEBRA omega2 cB)
      '(IN f (FUN omega omega2))
      (forall-guarded '(b_) '((IN b_ cB))
        '(IN (SEP x_ omega (IN (f x_) b_)) cA)))))

(notation! 'IS-MEASURABLE-MAP 'kind 'predicate 'arity 5
           'english "$5 is a measurable map from $1 with $2 to $3 with $4")

;;; =====================================================================
;;; THEOREMS.  Nothing below is proved here.  Each is a `support' with a
;;; `reference' warrant naming the result and the page, and a `gloss!' giving
;;; the statement in words.  Where the VNB statement is not literally the
;;; source's, the gloss says so and says why.

;;; -----------------------------------------------------------------------
;;; The generated sigma-algebra IS one.

(support 'sigma-generated-is-sigma-algebra
  (forall-guarded '(omega cE)
                  '((IN omega SET) (SUBSET cE (POWER omega)))
    '(IS-SIGMA-ALGEBRA omega (SIGMA-GENERATED omega cE))))

(warrant! 'sigma-generated-is-sigma-algebra 'reference '(rudin-rca "Thm. 1.10" 27))
(topic!   'sigma-generated-is-sigma-algebra 'set-quotient)
(gloss!   'sigma-generated-is-sigma-algebra
  "For any family cE of subsets of a set omega there is a smallest
   sigma-algebra on omega containing cE, namely SIGMA-GENERATED(omega, cE).
   Rudin Thm. 1.10 (p. 12) and Thayer Def. 1.9 (p. 2) state it as the
   existence of a smallest such sigma-algebra; VNB has already NAMED that
   object by the intersection formula, so what is left to assert is only that
   the named object satisfies IS-SIGMA-ALGEBRA.  Its leastness -- that it is
   contained in every sigma-algebra on omega containing cE -- is not asserted
   separately: it is one instantiation of sigma-generated-membership.")

;;; -----------------------------------------------------------------------
;;; The Caratheodory construction.  Thayer Chapter 4, Sec. 1.  Rudin has no
;;; counterpart in Chapter 1 -- see the header.

(support 'caratheodory-measurable-sigma-algebra
  (forall-guarded '(omega mu) '((IS-OUTER-MEASURE omega mu))
    '(IS-SIGMA-ALGEBRA omega (CARATHEODORY-SETS omega mu))))

(warrant! 'caratheodory-measurable-sigma-algebra 'reference
          '(thayer-measures "Prop. 4.4" 36))
(topic!   'caratheodory-measurable-sigma-algebra 'set-quotient)
(gloss!   'caratheodory-measurable-sigma-algebra
  "Caratheodory's theorem, first half: the sets that split every test set
   additively for an outer measure mu form a sigma-algebra on omega.  Thayer
   Prop. 4.4 (p. 30) states both halves in one sentence ('the mu* measurable
   sets form a (non-empty) sigma-algebra A and mu*|A is a countably additive
   measure'); VNB splits it into this and caratheodory-measure, because the
   two conclusions are about different objects and a proof will want them
   separately.  Rudin does not carry the Caratheodory construction in
   Chapter 1, so no Rudin number is given.")

(support 'caratheodory-measure
  (forall-guarded '(omega mu) '((IS-OUTER-MEASURE omega mu))
    '(IS-MEASURE omega
                 (CARATHEODORY-SETS omega mu)
                 (RES mu (CARATHEODORY-SETS omega mu)))))

(warrant! 'caratheodory-measure 'reference '(thayer-measures "Prop. 4.4" 36))
(topic!   'caratheodory-measure 'set-quotient)
(gloss!   'caratheodory-measure
  "Caratheodory's theorem, second half: the restriction of the outer measure
   mu to the sigma-algebra of its measurable sets is a countably additive
   measure.  Thayer Prop. 4.4 (p. 30), written there as mu*|A; VNB writes the
   restriction with the kernel's RES head.  See
   caratheodory-measurable-sigma-algebra for why the source's one statement is
   two here.")

(support 'caratheodory-null-measurable
  (forall-guarded '(omega mu es)
                  '((IS-OUTER-MEASURE omega mu)
                    (SUBSET es omega)
                    (= (mu es) 0))
    '(IS-CARATHEODORY-MEASURABLE omega mu es)))

(warrant! 'caratheodory-null-measurable 'reference
          '(thayer-measures "Remark 4.3" 36))
(topic!   'caratheodory-null-measurable 'set-quotient)
(gloss!   'caratheodory-null-measurable
  "Every set of outer measure zero is Caratheodory measurable.  Thayer
   Remark 4.3 (p. 30), stated there as 'every set E such that mu*(E) = 0 is
   measurable'; VNB adds the explicit hypothesis that es is a subset of omega,
   which the source carries implicitly by working inside P(X).")

(support 'caratheodory-superadditive-suffices
  (forall-guarded '(omega mu es)
                  (list '(IS-OUTER-MEASURE omega mu)
                        '(SUBSET es omega)
                        (forall-guarded '(a_) '((IN a_ (POWER omega)))
                          '(<= (eplus (mu (INTERSECTION a_ es))
                                      (mu (DIFFERENCE a_ es)))
                               (mu a_))))
    '(IS-CARATHEODORY-MEASURABLE omega mu es)))

(warrant! 'caratheodory-superadditive-suffices 'reference
          '(thayer-measures "Eq. (75), following Def. 4.2" 36))
(topic!   'caratheodory-superadditive-suffices 'set-quotient)
(gloss!   'caratheodory-superadditive-suffices
  "Only one of the two inequalities has to be checked: if the two pieces of
   every test set together weigh AT MOST the test set, then es is Caratheodory
   measurable, the reverse inequality being automatic from subadditivity.
   Thayer states this as the displayed inequality (75) in the paragraph after
   Def. 4.2 (p. 30) -- an unnumbered remark, so the citation is to the
   equation, not to a numbered result.  This is the working form of the
   measurability test and the reason it is stated at all.")

(support 'outer-measure-binary-subadditive
  (forall-guarded '(omega mu a_ b_)
                  '((IS-OUTER-MEASURE omega mu)
                    (IN a_ (POWER omega))
                    (IN b_ (POWER omega)))
    '(<= (mu (UNION a_ b_)) (eplus (mu a_) (mu b_)))))

(warrant! 'outer-measure-binary-subadditive 'reference
          '(thayer-measures "Def. 4.1(3)" 36))
(topic!   'outer-measure-binary-subadditive 'inequalities)
(gloss!   'outer-measure-binary-subadditive
  "An outer measure is subadditive on PAIRS: mu(a union b) <= mu(a) + mu(b).
   NOT literally the source's statement -- Def. 4.1(3) (p. 30) states COUNTABLE
   subadditivity, over a sequence.  The binary case is the instance whose
   sequence is a, b, empty, empty, ... , and it is stated separately because
   the countable form cannot be used on two sets without first building that
   sequence.  Both sources use the binary form silently (Thayer does so in the
   very next paragraph, to get inequality (75)).")

;;; -----------------------------------------------------------------------
;;; Elementary properties of a measure.  Rudin Thm. 1.19 (p. 17) is the list;
;;; Thayer proves the two continuity statements as Prop. 1.17 and 1.18.

(support 'measure-monotone
  (forall-guarded '(omega cA mu a_ b_)
                  '((IS-MEASURE omega cA mu)
                    (IN a_ cA)
                    (IN b_ cA)
                    (SUBSET a_ b_))
    '(<= (mu a_) (mu b_))))

(warrant! 'measure-monotone 'reference '(rudin-rca "Thm. 1.19(c)" 32))
(topic!   'measure-monotone 'inequalities)
(gloss!   'measure-monotone
  "A measure is monotone: a subset of a measurable set has no larger measure.
   Rudin Thm. 1.19(c), p. 17.  Thayer states the same fact without a number,
   using it from Chapter 1 onward.")

(support 'measure-finitely-additive
  (forall-guarded '(omega cA mu a_ b_)
                  '((IS-MEASURE omega cA mu)
                    (IN a_ cA)
                    (IN b_ cA)
                    (= (INTERSECTION a_ b_) EMPTY-SET))
    '(= (mu (UNION a_ b_)) (eplus (mu a_) (mu b_)))))

(warrant! 'measure-finitely-additive 'reference '(rudin-rca "Thm. 1.19(b)" 32))
(topic!   'measure-finitely-additive 'plumbing)
(gloss!   'measure-finitely-additive
  "A measure is additive on two disjoint measurable sets.  Rudin
   Thm. 1.19(b), p. 17, which states the n-term form; VNB states the BINARY
   case, since the n-term form needs a finite family and follows from this one
   by induction.  Both sources derive it from countable additivity by padding
   the sequence with empty sets.")

(support 'measure-countably-subadditive
  (forall-guarded '(omega cA mu f_)
                  '((IS-MEASURE omega cA mu)
                    (IN f_ (FUN NN cA)))
    '(<= (mu (BIG-UNION n_ NN (f_ n_)))
         (ESUM (VNB-LAMBDA n_ NN (mu (f_ n_)))))))

(warrant! 'measure-countably-subadditive 'well-known
  "Countable subadditivity of a measure -- countable additivity applied to the
   disjointified sequence B_1 = A_1, B_k = A_k \\ (A_1 union ... union A_{k-1}),
   which has the same union and termwise smaller measure by monotonicity.
   Neither source gives it a number: Thayer uses it unnumbered in the proof of
   Prop. 2.9 (p. 10) and Rudin's Thm. 1.19 list stops at continuity from
   above.  `well-known' rather than `reference' precisely because there is no
   numbered result to point at.")
(topic!   'measure-countably-subadditive 'inequalities)
(gloss!   'measure-countably-subadditive
  "The measure of a countable union is at most the sum of the measures, the
   terms not being assumed disjoint.")

(support 'measure-continuity-from-below
  (forall-guarded '(omega cA mu f_)
                  (list '(IS-MEASURE omega cA mu)
                        '(IN f_ (FUN NN cA))
                        (forall-guarded '(n_) '((IN n_ NN))
                          '(SUBSET (f_ n_) (f_ (succ n_)))))
    '(= (mu (BIG-UNION n_ NN (f_ n_)))
        (ESUP (IMAGE (VNB-LAMBDA n_ NN (mu (f_ n_))) NN)))))

(warrant! 'measure-continuity-from-below 'reference
          '(thayer-measures "Prop. 1.17" 10))
(topic!   'measure-continuity-from-below 'analysis)
(gloss!   'measure-continuity-from-below
  "For a non-decreasing sequence of measurable sets, the measure of the union
   is the supremum of the measures.  Thayer Prop. 1.17 (p. 4), Eq. (7), which
   writes exactly sup_k mu(A_k); Rudin Thm. 1.19(d) (p. 17) writes the same
   fact as mu(A_n) -> mu(A), a LIMIT.  VNB follows Thayer, because the
   supremum is available directly in RR-POS-STAR (ESUP over the image of the sequence)
   whereas a limit in [0,+inf] would first have to be defined.")

;;; Continuity from above.  The kernel has BIG-UNION and no dual binder, so the
;;; countable INTERSECTION is written the way Thayer writes it in the remark
;;; after Def. 1.7 (p. 2) and again in the proof of Prop. 1.18:
;;; intersection_i A_i = X \ union_i (X \ A_i).

(support 'measure-continuity-from-above
  (forall-guarded '(omega cA mu f_)
                  (list '(IS-MEASURE omega cA mu)
                        '(IN f_ (FUN NN cA))
                        (forall-guarded '(n_) '((IN n_ NN))
                          '(SUBSET (f_ (succ n_)) (f_ n_)))
                        '(IN (mu (f_ 0)) RR))
    '(= (mu (COMPLEMENT-IN omega (BIG-UNION n_ NN (COMPLEMENT-IN omega (f_ n_)))))
        (EINF (IMAGE (VNB-LAMBDA n_ NN (mu (f_ n_))) NN)))))

(warrant! 'measure-continuity-from-above 'reference
          '(thayer-measures "Prop. 1.18" 11))
(topic!   'measure-continuity-from-above 'analysis)
(gloss!   'measure-continuity-from-above
  "For a non-increasing sequence of measurable sets whose FIRST term has
   finite measure, the measure of the intersection is the infimum of the
   measures.  Thayer Prop. 1.18 (p. 5), Eq. (9), which writes inf_k mu(A_k);
   Rudin Thm. 1.19(e) (p. 17) writes it as a limit.  Two divergences, both
   forced by the kernel and neither mathematical: the countable intersection
   is spelled omega \\ union_n (omega \\ A_n), there being no countable
   intersection binder; and the finiteness hypothesis is placed on the term of
   index 0, the sources indexing their sequences from 1.  The hypothesis is
   not decorative -- Thayer's paragraph before Prop. 1.18 says in as many
   words that the statement fails without it.")

;;; -----------------------------------------------------------------------
;;; Measurable maps compose.

(support 'measurable-map-compose
  (forall-guarded '(omega cA omega2 cB omega3 cC f g)
                  '((IS-MEASURABLE-MAP omega cA omega2 cB f)
                    (IS-MEASURABLE-MAP omega2 cB omega3 cC g))
    '(IS-MEASURABLE-MAP omega cA omega3 cC (COMPOSE g f))))

(warrant! 'measurable-map-compose 'reference '(thayer-measures "Sec. 1.4" 11))
(topic!   'measurable-map-compose 'plumbing)
(gloss!   'measurable-map-compose
  "The composition of two measurable maps is measurable.  Thayer states it in
   the opening paragraph of Sec. 1.4 (p. 5) -- an unnumbered display, so the
   citation is to the section.  COMPOSE(g, f) is the VNB functoid
   (compose.scm), i.e. x |-> g(f(x)); note the source writes the composite in
   the opposite order in its displayed identity; VNB states the version that
   matches the typings, f from omega to omega2 and g from omega2 to omega3.")

;;; -----------------------------------------------------------------------
;;; NOT STATED, and why -- the honest end of this file.
;;;
;;;   * The push-forward of a measure by a measurable map (Thayer Prop. 1.19,
;;;     p. 6) and its functoriality (Eq. (11)); the pull-back along a
;;;     surjection (Prop. 1.22, p. 6).  Both state cleanly in this vocabulary;
;;;     neither is on the path to the integral, which is the next rung.
;;;   * Monotone classes and the monotone class theorem (Thayer Def. 1.12,
;;;     Thm. 1.13, p. 3).
;;;   * The construction of an outer measure from a set function on a covering
;;;     class (Thayer Chapter 4, Sec. 2, p. 32; Munroe's Method I), which is
;;;     what turns Caratheodory's theorem into LEBESGUE measure.  It needs an
;;;     infimum over countable covers -- EINF plus a SEP over sequences -- and
;;;     is the obvious next file.
;;;   * Vitali's theorem, that no translation-invariant countably additive
;;;     measure is defined on all subsets of RR (Thayer Prop. 1.23, p. 7).
;;;     Statable, but it needs translation on RR as an operation on SETS,
;;;     which nothing in the tree provides.
