;;; pseudometric.scm -- PSEUDOMETRIC-SPACE, the topology GENERATED by a countable
;;; family of pseudometrics (the gauge topology), and the metrizability cluster
;;; T2/T3/T4 stated as warranted PSS supports.
;;;
;;; A pseudometric is a metric that need NOT separate points (d(x,y)=0 is allowed
;;; for x /= y): the `is-pseudometric' property is `is-metric' minus
;;; identity-of-indiscernibles (operation-properties.scm).  PSEUDOMETRIC-SPACE
;;; reuses the METRIC-SPACE slots PTS (carrier) and DIST (distance), as the
;;; one-name-one-slot rule requires -- a metric space IS a pseudometric space that
;;; additionally separates.
;;;
;;; The gauge topology of a COUNTABLE family {d_n : n in NN} of pseudometrics on a
;;; common carrier: U is open iff around every point y in U some BASIC neighbourhood
;;;    { x : d_n(y,x) < r  for all n <= k }
;;; (control the first k pseudometrics to within r) lies inside U.  This is the
;;; standard countable-gauge basis; it needs no arbitrary finite intersections,
;;; only a bound k in NN.  PSEUDO-GAUGE-TOP packages it as a TOP-SPACE exactly as
;;; METRIC-TOP packages a metric's open sets.
;;;
;;; These are the heads that let the (c)-conditions of the metrizability cluster be
;;; STATED.  T2/T3/T4 are warranted supports, not VNB proofs -- the deliverable is
;;; the vocabulary and the honest statements; proving them (in particular the
;;; sum-metric d = SUM 2^-n d_n/(1+d_n) for (c)=>(a)) is the stress payload.
;;;
;;; Loads after top-space (IS-METRIZABLE-TOP-SPACE, METRIC-TOP, IS-HAUSDORFF) and
;;; bounded-metric (IS-BOUNDED-METRIC-SPACE).

;;; -----------------------------------------------------------------------
;;; The structure.  Same shape as METRIC-SPACE, weaker property.

(declare-structure PSEUDOMETRIC-SPACE
  (carriers PTS)
  (op DIST (CARTESIAN PTS PTS) RR)
  (property is-pseudometric DIST PTS))
(notation! 'IS-PSEUDOMETRIC-SPACE 'noun "pseudometric space" 'article "a")

;;; -----------------------------------------------------------------------
;;; A countable family of pseudometrics sharing one carrier (the parameter `ground'):
;;; a map on NN whose n-th value is a pseudometric space whose PTS is `ground'.
;;; (Countable = indexed by NN.)  Note `ground' is an ordinary bound variable, NOT the
;;; carrier accessor CARR.

(def-predicate 'IS-COUNTABLE-PSEUDOMETRIC-FAMILY '(fam ground)
  (forall-guarded '(n_) '((IN n_ NN))
    (conjuncts->and
      (list '(IS-PSEUDOMETRIC-SPACE (fam n_))
            '(== (PTS (fam n_)) ground)))))
(notation! 'IS-COUNTABLE-PSEUDOMETRIC-FAMILY 'kind 'predicate 'arity 2
           'english "$1 is a countable family of pseudometrics on $2")

;;; -----------------------------------------------------------------------
;;; IS-OPEN-GAUGE(fam, ground, U): U is open in the gauge topology of the family --
;;; every point of U carries a basic neighbourhood (first k pseudometrics within r)
;;; contained in U.  Points are y/x, the pseudometric index is n_, the bound k_.

(def-predicate 'IS-OPEN-GAUGE '(fam ground U)
  (conjuncts->and
    (list
      '(SUBSET U ground)
      (forall-guarded '(y) '((IN y U))
        (list 'FORSOME 'k_
          (conjuncts->and
            (list '(IN k_ NN)
                  (list 'FORSOME 'r
                    (conjuncts->and
                      (list '(POS-RR r)
                            (forall-guarded '(x) '((IN x ground))
                              (list 'IMPLIES
                                (forall-guarded '(n_) '((IN n_ NN) (<= n_ k_))
                                  '(< ((DIST (fam n_)) y x) r))
                                '(IN x U)))))))))))))
(notation! 'IS-OPEN-GAUGE 'kind 'predicate 'arity 3
           'english "$3 is open in the gauge topology of the family $1 on $2")

;;; The gauge topology as a TOP-SPACE, exactly as METRIC-TOP builds a metric's.
(def-functoid 'PSEUDO-GAUGE-TOP '(fam ground)
  '(LIST ground (SEP u (POWER ground) (IS-OPEN-GAUGE fam ground u))))
(notation! 'PSEUDO-GAUGE-TOP 'kind 'functoid 'arity 2
           'english "the topology generated by the pseudometric family $1 on $2")

;;; -----------------------------------------------------------------------
;;; IS-GAUGE-COUNTABLE(s): s is (up to ==) the gauge topology of SOME countable
;;; pseudometric family on its carrier.  This is condition (c) WITHOUT Hausdorff --
;;; the non-Hausdorff-friendly part, and what the T4 witness needs.

(def-predicate 'IS-GAUGE-COUNTABLE '(s)
  (conjuncts->and
    (list
      '(IS-TOP-SPACE s)
      (list 'FORSOME 'fam
        (conjuncts->and
          (list '(IS-COUNTABLE-PSEUDOMETRIC-FAMILY fam (PTS s))
                '(== (PSEUDO-GAUGE-TOP fam (PTS s)) s)))))))
(notation! 'IS-GAUGE-COUNTABLE 'kind 'predicate 'arity 1
           'english "$1 has a countable pseudometric gauge")

;;; =======================================================================
;;; The metrizability cluster.  (a) IS-METRIZABLE-TOP-SPACE; (b) metrizable by a
;;; bounded metric (T1, bounded-metric.scm); (c) Hausdorff AND gauge-countable.

;;; T2  (a) <=> (c).
(support 'metrizable-iff-gauge-countable
  (forall-guarded '(s) '((IS-TOP-SPACE s))
    (list 'IFF
      '(IS-METRIZABLE-TOP-SPACE s)
      (conjuncts->and (list '(IS-HAUSDORFF s) '(IS-GAUGE-COUNTABLE s))))))
(warrant! 'metrizable-iff-gauge-countable 'well-known
  "A topological space is metrizable iff it is Hausdorff and its topology is
   generated by a countable family of pseudometrics.  (=>) a metric is a single
   pseudometric, so {DIST} is a countable (singleton) family generating the same
   topology, and a metric space is Hausdorff.  (<=) given such a family and X
   Hausdorff -- so the family separates points (T0 already suffices) -- the sum
   d = SUM_n 2^-n d_n/(1+d_n) is a metric inducing the same topology.  Standard
   metrization of a countable gauge / uniform space (Kelley, General Topology,
   ch. 6; Bourbaki, Topologie Generale IX).")

;;; T3  (b) <=> (c).  A corollary of T1 and T2, on the board so the TFAE is closed.
(support 'bounded-metrizable-iff-gauge-countable
  (forall-guarded '(s) '((IS-TOP-SPACE s))
    (list 'IFF
      (list 'FORSOME 'md
        (conjuncts->and (list '(IS-BOUNDED-METRIC-SPACE md) '(== (METRIC-TOP md) s))))
      (conjuncts->and (list '(IS-HAUSDORFF s) '(IS-GAUGE-COUNTABLE s))))))
(warrant! 'bounded-metrizable-iff-gauge-countable 'well-known
  "Metrizable by a bounded metric iff Hausdorff and gauge-countable.  Immediate
   corollary of metrizable-iff-bounded-metrizable (T1) and
   metrizable-iff-gauge-countable (T2): compose the two equivalences through
   metrizability.")

;;; T4  witness: gauge-countable does NOT imply metrizable -- the Hausdorff
;;; hypothesis in (c) is load-bearing, not decoration.
(support 'gauge-countable-not-metrizable-witness
  (list 'FORSOME 's
    (conjuncts->and
      (list '(IS-GAUGE-COUNTABLE s)
            '(NOT (IS-METRIZABLE-TOP-SPACE s))))))
(warrant! 'gauge-countable-not-metrizable-witness 'well-known
  "There is a gauge-countable space that is not metrizable, so IS-GAUGE-COUNTABLE
   without IS-HAUSDORFF does not imply IS-METRIZABLE-TOP-SPACE.  Concrete witness:
   the single pseudometric d == 0 on any carrier with at least two points is a
   countable (singleton) pseudometric family whose gauge topology is the indiscrete
   topology {EMPTY-SET, PTS} -- non-Hausdorff, hence non-metrizable.  The
   substantive instances are non-Hausdorff spectra (e.g. the primitive-ideal /
   hull-kernel space of a C*-algebra).  Certifies the Hausdorff hypothesis of the
   gauge characterization (T2) is essential.")
