;;; qq-fractions.scm -- QQ is the field of fractions of the integers.
;;;
;;; THE AXIOMATIZATION GAP.  number-systems.scm introduces QQ as a primitive
;;; SET with the ordered-field signature (qq-add-closed, ..., qq-recip-inverse,
;;; :158-217) and ties it to ZZ by exactly one axiom, `zz-subset-qq' (:31) --
;;; the INCLUSION, and nothing else.  Nothing says QQ is the FRACTION FIELD of
;;; ZZ.  So QQ = RR satisfies every QQ axiom in the library, and in that model
;;; some rational squares to 2: `not(in(sqrt(2), qq))' is not merely unproven,
;;; it is FALSE IN A MODEL of the current theory.  It cannot be proved without
;;; this axiom, and it should not be.
;;;
;;; The honest fix is a construction: build QQ as the localization of ZZ, or as
;;; a quotient of ZZ x (ZZ \ {0}).  The library has no localization machinery,
;;; so we assert the one fact that construction would deliver, and warrant it
;;; `reference': it is the defining property of the rationals, and no textbook
;;; would pause over it.  When a fraction-field construction lands, this file
;;; becomes a theorem and the warrant is retired.
;;;
;;; WHY NN AND NOT ZZ.  The classical statement is "q = a/b with a, b integers,
;;; b /= 0".  We state it for NON-NEGATIVE q with a and b in NN, and that is not
;;; a dodge -- it is the weaker fact, and it is the one that pays:
;;;
;;;   * ZZ is under-specified in the same way QQ is.  number-systems.scm:104-151
;;;     axiomatizes ZZ as a commutative RING containing NN and closed under
;;;     negation.  Nothing forces every integer to be n or -n for some n in NN,
;;;     so ZZ could be QQ, and "every integer is even or odd" is no more
;;;     provable there than the fraction property is.  A ZZ-shaped support would
;;;     therefore need a SECOND support (ZZ is generated by NN) to be usable.
;;;   * NN is pinned: it has induction (nn-induction, number-systems.scm:94) and
;;;     a real order calculus (structure-library/order-lemmas.scm).  Parity is a
;;;     THEOREM there, proved, not asserted -- which is the whole point of the
;;;     exercise.
;;;   * minimize! wants an NN-valued MEASURE (minimize.scm).  A denominator in
;;;     NN is one; a denominator in ZZ is not, and there is no ZZ -> NN bridge
;;;     in the library to make it one.
;;;
;;; And it suffices: SQRT(2) >= 0 (sqrt-nonneg, real-powers.scm), so the only
;;; rational we need to take apart is a non-negative one.
;;;
;;; Loads after number-systems (QQ, NN, the inclusion chain) and proof-debt
;;; (support/warrant!).

;;; qq-nonneg-is-fraction RETIRED 2026-09-18 (rake batch 5): proven modulo 0 in theorem-library/rake-algebra3.scm

