;;; sigma-algebra.scm -- ALGEBRAS and SIGMA-ALGEBRAS of sets.  Vocabulary only:
;;; the two definitions of Chapter 1 of the measure-theory notes, cross-checked
;;; against Rudin.  Nothing is asserted here.
;;;
;;; SOURCES.  Thayer, Construction of Measures, Def. 1.1 (algebra of sets, p. 1)
;;; and Def. 1.7 (sigma-algebra, p. 2); Rudin, Real and Complex Analysis, Def.
;;; 1.3 (p. 8).  The two agree, by different routes:
;;;
;;;   NOTES     an algebra is a NONEMPTY A subset P(X) closed under finite
;;;             unions, finite intersections and complements relative to X;
;;;             a sigma-algebra is an algebra also closed under COUNTABLE unions.
;;;   RUDIN     a sigma-algebra in X is a collection M of subsets of X with
;;;             (i) X in M, (ii) A in M => X\A in M, (iii) M closed under
;;;             countable unions.
;;;
;;; IS-SIGMA-ALGEBRA below is stated in RUDIN's three-clause form -- it is the
;;; shorter of the two and the one every later proof actually cites.  The notes'
;;; form follows from it (a countable union with all but finitely many terms
;;; empty is a finite union) and implies it (nonempty + complements + finite
;;; unions give X in A); neither direction is claimed here.
;;;
;;; ARITY.  Both sources say "finite unions/intersections"; IS-ALGEBRA-OF-SETS
;;; states the BINARY closures.  Finite arity follows by induction on the number
;;; of terms, and finite INTERSECTION follows from binary union + complement by
;;; De Morgan; stating the binary laws keeps the definition first-order and
;;; quantifier-free over families.  It is stated as it is USED.
;;;
;;; COUNTABLE.  "Countable union" is rendered as a union over a SEQUENCE, exactly
;;; as Rudin writes it (A = union_{n=1}^{infinity} A_n): a family is a function
;;; f in FUN(NN, cA), applied by juxtaposition (f_ n_), and the union is the
;;; BIG-UNION binder over NN.  This admits repetitions, so it covers finite and
;;; empty subfamilies too -- no separate countability predicate is needed.
;;;
;;; NEXT (not stated, deliberately): every sigma-algebra contains EMPTY-SET and
;;; is closed under countable intersections (both one-line consequences); the
;;; sigma-algebra GENERATED by a family (Def. 1.9), which needs the intersection
;;; of a family of sigma-algebras; monotone classes (Def. 1.12) and the monotone
;;; class theorem (Thm. 1.13).
;;; ====================================================================

;;; IS-ALGEBRA-OF-SETS(omega, cA): cA is a nonempty family of subsets of omega
;;; closed under binary union, binary intersection and complement in omega.
(def-predicate 'IS-ALGEBRA-OF-SETS '(omega cA)
  (conjuncts->and
    (list
      '(IN omega SET)
      '(SUBSET cA (POWER omega))
      '(FORSOME a_ (IN a_ cA))                             ; nonempty
      (forall-guarded '(a_) '((IN a_ cA))
        '(IN (COMPLEMENT-IN omega a_) cA))
      (forall-guarded '(a_) '((IN a_ cA))
        (forall-guarded '(b_) '((IN b_ cA))
          '(IN (UNION a_ b_) cA)))
      (forall-guarded '(a_) '((IN a_ cA))
        (forall-guarded '(b_) '((IN b_ cA))
          '(IN (INTERSECTION a_ b_) cA))))))

;;; IS-SIGMA-ALGEBRA(omega, cA): Rudin's Def. 1.3 -- omega itself is a member,
;;; members have their complements, and countable unions of members are members.
(def-predicate 'IS-SIGMA-ALGEBRA '(omega cA)
  (conjuncts->and
    (list
      '(IN omega SET)
      '(SUBSET cA (POWER omega))
      '(IN omega cA)                                       ; Rudin 1.3(i)
      (forall-guarded '(a_) '((IN a_ cA))                  ; Rudin 1.3(ii)
        '(IN (COMPLEMENT-IN omega a_) cA))
      (forall-guarded '(f_) '((IN f_ (FUN NN cA)))         ; Rudin 1.3(iii)
        '(IN (BIG-UNION n_ NN (f_ n_)) cA)))))

(notation! 'IS-ALGEBRA-OF-SETS 'kind 'predicate 'arity 2
           'english "$2 is an algebra of subsets of $1")
(notation! 'IS-SIGMA-ALGEBRA   'kind 'predicate 'arity 2
           'english "$2 is a sigma-algebra of subsets of $1")
