;;; zz-arith.scm -- ZZ is GENERATED by NN.  The axiom that makes the integers
;;; the integers.
;;;
;;; THE GAP (and it is the same one, a third time).  number-systems.scm gives ZZ
;;; a commutative-ring signature (:104-151: closure, assoc, comm, distrib,
;;; a+0 = a, a + (-a) = 0, 1*a = a), plus NN <= ZZ and ZZ <= QQ.  It never says
;;; the integers are GENERATED by the naturals.  So the axioms say "ZZ is some
;;; commutative ring that contains NN and sits inside QQ" -- and QQ ITSELF is a
;;; model of every one of them.  In that model 2 * (1/2) = 1, so
;;;
;;;     forall k in ZZ. 2*k /= 1
;;;
;;; -- the innocuous-looking lemma on which all of parity rests -- is FALSE in a
;;; model of the current theory.  Not hard: false.  And so is the parity
;;; dichotomy (in QQ nothing is odd).  Every argument by parity, by descent, by
;;; "no integer strictly between 0 and 1", was unreachable, and the reason was
;;; never stated anywhere.
;;;
;;; This axiom states it: every integer is a natural number or the negative of
;;; one.  From it, with NN's induction, the whole of parity is THEOREM --
;;; dichotomy, exclusivity, 2k /= 1, discreteness (theorem-library/parity.scm).
;;;
;;; Retire it by CONSTRUCTING ZZ (as a quotient of NN x NN, the usual
;;; difference-pairs), at which point this becomes a theorem.  The library has no
;;; such construction, so it is asserted -- and warranted `reference', because it
;;; is the definition of the integers and no textbook pauses over it.
;;;
;;; MOVED 2026-08-01.  The axiom itself now lives in number-systems.scm, in the
;;; ZZ block immediately after zz-distributive, under the SAME name
;;; (`zz-generated-by-nn') and with the same `reference' warrant -- so every
;;; citation, including zz-parity-proof.scm:94 and :235, is unaffected.  It was
;;; installed here as a PSS support, which put the axiom that says what ZZ IS in
;;; a downstream lemma file, two load steps away from the ring axioms it
;;; completes; the user's arithmetic-base cleanup of 2026-08-01 (items (a)-(f))
;;; put it back with them.
;;;
;;; This file is now argument only -- it installs nothing.  That is why it is
;;; kept rather than deleted: the passage above is the clearest statement in the
;;; tree of what an under-determined number system costs, and number-systems.scm
;;; carries only a four-line summary of it.
;;;
;;; Loads after number-systems (ZZ, NN, negation) and proof-debt.
