;;; zz-arith.scm -- ZZ is GENERATED by NN.  The axiom that makes the integers
;;; the integers.
;;;
;;; THE GAP (and it is the same one, a third time).  number-systems.scm gives ZZ
;;; a commutative-ring signature (:104-151: closure, assoc, comm, distrib,
;;; a+0 = a, a + (-a) = 0, 1*a = a), plus NN <= ZZ and ZZ <= QQ.  It never says
;;; the integers are GENERATED by the naturals.  So the axioms say "ZZ is some
;;; commutative ring that contains NN and sits inside QQ" -- and QQ ITSELF is a
;;; model of every one of them.  In that model 2 * (1/2) = 1, so
;;;
;;;     forall k in ZZ. 2*k /= 1
;;;
;;; -- the innocuous-looking lemma on which all of parity rests -- is FALSE in a
;;; model of the current theory.  Not hard: false.  And so is the parity
;;; dichotomy (in QQ nothing is odd).  Every argument by parity, by descent, by
;;; "no integer strictly between 0 and 1", was unreachable, and the reason was
;;; never stated anywhere.
;;;
;;; This axiom states it: every integer is a natural number or the negative of
;;; one.  From it, with NN's induction, the whole of parity is THEOREM --
;;; dichotomy, exclusivity, 2k /= 1, discreteness (theorem-library/parity.scm).
;;;
;;; Retire it by CONSTRUCTING ZZ (as a quotient of NN x NN, the usual
;;; difference-pairs), at which point this becomes a theorem.  The library has no
;;; such construction, so it is asserted -- and warranted `reference', because it
;;; is the definition of the integers and no textbook pauses over it.
;;;
;;; Loads after number-systems (ZZ, NN, negation) and proof-debt (support/warrant!).

(support 'zz-generated-by-nn
  '(FORALL a
     (IMPLIES (IN a ZZ)
       (FORSOME n
         (AND (IN n NN)
              (OR (= a n) (= a (- n))))))))

(warrant! 'zz-generated-by-nn 'reference
  "Every integer is a natural number or the negative of one -- the defining
   property of ZZ as the ring generated by NN.  ASSERTED because number-systems.scm
   introduces ZZ by its RING axioms alone: as axiomatized, QQ is a model of ZZ,
   and in QQ nothing is odd and 2*(1/2) = 1.  Without this, parity is not merely
   unproven but refutable in a model.  Retire it by constructing ZZ from NN
   (difference pairs), at which point it becomes a theorem.")
