;;; zz-divisibility.scm -- divisibility, Bezout combinations, gcd and coprimality
;;; on the INTEGERS.  Vocabulary only; nothing is asserted here.
;;;
;;; WHY ZZ AND NOT A GENERAL COMMUTATIVE RING.  Divisibility, gcd and coprimality
;;; are ring notions, and the natural statement is over a Euclidean ring s, with
;;; ((MUL s) a c) where this file writes (* a c).  The obstruction is not the
;;; statement but the PROOFS: `crs' (the commutative-ring normalizer) decides
;;; ring identities over the SURFACE operations +, *, - on NN/ZZ/QQ/RR/CC, and
;;; does not reach the abstract (ADD s) / (MUL s) of a structure parameter.  The
;;; ideal computations below -- "(x1*a + y1*b) + (x2*a + y2*b) = (x1+x2)*a +
;;; (y1+y2)*b" -- are exactly what it decides, at ZZ, in one step each.  Restate
;;; these four over a general s when the abstract normalizer exists; the theorems
;;; below then transport with `transport!' rather than being reproved.
;;;
;;; The bridge to the abstract layer is already built in the other direction:
;;; ZZ-RING is a declare-instance!'d EUCLIDEAN-RING (numeric-instances.scm), and
;;; `transport!' (transport.scm) rewrites any theorem about a Euclidean ring into
;;; the ZZ surface language.  That is how euclidean-ideal-has-generator arrives.
;;; ====================================================================

;;; ZZ-DIVIDES(a, b): a divides b -- b = a*c for some integer c.
;;; Note the orientation: the FIRST argument is the divisor.
(def-predicate 'ZZ-DIVIDES '(a b)
  (conjuncts->and
    (list
      '(IN a ZZ)
      '(IN b ZZ)
      '(FORSOME c_ (AND (IN c_ ZZ) (= b (* a c_)))))))

;;; ZZ-BEZOUT-SET(a, b) = { x*a + y*b : x, y in ZZ }, the ideal generated by a
;;; and b.  A SEP over ZZ, so its members are integers by construction.
(def-functoid 'ZZ-BEZOUT-SET '(a b)
  '(SEP z ZZ
     (FORSOME x_ (AND (IN x_ ZZ)
       (FORSOME y_ (AND (IN y_ ZZ)
         (= z (+ (* x_ a) (* y_ b)))))))))

;;; Its membership law, as a DEFINITIONAL axiom.  `mac-h' cannot unfold a
;;; def-functoid in an ASSUMPTION -- def-functoid installs a macete, not a
;;; theorem -- and every argument below reads a Bezout combination out of the
;;; context ("d is in the set, so d = x*a + y*b").  This is the functoid unfold
;;; composed with the SEP separation schema, both trusted base; it costs no debt.
(fluid-let ((*current-provenance* 'definitional))
  (add-axiom! *library* 'zz-bezout-set-membership
    (nest-quantifiers 'FORALL '(a b z_)
      '(IFF (IN z_ (ZZ-BEZOUT-SET a b))
            (AND (IN z_ ZZ)
                 (FORSOME x_ (AND (IN x_ ZZ)
                   (FORSOME y_ (AND (IN y_ ZZ)
                     (= z_ (+ (* x_ a) (* y_ b))))))))))))

;;; ZZ-IS-GCD(a, b, d): d is A greatest common divisor of a and b -- a common
;;; divisor that every common divisor divides.  "A", not "the": gcds are unique
;;; only up to a unit, and over ZZ the units are +1 and -1, so d and -d are both
;;; gcds.  Pinning a canonical NONNEGATIVE representative is a separate step (a
;;; `minimize!' over the positive members of ZZ-BEZOUT-SET) and is not done here.
(def-predicate 'ZZ-IS-GCD '(a b d)
  (conjuncts->and
    (list
      '(ZZ-DIVIDES d a)
      '(ZZ-DIVIDES d b)
      (forall-guarded '(e_) '((IN e_ ZZ) (ZZ-DIVIDES e_ a) (ZZ-DIVIDES e_ b))
        '(ZZ-DIVIDES e_ d)))))

;;; ZZ-COPRIME(a, b): 1 is a gcd of a and b.  Equivalent over ZZ to the Bezout
;;; form (1 = x*a + y*b for some integers x, y) -- that equivalence is a theorem,
;;; not a definition, and is not claimed here.
(def-predicate 'ZZ-COPRIME '(a b)
  '(ZZ-IS-GCD a b 1))

(notation! 'ZZ-DIVIDES 'kind 'predicate 'arity 2
           'english "$1 divides $2")
(notation! 'ZZ-IS-GCD  'kind 'predicate 'arity 3
           'english "$3 is a greatest common divisor of $1 and $2")
(notation! 'ZZ-COPRIME 'kind 'predicate 'arity 2
           'english "$1 and $2 are coprime")
