(load "/home/ubuntu/prover/driver-kit.scm")
(define (try name thunk) (call-with-current-continuation (lambda (k) (with-exception-handler (lambda (e) (display ";; ERR in ") (display name) (display ": ") (display (condition/report-string e)) (newline) (k #f)) thunk))))
(def-functoid 'PROBE-C2 '(x_) 'SET)
(define IOTA-T '(IOTA val_ (IN (LIST 0 val_) PROBE-C2)))
;; 1. the IOTA of app-graph at the functoid equals SET
(sp (make-wff (list '= IOTA-T 'SET)))
(try "app-graph" (lambda () (fact 'app-graph 'PROBE-C2 0)))
(display ";; context: ") (for-each (lambda (a) (display (expression->string a)) (display " | ")) (dk-asms)) (newline)
(try "subst iota -> phi(0)" (lambda () (subst (list '== IOTA-T '(PROBE-C2 0)))))
(display ";; goal: ") (display (expression->string (dk-goal))) (newline)
(try "mac+rfl" (lambda () (mac 'PROBE-C2) (rfl)))
(display ";; IOTA = SET proved? ") (display (proof-done? *ps*)) (newline)
(if (proof-done? *ps*) (qed 'probe-iota-is-set))
;; 2. the pair <0, SET> is a member of the functoid
(sp (make-wff '(IN (LIST 0 SET) PROBE-C2)))
(fact 'probe-iota-is-set)
(try "iota-e" (lambda () (iota-e IOTA-T)))
(display ";; context: ") (for-each (lambda (a) (display (expression->string a)) (display " | ")) (dk-asms)) (newline)
(try "subst" (lambda () (subst (list '= 'SET IOTA-T))))
(display ";; goal: ") (display (expression->string (dk-goal))) (newline)
(try "ass" (lambda () (ass)))
(display ";; <0,SET> in PROBE-C2 proved? ") (display (proof-done? *ps*)) (newline)
(if (proof-done? *ps*) (qed 'probe-pair-in-functoid))
;; 3. hence the pair is a set
(sp (make-wff '(IN (LIST 0 SET) SET)))
(fact 'probe-pair-in-functoid)
(try "mis" (lambda () (fact 'membership-implies-sethood '(LIST 0 SET) 'PROBE-C2) (ass)))
(display ";; (LIST 0 SET) in SET proved? ") (display (proof-done? *ps*)) (newline)
