;; Same derivation with a NAMED functoid whose value is the proper class SET: no vnb-lambda, no beta.
(def-functoid 'PROBE-CONST-SET '(x_) 'SET)
(sp (make-wff "set in set"))
(fact 'image-membership-iff 'PROBE-CONST-SET 'NN 'SET)
(define rhs (let loop ((as (dk-asms))) (cond ((null? as) #f) ((and (pair? (car as)) (eq? (caar as) 'IFF)) (caddr (car as))) (#t (loop (cdr as))))))
(display ";; rhs: ") (write rhs) (newline)
(have! rhs (lambda ()
  (ew 0) (di)
  (let ((eq-leaf (car (filter (lambda (l) (eq? (car (dk-goal-of l)) '=)) (dk-open-leaves))))
        (in-leaf (car (filter (lambda (l) (equal? (dk-goal-of l) '(IN 0 NN))) (dk-open-leaves)))))
    (dk-focus! in-leaf) (arith)
    (dk-focus! eq-leaf) (mac 'PROBE-CONST-SET)
    (display ";; after mac goal: ") (display (expression->string (dk-goal))) (newline)
    (rfl))))
(have! '(IN SET (IMAGE PROBE-CONST-SET NN)) (lambda () (prop)))
(fact 'membership-implies-sethood 'SET '(IMAGE PROBE-CONST-SET NN))
(ass)
(display ";; SET in SET by a functoid alone? ") (display (proof-done? *ps*)) (newline)
(if (proof-done? *ps*) (qed 'probe-set-in-set-functoid))
