;; SOUNDNESS PROBE (2026-09-30, notes-52): can a set-builder lambda whose body is a
;; proper class be beta-reduced, and does image-membership-iff then make SET a member?
(define L '(VNB-LAMBDA x_ NN SET))
(sp (make-wff "set in set"))
(fact 'image-membership-iff L 'NN 'SET)
(display ";; after fact: ") (display (length (dk-asms))) (display " assumptions") (newline)
(for-each (lambda (a) (display ";;   ") (display (expression->string a)) (newline)) (dk-asms))
(define rhs (let loop ((as (dk-asms))) (cond ((null? as) #f) ((and (pair? (car as)) (eq? (caar as) 'IFF)) (caddr (car as))) (#t (loop (cdr as))))))
(display ";; rhs: ") (write rhs) (newline)
(have! rhs (lambda ()
  (ew 0)
  (have! '(IN 0 NN) (lambda () (arith)))
  (di)
  (display ";; leaves after di: ") (display (length (dk-open-leaves))) (newline)
  (for-each (lambda (l) (display ";;   goal ") (display (expression->string (dk-goal-of l))) (newline)) (dk-open-leaves))
  (let ((eq-leaf (car (filter (lambda (l) (eq? (car (dk-goal-of l)) '=)) (dk-open-leaves))))
        (in-leaf (car (filter (lambda (l) (equal? (dk-goal-of l) '(IN 0 NN))) (dk-open-leaves)))))
    (dk-focus! in-leaf) (arith)
    (dk-focus! eq-leaf) (lam-b)
    (display ";; after lam-b goal: ") (display (expression->string (dk-goal))) (newline)
    (rfl)
    (display ";; eq leaf grounded? ") (display (not (memq eq-leaf (dk-open-leaves)))) (newline))))
(display ";; after have!: leaves ") (display (length (dk-open-leaves))) (newline)
(have! (list 'IN 'SET (list 'IMAGE L 'NN)) (lambda () (prop)))
(display ";; SET in IMAGE landed: ") (display (and (member (list 'IN 'SET (list 'IMAGE L 'NN)) (dk-asms)) #t)) (newline)
(fact 'membership-implies-sethood 'SET (list 'IMAGE L 'NN))
(ass)
(display ";; SET in SET proved? ") (display (proof-done? *ps*)) (newline)
(display ";; owed leaves: ") (display (length (proof-open-leaves *ps*))) (newline)

(if (proof-done? *ps*) (qed 'probe-set-in-set))
;; Stage 2b: Burali-Forti.  ORD is a subclass of SET; if SET is a set, so is ORD.
(define (try name thunk) (call-with-current-continuation (lambda (k) (with-exception-handler (lambda (e) (display ";; ERR in ") (display name) (display ": ") (display (condition/report-string e)) (newline) (k #f)) thunk))))
(sp (make-wff "falsity"))
(fact 'probe-set-in-set)
(have! '(SUBSET ORD SET)
  (lambda ()
    (mac 'subset-def) (di)
    (let ((xv (cadr (dk-goal))))
      (display ";; eigenvariable ") (display xv) (newline)
      (fact 'membership-implies-sethood xv 'ORD)
      (ass))))
(display ";; ORD subset SET landed: ") (display (and (member '(SUBSET ORD SET) (dk-asms)) #t)) (newline)
(try "subclass A B" (lambda () (fact 'subclass-of-set-is-set 'SET 'ORD)))
(if (not (member '(IN ORD SET) (dk-asms))) (try "subclass B A" (lambda () (fact 'subclass-of-set-is-set 'ORD 'SET))))
(display ";; ORD in SET landed: ") (display (and (member '(IN ORD SET) (dk-asms)) #t)) (newline)
(fact 'burali-forti)
(display ";; context: ") (for-each (lambda (a) (display (expression->string a)) (display " | ")) (dk-asms)) (newline)
(try "prop" (lambda () (prop)))
(display ";; FALSITY proved? ") (display (proof-done? *ps*)) (newline)
(if (proof-done? *ps*) (qed 'probe-falsity))
