;;; certification.scm -- VNB test stamp.  AUTO-GENERATED by vnb-test.
;;; 2026-06-22.  Do not edit by hand; re-run ./vnb-test to refresh.
;;; Each (certify! 'name "date") records a theorem re-proved to QED.

(certify! 'abelian-group-is-group "2026-06-22")
(certify! 'abelian-group-mul-comm "2026-06-22")
(certify! 'bijection-in-fun "2026-06-22")
(certify! 'bijection-injective "2026-06-22")
(certify! 'bijection-is-injection "2026-06-22")
(certify! 'bijection-surjective "2026-06-22")
(certify! 'commutative-ring-is-ring "2026-06-22")
(certify! 'converges-to-compose-continuous "2026-06-22")
(certify! 'euclidean-ring-is-integral-domain "2026-06-22")
(certify! 'euclidean-ring-is-pid "2026-06-22")
(certify! 'metric-pos "2026-06-22")
(certify! 'metric-self-zero "2026-06-22")
(certify! 'metric-sym "2026-06-22")
(certify! 'metric-triangle "2026-06-22")
(certify! 'metric-zero-eq "2026-06-22")
(certify! 'module-zero-act "2026-06-22")
(certify! 'nn-least-element "2026-06-22")
