(display "\n=== the open obligation ===\n")
(display (expression->string (wff-formula (functor-obligation 'trunc-metric-functorial))))
(newline)
(display "\n=== IS-HOM-METRIC-SPACE unfolded ===\n")
(sp (functor-obligation 'trunc-metric-functorial))
(quietly (lambda () (di) (di) (di) (di)))
(display "GOAL: ")
(display (expression->string (wff-formula (sequent-node-assertion (proof-state-focus *ps*)))))
(newline)
(display "CTX:\n")
(for-each (lambda (w) (display "  - ") (display (expression->string (wff-formula w))) (newline))
          (sequent-node-assumptions (proof-state-focus *ps*)))
(quietly (lambda () (mac 'is-hom-metric-space) (slot 'PTS)))
(display "\nAFTER (mac 'is-hom-metric-space) (slot 'PTS):\n  ")
(display (expression->string (wff-formula (sequent-node-assertion (proof-state-focus *ps*)))))
(newline)
