;;; border-mult-proof.scm -- Brick B3 (LA Phase B): block-matrix multiplication.
;;;   BORDER(A,b,X,p,q) . BORDER(A,d,Y,q,r) = BORDER(A, b*d, X.Y, p, r)   [trust:none]
;;; The [[b,0],[0,X]] . [[d,0],[0,Y]] = [[bd,0],[0,XY]] direct-sum law -- the crux
;;; that lets the Smith recursion border a block equivalence back to the full
;;; matrix.  Via matrix-entry-extensionality + a 4-way case split on (i=1?)x(k=1?):
;;; three cases collapse to a single FINSUM term (finsum-single-support); the
;;; interior case reindexes the product sum by dropping the vanishing j=1 term and
;;; shifting (finsum-interval-shift) + finsum-congruence.  Mirrors matmul-assoc.
(define (bm-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (bm-di*) (let lp () (let* ((g (bm-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (bm-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (bm-foc! n) (set-proof-state-focus! *ps* n))
(define (bm-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (bm-find pred) (let lp ((as (bm-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (bm-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))
(define (impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))
(define (bm-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((use-or (bm-last)))
    (pbc) (cut `(NOT ,P))
    (let ((use-notp (bm-last)))
      (di) (cut `(OR ,P (NOT ,P)))
      (let ((u2 (bm-last))) (oi-l) (ass) (bm-foc! u2))
      (ai `(NOT (OR ,P (NOT ,P)))) (bm-foc! use-notp))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (bm-last))) (oi-r) (ass) (bm-foc! u3))
    (ai `(NOT (OR ,P (NOT ,P)))) (bm-foc! use-or)))
(define (bm-cases P) (bm-em P) (ai `(OR ,P (NOT ,P))) (bm-last))

(define BX '(BORDER A b X p q))
(define BY '(BORDER A d Y q r))
(define XY '(MATMUL A X Y))
(define BD '((MUL A) b d))
(define BXY (list 'BORDER 'A BD XY 'p 'r))
(define LHS (list 'MATMUL 'A BX BY))
(define AG '(RING-ADDITIVE-AG A))
(define FF (list 'VNB-LAMBDA 'j '(INTERVAL 1 (succ q)) (list '(MUL A) (list 'ENTRY BX 'i 'j) (list 'ENTRY BY 'j 'k))))
(define INTq '(INTERVAL 1 (succ q)))
(define ID-AG '(IDEN (RING-ADDITIVE-AG A)))
(define (VANISH) (fa* '(jz) (impl* (list '(IN jz (INTERVAL 1 (succ q))) '(NOT (= jz 1)))
                    (list '= (list FF 'jz) ID-AG))))

(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-RING A)
    (fa* '(p q r X Y b d)
      (impl* (list '(IN p NN) '(IN q NN) '(IN r NN)
                   '(IN X (MAT p q (CARR A))) '(IN Y (MAT q r (CARR A)))
                   '(IN b (CARR A)) '(IN d (CARR A)))
             (list '= LHS BXY)))))))
(bm-di*)
(fact 'border-type 'A 'b 'X 'p 'q)
(fact 'border-type 'A 'd 'Y 'q 'r)
(fact 'matmul-type 'A '(succ p) '(succ q) '(succ r) BX BY)
(fact 'ring-carrier-closed-mul 'A 'b 'd)
(fact 'matmul-type 'A 'p 'q 'r 'X 'Y)
(fact 'border-type 'A BD XY 'p 'r)
(fact 'ring-additive-ag-is-abelian-group 'A)
(fact 'interval-in-set 1 '(succ q))
;; interval-card-in-nn is guarded on its upper bound; here that bound is succ q,
;; and q is typed by the statement's own premise.
(fact 'nn-succ-closed 'q)
(fact 'interval-card-in-nn 1 '(succ q))
(fact 'one-in-interval 'q)

(cut (fa* '(i) (impl* '((IN i (INTERVAL 1 (succ p))))
       (fa* '(k) (impl* '((IN k (INTERVAL 1 (succ r))))
         (list '= (list 'ENTRY LHS 'i 'k) (list 'ENTRY BXY 'i 'k)))))))
(bm-di*)
(fact 'matmul-entry 'A '(succ p) '(succ q) '(succ r) BX BY 'i 'k)
(subst (list '= (list 'ENTRY LHS 'i 'k) (list 'FINSUM AG FF INTq)))
(fact 'matprod-summand-type 'A '(succ p) '(succ q) '(succ r) BX BY 'i 'k)

;; ===== 4-case split =====
(define NOTi (bm-cases '(= i 1)))
;; ---- i=1 ----
(define NOTk-a (bm-cases '(= k 1)))
;; -- i=1,k=1 --
(cut (VANISH)) (define V (bm-last))
(bm-di*) (lam-b) (subst '(= i 1))
(fact 'border-entry-1j 'A 'b 'X 'p 'q 'jz)
(subst (list '= (list 'ENTRY BX 1 'jz) '(ZERO A)))
(fact 'entry-in-carrier '(succ q) '(succ r) '(CARR A) BY 'jz 'k)
(fact 'ring-mul-zero-left 'A (list 'ENTRY BY 'jz 'k))
(subst (list '= (list '(MUL A) '(ZERO A) (list 'ENTRY BY 'jz 'k)) '(ZERO A)))
(fact 'ras-id 'A) (subst (list '= ID-AG '(ZERO A))) (rfl)
(bm-foc! V)
(fact 'finsum-single-support AG INTq FF 1)
(subst (list '= (list 'FINSUM AG FF INTq) (list FF 1)))
(lam-b) (subst '(= i 1)) (subst '(= k 1))
(fact 'border-entry-11 'A 'b 'X 'p 'q) (subst (list '= (list 'ENTRY BX 1 1) 'b))
(fact 'border-entry-11 'A 'd 'Y 'q 'r) (subst (list '= (list 'ENTRY BY 1 1) 'd))
(fact 'border-entry-11 'A BD XY 'p 'r) (subst (list '= (list 'ENTRY BXY 1 1) BD))
(rfl)
;; -- i=1,k/=1 --
(bm-foc! NOTk-a)
(cut (VANISH)) (define V2 (bm-last))
(bm-di*) (lam-b) (subst '(= i 1))
(fact 'border-entry-1j 'A 'b 'X 'p 'q 'jz)
(subst (list '= (list 'ENTRY BX 1 'jz) '(ZERO A)))
(fact 'entry-in-carrier '(succ q) '(succ r) '(CARR A) BY 'jz 'k)
(fact 'ring-mul-zero-left 'A (list 'ENTRY BY 'jz 'k))
(subst (list '= (list '(MUL A) '(ZERO A) (list 'ENTRY BY 'jz 'k)) '(ZERO A)))
(fact 'ras-id 'A) (subst (list '= ID-AG '(ZERO A))) (rfl)
(bm-foc! V2)
(fact 'finsum-single-support AG INTq FF 1)
(subst (list '= (list 'FINSUM AG FF INTq) (list FF 1)))
(lam-b) (subst '(= i 1))
(fact 'border-entry-11 'A 'b 'X 'p 'q) (subst (list '= (list 'ENTRY BX 1 1) 'b))
(fact 'border-entry-1j 'A 'd 'Y 'q 'r 'k) (subst (list '= (list 'ENTRY BY 1 'k) '(ZERO A)))
(fact 'ring-mul-zero-right 'A 'b) (subst (list '= (list '(MUL A) 'b '(ZERO A)) '(ZERO A)))
(fact 'border-entry-1j 'A BD XY 'p 'r 'k) (subst (list '= (list 'ENTRY BXY 1 'k) '(ZERO A)))
(rfl)
;; ---- i/=1 ----
(bm-foc! NOTi)
(define NOTk-b (bm-cases '(= k 1)))
;; -- i/=1,k=1 --
(cut (VANISH)) (define V3 (bm-last))
(bm-di*) (lam-b) (subst '(= k 1))
(fact 'border-entry-i1 'A 'd 'Y 'q 'r 'jz)
(subst (list '= (list 'ENTRY BY 'jz 1) '(ZERO A)))
(fact 'entry-in-carrier '(succ p) '(succ q) '(CARR A) BX 'i 'jz)
(fact 'ring-mul-zero-right 'A (list 'ENTRY BX 'i 'jz))
(subst (list '= (list '(MUL A) (list 'ENTRY BX 'i 'jz) '(ZERO A)) '(ZERO A)))
(fact 'ras-id 'A) (subst (list '= ID-AG '(ZERO A))) (rfl)
(bm-foc! V3)
(fact 'finsum-single-support AG INTq FF 1)
(subst (list '= (list 'FINSUM AG FF INTq) (list FF 1)))
(lam-b) (subst '(= k 1))
(fact 'border-entry-i1 'A 'b 'X 'p 'q 'i) (subst (list '= (list 'ENTRY BX 'i 1) '(ZERO A)))
(fact 'border-entry-11 'A 'd 'Y 'q 'r) (subst (list '= (list 'ENTRY BY 1 1) 'd))
(fact 'ring-mul-zero-left 'A 'd) (subst (list '= (list '(MUL A) '(ZERO A) 'd) '(ZERO A)))
(fact 'border-entry-i1 'A BD XY 'p 'r 'i) (subst (list '= (list 'ENTRY BXY 'i 1) '(ZERO A)))
(rfl)

;; -- i/=1,k/=1 : CRUX --
(bm-foc! NOTk-b)
(fact 'interval-in-set 1 'q) (fact 'interval-card-in-nn 1 'q)  ; [1,q] finite (for finsum-type/congruence)
(fact 'funcomp-succ-type '(CARR (RING-ADDITIVE-AG A)) 'q FF)   ; SHIFT typed
(define SHIFT (list 'VNB-LAMBDA 'z '(INTERVAL 1 q) (list FF '(succ z))))
(define IMU '(NN-MINUS i 1))
(define KMU '(NN-MINUS k 1))
(define GG (list 'VNB-LAMBDA 'z '(INTERVAL 1 q) (list '(MUL A) (list 'ENTRY 'X IMU 'z) (list 'ENTRY 'Y 'z KMU))))
(fact 'finsum-interval-shift AG 'q FF)
(subst (list '= (list 'FINSUM AG FF INTq)
             (list '(OPR (RING-ADDITIVE-AG A)) (list FF 1) (list 'FINSUM AG SHIFT '(INTERVAL 1 q)))))
;; typings for GG + SHIFT
(fact 'pred-in-interval 'p 'i) (fact 'pred-in-interval 'r 'k)
(fact 'matprod-summand-type 'A 'p 'q 'r 'X 'Y IMU KMU)         ; GG typed
;; RHS: BXY_{i,k} = XY_{i-1,k-1} = FINSUM GG
(fact 'border-entry-block2 'A BD XY 'p 'r 'i 'k)
(subst (list '= (list 'ENTRY BXY 'i 'k) (list 'ENTRY XY IMU KMU)))
(fact 'matmul-entry 'A 'p 'q 'r 'X 'Y IMU KMU)
(subst (list '= (list 'ENTRY XY IMU KMU) (list 'FINSUM AG GG '(INTERVAL 1 q))))
;; congruence FINSUM SHIFT = FINSUM GG  (BEFORE reducing FF(1) -- keeps SHIFT un-reduced)
(cut (fa* '(z) (impl* '((IN z (INTERVAL 1 q))) (list '= (list SHIFT 'z) (list GG 'z)))))
(define CG (bm-last))
(bm-di*)
;; SHIFT has domain [1,succ q] and is applied at (succ z) for z from [1,q];
;; succ-in-interval is what licenses the reduction, so it comes FIRST.
(fact 'succ-in-interval 'q 'z)
(lam-b) (lam-b) (lam-b)
(fact 'succ-not-one 'q 'z)
(fact 'border-entry-block2 'A 'b 'X 'p 'q 'i '(succ z))
(subst (list '= (list 'ENTRY BX 'i '(succ z)) (list 'ENTRY 'X IMU '(NN-MINUS (succ z) 1))))
(fact 'border-entry-block2 'A 'd 'Y 'q 'r '(succ z) 'k)
(subst (list '= (list 'ENTRY BY '(succ z) 'k) (list 'ENTRY 'Y '(NN-MINUS (succ z) 1) KMU)))
(fact 'interval-elt-in-nn 1 'q 'z) (fact 'nn-minus-succ-1 'z)
(subst '(= (NN-MINUS (succ z) 1) z))
(fact 'entry-in-carrier 'p 'q '(CARR A) 'X IMU 'z)
(fact 'entry-in-carrier 'q 'r '(CARR A) 'Y 'z KMU)
(fact 'ring-carrier-closed-mul 'A (list 'ENTRY 'X IMU 'z) (list 'ENTRY 'Y 'z KMU))
(rfl)
(bm-foc! CG)
(fact 'finsum-congruence AG '(INTERVAL 1 q) SHIFT GG)
(subst (list '= (list 'FINSUM AG SHIFT '(INTERVAL 1 q)) (list 'FINSUM AG GG '(INTERVAL 1 q))))
;; now goal: (OPR AG)(FF 1)(FINSUM GG) = FINSUM GG ; reduce FF(1) -> 0
(lam-b)
(fact 'border-entry-i1 'A 'b 'X 'p 'q 'i) (subst (list '= (list 'ENTRY BX 'i 1) '(ZERO A)))
(fact 'entry-in-carrier '(succ q) '(succ r) '(CARR A) BY 1 'k)
(fact 'ring-mul-zero-left 'A (list 'ENTRY BY 1 'k))
(subst (list '= (list '(MUL A) '(ZERO A) (list 'ENTRY BY 1 'k)) '(ZERO A)))
(mac 'ras-op)
;; (ADD A)(ZERO A)(FINSUM GG) -> FINSUM GG
(fact 'finsum-type AG '(INTERVAL 1 q) GG)
(cut (list 'IN (list 'FINSUM AG GG '(INTERVAL 1 q)) '(CARR A)))
(define FTC (bm-last))
(fact 'ras-carr 'A) (fact 'eq-sym (list 'CARR AG) '(CARR A))
(subst (list '= '(CARR A) (list 'CARR AG))) (ass)
(bm-foc! FTC)
(fact 'ring-add-left-id 'A (list 'FINSUM AG GG '(INTERVAL 1 q)))
(subst (list '= (list '(ADD A) '(ZERO A) (list 'FINSUM AG GG '(INTERVAL 1 q)))
             (list 'FINSUM AG GG '(INTERVAL 1 q))))
(rfl)

;; ===== back to main goal: matrix-entry-extensionality =====
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) LHS))))
(fact 'matrix-entry-extensionality '(succ p) '(succ r) '(CARR A) LHS BXY)
(ass)

(qed 'border-mult)
(topic! 'border-mult 'algebra)
;; categorize the BORDER read-offs (mat-equiv.scm loads before the PSS layer)
(topic! 'border-type 'plumbing)
(topic! 'border-entry-11 'algebra)
(topic! 'border-entry-1j 'algebra)
(topic! 'border-entry-i1 'algebra)
(topic! 'border-entry-block 'algebra)
(topic! 'border-entry-block2 'algebra)
