
;;; border-assembly-proof.scm -- Brick B3 (LA Phase B): the border algebra.
;;;   border-identity    BORDER(A,1,I_p,p,p) = I_{succ p}
;;;   border-is-diagonal E diagonal => BORDER(A,b,E,p,q) diagonal
;;;   border-invertible  U invertible => BORDER(A,1,U,n,n) invertible
;;; The routine lemmas the Smith bordering needs, built on border-mult + the BORDER
;;; read-offs.  Entry-level case proofs (border-identity/is-diagonal); border-invertible
;;; = border-mult + border-identity (inverse of BORDER(1,U) is BORDER(1,U^-1)).
(define (bm-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (bm-di*) (let lp () (let* ((g (bm-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (bm-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (bm-foc! n) (set-proof-state-focus! *ps* n))
(define (bm-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (bm-find pred) (let lp ((as (bm-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (bm-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))
(define (impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))
(define (bm-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((use-or (bm-last)))
    (pbc) (cut `(NOT ,P))
    (let ((use-notp (bm-last)))
      (di) (cut `(OR ,P (NOT ,P)))
      (let ((u2 (bm-last))) (oi-l) (ass) (bm-foc! u2))
      (ai `(NOT (OR ,P (NOT ,P)))) (bm-foc! use-notp))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (bm-last))) (oi-r) (ass) (bm-foc! u3))
    (ai `(NOT (OR ,P (NOT ,P)))) (bm-foc! use-or)))
(define (bm-cases P) (bm-em P) (ai `(OR ,P (NOT ,P))) (bm-last))

;; ===================== border-identity =====================
(define BI '(BORDER A (ONE A) (IDENTMAT A p) p p))
(define IM '(IDENTMAT A (succ p)))
(define IP '(IDENTMAT A p))
(sp (make-wff (list 'FORALL 'A (list 'IMPLIES '(IS-RING A) (list 'FORALL 'p (list 'IMPLIES '(IN p NN)
    (list '= BI IM)))))))
(bm-di*)
(fact 'ring-one-in 'A) (fact 'identmat-type 'A 'p)
(fact 'border-type 'A '(ONE A) IP 'p 'p) (fact 'identmat-type 'A '(succ p))
(cut (fa* '(i) (impl* '((IN i (INTERVAL 1 (succ p))))
       (fa* '(j) (impl* '((IN j (INTERVAL 1 (succ p))))
         (list '= (list 'ENTRY BI 'i 'j) (list 'ENTRY IM 'i 'j)))))))
(bm-di*)
(fact 'entry-of-identmat 'A '(succ p) 'i 'j)
(define RIF '(IF (= i j) (ONE A) (ZERO A)))
(subst (list '= (list 'ENTRY IM 'i 'j) RIF))
(fact 'interval-elt-in-nn 1 '(succ p) 'i) (fact 'interval-lo 1 '(succ p) 'i)
(fact 'interval-elt-in-nn 1 '(succ p) 'j) (fact 'interval-lo 1 '(succ p) 'j)
(define NEQij (bm-cases '(= i j)))
(if-true RIF) (define c1 (bm-last)) (ass) (bm-foc! c1)
(subst (list '= RIF '(ONE A))) (subst '(= i j))
(define NEQj1a (bm-cases '(= j 1)))
(subst '(= j 1))
(fact 'border-entry-11 'A '(ONE A) IP 'p 'p) (subst (list '= (list 'ENTRY BI 1 1) '(ONE A))) (rfl)
(bm-foc! NEQj1a)
(fact 'border-entry-block2 'A '(ONE A) IP 'p 'p 'j 'j)
(subst (list '= (list 'ENTRY BI 'j 'j) (list 'ENTRY IP '(NN-MINUS j 1) '(NN-MINUS j 1))))
(fact 'pred-in-interval 'p 'j)
(fact 'entry-of-identmat 'A 'p '(NN-MINUS j 1) '(NN-MINUS j 1))
(define DIF (list 'IF (list '= '(NN-MINUS j 1) '(NN-MINUS j 1)) '(ONE A) '(ZERO A)))
(subst (list '= (list 'ENTRY IP '(NN-MINUS j 1) '(NN-MINUS j 1)) DIF))
(if-true DIF) (define c2 (bm-last)) (rfl) (bm-foc! c2)
(subst (list '= DIF '(ONE A))) (rfl)
(bm-foc! NEQij)
(if-false RIF) (define c3 (bm-last)) (ass) (bm-foc! c3)
(subst (list '= RIF '(ZERO A)))
(define NEQi1 (bm-cases '(= i 1)))
(subst '(= i 1))
(fact 'neq-sym 'i 'j) (cut '(NOT (= j 1))) (define k1 (bm-last))
(fact 'eq-sym 'i 1) (subst '(= 1 i)) (ass) (bm-foc! k1)
(fact 'border-entry-1j 'A '(ONE A) IP 'p 'p 'j) (subst (list '= (list 'ENTRY BI 1 'j) '(ZERO A))) (rfl)
(bm-foc! NEQi1)
(define NEQj1b (bm-cases '(= j 1)))
(subst '(= j 1))
(fact 'border-entry-i1 'A '(ONE A) IP 'p 'p 'i) (subst (list '= (list 'ENTRY BI 'i 1) '(ZERO A))) (rfl)
(bm-foc! NEQj1b)
(fact 'border-entry-block2 'A '(ONE A) IP 'p 'p 'i 'j)
(subst (list '= (list 'ENTRY BI 'i 'j) (list 'ENTRY IP '(NN-MINUS i 1) '(NN-MINUS j 1))))
(fact 'pred-in-interval 'p 'i) (fact 'pred-in-interval 'p 'j)
(fact 'entry-of-identmat 'A 'p '(NN-MINUS i 1) '(NN-MINUS j 1))
(define DIF2 (list 'IF (list '= '(NN-MINUS i 1) '(NN-MINUS j 1)) '(ONE A) '(ZERO A)))
(subst (list '= (list 'ENTRY IP '(NN-MINUS i 1) '(NN-MINUS j 1)) DIF2))
(fact 'nn-minus-1-inj 'i 'j)
(if-false DIF2) (define c4 (bm-last)) (ass) (bm-foc! c4)
(subst (list '= DIF2 '(ZERO A))) (rfl)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) BI))))
(fact 'matrix-entry-extensionality '(succ p) '(succ p) '(CARR A) BI IM)
(ass)
(qed 'border-identity)

;; ===================== border-is-diagonal =====================
(define BE '(BORDER A b E p q))
(sp (make-wff (list 'FORALL 'A (list 'IMPLIES '(IS-RING A) (fa* '(b E p q)
    (impl* (list '(IN p NN) '(IN q NN) '(IS-DIAGONAL A p q E))
      (list 'IS-DIAGONAL 'A '(succ p) '(succ q) BE)))))))
(bm-di*)
(mac 'IS-DIAGONAL)
(bm-di*)                                          ; i j ; IN i ; IN j ; NOT(=i j)
(fact 'interval-elt-in-nn 1 '(succ p) 'i) (fact 'interval-lo 1 '(succ p) 'i)
(fact 'interval-elt-in-nn 1 '(succ q) 'j) (fact 'interval-lo 1 '(succ q) 'j)
(define D-NEQi1 (bm-cases '(= i 1)))
(subst '(= i 1))
(fact 'neq-sym 'i 'j) (cut '(NOT (= j 1))) (define dk1 (bm-last))
(fact 'eq-sym 'i 1) (subst '(= 1 i)) (ass) (bm-foc! dk1)
(fact 'border-entry-1j 'A 'b 'E 'p 'q 'j) (ass)
(bm-foc! D-NEQi1)
(define D-NEQj1 (bm-cases '(= j 1)))
(subst '(= j 1))
(fact 'border-entry-i1 'A 'b 'E 'p 'q 'i) (ass)
(bm-foc! D-NEQj1)
(fact 'border-entry-block2 'A 'b 'E 'p 'q 'i 'j)
(subst (list '= (list 'ENTRY BE 'i 'j) (list 'ENTRY 'E '(NN-MINUS i 1) '(NN-MINUS j 1))))
(fact 'pred-in-interval 'p 'i) (fact 'pred-in-interval 'q 'j)
(fact 'nn-minus-1-inj 'i 'j)
(mac-h 'IS-DIAGONAL '(IS-DIAGONAL A p q E))
(define EDIAG (bm-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'i)))))
(inst+ EDIAG '(NN-MINUS i 1))
(define EDj (bm-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'j)))))
(inst+ EDj '(NN-MINUS j 1))
(ass)
(qed 'border-is-diagonal)

;; ===================== border-invertible =====================
(define BU '(BORDER A (ONE A) U n n))
(sp (make-wff (list 'FORALL 'A (list 'IMPLIES '(IS-RING A) (fa* '(n U)
    (impl* (list '(IN n NN) '(IS-INVERTIBLE-MAT A n U))
      (list 'IS-INVERTIBLE-MAT 'A '(succ n) BU)))))))
(bm-di*)
(mac-h 'IS-INVERTIBLE-MAT '(IS-INVERTIBLE-MAT A n U))
(ai 1) (ai 1) (ai 1) (ai 1)
(define UVEQ (bm-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
             (eq? (car (cadr z)) 'MATMUL) (equal? (caddr (cadr z)) 'U)))))
(define V (cadddr (cadr UVEQ)))                    ; UVEQ = (= (MATMUL A U V)(IDENTMAT A n))
(define VUEQ (bm-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
             (eq? (car (cadr z)) 'MATMUL) (equal? (caddr (cadr z)) V) (equal? (cadddr (cadr z)) 'U)))))
(define BV (list 'BORDER 'A '(ONE A) V 'n 'n))
(fact 'ring-one-in 'A)
(fact 'invertible-mat-is-mat 'A 'n 'U)
(fact 'border-type 'A '(ONE A) 'U 'n 'n)
(fact 'border-type 'A '(ONE A) V 'n 'n)
(fact 'identmat-type 'A '(succ n))
(mac 'IS-INVERTIBLE-MAT)
(di)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'IN) (equal? (cadr g) BU)))) (ass)
(bm-foc-goal! (H? 'FORSOME))
(ew BV) (di)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'IN) (equal? (cadr g) BV)))) (ass)
(bm-foc-goal! (H? 'AND)) (di)
;; BU.BV = I
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'MATMUL 'A BU BV)))))
(fact 'border-mult 'A 'n 'n 'n 'U V '(ONE A) '(ONE A))
(subst (list '= (list 'MATMUL 'A BU BV)
             (list 'BORDER 'A (list '(MUL A) '(ONE A) '(ONE A)) (list 'MATMUL 'A 'U V) 'n 'n)))
(fact 'ring-mul-left-id 'A '(ONE A))
(subst (list '= (list '(MUL A) '(ONE A) '(ONE A)) '(ONE A)))
(subst UVEQ)
(fact 'border-identity 'A 'n)
(subst (list '= (list 'BORDER 'A '(ONE A) (list 'IDENTMAT 'A 'n) 'n 'n) '(IDENTMAT A (succ n))))
(rfl)
;; BV.BU = I
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'MATMUL 'A BV BU)))))
(fact 'border-mult 'A 'n 'n 'n V 'U '(ONE A) '(ONE A))
(subst (list '= (list 'MATMUL 'A BV BU)
             (list 'BORDER 'A (list '(MUL A) '(ONE A) '(ONE A)) (list 'MATMUL 'A V 'U) 'n 'n)))
(fact 'ring-mul-left-id 'A '(ONE A))
(subst (list '= (list '(MUL A) '(ONE A) '(ONE A)) '(ONE A)))
(subst VUEQ)
(fact 'border-identity 'A 'n)
(subst (list '= (list 'BORDER 'A '(ONE A) (list 'IDENTMAT 'A 'n) 'n 'n) '(IDENTMAT A (succ n))))
(rfl)
(qed 'border-invertible)

(category! 'border-identity 'algebra)
(category! 'border-is-diagonal 'algebra)
(category! 'border-invertible 'algebra)


;; ===================== bordering =====================
;; G = BORDER(b,W), MAT-EQUIV(W,E)  =>  G ~ BORDER(b,E).  Witness the bordered
;; invertibles BORDER(1,U'), BORDER(1,V'); U.G.V = BORDER(b, U'.W.V') = BORDER(b,E)
;; by two border-mults.  W/G named to dodge the case-fold clash with MAT-EQUIV's m/C.
(define BCE (list 'BORDER 'A 'b 'E 'p 'q))
(define GBORD (list 'BORDER 'A 'b 'W 'p 'q))

(sp (make-wff (list 'FORALL 'A (list 'IMPLIES '(IS-RING A) (fa* '(p q b W G E)
    (impl* (list '(IN p NN) '(IN q NN) '(IN b (CARR A))
                 '(IN W (MAT p q (CARR A)))
                 '(IN G (MAT (succ p) (succ q) (CARR A)))
                 (list '= 'G GBORD)
                 '(MAT-EQUIV A p q W E))
      (list 'MAT-EQUIV 'A '(succ p) '(succ q) 'G BCE)))))))
(bm-di*)
(mac-h 'MAT-EQUIV '(MAT-EQUIV A p q W E))
(ai 1) (ai 1) (ai 1) (ai 1)
(define EEQ (bm-find (lambda (z) (and (pair? z) (eq? (car z) '=) (eq? (cadr z) 'E)))))
(define RHS (caddr EEQ))                            ; (MATMUL A (MATMUL A U' W) V')
(define INNER (caddr RHS))                          ; (MATMUL A U' W)
(define UP (caddr INNER))                           ; U'
(define VP (cadddr RHS))                            ; V'
(define BU (list 'BORDER 'A '(ONE A) UP 'p 'p))
(define BV (list 'BORDER 'A '(ONE A) VP 'q 'q))
(fact 'border-invertible 'A 'p UP)
(fact 'border-invertible 'A 'q VP)
(fact 'ring-one-in 'A)
(fact 'invertible-mat-is-mat 'A 'p UP)
(fact 'invertible-mat-is-mat 'A 'q VP)
(mac 'MAT-EQUIV)
(ew BU) (di)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'IS-INVERTIBLE-MAT) (equal? (cadddr g) BU)))) (ass)
(bm-foc-goal! (H? 'FORSOME))
(ew BV) (di)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'IS-INVERTIBLE-MAT) (equal? (cadddr g) BV)))) (ass)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) BCE))))
(subst (list '= 'G GBORD))
(fact 'border-mult 'A 'p 'p 'q UP 'W '(ONE A) 'b)
(subst (list '= (list 'MATMUL 'A BU GBORD)
             (list 'BORDER 'A (list '(MUL A) '(ONE A) 'b) (list 'MATMUL 'A UP 'W) 'p 'q)))
(fact 'ring-mul-left-id 'A 'b)
(subst (list '= (list '(MUL A) '(ONE A) 'b) 'b))
(fact 'matmul-type 'A 'p 'p 'q UP 'W)
(fact 'border-mult 'A 'p 'q 'q (list 'MATMUL 'A UP 'W) VP 'b '(ONE A))
(subst (list '= (list 'MATMUL 'A (list 'BORDER 'A 'b (list 'MATMUL 'A UP 'W) 'p 'q) BV)
             (list 'BORDER 'A (list '(MUL A) 'b '(ONE A)) (list 'MATMUL 'A (list 'MATMUL 'A UP 'W) VP) 'p 'q)))
(fact 'ring-mul-right-id 'A 'b)
(subst (list '= (list '(MUL A) 'b '(ONE A)) 'b))
(subst EEQ)
(fact 'matmul-type 'A 'p 'q 'q (list 'MATMUL 'A UP 'W) VP)   ; (U'.W).V' : p x q
(fact 'border-type 'A 'b (list 'MATMUL 'A (list 'MATMUL 'A UP 'W) VP) 'p 'q)
(rfl)
(qed 'bordering)
(category! 'bordering 'algebra)
