;;; cauchy-integral-formula.scm -- CAUCHY WITH AN EXCEPTIONAL POINT ON A DISC, THE WINDING
;;; NUMBER OF A CIRCLE INSIDE IT, THE CAUCHY INTEGRAL FORMULA ON A DISC, THEOREM 3.35
;;; (HOLOMORPHIC => ANALYTIC) AND THE HOLOMORPHY OF THE DERIVATIVE.
;;; (complex-analysis.pdf ch. 3: Cor 3.9 with one exceptional point, Example 3.13 /
;;; Cor 3.30 for the circle, 3.7 (first form of the integral formula), Theorem 3.35.)
;;; Agent CA-3 of week 2 of the October roadmap (scratchpad/triage/WEEK2.md), 2026-10-04.
;;;
;;; CONTENTS (in proof order).
;;;  (1) cif-open-minus-point            an open set minus a point is open
;;;  (2) cauchy-convex-sub-except        f continuous on an open u, holomorphic on u \ {x}: the
;;;                                      integral over a closed road in a convex open v inside u
;;;                                      is 0 (x in v or not)
;;;  (3) cauchy-disc-except              the same for an open disc B(c, r) inside u
;;;  (4) cif-recip-shift-diff            (1/(w - c))' = -(1/(w - c))^2 on CC \ {c}
;;;  (5) cif-recip-power-diff            ((1/(w - c))^(j+1))' = -(j+1) (1/(w - c))^(j+2)   (induction)
;;;  (6) cif-recip-power-closed-zero     int over a closed road off c of (1/(w - c))^(j+2) = 0
;;;  (7) circle-trace-magnitude          |w - c| = r on the trace of CIRCLE-PATH(c, r)
;;;      circle-path-closed              CIRCLE-PATH(c, r)(2 pi) = CIRCLE-PATH(c, r)(0)
;;;  (8) winding-circle-inside           WINDING(circle(c, r), z) = 1 for every |z - c| < r
;;;  (9) cauchy-integral-formula-disc    f(z) = 1/(2 pi i) int_C(c,r) f(w)/(w - z) dw
;;; (10) cauchy-integral-formula-disc-restrict   the same, the weight spelled RESTRICT(f, trace)
;;;                                      as analytic-from-integral.scm spells it
;;; (11) holomorphic-power-series-disc   THEOREM 3.35: f is the sum of its power series on B(c, r)
;;; (12) holomorphic-analytic-at         HOLOMORPHIC-ON(u, f), c in u  =>  IS-ANALYTIC-AT(f, u, c)
;;; (13) holomorphic-deriv-holomorphic   HOLOMORPHIC-ON(u, f) => HOLOMORPHIC-ON(u, w |-> DERIV-ON(u, f, w))
;;;
;;; THE ROUTES.
;;; * (8), WITHOUT A LOGARITHM.  Lemma 3.33 (cauchy-kernel-integral-series, CA-2) with the
;;;   weight 1 on the trace T of the circle (every point of T is at distance exactly r from
;;;   c): int 1/(w - z) = sum_k a_k (z - c)^k with a_k = int (1/(w - c))^(k+1).  For k >= 1
;;;   the integrand has the primitive -(1/k) (1/(w - c))^k on CC \ {c} ((4)-(6), by the
;;;   product rule and induction), so a_k = 0 on the closed circle; the series is then
;;;   a_k 0^k termwise and cps-sum-at-zero sums it to a_0 = int 1/(w - c), whose winding
;;;   number is 1 (winding-circle-center).  The log route the brief proposed is not needed.
;;; * (9): the Caratheodory factor p of f at z (the witness of IS-DIFF-ON(u, f, z, f'(z)))
;;;   is continuous at z, equals (f(w) - f(z))/(w - z) off z (holomorphic there: hence
;;;   continuous on all of u), so (3) gives int p = 0 over the circle; on the trace
;;;   p = (f(w) - f(z))/(w - z), linearity splits the integral, and (8) gives
;;;   int 1/(w - z) = 2 pi i.
;;; * (11), (12): analytic-from-integral-formula / analytic-at-from-integral-formula (CA-2) fed
;;;   with (10).  (12) takes the disc B(c, s/2) inside the ball B(c, s) that the openness of u
;;;   gives at c.
;;; * (13): at a point a of u, (12) gives f = G_cf on a ball B(a, r) (G_cf the sum of a
;;;   power series centred at a); cps-translate-diff gives G_cf' = G_dcf (dcf the derived
;;;   coefficients, cps-radius-derived: same radius), cc-diff-on-local carries it to u, so
;;;   DERIV-ON(u, f, w) = G_dcf(w) on the ball; G_dcf is holomorphic (cps-translate-holomorphic),
;;;   so the derivative function is differentiable at a (cc-diff-on-local again).
;;;
;;; STATEMENT CHECKS.  The disc hypotheses are B(c, s) SUBSET u with 0 < r < s (an OPEN disc
;;; strictly larger than the circle), not "the closed disc D(c, r) inside u": the two are
;;; equivalent by the compactness of the closed disc (a Lebesgue-number argument), which the
;;; tree does not have as a lemma; (12) shows that nothing is lost for analyticity.  z is
;;; typed (IN z CC) and |z - c| < r, the spelling of analytic-from-integral.scm.  The circle
;;; is CA-1's CIRCLE-PATH / CIRCLE-DERIV on [0, 2 pi]; 1/(2 pi i) is recip((2 pi) i), the
;;; spelling of WINDING.  The integrand of (9) is a VNB-LAMBDA over the trace T (f is
;;; defined there since T lies in u); (10)-(11) use RESTRICT(f, T), the weight phi of
;;; CA-2's statements, so that they compose by one citation.  "The derivative" of (13) is
;;; the function w |-> DERIV-ON(CC-NORMED-FIELD, u, f, w) on u (structure-library/diff-on.scm).
;;;
;;; NOTHING asserted, no definition.  Helper prefix cif-; theorem binders cif*_ and the
;;; binders of the cited theorems where an instance must match (u, f, c, r, z, pgam, dgam,
;;; a, b, aiw_, aitk_, wnw_).
;;; LOAD WINDOW: lo = theorem-library/analytic-from-integral (cauchy-kernel-integral-series,
;;; analytic-from-integral-formula, analytic-at-from-integral-formula, aif-cont-*; load.scm
;;; line 3539), above winding-number-laws (3538: cauchy-disc, line-int-domain-congruence,
;;; holomorphic-on-restrict, winding-integrand-holomorphic, winding-circle-center,
;;; circle-is-road, cc-punctured-membership/-open), analytic-log-laws (3535:
;;; cps-translate-diff, cps-translate-holomorphic), goursat-exceptional (3519:
;;; cauchy-convex-closed-except), goursat (3518), goursat-bricks (3493:
;;; line-int-closed-road-of-derivative), cps-taylor-coefficients (3475: cps-sum-at-zero),
;;; cc-power-series-deriv (3472: cps-radius-derived, cc-diff-on-quadratic).  hi: none.
;;; Tactics: the early kit only (dk-*, use-em, use-cases, use-induction, prop, crs, ineq).
;;; piece 1: open minus a point, Cauchy with an exceptional point on a convex set / disc
(define cif-nfm '(NF-METRIC-SPACE CC-NORMED-FIELD))
(define (cif-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (cif-cont u f)
  (list 'FORALL 'rgy_ (list 'IMPLIES (list 'IN 'rgy_ u)
    (list 'IS-CONTINUOUS-AT (list 'SUBSPACE-MS cif-nfm u) cif-nfm f 'rgy_))))
(define (cif-imps hyps body)
  (if (null? hyps) body (list 'IMPLIES (car hyps) (cif-imps (cdr hyps) body))))
(define (cif-all vars body)
  (if (null? vars) body (list 'FORALL (car vars) (cif-all (cdr vars) body))))
(define (cif-and! a b)
  (let* ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! dk-ass!))))
    f))
(define (cif-pz z) (list 'DIFFERENCE 'CC (list 'SINGLETON z)))

(define (cif-rr! t)
  (let* ((typ (list 'IN t 'RR)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'rr-zero-in) typ)
          ((eqv? t 1) (fact 'rr-one-in) typ)
          ((eq? t 'PI) (dk-split-all! (list (dk-cite! 'pi-pos))) typ)
          ((number? t) (dk-have! typ (lambda () (arith))) typ)
          ((dk-asm? (list 'IN t 'NN)) (fact 'nn-in-rr t) typ)
          ((cif-op? t 'succ 2) (cif-nn! t) (fact 'nn-in-rr t) typ)
          ((cif-op? t '* 3) (cif-rr! (cadr t)) (cif-rr! (caddr t)) (fact 'rr-mul-in-rr (cadr t) (caddr t)) typ)
          ((cif-op? t '+ 3) (cif-rr! (cadr t)) (cif-rr! (caddr t)) (fact 'rr-add-in-rr (cadr t) (caddr t)) typ)
          ((cif-op? t '- 3) (cif-rr! (cadr t)) (cif-rr! (caddr t)) (fact 'rr-sub-in-rr (cadr t) (caddr t)) typ)
          ((cif-op? t '- 2) (cif-rr! (cadr t)) (fact 'rr-neg-closed (cadr t)) typ)
          ((cif-op? t 'magnitude 2) (cif-cc! (cadr t)) (fact 'cc-magnitude-closed (cadr t)) typ)
          ((cif-op? t 'real-part 2) (cif-cc! (cadr t)) (fact 'real-part-in-rr (cadr t)) typ)
          ((cif-op? t 'imag-part 2) (cif-cc! (cadr t)) (fact 'imag-part-in-rr (cadr t)) typ)
          ((cif-op? t 'abs 2) (cif-rr! (cadr t)) (fact 'rr-abs-closed (cadr t)) typ)
          ((cif-op? t 'recip 2)
           (cif-rr! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (if (dk-asm? (list '< 0 (cadr t)))
                   (fact 'rr-pos-ne-zero (cadr t))
                   (error "cif-rr!: land the non-vanishing first" (expression->string (cadr t)))))
           (cif-and! (list 'IN (cadr t) 'RR) (list 'NOT (list '= (cadr t) 0)))
           (fact 'rr-recip-closed (cadr t))
           typ)
          (#t (dk-real! t) typ))))
(define (cif-nn! t)
  (let* ((typ (list 'IN t 'NN)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'nn-zero-in) typ)
          ((cif-op? t 'succ 2) (cif-nn! (cadr t)) (fact 'nn-succ-closed (cadr t)) typ)
          (#t (dk-type! t 'NN)))))
(define (cif-cc! t)
  (let* ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((eqv? t +i) (fact 'cc-i-in) typ)
          ((or (and (number? t) (real? t)) (eq? t 'PI) (dk-asm? (list 'IN t 'RR)) (dk-asm? (list 'IN t 'NN))
               (cif-op? t 'succ 2)
               (cif-op? t 'magnitude 2) (cif-op? t 'real-part 2) (cif-op? t 'imag-part 2))
           (cif-rr! t) (fact 'rr-subset-cc t) typ)
          ((cif-op? t '- 3) (cif-cc! (cadr t)) (cif-cc! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((cif-op? t '- 2) (cif-cc! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((cif-op? t '+ 3) (cif-cc! (cadr t)) (cif-cc! (caddr t))
           (cif-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((cif-op? t '* 3) (cif-cc! (cadr t)) (cif-cc! (caddr t))
           (cif-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((cif-op? t 'power 3) (cif-cc! (cadr t)) (cif-nn! (caddr t))
           (cif-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'NN)) (fact 'power-typing-nonneg (cadr t) (caddr t)) typ)
          ((cif-op? t 'CC-EXP 2) (cif-cc! (cadr t))
           (dk-split-all! (list (dk-cite! 'cc-exp-converges (cadr t)))) typ)
          ((cif-op? t 'recip 2) (cif-cc! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (error "cif-cc!: land the non-vanishing first" (expression->string (cadr t))))
           (cif-and! (list 'IN (cadr t) 'CC) (list 'NOT (list '= (cadr t) 0)))
           (fact 'cc-recip-closed (cadr t)) typ)
          (#t (dk-type! t 'CC)))))

;;; y in CC \ {z}: land y in CC, y /= z, y - z /= 0
(define (cif-sub-nz! y z)
  (let* ((nz (list 'NOT (list '= (list '- y z) 0))))
    (dk-have! nz
      (lambda ()
        (di)
        (dk-cite! 'cc-sub-zero-eq y z)
        (ai (dk-ctx-form (list 'NOT (list '= y z))))))
    nz))
(define (cif-steps . thunks)
  ;; run THUNKS in order while the leaf focused at the start stays open
  (let* ((leaf (proof-state-focus *ps*)))
    (let loop ((ts thunks))
      (if (and (pair? ts) (not (sequent-node-grounded? leaf)))
          (begin ((car ts)) (loop (cdr ts)))))))
(define (cif-pz-open! z y)
  (let* ((iff (dk-cite! 'cc-punctured-membership z y)))
    (cif-steps
      (lambda () (dk-have! (list 'IN y 'CC) (lambda () (cif-only-prop! iff (list 'IN y (cif-pz z))))))
      (lambda () (dk-have! (list 'NOT (list '= y z)) (lambda () (cif-only-prop! iff (list 'IN y (cif-pz z))))))
      (lambda () (cif-sub-nz! y z)))))
(define (cif-pz-in! z y)
  (let* ((iff (dk-cite! 'cc-punctured-membership z y)))
    (dk-have! (list 'IN y (cif-pz z))
      (lambda () (cif-only-prop! iff (list 'IN y 'CC) (list 'NOT (list '= y z)))))))
;;; the punctured plane: open (both spellings), a set
(define (cif-pz-setup! z)
  (let* ((d (cif-pz z)))
    (fact 'nf-cc-is-metric-space)
    (dk-cite! 'cc-punctured-open z)
    (let* ((iff (dk-cite! 'cc-ms-open-iff d)))
      (dk-have! (list 'IS-OPEN cif-nfm d) (lambda () (cif-only-prop! iff (list 'IS-OPEN 'CC-MS d)))))
    (fact 'cc-is-set)
    (dk-cite! 'difference-set 'CC (list 'SINGLETON z))
    (dk-cite! 'cc-open-subset-cc d)))
;;; (cif-lam-typ! LAM DOM TYPER) -- LAM in FUN(DOM, CC); TYPER of the eigenvariable
(define (cif-lam-typ! lam dom pre)
  (dk-have! (list 'IN lam (list 'FUN dom 'CC))
    (lambda ()
      (dk-lam-type! (lambda ()
                      (let* ((v (dk-di-var!)) (leaf (proof-state-focus *ps*)))
                        (cif-steps
                          (lambda () (pre v))
                          (lambda () (if (dk--redex? (dk-goal)) (dk-lam-b!)))
                          (lambda () (if (not (dk-asm? (dk-goal))) (cif-cc! (cadr (dk-goal)))))
                          (lambda () (ass)))))))))
;;; detach an implication whose antecedent THUNK proves
(define (cif-detach! imp thunk)
  (if (and (pair? imp) (eq? (car imp) 'IMPLIES))
      (begin (dk-have! (cadr imp) thunk)
             (dk-landed-1 (lambda () (detach! imp))))
      imp))
(define (cif-only-prop! . fs) (if (apply dk-only! fs) (prop)))
(define (cif-lam-b-if!) (if (dk--redex? (dk-goal)) (dk-lam-b!)))
;;; subst, then ass on the SAME leaf unless the subst closed it
(define (cif-subst-ass! eq)
  (let* ((leaf (proof-state-focus *ps*)))
    (subst eq)
    (if (not (sequent-node-grounded? leaf)) (ass))))
;;; 2 pi i: in CC and non-zero, its reciprocal in CC
(define cif-tpi '(* (* 2 PI) +i))
(define (cif-tpi!)
  (cif-rr! '(* 2 PI))
  (dk-have! '(< 0 (* 2 PI)) (lambda () (dk-ineq! '(< 0 PI))))
  (dk-cite! 'rr-pos-ne-zero '(* 2 PI))
  (cif-cc! '(* 2 PI))
  (fact 'cc-i-in)
  (dk-have! '(NOT (= +i 0))
    (lambda ()
      (di)
      (fact 'cc-i-squared)
      (dk-have! '(= (* 0 0) -1) (lambda () (subst '(= 0 +i)) (ass)))
      (dk-have! '(NOT (= (* 0 0) -1)) (lambda () (arith)))
      (ai '(NOT (= (* 0 0) -1)))))
  (dk-cite! 'cc-mul-nonzero '(* 2 PI) +i)
  (cif-cc! cif-tpi)
  (cif-cc! (list 'recip cif-tpi))
  (cif-and! (list 'IN cif-tpi 'CC) (list 'NOT (list '= cif-tpi 0)))
  (dk-cite! 'cc-recip-inverse cif-tpi))
;;; x in CC, c in CC, s in RR, |x - c| < s in context: land x in BALL(CC-MS, c, s)
(define (cif-in-ball! x c s)
  (let* ((m (list 'magnitude (list '- x c))))
    (fact 'cc-is-metric-space)
    (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
    (dk-have! (list 'IN x '(PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
    (dk-have! (list 'IN c '(PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
    (cif-rr! m)
    (dk-cite! 'cc-ms-dist c x)
    (dk-cite! 'cc-magnitude-sub-sym c x)
    (dk-have! (list '<= (list '(DIST CC-MS) c x) m)
      (lambda ()
        (subst (list '= (list '(DIST CC-MS) c x) (list 'magnitude (list '- c x))))
        (if (not (equal? c x)) (subst (list '= (list 'magnitude (list '- c x)) m)))
        (dk-ineq!)))
    (let* ((cj (list 'AND (list 'IN x '(PTS CC-MS)) (list 'AND (list 'IN m 'RR) (list 'AND (list 'IN s 'RR)
                (list 'AND (list '<= (list '(DIST CC-MS) c x) m) (list '< m s)))))))
      (dk-have! cj (lambda () (dk-conj-close! dk-ass!)))
      (dk-cite! 'ball-mem-from-le 'CC-MS c x m s))))
;;; subst EQ in a == goal, then qrfl on the same leaf unless the subst closed it
(define (cif-subst-qrfl! eq)
  (let* ((leaf (proof-state-focus *ps*)))
    (subst eq)
    (if (not (sequent-node-grounded? leaf)) (qrfl))))
;;; x in BALL(CC-MS, c, r) in context: land x in CC and |x - c| < r; return the latter
(define (cif-ball-open! c r x)
  ;; x in BALL(CC-MS, c, r) in context: land x in CC and |x - c| < r (stops early when a
  ;; landing closes the focus leaf, the claim being the goal)
  (let* ((dcx (list '(DIST CC-MS) c x))
         (mag (list 'magnitude (list '- c x)))
         (mag2 (list 'magnitude (list '- x c)))
         (cj  (list 'AND (list 'IN x '(PTS CC-MS)) (list 'AND (list '<= dcx r) (list 'NOT (list '= dcx r))))))
    (cif-steps
      (lambda () (fact 'cc-is-metric-space))
      (lambda () (let* ((iff (dk-cite! 'ball-membership 'CC-MS c r x)))
                   (dk-have! cj (lambda () (cif-only-prop! iff (list 'IN x (list 'BALL 'CC-MS c r)))))))
      (lambda () (dk-split-all! (list (dk-ctx-form cj))))
      (lambda () (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl))))
      (lambda () (dk-have! (list 'IN x 'CC) (lambda () (subst '(= CC (PTS CC-MS))) (ass))))
      (lambda () (dk-cite! 'cc-ms-dist c x))
      (lambda () (cif-rr! mag))
      (lambda () (cif-rr! mag2))
      (lambda () (dk-cite! 'cc-magnitude-sub-sym c x))
      (lambda () (dk-have! (list 'AND (list '<= mag r) (list 'NOT (list '= mag r)))
                   (lambda () (subst (list '= mag dcx)) (dk-conj-close! dk-ass!))))
      (lambda () (dk-cite! 'rr-le-ne-lt mag r))
      (lambda () (dk-have! (list '< mag2 r) (lambda () (dk-ineq! (list '< mag r) (list '= mag mag2))))))))

(define (cif-subst-sym e from to)
  (cond ((eq? e from) to)
        ((pair? e) (cons (cif-subst-sym (car e) from to) (cif-subst-sym (cdr e) from to)))
        (#t e)))
;;; a point x of the trace, the trace already known inside CC \ {c} (and CC \ {z} ...):
;;; land x in CC, x /= c, x - c /= 0 (the same for each z in ZS)
(define (cif-tpt! x . zs)
  (cif-steps
    (lambda () (fact 'subset-mem-fwd cif-T (cif-pz 'c) x))
    (lambda () (cif-pz-open! 'c x))
    (lambda () (for-each (lambda (z) (fact 'subset-mem-fwd cif-T (cif-pz z) x) (cif-pz-open! z x)) zs))))
(define (cif-dump-open!)
  (for-each (lambda (l) (display "\n;; OPEN: ") (display (expression->string (dk-goal-of l)))) (dk-open-leaves)))
(define (cif-center-in-ball! a r)
  ;; a in CC, r in RR, 0 < r: land a in BALL(CC-MS, a, r) (which also certifies the ball DEFINED)
  (let* ((d (list '- a a)) (m (list 'magnitude d)))
    (cif-rr! m)
    (cif-cc! d)
    (dk-have! (list '= d 0) (lambda () (crs)))
    (let ((iff (dk-cite! 'cc-magnitude-zero-iff d)))
      (dk-have! (list '= m 0) (lambda () (cif-only-prop! iff (list '= d 0)))))
    (dk-have! (list '< m r) (lambda () (dk-ineq! (list '= m 0) (list '< 0 r))))
    (cif-in-ball! a a r)))
;;; (1) an open set minus a point is open
(sp (make-wff (list 'FORALL 'cifv_ (list 'IMPLIES (list 'IS-OPEN cif-nfm 'cifv_)
  (list 'FORALL 'cifx_ (list 'IMPLIES '(IN cifx_ CC)
    (list 'IS-OPEN cif-nfm '(DIFFERENCE cifv_ (SINGLETON cifx_)))))))))
(dk-peel!)
(let* ((v 'cifv_) (x 'cifx_) (d (list 'DIFFERENCE v (list 'SINGLETON x)))
       (p (cif-pz x)) (i (list 'INTERSECTION v p)))
  (fact 'nf-cc-is-metric-space)
  (dk-cite! 'cc-open-subset-cc v)
  (dk-cite! 'cc-punctured-open x)
  (let* ((iff (dk-cite! 'cc-ms-open-iff p)))
    (dk-have! (list 'IS-OPEN cif-nfm p) (lambda () (cif-only-prop! iff (list 'IS-OPEN 'CC-MS p)))))
  (dk-have! (list 'FORALL 'cify_ (list 'IFF (list 'IN 'cify_ d) (list 'IN 'cify_ i)))
    (lambda ()
      (let* ((y (dk-di-var! (lambda (g) (cadr (cadr g))))))
        (let* ((f1 (dk-cite! 'difference-membership v (list 'SINGLETON x) y))
              (f2 (dk-cite! 'intersection-membership v p y))
              (f3 (dk-cite! 'difference-membership 'CC (list 'SINGLETON x) y))
              (f4 (dk-cite! 'subset-mem-fwd v 'CC y)))
          (cif-only-prop! f1 f2 f3 f4)))))
  (dk-cite! 'class-extensionality d i)
  (subst (list '= d i))
  (cif-and! (list 'IS-OPEN cif-nfm v) (list 'IS-OPEN cif-nfm p))
  (dk-cite! 'inter-of-opens-open cif-nfm v p)
  (ass))
(qed 'cif-open-minus-point)

;;; (2) Cauchy for a closed road in a convex open subset of an open set where f is
;;; continuous, and holomorphic except at one point
(define cif-ux '(DIFFERENCE u (SINGLETON cifx_)))
(define cif-E
  (list (list 'IS-OPEN cif-nfm 'u) '(IN f (FUN u CC)) (cif-cont 'u 'f) '(IN cifx_ u)
        (list 'HOLOMORPHIC-ON cif-ux (list 'RESTRICT 'f cif-ux))))
(define cif-road-h '((IS-ROAD pgam dgam a b)))
(sp (make-wff (cif-all '(u f cifx_) (cif-imps cif-E
  (list 'FORALL 'cifv_ (cif-imps (list (list 'IS-OPEN cif-nfm 'cifv_) '(IS-CONVEX cifv_) '(SUBSET cifv_ u))
    (cif-all '(pgam dgam a b)
      (cif-imps (list '(IS-ROAD pgam dgam a b) '(SUBSET (TRACE pgam a b) cifv_) '(= (pgam b) (pgam a)))
        '(= (LINE-INT f pgam dgam a b) 0)))))))))
(dk-peel!)
(let* ((v 'cifv_) (x 'cifx_) (g (list 'RESTRICT 'f v)) (tr '(TRACE pgam a b))
       (hux (list 'RESTRICT 'f cif-ux)))
  (fact 'nf-cc-is-metric-space)
  (fact 'nf-metric-carrier 'CC-NORMED-FIELD)
  (fact 'cc-nf-carr)
  (dk-have! (list '== (list 'PTS cif-nfm) 'CC)
    (lambda () (subst (list '== (list 'PTS cif-nfm) '(CARR CC-NORMED-FIELD))) (ass)))
  (dk-cite! 'cc-open-subset-cc 'u)
  (dk-cite! 'cc-open-subset-cc v)
  (dk-have! (list 'SUBSET 'u (list 'PTS cif-nfm))
    (lambda () (subst (list '== (list 'PTS cif-nfm) 'CC)) (ass)))
  (dk-cite! 'holomorphic-on-open cif-ux hux)
  (dk-cite! 'holomorphic-on-in-fun cif-ux hux)
  (dk-cite! 'subset-trans tr v 'u)
  (dk-cite! 'restrict-in-fun 'f 'u 'CC v)
  (dk-have! (cif-cont v g)
    (lambda ()
      (let* ((y (dk-di-var!)))
        (fact 'subset-mem-fwd v 'u y)
        (dk-apply! (dk-ctx-form (cif-cont 'u 'f)) y)
        (dk-cite! 'subspace-restrict-continuous-at cif-nfm 'u v cif-nfm 'f y)
        (ass))))
  (dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ tr) (list '== (list g 'wnx_) '(f wnx_))))
    (lambda ()
      (let* ((z (dk-di-var!)))
        (fact 'subset-mem-fwd tr v z)
        (dk-cite! 'restrict-apply 'f v z)
        (ass))))
  (dk-cite! 'line-int-domain-congruence 'u 'f 'pgam 'dgam 'a 'b v g)
  (subst (list '= '(LINE-INT f pgam dgam a b) (list 'LINE-INT g 'pgam 'dgam 'a 'b)))
  (fact 'subset-mem-fwd 'u 'CC x)
  (use-em (list 'IN x v)
    (lambda ()
      (let* ((w (list 'DIFFERENCE v (list 'SINGLETON x)))
             (gw (list 'RESTRICT g w)) (hw (list 'RESTRICT hux w)))
        (dk-cite! 'cif-open-minus-point v x)
        (dk-have! (list 'SUBSET w v)
          (lambda () (let* ((z (subset-by-element!)))
                       (let* ((f1 (dk-cite! 'difference-membership v (list 'SINGLETON x) z)))
                         (cif-only-prop! f1 (list 'IN z w))))))
        (dk-have! (list 'SUBSET w cif-ux)
          (lambda () (let* ((z (subset-by-element!)))
                       (let* ((f1 (dk-cite! 'difference-membership v (list 'SINGLETON x) z))
                             (f2 (dk-cite! 'difference-membership 'u (list 'SINGLETON x) z))
                             (f3 (dk-cite! 'subset-mem-fwd v 'u z)))
                         (cif-only-prop! f1 f2 f3 (list 'IN z w))))))
        (dk-cite! 'holomorphic-on-restrict cif-ux hux w)
        (dk-cite! 'restrict-in-fun g v 'CC w)
        (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ w) (list '== (list gw 'hbx_) (list hw 'hbx_))))
          (lambda ()
            (let* ((z (dk-di-var!)))
              (fact 'subset-mem-fwd w v z)
              (fact 'subset-mem-fwd w cif-ux z)
              (dk-cite! 'restrict-apply g w z) (dk-cite! 'restrict-apply 'f v z)
              (dk-cite! 'restrict-apply hux w z) (dk-cite! 'restrict-apply 'f cif-ux z)
              (subst (list '== (list gw z) (list g z)))
              (subst (list '== (list g z) (list 'f z)))
              (subst (list '== (list hw z) (list hux z)))
              (subst (list '== (list hux z) (list 'f z)))
              (qrfl))))
        (dk-cite! 'holomorphic-transfer-ptwise-eq w gw hw)
        (dk-cite! 'cauchy-convex-closed-except v g x 'pgam 'dgam 'a 'b)
        (ass)))
    (lambda ()
      (let* ((hv (list 'RESTRICT hux v)))
        (dk-have! (list 'SUBSET v cif-ux)
          (lambda ()
            (let* ((z (subset-by-element!)))
              (fact 'subset-mem-fwd v 'u z)
              (dk-have! (list 'NOT (list 'IN z (list 'SINGLETON x)))
                (lambda ()
                  (di)
                  (let* ((sm (dk-cite! 'singleton-membership x z)))
                    (dk-have! (list '= z x) (lambda () (cif-only-prop! sm (list 'IN z (list 'SINGLETON x)))))
                    (dk-have! (list 'IN x v) (lambda () (subst (list '= x z)) (ass)))
                    (ai (dk-ctx-form (list 'NOT (list 'IN x v)))))))
              (let* ((f1 (dk-cite! 'difference-membership 'u (list 'SINGLETON x) z)))
                (cif-only-prop! f1 (list 'IN z 'u) (list 'NOT (list 'IN z (list 'SINGLETON x))))))))
        (dk-cite! 'holomorphic-on-restrict cif-ux hux v)
        (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ v) (list '== (list g 'hbx_) (list hv 'hbx_))))
          (lambda ()
            (let* ((z (dk-di-var!)))
              (fact 'subset-mem-fwd v cif-ux z)
              (dk-cite! 'restrict-apply 'f v z)
              (dk-cite! 'restrict-apply hux v z) (dk-cite! 'restrict-apply 'f cif-ux z)
              (subst (list '== (list g z) (list 'f z)))
              (subst (list '== (list hv z) (list hux z)))
              (subst (list '== (list hux z) (list 'f z)))
              (qrfl))))
        (dk-cite! 'holomorphic-transfer-ptwise-eq v g hv)
        (dk-cite! 'cauchy-convex-closed v g 'pgam 'dgam 'a 'b)
        (ass)))))
(qed 'cauchy-convex-sub-except)

;;; (3) the same for an open disc B(c, r) inside u
(sp (make-wff (cif-all '(u f cifx_) (cif-imps cif-E
  '(FORALL c (IMPLIES (IN c CC) (FORALL r (IMPLIES (IN r RR) (IMPLIES (< 0 r)
    (IMPLIES (SUBSET (BALL CC-MS c r) u)
      (FORALL pgam (FORALL dgam (FORALL a (FORALL b
        (IMPLIES (IS-ROAD pgam dgam a b) (IMPLIES (SUBSET (TRACE pgam a b) (BALL CC-MS c r))
          (IMPLIES (= (pgam b) (pgam a)) (= (LINE-INT f pgam dgam a b) 0))))))))))))))))))
(dk-peel!)
(let* ((bl '(BALL CC-MS c r)))
  (fact 'cc-is-metric-space)
  (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
  (dk-have! '(IN c (PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
  (dk-have! '(<= 0 r) (lambda () (dk-ineq! '(< 0 r))))
  (dk-have! '(NOT (= 0 r)) (lambda () (fact 'rr-zero-in) (dk-split-all! (list (dk-cite! 'pw-lt-ne 0 'r))) (ass)))
  (cif-and! '(IN r RR) (cif-and! '(<= 0 r) '(NOT (= 0 r))))
  (dk-cite! 'ball-is-open 'CC-MS 'c 'r)
  (let* ((iff (dk-cite! 'cc-ms-open-iff bl)))
    (dk-have! (list 'IS-OPEN cif-nfm bl) (lambda () (cif-only-prop! iff (list 'IS-OPEN 'CC-MS bl)))))
  (dk-cite! 'cc-ball-is-convex 'c 'r)
  (dk-cite! 'cauchy-convex-sub-except 'u 'f 'cifx_ bl 'pgam 'dgam 'a 'b)
  (ass))
(qed 'cauchy-disc-except)
;;; (4) the derivative of w |-> 1/(w - c) on CC \ {c}
(define (cif-R c) (list 'VNB-LAMBDA 'cifv_ (cif-pz c) (list 'recip (list '- 'cifv_ c))))
(define (cif-S c) (list 'VNB-LAMBDA 'cifv_ (cif-pz c) (list '- 'cifv_ c)))
(define (cif-P c n) (list 'VNB-LAMBDA 'cifv_ (cif-pz c) (list 'power (list 'recip (list '- 'cifv_ c)) n)))
(define (cif-sq-recip w c) (list '* (list 'recip (list '- w c)) (list 'recip (list '- w c))))
(sp (make-wff (list 'FORALL 'cifc_ (list 'IMPLIES '(IN cifc_ CC)
  (list 'FORALL 'cifw_ (list 'IMPLIES (list 'IN 'cifw_ (cif-pz 'cifc_))
    (list 'IS-DIFF-ON 'CC-NORMED-FIELD (cif-pz 'cifc_) (cif-R 'cifc_) 'cifw_
          (list '- (cif-sq-recip 'cifw_ 'cifc_)))))))))
(dk-peel!)
(let* ((c 'cifc_) (w 'cifw_) (d (cif-pz c)) (S (cif-S c)) (R (cif-R c)))
  (cif-pz-setup! c)
  (cif-pz-open! c w)
  (cif-lam-typ! S d (lambda (v) (cif-pz-open! c v)))
  (cif-lam-typ! R d (lambda (v) (cif-pz-open! c v)))
  (fact 'rr-zero-in) (fact 'cc-one-in)
  (dk-have! '(<= 0 0) (lambda () (dk-ineq!)))
  (let* ((imp (dk-cite! 'cc-diff-on-quadratic d S w 1 0)))
    (cif-detach! imp
      (lambda ()
        (let* ((x (dk-di-var!)))
          (cif-pz-open! c x)
          (dk-lam-b!)
          (let* ((g (dk-goal)) (e (cadr (cadr g))) (mm (caddr (caddr g))))
            (dk-have! (list '= e 0) (lambda () (crs)))
            (subst (list '= e 0))
            (fact 'cc-magnitude-zero)
            (subst '(= (magnitude 0) 0))
            (cif-rr! mm)
            (dk-have! (list '= (list '* 0 mm) 0) (lambda () (crs)))
            (subst (list '= (list '* 0 mm) 0))
            (dk-ineq!))))))
  (dk-have! (list 'FORALL 'cry_ (list 'IMPLIES (list 'IN 'cry_ d) (list 'NOT (list '= (list S 'cry_) 0))))
    (lambda () (let* ((y (dk-di-var!))) (cif-pz-open! c y) (dk-lam-b!) (ass))))
  (dk-have! (list 'FORALL 'cry_ (list 'IMPLIES (list 'IN 'cry_ d) (list '== (list R 'cry_) (list 'recip (list S 'cry_)))))
    (lambda () (let* ((y (dk-di-var!))) (cif-pz-open! c y) (dk-lam-b!) (qrfl))))
  (let* ((r1 (dk-cite! 'diff-on-recip-cc d S w 1 R))
         (v1 (list-ref r1 5))
         (gv (list-ref (dk-goal) 5))
         (a (list 'recip (list '- w c))))
    (cif-cc! a)
    (dk-have! (list '= gv v1)
      (lambda ()
        (dk-lam-b!)
        (subst (dk-cite! 'cc-recip-mul (list '- w c) (list '- w c)))
        (crs)))
    (subst (list '= gv v1))
    (ass)))
(qed 'cif-recip-shift-diff)

;;; (5) the derivative of w |-> (1/(w - c))^(j+1): -(j+1) (1/(w - c))^(j+2)
(define (cif-pd-goal j)
  (list 'FORALL 'cifc_ (list 'IMPLIES '(IN cifc_ CC)
    (list 'FORALL 'cifw_ (list 'IMPLIES (list 'IN 'cifw_ (cif-pz 'cifc_))
      (list 'IS-DIFF-ON 'CC-NORMED-FIELD (cif-pz 'cifc_) (cif-P 'cifc_ (list 'succ j)) 'cifw_
            (list '* (list '- (list 'succ j)) (list 'power (list 'recip (list '- 'cifw_ 'cifc_)) (list 'succ (list 'succ j))))))))))
;;; a typed in CC, n in NN: land a^succ(n) = a * a^n
(define (cif-pow-succ! a n)
  (cif-cc! a) (cif-nn! n)
  (cif-and! (list 'IN a 'CC) (list 'IN n 'NN))
  (dk-cite! 'power-succ a n))
(define (cif-carr-typ! lam d)
  (fact 'cc-nf-carr)
  (dk-have! (list 'IN lam (list 'FUN d '(CARR CC-NORMED-FIELD)))
    (lambda () (subst '(== (CARR CC-NORMED-FIELD) CC)) (ass))))
(sp (make-wff (list 'FORALL 'cifj_ (list 'IMPLIES '(IN cifj_ NN) (cif-pd-goal 'cifj_)))))
(define cif-pd-br (use-induction))
(dk-focus! (cdr (assq 'base cif-pd-br)))
(dk-peel!)
(let* ((c 'cifc_) (w 'cifw_) (d (cif-pz c)) (R (cif-R c)) (P (cif-P c '(succ 0)))
       (a (list 'recip (list '- w c))))
  (cif-pz-setup! c)
  (cif-pz-open! c w)
  (fact 'nn-zero-in)
  (fact 'nn-succ-closed 0)
  (cif-lam-typ! P d (lambda (v) (cif-pz-open! c v)))
  (cif-carr-typ! P d)
  (dk-cite! 'cif-recip-shift-diff c w)
  (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ d) (list '== (list P 'hbx_) (list R 'hbx_))))
    (lambda ()
      (let* ((x (dk-di-var!)) (ax (list 'recip (list '- x c))))
        (cif-pz-open! c x)
        (dk-lam-b!)
        (subst (cif-pow-succ! ax 0))
        (subst (dk-cite! 'power-zero ax))
        (dk-have! (list '= (list '* ax 1) ax) (lambda () (crs)))
        (subst (list '= (list '* ax 1) ax))
        (qrfl))))
  (dk-cite! 'diff-on-transfer-ptwise-eq 'CC-NORMED-FIELD d P R w (list '- (cif-sq-recip w c)))
  (let* ((gv (list-ref (dk-goal) 5)))
    (cif-cc! a)
    (dk-have! (list '= gv (list '- (cif-sq-recip w c)))
      (lambda ()
        (subst (cif-pow-succ! a '(succ 0)))
        (subst (cif-pow-succ! a 0))
        (subst (dk-cite! 'power-zero a))
        (crs)))
    (subst (list '= gv (list '- (cif-sq-recip w c))))
    (ass)))
(dk-focus! (cdr (assq 'step cif-pd-br)))
(define cif-pd-n (cdr (assq 'var cif-pd-br)))
(define cif-pd-ih (cdr (assq 'ih cif-pd-br)))
(dk-peel!)
(let* ((n cif-pd-n) (sn (list 'succ n)) (ssn (list 'succ sn))
       (c (cadr (dk-pick (lambda (f) (and (cif-op? f 'IN 3) (eq? (caddr f) 'CC))) "c")))
       (wt (dk-pick (lambda (f) (and (cif-op? f 'IN 3) (pair? (caddr f)) (eq? (car (caddr f)) 'DIFFERENCE))) "w"))
       (w (cadr wt))
       (d (cif-pz c)) (R (cif-R c)) (Pn (cif-P c sn)) (P (cif-P c ssn))
       (a (list 'recip (list '- w c))))
  (cif-pz-setup! c)
  (cif-pz-open! c w)
  (fact 'nn-succ-closed n)
  (fact 'nn-succ-closed sn)
  (cif-lam-typ! P d (lambda (v) (cif-pz-open! c v)))
  (cif-lam-typ! Pn d (lambda (v) (cif-pz-open! c v)))
  (cif-lam-typ! R d (lambda (v) (cif-pz-open! c v)))
  (cif-carr-typ! P d)
  (fact 'cc-is-normed-field)
  (let* ((dr (dk-cite! 'cif-recip-shift-diff c w))
         (dp (dk-apply! cif-pd-ih c w))
         (l (list-ref dr 5)) (m (list-ref dp 5))
         (pr (dk-cite! 'diff-on-product 'CC-NORMED-FIELD d R Pn w l m))
         (plam (list-ref pr 3)) (pval (list-ref pr 5)))
    (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ d) (list '== (list P 'hbx_) (list plam 'hbx_))))
      (lambda ()
        (let* ((x (dk-di-var!)) (ax (list 'recip (list '- x c))) (q (list 'power ax sn)))
          (cif-pz-open! c x)
          (dk-lam-b!)
          (cif-cc! q)
          (subst (dk-cite! 'cc-nf-mul-apply ax q))
          (subst (cif-pow-succ! ax sn))
          (qrfl))))
    (dk-cite! 'diff-on-transfer-ptwise-eq 'CC-NORMED-FIELD d P plam w pval)
    (let* ((gv (list-ref (dk-goal) 5))
           (q (list 'power a sn)))
      (cif-cc! a) (cif-cc! q) (cif-cc! l) (cif-cc! m)
      (dk-have! (list '= gv pval)
        (lambda ()
          (dk-lam-b!)
          (cif-cc! (list '* l q)) (cif-cc! (list '* m a))
          (subst (dk-cite! 'cc-nf-mul-apply l q))
          (subst (dk-cite! 'cc-nf-mul-apply m a))
          (subst (dk-cite! 'cc-nf-add-apply (list '* l q) (list '* m a)))
          (subst (cif-pow-succ! a ssn))
          (subst (cif-pow-succ! a sn))
          (subst (dk-cite! 'nn-succ-plus-one sn))
          (let* ((qv (dk-name! q 'CC)))
            (subst (list '= q qv))
            (cif-cc! sn)
            (let* ((sv (dk-name! sn 'CC)))
              (subst (list '= sn sv))
              (crs)))))
      (subst (list '= gv pval))
      (ass))))
(qed 'cif-recip-power-diff)
;;; (6) the integral of (1/(w - c))^(j+2) over a closed road off c is 0: the
;;; primitive is -(1/(j+1)) (1/(w - c))^(j+1)
(sp (make-wff (list 'FORALL 'cifj_ (list 'IMPLIES '(IN cifj_ NN)
  (list 'FORALL 'cifc_ (list 'IMPLIES '(IN cifc_ CC)
    (cif-all '(pgam dgam a b)
      (cif-imps (list '(IS-ROAD pgam dgam a b) (list 'SUBSET '(TRACE pgam a b) (cif-pz 'cifc_)) '(= (pgam b) (pgam a)))
        (list '= (list 'LINE-INT (cif-P 'cifc_ '(succ (succ cifj_))) 'pgam 'dgam 'a 'b) 0)))))))))
(dk-peel!)
(let* ((j 'cifj_) (c 'cifc_) (d (cif-pz c)) (sj (list 'succ j)) (ssj (list 'succ sj))
       (Pj (cif-P c sj)) (df (cif-P c ssj))
       (k (list '- (list 'recip sj)))
       (F (list 'VNB-LAMBDA 'cexy_ d (list '* k (list Pj 'cexy_)))))
  (cif-pz-setup! c)
  (fact 'nn-succ-closed j)
  (fact 'nn-succ-closed sj)
  (cif-cc! sj)
  (dk-cite! 'nn-succ-nonzero j)
  (cif-cc! k)
  (cif-lam-typ! Pj d (lambda (v) (cif-pz-open! c v)))
  (cif-lam-typ! df d (lambda (v) (cif-pz-open! c v)))
  (cif-lam-typ! F d (lambda (v) (cif-pz-open! c v) (cif-cc! (list 'power (list 'recip (list '- v c)) sj))))
  (cif-and! (list 'IN sj 'CC) (list 'NOT (list '= sj 0)))
  (dk-cite! 'cc-recip-inverse sj)
  (dk-have! (list 'FORALL 'hbz_ (list 'IMPLIES (list 'IN 'hbz_ d) (list 'IS-DIFF-ON 'CC-NORMED-FIELD d F 'hbz_ (list df 'hbz_))))
    (lambda ()
      (let* ((z (dk-di-var!))
             (az (list 'recip (list '- z c)))
             (p2 (list 'power az ssj))
             (dp (dk-cite! 'cif-recip-power-diff j c z))
             (m (list-ref dp 5))
             (sc (dk-cite! 'cc-diff-on-scale d Pj z m k)))
        (cif-pz-open! c z)
        (cif-cc! p2)
        (dk-have! (list '= (list df z) (list '* k m))
          (lambda ()
            (dk-lam-b!)
            (let* ((rv (dk-name! (list 'recip sj) 'CC))
                  (pv (dk-name! p2 'CC)))
              (subst (list '= p2 pv))
              (subst (list '= (list 'recip sj) rv))
              (dk-have! (list '= (list '* (list '- rv) (list '* (list '- sj) pv)) (list '* (list '* sj rv) pv)) (lambda () (crs)))
              (subst (list '= (list '* (list '- rv) (list '* (list '- sj) pv)) (list '* (list '* sj rv) pv)))
              (dk-have! (list '= (list '* sj rv) 1) (lambda () (subst (list '= rv (list 'recip sj))) (ass)))
              (subst (list '= (list '* sj rv) 1))
              (crs))))
        (subst (list '= (list df z) (list '* k m)))
        (ass))))
  (dk-have! (list 'HOLOMORPHIC-ON d F)
    (lambda ()
      (mac 'HOLOMORPHIC-ON)
      (dk-conj-close!
        (lambda ()
          (let* ((g (dk-goal)))
            (cond ((dk-asm? g) (ass))
                  ((cif-op? g 'FORALL 3)
                   (let* ((z (dk-di-var!)))
                     (ew (list df z))
                     (dk-apply! (dk-ctx-form (list 'FORALL 'hbz_ (list 'IMPLIES (list 'IN 'hbz_ d)
                                   (list 'IS-DIFF-ON 'CC-NORMED-FIELD d F 'hbz_ (list df 'hbz_))))) z)
                     (ass)))
                  (#t (error "cif: unexpected holomorphy conjunct" (expression->string g)))))))))
  (dk-cite! 'line-int-closed-road-of-derivative d F df 'pgam 'dgam 'a 'b)
  (ass))
(qed 'cif-recip-power-closed-zero)
;;; (7) the circle: its trace lies at distance r from the centre; it is closed
(define cif-tp '(* 2 PI))
(define cif-I (list 'CCINT 0 cif-tp))
(define cif-C '(CIRCLE-PATH c r))
(define cif-Cd '(CIRCLE-DERIV c r))
(define cif-T (list 'TRACE cif-C 0 cif-tp))
(define (cif-kern z) (list 'VNB-LAMBDA 'wnw_ (cif-pz z) (list 'recip (list '- 'wnw_ z))))
(define (cif-in-I! v)
  (dk-have! (list 'IN v cif-I)
    (lambda () (mac 'ccint-membership)
               (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (dk-ineq! (list '< 0 cif-tp) '(< 0 PI))))))))
(define (cif-circle-basics!)
  (fact 'rr-zero-in)
  (cif-rr! cif-tp)
  (dk-have! (list '< 0 cif-tp) (lambda () (dk-ineq! '(< 0 PI))))
  (dk-cite! 'circle-is-road 'c 'r)
  (fact 'is-road-is-path cif-C cif-Cd 0 cif-tp)
  (fact 'is-path-in-fun cif-C 0 cif-tp)
  (dk-cite! 'trace-subset-cc cif-C 0 cif-tp))

(sp (make-wff (list 'FORALL 'c (list 'IMPLIES '(IN c CC) (list 'FORALL 'r (list 'IMPLIES '(IN r RR) (list 'IMPLIES '(<= 0 r)
  (list 'FORALL 'cify_ (list 'IMPLIES (list 'IN 'cify_ cif-T) '(= (magnitude (- cify_ c)) r))))))))))
(dk-peel!)
(let* ((y 'cify_) (img (list 'IN y (list 'IMAGE cif-C cif-I))))
  (cif-circle-basics!)
  (fact 'trace-unfold cif-C 0 cif-tp)
  (dk-have! img (lambda () (subst (list '== (list 'IMAGE cif-C cif-I) cif-T)) (ass)))
  (let* ((ex (car (dk-landed (lambda () (mac-h 'image-membership-iff (dk-ctx-form img))))))
         (ex2 (if (dk-head-is? ex 'AND) (begin (dk-split! ex) (dk-pick (dk-head? 'FORSOME) "image witness")) ex))
         (t (dk-skolem! ex2))
         (e (list 'CC-EXP (list '* '+i t)))
         (x (list '* 'r e)))
    (dk-split-all!)
    (fact 'ccint-elt-in-rr 0 cif-tp t)
    (subst (list '= y (list cif-C t)))
    (mac 'CIRCLE-PATH)
    (dk-lam-b!)
    (cif-cc! x)
    (dk-have! (list '= (list '- (list '+ 'c x) 'c) x) (lambda () (crs)))
    (subst (list '= (list '- (list '+ 'c x) 'c) x))
    (cif-and! '(IN r CC) (list 'IN e 'CC))
    (subst (dk-cite! 'cc-magnitude-mul 'r e))
    (subst (dk-cite! 'cc-exp-magnitude-imaginary t))
    (subst (dk-cite! 'rr-magnitude-is-abs 'r))
    (subst (dk-cite! 'rr-abs-of-nonneg 'r))
    (crs)))
(qed 'circle-trace-magnitude)

(sp (make-wff (list 'FORALL 'c (list 'IMPLIES '(IN c CC) (list 'FORALL 'r (list 'IMPLIES '(IN r RR)
  (list '= (list cif-C cif-tp) (list cif-C 0))))))))
(dk-peel!)
(cif-rr! cif-tp)
(dk-have! (list '< 0 cif-tp) (lambda () (dk-ineq! '(< 0 PI))))
(fact 'rr-zero-in)
(cif-in-I! 0)
(cif-in-I! cif-tp)
(mac 'CIRCLE-PATH)
(dk-lam-b!)
(let* ((a1 (list '* '+i cif-tp)) (a2 (list '* cif-tp '+i)) (b1 '(* +i 0)))
  (cif-cc! a1) (cif-cc! a2) (cif-cc! b1)
  (cif-cc! (list 'CC-EXP a1)) (cif-cc! (list 'CC-EXP a2)) (cif-cc! (list 'CC-EXP b1)) (cif-cc! '(CC-EXP 0))
  (dk-have! (list '= a1 a2) (lambda () (crs)))
  (dk-congr! (list '= a1 a2) (lambda (w) (list 'CC-EXP w)))
  (fact 'cc-exp-two-pi-i)
  (dk-have! (list '= b1 0) (lambda () (crs)))
  (dk-congr! (list '= b1 0) (lambda (w) (list 'CC-EXP w)))
  (fact 'cc-exp-zero)
  (subst (list '= (list 'CC-EXP a1) (list 'CC-EXP a2)))
  (subst (list '= (list 'CC-EXP a2) 1))
  (subst (list '= (list 'CC-EXP b1) '(CC-EXP 0)))
  (subst '(= (CC-EXP 0) 1))
  (cif-cc! '(+ c (* r 1)))
  (rfl))
(qed 'circle-path-closed)
;;; (8) THE WINDING NUMBER OF THE CIRCLE IS 1 AT EVERY POINT OF THE OPEN DISC.
;;; Lemma 3.33 (cauchy-kernel-integral-series) with the weight 1 on the trace:
;;; int 1/(w - z) = sum_k a_k (z - c)^k, a_k = int (1/(w - c))^(k+1); a_k = 0 for
;;; k >= 1 (cif-recip-power-closed-zero), so the sum is a_0 = int 1/(w - c).
(define (cif-circ-pt! y)
  ;; y in the trace of the circle (c, r in context, 0 < r): y in CC, |y - c| = r,
  ;; r <= |y - c|, y /= c, y - c /= 0, y in CC \ {c}
  (let* ((m (list 'magnitude (list '- y 'c))))
    (cif-steps
      (lambda () (fact 'subset-mem-fwd cif-T 'CC y))
      (lambda () (dk-cite! 'circle-trace-magnitude 'c 'r y))
      (lambda () (cif-rr! m))
      (lambda () (dk-have! (list '<= 'r m) (lambda () (dk-ineq! (list '= m 'r)))))
      (lambda ()
        (dk-have! (list 'NOT (list '= y 'c))
          (lambda ()
            (di)
            (dk-have! (list '= m 0)
              (lambda () (subst (list '= y 'c))
                         (dk-have! '(= (- c c) 0) (lambda () (crs)))
                         (subst '(= (- c c) 0))
                         (fact 'cc-magnitude-zero)
                         (ass)))
            (dk-absurd! (list 'IN m 'RR) '(IN r RR) (list '= m 0) (list '= m 'r) '(< 0 r)))))
      (lambda () (cif-sub-nz! y 'c))
      (lambda () (cif-pz-in! 'c y)))))
(define (cif-circ-not-z! y)
  ;; y in the trace, |z - c| < r: y /= z, y in CC \ {z}
  (cif-steps
    (lambda ()
      (dk-have! (list 'NOT (list '= y 'z))
        (lambda ()
          (di)
          (dk-have! '(= (magnitude (- z c)) r)
            (lambda () (subst (list '= 'z y)) (ass)))
          (cif-rr! '(magnitude (- z c)))
          (dk-absurd! '(IN (magnitude (- z c)) RR) '(IN r RR) '(= (magnitude (- z c)) r) '(< (magnitude (- z c)) r)))))
    (lambda () (cif-sub-nz! y 'z))
    (lambda () (cif-pz-in! 'z y))))
(define (cif-Hk g k)
  (list 'VNB-LAMBDA 'aiw_ cif-T (list '* (list g 'aiw_) (list 'power '(recip (- aiw_ c)) (list 'succ k)))))
(define (cif-LI f) (list 'LINE-INT f cif-C cif-Cd 0 cif-tp))
;;; the trace lies in CC \ {p} (p = c or z); land it
(define (cif-trace-in-pz! p)
  (dk-have! (list 'SUBSET cif-T (cif-pz p))
    (lambda ()
      (let* ((y (subset-by-element!)) (leaf (proof-state-focus *ps*)))
        (cif-circ-pt! y)
        (if (eq? p 'z) (cif-circ-not-z! y))
        (if (not (sequent-node-grounded? leaf)) (ass))))))
;;; the winding kernel about p: typed, continuous on CC \ {p}
(define (cif-kern-setup! p)
  (let* ((dd (cif-pz p)) (k (cif-kern p)))
    (dk-cite! 'winding-integrand-holomorphic p)
    (dk-cite! 'holomorphic-on-in-fun dd k)
    (dk-cite! 'holomorphic-on-continuous dd k)
    (dk-cite! 'holomorphic-on-open dd k)
    (dk-cite! 'cc-open-subset-cc dd)))

(sp (make-wff '(FORALL c (IMPLIES (IN c CC) (FORALL r (IMPLIES (IN r RR) (IMPLIES (< 0 r)
  (FORALL z (IMPLIES (IN z CC) (IMPLIES (< (magnitude (- z c)) r)
    (= (WINDING (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI) z) 1)))))))))))
(dk-peel!)
(cif-circle-basics!)
(dk-have! '(<= 0 r) (lambda () (dk-ineq! '(< 0 r))))
(dk-cite! 'trace-is-set cif-C 0 cif-tp)
(fact 'subset-refl cif-T)
(dk-cite! 'circle-path-closed 'c 'r)
(cif-pz-setup! 'c)
(cif-pz-setup! 'z)
(cif-kern-setup! 'c)
(cif-kern-setup! 'z)
(cif-trace-in-pz! 'c)
(cif-trace-in-pz! 'z)
(fact 'cc-one-in)
(define cif-wi-pair
  (dk-abstract! cif-T 'CC (lambda (y) 1) (lambda (y) (ass))))
(define cif-wi-g (car cif-wi-pair))
(define cif-wi-gv (cdr cif-wi-pair))
(dk-cite! 'aif-cont-const cif-T 1 cif-wi-g)
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cif-T) '(<= r (magnitude (- aix_ c)))))
  (lambda ()
    (let* ((y (dk-di-var!)) (m (list 'magnitude (list '- y 'c))))
      (fact 'subset-mem-fwd cif-T 'CC y)
      (dk-cite! 'circle-trace-magnitude 'c 'r y)
      (cif-rr! m)
      (dk-ineq! (list '= m 'r)))))
(define cif-wi-ks (dk-cite! 'cauchy-kernel-integral-series cif-T 'c 'r cif-wi-g cif-C cif-Cd 0 cif-tp 'z))
(define cif-wi-tt (cadr cif-wi-ks))
(define cif-wi-lz (caddr cif-wi-ks))
;;; G(y) = 1 on the trace, as an equation at a point y of the trace
(define (cif-wi-g1! y) (dk-apply! cif-wi-gv y))
;;; a_0 = int 1/(w - c)
(define cif-wi-h0 (cif-Hk cif-wi-g 0))
(cif-lam-typ! cif-wi-h0 cif-T (lambda (v) (cif-tpt! v) (cif-wi-g1! v) (fact 'nn-zero-in) (fact 'nn-succ-closed 0)
                                   (cif-lam-b-if!) (subst (list '== (list cif-wi-g v) 1))))
(dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ cif-T) (list '== (list cif-wi-h0 'wnx_) (list (cif-kern 'c) 'wnx_))))
  (lambda ()
    (let* ((x (dk-di-var!)) (ax (list 'recip (list '- x 'c))))
      (cif-tpt! x)
      (cif-wi-g1! x)
      (dk-lam-b!)
      (subst (list '== (list cif-wi-g x) 1))
      (subst (cif-pow-succ! ax 0))
      (subst (dk-cite! 'power-zero ax))
      (dk-have! (list '= (list '* 1 (list '* ax 1)) ax) (lambda () (crs)))
      (subst (list '= (list '* 1 (list '* ax 1)) ax))
      (qrfl))))
(define cif-wi-a0
  (dk-cite! 'line-int-domain-congruence (cif-pz 'c) (cif-kern 'c) cif-C cif-Cd 0 cif-tp cif-T cif-wi-h0))
(dk-cite! 'line-int-in-cc (cif-pz 'c) (cif-kern 'c) cif-C cif-Cd 0 cif-tp)
;;; a_(q+1) = 0
(define cif-wi-az
  (list 'FORALL 'cifq_ (list 'IMPLIES '(IN cifq_ NN) (list '= (cif-LI (cif-Hk cif-wi-g '(succ cifq_))) 0))))
(dk-have! cif-wi-az
  (lambda ()
    (let* ((q (dk-di-var!)) (sq (list 'succ q)) (ssq (list 'succ sq))
           (d (cif-pz 'c)) (R (cif-R 'c)) (P (cif-P 'c ssq)) (H (cif-Hk cif-wi-g sq)))
      (fact 'nn-succ-closed q)
      (fact 'nn-succ-closed sq)
      (cif-lam-typ! P d (lambda (v) (cif-pz-open! 'c v)))
      (cif-lam-typ! R d (lambda (v) (cif-pz-open! 'c v)))
      (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ d) '(NOT (= aix_ c))))
        (lambda () (let* ((v (dk-di-var!))) (cif-steps (lambda () (cif-pz-open! 'c v)) ass))))
      (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ d) (list '== (list R 'aix_) '(recip (- aix_ c)))))
        (lambda () (let* ((v (dk-di-var!))) (cif-pz-open! 'c v) (dk-lam-b!) (qrfl))))
      (dk-cite! 'aif-cont-recip-shift d 'c R)
      (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ d) (list '== (list P 'aix_) (list 'power (list R 'aix_) ssq))))
        (lambda () (let* ((v (dk-di-var!))) (cif-pz-open! 'c v) (dk-lam-b!) (qrfl))))
      (dk-cite! 'aif-cont-power-of d R ssq P)
      (cif-lam-typ! H cif-T (lambda (v) (cif-tpt! v) (cif-wi-g1! v)
                                 (cif-lam-b-if!) (subst (list '== (list cif-wi-g v) 1))))
      (dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ cif-T) (list '== (list H 'wnx_) (list P 'wnx_))))
        (lambda ()
          (let* ((x (dk-di-var!)) (px (list 'power (list 'recip (list '- x 'c)) ssq)))
            (cif-tpt! x)
            (cif-wi-g1! x)
            (dk-lam-b!)
            (subst (list '== (list cif-wi-g x) 1))
            (cif-cc! px)
            (dk-have! (list '= (list '* 1 px) px) (lambda () (crs)))
            (subst (list '= (list '* 1 px) px))
            (qrfl))))
      (let* ((e1 (dk-cite! 'line-int-domain-congruence d P cif-C cif-Cd 0 cif-tp cif-T H))
            (e2 (dk-cite! 'cif-recip-power-closed-zero q 'c cif-C cif-Cd 0 cif-tp)))
        (cif-subst-ass! e1)))))
;;; every a_k is a complex number
(define cif-wi-at
  (list 'FORALL 'cifk_ (list 'IMPLIES '(IN cifk_ NN) (list 'IN (cif-LI (cif-Hk cif-wi-g 'cifk_)) 'CC))))
(dk-have! cif-wi-at
  (lambda ()
    (let* ((k (dk-di-var!)))
      (use-cases (dk-fact! 'nn-zero-or-succ k)
        (lambda ()
          (subst (list '= k 0))
          (cif-subst-ass! cif-wi-a0))
        (lambda ()
          (let* ((q (dk-skolem! (dk-pick (dk-head? 'FORSOME) "the predecessor"))))
            (subst (list '= k (list 'succ q)))
            (fact 'cc-zero-in)
            (cif-subst-ass! (dk-apply! (dk-ctx-form cif-wi-az) q))))))))
(define (cif-wi-typ-tt! lam)
  (cif-lam-typ! lam 'NN (lambda (v) (dk-apply! (dk-ctx-form cif-wi-at) v) (cif-cc! '(- z c)))))
(cif-wi-typ-tt! cif-wi-tt)
(define cif-wi-sz (dk-cite! 'cps-sum-at-zero cif-wi-tt))
(dk-split-all! (list cif-wi-sz))
(define cif-wi-tt2 (cadr (dk-pick (dk-head? 'CC-SERIES-CONVERGES) "the series at 0")))
(cif-wi-typ-tt! cif-wi-tt2)
(dk-fun-ext! cif-wi-tt cif-wi-tt2 'NN 'CC #f #f
  (lambda (v)
    (dk-apply! (dk-ctx-form cif-wi-at) v)
    (use-cases (dk-fact! 'nn-zero-or-succ v)
      (lambda ()
        (subst (list '= v 0))
        (fact 'nn-zero-in)
        (dk-lam-b!)
        (subst (dk-cite! 'power-zero 0))
        (cif-cc! '(- z c))
        (subst (dk-cite! 'power-zero '(- z c)))
        (subst cif-wi-a0)
        (crs))
      (lambda ()
        (let* ((q (dk-skolem! (dk-pick (dk-head? 'FORSOME) "the predecessor"))))
          (subst (list '= v (list 'succ q)))
          (fact 'nn-succ-closed q)
          (dk-lam-b!)
          (subst (dk-apply! (dk-ctx-form cif-wi-az) q))
          (subst (dk-cite! 'power-zero-base q))
          (cif-cc! '(- z c))
          (fact 'nn-succ-closed q)
          (cif-cc! (list 'power '(- z c) (list 'succ q)))
          (crs))))))
(dk-have! (list 'CC-SERIES-CONVERGES-TO cif-wi-tt2 cif-wi-lz)
  (lambda () (cif-subst-ass! (list '= cif-wi-tt2 cif-wi-tt))))
(fact 'cc-series-limit-converges-to cif-wi-tt2)
(define cif-wi-ps (list 'VNB-LAMBDA 'k 'NN (list 'CC-SERIES-PARTIAL-SUM cif-wi-tt2 'k)))
(define cif-wi-l2 (list 'CC-SERIES-LIMIT cif-wi-tt2))
(dk-project! (list 'CONVERGES-TO 'CC-MS cif-wi-ps cif-wi-lz) 'cc-series-converges-to
             (list 'CC-SERIES-CONVERGES-TO cif-wi-tt2 cif-wi-lz))
(dk-project! (list 'CONVERGES-TO 'CC-MS cif-wi-ps cif-wi-l2) 'cc-series-converges-to
             (list 'CC-SERIES-CONVERGES-TO cif-wi-tt2 cif-wi-l2))
;;; the integral about z equals the integral about c
(define cif-wi-hz (cadr cif-wi-lz))
(cif-lam-typ! cif-wi-hz cif-T (lambda (v) (cif-tpt! v 'z) (cif-wi-g1! v)
                                   (cif-lam-b-if!) (subst (list '== (list cif-wi-g v) 1))))
(dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ cif-T) (list '== (list cif-wi-hz 'wnx_) (list (cif-kern 'z) 'wnx_))))
  (lambda ()
    (let* ((x (dk-di-var!)) (ax (list 'recip (list '- x 'z))))
      (cif-tpt! x 'z)
      (cif-wi-g1! x)
      (dk-lam-b!)
      (subst (list '== (list cif-wi-g x) 1))
      (cif-cc! ax)
      (dk-have! (list '= (list '* 1 ax) ax) (lambda () (crs)))
      (subst (list '= (list '* 1 ax) ax))
      (qrfl))))
(define cif-wi-ez
  (dk-cite! 'line-int-domain-congruence (cif-pz 'z) (cif-kern 'z) cif-C cif-Cd 0 cif-tp cif-T cif-wi-hz))
(dk-cite! 'line-int-in-cc (cif-pz 'z) (cif-kern 'z) cif-C cif-Cd 0 cif-tp)
(dk-cite! 'metric-limit-unique 'CC-MS cif-wi-ps cif-wi-lz cif-wi-l2)
(dk-have! (list '= (cif-LI (cif-kern 'z)) (cif-LI (cif-kern 'c)))
  (lambda ()
    (subst (list '= (cif-LI (cif-kern 'z)) cif-wi-lz))
    (subst (list '= cif-wi-lz cif-wi-l2))
    (subst (list '= cif-wi-l2 (list cif-wi-tt 0)))
    (fact 'nn-zero-in)
    (dk-lam-b!)
    (cif-cc! '(- z c))
    (subst (dk-cite! 'power-zero '(- z c)))
    (subst cif-wi-a0)
    (crs)))
(dk-cite! 'winding-circle-center 'c 'r)
(define cif-wi-wz '(WINDING (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI) z))
(define cif-wi-wc '(WINDING (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI) c))
(dk-have! (list '== cif-wi-wz cif-wi-wc)
  (lambda ()
    (mac 'WINDING)
    (subst (list '= (cif-LI (cif-kern 'z)) (cif-LI (cif-kern 'c))))
    (qrfl)))
(cif-subst-ass! (list '== cif-wi-wz cif-wi-wc))
(qed (quote winding-circle-inside))
;;; (9) THE CAUCHY INTEGRAL FORMULA ON A DISC (3.7's first form): f holomorphic on u,
;;; B(c, s) inside u, 0 < r < s, |z - c| < r:
;;;   f(z) = 1/(2 pi i) int_C(c, r) f(w)/(w - z) dw.
(define (cif-f1 z) (list 'VNB-LAMBDA 'cifw_ cif-T (list '* '(f cifw_) (list 'recip (list '- 'cifw_ z)))))
(sp (make-wff '(FORALL u (FORALL f (IMPLIES (HOLOMORPHIC-ON u f)
  (FORALL c (IMPLIES (IN c CC) (FORALL cifs_ (IMPLIES (IN cifs_ RR) (IMPLIES (< 0 cifs_)
    (IMPLIES (SUBSET (BALL CC-MS c cifs_) u)
      (FORALL r (IMPLIES (IN r RR) (IMPLIES (< 0 r) (IMPLIES (< r cifs_)
        (FORALL z (IMPLIES (IN z CC) (IMPLIES (< (magnitude (- z c)) r)
          (= (f z) (* (recip (* (* 2 PI) +i))
                      (LINE-INT (VNB-LAMBDA cifw_ (TRACE (CIRCLE-PATH c r) 0 (* 2 PI))
                                            (* (f cifw_) (recip (- cifw_ z))))
                                (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI))))))))))))))))))))))
(dk-peel!)
(define cif-cf-w '(DIFFERENCE u (SINGLETON z)))
(define cif-cf-bl '(BALL CC-MS c cifs_))
(cif-circle-basics!)
(dk-have! '(<= 0 r) (lambda () (dk-ineq! '(< 0 r))))
(dk-cite! 'trace-is-set cif-C 0 cif-tp)
(fact 'subset-refl cif-T)
(dk-cite! 'circle-path-closed 'c 'r)
(fact 'nf-cc-is-metric-space)
(fact 'cc-is-normed-field)
(fact 'cc-nf-carr)
(dk-cite! 'holomorphic-on-in-fun 'u 'f)
(dk-cite! 'holomorphic-on-open 'u 'f)
(dk-cite! 'cc-open-subset-cc 'u)
(cif-pz-setup! 'z)
(cif-kern-setup! 'z)
(cif-trace-in-pz! 'z)
;; z in u
(cif-rr! '(magnitude (- z c)))
(dk-have! '(< (magnitude (- z c)) cifs_) (lambda () (dk-ineq! '(< (magnitude (- z c)) r) '(< r cifs_))))
(cif-in-ball! 'z 'c 'cifs_)
(fact 'subset-mem-fwd cif-cf-bl 'u 'z)
(fact 'fun-apply-type-c 'f 'u 'CC 'z)
;; the trace lies in the ball B(c, s), hence in u, and off z
(dk-have! (list 'SUBSET cif-T cif-cf-bl)
  (lambda ()
    (let* ((y (subset-by-element!)) (leaf (proof-state-focus *ps*)))
      (cif-circ-pt! y)
      (dk-have! (list '< (list 'magnitude (list '- y 'c)) 'cifs_)
        (lambda () (dk-ineq! (list '= (list 'magnitude (list '- y 'c)) 'r) '(< r cifs_))))
      (cif-in-ball! y 'c 'cifs_)
      (if (not (sequent-node-grounded? leaf)) (ass)))))
(dk-cite! 'subset-trans cif-T cif-cf-bl 'u)
;; the Caratheodory factor of f at z
(define cif-cf-l (dk-skolem! (dk-apply! (dk-cite! 'holomorphic-on-diff 'u 'f) 'z)))
(mac-h 'IS-DIFF-ON (dk-pick (dk-head? 'IS-DIFF-ON) "the derivative of f at z"))
(dk-split-all!)
(define cif-cf-p (dk-skolem! (dk-pick (lambda (fm) (and (dk-head-is? fm 'FORSOME) (dk-contains? fm 'MUL))) "the factor")))
(dk-split-all!)
(define cif-cf-fac (dk-pick (lambda (fm) (and (dk-head-is? fm 'FORALL) (dk-contains? fm 'MUL) (dk-contains? fm cif-cf-p))) "the factorisation"))
(dk-have! (list 'IN cif-cf-p '(FUN u CC))
  (lambda () (subst '(= CC (CARR CC-NORMED-FIELD))) (ass)))
;; f(x) - f(z) = p(x) (x - z) on u
(define cif-cf-fac2
  (list 'FORALL 'cifx_ (list 'IMPLIES '(IN cifx_ u)
    (list '= '(- (f cifx_) (f z)) (list '* (list cif-cf-p 'cifx_) '(- cifx_ z))))))
(dk-have! cif-cf-fac2
  (lambda ()
    (let* ((x (dk-di-var!)) (fx (list 'f x)) (px (list cif-cf-p x)) (d (list '- x 'z)))
      (fact 'subset-mem-fwd 'u 'CC x)
      (fact 'fun-apply-type-c 'f 'u 'CC x)
      (fact 'fun-apply-type-c cif-cf-p 'u 'CC x)
      (cif-cc! d)
      (dk-apply! cif-cf-fac x)
      (dk-cite! 'cc-nf-sub fx '(f z))
      (dk-cite! 'cc-nf-sub x 'z)
      (cif-and! (list 'IN px 'CC) (list 'IN d 'CC))
      (dk-cite! 'cc-nf-mul-apply px d)
      (subst (list '= (list '* px d) (list '(MUL CC-NORMED-FIELD) px d)))
      (subst (list '= d (list '(ADD CC-NORMED-FIELD) x (list '(NEG CC-NORMED-FIELD) 'z))))
      (subst (list '= (list '- fx '(f z)) (list '(ADD CC-NORMED-FIELD) fx (list '(NEG CC-NORMED-FIELD) '(f z)))))
      (ass))))
;; W = u \ {z}: open, inside u and inside CC \ {z}
(dk-cite! 'cif-open-minus-point 'u 'z)
(define (cif-cf-w-pt! x)
  ;; x in W: x in u, x in CC, x /= z, x - z /= 0, x in CC \ {z}
  (let* ((dm (dk-cite! 'difference-membership 'u '(SINGLETON z) x))
        (sm (dk-cite! 'singleton-membership 'z x)))
    (cif-steps
      (lambda () (dk-have! (list 'IN x 'u) (lambda () (cif-only-prop! dm (list 'IN x cif-cf-w)))))
      (lambda () (fact 'subset-mem-fwd 'u 'CC x))
      (lambda () (fact 'membership-implies-sethood x 'CC))
      (lambda () (dk-have! (list 'NOT (list '= x 'z))
                   (lambda () (cif-only-prop! dm sm (list 'IN x cif-cf-w) (list 'IN x 'SET)))))
      (lambda () (cif-sub-nz! x 'z))
      (lambda () (cif-pz-in! 'z x)))))
(dk-have! (list 'SUBSET cif-cf-w 'u)
  (lambda () (let* ((x (subset-by-element!))) (cif-cf-w-pt! x))))
(dk-have! (list 'SUBSET cif-cf-w (cif-pz 'z))
  (lambda () (let* ((x (subset-by-element!))) (cif-cf-w-pt! x))))
(dk-cite! 'cc-open-subset-cc cif-cf-w)
(fact 'cc-is-set)
(fact 'subclass-of-set-is-set 'u 'CC)
(dk-cite! 'difference-set 'u '(SINGLETON z))
(let* ((iff (dk-cite! 'cc-ms-open-iff cif-cf-w)))
  (dk-have! (list 'IS-OPEN 'CC-MS cif-cf-w) (lambda () (cif-only-prop! iff (list 'IS-OPEN cif-nfm cif-cf-w)))))
;; h(x) = (f(x) - f(z)) / (x - z) is holomorphic on W
(define cif-cf-h (list 'VNB-LAMBDA 'cifx_ cif-cf-w '(* (- (f cifx_) (f z)) (recip (- cifx_ z)))))
(define cif-cf-g1 (list 'VNB-LAMBDA 'cifx_ cif-cf-w '(- (f cifx_) (f z))))
(define cif-cf-k (list 'VNB-LAMBDA 'hbx_ cif-cf-w '(- (f z))))
(define cif-cf-rf (list 'RESTRICT 'f cif-cf-w))
(define cif-cf-rk (list 'RESTRICT (cif-kern 'z) cif-cf-w))
(cif-cc! '(- (f z)))
(dk-cite! 'holomorphic-on-restrict 'u 'f cif-cf-w)
(dk-cite! 'holomorphic-const cif-cf-w '(- (f z)))
(dk-cite! 'holomorphic-on-restrict (cif-pz 'z) (cif-kern 'z) cif-cf-w)
(cif-lam-typ! cif-cf-g1 cif-cf-w (lambda (v) (cif-cf-w-pt! v) (fact 'fun-apply-type-c 'f 'u 'CC v)))
(cif-lam-typ! cif-cf-h cif-cf-w (lambda (v) (cif-cf-w-pt! v) (fact 'fun-apply-type-c 'f 'u 'CC v)))
(dk-have! (list 'FORALL 'cifhx_ (list 'IMPLIES (list 'IN 'cifhx_ cif-cf-w)
            (list '== (list cif-cf-g1 'cifhx_) (list '+ (list cif-cf-rf 'cifhx_) (list cif-cf-k 'cifhx_)))))
  (lambda ()
    (let* ((x (dk-di-var!)))
      (cif-cf-w-pt! x)
      (fact 'fun-apply-type-c 'f 'u 'CC x)
      (dk-cite! 'restrict-apply 'f cif-cf-w x)
      (subst (list '== (list cif-cf-rf x) (list 'f x)))
      (dk-lam-b!)
      (dk-have! (list '= (list '- (list 'f x) '(f z)) (list '+ (list 'f x) '(- (f z)))) (lambda () (crs)))
      (cif-subst-qrfl! (list '= (list '- (list 'f x) '(f z)) (list '+ (list 'f x) '(- (f z))))))))
(dk-cite! 'holomorphic-sum cif-cf-w cif-cf-rf cif-cf-k cif-cf-g1)
(dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ cif-cf-w)
            (list '== (list cif-cf-h 'hbx_) (list '* (list cif-cf-g1 'hbx_) (list cif-cf-rk 'hbx_)))))
  (lambda ()
    (let* ((x (dk-di-var!)))
      (cif-cf-w-pt! x)
      (fact 'fun-apply-type-c 'f 'u 'CC x)
      (dk-cite! 'restrict-apply (cif-kern 'z) cif-cf-w x)
      (subst (list '== (list cif-cf-rk x) (list (cif-kern 'z) x)))
      (dk-lam-b!)
      (qrfl))))
(dk-cite! 'holomorphic-product cif-cf-w cif-cf-g1 cif-cf-rk cif-cf-h)
;; p agrees with h on W
(define cif-cf-rp (list 'RESTRICT cif-cf-p cif-cf-w))
(define cif-cf-ph
  (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ cif-cf-w) (list '== (list cif-cf-rp 'hbx_) (list cif-cf-h 'hbx_)))))
(dk-have! cif-cf-ph
  (lambda ()
    (let* ((x (dk-di-var!)) (px (list cif-cf-p x)) (d (list '- x 'z)))
      (cif-cf-w-pt! x)
      (fact 'fun-apply-type-c 'f 'u 'CC x)
      (fact 'fun-apply-type-c cif-cf-p 'u 'CC x)
      (dk-cite! 'restrict-apply cif-cf-p cif-cf-w x)
      (subst (list '== (list cif-cf-rp x) px))
      (dk-lam-b!)
      (dk-apply! (dk-ctx-form cif-cf-fac2) x)
      (subst (list '= (list '- (list 'f x) '(f z)) (list '* px d)))
      (cif-cc! d)
      (cif-and! (list 'IN d 'CC) (list 'NOT (list '= d 0)))
      (dk-cite! 'cc-recip-inverse d)
      (cif-cc! (list 'recip d))
      (let* ((a (dk-name! (list 'recip d) 'CC)))
        (subst (list '= (list 'recip d) a))
        (dk-have! (list '= (list '* d a) 1) (lambda () (subst (list '= a (list 'recip d))) (ass)))
        (dk-have! (list '= (list '* (list '* px d) a) (list '* px (list '* d a))) (lambda () (crs)))
        (subst (list '= (list '* (list '* px d) a) (list '* px (list '* d a))))
        (subst (list '= (list '* d a) 1))
        (dk-have! (list '= (list '* px 1) px) (lambda () (crs)))
        (cif-subst-qrfl! (list '= (list '* px 1) px))))))
(dk-cite! 'restrict-in-fun cif-cf-p 'u 'CC cif-cf-w)
(dk-cite! 'holomorphic-transfer-ptwise-eq cif-cf-w cif-cf-rp cif-cf-h)
;; p is continuous on u
(dk-have! (cif-cont 'u cif-cf-p)
  (lambda ()
    (let* ((y (dk-di-var!)))
      (use-em (list '= y 'z)
        (lambda () (subst (list '= y 'z)) (ass))
        (lambda ()
          (fact 'subset-mem-fwd 'u 'CC y)
          (fact 'membership-implies-sethood y 'CC)
          (let* ((dm (dk-cite! 'difference-membership 'u '(SINGLETON z) y))
                (sm (dk-cite! 'singleton-membership 'z y)))
            (dk-have! (list 'IN y cif-cf-w)
              (lambda () (cif-only-prop! dm sm (list 'IN y 'u) (list 'IN y 'SET) (list 'NOT (list '= y 'z))))))
          (let* ((l (dk-skolem! (dk-apply! (dk-cite! 'holomorphic-on-diff cif-cf-w cif-cf-rp) y)))
                 (dd (dk-pick (lambda (fm) (and (dk-head-is? fm 'IS-DIFF-ON) (dk-contains? fm l))) "the derivative")))
            (dk-have! (list 'FORALL 'cexx_ (list 'IMPLIES (list 'IN 'cexx_ cif-cf-w) (list '= (list cif-cf-p 'cexx_) (list cif-cf-rp 'cexx_))))
              (lambda ()
                (let* ((x (dk-di-var!)))
                  (cif-cf-w-pt! x)
                  (fact 'fun-apply-type-c cif-cf-p 'u 'CC x)
                  (dk-cite! 'restrict-apply cif-cf-p cif-cf-w x)
                  (subst (list '== (list cif-cf-rp x) (list cif-cf-p x)))
                  (rfl))))
            (dk-cite! 'cc-diff-on-local 'u cif-cf-p cif-cf-w cif-cf-rp y l)
            (dk-cite! 'diff-on-implies-continuous 'CC-NORMED-FIELD 'u cif-cf-p y l)
            (ass)))))))
;; Cauchy on the disc for p: its integral over the circle is 0
(dk-have! (list 'HOLOMORPHIC-ON cif-cf-w (list 'RESTRICT cif-cf-p cif-cf-w)) (lambda () (ass)))
(define cif-cf-zero (dk-cite! 'cauchy-disc-except 'u cif-cf-p 'z 'c 'cifs_ cif-C cif-Cd 0 cif-tp))
;; on the trace, p is (f(w) - f(z)) / (w - z)
(define cif-cf-g2 (list 'VNB-LAMBDA 'cifw_ cif-T '(* (- (f cifw_) (f z)) (recip (- cifw_ z)))))
(define (cif-cf-t-pt0! x)
  (cif-steps
    (lambda () (cif-circ-pt! x))
    (lambda () (cif-circ-not-z! x))
    (lambda () (fact 'subset-mem-fwd cif-T 'u x))
    (lambda () (fact 'membership-implies-sethood x 'CC))
    (lambda () (let* ((dm (dk-cite! 'difference-membership 'u '(SINGLETON z) x))
                     (sm (dk-cite! 'singleton-membership 'z x)))
                 (dk-have! (list 'IN x cif-cf-w)
                   (lambda () (cif-only-prop! dm sm (list 'IN x 'u) (list 'IN x 'SET) (list 'NOT (list '= x 'z)))))))))
(dk-have! (list 'SUBSET cif-T cif-cf-w)
  (lambda () (let* ((x (subset-by-element!))) (cif-cf-t-pt0! x))))
(cif-trace-in-pz! 'c)
(define (cif-cf-t-pt! x)
  (cif-steps
    (lambda () (cif-tpt! x 'z))
    (lambda () (fact 'subset-mem-fwd cif-T 'u x))
    (lambda () (fact 'fun-apply-type-c 'f 'u 'CC x))
    (lambda () (fact 'subset-mem-fwd cif-T cif-cf-w x))))
(cif-lam-typ! cif-cf-g2 cif-T (lambda (v) (cif-cf-t-pt! v)))
(dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ cif-T) (list '== (list cif-cf-g2 'wnx_) (list cif-cf-p 'wnx_))))
  (lambda ()
    (let* ((x (dk-di-var!)))
      (cif-cf-t-pt! x)
      (dk-apply! (dk-ctx-form cif-cf-ph) x)
      (dk-cite! 'restrict-apply cif-cf-p cif-cf-w x)
      (subst (list '== (list cif-cf-p x) (list cif-cf-rp x)))
      (subst (list '== (list cif-cf-rp x) (list cif-cf-h x)))
      (dk-lam-b!)
      (qrfl))))
(define cif-cf-e1 (dk-cite! 'line-int-domain-congruence 'u cif-cf-p cif-C cif-Cd 0 cif-tp cif-T cif-cf-g2))
;; the integrand splits: f(w)/(w - z) = (f(w) - f(z))/(w - z) + f(z) * 1/(w - z)
(define cif-cf-f1 (cif-f1 'z))
(define cif-cf-kt (list 'VNB-LAMBDA 'cifw_ cif-T '(recip (- cifw_ z))))
(define cif-cf-f2 (list 'VNB-LAMBDA 'cifw_ cif-T '(* (f z) (recip (- cifw_ z)))))
(cif-lam-typ! cif-cf-f1 cif-T (lambda (v) (cif-cf-t-pt! v)))
(cif-lam-typ! cif-cf-kt cif-T (lambda (v) (cif-cf-t-pt! v)))
(cif-lam-typ! cif-cf-f2 cif-T (lambda (v) (cif-cf-t-pt! v)))
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cif-T) (list '== (list cif-cf-g2 'aix_) (list cif-cf-h 'aix_))))
  (lambda () (let* ((x (dk-di-var!))) (cif-cf-t-pt! x) (dk-lam-b!) (qrfl))))
(dk-cite! 'aif-cont-holo-restrict cif-cf-w cif-cf-h cif-T cif-cf-g2)
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cif-T) (list '== (list cif-cf-kt 'aix_) (list (cif-kern 'z) 'aix_))))
  (lambda () (let* ((x (dk-di-var!))) (cif-cf-t-pt! x) (dk-lam-b!) (qrfl))))
(dk-cite! 'aif-cont-holo-restrict (cif-pz 'z) (cif-kern 'z) cif-T cif-cf-kt)
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cif-T) (list '== (list cif-cf-f2 'aix_) (list '* '(f z) (list cif-cf-kt 'aix_)))))
  (lambda () (let* ((x (dk-di-var!))) (cif-cf-t-pt! x) (dk-lam-b!) (qrfl))))
(dk-cite! 'aif-cont-scale cif-T '(f z) cif-cf-kt cif-cf-f2)
(dk-have! (list 'FORALL 'liz_ (list 'IMPLIES (list 'IN 'liz_ cif-T)
            (list '== (list cif-cf-f1 'liz_) (list '+ (list cif-cf-g2 'liz_) (list cif-cf-f2 'liz_)))))
  (lambda ()
    (let* ((x (dk-di-var!)) (d (list '- x 'z)))
      (cif-cf-t-pt! x)
      (dk-lam-b!)
      (cif-cc! (list 'recip d))
      (let* ((a (dk-name! (list 'recip d) 'CC)))
        (subst (list '= (list 'recip d) a))
        (let* ((eq (list '= (list '* (list 'f x) a) (list '+ (list '* (list '- (list 'f x) '(f z)) a) (list '* '(f z) a)))))
          (dk-have! eq (lambda () (crs)))
          (cif-subst-qrfl! eq))))))
(define cif-cf-e2 (dk-apply! (dk-cite! 'line-int-sum cif-T cif-cf-g2 cif-cf-f2 cif-C cif-Cd 0 cif-tp) cif-cf-f1))
(dk-have! (list 'FORALL 'liz_ (list 'IMPLIES (list 'IN 'liz_ cif-T) (list '== (list cif-cf-f2 'liz_) (list '* '(f z) (list cif-cf-kt 'liz_)))))
  (lambda () (let* ((x (dk-di-var!))) (cif-cf-t-pt! x) (dk-lam-b!) (qrfl))))
(define cif-cf-e3 (dk-apply! (dk-cite! 'line-int-scalar cif-T cif-cf-kt cif-C cif-Cd 0 cif-tp) '(f z) cif-cf-f2))
(define cif-cf-e4 (dk-cite! 'line-int-domain-congruence (cif-pz 'z) (cif-kern 'z) cif-C cif-Cd 0 cif-tp cif-T cif-cf-kt))
;; int 1/(w - z) = 2 pi i, from winding-circle-inside
(cif-tpi!)
(dk-cite! 'winding-circle-inside 'c 'r 'z)
(dk-cite! 'line-int-in-cc (cif-pz 'z) (cif-kern 'z) cif-C cif-Cd 0 cif-tp)
(define cif-cf-lk (cif-LI (cif-kern 'z)))
(dk-have! (list '= cif-cf-lk cif-tpi)
  (lambda ()
    (let* ((wz '(WINDING (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI) z)))
      (dk-have! (list '== wz (list '* (list 'recip cif-tpi) cif-cf-lk)) (lambda () (mac 'WINDING) (qrfl)))
      (dk-have! (list '= (list '* (list 'recip cif-tpi) cif-cf-lk) 1)
        (lambda () (subst (list '== (list '* (list 'recip cif-tpi) cif-cf-lk) wz)) (ass)))
      (let* ((a (dk-name! (list 'recip cif-tpi) 'CC)) (lv (dk-name! cif-cf-lk 'CC)))
        (subst (list '= cif-cf-lk lv))
        (dk-have! (list '= (list '* a lv) 1)
          (lambda () (subst (list '= a (list 'recip cif-tpi))) (subst (list '= lv cif-cf-lk)) (ass)))
        (dk-have! (list '= (list '* cif-tpi a) 1)
          (lambda () (subst (list '= a (list 'recip cif-tpi))) (ass)))
        (dk-have! (list '= lv (list '* (list '* cif-tpi a) lv)) (lambda () (subst (list '= (list '* cif-tpi a) 1)) (crs)))
        (subst (list '= lv (list '* (list '* cif-tpi a) lv)))
        (dk-have! (list '= (list '* (list '* cif-tpi a) lv) (list '* cif-tpi (list '* a lv))) (lambda () (crs)))
        (subst (list '= (list '* (list '* cif-tpi a) lv) (list '* cif-tpi (list '* a lv))))
        (subst (list '= (list '* a lv) 1))
        (crs)))))
;; assemble
(subst cif-cf-e2)
(subst cif-cf-e3)
(subst cif-cf-e4)
(subst (list '= cif-cf-lk cif-tpi))
(subst cif-cf-e1)
(subst cif-cf-zero)
(let* ((a (dk-name! (list 'recip cif-tpi) 'CC)))
  (subst (list '= (list 'recip cif-tpi) a))
  (dk-have! (list '= (list '* cif-tpi a) 1) (lambda () (subst (list '= a (list 'recip cif-tpi))) (ass)))
  (dk-have! (list '= (list '* a (list '+ 0 (list '* '(f z) cif-tpi))) (list '* (list '* cif-tpi a) '(f z))) (lambda () (crs)))
  (subst (list '= (list '* a (list '+ 0 (list '* '(f z) cif-tpi))) (list '* (list '* cif-tpi a) '(f z))))
  (subst (list '= (list '* cif-tpi a) 1))
  (crs))
(qed 'cauchy-integral-formula-disc)
;;; (10) the integral formula in the spelling of analytic-from-integral.scm: the weight
;;; is f restricted to the trace
(define cif-rf (list 'RESTRICT 'f cif-T))
(define (cif-f1r z) (list 'VNB-LAMBDA 'aiw_ cif-T (list '* (list cif-rf 'aiw_) (list 'recip (list '- 'aiw_ z)))))
;;; the standing setting of a disc B(c, s) inside u, 0 < r < s (c, s, r, u, f in context):
;;; the circle basics, T inside B(c, s) and inside u, f continuous on T
(define (cif-disc-setting!)
  (cif-center-in-ball! 'c 'cifs_)
  (cif-circle-basics!)
  (dk-have! '(<= 0 r) (lambda () (dk-ineq! '(< 0 r))))
  (dk-cite! 'trace-is-set cif-C 0 cif-tp)
  (fact 'subset-refl cif-T)
  (dk-cite! 'circle-path-closed 'c 'r)
  (fact 'nf-cc-is-metric-space)
  (fact 'nf-metric-carrier 'CC-NORMED-FIELD)
  (fact 'cc-nf-carr)
  (dk-have! (list '== (list 'PTS cif-nfm) 'CC)
    (lambda () (subst (list '== (list 'PTS cif-nfm) '(CARR CC-NORMED-FIELD))) (ass)))
  (dk-cite! 'holomorphic-on-in-fun 'u 'f)
  (dk-cite! 'holomorphic-on-open 'u 'f)
  (dk-cite! 'holomorphic-on-continuous 'u 'f)
  (dk-cite! 'cc-open-subset-cc 'u)
  (dk-have! (list 'SUBSET 'u (list 'PTS cif-nfm))
    (lambda () (subst (list '== (list 'PTS cif-nfm) 'CC)) (ass)))
  (dk-have! (list 'SUBSET cif-T '(BALL CC-MS c cifs_))
    (lambda ()
      (let* ((y (subset-by-element!)) (leaf (proof-state-focus *ps*)))
        (cif-circ-pt! y)
        (dk-have! (list '< (list 'magnitude (list '- y 'c)) 'cifs_)
          (lambda () (dk-ineq! (list '= (list 'magnitude (list '- y 'c)) 'r) '(< r cifs_))))
        (cif-in-ball! y 'c 'cifs_)
        (if (not (sequent-node-grounded? leaf)) (ass)))))
  (dk-cite! 'subset-trans cif-T '(BALL CC-MS c cifs_) 'u)
  (dk-cite! 'restrict-in-fun 'f 'u 'CC cif-T)
  (dk-have! (cif-cont cif-T cif-rf)
    (lambda ()
      (let* ((y (dk-di-var!)))
        (fact 'subset-mem-fwd cif-T 'u y)
        (dk-apply! (dk-ctx-form (cif-cont 'u 'f)) y)
        (dk-cite! 'subspace-restrict-continuous-at cif-nfm 'u cif-T cif-nfm 'f y)
        (ass))))
  (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cif-T) '(<= r (magnitude (- aix_ c)))))
    (lambda ()
      (let* ((y (dk-di-var!)) (m (list 'magnitude (list '- y 'c))))
        (fact 'subset-mem-fwd cif-T 'CC y)
        (dk-cite! 'circle-trace-magnitude 'c 'r y)
        (cif-rr! m)
        (dk-ineq! (list '= m 'r))))))

(define cif-disc-hyps
  '((HOLOMORPHIC-ON u f) (IN c CC) (IN cifs_ RR) (< 0 cifs_) (SUBSET (BALL CC-MS c cifs_) u)
    (IN r RR) (< 0 r) (< r cifs_)))
(define (cif-under-disc body)
  (list 'FORALL 'u (list 'FORALL 'f (list 'IMPLIES '(HOLOMORPHIC-ON u f)
    (list 'FORALL 'c (list 'IMPLIES '(IN c CC) (list 'FORALL 'cifs_ (list 'IMPLIES '(IN cifs_ RR) (list 'IMPLIES '(< 0 cifs_)
      (list 'IMPLIES '(SUBSET (BALL CC-MS c cifs_) u)
        (list 'FORALL 'r (list 'IMPLIES '(IN r RR) (list 'IMPLIES '(< 0 r) (list 'IMPLIES '(< r cifs_) body))))))))))))))
(define cif-kap (list 'recip cif-tpi))

(sp (make-wff (cif-under-disc
  (list 'FORALL 'z (list 'IMPLIES '(IN z CC) (list 'IMPLIES '(< (magnitude (- z c)) r)
    (list '= '(f z) (list '* cif-kap (cif-LI (cif-f1r 'z))))))))))
(dk-peel!)
(cif-disc-setting!)
(cif-pz-setup! 'z)
(cif-pz-setup! 'c)
(cif-kern-setup! 'z)
(cif-trace-in-pz! 'c)
(cif-trace-in-pz! 'z)
(define cif-fr-e0 (dk-cite! 'cauchy-integral-formula-disc 'u 'f 'c 'cifs_ 'r 'z))
(define cif-fr-f1 (cif-f1 'z))
(define cif-fr-kt (list 'VNB-LAMBDA 'cifw_ cif-T '(recip (- cifw_ z))))
(define (cif-fr-pt! x)
  (cif-steps
    (lambda () (cif-tpt! x 'z))
    (lambda () (fact 'subset-mem-fwd cif-T 'u x))
    (lambda () (fact 'fun-apply-type-c 'f 'u 'CC x))))
(cif-lam-typ! cif-fr-f1 cif-T (lambda (v) (cif-fr-pt! v)))
(cif-lam-typ! cif-fr-kt cif-T (lambda (v) (cif-fr-pt! v)))
(cif-lam-typ! (cif-f1r 'z) cif-T (lambda (v) (cif-fr-pt! v) (dk-cite! 'restrict-apply 'f cif-T v)
                                      (cif-lam-b-if!) (subst (list '== (list cif-rf v) (list 'f v)))))
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cif-T) (list '== (list cif-fr-kt 'aix_) (list (cif-kern 'z) 'aix_))))
  (lambda () (let* ((x (dk-di-var!))) (cif-fr-pt! x) (dk-lam-b!) (qrfl))))
(dk-cite! 'aif-cont-holo-restrict (cif-pz 'z) (cif-kern 'z) cif-T cif-fr-kt)
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cif-T) (list '== (list cif-fr-f1 'aix_) (list '* (list cif-rf 'aix_) (list cif-fr-kt 'aix_)))))
  (lambda ()
    (let* ((x (dk-di-var!)))
      (cif-fr-pt! x)
      (dk-cite! 'restrict-apply 'f cif-T x)
      (subst (list '== (list cif-rf x) (list 'f x)))
      (dk-lam-b!)
      (qrfl))))
(dk-cite! 'aif-cont-product cif-T cif-rf cif-fr-kt cif-fr-f1)
(dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ cif-T) (list '== (list (cif-f1r 'z) 'wnx_) (list cif-fr-f1 'wnx_))))
  (lambda ()
    (let* ((x (dk-di-var!)))
      (cif-fr-pt! x)
      (dk-cite! 'restrict-apply 'f cif-T x)
      (dk-lam-b!)
      (cif-subst-qrfl! (list '== (list cif-rf x) (list 'f x))))))
(define cif-fr-e1 (dk-cite! 'line-int-domain-congruence cif-T cif-fr-f1 cif-C cif-Cd 0 cif-tp cif-T (cif-f1r 'z)))
(cif-subst-ass! cif-fr-e1)
(qed 'cauchy-integral-formula-disc-restrict)

;;; (11) THEOREM 3.35: f holomorphic on u, B(c, s) inside u, 0 < r < s: f is the sum of
;;; its power series on B(c, r), with the coefficients of Remark 3.34
(define (cif-h3 z)
  (list 'VNB-LAMBDA 'aitk_ 'NN
    (list '* (list '* cif-kap (cif-LI (list 'VNB-LAMBDA 'aiw_ cif-T
                                            (list '* (list cif-rf 'aiw_) (list 'power '(recip (- aiw_ c)) '(succ aitk_))))))
             (list 'power (list '- z 'c) 'aitk_))))
(define cif-formula-r
  (list 'FORALL 'z (list 'IMPLIES '(IN z CC) (list 'IMPLIES '(< (magnitude (- z c)) r)
    (list '= '(f z) (list '* cif-kap (cif-LI (cif-f1r 'z))))))))
(sp (make-wff (cif-under-disc
  (list 'FORALL 'z (list 'IMPLIES '(IN z CC) (list 'IMPLIES '(< (magnitude (- z c)) r)
    (list 'CC-SERIES-CONVERGES-TO (cif-h3 'z) '(f z))))))))
(dk-peel!)
(cif-disc-setting!)
(cif-tpi!)
(dk-have! cif-formula-r
  (lambda ()
    (let* ((lk (dk-peel!)))
      (let* ((z1 (cadr (car (filter (dk-head? 'IN) lk)))))
        (dk-cite! 'cauchy-integral-formula-disc-restrict 'u 'f 'c 'cifs_ 'r z1)
        (ass)))))
(dk-cite! 'analytic-from-integral-formula cif-T 'c 'r cif-rf cif-C cif-Cd 0 cif-tp cif-kap 'f 'z)
(ass)
(qed 'holomorphic-power-series-disc)

;;; (12) holomorphic => analytic: IS-ANALYTIC-AT at every point of the open set
(sp (make-wff '(FORALL u (FORALL f (IMPLIES (HOLOMORPHIC-ON u f)
  (FORALL c (IMPLIES (IN c u) (IS-ANALYTIC-AT f u c))))))))
(dk-peel!)
(dk-cite! 'holomorphic-on-open-cc-ms 'u 'f)
(dk-cite! 'holomorphic-on-in-fun 'u 'f)
(dk-cite! 'holomorphic-on-open 'u 'f)
(dk-cite! 'cc-open-subset-cc 'u)
(fact 'subset-mem-fwd 'u 'CC 'c)
(define cif-ha-ex
  (dk-project! '(FORALL y (IMPLIES (IN y u) (FORSOME r (AND (POS-RR r) (SUBSET (BALL CC-MS y r) u)))))
               'is-open '(IS-OPEN CC-MS u)))
(define cif-ha-s (dk-skolem! (dk-apply! cif-ha-ex 'c)))
(dk-cite! 'rr-pos-rr-in-rr cif-ha-s)
(dk-cite! 'rr-lt-of-pos-rr cif-ha-s)
(define cif-ha-r (list '* 1/2 cif-ha-s))
(cif-rr! cif-ha-r)
(dk-have! (list '< 0 cif-ha-r) (lambda () (dk-ineq! (list '< 0 cif-ha-s))))
(dk-have! (list '< cif-ha-r cif-ha-s) (lambda () (dk-ineq! (list '< 0 cif-ha-s))))
(define cif-ha-rv (dk-name! cif-ha-r))
(dk-have! (list '< 0 cif-ha-rv) (lambda () (dk-ineq! (list '< 0 cif-ha-r) (list '= cif-ha-rv cif-ha-r))))
(dk-have! (list '< cif-ha-rv cif-ha-s) (lambda () (dk-ineq! (list '< cif-ha-r cif-ha-s) (list '= cif-ha-rv cif-ha-r))))
(dk-have! (list 'SUBSET (list 'BALL 'CC-MS 'c cif-ha-rv) 'u)
  (lambda ()
    (let* ((x (subset-by-element!)))
      (cif-ball-open! 'c cif-ha-rv x)
      (dk-have! (list '< (list 'magnitude (list '- x 'c)) cif-ha-s)
        (lambda () (dk-ineq! (list '< (list 'magnitude (list '- x 'c)) cif-ha-rv) (list '< cif-ha-rv cif-ha-s))))
      (cif-in-ball! x 'c cif-ha-s)
      (fact 'subset-mem-fwd (list 'BALL 'CC-MS 'c cif-ha-s) 'u x)
      (ass))))
(cif-tpi!)
(let* ((s cif-ha-s) (r cif-ha-rv)
       (T (list 'TRACE (list 'CIRCLE-PATH 'c r) 0 cif-tp))
       (rf (list 'RESTRICT 'f T))
       (form (list 'FORALL 'z (list 'IMPLIES '(IN z CC) (list 'IMPLIES (list '< '(magnitude (- z c)) r)
               (list '= '(f z) (list '* cif-kap
                 (list 'LINE-INT (list 'VNB-LAMBDA 'aiw_ T (list '* (list rf 'aiw_) '(recip (- aiw_ z))))
                       (list 'CIRCLE-PATH 'c r) (list 'CIRCLE-DERIV 'c r) 0 cif-tp))))))))
  (dk-have! form
    (lambda ()
      (let* ((lk (dk-peel!)))
        (let* ((z1 (cadr (car (filter (dk-head? 'IN) lk)))))
          (dk-cite! 'cauchy-integral-formula-disc-restrict 'u 'f 'c s r z1)
          (ass)))))
  ;; the hypotheses of analytic-at-from-integral-formula about T and the weight
  (dk-cite! 'circle-is-road 'c r)
  (fact 'is-road-is-path (list 'CIRCLE-PATH 'c r) (list 'CIRCLE-DERIV 'c r) 0 cif-tp)
  (fact 'is-path-in-fun (list 'CIRCLE-PATH 'c r) 0 cif-tp)
  (dk-cite! 'trace-subset-cc (list 'CIRCLE-PATH 'c r) 0 cif-tp)
  (fact 'subset-refl T)
  (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ T) (list '<= r '(magnitude (- aix_ c)))))
    (lambda ()
      (let* ((y (dk-di-var!)) (m (list 'magnitude (list '- y 'c))))
        (fact 'subset-mem-fwd T 'CC y)
        (dk-have! (list '<= 0 r) (lambda () (dk-ineq! (list '< 0 r))))
        (dk-cite! 'circle-trace-magnitude 'c r y)
        (cif-rr! m)
        (dk-ineq! (list '= m r)))))
  (fact 'nf-cc-is-metric-space)
  (fact 'nf-metric-carrier 'CC-NORMED-FIELD)
  (fact 'cc-nf-carr)
  (dk-have! (list '== (list 'PTS cif-nfm) 'CC)
    (lambda () (subst (list '== (list 'PTS cif-nfm) '(CARR CC-NORMED-FIELD))) (ass)))
  (dk-have! (list 'SUBSET 'u (list 'PTS cif-nfm))
    (lambda () (subst (list '== (list 'PTS cif-nfm) 'CC)) (ass)))
  (dk-cite! 'holomorphic-on-continuous 'u 'f)
  (dk-have! (list 'SUBSET T 'u)
    (lambda ()
      (let* ((y (subset-by-element!)))
        (fact 'subset-mem-fwd T 'CC y)
        (dk-have! (list '<= 0 r) (lambda () (dk-ineq! (list '< 0 r))))
        (dk-cite! 'circle-trace-magnitude 'c r y)
        (cif-rr! (list 'magnitude (list '- y 'c)))
        (dk-have! (list '< (list 'magnitude (list '- y 'c)) s)
          (lambda () (dk-ineq! (list '= (list 'magnitude (list '- y 'c)) r) (list '< r s))))
        (cif-in-ball! y 'c s)
        (fact 'subset-mem-fwd (list 'BALL 'CC-MS 'c s) 'u y)
        (ass))))
  (dk-cite! 'restrict-in-fun 'f 'u 'CC T)
  (dk-have! (cif-cont T rf)
    (lambda ()
      (let* ((y (dk-di-var!)))
        (fact 'subset-mem-fwd T 'u y)
        (dk-apply! (dk-ctx-form (cif-cont 'u 'f)) y)
        (dk-cite! 'subspace-restrict-continuous-at cif-nfm 'u T cif-nfm 'f y)
        (ass))))
  (dk-cite! 'analytic-at-from-integral-formula T 'c r rf (list 'CIRCLE-PATH 'c r) (list 'CIRCLE-DERIV 'c r) 0 cif-tp
            cif-kap 'u 'f)
  (ass))
(qed 'holomorphic-analytic-at)
;;; (13) THE DERIVATIVE OF A HOLOMORPHIC FUNCTION IS HOLOMORPHIC (3.35 with 2.10: on a
;;; disc where f is the sum of its power series, f' is the sum of the derived series)
(define cif-dh-d '(VNB-LAMBDA cifdw_ u (DERIV-ON CC-NORMED-FIELD u f cifdw_)))
;;; v in u: land L with IS-DIFF-ON(u, f, v, L), DERIV-ON(u, f, v) = L, L in CC; return L
(define (cif-dh-dv! v)
  (let* ((l (dk-skolem! (dk-apply! (dk-cite! 'holomorphic-on-diff 'u 'f) v)))
         (dd (dk-pick (lambda (fm) (and (dk-head-is? fm 'IS-DIFF-ON) (dk-contains? fm l))) "the derivative")))
    (dk-project! (list 'IN l '(CARR CC-NORMED-FIELD)) 'IS-DIFF-ON dd)
    (dk-have! (list 'IN l 'CC) (lambda () (subst '(= CC (CARR CC-NORMED-FIELD))) (ass)))
    (dk-cite! 'cc-deriv-on-of-is-diff-on 'u 'f v l)
    l))
(sp (make-wff (list 'FORALL 'u (list 'FORALL 'f (list 'IMPLIES '(HOLOMORPHIC-ON u f)
  (list 'HOLOMORPHIC-ON 'u cif-dh-d))))))
(dk-peel!)
(fact 'cc-nf-carr)
(dk-cite! 'holomorphic-on-in-fun 'u 'f)
(dk-cite! 'holomorphic-on-open 'u 'f)
(dk-cite! 'cc-open-subset-cc 'u)
(fact 'cc-is-set)
(fact 'subclass-of-set-is-set 'u 'CC)
(dk-have! (list 'IN cif-dh-d '(FUN u CC))
  (lambda ()
    (dk-lam-type!
      (lambda ()
        (let* ((v (dk-di-var!)) (leaf (proof-state-focus *ps*)))
          (cif-lam-b-if!)
          (let* ((l (cif-dh-dv! v)))
            (subst (list '= (list 'DERIV-ON 'CC-NORMED-FIELD 'u 'f v) l))
            (if (not (sequent-node-grounded? leaf)) (ass))))))))
(mac 'HOLOMORPHIC-ON)
(dk-conj-close!
  (lambda ()
    (let* ((g (dk-goal)))
      (cond
        ((dk-asm? g) (ass))
        ((not (dk-head-is? g 'FORALL)) (error "cif: unexpected conjunct" (expression->string g)))
        (#t
         (let* ((a (dk-di-var!)))
           (fact 'subset-mem-fwd 'u 'CC a)
           (dk-cite! 'holomorphic-analytic-at 'u 'f a)
           (mac-h 'IS-ANALYTIC-AT (dk-pick (dk-head? 'IS-ANALYTIC-AT) "analytic at a"))
           (dk-split-all!)
           (let* ((cf (dk-skolem! (dk-pick (lambda (fm) (and (dk-head-is? fm 'FORSOME) (dk-contains? fm 'CPS-RADIUS))) "the coefficients")))
                  (r (dk-skolem! (dk-pick (lambda (fm) (and (dk-head-is? fm 'FORSOME) (dk-contains? fm 'CPS-RADIUS))) "the radius"))))
             (dk-split-all!)
             (let* ((bl (list 'BALL 'CC-MS a r))
                    (rep (dk-pick (lambda (fm) (and (dk-head-is? fm 'FORALL) (dk-contains? fm 'CC-SERIES-LIMIT) (dk-contains? fm cf))) "the representation"))
                    (pr (dk-abstract! 'NN 'CC (lambda (k) (list '* (list 'succ k) (list cf (list 'succ k))))
                                      (lambda (k) (fact 'nn-succ-closed k) (fact 'fun-apply-type-c cf 'NN 'CC (list 'succ k))
                                                  (cif-cc! (list '* (list 'succ k) (list cf (list 'succ k)))) (ass))))
                    (dcf (car pr)) (dve (cdr pr))
                    (gc (list 'VNB-LAMBDA 'algz_ bl (list 'CC-SERIES-LIMIT (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* (list cf 'cpsk_) (list 'power '(- algz_ a) 'cpsk_))))))
                    (gd (list 'VNB-LAMBDA 'algz_ bl (list 'CC-SERIES-LIMIT (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* (list dcf 'cpsk_) (list 'power '(- algz_ a) 'cpsk_))))))
                    (vald (lambda (w) (list 'CC-SERIES-LIMIT (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* (list dcf 'cpsk_) (list 'power (list '- w a) 'cpsk_)))))))
               (set! gc (cif-subst-sym gc 'a a))
               (set! gd (cif-subst-sym gd 'a a))
               (dk-have! (list 'FORALL 'cpdj_ (list 'IMPLIES '(IN cpdj_ NN) (list '= (list dcf 'cpdj_) (list '* '(succ cpdj_) (list cf '(succ cpdj_))))))
                 (lambda ()
                   (let* ((k (dk-di-var!)))
                     (fact 'nn-succ-closed k)
                     (fact 'fun-apply-type-c cf 'NN 'CC (list 'succ k))
                     (cif-cc! (list '* (list 'succ k) (list cf (list 'succ k))))
                     (subst (dk-apply! dve k))
                     (rfl))))
               (dk-cite! 'cps-radius-derived cf dcf)
               (dk-have! (list '< r (list 'CPS-RADIUS dcf))
                 (lambda () (cif-subst-ass! (list '= (list 'CPS-RADIUS dcf) (list 'CPS-RADIUS cf)))))
               (dk-cite! 'cps-translate-holomorphic dcf a r)
               (let* ((tdiff (dk-cite! 'cps-translate-diff cf dcf a r)))
                 ;; f = Gc on the ball, so f has derivative Vd(w) at w on u
                 (dk-have! (list 'FORALL 'cexx_ (list 'IMPLIES (list 'IN 'cexx_ bl) (list '= '(f cexx_) (list gc 'cexx_))))
                   (lambda ()
                     (let* ((x (dk-di-var!)))
                       (fact 'subset-mem-fwd bl 'u x)
                       (fact 'fun-apply-type-c 'f 'u 'CC x)
                       (dk-apply! rep x)
                       (dk-lam-b!)
                       (ass))))
                 (dk-have! (list 'FORALL 'cexx_ (list 'IMPLIES (list 'IN 'cexx_ bl) (list '= (list cif-dh-d 'cexx_) (list gd 'cexx_))))
                   (lambda ()
                     (let* ((x (dk-di-var!)) (dx (dk-apply! tdiff x)))
                       (fact 'subset-mem-fwd bl 'u x)
                       (dk-project! (list 'IN (vald x) '(CARR CC-NORMED-FIELD)) 'IS-DIFF-ON dx)
                       (dk-have! (list 'IN (vald x) 'CC) (lambda () (subst '(= CC (CARR CC-NORMED-FIELD))) (ass)))
                       (dk-cite! 'cc-diff-on-local 'u 'f bl gc x (vald x))
                       (dk-cite! 'cc-deriv-on-of-is-diff-on 'u 'f x (vald x))
                       (cif-lam-b-if!)
                       (ass))))
                 ;; Gd is holomorphic on the ball, so D is differentiable at a on u
                 (cif-center-in-ball! a r)
                 (let* ((l (dk-skolem! (dk-apply! (dk-cite! 'holomorphic-on-diff bl gd) a))))
                   (dk-cite! 'cc-diff-on-local 'u cif-dh-d bl gd a l)
                   (ew l)
                   (ass)))))))))))
(qed 'holomorphic-deriv-holomorphic)
