;;; cauchy-estimates.scm -- THE CIRCLE'S LENGTH, CAUCHY'S ESTIMATES, THE DERIVATIVE FORMULA,
;;; LIOUVILLE AND THE FUNDAMENTAL THEOREM OF ALGEBRA.
;;; (complex-analysis.pdf ch. 3: Prop 3.40 / Cor 3.42 through the coefficients, Prop 3.47 and
;;; Cor 3.48 (Cauchy's estimates, Liouville); ch. 1, 1.5 (the fundamental theorem of algebra).)
;;; Agent CA-3 of week 2 of the October roadmap (scratchpad/triage/WEEK2.md), 2026-10-04.
;;; Built on theorem-library/cauchy-integral-formula.scm (same agent).
;;;
;;; CONTENTS.
;;;  cc-magnitude-i                     |i| = 1
;;;  circle-road-length                 ROAD-LENGTH(CIRCLE-DERIV(c, r), 0, 2 pi) = 2 pi r  (r >= 0)
;;;  cauchy-kernel-constant-magnitude   |1/(2 pi i)| = 1/(2 pi)
;;;  cauchy-estimate-circle             |f| <= M on C(c, r)  =>  |a_k| <= M r^-k for the
;;;                                     coefficients a_k of holomorphic-power-series-disc
;;;  cauchy-estimate-center             ... and |f(c)| <= M (k = 0: the integral formula at c)
;;;  cauchy-coefficients-radius         every 0 <= rho < r lies below CPS-RADIUS of (a_k)
;;;  holomorphic-coefficient-series     f(z) = sum_k g(k) (z - c)^k for a coefficient FUNCTION g
;;;                                     with g(k) = a_k (the shape taylor-coefficients-at reads)
;;;  cauchy-derivative-formula          THE DERIVATIVE FORMULA: on B(c, rho), 0 < rho < r,
;;;                                     f^(k)(c) = k! a_k = k!/(2 pi i) int_C f(w)/(w - c)^(k+1) dw,
;;;                                     f^(k) = NTH-DERIV-ON(CC-NORMED-FIELD, B(c, rho), f|B(c, rho), k)
;;;  cauchy-estimate-derivative         CAUCHY'S ESTIMATES: |f^(k)(c)| <= k! M r^-k
;;;  cie-squeeze                        x <= K / R for every R > R0 (R0, K >= 0)  =>  x <= 0
;;;  bounded-entire-deriv-zero          f entire, |f| <= M  =>  f'(a) = 0 at every a
;;;  liouville                          f entire, |f| <= M  =>  f(z) = f(0) for every z
;;;  polynomial-holomorphic             z |-> sum_{k < j} p(k) z^k is entire
;;;  polynomial-growth-bound            |sum_{k <= j} p(k) w^k| <= (sum_{k <= j} |p(k)|) |w|^j, |w| >= 1
;;;  fundamental-theorem-of-algebra     p(n) /= 0, n >= 1  =>  sum_{k <= n} p(k) z^k = 0 for some z
;;;
;;; THE ROUTES.
;;; * The derivative formula goes through the coefficients (the brief's first option):
;;;   Theorem 3.35 (holomorphic-power-series-disc) gives f as the sum of sum_k a_k (z - c)^k on
;;;   B(c, r); the radius of convergence of (a_k) is at least r (the absolute convergence of
;;;   cauchy-kernel-series-absolute at every |z - c| < r: cauchy-coefficients-radius, the route
;;;   of analytic-at-from-integral-formula); taylor-coefficients-at (Cor 2.14 at a point) then
;;;   reads f^(k)(c) = k! a_k off the series.  The k-th derivative is the tree's NTH-DERIV-ON on
;;;   a ball B(c, rho), rho < r, of the restriction of f: the vocabulary of taylor-coefficients-at.
;;; * Liouville by the notes' route: |f'(a)| = |a_1| <= M / q for the circle of every radius q
;;;   (with the derivative taken on the fixed ball B(a, 1/2)), so f' = 0; then f is constant on
;;;   every ball B(0, R) (alg-zero-deriv-ball).
;;; * THE FUNDAMENTAL THEOREM OF ALGEBRA does not cite Liouville: a polynomial p of degree
;;;   n >= 1 without zeros has the entire reciprocal g = 1/p, and the growth bound gives
;;;   |g| <= K / R on the circle |w| = R for R large, so |g(0)| <= K / R (cauchy-estimate-center,
;;;   the mean-value inequality at the centre), g(0) = 0, against g(0) p(0) = 1.  This is the
;;;   same estimate as Liouville's applied to g at one point, one step shorter than "g is
;;;   bounded, hence constant, hence ..." (which needs |g| bounded on the compact disc as well).
;;;
;;; STATEMENT CHECKS.  (1) THE POLYNOMIAL VOCABULARY.  The tree's polynomials are the ring
;;; POLY(A) = MONALG(A, NN-ADD-MONOID) of finitely supported coefficient sequences
;;; (structure-library/polynomial.scm) with DEG (poly-degree.scm); there is NO evaluation map
;;; from POLY(CC) to functions CC -> CC.  So the theorem is stated, as the brief allows, for
;;; the polynomial FUNCTION given by a coefficient function p in FUN(NN, CC):
;;;   z |-> CC-SERIES-PARTIAL-SUM(k |-> p(k) z^k, n + 1) = sum_{k <= n} p(k) z^k,
;;; the degree n = succ(m) >= 1 with p(n) /= 0 (coefficients beyond n are not read).  An
;;; evaluation map POLY(CC) -> FUN(CC, CC) with eval = this partial sum at DEG + 1 would make
;;; the POLY form one citation.  (2) The bound hypotheses are |f| <= M on the TRACE of the
;;; circle (Cauchy's estimates) or on all of CC (Liouville); M is not assumed nonnegative (it
;;; is, being a bound of |f|).  (3) The disc hypotheses are those of cauchy-integral-formula.scm:
;;; f holomorphic on u, B(c, s) inside u, 0 < r < s.  (4) The binder of the polynomial's
;;; coefficient lambda is k; the coefficient function is ciep_, the degree's predecessor ciem_.
;;;
;;; NOTHING asserted, no definition.  Helper prefix cie- (the cif- helpers of
;;; cauchy-integral-formula.scm copied: a helper is local to its file); theorem binders cie*_
;;; and the binders of the cited theorems where an instance must match.
;;; LOAD WINDOW: lo = theorem-library/cauchy-integral-formula (every theorem of it but
;;; cif-open-minus-point is cited: the latest is holomorphic-power-series-disc); also
;;; analytic-log-laws (taylor-coefficients-at, alg-zero-deriv-ball), analytic-from-integral
;;; (cauchy-estimate-from-formula, cauchy-kernel-series-absolute, aif-cont-*), nth-deriv-laws
;;; (nth-deriv-on-succ-apply), cc-exp (cc-exp-magnitude-imaginary).  hi: none.
;;; Tactics: the early kit only (dk-*, use-cases, use-induction, pbc, prop, crs, ineq).
;;; piece 1: open minus a point, Cauchy with an exceptional point on a convex set / disc
(define cie-nfm '(NF-METRIC-SPACE CC-NORMED-FIELD))
(define (cie-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (cie-cont u f)
  (list 'FORALL 'rgy_ (list 'IMPLIES (list 'IN 'rgy_ u)
    (list 'IS-CONTINUOUS-AT (list 'SUBSPACE-MS cie-nfm u) cie-nfm f 'rgy_))))
(define (cie-imps hyps body)
  (if (null? hyps) body (list 'IMPLIES (car hyps) (cie-imps (cdr hyps) body))))
(define (cie-all vars body)
  (if (null? vars) body (list 'FORALL (car vars) (cie-all (cdr vars) body))))
(define (cie-and! a b)
  (let* ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! dk-ass!))))
    f))
(define (cie-pz z) (list 'DIFFERENCE 'CC (list 'SINGLETON z)))

(define (cie-rr! t)
  (let* ((typ (list 'IN t 'RR)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'rr-zero-in) typ)
          ((eqv? t 1) (fact 'rr-one-in) typ)
          ((eq? t 'PI) (dk-split-all! (list (dk-cite! 'pi-pos))) typ)
          ((number? t) (dk-have! typ (lambda () (arith))) typ)
          ((dk-asm? (list 'IN t 'NN)) (fact 'nn-in-rr t) typ)
          ((cie-op? t 'succ 2) (cie-nn! t) (fact 'nn-in-rr t) typ)
          ((cie-op? t '* 3) (cie-rr! (cadr t)) (cie-rr! (caddr t)) (fact 'rr-mul-in-rr (cadr t) (caddr t)) typ)
          ((cie-op? t '+ 3) (cie-rr! (cadr t)) (cie-rr! (caddr t)) (fact 'rr-add-in-rr (cadr t) (caddr t)) typ)
          ((cie-op? t '- 3) (cie-rr! (cadr t)) (cie-rr! (caddr t)) (fact 'rr-sub-in-rr (cadr t) (caddr t)) typ)
          ((cie-op? t '- 2) (cie-rr! (cadr t)) (fact 'rr-neg-closed (cadr t)) typ)
          ((cie-op? t 'magnitude 2) (cie-cc! (cadr t)) (fact 'cc-magnitude-closed (cadr t)) typ)
          ((cie-op? t 'real-part 2) (cie-cc! (cadr t)) (fact 'real-part-in-rr (cadr t)) typ)
          ((cie-op? t 'imag-part 2) (cie-cc! (cadr t)) (fact 'imag-part-in-rr (cadr t)) typ)
          ((cie-op? t 'abs 2) (cie-rr! (cadr t)) (fact 'rr-abs-closed (cadr t)) typ)
          ((cie-op? t 'recip 2)
           (cie-rr! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (if (dk-asm? (list '< 0 (cadr t)))
                   (fact 'rr-pos-ne-zero (cadr t))
                   (error "cie-rr!: land the non-vanishing first" (expression->string (cadr t)))))
           (cie-and! (list 'IN (cadr t) 'RR) (list 'NOT (list '= (cadr t) 0)))
           (fact 'rr-recip-closed (cadr t))
           typ)
          (#t (dk-real! t) typ))))
(define (cie-nn! t)
  (let* ((typ (list 'IN t 'NN)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'nn-zero-in) typ)
          ((cie-op? t 'succ 2) (cie-nn! (cadr t)) (fact 'nn-succ-closed (cadr t)) typ)
          (#t (dk-type! t 'NN)))))
(define (cie-cc! t)
  (let* ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((eqv? t +i) (fact 'cc-i-in) typ)
          ((or (and (number? t) (real? t)) (eq? t 'PI) (dk-asm? (list 'IN t 'RR)) (dk-asm? (list 'IN t 'NN))
               (cie-op? t 'succ 2)
               (cie-op? t 'magnitude 2) (cie-op? t 'real-part 2) (cie-op? t 'imag-part 2))
           (cie-rr! t) (fact 'rr-subset-cc t) typ)
          ((cie-op? t '- 3) (cie-cc! (cadr t)) (cie-cc! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((cie-op? t '- 2) (cie-cc! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((cie-op? t '+ 3) (cie-cc! (cadr t)) (cie-cc! (caddr t))
           (cie-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((cie-op? t '* 3) (cie-cc! (cadr t)) (cie-cc! (caddr t))
           (cie-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((cie-op? t 'power 3) (cie-cc! (cadr t)) (cie-nn! (caddr t))
           (cie-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'NN)) (fact 'power-typing-nonneg (cadr t) (caddr t)) typ)
          ((cie-op? t 'CC-EXP 2) (cie-cc! (cadr t))
           (dk-split-all! (list (dk-cite! 'cc-exp-converges (cadr t)))) typ)
          ((cie-op? t 'recip 2) (cie-cc! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (error "cie-cc!: land the non-vanishing first" (expression->string (cadr t))))
           (cie-and! (list 'IN (cadr t) 'CC) (list 'NOT (list '= (cadr t) 0)))
           (fact 'cc-recip-closed (cadr t)) typ)
          (#t (dk-type! t 'CC)))))

;;; y in CC \ {z}: land y in CC, y /= z, y - z /= 0
(define (cie-sub-nz! y z)
  (let* ((nz (list 'NOT (list '= (list '- y z) 0))))
    (dk-have! nz
      (lambda ()
        (di)
        (dk-cite! 'cc-sub-zero-eq y z)
        (ai (dk-ctx-form (list 'NOT (list '= y z))))))
    nz))
(define (cie-steps . thunks)
  ;; run THUNKS in order while the leaf focused at the start stays open
  (let* ((leaf (proof-state-focus *ps*)))
    (let loop ((ts thunks))
      (if (and (pair? ts) (not (sequent-node-grounded? leaf)))
          (begin ((car ts)) (loop (cdr ts)))))))
(define (cie-pz-open! z y)
  (let* ((iff (dk-cite! 'cc-punctured-membership z y)))
    (cie-steps
      (lambda () (dk-have! (list 'IN y 'CC) (lambda () (cie-only-prop! iff (list 'IN y (cie-pz z))))))
      (lambda () (dk-have! (list 'NOT (list '= y z)) (lambda () (cie-only-prop! iff (list 'IN y (cie-pz z))))))
      (lambda () (cie-sub-nz! y z)))))
(define (cie-pz-in! z y)
  (let* ((iff (dk-cite! 'cc-punctured-membership z y)))
    (dk-have! (list 'IN y (cie-pz z))
      (lambda () (cie-only-prop! iff (list 'IN y 'CC) (list 'NOT (list '= y z)))))))
;;; the punctured plane: open (both spellings), a set
(define (cie-pz-setup! z)
  (let* ((d (cie-pz z)))
    (fact 'nf-cc-is-metric-space)
    (dk-cite! 'cc-punctured-open z)
    (let* ((iff (dk-cite! 'cc-ms-open-iff d)))
      (dk-have! (list 'IS-OPEN cie-nfm d) (lambda () (cie-only-prop! iff (list 'IS-OPEN 'CC-MS d)))))
    (fact 'cc-is-set)
    (dk-cite! 'difference-set 'CC (list 'SINGLETON z))
    (dk-cite! 'cc-open-subset-cc d)))
;;; (cie-lam-typ! LAM DOM TYPER) -- LAM in FUN(DOM, CC); TYPER of the eigenvariable
(define (cie-lam-typ! lam dom pre)
  (dk-have! (list 'IN lam (list 'FUN dom 'CC))
    (lambda ()
      (dk-lam-type! (lambda ()
                      (let* ((v (dk-di-var!)) (leaf (proof-state-focus *ps*)))
                        (cie-steps
                          (lambda () (pre v))
                          (lambda () (if (dk--redex? (dk-goal)) (dk-lam-b!)))
                          (lambda () (if (not (dk-asm? (dk-goal))) (cie-cc! (cadr (dk-goal)))))
                          (lambda () (ass)))))))))
;;; detach an implication whose antecedent THUNK proves
(define (cie-detach! imp thunk)
  (if (and (pair? imp) (eq? (car imp) 'IMPLIES))
      (begin (dk-have! (cadr imp) thunk)
             (dk-landed-1 (lambda () (detach! imp))))
      imp))
(define (cie-only-prop! . fs) (if (apply dk-only! fs) (prop)))
(define (cie-lam-b-if!) (if (dk--redex? (dk-goal)) (dk-lam-b!)))
;;; subst, then ass on the SAME leaf unless the subst closed it
(define (cie-subst-ass! eq)
  (let* ((leaf (proof-state-focus *ps*)))
    (subst eq)
    (if (not (sequent-node-grounded? leaf)) (ass))))
;;; 2 pi i: in CC and non-zero, its reciprocal in CC
(define cie-tpi '(* (* 2 PI) +i))
(define (cie-tpi!)
  (cie-rr! '(* 2 PI))
  (dk-have! '(< 0 (* 2 PI)) (lambda () (dk-ineq! '(< 0 PI))))
  (dk-cite! 'rr-pos-ne-zero '(* 2 PI))
  (cie-cc! '(* 2 PI))
  (fact 'cc-i-in)
  (dk-have! '(NOT (= +i 0))
    (lambda ()
      (di)
      (fact 'cc-i-squared)
      (dk-have! '(= (* 0 0) -1) (lambda () (subst '(= 0 +i)) (ass)))
      (dk-have! '(NOT (= (* 0 0) -1)) (lambda () (arith)))
      (ai '(NOT (= (* 0 0) -1)))))
  (dk-cite! 'cc-mul-nonzero '(* 2 PI) +i)
  (cie-cc! cie-tpi)
  (cie-cc! (list 'recip cie-tpi))
  (cie-and! (list 'IN cie-tpi 'CC) (list 'NOT (list '= cie-tpi 0)))
  (dk-cite! 'cc-recip-inverse cie-tpi))
;;; x in CC, c in CC, s in RR, |x - c| < s in context: land x in BALL(CC-MS, c, s)
(define (cie-in-ball! x c s)
  (let* ((m (list 'magnitude (list '- x c))))
    (fact 'cc-is-metric-space)
    (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
    (dk-have! (list 'IN x '(PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
    (dk-have! (list 'IN c '(PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
    (cie-rr! m)
    (dk-cite! 'cc-ms-dist c x)
    (dk-cite! 'cc-magnitude-sub-sym c x)
    (dk-have! (list '<= (list '(DIST CC-MS) c x) m)
      (lambda ()
        (subst (list '= (list '(DIST CC-MS) c x) (list 'magnitude (list '- c x))))
        (if (not (equal? c x)) (subst (list '= (list 'magnitude (list '- c x)) m)))
        (dk-ineq!)))
    (let* ((cj (list 'AND (list 'IN x '(PTS CC-MS)) (list 'AND (list 'IN m 'RR) (list 'AND (list 'IN s 'RR)
                (list 'AND (list '<= (list '(DIST CC-MS) c x) m) (list '< m s)))))))
      (dk-have! cj (lambda () (dk-conj-close! dk-ass!)))
      (dk-cite! 'ball-mem-from-le 'CC-MS c x m s))))
;;; subst EQ in a == goal, then qrfl on the same leaf unless the subst closed it
(define (cie-subst-qrfl! eq)
  (let* ((leaf (proof-state-focus *ps*)))
    (subst eq)
    (if (not (sequent-node-grounded? leaf)) (qrfl))))
;;; x in BALL(CC-MS, c, r) in context: land x in CC and |x - c| < r; return the latter
(define (cie-ball-open! c r x)
  ;; x in BALL(CC-MS, c, r) in context: land x in CC and |x - c| < r (stops early when a
  ;; landing closes the focus leaf, the claim being the goal)
  (let* ((dcx (list '(DIST CC-MS) c x))
         (mag (list 'magnitude (list '- c x)))
         (mag2 (list 'magnitude (list '- x c)))
         (cj  (list 'AND (list 'IN x '(PTS CC-MS)) (list 'AND (list '<= dcx r) (list 'NOT (list '= dcx r))))))
    (cie-steps
      (lambda () (fact 'cc-is-metric-space))
      (lambda () (let* ((iff (dk-cite! 'ball-membership 'CC-MS c r x)))
                   (dk-have! cj (lambda () (cie-only-prop! iff (list 'IN x (list 'BALL 'CC-MS c r)))))))
      (lambda () (dk-split-all! (list (dk-ctx-form cj))))
      (lambda () (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl))))
      (lambda () (dk-have! (list 'IN x 'CC) (lambda () (subst '(= CC (PTS CC-MS))) (ass))))
      (lambda () (dk-cite! 'cc-ms-dist c x))
      (lambda () (cie-rr! mag))
      (lambda () (cie-rr! mag2))
      (lambda () (dk-cite! 'cc-magnitude-sub-sym c x))
      (lambda () (dk-have! (list 'AND (list '<= mag r) (list 'NOT (list '= mag r)))
                   (lambda () (subst (list '= mag dcx)) (dk-conj-close! dk-ass!))))
      (lambda () (dk-cite! 'rr-le-ne-lt mag r))
      (lambda () (dk-have! (list '< mag2 r) (lambda () (dk-ineq! (list '< mag r) (list '= mag mag2))))))))

(define (cie-subst-sym e from to)
  (cond ((eq? e from) to)
        ((pair? e) (cons (cie-subst-sym (car e) from to) (cie-subst-sym (cdr e) from to)))
        (#t e)))
;;; a point x of the trace, the trace already known inside CC \ {c} (and CC \ {z} ...):
;;; land x in CC, x /= c, x - c /= 0 (the same for each z in ZS)
(define (cie-tpt! x . zs)
  (cie-steps
    (lambda () (fact 'subset-mem-fwd cie-T (cie-pz 'c) x))
    (lambda () (cie-pz-open! 'c x))
    (lambda () (for-each (lambda (z) (fact 'subset-mem-fwd cie-T (cie-pz z) x) (cie-pz-open! z x)) zs))))
(define (cie-dump-open!)
  (for-each (lambda (l) (display "\n;; OPEN: ") (display (expression->string (dk-goal-of l)))) (dk-open-leaves)))
(define (cie-center-in-ball! a r)
  ;; a in CC, r in RR, 0 < r: land a in BALL(CC-MS, a, r) (which also certifies the ball DEFINED)
  (let* ((d (list '- a a)) (m (list 'magnitude d)))
    (cie-rr! m)
    (cie-cc! d)
    (dk-have! (list '= d 0) (lambda () (crs)))
    (let ((iff (dk-cite! 'cc-magnitude-zero-iff d)))
      (dk-have! (list '= m 0) (lambda () (cie-only-prop! iff (list '= d 0)))))
    (dk-have! (list '< m r) (lambda () (dk-ineq! (list '= m 0) (list '< 0 r))))
    (cie-in-ball! a a r)))

(define (cie-R c) (list 'VNB-LAMBDA 'cifv_ (cie-pz c) (list 'recip (list '- 'cifv_ c))))
(define (cie-S c) (list 'VNB-LAMBDA 'cifv_ (cie-pz c) (list '- 'cifv_ c)))
(define (cie-P c n) (list 'VNB-LAMBDA 'cifv_ (cie-pz c) (list 'power (list 'recip (list '- 'cifv_ c)) n)))
(define (cie-sq-recip w c) (list '* (list 'recip (list '- w c)) (list 'recip (list '- w c))))
(define (cie-pd-goal j)
  (list 'FORALL 'cifc_ (list 'IMPLIES '(IN cifc_ CC)
    (list 'FORALL 'cifw_ (list 'IMPLIES (list 'IN 'cifw_ (cie-pz 'cifc_))
      (list 'IS-DIFF-ON 'CC-NORMED-FIELD (cie-pz 'cifc_) (cie-P 'cifc_ (list 'succ j)) 'cifw_
            (list '* (list '- (list 'succ j)) (list 'power (list 'recip (list '- 'cifw_ 'cifc_)) (list 'succ (list 'succ j))))))))))
(define (cie-pow-succ! a n)
  (cie-cc! a) (cie-nn! n)
  (cie-and! (list 'IN a 'CC) (list 'IN n 'NN))
  (dk-cite! 'power-succ a n))
(define (cie-carr-typ! lam d)
  (fact 'cc-nf-carr)
  (dk-have! (list 'IN lam (list 'FUN d '(CARR CC-NORMED-FIELD)))
    (lambda () (subst '(== (CARR CC-NORMED-FIELD) CC)) (ass))))
(define cie-tp '(* 2 PI))
(define cie-I (list 'CCINT 0 cie-tp))
(define cie-C '(CIRCLE-PATH c r))
(define cie-Cd '(CIRCLE-DERIV c r))
(define cie-T (list 'TRACE cie-C 0 cie-tp))
(define (cie-kern z) (list 'VNB-LAMBDA 'wnw_ (cie-pz z) (list 'recip (list '- 'wnw_ z))))
(define (cie-in-I! v)
  (dk-have! (list 'IN v cie-I)
    (lambda () (mac 'ccint-membership)
               (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (dk-ineq! (list '< 0 cie-tp) '(< 0 PI))))))))
(define (cie-circle-basics!)
  (fact 'rr-zero-in)
  (cie-rr! cie-tp)
  (dk-have! (list '< 0 cie-tp) (lambda () (dk-ineq! '(< 0 PI))))
  (dk-cite! 'circle-is-road 'c 'r)
  (fact 'is-road-is-path cie-C cie-Cd 0 cie-tp)
  (fact 'is-path-in-fun cie-C 0 cie-tp)
  (dk-cite! 'trace-subset-cc cie-C 0 cie-tp))
(define (cie-circ-pt! y)
  ;; y in the trace of the circle (c, r in context, 0 < r): y in CC, |y - c| = r,
  ;; r <= |y - c|, y /= c, y - c /= 0, y in CC \ {c}
  (let* ((m (list 'magnitude (list '- y 'c))))
    (cie-steps
      (lambda () (fact 'subset-mem-fwd cie-T 'CC y))
      (lambda () (dk-cite! 'circle-trace-magnitude 'c 'r y))
      (lambda () (cie-rr! m))
      (lambda () (dk-have! (list '<= 'r m) (lambda () (dk-ineq! (list '= m 'r)))))
      (lambda ()
        (dk-have! (list 'NOT (list '= y 'c))
          (lambda ()
            (di)
            (dk-have! (list '= m 0)
              (lambda () (subst (list '= y 'c))
                         (dk-have! '(= (- c c) 0) (lambda () (crs)))
                         (subst '(= (- c c) 0))
                         (fact 'cc-magnitude-zero)
                         (ass)))
            (dk-absurd! (list 'IN m 'RR) '(IN r RR) (list '= m 0) (list '= m 'r) '(< 0 r)))))
      (lambda () (cie-sub-nz! y 'c))
      (lambda () (cie-pz-in! 'c y)))))
(define (cie-circ-not-z! y)
  ;; y in the trace, |z - c| < r: y /= z, y in CC \ {z}
  (cie-steps
    (lambda ()
      (dk-have! (list 'NOT (list '= y 'z))
        (lambda ()
          (di)
          (dk-have! '(= (magnitude (- z c)) r)
            (lambda () (subst (list '= 'z y)) (ass)))
          (cie-rr! '(magnitude (- z c)))
          (dk-absurd! '(IN (magnitude (- z c)) RR) '(IN r RR) '(= (magnitude (- z c)) r) '(< (magnitude (- z c)) r)))))
    (lambda () (cie-sub-nz! y 'z))
    (lambda () (cie-pz-in! 'z y))))
(define (cie-Hk g k)
  (list 'VNB-LAMBDA 'aiw_ cie-T (list '* (list g 'aiw_) (list 'power '(recip (- aiw_ c)) (list 'succ k)))))
(define (cie-LI f) (list 'LINE-INT f cie-C cie-Cd 0 cie-tp))
(define (cie-trace-in-pz! p)
  (dk-have! (list 'SUBSET cie-T (cie-pz p))
    (lambda ()
      (let* ((y (subset-by-element!)) (leaf (proof-state-focus *ps*)))
        (cie-circ-pt! y)
        (if (eq? p 'z) (cie-circ-not-z! y))
        (if (not (sequent-node-grounded? leaf)) (ass))))))
(define (cie-kern-setup! p)
  (let* ((dd (cie-pz p)) (k (cie-kern p)))
    (dk-cite! 'winding-integrand-holomorphic p)
    (dk-cite! 'holomorphic-on-in-fun dd k)
    (dk-cite! 'holomorphic-on-continuous dd k)
    (dk-cite! 'holomorphic-on-open dd k)
    (dk-cite! 'cc-open-subset-cc dd)))
(define (cie-wi-g1! y) (dk-apply! cie-wi-gv y))
(define (cie-wi-typ-tt! lam)
  (cie-lam-typ! lam 'NN (lambda (v) (dk-apply! (dk-ctx-form cie-wi-at) v) (cie-cc! '(- z c)))))
(define cie-wi-wz '(WINDING (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI) z))
(define cie-wi-wc '(WINDING (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI) c))
(define (cie-f1 z) (list 'VNB-LAMBDA 'cifw_ cie-T (list '* '(f cifw_) (list 'recip (list '- 'cifw_ z)))))
(define cie-cf-w '(DIFFERENCE u (SINGLETON z)))
(define cie-cf-bl '(BALL CC-MS c cifs_))
(define (cie-cf-w-pt! x)
  ;; x in W: x in u, x in CC, x /= z, x - z /= 0, x in CC \ {z}
  (let* ((dm (dk-cite! 'difference-membership 'u '(SINGLETON z) x))
        (sm (dk-cite! 'singleton-membership 'z x)))
    (cie-steps
      (lambda () (dk-have! (list 'IN x 'u) (lambda () (cie-only-prop! dm (list 'IN x cie-cf-w)))))
      (lambda () (fact 'subset-mem-fwd 'u 'CC x))
      (lambda () (fact 'membership-implies-sethood x 'CC))
      (lambda () (dk-have! (list 'NOT (list '= x 'z))
                   (lambda () (cie-only-prop! dm sm (list 'IN x cie-cf-w) (list 'IN x 'SET)))))
      (lambda () (cie-sub-nz! x 'z))
      (lambda () (cie-pz-in! 'z x)))))
(define cie-cf-h (list 'VNB-LAMBDA 'cifx_ cie-cf-w '(* (- (f cifx_) (f z)) (recip (- cifx_ z)))))
(define cie-cf-g1 (list 'VNB-LAMBDA 'cifx_ cie-cf-w '(- (f cifx_) (f z))))
(define cie-cf-k (list 'VNB-LAMBDA 'hbx_ cie-cf-w '(- (f z))))
(define cie-cf-rf (list 'RESTRICT 'f cie-cf-w))
(define cie-cf-rk (list 'RESTRICT (cie-kern 'z) cie-cf-w))
(define cie-cf-g2 (list 'VNB-LAMBDA 'cifw_ cie-T '(* (- (f cifw_) (f z)) (recip (- cifw_ z)))))
(define (cie-cf-t-pt0! x)
  (cie-steps
    (lambda () (cie-circ-pt! x))
    (lambda () (cie-circ-not-z! x))
    (lambda () (fact 'subset-mem-fwd cie-T 'u x))
    (lambda () (fact 'membership-implies-sethood x 'CC))
    (lambda () (let* ((dm (dk-cite! 'difference-membership 'u '(SINGLETON z) x))
                     (sm (dk-cite! 'singleton-membership 'z x)))
                 (dk-have! (list 'IN x cie-cf-w)
                   (lambda () (cie-only-prop! dm sm (list 'IN x 'u) (list 'IN x 'SET) (list 'NOT (list '= x 'z)))))))))
(define (cie-cf-t-pt! x)
  (cie-steps
    (lambda () (cie-tpt! x 'z))
    (lambda () (fact 'subset-mem-fwd cie-T 'u x))
    (lambda () (fact 'fun-apply-type-c 'f 'u 'CC x))
    (lambda () (fact 'subset-mem-fwd cie-T cie-cf-w x))))
(define cie-cf-f1 (cie-f1 'z))
(define cie-cf-kt (list 'VNB-LAMBDA 'cifw_ cie-T '(recip (- cifw_ z))))
(define cie-cf-f2 (list 'VNB-LAMBDA 'cifw_ cie-T '(* (f z) (recip (- cifw_ z)))))
(define cie-cf-lk (cie-LI (cie-kern 'z)))
(define cie-rf (list 'RESTRICT 'f cie-T))
(define (cie-f1r z) (list 'VNB-LAMBDA 'aiw_ cie-T (list '* (list cie-rf 'aiw_) (list 'recip (list '- 'aiw_ z)))))
(define (cie-disc-setting!)
  (cie-center-in-ball! 'c 'cifs_)
  (cie-circle-basics!)
  (dk-have! '(<= 0 r) (lambda () (dk-ineq! '(< 0 r))))
  (dk-cite! 'trace-is-set cie-C 0 cie-tp)
  (fact 'subset-refl cie-T)
  (dk-cite! 'circle-path-closed 'c 'r)
  (fact 'nf-cc-is-metric-space)
  (fact 'nf-metric-carrier 'CC-NORMED-FIELD)
  (fact 'cc-nf-carr)
  (dk-have! (list '== (list 'PTS cie-nfm) 'CC)
    (lambda () (subst (list '== (list 'PTS cie-nfm) '(CARR CC-NORMED-FIELD))) (ass)))
  (dk-cite! 'holomorphic-on-in-fun 'u 'f)
  (dk-cite! 'holomorphic-on-open 'u 'f)
  (dk-cite! 'holomorphic-on-continuous 'u 'f)
  (dk-cite! 'cc-open-subset-cc 'u)
  (dk-have! (list 'SUBSET 'u (list 'PTS cie-nfm))
    (lambda () (subst (list '== (list 'PTS cie-nfm) 'CC)) (ass)))
  (dk-have! (list 'SUBSET cie-T '(BALL CC-MS c cifs_))
    (lambda ()
      (let* ((y (subset-by-element!)) (leaf (proof-state-focus *ps*)))
        (cie-circ-pt! y)
        (dk-have! (list '< (list 'magnitude (list '- y 'c)) 'cifs_)
          (lambda () (dk-ineq! (list '= (list 'magnitude (list '- y 'c)) 'r) '(< r cifs_))))
        (cie-in-ball! y 'c 'cifs_)
        (if (not (sequent-node-grounded? leaf)) (ass)))))
  (dk-cite! 'subset-trans cie-T '(BALL CC-MS c cifs_) 'u)
  (dk-cite! 'restrict-in-fun 'f 'u 'CC cie-T)
  (dk-have! (cie-cont cie-T cie-rf)
    (lambda ()
      (let* ((y (dk-di-var!)))
        (fact 'subset-mem-fwd cie-T 'u y)
        (dk-apply! (dk-ctx-form (cie-cont 'u 'f)) y)
        (dk-cite! 'subspace-restrict-continuous-at cie-nfm 'u cie-T cie-nfm 'f y)
        (ass))))
  (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cie-T) '(<= r (magnitude (- aix_ c)))))
    (lambda ()
      (let* ((y (dk-di-var!)) (m (list 'magnitude (list '- y 'c))))
        (fact 'subset-mem-fwd cie-T 'CC y)
        (dk-cite! 'circle-trace-magnitude 'c 'r y)
        (cie-rr! m)
        (dk-ineq! (list '= m 'r))))))
(define cie-disc-hyps
  '((HOLOMORPHIC-ON u f) (IN c CC) (IN cifs_ RR) (< 0 cifs_) (SUBSET (BALL CC-MS c cifs_) u)
    (IN r RR) (< 0 r) (< r cifs_)))
(define (cie-under-disc body)
  (list 'FORALL 'u (list 'FORALL 'f (list 'IMPLIES '(HOLOMORPHIC-ON u f)
    (list 'FORALL 'c (list 'IMPLIES '(IN c CC) (list 'FORALL 'cifs_ (list 'IMPLIES '(IN cifs_ RR) (list 'IMPLIES '(< 0 cifs_)
      (list 'IMPLIES '(SUBSET (BALL CC-MS c cifs_) u)
        (list 'FORALL 'r (list 'IMPLIES '(IN r RR) (list 'IMPLIES '(< 0 r) (list 'IMPLIES '(< r cifs_) body))))))))))))))
(define cie-kap (list 'recip cie-tpi))
(define cie-fr-f1 (cie-f1 'z))
(define cie-fr-kt (list 'VNB-LAMBDA 'cifw_ cie-T '(recip (- cifw_ z))))
(define (cie-fr-pt! x)
  (cie-steps
    (lambda () (cie-tpt! x 'z))
    (lambda () (fact 'subset-mem-fwd cie-T 'u x))
    (lambda () (fact 'fun-apply-type-c 'f 'u 'CC x))))
(define (cie-h3 z)
  (list 'VNB-LAMBDA 'aitk_ 'NN
    (list '* (list '* cie-kap (cie-LI (list 'VNB-LAMBDA 'aiw_ cie-T
                                            (list '* (list cie-rf 'aiw_) (list 'power '(recip (- aiw_ c)) '(succ aitk_))))))
             (list 'power (list '- z 'c) 'aitk_))))
(define cie-formula-r
  (list 'FORALL 'z (list 'IMPLIES '(IN z CC) (list 'IMPLIES '(< (magnitude (- z c)) r)
    (list '= '(f z) (list '* cie-kap (cie-LI (cie-f1r 'z))))))))

(define (cie-subst-rfl! eq)
  (let ((leaf (proof-state-focus *ps*)))
    (subst eq)
    (if (not (sequent-node-grounded? leaf)) (rfl))))
;;; (E0) |i| = 1
(sp (make-wff '(= (magnitude +i) 1)))
(let* ((m '(magnitude +i)))
  (fact 'cc-i-in)
  (fact 'rr-one-in)
  (cie-rr! m)
  (fact 'cc-magnitude-nonneg '+i)
  (dk-have! '(<= 0 1) (lambda () (dk-ineq!)))
  (cie-and! '(IN +i CC) '(IN +i CC))
  (dk-have! (list '= (list '* m m) '(* 1 1)) (lambda () (crs)))
  (cie-and! (list 'IN m 'RR) '(IN 1 RR))
  (cie-and! (list '<= 0 m) '(<= 0 1))
  (dk-cite! 'sqrt-unique m 1)
  (ass))
(qed 'cc-magnitude-i)

;;; (E1) the length of the circle of radius r: 2 pi r
(sp (make-wff (list 'FORALL 'c (list 'IMPLIES '(IN c CC) (list 'FORALL 'r (list 'IMPLIES '(IN r RR) (list 'IMPLIES '(<= 0 r)
  (list '= (list 'ROAD-LENGTH cie-Cd 0 cie-tp) (list '* cie-tp 'r)))))))))
(dk-peel!)
(cie-rr! cie-tp)
(dk-have! (list '< 0 cie-tp) (lambda () (dk-ineq! '(< 0 PI))))
(fact 'rr-zero-in)
(cie-in-I! 0)
(cie-in-I! cie-tp)
(fact 'cc-magnitude-i)
(mac 'ROAD-LENGTH)
(let* ((lam (cadr (cadr (dk-goal))))
       (val! (lambda (y)
               ;; y in [0, 2 pi]: |CIRCLE-DERIV(c, r)(y)| = r, after unfolding
               (let* ((e (list 'CC-EXP (list '* '+i y))) (x (list '* 'r e)))
                 (fact 'ccint-elt-in-rr 0 cie-tp y)
                 (cie-cc! x)
                 (cie-and! '(IN +i CC) (list 'IN x 'CC))
                 (cie-and! '(IN r CC) (list 'IN e 'CC))
                 (dk-cite! 'cc-magnitude-mul '+i x)
                 (dk-cite! 'cc-magnitude-mul 'r e)
                 (dk-cite! 'cc-exp-magnitude-imaginary y)
                 (dk-cite! 'rr-magnitude-is-abs 'r)
                 (dk-cite! 'rr-abs-of-nonneg 'r)))))
  (fact 'rr-is-set)
  (fact 'ccint-subset-rr 0 cie-tp)
  (fact 'subclass-of-set-is-set cie-I 'RR)
  (dk-have! (list 'FORALL 'pay_ (list 'IMPLIES (list 'IN 'pay_ cie-I) (list '== (list lam 'pay_) 'r)))
    (lambda ()
      (let* ((y (dk-di-var!)))
        (val! y)
        (dk-lam-b!)
        (mac 'CIRCLE-DERIV)
        (dk-lam-b!)
        (let* ((e (list 'CC-EXP (list '* '+i y))) (x (list '* 'r e)))
          (subst (list '= (list 'magnitude (list '* '+i x)) (list '* '(magnitude +i) (list 'magnitude x))))
          (subst (list '= (list 'magnitude x) (list '* '(magnitude r) (list 'magnitude e))))
          (subst (list '= (list 'magnitude e) 1))
          (subst '(= (magnitude r) (abs r)))
          (subst '(= (abs r) r))
          (subst '(= (magnitude +i) 1))
          (dk-have! '(= (* 1 (* r 1)) r) (lambda () (crs)))
          (cie-subst-qrfl! '(= (* 1 (* r 1)) r))))))
  (dk-have! (list 'IN lam (list 'FUN cie-I 'RR))
    (lambda ()
      (dk-lam-type!
        (lambda ()
          (let* ((y (dk-di-var!)) (leaf (proof-state-focus *ps*)))
            (dk-apply! (dk-ctx-form (list 'FORALL 'pay_ (list 'IMPLIES (list 'IN 'pay_ cie-I) (list '== (list lam 'pay_) 'r)))) y)
            (cie-lam-b-if!)
            (if (not (sequent-node-grounded? leaf))
                (begin
                  (val! y)
                  (mac 'CIRCLE-DERIV)
                  (dk-lam-b!)
                  (cie-rr! (cadr (dk-goal)))
                  (ass)))))
        ass)))
  (let* ((cst (dk-cite! 'pw-int-const 0 cie-tp 'r lam)))
    (subst cst)
    (crs)))
(qed 'circle-road-length)

;;; (E2) |1/(2 pi i)| = 1/(2 pi)
(sp (make-wff (list '= (list 'magnitude cie-kap) (list 'recip cie-tp))))
(cie-tpi!)
(fact 'cc-magnitude-i)
(dk-cite! 'aif-magnitude-recip cie-tpi)
(subst (list '= (list 'magnitude cie-kap) (list 'recip (list 'magnitude cie-tpi))))
(cie-and! (list 'IN cie-tp 'CC) '(IN +i CC))
(subst (dk-cite! 'cc-magnitude-mul cie-tp '+i))
(subst (dk-cite! 'rr-magnitude-is-abs cie-tp))
(dk-have! (list '<= 0 cie-tp) (lambda () (dk-ineq! (list '< 0 cie-tp))))
(subst (dk-cite! 'rr-abs-of-nonneg cie-tp))
(subst '(= (magnitude +i) 1))
(dk-have! (list '= (list '* cie-tp 1) cie-tp) (lambda () (crs)))
(subst (list '= (list '* cie-tp 1) cie-tp))
(cie-and! (list 'IN cie-tp 'RR) (list 'NOT (list '= cie-tp 0)))
(dk-cite! 'rr-recip-closed cie-tp)
(rfl)
(qed 'cauchy-kernel-constant-magnitude)

;;; (E3) CAUCHY'S ESTIMATES (Prop 3.47 in the coefficient form): |f| <= M on the circle
;;; C(c, r) => the k-th coefficient of holomorphic-power-series-disc has modulus <= M r^-k
(define (cie-coef k)
  (list '* cie-kap (cie-LI (list 'VNB-LAMBDA 'aiw_ cie-T
                             (list '* (list cie-rf 'aiw_) (list 'power '(recip (- aiw_ c)) (list 'succ k)))))))
(define cie-bnd-h (list 'FORALL 'ciey_ (list 'IMPLIES (list 'IN 'ciey_ cie-T) '(<= (magnitude (f ciey_)) ciebd_))))
(sp (make-wff (cie-under-disc
  (list 'FORALL 'ciebd_ (list 'IMPLIES '(IN ciebd_ RR) (list 'IMPLIES cie-bnd-h
    (list 'FORALL 'k (list 'IMPLIES '(IN k NN)
      (list '<= (list 'magnitude (cie-coef 'k)) '(* ciebd_ (power (recip r) k)))))))))))
(dk-peel!)
(cie-disc-setting!)
(cie-tpi!)
(define (cie-rf-bound!)
  (dk-have! (list 'FORALL 'aiy_ (list 'IMPLIES (list 'IN 'aiy_ cie-T) (list '<= (list 'magnitude (list cie-rf 'aiy_)) 'ciebd_)))
    (lambda ()
      (let* ((y (dk-di-var!)))
        (dk-apply! (dk-ctx-form cie-bnd-h) y)
        (dk-cite! 'restrict-apply 'f cie-T y)
        (cie-subst-ass! (list '== (list cie-rf y) (list 'f y)))))))
(cie-rf-bound!)
(let* ((est (dk-cite! 'cauchy-estimate-from-formula cie-T 'c 'r cie-rf cie-C cie-Cd 0 cie-tp 'ciebd_ cie-kap 'k))
       (rhs (caddr est))
       (q '(recip r)) (p '(power (recip r) k)))
  (dk-cite! 'circle-road-length 'c 'r)
  (dk-cite! 'cauchy-kernel-constant-magnitude)
  (fact 'rr-pos-ne-zero 'r)
  (cie-and! '(IN r RR) '(NOT (= r 0)))
  (dk-cite! 'rr-recip-closed 'r)
  (dk-cite! 'rr-recip-inverse 'r)
  (cie-and! (list 'IN cie-tp 'RR) (list 'NOT (list '= cie-tp 0)))
  (dk-cite! 'rr-recip-closed cie-tp)
  (dk-cite! 'rr-recip-inverse cie-tp)
  (fact 'power-real-closed q 'k)
  (dk-have! (list '= '(* ciebd_ (power (recip r) k)) rhs)
    (lambda ()
      (subst (list '= (list 'magnitude cie-kap) (list 'recip cie-tp)))
      (subst (list '= (list 'ROAD-LENGTH cie-Cd 0 cie-tp) (list '* cie-tp 'r)))
      (fact 'cc-i-in)
      (fact 'rr-subset-cc q)
      (subst (cie-pow-succ! q 'k))
      (let* ((pv (dk-name! p)) (a (dk-name! (list 'recip cie-tp))) (qv (dk-name! q)))
        (subst (list '= p pv))
        (subst (list '= (list 'recip cie-tp) a))
        (subst (list '= q qv))
        (dk-have! (list '= (list '* cie-tp a) 1) (lambda () (subst (list '= a (list 'recip cie-tp))) (ass)))
        (dk-have! (list '= (list '* 'r qv) 1) (lambda () (subst (list '= qv q)) (ass)))
        (let* ((e (list '= (list '* a (list '* (list '* cie-tp 'r) (list '* 'ciebd_ (list '* qv pv))))
                       (list '* (list '* (list '* cie-tp a) (list '* 'r qv)) (list '* 'ciebd_ pv)))))
          (dk-have! e (lambda () (crs)))
          (subst e)
          (subst (list '= (list '* cie-tp a) 1))
          (subst (list '= (list '* 'r qv) 1))
          (crs)))))
  (cie-subst-ass! (list '= '(* ciebd_ (power (recip r) k)) rhs)))
(qed 'cauchy-estimate-circle)

;;; (E4) the bound at the centre (k = 0): |f(c)| <= M when |f| <= M on the circle
(sp (make-wff (cie-under-disc
  (list 'FORALL 'ciebd_ (list 'IMPLIES '(IN ciebd_ RR) (list 'IMPLIES cie-bnd-h
    '(<= (magnitude (f c)) ciebd_)))))))
(dk-peel!)
(cie-disc-setting!)
(cie-tpi!)
(cie-pz-setup! 'c)
(cie-kern-setup! 'c)
(cie-trace-in-pz! 'c)
(cie-center-in-ball! 'c 'r)
(cie-cc! '(- c c))
(dk-have! '(= (- c c) 0) (lambda () (crs)))
(dk-congr! '(= (- c c) 0) (lambda (w) (list 'magnitude w)))
(fact 'cc-magnitude-zero)
(cie-rr! '(magnitude (- c c)))
(dk-have! '(< (magnitude (- c c)) r) (lambda () (dk-ineq! '(= (magnitude (- c c)) (magnitude 0)) '(= (magnitude 0) 0) '(< 0 r))))
(define cie-ce-i1 (cie-f1r 'c))
(define cie-ce-i0 (list 'VNB-LAMBDA 'aiw_ cie-T (list '* (list cie-rf 'aiw_) (list 'power '(recip (- aiw_ c)) '(succ 0)))))
(define cie-ce-kt (list 'VNB-LAMBDA 'cifw_ cie-T '(recip (- cifw_ c))))
(define (cie-ce-pt! x)
  (cie-steps
    (lambda () (cie-tpt! x))
    (lambda () (fact 'subset-mem-fwd cie-T 'u x))
    (lambda () (fact 'fun-apply-type-c 'f 'u 'CC x))
    (lambda () (dk-cite! 'restrict-apply 'f cie-T x))))
(fact 'nn-zero-in)
(fact 'nn-succ-closed 0)
(cie-lam-typ! cie-ce-kt cie-T (lambda (v) (cie-ce-pt! v)))
(cie-lam-typ! cie-ce-i1 cie-T (lambda (v) (cie-ce-pt! v) (cie-lam-b-if!) (subst (list '== (list cie-rf v) (list 'f v)))))
(cie-lam-typ! cie-ce-i0 cie-T (lambda (v) (cie-ce-pt! v) (cie-lam-b-if!) (subst (list '== (list cie-rf v) (list 'f v)))))
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cie-T) (list '== (list cie-ce-kt 'aix_) (list (cie-kern 'c) 'aix_))))
  (lambda () (let* ((x (dk-di-var!))) (cie-ce-pt! x) (dk-lam-b!) (qrfl))))
(dk-cite! 'aif-cont-holo-restrict (cie-pz 'c) (cie-kern 'c) cie-T cie-ce-kt)
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cie-T) (list '== (list cie-ce-i1 'aix_) (list '* (list cie-rf 'aix_) (list cie-ce-kt 'aix_)))))
  (lambda () (let* ((x (dk-di-var!))) (cie-ce-pt! x) (dk-lam-b!) (qrfl))))
(dk-cite! 'aif-cont-product cie-T cie-rf cie-ce-kt cie-ce-i1)
(dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ cie-T) (list '== (list cie-ce-i0 'wnx_) (list cie-ce-i1 'wnx_))))
  (lambda ()
    (let* ((x (dk-di-var!)) (ax (list 'recip (list '- x 'c))))
      (cie-ce-pt! x)
      (dk-lam-b!)
      (subst (cie-pow-succ! ax 0))
      (subst (dk-cite! 'power-zero ax))
      (let* ((e (list '= (list '* ax 1) ax)))
        (dk-have! e (lambda () (crs)))
        (cie-subst-qrfl! e)))))
(define cie-ce-e1 (dk-cite! 'line-int-domain-congruence cie-T cie-ce-i1 cie-C cie-Cd 0 cie-tp cie-T cie-ce-i0))
(dk-cite! 'cauchy-integral-formula-disc-restrict 'u 'f 'c 'cifs_ 'r 'c)
(subst (list '= '(f c) (list '* cie-kap (cie-LI cie-ce-i1))))
(subst (list '= (cie-LI cie-ce-i1) (cie-LI cie-ce-i0)))
(let* ((est (dk-cite! 'cauchy-estimate-circle 'u 'f 'c 'cifs_ 'r 'ciebd_ 0))
       (eq '(= ciebd_ (* ciebd_ (power (recip r) 0)))))
  (cie-rr! '(recip r))
  (fact 'rr-subset-cc '(recip r))
  (dk-cite! 'power-zero '(recip r))
  (dk-have! eq (lambda () (subst '(= (power (recip r) 0) 1)) (crs)))
  (cie-subst-ass! eq))
(qed 'cauchy-estimate-center)
;;; (E5) the coefficients of holomorphic-power-series-disc: typed, and every 0 <= rho < r
;;; lies below the radius of convergence of their sequence
(define (cie-hcoef k)
  (list 'VNB-LAMBDA 'aiw_ cie-T (list '* (list cie-rf 'aiw_) (list 'power '(recip (- aiw_ c)) (list 'succ k)))))
(define cie-RT (list 'VNB-LAMBDA 'aiw_ cie-T '(recip (- aiw_ c))))
(define (cie-tpt-rf! v)
  (cie-steps
    (lambda () (cie-tpt! v))
    (lambda () (fact 'fun-apply-type-c cie-rf cie-T 'CC v))))
;;; in the disc setting with T inside CC \ {c}: the reciprocal 1/(w - c) on T, continuous
(define (cie-RT-setup!)
  (cie-lam-typ! cie-RT cie-T (lambda (v) (cie-tpt! v)))
  (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cie-T) '(NOT (= aix_ c))))
    (lambda () (let* ((v (dk-di-var!)) (leaf (proof-state-focus *ps*))) (cie-tpt! v) (if (not (sequent-node-grounded? leaf)) (ass)))))
  (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cie-T) (list '== (list cie-RT 'aix_) '(recip (- aix_ c)))))
    (lambda () (let* ((v (dk-di-var!))) (cie-tpt! v) (dk-lam-b!) (qrfl))))
  (dk-cite! 'aif-cont-recip-shift cie-T 'c cie-RT))
;;; k in NN in context: H_k typed and continuous on T, its integral in CC
(define (cie-Hk! k)
  (let* ((P (list 'VNB-LAMBDA 'aiw_ cie-T (list 'power '(recip (- aiw_ c)) (list 'succ k))))
        (H (cie-hcoef k)))
    (fact 'nn-succ-closed k)
    (cie-lam-typ! P cie-T (lambda (v) (cie-tpt! v)))
    (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cie-T) (list '== (list P 'aix_) (list 'power (list cie-RT 'aix_) (list 'succ k)))))
      (lambda () (let* ((v (dk-di-var!))) (cie-tpt! v) (dk-lam-b!) (qrfl))))
    (dk-cite! 'aif-cont-power-of cie-T cie-RT (list 'succ k) P)
    (cie-lam-typ! H cie-T (lambda (v) (cie-tpt-rf! v)))
    (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ cie-T) (list '== (list H 'aix_) (list '* (list cie-rf 'aix_) (list P 'aix_)))))
      (lambda () (let* ((v (dk-di-var!))) (cie-tpt-rf! v) (dk-lam-b!) (qrfl))))
    (dk-cite! 'aif-cont-product cie-T cie-rf P H)
    (dk-cite! 'line-int-in-cc cie-T H cie-C cie-Cd 0 cie-tp)))
(define cie-g-h (list 'FORALL 'ciek_ (list 'IMPLIES '(IN ciek_ NN) (list '= '(cieg_ ciek_) (cie-coef 'ciek_)))))
(sp (make-wff (cie-under-disc
  (list 'FORALL 'cieg_ (list 'IMPLIES '(IN cieg_ (FUN NN CC)) (list 'IMPLIES cie-g-h
    (list 'FORALL 'cierho_ (list 'IMPLIES '(IN cierho_ RR) (list 'IMPLIES '(<= 0 cierho_) (list 'IMPLIES '(< cierho_ r)
      '(< cierho_ (CPS-RADIUS cieg_))))))))))))
(dk-peel!)
(cie-disc-setting!)
(cie-tpi!)
(cie-pz-setup! 'c)
(cie-trace-in-pz! 'c)
(cie-RT-setup!)
(define cie-rd-t '(* 1/2 (+ cierho_ r)))
(cie-rr! cie-rd-t)
(dk-have! (list '<= 0 cie-rd-t) (lambda () (dk-ineq! '(<= 0 cierho_) '(< 0 r))))
(dk-have! (list '< 'cierho_ cie-rd-t) (lambda () (dk-ineq! '(< cierho_ r))))
(dk-have! (list '< cie-rd-t 'r) (lambda () (dk-ineq! '(< cierho_ r))))
(define cie-rd-zt (list '+ 'c cie-rd-t))
(fact 'rr-subset-cc cie-rd-t)
(cie-cc! cie-rd-zt)
(dk-have! (list '= (list '- cie-rd-zt 'c) cie-rd-t) (lambda () (crs)))
(dk-cite! 'rr-magnitude-is-abs cie-rd-t)
(dk-cite! 'rr-abs-of-nonneg cie-rd-t)
(dk-have! (list '= (list 'magnitude cie-rd-t) cie-rd-t)
  (lambda () (subst (list '= (list 'magnitude cie-rd-t) (list 'abs cie-rd-t))) (ass)))
(dk-have! (list '< (list 'magnitude (list '- cie-rd-zt 'c)) 'r)
  (lambda () (subst (list '= (list '- cie-rd-zt 'c) cie-rd-t))
              (subst (list '= (list 'magnitude cie-rd-t) cie-rd-t)) (ass)))
(define cie-rd-abs (dk-cite! 'cauchy-kernel-series-absolute cie-T 'c 'r cie-rf cie-C cie-Cd 0 cie-tp cie-rd-zt))
(define cie-rd-absf (cadr cie-rd-abs))
(dk-cite! 'cauchy-kernel-constant-magnitude)
(cie-rr! (list 'recip cie-tp))
(dk-have! (list 'IN (list 'magnitude cie-kap) 'RR) (lambda () (cie-subst-ass! (list '= (list 'magnitude cie-kap) (list 'recip cie-tp)))))
(dk-cite! 'cc-magnitude-nonneg cie-kap)
(define (cie-rd-q j) (list 'power (list '- cie-rd-zt 'c) j))
(define cie-rd-tgt (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* (list 'magnitude '(cieg_ cpsk_)) (list 'power cie-rd-t 'cpsk_))))
(define (cie-rd-pt! j)
  (cie-Hk! j)
  (cie-cc! (cie-rd-q j))
  (cie-cc! (list '* (cie-LI (cie-hcoef j)) (cie-rd-q j)))
  (dk-cite! 'cc-magnitude-closed (list '* (cie-LI (cie-hcoef j)) (cie-rd-q j)))
  (dk-cite! 'cc-magnitude-nonneg (list '* (cie-LI (cie-hcoef j)) (cie-rd-q j))))
(dk-have! (list 'IN cie-rd-absf '(FUN NN RR))
  (lambda () (dk-lam-type! (lambda () (let* ((j (dk-di-var!)) (leaf (proof-state-focus *ps*)))
                                        (cie-rd-pt! j) (cie-lam-b-if!)
                                        (if (not (sequent-node-grounded? leaf)) (ass)))))))
(dk-have! (list 'FORALL 'cpsk_ (list 'IMPLIES '(IN cpsk_ NN) (list '<= 0 (list cie-rd-absf 'cpsk_))))
  (lambda () (let* ((j (dk-di-var!)) (leaf (proof-state-focus *ps*)))
               (cie-rd-pt! j) (cie-lam-b-if!) (if (not (sequent-node-grounded? leaf)) (ass)))))
(dk-have! (list 'IN cie-rd-tgt '(FUN NN RR))
  (lambda () (dk-lam-type! (lambda () (let* ((j (dk-di-var!)) (leaf (proof-state-focus *ps*)))
                                        (fact 'fun-apply-type-c 'cieg_ 'NN 'CC j)
                                        (dk-cite! 'cc-magnitude-closed (list 'cieg_ j))
                                        (fact 'power-real-closed cie-rd-t j)
                                        (cie-lam-b-if!)
                                        (cie-rr! (cadr (dk-goal)))
                                        (if (not (sequent-node-grounded? leaf)) (ass)))))))
(dk-have! (list 'FORALL 'cpsk_ (list 'IMPLIES '(IN cpsk_ NN)
            (list '= (list cie-rd-tgt 'cpsk_) (list '* (list 'magnitude cie-kap) (list cie-rd-absf 'cpsk_)))))
  (lambda ()
    (let* ((j (dk-di-var!)) (A (cie-LI (cie-hcoef j))) (q (list '- cie-rd-zt 'c)) (tj (list 'power cie-rd-t j)))
      (cie-rd-pt! j)
      (fact 'power-real-closed cie-rd-t j)
      (dk-cite! 'cc-magnitude-closed A)
      (dk-lam-b!)
      (subst (dk-apply! (dk-ctx-form cie-g-h) j))
      (cie-and! (list 'IN cie-kap 'CC) (list 'IN A 'CC))
      (subst (dk-cite! 'cc-magnitude-mul cie-kap A))
      (cie-and! (list 'IN A 'CC) (list 'IN (cie-rd-q j) 'CC))
      (subst (dk-cite! 'cc-magnitude-mul A (cie-rd-q j)))
      (subst (dk-cite! 'cc-magnitude-power j q))
      (let* ((e (list '= (list '* (list '* (list 'magnitude cie-kap) (list 'magnitude A)) tj)
                        (list '* (list 'magnitude cie-kap) (list '* (list 'magnitude A) tj)))))
        (cie-steps
          (lambda () (subst (list '= q cie-rd-t)))
          (lambda () (subst (list '= (list 'magnitude cie-rd-t) cie-rd-t)))
          (lambda () (dk-have! e (lambda () (crs))))
          (lambda () (subst e))
          ass)))))
(dk-cite! 'series-scale-converges cie-rd-absf (list 'magnitude cie-kap) cie-rd-tgt)
(define cie-rd-E
  (list 'SEP 'cpsr_ 'RR (list 'AND '(<= 0 cpsr_)
    (list 'SERIES-CONVERGES (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* (list 'magnitude '(cieg_ cpsk_)) '(power cpsr_ cpsk_)))))))
(dk-have! (list 'IN cie-rd-t cie-rd-E)
  (lambda () (in-sep! (lambda () (dk-conj-close! dk-ass!)))))
(dk-have! (list 'SUBSET cie-rd-E 'RR-POS-STAR)
  (lambda ()
    (mac 'subset-def)
    (let* ((x (dk-di-var!)))
      (sep-me (list 'IN x cie-rd-E))
      (dk-split-all!)
      (mac 'rr-pos-star-membership)
      (oi-l)
      (dk-conj-close! dk-ass!))))
(define cie-rd-sup (list 'ESUP cie-rd-E))
(dk-apply! (dk-cite! 'esup-upper cie-rd-E) cie-rd-t)
(fact 'esup-in cie-rd-E)
(subst (dk-fact! 'cps-radius-unfold 'cieg_))
(mac-h 'rr-pos-star-membership (list 'IN cie-rd-sup 'RR-POS-STAR))
(use-cases (dk-pick (dk-head? 'OR) "the two kinds of extended real")
  (lambda ()
    (dk-split-all!)
    (dk-ineq! (list '< 'cierho_ cie-rd-t) (list '<= cie-rd-t cie-rd-sup)))
  (lambda ()
    (subst (list '= cie-rd-sup 'POS-INF))
    (mac '<)
    (dk-conj-close!
      (lambda ()
        (if (dk-head-is? (dk-goal) '<=)
            (begin
              (dk-have! '(IN cierho_ RR-POS-STAR)
                (lambda () (mac 'rr-pos-star-membership) (oi-l) (dk-conj-close! dk-ass!)))
              (fact 'rr-pos-star-below-pos-inf 'cierho_)
              (ass))
            (begin
              (di)
              (fact 'pos-inf-not-in-rr)
              (dk-have! '(IN POS-INF RR) (lambda () (subst (list '= 'POS-INF 'cierho_)) (ass)))
              (ai '(NOT (IN POS-INF RR)))))))))
(qed 'cauchy-coefficients-radius)

;;; (E6) on a ball B(c, rho), 0 < rho < r, f is the sum sum_k g(k) (z - c)^k of the
;;; coefficient sequence g (the shape taylor-coefficients-at reads)
(define (cie-ser g z) (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* (list g 'cpsk_) (list 'power (list '- z 'c) 'cpsk_))))
(define (cie-h3b z)
  (list 'VNB-LAMBDA 'aitk_ 'NN (list '* (cie-coef 'aitk_) (list 'power (list '- z 'c) 'aitk_))))
(sp (make-wff (cie-under-disc
  (list 'FORALL 'cieg_ (list 'IMPLIES '(IN cieg_ (FUN NN CC)) (list 'IMPLIES cie-g-h
    (list 'FORALL 'z (list 'IMPLIES '(IN z CC) (list 'IMPLIES '(< (magnitude (- z c)) r)
      (list '= '(f z) (list 'CC-SERIES-LIMIT (cie-ser 'cieg_ 'z))))))))))))
(dk-peel!)
(cie-disc-setting!)
(cie-tpi!)
(cie-pz-setup! 'c)
(cie-trace-in-pz! 'c)
(cie-RT-setup!)
(define cie-sr-h3 (cie-h3b 'z))
(define cie-sr-s (cie-ser 'cieg_ 'z))
(define cie-sr-ct (dk-cite! 'holomorphic-power-series-disc 'u 'f 'c 'cifs_ 'r 'z))
(cie-cc! '(- z c))
(define (cie-sr-typ! lam)
  (cie-lam-typ! lam 'NN (lambda (j) (cie-Hk! j) (fact 'fun-apply-type-c 'cieg_ 'NN 'CC j))))
(cie-sr-typ! cie-sr-h3)
(cie-sr-typ! cie-sr-s)
(dk-fun-ext! cie-sr-s cie-sr-h3 'NN 'CC #f #f
  (lambda (v)
    (cie-Hk! v)
    (cie-cc! (cie-coef v))
    (cie-cc! (list '* (cie-coef v) (list 'power '(- z c) v)))
    (dk-lam-b!)
    (cie-subst-rfl! (dk-apply! (dk-ctx-form cie-g-h) v))))
(dk-have! (list 'CC-SERIES-CONVERGES cie-sr-h3)
  (lambda () (mac 'cc-series-converges) (mac 'converges) (ew '(f z))
              (mac-h 'cc-series-converges-to (dk-ctx-form cie-sr-ct)) (ass)))
(fact 'cc-series-limit-converges-to cie-sr-h3)
(fact 'cc-series-limit-in-cc cie-sr-h3)
(cie-rr! '(magnitude (- z c)))
(dk-have! '(< (magnitude (- z c)) cifs_) (lambda () (dk-ineq! '(< (magnitude (- z c)) r) '(< r cifs_))))
(cie-in-ball! 'z 'c 'cifs_)
(fact 'subset-mem-fwd '(BALL CC-MS c cifs_) 'u 'z)
(fact 'fun-apply-type-c 'f 'u 'CC 'z)
(let* ((lim (list 'CC-SERIES-LIMIT cie-sr-h3))
      (ps (list 'VNB-LAMBDA 'k 'NN (list 'CC-SERIES-PARTIAL-SUM cie-sr-h3 'k))))
  (dk-have! (list '= lim '(f z))
    (lambda ()
      (dk-project! (list 'CONVERGES-TO 'CC-MS ps lim) 'cc-series-converges-to (list 'CC-SERIES-CONVERGES-TO cie-sr-h3 lim))
      (dk-project! (list 'CONVERGES-TO 'CC-MS ps '(f z)) 'cc-series-converges-to (list 'CC-SERIES-CONVERGES-TO cie-sr-h3 '(f z)))
      (dk-cite! 'metric-limit-unique 'CC-MS ps lim '(f z))
      (ass)))
  (subst (list '= cie-sr-s cie-sr-h3))
  (subst (list '= lim '(f z)))
  (rfl))
(qed 'holomorphic-coefficient-series)
;;; (E7) THE DERIVATIVE FORMULA (Prop 3.40 / Cor 3.42 through the coefficients): on a
;;; ball B(c, rho), 0 < rho < r, the k-th derivative of f at c is k! times the k-th
;;; coefficient kap int_C(c, r) f(w) / (w - c)^(k+1) dw
(define cie-rho-h '((IN cierho_ RR) (< 0 cierho_) (< cierho_ r)))
(define cie-brho '(BALL CC-MS c cierho_))
(define (cie-nth k) (list (list 'NTH-DERIV-ON 'CC-NORMED-FIELD cie-brho (list 'RESTRICT 'f cie-brho) k) 'c))
(define (cie-under-rho body)
  (cie-under-disc (list 'FORALL 'cierho_ (cie-imps cie-rho-h body))))
(sp (make-wff (cie-under-rho
  (list 'FORALL 'k (list 'IMPLIES '(IN k NN)
    (list '= (cie-nth 'k) (list '* '(factorial k) (cie-coef 'k))))))))
(dk-peel!)
(cie-disc-setting!)
(cie-tpi!)
(cie-pz-setup! 'c)
(cie-trace-in-pz! 'c)
(cie-RT-setup!)
(fact 'cc-is-set)
(define cie-df-pair
  (dk-abstract! 'NN 'CC (lambda (j) (cie-coef j))
                (lambda (j) (let* ((leaf (proof-state-focus *ps*)))
                              (cie-Hk! j) (cie-cc! (cie-coef j))
                              (if (not (sequent-node-grounded? leaf)) (ass))))))
(define cie-df-g (car cie-df-pair))
(define cie-df-gv (cdr cie-df-pair))
(define cie-df-gh (cie-subst-sym cie-g-h 'cieg_ cie-df-g))
(dk-have! cie-df-gh
  (lambda ()
    (let* ((j (dk-di-var!)))
      (cie-Hk! j) (cie-cc! (cie-coef j))
      (cie-subst-rfl! (dk-apply! cie-df-gv j)))))
(dk-have! '(<= 0 cierho_) (lambda () (dk-ineq! '(< 0 cierho_))))
(dk-cite! 'cauchy-coefficients-radius 'u 'f 'c 'cifs_ 'r cie-df-g 'cierho_)
(dk-have! (list 'SUBSET cie-brho 'u)
  (lambda ()
    (let* ((x (subset-by-element!)))
      (cie-ball-open! 'c 'cierho_ x)
      (dk-have! (list '< (list 'magnitude (list '- x 'c)) 'cifs_)
        (lambda () (dk-ineq! (list '< (list 'magnitude (list '- x 'c)) 'cierho_) '(< cierho_ r) '(< r cifs_))))
      (cie-in-ball! x 'c 'cifs_)
      (fact 'subset-mem-fwd '(BALL CC-MS c cifs_) 'u x)
      (ass))))
(dk-have! (list 'FORALL 'algz_ (list 'IMPLIES (list 'IN 'algz_ cie-brho)
            (list '= '(f algz_) (list 'CC-SERIES-LIMIT (cie-ser cie-df-g 'algz_)))))
  (lambda ()
    (let* ((x (dk-di-var!)))
      (cie-ball-open! 'c 'cierho_ x)
      (dk-have! (list '< (list 'magnitude (list '- x 'c)) 'r)
        (lambda () (dk-ineq! (list '< (list 'magnitude (list '- x 'c)) 'cierho_) '(< cierho_ r))))
      (dk-cite! 'holomorphic-coefficient-series 'u 'f 'c 'cifs_ 'r cie-df-g x)
      (ass))))
(let* ((tc (dk-cite! 'taylor-coefficients-at 'f 'u cie-df-g 'c 'cierho_ 'k)))
  (cie-Hk! 'k)
  (cie-cc! (cie-coef 'k))
  (subst tc)
  (subst (dk-apply! (dk-ctx-form cie-df-gh) 'k))
  (fact 'factorial-real-pos 'k)
  (dk-split-all!)
  (fact 'rr-subset-cc '(factorial k))
  (cie-cc! (list '* '(factorial k) (cie-coef 'k)))
  (rfl))
(qed 'cauchy-derivative-formula)

;;; (E8) CAUCHY'S ESTIMATES (Cor 3.48): |f| <= M on the circle C(c, r) => the k-th
;;; derivative at c has modulus <= k! M r^-k
(sp (make-wff (cie-under-rho
  (list 'FORALL 'ciebd_ (list 'IMPLIES '(IN ciebd_ RR) (list 'IMPLIES cie-bnd-h
    (list 'FORALL 'k (list 'IMPLIES '(IN k NN)
      (list '<= (list 'magnitude (cie-nth 'k)) '(* (factorial k) (* ciebd_ (power (recip r) k))))))))))))
(dk-peel!)
(cie-disc-setting!)
(cie-tpi!)
(cie-pz-setup! 'c)
(cie-trace-in-pz! 'c)
(cie-RT-setup!)
(let* ((co (cie-coef 'k)) (bd '(* ciebd_ (power (recip r) k))))
  (dk-cite! 'cauchy-derivative-formula 'u 'f 'c 'cifs_ 'r 'cierho_ 'k)
  (subst (list '= (cie-nth 'k) (list '* '(factorial k) co)))
  (cie-Hk! 'k)
  (cie-cc! co)
  (fact 'factorial-real-pos 'k)
  (dk-split-all!)
  (fact 'rr-subset-cc '(factorial k))
  (cie-and! '(IN (factorial k) CC) (list 'IN co 'CC))
  (subst (dk-cite! 'cc-magnitude-mul '(factorial k) co))
  (subst (dk-cite! 'rr-magnitude-is-abs '(factorial k)))
  (dk-have! '(<= 0 (factorial k)) (lambda () (dk-ineq! '(< 0 (factorial k)))))
  (subst (dk-cite! 'rr-abs-of-nonneg '(factorial k)))
  (let* ((est (dk-cite! 'cauchy-estimate-circle 'u 'f 'c 'cifs_ 'r 'ciebd_ 'k)))
    (fact 'rr-pos-ne-zero 'r)
    (cie-and! '(IN r RR) '(NOT (= r 0)))
    (dk-cite! 'rr-recip-closed 'r)
    (fact 'power-real-closed '(recip r) 'k)
    (cie-rr! bd)
    (dk-cite! 'cc-magnitude-closed co)
    (cie-and! (list '<= 0 '(factorial k)) (list '<= (list 'magnitude co) bd))
    (dk-cite! 'rr-le-scale-nonneg '(factorial k) (list 'magnitude co) bd)
    (ass)))
(qed 'cauchy-estimate-derivative)

;;; (E9) x <= K / R for every R > R0 (K >= 0) => x <= 0
(sp (make-wff '(FORALL ciex_ (IMPLIES (IN ciex_ RR) (FORALL ciek_ (IMPLIES (IN ciek_ RR) (FORALL ciea_ (IMPLIES (IN ciea_ RR)
  (IMPLIES (<= 0 ciea_) (IMPLIES (<= 0 ciek_)
    (IMPLIES (FORALL cieq_ (IMPLIES (IN cieq_ RR) (IMPLIES (< ciea_ cieq_) (<= ciex_ (* ciek_ (recip cieq_))))))
      (<= ciex_ 0))))))))))))
(dk-peel!)
(define cie-sq-h (dk-pick (lambda (fm) (and (dk-head-is? fm 'FORALL) (dk-contains? fm 'cieq_))) "the bound"))
(dk-cite! 'rr-le-all-pos-nonpos 'ciex_)
(let* ((imp (dk-pick (lambda (fm) (and (dk-head-is? fm 'IMPLIES) (dk-contains? fm 'POS-RR))) "the eps form")))
  (cie-detach! imp
    (lambda ()
      (dk-peel!)
      (let* ((e (cadr (dk-pick (dk-head? 'POS-RR) "eps"))))
        (dk-cite! 'rr-pos-rr-in-rr e)
        (dk-cite! 'rr-lt-of-pos-rr e)
        (fact 'rr-pos-ne-zero e)
        (cie-and! (list 'IN e 'RR) (list 'NOT (list '= e 0)))
        (dk-cite! 'rr-recip-closed e)
        (dk-cite! 'rr-recip-pos e)
        (dk-cite! 'rr-recip-inverse e)
        (let* ((re (dk-name! (list 'recip e)))
               (R (list '+ (list '+ 'ciea_ 1) (list '* 'ciek_ re))))
          (dk-have! (list '= (list '* e re) 1) (lambda () (subst (list '= re (list 'recip e))) (ass)))
          (dk-have! (list '< 0 re) (lambda () (subst (list '= re (list 'recip e))) (ass)))
          (cie-and! '(IN ciek_ RR) (list 'IN re 'RR))
          (dk-have! (list '<= 0 re) (lambda () (dk-ineq! (list '< 0 re))))
          (cie-and! '(<= 0 ciek_) (list '<= 0 re))
          (dk-cite! 'rr-leq-mul-nonneg 'ciek_ re)
          (cie-rr! R)
          (let* ((rv (dk-name! R)))
            (dk-have! (list '< 'ciea_ rv) (lambda () (dk-ineq! (list '= rv R) (list '<= 0 (list '* 'ciek_ re)))))
            (dk-have! (list '< 0 rv) (lambda () (dk-ineq! (list '= rv R) (list '<= 0 (list '* 'ciek_ re)) '(<= 0 ciea_))))
            (dk-apply! cie-sq-h rv)
            (fact 'rr-pos-ne-zero rv)
            (cie-and! (list 'IN rv 'RR) (list 'NOT (list '= rv 0)))
            (dk-cite! 'rr-recip-closed rv)
            (dk-cite! 'rr-recip-inverse rv)
            (let* ((rr (dk-name! (list 'recip rv)))
                   (p1 (begin (cie-rr! (list '* 'ciek_ rr)) (dk-name! (list '* 'ciek_ rr))))
                   (p2 (begin (cie-rr! (list '* e rv)) (dk-name! (list '* e rv)))))
              (dk-have! (list '= (list '* rv rr) 1) (lambda () (subst (list '= rr (list 'recip rv))) (ass)))
              (dk-have! (list '< 0 rr) (lambda () (dk-cite! 'rr-recip-pos rv) (subst (list '= rr (list 'recip rv))) (ass)))
              ;; e R = e (a + 1) + K
              (dk-have! (list '= p2 (list '+ (list '* e (list '+ 'ciea_ 1)) 'ciek_))
                (lambda ()
                  (subst (list '= p2 (list '* e rv)))
                  (subst (list '= rv R))
                  (let* ((eq (list '= (list '* e (list '+ (list '+ 'ciea_ 1) (list '* 'ciek_ re)))
                                  (list '+ (list '* e (list '+ 'ciea_ 1)) (list '* (list '* e re) 'ciek_)))))
                    (dk-have! eq (lambda () (crs)))
                    (subst eq)
                    (subst (list '= (list '* e re) 1))
                    (crs))))
              (cie-rr! (list '+ 'ciea_ 1))
              (cie-and! (list 'IN e 'RR) (list 'IN (list '+ 'ciea_ 1) 'RR))
              (dk-have! (list '<= 0 e) (lambda () (dk-ineq! (list '< 0 e))))
              (dk-have! (list '<= 0 (list '+ 'ciea_ 1)) (lambda () (dk-ineq! '(<= 0 ciea_))))
              (cie-and! (list '<= 0 e) (list '<= 0 (list '+ 'ciea_ 1)))
              (dk-cite! 'rr-leq-mul-nonneg e (list '+ 'ciea_ 1))
              (cie-rr! (list '* e (list '+ 'ciea_ 1)))
              (dk-have! (list '<= 'ciek_ p2)
                (lambda () (dk-ineq! (list '= p2 (list '+ (list '* e (list '+ 'ciea_ 1)) 'ciek_))
                                     (list '<= 0 (list '* e (list '+ 'ciea_ 1))))))
              (dk-have! (list '<= 0 rr) (lambda () (dk-ineq! (list '< 0 rr))))
              (dk-cite! 'rr-mul-le-right 'ciek_ p2 rr)
              (cie-rr! (list '* p2 rr))
              (dk-have! (list '= (list '* p2 rr) e)
                (lambda ()
                  (subst (list '= p2 (list '* e rv)))
                  (let* ((eq (list '= (list '* (list '* e rv) rr) (list '* e (list '* rv rr)))))
                    (dk-have! eq (lambda () (crs)))
                    (subst eq)
                    (subst (list '= (list '* rv rr) 1))
                    (crs))))
              (dk-have! (list '<= 'ciex_ p1)
                (lambda () (subst (list '= p1 (list '* 'ciek_ rr))) (subst (list '= rr (list 'recip rv))) (ass)))
              (dk-have! (list '<= p1 e)
                (lambda () (subst (list '= p1 (list '* 'ciek_ rr))) (subst (list '= e (list '* p2 rr))) (ass)))
              (dk-ineq! (list '<= 'ciex_ p1) (list '<= p1 e))))))))
  (ass))
(qed 'cie-squeeze)
;;; (E10) a bounded entire function has derivative 0 everywhere: the derivative at a is
;;; the first Taylor coefficient on B(a, 1/2), bounded by M / q for every circle radius q
(define cie-lv-bnd '(FORALL ciey_ (IMPLIES (IN ciey_ CC) (<= (magnitude (f ciey_)) ciebd_))))
(sp (make-wff (list 'FORALL 'f (list 'IMPLIES '(HOLOMORPHIC-ON CC f)
  (list 'FORALL 'ciebd_ (list 'IMPLIES '(IN ciebd_ RR) (list 'IMPLIES cie-lv-bnd
    '(FORALL a (IMPLIES (IN a CC) (IS-DIFF-ON CC-NORMED-FIELD CC f a 0))))))))))
(dk-peel!)
(fact 'cc-is-metric-space)
(dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
(fact 'nf-cc-is-metric-space)
(fact 'cc-nf-carr)
(dk-cite! 'holomorphic-on-open 'CC 'f)
(dk-cite! 'holomorphic-on-in-fun 'CC 'f)
(fact 'cc-zero-in)
(fact 'fun-apply-type-c 'f 'CC 'CC 0)
(dk-apply! (dk-ctx-form cie-lv-bnd) 0)
(dk-cite! 'cc-magnitude-closed '(f 0))
(dk-cite! 'cc-magnitude-nonneg '(f 0))
(dk-have! '(<= 0 ciebd_) (lambda () (dk-ineq! '(<= (magnitude (f 0)) ciebd_) '(<= 0 (magnitude (f 0))))))
(let* ((a 'a) (h 1/2)
       (bh (list 'BALL 'CC-MS a h))
       (l (dk-skolem! (dk-apply! (dk-cite! 'holomorphic-on-diff 'CC 'f) a)))
       (ml (list 'magnitude l))
       (nth (list (list 'NTH-DERIV-ON 'CC-NORMED-FIELD bh (list 'RESTRICT 'f bh) '(succ 0)) a)))
  (cie-rr! h)
  (dk-have! (list '< 0 h) (lambda () (dk-ineq!)))
  (cie-center-in-ball! a h)
  (let* ((iff (dk-cite! 'cc-ms-open-iff bh)))
    (dk-cite! 'ball-is-open 'CC-MS a h)
    (dk-have! (list 'IS-OPEN cie-nfm bh) (lambda () (cie-only-prop! iff (list 'IS-OPEN 'CC-MS bh)))))
  (dk-have! (list 'SUBSET bh 'CC) (lambda () (let ((x (subset-by-element!))) (cie-ball-open! a h x))))
  (let* ((dd (dk-pick (lambda (fm) (and (dk-head-is? fm 'IS-DIFF-ON) (dk-contains? fm l))) "the derivative at a")))
    (dk-project! (list 'IN l '(CARR CC-NORMED-FIELD)) 'IS-DIFF-ON dd)
    (dk-have! (list 'IN l 'CC) (lambda () (subst '(= CC (CARR CC-NORMED-FIELD))) (ass)))
    (dk-cite! 'diff-on-shrink 'CC-NORMED-FIELD 'CC 'f a l bh)
    (dk-cite! 'cc-deriv-on-of-is-diff-on bh (list 'RESTRICT 'f bh) a l))
  (fact 'nn-zero-in)
  (dk-have! (list '= nth l)
    (lambda ()
      (subst (dk-cite! 'nth-deriv-on-succ-apply 'CC-NORMED-FIELD bh (list 'RESTRICT 'f bh) 0 a))
      (subst (dk-cite! 'nth-deriv-on-zero 'CC-NORMED-FIELD bh (list 'RESTRICT 'f bh)))
      (ass)))
  (dk-cite! 'cc-magnitude-closed l)
  (dk-cite! 'cc-magnitude-nonneg l)
  ;; |f'(a)| <= M / q for every q > 1/2
  (dk-have! (list 'FORALL 'cieq_ (list 'IMPLIES '(IN cieq_ RR) (list 'IMPLIES (list '< h 'cieq_)
              (list '<= ml '(* ciebd_ (recip cieq_))))))
    (lambda ()
      (let* ((lk (dk-peel!))
             (q (cadr (car (filter (dk-head? 'IN) lk))))
             (s (list '+ q 1))
             (cp (list 'CIRCLE-PATH a q)) (cd (list 'CIRCLE-DERIV a q))
             (tr (list 'TRACE cp 0 cie-tp)))
        (cie-rr! s)
        (dk-have! (list '< 0 q) (lambda () (dk-ineq! (list '< h q))))
        (dk-have! (list '< 0 s) (lambda () (dk-ineq! (list '< h q))))
        (dk-have! (list '< q s) (lambda () (dk-ineq!)))
        (dk-have! (list 'SUBSET (list 'BALL 'CC-MS a s) 'CC)
          (lambda () (let ((x (subset-by-element!))) (cie-ball-open! a s x))))
        (dk-cite! 'circle-is-road a q)
        (fact 'is-road-is-path cp cd 0 cie-tp)
        (fact 'is-path-in-fun cp 0 cie-tp)
        (dk-cite! 'trace-subset-cc cp 0 cie-tp)
        (dk-have! (list 'FORALL 'ciey_ (list 'IMPLIES (list 'IN 'ciey_ tr) '(<= (magnitude (f ciey_)) ciebd_)))
          (lambda () (let ((y (dk-di-var!)))
                       (fact 'subset-mem-fwd tr 'CC y)
                       (dk-apply! (dk-ctx-form cie-lv-bnd) y)
                       (ass))))
        (fact 'nn-succ-closed 0)
        (let* ((est (dk-cite! 'cauchy-estimate-derivative 'CC 'f a s q h 'ciebd_ '(succ 0)))
               (rhs (caddr est))
               (rq (list 'recip q)))
          (fact 'rr-pos-ne-zero q)
          (cie-and! (list 'IN q 'RR) (list 'NOT (list '= q 0)))
          (dk-cite! 'rr-recip-closed q)
          (fact 'rr-subset-cc rq)
          (cie-rr! (list '* 'ciebd_ rq))
          (dk-have! (list '= (list '* 'ciebd_ rq) rhs)
            (lambda ()
              (subst (dk-cite! 'factorial-succ 0))
              (subst (dk-cite! 'factorial-zero))
              (subst (cie-pow-succ! rq 0))
              (subst (dk-cite! 'power-zero rq))
              (fact 'nn-one-is-succ-zero)
              (subst '(= (succ 0) 1))
              (crs)))
          (subst (list '= l nth))
          (cie-subst-ass! (list '= (list '* 'ciebd_ rq) rhs))))))
  (dk-have! (list '<= 0 h) (lambda () (dk-ineq!)))
  (dk-cite! 'cie-squeeze ml 'ciebd_ h)
  (dk-have! (list '= ml 0) (lambda () (dk-ineq! (list '<= ml 0) (list '<= 0 ml))))
  (let* ((iff (dk-cite! 'cc-magnitude-zero-iff l)))
    (dk-have! (list '= l 0) (lambda () (cie-only-prop! iff (list '= ml 0)))))
  (cie-subst-ass! (list '= 0 l)))
(qed 'bounded-entire-deriv-zero)

;;; (E11) LIOUVILLE: a bounded entire function is constant
(sp (make-wff (list 'FORALL 'f (list 'IMPLIES '(HOLOMORPHIC-ON CC f)
  (list 'FORALL 'ciebd_ (list 'IMPLIES '(IN ciebd_ RR) (list 'IMPLIES cie-lv-bnd
    '(FORALL z (IMPLIES (IN z CC) (= (f z) (f 0)))))))))))
(dk-peel!)
(fact 'cc-is-metric-space)
(dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
(fact 'nf-cc-is-metric-space)
(fact 'cc-zero-in)
(dk-cite! 'holomorphic-on-in-fun 'CC 'f)
(let* ((m (list 'magnitude (list '- 'z 0)))
       (rr (list '+ m 1))
       (bl (list 'BALL 'CC-MS 0 rr))
       (h (list 'RESTRICT 'f bl))
       (d0 (dk-cite! 'bounded-entire-deriv-zero 'f 'ciebd_)))
  (cie-rr! rr)
  (dk-cite! 'cc-magnitude-nonneg (list '- 'z 0))
  (dk-have! (list '< 0 rr) (lambda () (dk-ineq! (list '<= 0 m))))
  (dk-have! (list '< m rr) (lambda () (dk-ineq!)))
  (cie-in-ball! 'z 0 rr)
  (cie-center-in-ball! 0 rr)
  (dk-have! (list '<= 0 rr) (lambda () (dk-ineq! (list '< 0 rr))))
  (dk-have! (list 'NOT (list '= 0 rr)) (lambda () (fact 'rr-zero-in) (dk-split-all! (list (dk-cite! 'pw-lt-ne 0 rr))) (ass)))
  (cie-and! (list 'IN rr 'RR) (cie-and! (list '<= 0 rr) (list 'NOT (list '= 0 rr))))
  (dk-have! '(IN 0 (PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
  (let* ((iff (dk-cite! 'cc-ms-open-iff bl)))
    (dk-cite! 'ball-is-open 'CC-MS 0 rr)
    (dk-have! (list 'IS-OPEN cie-nfm bl) (lambda () (cie-only-prop! iff (list 'IS-OPEN 'CC-MS bl)))))
  (dk-have! (list 'SUBSET bl 'CC) (lambda () (let ((x (subset-by-element!))) (cie-ball-open! 0 rr x))))
  (dk-cite! 'restrict-in-fun 'f 'CC 'CC bl)
  (dk-have! (list 'FORALL 'hbz_ (list 'IMPLIES (list 'IN 'hbz_ bl) (list 'IS-DIFF-ON 'CC-NORMED-FIELD bl h 'hbz_ 0)))
    (lambda ()
      (let ((x (dk-di-var!)))
        (fact 'subset-mem-fwd bl 'CC x)
        (dk-apply! d0 x)
        (dk-cite! 'diff-on-shrink 'CC-NORMED-FIELD 'CC 'f x 0 bl)
        (ass))))
  (let* ((cz (dk-cite! 'alg-zero-deriv-ball 0 rr h)))
    (dk-apply! cz 'z)
    (dk-cite! 'restrict-apply 'f bl 'z)
    (dk-cite! 'restrict-apply 'f bl 0)
    (fact 'fun-apply-type-c 'f 'CC 'CC 'z)
    (fact 'fun-apply-type-c 'f 'CC 'CC 0)
    (subst (list '== '(f z) (list h 'z)))
    (subst (list '== '(f 0) (list h 0)))
    (ass)))
(qed 'liouville)
;;; (E12)-(E14) THE FUNDAMENTAL THEOREM OF ALGEBRA (the notes' 1.5) for the polynomial
;;; function z |-> sum_{k <= n} p(k) z^k with p(n) /= 0, n >= 1, written as the partial sum
;;; CC-SERIES-PARTIAL-SUM(k |-> p(k) z^k, n + 1) of a coefficient function p in FUN(NN, CC).
(define (cie-pterm w) (list 'VNB-LAMBDA 'k 'NN (list '* '(ciep_ k) (list 'power w 'k))))
(define (cie-poly w n) (list 'CC-SERIES-PARTIAL-SUM (cie-pterm w) n))
(define cie-A '(VNB-LAMBDA k NN (magnitude (ciep_ k))))
(define (cie-F n) (list 'VNB-LAMBDA 'cifw_ 'CC (cie-poly 'cifw_ n)))
(define (cie-cc-open!)
  (fact 'cc-is-metric-space)
  (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
  (dk-cite! 'carrier-is-open 'CC-MS)
  (dk-have! '(IS-OPEN CC-MS CC) (lambda () (subst '(= CC (PTS CC-MS))) (ass)))
  (fact 'cc-is-set))
;;; w in CC, j in NN, p in FUN(NN, CC): T_w typed, T_w(j) and the partial sums typed
(define (cie-pterm-typ! w)
  (cie-lam-typ! (cie-pterm w) 'NN (lambda (k) (fact 'fun-apply-type-c 'ciep_ 'NN 'CC k))))
(define (cie-ps-typ! w n)
  (cie-pterm-typ! w)
  (cie-nn! n)
  (dk-cite! 'cc-series-partial-sum-in-cc n (cie-pterm w)))
;;; (cie-ps-succ! w n): PS(T_w, succ n) == PS(T_w, n) + p(n) w^n, landed
(define (cie-ps-succ! w n)
  (let* ((tn (list (cie-pterm w) n)) (v (list '* (list 'ciep_ n) (list 'power w n))))
    (cie-ps-typ! w n)
    (fact 'fun-apply-type-c 'ciep_ 'NN 'CC n)
    (cie-cc! v)
    (dk-have! (list 'IN tn 'CC) (lambda () (cie-steps cie-lam-b-if! ass)))
    (let* ((e (dk-cite! 'cc-series-partial-sum-succ (cie-pterm w) n)))
      (dk-have! (list '== (list 'CC-SERIES-PARTIAL-SUM (cie-pterm w) (list 'succ n)) (list '+ (cie-poly w n) v))
        (lambda () (subst e) (dk-lam-b!) (qrfl))))))

;;; (E12) a polynomial function is entire
(sp (make-wff (list 'FORALL 'ciej_ (list 'IMPLIES '(IN ciej_ NN)
  (list 'FORALL 'ciep_ (list 'IMPLIES '(IN ciep_ (FUN NN CC)) (list 'HOLOMORPHIC-ON 'CC (cie-F 'ciej_))))))))
(define cie-ph-br (use-induction))
(dk-focus! (cdr (assq 'base cie-ph-br)))
(dk-peel!)
(cie-cc-open!)
(fact 'cc-zero-in)
(dk-cite! 'holomorphic-const 'CC 0)
(cie-lam-typ! (cie-F 0) 'CC (lambda (w) (cie-ps-typ! w 0)))
(dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES '(IN hbx_ CC) (list '== (list (cie-F 0) 'hbx_) '((VNB-LAMBDA hbx_ CC 0) hbx_))))
  (lambda ()
    (let* ((w (dk-di-var!)))
      (dk-lam-b!)
      (cie-subst-qrfl! (dk-cite! 'cc-series-partial-sum-zero (cie-pterm w))))))
(dk-cite! 'holomorphic-transfer-ptwise-eq 'CC (cie-F 0) '(VNB-LAMBDA hbx_ CC 0))
(if (dk-asm? (dk-goal)) (ass))
(dk-focus! (cdr (assq 'step cie-ph-br)))
(define cie-ph-n (cdr (assq 'var cie-ph-br)))
(define cie-ph-ih (cdr (assq 'ih cie-ph-br)))
(dk-peel!)
(let* ((n cie-ph-n)
       (pw (list 'VNB-LAMBDA 'cifx_ 'CC (list 'power 'cifx_ n)))
       (cn (list 'VNB-LAMBDA 'hbx_ 'CC (list 'ciep_ n)))
       (g (list 'VNB-LAMBDA 'cifx_ 'CC (list '* (list 'ciep_ n) (list 'power 'cifx_ n)))))
  (cie-cc-open!)
  (dk-apply! cie-ph-ih 'ciep_)
  (fact 'fun-apply-type-c 'ciep_ 'NN 'CC n)
  (cie-lam-typ! pw 'CC (lambda (w) #t))
  (cie-lam-typ! g 'CC (lambda (w) #t))
  (cie-lam-typ! (cie-F (list 'succ n)) 'CC (lambda (w) (cie-ps-typ! w (list 'succ n))))
  (dk-have! (list 'FORALL 'hbz_ (list 'IMPLIES '(IN hbz_ CC) (list '== (list pw 'hbz_) (list 'power 'hbz_ n))))
    (lambda () (dk-di-var!) (dk-lam-b!) (qrfl)))
  (dk-cite! 'holomorphic-power n 'CC pw)
  (dk-cite! 'holomorphic-const 'CC (list 'ciep_ n))
  (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES '(IN hbx_ CC) (list '== (list g 'hbx_) (list '* (list cn 'hbx_) (list pw 'hbx_)))))
    (lambda () (dk-di-var!) (dk-lam-b!) (qrfl)))
  (dk-cite! 'holomorphic-product 'CC cn pw g)
  (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES '(IN hbx_ CC)
              (list '== (list (cie-F (list 'succ n)) 'hbx_) (list '+ (list (cie-F n) 'hbx_) (list g 'hbx_)))))
    (lambda ()
      (let* ((w (dk-di-var!)))
        (cie-ps-succ! w n)
        (dk-lam-b!)
        (cie-subst-qrfl! (list '== (cie-poly w (list 'succ n)) (list '+ (cie-poly w n) (list '* (list 'ciep_ n) (list 'power w n))))))))
  (dk-cite! 'holomorphic-sum 'CC (cie-F n) g (cie-F (list 'succ n)))
  (if (dk-asm? (dk-goal)) (ass)))
(qed 'polynomial-holomorphic)

;;; (E13) the growth bound: for |w| >= 1, |sum_{k <= j} p(k) w^k| <= (sum_{k <= j} |p(k)|) |w|^j
(define (cie-SA n) (list 'CC-SERIES-PARTIAL-SUM cie-A n))
(define (cie-gb-body j)
  (list 'AND (list 'IN (cie-SA (list 'succ j)) 'RR)
    (list 'AND (list '<= 0 (cie-SA (list 'succ j)))
      (list 'FORALL 'ciew_ (list 'IMPLIES '(IN ciew_ CC) (list 'IMPLIES '(<= 1 (magnitude ciew_))
        (list '<= (list 'magnitude (cie-poly 'ciew_ (list 'succ j)))
                  (list '* (cie-SA (list 'succ j)) (list 'power '(magnitude ciew_) j)))))))))
(define (cie-A-typ!)
  (dk-have! (list 'IN cie-A '(FUN NN RR))
    (lambda () (dk-lam-type! (lambda () (let* ((k (dk-di-var!)) (leaf (proof-state-focus *ps*)))
                                          (fact 'fun-apply-type-c 'ciep_ 'NN 'CC k)
                                          (cie-lam-b-if!)
                                          (cie-rr! (cadr (dk-goal)))
                                          (if (not (sequent-node-grounded? leaf)) (ass)))))))
  (dk-have! (list 'IN cie-A '(FUN NN CC))
    (lambda () (dk-lam-type! (lambda () (let* ((k (dk-di-var!)) (leaf (proof-state-focus *ps*)))
                                          (fact 'fun-apply-type-c 'ciep_ 'NN 'CC k)
                                          (cie-lam-b-if!)
                                          (cie-cc! (cadr (dk-goal)))
                                          (if (not (sequent-node-grounded? leaf)) (ass))))))))
;;; SA(succ n) == SA(n) + |p(n)|
(define (cie-sa-succ! n)
  (cie-nn! n)
  (dk-cite! 'cc-series-partial-sum-in-cc n cie-A)
  (fact 'fun-apply-type-c 'ciep_ 'NN 'CC n)
  (cie-cc! (list 'magnitude (list 'ciep_ n)))
  (dk-have! (list 'IN (list cie-A n) 'CC) (lambda () (cie-steps cie-lam-b-if! ass)))
  (let* ((e (dk-cite! 'cc-series-partial-sum-succ cie-A n)))
    (dk-have! (list '== (cie-SA (list 'succ n)) (list '+ (cie-SA n) (list 'magnitude (list 'ciep_ n))))
      (lambda () (subst e) (dk-lam-b!) (qrfl)))))
(sp (make-wff (list 'FORALL 'ciej_ (list 'IMPLIES '(IN ciej_ NN)
  (list 'FORALL 'ciep_ (list 'IMPLIES '(IN ciep_ (FUN NN CC)) (cie-gb-body 'ciej_)))))))
(define cie-gb-br (use-induction))
(dk-focus! (cdr (assq 'base cie-gb-br)))
(dk-peel!)
(cie-A-typ!)
(fact 'nn-zero-in)
(cie-sa-succ! 0)
(let* ((sa (cie-SA '(succ 0))) (a0 '(magnitude (ciep_ 0))))
  (dk-have! (list '= sa a0)
    (lambda () (subst (list '== sa (list '+ (cie-SA 0) a0)))
                (subst (dk-cite! 'cc-series-partial-sum-zero cie-A))
                (crs)))
  (dk-cite! 'cc-magnitude-nonneg '(ciep_ 0))
  (fact 'fun-apply-type-c 'ciep_ 'NN 'CC 0)
  (cie-rr! a0)
  (dk-conj-close!
    (lambda ()
      (let* ((g (dk-goal)))
        (cond
          ((dk-head-is? g 'IN) (cie-subst-ass! (list '= sa a0)))
          ((dk-head-is? g '<=) (cie-subst-ass! (list '= sa a0)))
          (#t
           (let* ((lk (dk-peel!))
                  (w (cadr (car (filter (dk-head? 'IN) lk))))
                  (mw (list 'magnitude w)))
             (cie-ps-succ! w 0)
             (subst (list '== (cie-poly w '(succ 0)) (list '+ (cie-poly w 0) (list '* '(ciep_ 0) (list 'power w 0)))))
             (subst (dk-cite! 'cc-series-partial-sum-zero (cie-pterm w)))
             (subst (dk-cite! 'power-zero w))
             (cie-rr! mw)
             (fact 'rr-subset-cc mw)
             (subst (dk-cite! 'power-zero mw))
             (dk-have! (list '= (list '+ 0 (list '* '(ciep_ 0) 1)) '(ciep_ 0)) (lambda () (crs)))
             (subst (list '= (list '+ 0 (list '* '(ciep_ 0) 1)) '(ciep_ 0)))
             (subst (list '= sa a0))
             (dk-ineq! (list 'IN a0 'RR)))))))))
(dk-focus! (cdr (assq 'step cie-gb-br)))
(define cie-gb-n (cdr (assq 'var cie-gb-br)))
(define cie-gb-ih (cdr (assq 'ih cie-gb-br)))
(dk-peel!)
(cie-A-typ!)
(dk-split-all! (list (dk-apply! cie-gb-ih 'ciep_)))
(let* ((n cie-gb-n) (sn (list 'succ n)) (ssn (list 'succ sn))
       (sa (cie-SA sn)) (sa2 (cie-SA ssn)) (an (list 'magnitude (list 'ciep_ sn)))
       (bnd (dk-pick (lambda (fm) (and (dk-head-is? fm 'FORALL) (dk-contains? fm 'ciew_))) "the bound at n")))
  (fact 'nn-succ-closed n)
  (cie-sa-succ! sn)
  (dk-cite! 'cc-magnitude-nonneg (list 'ciep_ sn))
  (cie-rr! an)
  (dk-have! (list 'IN sa2 'RR) (lambda () (subst (list '== sa2 (list '+ sa an))) (cie-rr! (list '+ sa an)) (ass)))
  (dk-have! (list '<= 0 sa2) (lambda () (subst (list '== sa2 (list '+ sa an))) (dk-ineq! (list '<= 0 sa) (list '<= 0 an))))
  (dk-conj-close!
    (lambda ()
      (let* ((g (dk-goal)))
        (cond
          ((dk-asm? g) (ass))
          (#t
           (let* ((lk (dk-peel!))
                  (w (cadr (car (filter (dk-head? 'IN) lk))))
                  (mw (list 'magnitude w))
                  (q (cie-poly w sn))
                  (t (list '* (list 'ciep_ sn) (list 'power w sn)))
                  (x (list 'power mw n)) (y (list 'power mw sn)))
             (dk-apply! bnd w)
             (cie-ps-succ! w sn)
             (subst (list '== (cie-poly w ssn) (list '+ q t)))
             (cie-cc! q) (cie-cc! t)
             (cie-and! (list 'IN q 'CC) (list 'IN t 'CC))
             (dk-cite! 'cc-magnitude-triangle q t)
             (fact 'fun-apply-type-c 'ciep_ 'NN 'CC sn)
             (cie-cc! (list 'power w sn))
             (cie-and! (list 'IN (list 'ciep_ sn) 'CC) (list 'IN (list 'power w sn) 'CC))
             (dk-cite! 'cc-magnitude-mul (list 'ciep_ sn) (list 'power w sn))
             (dk-cite! 'cc-magnitude-power sn w)
             (cie-rr! mw)
             (fact 'power-real-closed mw n)
             (fact 'power-real-closed mw sn)
             (fact 'rr-subset-cc mw)
             (let* ((ys (cie-pow-succ! mw n))
                    (xv (dk-name! x)) (yv (dk-name! y)))
               (dk-have! (list '= yv (list '* mw xv)) (lambda () (subst (list '= yv y)) (subst (list '= xv x)) (ass)))
               (dk-have! (list '<= 0 mw) (lambda () (dk-ineq! (list '<= 1 mw))))
               (dk-have! (list '<= 0 xv) (lambda () (subst (list '= xv x)) (dk-cite! 'rr-power-nonneg n mw) (ass)))
               (cie-and! (list 'IN mw 'RR) (list 'IN xv 'RR))
               ;; x <= y: y - x = (|w| - 1) x >= 0
               (let* ((d (list '- mw 1)))
                 (cie-rr! d)
                 (dk-have! (list '<= 0 d) (lambda () (dk-ineq! (list '<= 1 mw))))
                 (cie-and! (list 'IN d 'RR) (list 'IN xv 'RR))
                 (cie-and! (list '<= 0 d) (list '<= 0 xv))
                 (dk-cite! 'rr-leq-mul-nonneg d xv)
                 (cie-rr! (list '* d xv))
                 (dk-have! (list '= (list '* d xv) (list '- yv xv)) (lambda () (subst (list '= yv (list '* mw xv))) (crs))))
               (dk-have! (list '<= xv yv) (lambda () (dk-ineq! (list '<= 0 (list '* (list '- mw 1) xv)) (list '= (list '* (list '- mw 1) xv) (list '- yv xv)))))
               (cie-and! (list '<= 0 sa) (list '<= xv yv))
               (dk-cite! 'rr-le-scale-nonneg sa xv yv)
               (let* ((p1 (begin (cie-rr! (list '* sa xv)) (dk-name! (list '* sa xv))))
                      (p2 (begin (cie-rr! (list '* sa yv)) (dk-name! (list '* sa yv))))
                      (p3 (begin (cie-rr! (list '* an yv)) (dk-name! (list '* an yv))))
                      (mq (list 'magnitude q)) (mt (list 'magnitude t)))
                 (cie-rr! mq) (cie-rr! mt)
                 (dk-have! (list '<= mq p1) (lambda () (subst (list '= p1 (list '* sa xv))) (subst (list '= xv x)) (ass)))
                 (dk-have! (list '<= p1 p2) (lambda () (subst (list '= p1 (list '* sa xv))) (subst (list '= p2 (list '* sa yv))) (ass)))
                 (dk-have! (list '= mt p3)
                   (lambda () (subst (list '= p3 (list '* an yv))) (subst (list '= yv y))
                              (subst (list '= mt (list '* an (list 'magnitude (list 'power w sn)))))
                              (subst (list '= (list 'magnitude (list 'power w sn)) y)) (rfl)))
                 (dk-have! (list '= (list '* sa2 y) (list '+ p2 p3))
                   (lambda () (subst (list '== sa2 (list '+ sa an))) (subst (list '= y yv))
                              (subst (list '= p2 (list '* sa yv))) (subst (list '= p3 (list '* an yv))) (crs)))
                 (cie-rr! (list 'magnitude (list '+ q t)))
                 (cie-rr! (list '* sa2 y))
                 (dk-ineq! (list '<= (list 'magnitude (list '+ q t)) (list '+ mq mt))
                           (list '<= mq p1) (list '<= p1 p2) (list '= mt p3)
                           (list '= (list '* sa2 y) (list '+ p2 p3))))))))))))
(qed 'polynomial-growth-bound)
;;; (E14) THE FUNDAMENTAL THEOREM OF ALGEBRA.  A polynomial function of degree n >= 1 with
;;; no zero would have an entire reciprocal g = 1/p; on the circle |w| = R (R large) the
;;; growth bound gives |g| <= K / R, so |g(0)| <= K / R for every large R
;;; (cauchy-estimate-center), g(0) = 0, against g(0) p(0) = 1.  (The notes route it through
;;; Liouville; the centre bound is the same estimate one step shorter.)
(define cie-fta-n '(succ ciem_))
(define cie-fta-top '(succ (succ ciem_)))
(define cie-fta-goal (list 'FORSOME 'z (list 'AND '(IN z CC) (list '= (cie-poly 'z cie-fta-top) 0))))
(sp (make-wff (list 'FORALL 'ciep_ (list 'IMPLIES '(IN ciep_ (FUN NN CC))
  (list 'FORALL 'ciem_ (list 'IMPLIES '(IN ciem_ NN) (list 'IMPLIES (list 'NOT (list '= (list 'ciep_ cie-fta-n) 0))
    cie-fta-goal)))))))
(dk-peel!)
(pbc)
(define cie-fta-nz
  (list 'FORALL 'cifz_ (list 'IMPLIES '(IN cifz_ CC) (list 'NOT (list '= (cie-poly 'cifz_ cie-fta-top) 0)))))
(dk-have! cie-fta-nz
  (lambda ()
    (let* ((z (dk-di-var!)))
      (di)
      (dk-have! cie-fta-goal (lambda () (ew z) (dk-conj-close! dk-ass!)))
      (ai (dk-ctx-form (list 'NOT cie-fta-goal))))))
(cie-cc-open!)
(fact 'nn-succ-closed 'ciem_)
(fact 'nn-succ-closed cie-fta-n)
(define cie-fta-F (cie-F cie-fta-top))
(define cie-fta-g (list 'VNB-LAMBDA 'cifv_ 'CC (list 'recip (cie-poly 'cifv_ cie-fta-top))))
(define (cie-fta-pt! v)
  ;; v in CC: P(v) typed, non-zero, its reciprocal typed
  (cie-ps-typ! v cie-fta-top)
  (dk-apply! (dk-ctx-form cie-fta-nz) v)
  (cie-cc! (list 'recip (cie-poly v cie-fta-top))))
(dk-cite! 'polynomial-holomorphic cie-fta-top 'ciep_)
(cie-lam-typ! cie-fta-F 'CC (lambda (v) (cie-ps-typ! v cie-fta-top)))
(cie-lam-typ! cie-fta-g 'CC (lambda (v) (cie-fta-pt! v)))
(dk-have! (list 'FORALL 'cry_ (list 'IMPLIES '(IN cry_ CC) (list 'NOT (list '= (list cie-fta-F 'cry_) 0))))
  (lambda () (let* ((v (dk-di-var!)) (leaf (proof-state-focus *ps*)))
               (cie-fta-pt! v) (dk-lam-b!) (if (not (sequent-node-grounded? leaf)) (ass)))))
(dk-have! (list 'FORALL 'cry_ (list 'IMPLIES '(IN cry_ CC) (list '== (list cie-fta-g 'cry_) (list 'recip (list cie-fta-F 'cry_)))))
  (lambda () (let* ((v (dk-di-var!))) (cie-fta-pt! v) (dk-lam-b!) (qrfl))))
(dk-cite! 'holomorphic-recip-of 'CC cie-fta-F cie-fta-g)
;; |p(n)| > 0
(define cie-fta-an (list 'ciep_ cie-fta-n))
(define cie-fta-al (list 'magnitude cie-fta-an))
(fact 'fun-apply-type-c 'ciep_ 'NN 'CC cie-fta-n)
(cie-rr! cie-fta-al)
(dk-cite! 'cc-magnitude-nonneg cie-fta-an)
(let* ((iff (dk-cite! 'cc-magnitude-zero-iff cie-fta-an)))
  (dk-have! (list 'NOT (list '= 0 cie-fta-al))
    (lambda () (di) (fact 'eq-sym 0 cie-fta-al)
                (dk-have! (list '= cie-fta-an 0) (lambda () (cie-only-prop! iff (list '= cie-fta-al 0))))
                (ai (dk-ctx-form (list 'NOT (list '= cie-fta-an 0)))))))
(cie-and! (list '<= 0 cie-fta-al) (list 'NOT (list '= 0 cie-fta-al)))
(dk-cite! 'rr-le-ne-lt 0 cie-fta-al)
;; the growth bound at degree n - 1 = m
(cie-A-typ!)
(dk-split-all! (list (dk-cite! 'polynomial-growth-bound 'ciem_ 'ciep_)))
(define cie-fta-sa (cie-SA cie-fta-n))
(define cie-fta-gb (dk-pick (lambda (fm) (and (dk-head-is? fm 'FORALL) (dk-contains? fm 'ciew_))) "the growth bound"))
(fact 'rr-pos-ne-zero cie-fta-al)
(cie-and! (list 'IN cie-fta-al 'RR) (list 'NOT (list '= cie-fta-al 0)))
(dk-cite! 'rr-recip-closed cie-fta-al)
(dk-cite! 'rr-recip-inverse cie-fta-al)
(dk-cite! 'rr-recip-pos cie-fta-al)
(define cie-fta-ra (dk-name! (list 'recip cie-fta-al)))
(dk-have! (list '= (list '* cie-fta-al cie-fta-ra) 1) (lambda () (subst (list '= cie-fta-ra (list 'recip cie-fta-al))) (ass)))
(dk-have! (list '< 0 cie-fta-ra) (lambda () (subst (list '= cie-fta-ra (list 'recip cie-fta-al))) (ass)))
(define cie-fta-k (list '* 2 cie-fta-ra))
(cie-rr! cie-fta-k)
(dk-have! (list '<= 0 cie-fta-k) (lambda () (dk-ineq! (list '< 0 cie-fta-ra))))
(cie-and! (list 'IN cie-fta-sa 'RR) (list 'IN cie-fta-ra 'RR))
(dk-have! (list '<= 0 cie-fta-ra) (lambda () (dk-ineq! (list '< 0 cie-fta-ra))))
(cie-and! (list '<= 0 cie-fta-sa) (list '<= 0 cie-fta-ra))
(dk-cite! 'rr-leq-mul-nonneg cie-fta-sa cie-fta-ra)
(define cie-fta-sr (begin (cie-rr! (list '* cie-fta-sa cie-fta-ra)) (dk-name! (list '* cie-fta-sa cie-fta-ra))))
(dk-have! (list '<= 0 cie-fta-sr) (lambda () (subst (list '= cie-fta-sr (list '* cie-fta-sa cie-fta-ra))) (ass)))
(define cie-fta-r0 (list '+ 1 (list '* 2 cie-fta-sr)))
(cie-rr! cie-fta-r0)
(dk-have! (list '<= 0 cie-fta-r0) (lambda () (dk-ineq! (list '<= 0 cie-fta-sr))))
;; on a circle |w| = R, R > R0: |g(w)| <= K / R
(define (cie-fta-circle-bound! rv)
  ;; rv in RR, R0 < rv in context
  (let* ((tr (list 'TRACE (list 'CIRCLE-PATH 0 rv) 0 cie-tp))
         (rr (list 'recip rv)))
    (dk-have! (list '< 0 rv) (lambda () (dk-ineq! (list '< cie-fta-r0 rv) (list '<= 0 cie-fta-sr))))
    (fact 'rr-pos-ne-zero rv)
    (cie-and! (list 'IN rv 'RR) (list 'NOT (list '= rv 0)))
    (dk-cite! 'rr-recip-closed rv)
    (dk-cite! 'rr-recip-inverse rv)
    (dk-have! (list '<= 0 rv) (lambda () (dk-ineq! (list '< 0 rv))))
    (cie-rr! rr)
    (cie-rr! (list '* cie-fta-k rr))
    (dk-cite! 'circle-is-road 0 rv)
    (fact 'is-road-is-path (list 'CIRCLE-PATH 0 rv) (list 'CIRCLE-DERIV 0 rv) 0 cie-tp)
    (fact 'is-path-in-fun (list 'CIRCLE-PATH 0 rv) 0 cie-tp)
    (dk-cite! 'trace-subset-cc (list 'CIRCLE-PATH 0 rv) 0 cie-tp)
    (dk-have! (list 'FORALL 'ciey_ (list 'IMPLIES (list 'IN 'ciey_ tr)
                (list '<= (list 'magnitude (list cie-fta-g 'ciey_)) (list '* cie-fta-k rr))))
      (lambda ()
        (let* ((y (dk-di-var!))
               (rho (list 'magnitude y))
               (q (cie-poly y cie-fta-n))
               (top (list '* cie-fta-an (list 'power y cie-fta-n)))
               (pp (cie-poly y cie-fta-top)))
          (fact 'subset-mem-fwd tr 'CC y)
          (cie-fta-pt! y)
          (dk-lam-b!)
          ;; |y| = R
          (dk-cite! 'circle-trace-magnitude 0 rv y)
          (cie-cc! (list '- y 0))
          (dk-have! (list '= (list '- y 0) y) (lambda () (crs)))
          (cie-rr! rho)
          (cie-rr! (list 'magnitude (list '- y 0)))
          (dk-congr! (list '= (list '- y 0) y) (lambda (w) (list 'magnitude w)))
          (dk-have! (list '= rho rv) (lambda () (dk-ineq! (list '= (list 'magnitude (list '- y 0)) rv) (list '= (list 'magnitude (list '- y 0)) rho))))
          (dk-have! (list '<= 1 rho) (lambda () (dk-ineq! (list '= rho rv) (list '< cie-fta-r0 rv) (list '<= 0 cie-fta-sr))))
          (dk-apply! cie-fta-gb y)
          ;; P = Q + top
          (cie-ps-succ! y cie-fta-n)
          (cie-cc! q) (cie-cc! top) (cie-cc! pp)
          (cie-cc! (list '- q))
          (dk-have! (list '= top (list '+ pp (list '- q)))
            (lambda () (subst (list '== pp (list '+ q top))) (crs)))
          (cie-and! (list 'IN pp 'CC) (list 'IN (list '- q) 'CC))
          (dk-cite! 'cc-magnitude-triangle pp (list '- q))
          (dk-cite! 'cc-magnitude-neg q)
          (cie-and! (list 'IN cie-fta-an 'CC) (list 'IN (list 'power y cie-fta-n) 'CC))
          (dk-cite! 'cc-magnitude-mul cie-fta-an (list 'power y cie-fta-n))
          (dk-cite! 'cc-magnitude-power cie-fta-n y)
          (fact 'power-real-closed rho 'ciem_)
          (fact 'rr-subset-cc rho)
          (cie-pow-succ! rho 'ciem_)
          (let* ((x (list 'power rho 'ciem_))
                 (mp (list 'magnitude pp)) (mq (list 'magnitude q)) (mt (list 'magnitude top))
                 (xv (dk-name! x)))
            (cie-rr! mp) (cie-rr! mq) (cie-rr! mt) (cie-rr! (list 'magnitude (list '- q)))
            (cie-rr! (list 'magnitude (list '+ pp (list '- q))))
            ;; X >= 1
            (fact 'rr-one-in)
            (dk-have! '(<= 0 1) (lambda () (dk-ineq!)))
            (dk-cite! 'rr-power-mono-base 'ciem_ 1 rho)
            (dk-cite! 'rr-power-one 'ciem_)
            (dk-have! (list '<= 1 xv) (lambda () (subst (list '= xv x)) (subst (list '= 1 (list 'power 1 'ciem_))) (ass)))
            (let* ((u (begin (cie-rr! (list '* cie-fta-al rho)) (dk-name! (list '* cie-fta-al rho))))
                   (ux (begin (cie-rr! (list '* u xv)) (dk-name! (list '* u xv))))
                   (sx (begin (cie-rr! (list '* cie-fta-sa xv)) (dk-name! (list '* cie-fta-sa xv)))))
              ;; |top| = U X, |Q| <= SA X
              (dk-have! (list '= mt ux)
                (lambda ()
                  (subst (list '= mt (list '* cie-fta-al (list 'magnitude (list 'power y cie-fta-n)))))
                  (subst (list '= (list 'magnitude (list 'power y cie-fta-n)) (list 'power rho cie-fta-n)))
                  (subst (list '= (list 'power rho cie-fta-n) (list '* rho x)))
                  (subst (list '= x xv))
                  (subst (list '= ux (list '* u xv)))
                  (subst (list '= u (list '* cie-fta-al rho)))
                  (crs)))
              (dk-have! (list '<= mq sx)
                (lambda () (subst (list '= sx (list '* cie-fta-sa xv))) (subst (list '= xv x)) (ass)))
              ;; U >= 2 SA
              (dk-have! (list '<= cie-fta-r0 rho) (lambda () (dk-ineq! (list '= rho rv) (list '< cie-fta-r0 rv))))
              (cie-and! (list '<= 0 cie-fta-al) (list '<= cie-fta-r0 rho))
              (dk-cite! 'rr-le-scale-nonneg cie-fta-al cie-fta-r0 rho)
              (cie-rr! (list '* cie-fta-al cie-fta-r0))
              (dk-have! (list '= (list '* cie-fta-al cie-fta-r0) (list '+ cie-fta-al (list '* 2 cie-fta-sa)))
                (lambda ()
                  (subst (list '= cie-fta-sr (list '* cie-fta-sa cie-fta-ra)))
                  (let* ((e (list '= (list '* cie-fta-al (list '+ 1 (list '* 2 (list '* cie-fta-sa cie-fta-ra))))
                                  (list '+ cie-fta-al (list '* (list '* 2 cie-fta-sa) (list '* cie-fta-al cie-fta-ra))))))
                    (dk-have! e (lambda () (crs)))
                    (subst e)
                    (subst (list '= (list '* cie-fta-al cie-fta-ra) 1))
                    (crs))))
              (dk-have! (list '<= (list '* 2 cie-fta-sa) u)
                (lambda () (dk-ineq! (list '<= (list '* cie-fta-al cie-fta-r0) (list '* cie-fta-al rho))
                                     (list '= (list '* cie-fta-al cie-fta-r0) (list '+ cie-fta-al (list '* 2 cie-fta-sa)))
                                     (list '= u (list '* cie-fta-al rho)) (list '<= 0 cie-fta-al))))
              ;; (U - SA) X >= U - SA
              (let* ((d (list '- u cie-fta-sa)))
                (cie-rr! d)
                (dk-have! (list '<= 0 d) (lambda () (dk-ineq! (list '<= (list '* 2 cie-fta-sa) u) (list '<= 0 cie-fta-sa))))
                (cie-and! (list '<= 0 d) (list '<= 1 xv))
                (dk-cite! 'rr-le-scale-nonneg d 1 xv)
                (let* ((dx (begin (cie-rr! (list '* d xv)) (dk-name! (list '* d xv)))))
                  (dk-have! (list '= dx (list '- ux sx))
                    (lambda () (subst (list '= dx (list '* d xv))) (subst (list '= ux (list '* u xv)))
                                (subst (list '= sx (list '* cie-fta-sa xv))) (crs)))
                  (dk-have! (list '<= d dx)
                    (lambda () (dk-ineq! (list '<= (list '* d 1) (list '* d xv)) (list '= dx (list '* d xv)))))
                  ;; |P| >= U/2
                  (dk-have! (list '<= mt (list '+ mp (list 'magnitude (list '- q))))
                    (lambda () (subst (list '= top (list '+ pp (list '- q)))) (ass)))
                  (dk-have! (list '<= (list '* 1/2 u) mp)
                    (lambda () (dk-ineq! (list '<= mt (list '+ mp (list 'magnitude (list '- q))))
                                         (list '= (list 'magnitude (list '- q)) mq)
                                         (list '= mt ux) (list '<= mq sx)
                                         (list '= dx (list '- ux sx)) (list '<= d dx)
                                         (list '<= (list '* 2 cie-fta-sa) u))))))
              ;; 1/|P| <= 1/(U/2) = K / R
              (let* ((h (list '* 1/2 u)))
                (cie-rr! h)
                (dk-have! (list '< 0 rho) (lambda () (dk-ineq! (list '= rho rv) (list '< 0 rv))))
                (dk-have! (list '< 0 u)
                  (lambda () (cie-steps (lambda () (subst (list '= u (list '* cie-fta-al rho))))
                                        (lambda () (dk-cite! 'rr-mul-pos cie-fta-al rho))
                                        ass)))
                (dk-have! (list '< 0 h) (lambda () (dk-ineq! (list '< 0 u))))
                (fact 'cc-magnitude-zero-iff pp)
                (dk-cite! 'aif-magnitude-recip pp)
                (subst (list '= (list 'magnitude (list 'recip pp)) (list 'recip mp)))
                (dk-cite! 'rr-recip-antitone h mp)
                (cie-rr! rr)
                (cie-rr! (list '* cie-fta-k rr))
                (dk-have! (list '= 1 (list '* h (list '* cie-fta-k rr)))
                  (lambda ()
                    (subst (list '= u (list '* cie-fta-al rho)))
                    (subst (list '= rho rv))
                    (let* ((e (list '= (list '* (list '* 1/2 (list '* cie-fta-al rv)) (list '* (list '* 2 cie-fta-ra) rr))
                                    (list '* (list '* cie-fta-al cie-fta-ra) (list '* rv rr)))))
                      (dk-have! e (lambda () (crs)))
                      (subst e)
                      (subst (list '= (list '* cie-fta-al cie-fta-ra) 1))
                      (subst (list '= (list '* rv rr) 1))
                      (crs))))
                (fact 'rr-pos-ne-zero h)
                (dk-cite! 'rr-recip-solve h 1 (list '* cie-fta-k rr))
                (cie-rr! (list 'recip h))
                (dk-have! (list '< 0 mp) (lambda () (dk-ineq! (list '< 0 h) (list '<= h mp))))
                (cie-rr! (list 'recip mp))
                (dk-ineq! (list '<= (list 'recip mp) (list 'recip h))
                          (list '= (list '* cie-fta-k rr) (list '* (list 'recip h) 1)))))))))
    ;; the centre bound
    (let* ((s (list '+ rv 1)))
      (cie-rr! s)
      (dk-have! (list '< 0 s) (lambda () (dk-ineq! (list '< 0 rv))))
      (dk-have! (list '< rv s) (lambda () (dk-ineq!)))
      (dk-have! (list 'SUBSET (list 'BALL 'CC-MS 0 s) 'CC)
        (lambda () (let* ((x (subset-by-element!))) (cie-ball-open! 0 s x))))
      (dk-cite! 'cauchy-estimate-center 'CC cie-fta-g 0 s rv (list '* cie-fta-k rr)))))
(fact 'cc-zero-in)
(cie-fta-pt! 0)
(define cie-fta-m0 (list 'magnitude (list cie-fta-g 0)))
(dk-have! (list 'IN (list cie-fta-g 0) 'CC)
  (lambda () (let ((leaf (proof-state-focus *ps*))) (dk-lam-b!) (if (not (sequent-node-grounded? leaf)) (ass)))))
(cie-rr! cie-fta-m0)
(dk-cite! 'cc-magnitude-nonneg (list cie-fta-g 0))
(dk-have! (list 'FORALL 'cieq_ (list 'IMPLIES '(IN cieq_ RR) (list 'IMPLIES (list '< cie-fta-r0 'cieq_)
            (list '<= cie-fta-m0 (list '* cie-fta-k '(recip cieq_))))))
  (lambda ()
    (let* ((lk (dk-peel!))
           (leaf (proof-state-focus *ps*))
           (rv (cadr (car (filter (dk-head? 'IN) lk)))))
      (cie-fta-circle-bound! rv)
      (if (not (sequent-node-grounded? leaf)) (ass)))))
(dk-cite! 'cie-squeeze cie-fta-m0 cie-fta-k cie-fta-r0)
(dk-have! (list '= cie-fta-m0 0) (lambda () (dk-ineq! (list '<= cie-fta-m0 0) (list '<= 0 cie-fta-m0))))
(let* ((g0 (list cie-fta-g 0)) (p0 (cie-poly 0 cie-fta-top))
       (iff (dk-cite! 'cc-magnitude-zero-iff g0)))
  (dk-have! (list '= g0 0) (lambda () (cie-only-prop! iff (list '= cie-fta-m0 0))))
  (cie-and! (list 'IN p0 'CC) (list 'NOT (list '= p0 0)))
  (dk-cite! 'cc-recip-inverse p0)
  (dk-have! (list '== g0 (list 'recip p0))
    (lambda () (let ((leaf (proof-state-focus *ps*))) (dk-lam-b!) (if (not (sequent-node-grounded? leaf)) (qrfl)))))
  (dk-have! (list '= (list 'recip p0) 0) (lambda () (cie-subst-ass! (list '== (list 'recip p0) g0))))
  (dk-have! '(= 1 0)
    (lambda ()
      (subst (list '= 1 (list '* p0 (list 'recip p0))))
      (subst (list '= (list 'recip p0) 0))
      (crs)))
  (dk-absurd! '(= 1 0)))
(qed 'fundamental-theorem-of-algebra)
