;;; cc-exp-surjective.scm -- PROPOSITION 2.19 COMPLETED (exp is a bijection of
;;; each strip onto its image) AND THE BRIDGE cc-exp|RR = r-exp.
;;; Batch 34, 2026-09-26.  exp, cos, sin: theorem-library/cc-exp.scm (31-A);
;;; PI and the injectivity half of 2.19: theorem-library/cc-exp-kernel.scm (31-B).
;;;
;;; THE SOURCE.  ~/docs/complex-analysis.pdf, 2.3.3.1, Prop 2.19 and its proof
;;; (scratchpad/triage/ca.txt lines 1464-1480): "The mapping exp is a bijection
;;; S = {z : -pi <= Im z < pi} -> C \ {0}.  It is a bijection
;;; S' = {z : -pi < Im z < pi} -> C \ (-inf, 0]."
;;;
;;; THE HEADLINES, in proof order.
;;;   (1) cc-exp-real-continuous-rr   t |-> exp t is in FUN(RR, RR), continuous
;;;                                   at every real point (rr-ms)
;;;   (R) cc-diff-on-restrict-rr      F differentiable on CC at the real a with
;;;                                   real derivative L, G in FUN(RR, RR) equal
;;;                                   to F on RR  ==>  is-diff-at(G, a, L)
;;;       cc-exp-real-deriv           is-diff-at(t |-> exp t, t, exp t)
;;;   (8) cxs-log-exp-deriv           t |-> log(exp t) - t has derivative 0
;;;       cc-exp-real-is-r-exp        THE BRIDGE: exp t = r-exp(t), t in RR
;;;   (3) cc-exp-real-surjective-pos  r > 0  ==>  r = exp s for a real s
;;;   (4) cc-circle-arg               a^2 + b^2 = 1  ==>  (a, b) = (cos th,
;;;                                   sin th), -pi <= th < pi
;;;   (5) cc-polar-form               w /= 0  ==>  w = r exp(i th), r > 0,
;;;                                   -pi <= th < pi
;;;   (6) cc-exp-surjective-strip     w /= 0  ==>  w = exp z, -pi <= Im z < pi
;;;       cc-exp-bijection-strip      PROP 2.19 (first assertion), as a member
;;;                                   of BIJECTION(S, CC \ {0})
;;;   (7) cc-exp-open-strip-avoids-negatives   -pi < Im z < pi  ==>  exp z is
;;;                                   not in (-inf, 0]
;;;       cc-exp-open-strip-onto      w not in (-inf, 0]  ==>  w = exp z,
;;;                                   -pi < Im z < pi
;;;       cc-exp-bijection-open-strip PROP 2.19 (second assertion), as a member
;;;                                   of BIJECTION(S', CC \ (-inf, 0])
;;;
;;; THE ROUTES.
;;;   * The bridge by uniqueness of the logarithm, not of y' = y: the real
;;;     derivative of exp comes from exp' = exp on CC through (R) (the
;;;     Caratheodory factor of a function real on RR is real on RR: phi(v) =
;;;     (G(v) - G(a)) / (v - a) off a); then deriv-chain with log-deriv and
;;;     deriv-difference give (log o exp - id)' = exp^-1 exp - 1 = 0,
;;;     deriv-zero-implies-constant on [min(0,t), max(0,t)], log 1 = 0, and
;;;     r-exp-char turns log(exp t) = t into r-exp(t) = exp(t).
;;;   * (3) through the bridge (s = log r, r-exp-log), which is shorter than the
;;;     IVT route: no growth estimate for exp on RR is needed.
;;;   * (4) the IVT for -cos on [0, pi] (-cos 0 = -1 <= -a <= 1 = -cos pi), then
;;;     (sin th0 - b)(sin th0 + b) = 0; the point th0 = pi goes to -pi.
;;;   * (7) the notes' argument through injectivity: exp z = -r' (r' > 0) =
;;;     exp(s' - pi i) with s' - pi i in S, so z = s' - pi i.
;;;
;;; NOTHING asserted: no support, stamp, axiom or definition.  Helper prefix
;;; cxs-; theorem binders cxs..._ (and those of cited theorems where an
;;; instance must match).  LOAD WINDOW: lo = theorem-library/cc-exp-kernel
;;; (PI, cos/sin values, injectivity); r-exp, log, chain-rule, ivt-proof,
;;; deriv-constant-proof load far earlier; hi: none.  Oracles: crs, ineq,
;;; arith (sos enters through citations).  Tactics: none of the late ones (no
;;; contra, prep, ineq-supply).
;;; ---- helpers (copied from cc-exp-kernel.scm, prefix cek- -> cxs-; a driver
;;; helper is local to its file; LOG, R-EXP, RECIP-STAR, CC-EXP, CC-COS, CC-SIN,
;;; PI cases added to cxs-rr-typ!) ----
(define (cxs-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (cxs-and! a b)
  (let ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! (lambda () (ass))))))
    f))
(define (cxs-nn-typ! t)
  (let ((typ (list 'IN t 'NN)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'nn-zero-in) typ)
          ((eqv? t 1) (fact 'nn-one-in) typ)
          ((and (exact-nonnegative-integer? t)) (dk-have! typ (lambda () (arith))) typ)
          ((cxs-op? t 'succ 2) (cxs-nn-typ! (cadr t)) (fact 'nn-succ-closed (cadr t)) typ)
          ((or (cxs-op? t '+ 3) (cxs-op? t '* 3))
           (cxs-nn-typ! (cadr t)) (cxs-nn-typ! (caddr t))
           (cxs-and! (list 'IN (cadr t) 'NN) (list 'IN (caddr t) 'NN))
           (fact (if (eq? (car t) '+) 'nn-add-closed 'nn-mul-closed) (cadr t) (caddr t)) typ)
          (#t (error "cxs-nn-typ!: cannot type" (expression->string t))))))
(define (cxs-rr-typ! t)
  (let ((typ (list 'IN t 'RR)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'rr-zero-in) typ)
          ((eqv? t 1) (fact 'rr-one-in) typ)
          ((and (number? t) (exact-rational? t)) (dk-have! typ (lambda () (arith))) typ)
          ((and (pair? t) (cxs-ground? t)) (dk-have! typ (lambda () (arith))) typ)
          ((dk-asm? (list 'IN t 'NN)) (fact 'nn-in-rr t) typ)
          ((cxs-op? t 'FACTORIAL 2)
           (cxs-nn-typ! (cadr t))
           (dk-split-all! (list (dk-fact! 'factorial-real-pos (cadr t)))) typ)
          ((or (cxs-op? t 'succ 2) (and (cxs-op? t '+ 3) (dk-asm? (list 'IN (cadr t) 'NN))
                                         (dk-asm? (list 'IN (caddr t) 'NN))))
           (cxs-nn-typ! t) (fact 'nn-in-rr t) typ)
          ((and (cxs-op? t 'recip 2) (cxs-op? (cadr t) 'FACTORIAL 2))
           (cxs-nn-typ! (cadr (cadr t))) (fact 'recip-factorial-in-rr (cadr (cadr t))) typ)
          ((cxs-op? t 'recip 2)
           (cxs-rr-typ! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (error "cxs-rr-typ!: recip of a term not known nonzero" (expression->string t)))
           (cxs-and! (list 'IN (cadr t) 'RR) (list 'NOT (list '= (cadr t) 0)))
           (fact 'rr-recip-closed (cadr t)) typ)
          ((cxs-op? t '* 3) (cxs-rr-typ! (cadr t)) (cxs-rr-typ! (caddr t)) (fact 'rr-mul-in-rr (cadr t) (caddr t)) typ)
          ((cxs-op? t '+ 3) (cxs-rr-typ! (cadr t)) (cxs-rr-typ! (caddr t)) (fact 'rr-add-in-rr (cadr t) (caddr t)) typ)
          ((cxs-op? t '- 3) (cxs-rr-typ! (cadr t)) (cxs-rr-typ! (caddr t)) (fact 'rr-sub-in-rr (cadr t) (caddr t)) typ)
          ((cxs-op? t '- 2) (cxs-rr-typ! (cadr t)) (fact 'rr-neg-closed (cadr t)) typ)
          ((cxs-op? t 'real-part 2) (cxs-cc-typ! (cadr t)) (fact 'real-part-in-rr (cadr t)) typ)
          ((cxs-op? t 'imag-part 2) (cxs-cc-typ! (cadr t)) (fact 'imag-part-in-rr (cadr t)) typ)
          ((cxs-op? t 'power 3) (cxs-rr-typ! (cadr t)) (cxs-nn-typ! (caddr t)) (fact 'power-real-closed (cadr t) (caddr t)) typ)
          ((cxs-op? t 'magnitude 2) (cxs-cc-typ! (cadr t)) (fact 'cc-magnitude-closed (cadr t)) typ)
          ((cxs-op? t 'abs 2) (cxs-rr-typ! (cadr t)) (fact 'rr-abs-closed (cadr t)) typ)
          ((cxs-op? t 'LOG 2) (cxs-rr-typ! (cadr t)) (fact 'log-in-rr (cadr t)) typ)
          ((cxs-op? t 'R-EXP 2) (cxs-rr-typ! (cadr t)) (fact 'r-exp-in-rr (cadr t)) typ)
          ((cxs-op? t 'RECIP-STAR 2) (cxs-rr-typ! (cadr t)) (fact 'recip-star-in-rr (cadr t)) typ)
          ((cxs-op? t 'CC-EXP 2) (cxs-exp-rr! (cadr t)) typ)
          ((or (cxs-op? t 'CC-COS 2) (cxs-op? t 'CC-SIN 2))
           (cxs-rr-typ! (cadr t)) (dk-split-all! (list (dk-cite! 'cc-cos-sin-real (cadr t)))) typ)
          ((eq? t 'PI) (cxs-pi-typ!) typ)
          (#t (error "cxs-rr-typ!: cannot type" (expression->string t))))))
(define (cxs-real? t)
  (or (and (number? t) (exact-rational? t))
      (dk-asm? (list 'IN t 'RR)) (dk-asm? (list 'IN t 'NN))
      (cxs-op? t 'succ 2) (cxs-op? t 'FACTORIAL 2) (cxs-op? t 'magnitude 2) (cxs-op? t 'abs 2) (cxs-op? t 'real-part 2) (cxs-op? t 'imag-part 2)
      (and (cxs-op? t 'recip 2) (cxs-op? (cadr t) 'FACTORIAL 2))
      (and (memq (dk-head t) '(* + -)) (= (length t) 3) (cxs-real? (cadr t)) (cxs-real? (caddr t)))
      (and (cxs-op? t 'power 3) (cxs-real? (cadr t)))))
;;; a ground numeric term (numbers under + - * recip): typed by arith
(define (cxs-ground? t)
  (or (number? t)
      (and (pair? t) (memq (car t) '(+ - * recip)) (every cxs-ground? (cdr t)))))
;;; D when (IN F (FUN D CC)) is in context
(define (cxs-fun-dom f)
  (let ((hit (find-first (lambda (a) (and (cxs-op? a 'IN 3) (equal? (cadr a) f)
                                          (cxs-op? (caddr a) 'FUN 3) (eq? (caddr (caddr a)) 'CC)))
                         (dk-asms))))
    (and hit (cadr (caddr hit)))))
(define (cxs-cc-typ! t)
  (let ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((eqv? t 1) (fact 'cc-one-in) typ)
          ((eqv? t +i) (fact 'cc-i-in) typ)
          ((and (pair? t) (cxs-ground? t)) (dk-have! typ (lambda () (arith))) typ)
          ((and (number? t) (exact-rational? t)) (cxs-rr-typ! t) (fact 'rr-subset-cc t) typ)
          ((cxs-real? t) (cxs-rr-typ! t) (fact 'rr-subset-cc t) typ)
          ((and (pair? t) (= (length t) 2) (dk-asm? (list 'IN (car t) '(FUN NN CC))))
           (cxs-nn-typ! (cadr t)) (fact 'fun-apply-type-c (car t) 'NN 'CC (cadr t)) typ)
          ((and (pair? t) (= (length t) 2) (cxs-fun-dom (car t)))
           (let ((dom (cxs-fun-dom (car t))))
             (if (eq? dom 'NN) (cxs-nn-typ! (cadr t)))
             (if (eq? dom 'CC) (cxs-cc-typ! (cadr t)))
             (fact 'fun-apply-type-c (car t) dom 'CC (cadr t)) typ))
          ((cxs-op? t 'CC-EXP 2) (cxs-exp-typ! (cadr t)) typ)
          ((cxs-op? t 'CC-COS 2) (cxs-cos-typ! (cadr t)) typ)
          ((cxs-op? t 'CC-SIN 2) (cxs-sin-typ! (cadr t)) typ)
          ((and (cxs-op? t 'CC-SERIES-PARTIAL-SUM 3) (dk-asm? (list 'IN (cadr t) '(FUN NN CC))))
           (cxs-nn-typ! (caddr t)) (fact 'cc-series-partial-sum-in-cc (caddr t) (cadr t)) typ)
          ((and (cxs-op? t 'CC-SERIES-LIMIT 2) (dk-asm? (list 'CC-SERIES-CONVERGES (cadr t))))
           (fact 'cc-series-limit-in-cc (cadr t)) typ)
          ((cxs-op? t '* 3) (cxs-cc-typ! (cadr t)) (cxs-cc-typ! (caddr t))
           (cxs-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((cxs-op? t '+ 3) (cxs-cc-typ! (cadr t)) (cxs-cc-typ! (caddr t))
           (cxs-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((cxs-op? t '- 3) (cxs-cc-typ! (cadr t)) (cxs-cc-typ! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((cxs-op? t '- 2) (cxs-cc-typ! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((cxs-op? t 'conjugate 2) (cxs-cc-typ! (cadr t)) (fact 'cc-conjugate-closed (cadr t)) typ)
          ((cxs-op? t 'power 3) (cxs-cc-typ! (cadr t)) (cxs-nn-typ! (caddr t))
           (cxs-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'NN)) (fact 'power-typing-nonneg (cadr t) (caddr t)) typ)
          ((cxs-op? t 'recip 2)
           (cxs-cc-typ! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (error "cxs-cc-typ!: recip of a term not known nonzero" (expression->string t)))
           (cxs-and! (list 'IN (cadr t) 'CC) (list 'NOT (list '= (cadr t) 0)))
           (fact 'cc-recip-closed (cadr t)) typ)
          (#t (error "cxs-cc-typ!: cannot type" (expression->string t))))))

;;; (IN LAM (FUN NN COD)) for LAM = (VNB-LAMBDA v NN body): TYPER gets the
;;; eigenvariable and must land the body's typing.
(define (cxs-lam-typ! lam cod typer)
  (let ((typ (list 'IN lam (list 'FUN 'NN cod))))
    (if (not (dk-asm? typ))
        (dk-have! typ
          (lambda ()
            (dk-lam-t!)
            (let* ((j (dk-di-var!)) (leaf (proof-state-focus *ps*)))
              (typer j)
              (if (not (sequent-node-grounded? leaf)) (ass))))))
    typ))

;;; beta-reduce the focus goal; the reduct is a NEW node that becomes the focus
;;; while the worked leaf stays open, unless beta grounded it: run CLOSER then.
(define (cxs-beta! closer)
  (let ((leaf (proof-state-focus *ps*)))
    (dk-lam-b!)
    (if (not (sequent-node-grounded? leaf)) (closer))))

;;; A commutative-ring identity with opaque atoms: prove BODY over fresh complex
;;; variables VARS by crs on a lane, then instantiate it at TERMS (typed in CC
;;; first); returns the landed instance.
(define (cxs-ring-id! vars body terms)
  (let ((gen (let build ((vs vars))
               (if (null? vs) body
                   (list 'FORALL (car vs) (list 'IMPLIES (list 'IN (car vs) 'CC) (build (cdr vs))))))))
    (if (not (dk-asm? gen)) (dk-have! gen (lambda () (dk-peel!) (crs))))
    (for-each cxs-cc-typ! terms)
    (apply dk-apply! (dk-ctx-form gen) terms)))

;;; detach an implication chain: an antecedent in context by detach!, one not in
;;; context (a conjunction of context facts) by detach-with!
(define (cxs-chain! ch)
  (let loop ((c ch))
    (cond ((not (dk-head-is? c 'IMPLIES)) c)
          ((dk-asm? (cadr c))
           (let ((new (dk-landed* (lambda () (detach! c)))))
             (loop (if (pair? new) (car new) (caddr c)))))
          (#t (loop (detach-with! c (lambda () (dk-conj-close! (lambda () (ass))))))))))

;;; POS-RR c from (IN c RR) and (< 0 c) in context
(define (cxs-pos-rr! c)
  (if (not (dk-asm? (list 'POS-RR c)))
      (dk-have! (list 'POS-RR c)
        (lambda ()
          (mac-h '< (dk-ctx-form (list '< 0 c)))
          (dk-split-all!)
          (mac 'pos-rr)
          (dk-conj-close! (lambda () (ass)))))))

;;; close the focus goal from a contradiction (< 0 0) proved by dk-ineq! from PREMS
(define (cxs-absurd! . prems)
  (dk-have! '(< 0 0) (lambda () (apply dk-ineq! prems)))
  (if (not (dk-asm? '(IN 0 RR))) (fact 'rr-zero-in))
  (ai (dk-cite! 'rr-lt-irrefl 0)))

;;; ======================================================================
;;; (0) THE UNFOLD EQUATIONS.  A def-functoid unfolds in a GOAL by `mac' but not
;;; in an assumption; these theorems are what `mac-h' can name.
;;; ======================================================================
(define (cxs-ind! base-k step-k)
  (let* ((br (use-induction))
         (v (cdr (assq 'var br)))
         (ih (cdr (assq 'ih br)))
         (step (cdr (assq 'step br))))
    (dk-focus! (cdr (assq 'base br)))
    (base-k)
    (dk-focus! step)
    (step-k v ih)))
(define (cxs-pw! z k)                    ; z^(succ k) = z z^k, rewritten in the goal
  (cxs-cc-typ! z) (cxs-nn-typ! k)
  (cxs-and! (list 'IN z 'CC) (list 'IN k 'NN))
  (subst (dk-fact! 'power-succ z k)))

(define (cxs-exp-typ! z)
  (cxs-cc-typ! z)
  (if (not (dk-asm? (list 'IN (list 'CC-EXP z) 'CC)))
      (dk-split-all! (list (dk-fact! 'cc-exp-converges z)))))

(define (cxs-cos-typ! z)
  (cxs-cc-typ! z)
  (if (not (dk-asm? (list 'IN (list 'CC-COS z) 'CC))) (dk-split-all! (list (dk-fact! 'cc-cos-converges z)))))
(define (cxs-sin-typ! z)
  (cxs-cc-typ! z)
  (if (not (dk-asm? (list 'IN (list 'CC-SIN z) 'CC))) (dk-split-all! (list (dk-fact! 'cc-sin-converges z)))))
(define (cxs-conj-typ! z) (cxs-cc-typ! (list 'conjugate z)))
(define (cxs-pow2! x)                    ; (= (power x 2) (* x x)) in context
  (let ((e (list '= (list 'power x 2) (list '* x x))))
    (if (not (dk-asm? e))
        (dk-have! e
          (lambda ()
            (cxs-cc-typ! x)
            (fact 'nn-two-is-succ-succ-zero)
            (subst '(= 2 (succ (succ 0))))
            (fact 'nn-zero-in)
            (cxs-nn-typ! '(succ 0))
            (cxs-pw! x '(succ 0))
            (cxs-pw! x 0)
            (subst (dk-fact! 'power-zero x))
            (crs))))
    e))
(define (cxs-land-var landed dom)
  (let ((hit (find-first (lambda (f) (and (dk-head-is? f 'IN) (symbol? (cadr f)) (equal? (caddr f) dom))) landed)))
    (if hit (cadr hit) (error "cxs-land-var: no typing landed in" dom))))
(define (cxs-exp-rr! t)                 ; (IN (CC-EXP t) RR) and (IN (CC-EXP t) CC), t typed in RR
  (cxs-rr-typ! t) (fact 'rr-subset-cc t)
  (if (not (dk-asm? (list 'IN (list 'CC-EXP t) 'RR))) (fact 'cc-exp-real-valued t))
  (cxs-exp-typ! t))
(define (cxs-leq-total! a b)
  (cxs-rr-typ! a) (cxs-rr-typ! b)
  (cxs-and! (list 'IN a 'RR) (list 'IN b 'RR))
  (dk-fact! 'rr-leq-total a b))
(define (cxs-pi-typ!)
  (if (not (dk-asm? '(IN PI RR))) (begin (fact 'pi-pos) (dk-split-all!)))
  (fact 'rr-subset-cc 'PI))
(define (cxs-im-eq! x y)
  (let ((e (list '= (list 'imag-part x) y)) (yi (list '* y +i)))
    (if (not (dk-asm? e))
        (dk-have! e
          (lambda ()
            (cxs-rr-typ! y) (fact 'rr-subset-cc y) (cxs-cc-typ! x) (cxs-cc-typ! yi)
            (if (not (equal? x yi))
                (begin
                  (dk-have! (list '= x yi) (lambda () (crs)))
                  (subst (list '= x yi))))
            (subst (dk-fact! 'cc-im-real-mul y +i))
            (dk-have! (list '= (list 'imag-part +i) 1) (lambda () (arith)))
            (subst (list '= (list 'imag-part +i) 1))
            (crs))))
    e))

;;; ======================================================================
;;; (1) exp IS A CONTINUOUS REAL FUNCTION ON RR: t |-> exp t, as a member of
;;; FUN(RR, RR), is continuous at every real point (rr-ms).  The route of
;;; cc-cos-real-continuous: exp is continuous on CC (cc-exp-continuous), real on
;;; RR (cc-exp-real-valued), and cc-continuous-restrict-rr restricts.
;;; ======================================================================
(define cxs-expr '(VNB-LAMBDA cxsv_ RR (CC-EXP cxsv_)))
(define cxs-expl '(VNB-LAMBDA cexy_ CC (CC-EXP cexy_)))
(sp (make-wff (list 'AND (list 'IN cxs-expr '(FUN RR RR))
  (list 'FORALL 'cxsx_ (list 'IMPLIES '(IN cxsx_ RR) (list 'IS-CONTINUOUS-AT 'RR-MS 'RR-MS cxs-expr 'cxsx_))))))
(dk-have! (list 'IN cxs-expr '(FUN RR RR))
  (lambda ()
    (dk-lam-t!)
    (let ((v (dk-di-var!)) (leaf (proof-state-focus *ps*)))
      (fact 'cc-exp-real-valued v)
      (if (not (sequent-node-grounded? leaf)) (ass)))))
(dk-conj-close!
  (lambda ()
    (if (dk-head-is? (dk-goal) 'IN)
        (ass)
        (let* ((ld (dk-peel!)) (x (cxs-land-var ld 'RR)))
          (fact 'rr-subset-cc x)
          (fact 'cc-exp-continuous x)
          (cxs-chain!
            (detach-with! (dk-fact! 'cc-continuous-restrict-rr cxs-expl cxs-expr x)
              (lambda ()
                (let* ((lv (dk-peel!)) (v (cxs-land-var lv 'RR)) (leaf (proof-state-focus *ps*)))
                  (fact 'rr-subset-cc v)
                  (cxs-exp-typ! v)
                  (dk-lam-b!)
                  (if (not (sequent-node-grounded? leaf)) (rfl))))))
          (ass)))))
(qed 'cc-exp-real-continuous-rr)

;;; ======================================================================
;;; (R) THE REAL DERIVATIVE OF A COMPLEX-DIFFERENTIABLE FUNCTION THAT IS REAL
;;; ON RR.  F differentiable on CC at the real point a with the real derivative
;;; L, and G in FUN(RR, RR) agreeing with F on RR  ==>  G is differentiable at
;;; a with derivative L (is-diff-at).  The Caratheodory factor phi of F is real
;;; on RR: phi(a) = L, and for v /= a, phi(v) = (G(v) - G(a)) / (v - a).  Its
;;; restriction psi = (v in RR |-> phi(v)) is continuous at a by
;;; cc-continuous-restrict-rr, and is G's factor.
;;; ======================================================================
(sp (make-wff '(FORALL cxsf_ (FORALL cxsg_ (FORALL cxsa_ (FORALL cxsl_
  (IMPLIES (IS-DIFF-ON CC-NORMED-FIELD CC cxsf_ cxsa_ cxsl_)
  (IMPLIES (IN cxsg_ (FUN RR RR)) (IMPLIES (IN cxsa_ RR) (IMPLIES (IN cxsl_ RR)
  (IMPLIES (FORALL cxsv_ (IMPLIES (IN cxsv_ RR) (= (cxsg_ cxsv_) (cxsf_ cxsv_))))
    (IS-DIFF-AT cxsg_ cxsa_ cxsl_))))))))))))
(dk-peel!)
(define cxs-rs-pw (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f 'cxsg_))) "G = F on RR"))
(fact 'cc-nf-carr)
(mac-h 'IS-DIFF-ON (dk-ctx-form '(IS-DIFF-ON CC-NORMED-FIELD CC cxsf_ cxsa_ cxsl_)))
(dk-split-all!)
(define cxs-rs-phi (dk-skolem! (dk-pick (dk-head? 'FORSOME) "the Caratheodory factor")))
(define cxs-rs-eq (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f cxs-rs-phi) (dk-contains? f 'MUL))) "the Caratheodory equation"))
(fact 'rr-subset-cc 'cxsa_)
;;; (IN (FN v) CC) from (IN FN (FUN CC (CARR CC-NORMED-FIELD))), v in CC
(define (cxs-rs-typ! fn v)
  (let ((g (list 'IN (list fn v) 'CC)))
    (if (not (dk-asm? g))
        (begin
          (dk-cite! 'fun-apply-type-c fn 'CC '(CARR CC-NORMED-FIELD) v)
          (dk-have! g (lambda () (subst '(== CC (CARR CC-NORMED-FIELD))) (ass)))))
    g))
;;; v in RR: lands (= (- (G v) (G a)) (* (phi v) (- v a)))
(define (cxs-rs-e1! v)
  (let* ((phi cxs-rs-phi) (a 'cxsa_) (K 'CC-NORMED-FIELD)
         (fv (list 'cxsf_ v)) (fa '(cxsf_ cxsa_)) (gv (list 'cxsg_ v)) (ga '(cxsg_ cxsa_))
         (pv (list phi v)) (d (list '- v a))
         (addf (lambda (x y) (list (list 'ADD K) x y))) (negf (lambda (x) (list (list 'NEG K) x)))
         (claim (list '= (list '- gv ga) (list '* pv d))))
    (if (not (dk-asm? claim))
        (begin
          (fact 'rr-subset-cc v)
          (cxs-rs-typ! 'cxsf_ v) (cxs-rs-typ! 'cxsf_ a) (cxs-rs-typ! phi v)
          (if (not (dk-asm? (list '= gv fv))) (dk-apply! cxs-rs-pw v))
          (if (not (dk-asm? (list '= ga fa))) (dk-apply! cxs-rs-pw a))
          (if (not (dk-asm? (list '= (addf fv (negf fa)) (list (list 'MUL K) pv (addf v (negf a))))))
              (dk-apply! cxs-rs-eq v))
          (dk-cite! 'cc-nf-sub fv fa)
          (dk-cite! 'cc-nf-sub v a)
          (cxs-cc-typ! d)
          (dk-cite! 'cc-nf-mul-apply pv d)
          (dk-have! claim
            (lambda ()
              (subst (list '= gv fv))
              (subst (list '= ga fa))
              (subst (list '== (list '* pv d) (list (list 'MUL K) pv d)))
              (subst (list '== d (addf v (negf a))))
              (subst (list '== (list '- fv fa) (addf fv (negf fa))))
              (ass)))))
    claim))
;;; v in RR: (IN (phi v) RR)
(define (cxs-rs-real! v)
  (let* ((phi cxs-rs-phi) (a 'cxsa_) (pv (list phi v)) (d (list '- v a))
         (q (list '- (list 'cxsg_ v) '(cxsg_ cxsa_))) (r (list 'recip d))
         (off (lambda ()
                (dk-cite! 'fun-apply-type-c 'cxsg_ 'RR 'RR v)
                (dk-cite! 'fun-apply-type-c 'cxsg_ 'RR 'RR a)
                (cxs-rr-typ! d) (cxs-rr-typ! q)
                (let ((lt (if (dk-asm? (list '< v a)) (list '< v a) (list '< a v))))
                  (dk-have! (list 'NOT (list '= d 0)) (lambda () (di) (cxs-absurd! (list '= d 0) lt))))
                (cxs-rs-e1! v)
                (cxs-cc-typ! d)
                (cxs-and! (list 'IN d 'CC) (list 'NOT (list '= d 0)))
                (dk-cite! 'cc-recip-inverse d)
                (cxs-and! (list 'IN d 'RR) (list 'NOT (list '= d 0)))
                (dk-cite! 'rr-recip-closed d)
                (cxs-rr-typ! (list '* q r))
                (cxs-cc-typ! r)
                (dk-have! (list '= pv (list '* q r))
                  (lambda ()
                    (subst (list '= q (list '* pv d)))
                    (subst (cxs-ring-id! '(cxsxa_ cxsxb_ cxsxc_) '(= (* (* cxsxa_ cxsxb_) cxsxc_) (* cxsxa_ (* cxsxb_ cxsxc_))) (list pv d r)))
                    (subst (list '= (list '* d r) 1))
                    (crs)))
                (subst (list '= pv (list '* q r)))
                (ass))))
    (use-cases (dk-fact! 'rr-lt-trichotomy v a)
      off
      (lambda () (subst (list '= v a)) (subst (list '= (list phi a) 'cxsl_)) (ass))
      off)))
(define cxs-rs-T (list 'FORALL 'cxst_ (list 'IMPLIES '(IN cxst_ RR) (list 'IN (list cxs-rs-phi 'cxst_) 'RR))))
(dk-have! cxs-rs-T (lambda () (let ((v (dk-di-var!))) (cxs-rs-real! v))))
(define cxs-rs-psi (list 'VNB-LAMBDA 'cxsw_ 'RR (list cxs-rs-phi 'cxsw_)))
(dk-have! (list 'IN cxs-rs-psi '(FUN RR RR))
  (lambda ()
    (dk-lam-t!)
    (let ((v (dk-di-var!)) (leaf (proof-state-focus *ps*)))
      (dk-apply! (dk-ctx-form cxs-rs-T) v)
      (if (not (sequent-node-grounded? leaf)) (ass)))))
(define (cxs-rs-inner!)
  (let ((g (dk-goal)) (leaf (proof-state-focus *ps*)) (phi cxs-rs-phi) (psi cxs-rs-psi))
    (cond
      ((dk-head-is? g 'IN) (ass))
      ((dk-head-is? g 'IS-CONTINUOUS-AT)
       (cxs-chain!
         (detach-with! (dk-fact! 'cc-continuous-restrict-rr phi psi 'cxsa_)
           (lambda ()
             (let* ((lv (dk-peel!)) (v (cxs-land-var lv 'RR)) (lf (proof-state-focus *ps*)))
               (fact 'rr-subset-cc v)
               (cxs-rs-typ! phi v)
               (dk-lam-b!)
               (if (not (sequent-node-grounded? lf)) (rfl))))))
       (if (not (sequent-node-grounded? leaf)) (ass)))
      ((dk-head-is? g '=)
       (dk-lam-b!)
       (if (not (sequent-node-grounded? leaf)) (ass)))
      ((dk-head-is? g 'FORALL)
       (let* ((ld (dk-peel!)) (x (cxs-land-var ld 'RR)) (lf (proof-state-focus *ps*)))
         (dk-lam-b!)
         (if (not (sequent-node-grounded? lf))
             (begin (cxs-rs-e1! x) (if (not (sequent-node-grounded? lf)) (ass))))))
      (#t (error "cxs-rs-inner!: unexpected goal" (expression->string g))))))
(mac 'IS-DIFF-AT)
(dk-conj-close!
  (lambda ()
    (if (dk-head-is? (dk-goal) 'FORSOME)
        (begin (ew cxs-rs-psi) (dk-conj-close! cxs-rs-inner!))
        (ass))))
(qed 'cc-diff-on-restrict-rr)

;;; exp' = exp on the real line, as a real function
(sp (make-wff (list 'FORALL 'cxst_ (list 'IMPLIES '(IN cxst_ RR) (list 'IS-DIFF-AT cxs-expr 'cxst_ '(CC-EXP cxst_))))))
(dk-peel!)
(dk-split-all! (list (dk-fact! 'cc-exp-real-continuous-rr)))
(cxs-exp-rr! 'cxst_)
(fact 'cc-exp-deriv 'cxst_)
(cxs-chain!
  (detach-with! (dk-fact! 'cc-diff-on-restrict-rr cxs-expl cxs-expr 'cxst_ '(CC-EXP cxst_))
    (lambda ()
      (let* ((lv (dk-peel!)) (v (cxs-land-var lv 'RR)) (leaf (proof-state-focus *ps*)))
        (fact 'rr-subset-cc v)
        (cxs-exp-typ! v)
        (dk-lam-b!)
        (if (not (sequent-node-grounded? leaf)) (rfl))))))
(ass)
(qed 'cc-exp-real-deriv)

;;; ======================================================================
;;; (8) THE BRIDGE exp|RR = r-exp.  H(t) = log(exp t) - t has derivative
;;; exp(t)^-1 exp(t) - 1 = 0 on RR (deriv-chain with log-deriv, deriv-difference),
;;; so H is constant (deriv-zero-implies-constant on [min(0,t), max(0,t)]),
;;; H(0) = log 1 = 0, and log(exp t) = t gives r-exp(t) = exp(t) by r-exp-char.
;;; ======================================================================
(define cxs-lg '(VNB-LAMBDA x_ RR (LOG x_)))
(define cxs-hc '(VNB-LAMBDA cxsh_ RR (- (LOG (CC-EXP cxsh_)) cxsh_)))
(sp (make-wff (list 'FORALL 'cxsx_ (list 'IMPLIES '(IN cxsx_ RR) (list 'IS-DIFF-AT cxs-hc 'cxsx_ 0)))))
(dk-peel!)
(let* ((x 'cxsx_) (e '(CC-EXP cxsx_)) (m (list 'RECIP-STAR e)) (ex (list cxs-expr x))
       (lg cxs-lg) (me (list '* m e)))
  (fact 'rr-zero-in) (fact 'rr-one-in)
  (cxs-exp-rr! x)
  (dk-split-all! (list (dk-fact! 'cc-exp-real x)))
  (fact 'cc-exp-nonzero x)
  (cxs-rr-typ! m)
  (dk-split-all! (list (dk-fact! 'cc-exp-real-continuous-rr)))
  (fact 'log-lam-in-fun)
  (fact 'cc-exp-real-deriv x)
  (fact 'log-deriv e)
  (dk-have! (list '= ex e) (lambda () (cxs-beta! (lambda () (rfl)))))
  (dk-have! (list 'IS-DIFF-AT lg ex m) (lambda () (subst (list '= ex e)) (ass)))
  (fact 'deriv-chain cxs-expr lg x e m)
  (fact 'deriv-identity x)
  (let* ((cmp (list 'COMPOSE lg cxs-expr))
         (dd (dk-fact! 'deriv-difference cmp '(VNB-LAMBDA x RR x) x me 1))
         (hraw (cadr dd)))
    (cxs-rr-typ! me)
    (dk-have! (list '= me 1)
      (lambda ()
        (dk-have! (list '= me (list '* e m)) (lambda () (crs)))
        (subst (list '= me (list '* e m)))
        (dk-cite! 'recip-star-inverse e)
        (ass)))
    (dk-have! (list '= (list '- me 1) 0) (lambda () (dk-ineq! (list '= me 1))))
    (fact 'diff-at-in-fun hraw x (list '- me 1))
    (cxs-and! (list 'IN cxs-expr '(FUN RR RR)) (list 'IN lg '(FUN RR RR)))
    (let ((cxs-le-ca (dk-fact! 'compose-apply 'RR 'RR 'RR lg cxs-expr)))
    (dk-fun-ext! cxs-hc hraw 'RR 'RR
      (lambda ()
        (dk-lam-type!
          (lambda ()
            (let ((v (dk-di-var!)) (leaf (proof-state-focus *ps*)))
              (cxs-rr-typ! (list '- (list 'LOG (list 'CC-EXP v)) v))
              (if (not (sequent-node-grounded? leaf)) (ass))))))
      (lambda () (ass))
      (lambda (v)
        (let ((leaf (proof-state-focus *ps*)))
          (cxs-exp-rr! v)
          (cxs-rr-typ! (list 'LOG (list 'CC-EXP v)))
          (dk-apply! cxs-le-ca v)
          (dk-lam-b!)
          (if (not (sequent-node-grounded? leaf))
              (let ((lf (proof-state-focus *ps*)))
                (subst (list '= (list cmp v) (list lg (list cxs-expr v))))
                (dk-lam-b!)
                (if (not (sequent-node-grounded? lf)) (rfl))))))))
    (subst (list '= cxs-hc hraw))
    (subst (list '= 0 (list '- me 1)))
    (ass)))
(qed 'cxs-log-exp-deriv)

;;; lo < hi (reals): lands (= (H lo) (H hi))
(define (cxs-const! lo hi)
  (let* ((h cxs-hc) (claim (list '= (list h lo) (list h hi))))
    (cxs-and! (list 'IN hi 'RR) (list '< lo hi))
    (cxs-and! (list 'IN lo 'RR) (list 'AND (list 'IN hi 'RR) (list '< lo hi)))
    (cxs-and! (list 'IN h '(FUN RR RR)) (list 'AND (list 'IN lo 'RR) (list 'AND (list 'IN hi 'RR) (list '< lo hi))))
    (let* ((c1 (dk-fact! 'deriv-zero-implies-constant h lo hi))
           (c2 (detach-with! c1
                 (lambda ()
                   (let* ((ld (dk-peel!)) (y (cadr (car ld))))
                     (mac-h 'ccint-membership (car ld))
                     (dk-split-all!)
                     (fact 'cxs-log-exp-deriv y)
                     (fact 'diff-implies-continuous h y 0)
                     (ass)))))
           (c3 (detach-with! c2
                 (lambda ()
                   (dk-peel!)
                   (dk-split-all!)
                   (let ((y (caddr (dk-goal))))
                     (fact 'cxs-log-exp-deriv y)
                     (ass))))))
      (for-each
        (lambda (p)
          (dk-have! (list 'IN p (list 'CCINT lo hi))
            (lambda ()
              (mac 'ccint-membership)
              (dk-conj-close! (lambda () (if (dk-head-is? (dk-goal) 'IN) (ass) (dk-ineq! (list '< lo hi))))))))
        (list lo hi))
      (cxs-and! (list 'IN lo (list 'CCINT lo hi)) (list 'IN hi (list 'CCINT lo hi)))
      (dk-apply! c3 lo hi)
      claim)))
(define (cxs-bridge-tail!)
  (let* ((t 'cxst_) (h cxs-hc) (ht (list h t)) (h0 (list h 0)) (e '(CC-EXP cxst_)) (l (list 'LOG e)) (tl (list '- l t))
         (eq (if (dk-asm? (list '= ht h0)) (list '= ht h0) (list '= h0 ht))))
    (dk-cite! 'fun-apply-type-c h 'RR 'RR t)
    (dk-cite! 'fun-apply-type-c h 'RR 'RR 0)
    (cxs-rr-typ! l) (cxs-rr-typ! tl)
    (dk-have! (list '= ht tl) (lambda () (cxs-beta! (lambda () (rfl)))))
    (dk-cite! 'cc-exp-zero) (dk-cite! 'log-one)
    (dk-have! (list '= h0 0)
      (lambda ()
        (let ((leaf (proof-state-focus *ps*)))
          (dk-lam-b!)
          (if (not (sequent-node-grounded? leaf))
              (begin (subst '(= (CC-EXP 0) 1)) (subst '(= (LOG 1) 0)) (arith))))))
    (dk-have! (list '= l t) (lambda () (dk-ineq! eq (list '= ht tl) (list '= h0 0))))
    (fact 'r-exp-char t e)
    (subst (list '= (list 'R-EXP t) e))
    (rfl)))
(sp (make-wff '(FORALL cxst_ (IMPLIES (IN cxst_ RR) (= (CC-EXP cxst_) (R-EXP cxst_))))))
(dk-peel!)
(fact 'rr-zero-in)
(fact 'rr-subset-cc 0)
(let* ((t 'cxst_) (h cxs-hc) (ht (list h t)) (h0 (list h 0)) (e '(CC-EXP cxst_)) (l (list 'LOG e)))
  (cxs-exp-rr! t)
  (dk-split-all! (list (dk-fact! 'cc-exp-real t)))
  (fact 'cxs-log-exp-deriv 0)
  (fact 'diff-at-in-fun h 0 0)
  (use-cases (dk-fact! 'rr-lt-trichotomy t 0)
    (lambda () (cxs-const! t 0) (cxs-bridge-tail!))
    (lambda ()
      (subst (list '= t 0))
      (subst (dk-fact! 'cc-exp-zero))
      (subst (dk-fact! 'r-exp-zero))
      (arith))
    (lambda () (cxs-const! 0 t) (cxs-bridge-tail!))))
(qed 'cc-exp-real-is-r-exp)

;;; ======================================================================
;;; (3) exp MAPS RR ONTO THE POSITIVE REALS.  Through the bridge: for r > 0,
;;; s = log r has exp s = r-exp(log r) = r (r-exp-log).  (Shorter than the IVT
;;; route: no growth estimate for exp is needed.)
;;; ======================================================================
(sp (make-wff '(FORALL cxsr_ (IMPLIES (IN cxsr_ RR) (IMPLIES (< 0 cxsr_)
  (FORSOME cxss_ (AND (IN cxss_ RR) (= (CC-EXP cxss_) cxsr_))))))))
(dk-peel!)
(let ((s '(LOG cxsr_)))
  (fact 'log-in-rr 'cxsr_)
  (fact 'r-exp-log 'cxsr_)
  (fact 'cc-exp-real-is-r-exp s)
  (ew s)
  (dk-conj-close!
    (lambda ()
      (if (dk-head-is? (dk-goal) 'IN)
          (ass)
          (begin (subst (list '= (list 'CC-EXP s) (list 'R-EXP s))) (ass))))))
(qed 'cc-exp-real-surjective-pos)

;;; ======================================================================
;;; (4) EVERY POINT OF THE UNIT CIRCLE IS (cos th, sin th) WITH -pi <= th < pi.
;;; -cos is continuous on RR with -cos 0 = -1 <= -a <= 1 = -cos pi, so the IVT
;;; on [0, pi] gives th0 with cos th0 = a; sin^2 th0 = 1 - a^2 = b^2, so
;;; (sin th0 - b)(sin th0 + b) = 0.  sin th0 = b with th0 < pi: th = th0;
;;; sin th0 = -b: th = -th0 (cos even, sin odd); th0 = pi forces sin th0 = 0 =
;;; b, so -th0 = -pi serves.
;;; ======================================================================
(define (cxs-exp-it-eq! t u)             ; lands (= (CC-EXP (* +i t)) (CC-EXP u)) when (* +i t) = u by crs
  (let ((it (list '* +i t)))
    (cxs-cc-typ! it) (cxs-cc-typ! u) (cxs-exp-typ! it) (cxs-exp-typ! u)
    (dk-have! (list '= it u) (lambda () (crs)))
    (dk-congr! (list '= it u) (lambda (x) (list 'CC-EXP x)))))
(define cxs-ncos '(VNB-LAMBDA cekv_ RR (* -1 (CC-COS cekv_))))
;;; the closer of a conjunction of facts: assumption, else ineq from PREMS
(define (cxs-close-by! prems)
  (lambda ()
    (if (dk-asm? (dk-goal)) (ass) (apply dk-ineq! prems))))
(sp (make-wff '(FORALL cxsa_ (IMPLIES (IN cxsa_ RR) (FORALL cxsb_ (IMPLIES (IN cxsb_ RR)
  (IMPLIES (= (+ (power cxsa_ 2) (power cxsb_ 2)) 1)
    (FORSOME cxsth_ (AND (IN cxsth_ RR) (AND (<= (- PI) cxsth_) (AND (< cxsth_ PI)
      (AND (= (CC-COS cxsth_) cxsa_) (= (CC-SIN cxsth_) cxsb_)))))))))))))
(dk-peel!)
(cxs-pi-typ!)
(let* ((a 'cxsa_) (b 'cxsb_) (aa '(* cxsa_ cxsa_)) (bb '(* cxsb_ cxsb_)) (ma '(- cxsa_)) (nc cxs-ncos))
  (fact 'rr-zero-in) (fact 'rr-one-in)
  (fact 'rr-subset-cc a) (fact 'rr-subset-cc b)
  (cxs-pow2! a) (cxs-pow2! b)
  (cxs-rr-typ! aa) (cxs-rr-typ! bb) (cxs-rr-typ! ma) (cxs-rr-typ! -1)
  (dk-have! (list '= (list '+ aa bb) 1)
    (lambda () (subst (list '= aa '(power cxsa_ 2))) (subst (list '= bb '(power cxsb_ 2))) (ass)))
  (fact 'rr-sq-nonneg b)
  (dk-have! (list '<= a 1)
    (lambda ()
      (use-cases (cxs-leq-total! a 1)
        (lambda () (ass))
        (lambda ()
          (dk-have! (list '<= 0 a) (lambda () (dk-ineq! (list '<= 1 a))))
          (fact 'rr-mul-le-right 1 a a)
          (dk-ineq! (list '<= '(* 1 cxsa_) aa) (list '= (list '+ aa bb) 1) (list '<= 0 bb))))))
  (dk-have! (list '<= -1 a)
    (lambda ()
      (use-cases (cxs-leq-total! -1 a)
        (lambda () (ass))
        (lambda ()
          (dk-have! (list '<= 1 ma) (lambda () (dk-ineq! (list '<= a -1))))
          (dk-have! (list '<= 0 ma) (lambda () (dk-ineq! (list '<= a -1))))
          (fact 'rr-mul-le-right 1 ma ma)
          (cxs-rr-typ! (list '* ma ma))
          (dk-have! (list '= (list '* ma ma) aa) (lambda () (crs)))
          (dk-ineq! (list '<= (list '* 1 ma) (list '* ma ma)) (list '= (list '* ma ma) aa)
                    (list '= (list '+ aa bb) 1) (list '<= 0 bb))))))
  ;; the IVT for -cos on [0, pi] at -a
  (dk-split-all! (list (dk-fact! 'cc-neg-cos-continuous-rr)))
  (dk-have! '(<= 0 PI) (lambda () (dk-ineq! '(< 0 PI))))
  (fact 'cc-cos-zero)
  (fact 'cc-cos-pi)
  (fact 'rr-subset-cc 0)
  (cxs-rr-typ! '(CC-COS 0)) (cxs-rr-typ! '(CC-COS PI))
  (dk-have! (list 'FORALL 'x (list 'IMPLIES '(IN x (CCINT 0 PI)) (list 'IS-CONTINUOUS-AT 'RR-MS 'RR-MS nc 'x)))
    (lambda ()
      (let* ((ld (dk-peel!)) (x (cadr (car ld))))
        (mac-h 'ccint-membership (car ld))
        (dk-split-all!)
        (dk-apply! (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f 'IS-CONTINUOUS-AT))) "continuity") x)
        (ass))))
  (let ((n0 (list nc 0)) (npi (list nc 'PI)))
    (fact 'fun-apply-type-c nc 'RR 'RR 0)
    (fact 'fun-apply-type-c nc 'RR 'RR 'PI)
    (cxs-rr-typ! '(* -1 (CC-COS 0))) (cxs-rr-typ! '(* -1 (CC-COS PI)))
    (dk-have! (list '= n0 '(* -1 (CC-COS 0))) (lambda () (cxs-beta! (lambda () (rfl)))))
    (dk-have! (list '= npi '(* -1 (CC-COS PI))) (lambda () (cxs-beta! (lambda () (rfl)))))
    (dk-have! (list 'AND (list '<= n0 ma) (list '<= ma npi))
      (lambda ()
        (dk-conj-close!
          (lambda ()
            (dk-ineq! (list '= n0 '(* -1 (CC-COS 0))) (list '= npi '(* -1 (CC-COS PI))) '(= (CC-COS 0) 1) '(= (CC-COS PI) -1)
                      (list '<= a 1) (list '<= -1 a)))))))
  (let* ((p (dk-skolem! (dk-fact! 'ivt nc 0 'PI ma)))
         (cp (list 'CC-COS p)) (snp (list 'CC-SIN p)) (np (list nc p)) (mp (list '- p))
         (d1 (list '- snp b)) (d2 (list '+ snp b)))
    (mac-h 'ccint-membership (list 'IN p '(CCINT 0 PI)))
    (dk-split-all!)
    (fact 'fun-apply-type-c nc 'RR 'RR p)
    (fact 'rr-subset-cc p)
    (cxs-rr-typ! cp) (cxs-rr-typ! snp) (cxs-rr-typ! mp)
    (cxs-rr-typ! (list '* -1 cp))
    (dk-have! (list '= np (list '* -1 cp)) (lambda () (cxs-beta! (lambda () (rfl)))))
    (dk-have! (list '= cp a) (lambda () (dk-ineq! (list '= np ma) (list '= np (list '* -1 cp)))))
    ;; sin p = b or sin p = -b
    (fact 'cc-cos-sin-one p)
    (cxs-pow2! cp) (cxs-pow2! snp)
    (cxs-rr-typ! (list '* cp cp)) (cxs-rr-typ! (list '* snp snp))
    (dk-have! (list '= (list '* cp cp) aa) (lambda () (subst (list '= cp a)) (rfl)))
    (dk-have! (list '= (list '+ (list '* cp cp) (list '* snp snp)) 1)
      (lambda ()
        (subst (list '= (list '* cp cp) (list 'power cp 2)))
        (subst (list '= (list '* snp snp) (list 'power snp 2)))
        (ass)))
    (cxs-rr-typ! d1) (cxs-rr-typ! d2)
    (dk-have! (list '= (list '* d1 d2) 0)
      (lambda ()
        (subst (cxs-ring-id! '(cxsxa_ cxsxb_) '(= (* (- cxsxa_ cxsxb_) (+ cxsxa_ cxsxb_)) (- (* cxsxa_ cxsxa_) (* cxsxb_ cxsxb_))) (list snp b)))
        (dk-ineq! (list '= (list '+ (list '* cp cp) (list '* snp snp)) 1) (list '= (list '* cp cp) aa) (list '= (list '+ aa bb) 1))))
    (fact 'cc-cos-even p)
    (fact 'cc-sin-odd p)
    (let ((pos! (lambda ()
                  (ew p)
                  (dk-conj-close! (cxs-close-by! (list (list '<= 0 p) '(< 0 PI) (list '= d1 0))))))
          (neg! (lambda ()
                  (ew mp)
                  (dk-conj-close!
                    (lambda ()
                      (let ((g (dk-goal)))
                        (cond ((dk-asm? g) (ass))
                              ((dk-contains? g 'CC-COS) (subst (list '= (list 'CC-COS mp) cp)) (ass))
                              ((dk-contains? g 'CC-SIN) (subst (list '= (list 'CC-SIN mp) (list '- snp))) (dk-ineq! (list '= d2 0)))
                              (#t (dk-ineq! (list '<= 0 p) (list '<= p 'PI) '(< 0 PI))))))))))
      (use-cases (dk-fact! 'rr-no-zero-divisors d1 d2)
        (lambda ()
          (use-cases (dk-fact! 'rr-lt-trichotomy p 'PI)
            pos!
            (lambda ()
              (cxs-rr-typ! '(CC-SIN PI))
              (fact 'cc-sin-pi)
              (dk-congr! (list '= p 'PI) (lambda (x) (list 'CC-SIN x)))
              (dk-have! (list '= d2 0) (lambda () (dk-ineq! (list '= d1 0) (list '= snp '(CC-SIN PI)) '(= (CC-SIN PI) 0))))
              (neg!))
            (lambda () (cxs-absurd! (list '< 'PI p) (list '<= p 'PI)))))
        neg!))))
(qed 'cc-circle-arg)

;;; ======================================================================
;;; (5) THE POLAR FORM: w /= 0 is r exp(i th) with r = |w| > 0, -pi <= th < pi.
;;; a = Re w / |w|, b = Im w / |w| lie on the unit circle (|w|^2 = Re^2 + Im^2),
;;; (4) gives th, and exp(i th) = cos th + i sin th = a + i b (cc-exp-i).
;;; ======================================================================
(sp (make-wff '(FORALL cxsw_ (IMPLIES (IN cxsw_ CC) (IMPLIES (NOT (= cxsw_ 0))
  (FORSOME cxsr_ (AND (IN cxsr_ RR) (FORSOME cxsth_ (AND (IN cxsth_ RR)
    (AND (< 0 cxsr_) (AND (<= (- PI) cxsth_) (AND (< cxsth_ PI) (= cxsw_ (* cxsr_ (CC-EXP (* +i cxsth_))))))))))))))))
(dk-peel!)
(cxs-pi-typ!)
(let* ((w 'cxsw_) (r '(magnitude cxsw_)) (x '(real-part cxsw_)) (y '(imag-part cxsw_)) (ri (list 'recip r))
       (a (list '* x ri)) (b (list '* y ri)) (xx (list '+ x (list '* +i y))))
  (fact 'rr-zero-in)
  (cxs-rr-typ! r) (cxs-rr-typ! x) (cxs-rr-typ! y)
  (fact 'cc-magnitude-nonneg w)
  (dk-have! (list 'NOT (list '= r 0))
    (lambda ()
      (di)
      (let* ((i (dk-cite! 'cc-magnitude-zero-iff w))
             (ims (dk-landed (lambda () (ai i))))
             (fwd (find-first (lambda (f) (equal? (cadr f) (list '= r 0))) ims)))
        (detach! fwd)
        (ai (list 'NOT (list '= w 0))))))
  (dk-have! (list 'NOT (list '= 0 r))
    (lambda () (di) (dk-have! (list '= r 0) (lambda () (dk-ineq! (list '= 0 r)))) (ai (list 'NOT (list '= r 0)))))
  (cxs-and! (list '<= 0 r) (list 'NOT (list '= 0 r)))
  (fact 'rr-le-ne-lt 0 r)
  (cxs-and! (list 'IN r 'RR) (list 'NOT (list '= r 0)))
  (fact 'rr-recip-closed r)
  (fact 'rr-subset-cc r)
  (cxs-and! (list 'IN r 'CC) (list 'NOT (list '= r 0)))
  (fact 'cc-recip-inverse r)
  (cxs-rr-typ! a) (cxs-rr-typ! b)
  (fact 'cc-magnitude-sq w)
  (cxs-pow2! a) (cxs-pow2! b)
  (dk-have! (list '= (list '+ (list 'power a 2) (list 'power b 2)) 1)
    (lambda ()
      (subst (list '= (list 'power a 2) (list '* a a)))
      (subst (list '= (list 'power b 2) (list '* b b)))
      (subst (cxs-ring-id! '(cxsxa_ cxsxb_ cxsxc_)
               '(= (+ (* (* cxsxa_ cxsxc_) (* cxsxa_ cxsxc_)) (* (* cxsxb_ cxsxc_) (* cxsxb_ cxsxc_)))
                   (* (+ (* cxsxa_ cxsxa_) (* cxsxb_ cxsxb_)) (* cxsxc_ cxsxc_)))
               (list x y ri)))
      (subst (list '= (list '+ (list '* x x) (list '* y y)) (list '* r r)))
      (subst (cxs-ring-id! '(cxsxa_ cxsxb_) '(= (* (* cxsxa_ cxsxa_) (* cxsxb_ cxsxb_)) (* (* cxsxa_ cxsxb_) (* cxsxa_ cxsxb_))) (list r ri)))
      (subst (list '= (list '* r ri) 1))
      (arith)))
  (let* ((th (dk-skolem! (dk-fact! 'cc-circle-arg a b)))
         (it (list '* +i th)) (rhs (list '* r (list 'CC-EXP it))))
    (fact 'rr-subset-cc th)
    (fact 'cc-exp-i th)
    (fact 'cc-re-im-decompose w)
    (cxs-exp-typ! it) (cxs-cc-typ! rhs) (cxs-cc-typ! xx)
    (dk-have! (list '= rhs xx)
      (lambda ()
        (subst (list '= (list 'CC-EXP it) (list '+ (list 'CC-COS th) (list '* +i (list 'CC-SIN th)))))
        (subst (list '= (list 'CC-COS th) a))
        (subst (list '= (list 'CC-SIN th) b))
        (subst (cxs-ring-id! '(cxsxa_ cxsxb_ cxsxc_ cxsxd_)
                 (list '= (list '* 'cxsxa_ (list '+ '(* cxsxb_ cxsxd_) (list '* +i '(* cxsxc_ cxsxd_))))
                          (list '+ '(* cxsxb_ (* cxsxa_ cxsxd_)) (list '* +i '(* cxsxc_ (* cxsxa_ cxsxd_)))))
                 (list r x y ri)))
        (subst (list '= (list '* r ri) 1))
        (crs)))
    (ew r)
    (dk-conj-close!
      (lambda ()
        (if (dk-head-is? (dk-goal) 'FORSOME)
            (begin
              (ew th)
              (dk-conj-close!
                (lambda ()
                  (if (dk-asm? (dk-goal)) (ass) (begin (subst (list '= rhs xx)) (ass))))))
            (ass))))))
(qed 'cc-polar-form)

;;; ======================================================================
;;; (6) PROPOSITION 2.19, SURJECTIVITY: every w /= 0 is exp z with
;;; -pi <= Im z < pi.  w = r exp(i th) (5), r = exp s (3), z = s + th i.
;;; ======================================================================
(sp (make-wff '(FORALL cxsw_ (IMPLIES (IN cxsw_ CC) (IMPLIES (NOT (= cxsw_ 0))
  (FORSOME cxsz_ (AND (IN cxsz_ CC) (AND (<= (- PI) (imag-part cxsz_)) (AND (< (imag-part cxsz_) PI)
    (= (CC-EXP cxsz_) cxsw_))))))))))
(dk-peel!)
(cxs-pi-typ!)
(let* ((w 'cxsw_)
       (r (dk-skolem! (dk-fact! 'cc-polar-form w)))
       (th (dk-skolem! (dk-pick (dk-head? 'FORSOME) "the argument")))
       (it (list '* +i th)) (ti (list '* th +i)) (rhs (list '* r (list 'CC-EXP it)))
       (s (dk-skolem! (dk-fact! 'cc-exp-real-surjective-pos r)))
       (z (list '+ s ti)))
  (fact 'rr-subset-cc s) (fact 'rr-subset-cc th) (fact 'rr-subset-cc r)
  (cxs-cc-typ! ti) (cxs-cc-typ! z)
  (dk-have! (list '= z z) (lambda () (rfl)))
  (dk-split-all! (list (dk-fact! 'cc-re-im-of z s th)))
  (cxs-exp-typ! s) (cxs-exp-typ! ti) (cxs-exp-typ! it) (cxs-cc-typ! rhs)
  (fact 'cc-exp-add s ti)
  (cxs-exp-it-eq! th ti)
  (ew z)
  (dk-conj-close!
    (lambda ()
      (let ((g (dk-goal)))
        (cond ((dk-asm? g) (ass))
              ((dk-contains? g 'CC-EXP)
               (subst (list '= (list 'CC-EXP z) (list '* (list 'CC-EXP s) (list 'CC-EXP ti))))
               (subst (list '= (list 'CC-EXP s) r))
               (subst (list '= (list 'CC-EXP ti) (list 'CC-EXP it)))
               (subst (list '= w rhs))
               (rfl))
              (#t (subst (list '= (list 'imag-part z) th)) (ass)))))))
(qed 'cc-exp-surjective-strip)

;;; ======================================================================
;;; PROPOSITION 2.19 AS STATED: exp is a bijection of the strip
;;; S = {z : -pi <= Im z < pi} onto C \ {0}  (the tree's BIJECTION(X, Y):
;;; bijection-membership-iff).  Injectivity is cc-exp-injective-strip (31-B),
;;; surjectivity cc-exp-surjective-strip.
;;; ======================================================================
(define cxs-S '(SEP cxsq_ CC (AND (<= (- PI) (imag-part cxsq_)) (< (imag-part cxsq_) PI))))
(define cxs-Y '(DIFFERENCE CC (SINGLETON 0)))
(define (cxs-es dom) (list 'VNB-LAMBDA 'cxsz_ dom '(CC-EXP cxsz_)))
;;; open (IN v SEP) -- consumed -- landing (IN v CC) and the split condition
(define (cxs-open-sep! v s)
  (dk-split-all! (dk-landed (lambda () (sep-me (list 'IN v s))))))
;;; the sethood leaf (IN (SEP q CC p) SET)
(define (cxs-sep-set!)
  (let ((leaf (proof-state-focus *ps*)))
    (sep-set)
    (if (not (sequent-node-grounded? leaf))
        (begin (fact 'cc-is-set) (ass)))))
;;; (= (CC-EXP a) (CC-EXP b)) from (= (E a) (E b)), a, b in DOM (typed)
(define (cxs-unbeta-eq! dom a b)
  (let* ((e (cxs-es dom)) (ea (list e a)) (eb (list e b)))
    (fact 'rr-zero-in)
    (dk-have! (list '== ea (list 'CC-EXP a)) (lambda () (cxs-beta! (lambda () (qrfl)))))
    (dk-have! (list '== eb (list 'CC-EXP b)) (lambda () (cxs-beta! (lambda () (qrfl)))))
    (dk-have! (list '= (list 'CC-EXP a) (list 'CC-EXP b))
      (lambda ()
        (subst (list '== (list 'CC-EXP a) ea))
        (subst (list '== (list 'CC-EXP b) eb))
        (ass)))))
;;; the bijection driver: DOM the strip, COD the image, TYPER, INJ, SURJ per point
(define (cxs-bij! dom typer inj surj)
  (let ((e (cxs-es dom)))
    (mac 'bijection-membership-iff)
    (dk-conj-close!
      (lambda ()
        (let ((g (dk-goal)))
          (cond
            ((dk-head-is? g 'IN)
             (dk-lam-type! (lambda () (let ((v (dk-di-var!))) (typer v))) cxs-sep-set!))
            ((dk-contains? g 'FORSOME)
             (let* ((ld (dk-peel!)) (w (cadr (car ld)))) (surj w)))
            (#t
             (let* ((ld (dk-peel!))
                    (vs (map cadr (filter (lambda (f) (and (dk-head-is? f 'IN) (equal? (caddr f) dom))) ld))))
               (inj (car vs) (cadr vs))))))))))
;;; v in S  ==>  v in CC, -pi <= Im v < pi (the membership consumed)
(sp (make-wff (list 'IN (cxs-es cxs-S) (list 'BIJECTION cxs-S cxs-Y))))
(cxs-pi-typ!)
(cxs-bij! cxs-S
  (lambda (v)
    (let ((leaf (proof-state-focus *ps*)))
      (cxs-open-sep! v cxs-S)
      (fact 'cc-exp-maps-to-nonzero v)
      (if (not (sequent-node-grounded? leaf)) (ass))))
  (lambda (a b)
    (cxs-unbeta-eq! cxs-S a b)
    (cxs-open-sep! a cxs-S)
    (cxs-open-sep! b cxs-S)
    (fact 'cc-exp-injective-strip a b)
    (ass))
  (lambda (w)
    (mac-h 'difference-membership (list 'IN w cxs-Y))
    (dk-split-all!)
    (dk-have! (list 'NOT (list '= w 0))
      (lambda ()
        (di)
        (dk-have! (list 'IN w '(SINGLETON 0))
          (lambda ()
            (mac 'singleton-membership)
            (dk-conj-close!
              (lambda ()
                (if (dk-head-is? (dk-goal) 'IN)
                    (begin (fact 'membership-implies-sethood w 'CC) (ass))
                    (ass))))))
        (ai (list 'NOT (list 'IN w '(SINGLETON 0))))))
    (let ((z (dk-skolem! (dk-fact! 'cc-exp-surjective-strip w))))
      (dk-have! (list 'IN z cxs-S) (lambda () (in-sep! (lambda () (ass)) (lambda () (dk-conj-close! (lambda () (ass)))))))
      (ew z)
      (dk-conj-close!
        (lambda ()
          (if (dk-asm? (dk-goal)) (ass)
              (let ((leaf (proof-state-focus *ps*)))
                (dk-lam-b!)
                (if (not (sequent-node-grounded? leaf)) (ass)))))))))
(qed 'cc-exp-bijection-strip)

;;; ======================================================================
;;; (7) THE OPEN STRIP S' = {z : -pi < Im z < pi}.  The notes: e^(r + i th) is
;;; in (-inf, 0] iff th = -pi (0 is not a value).  A value exp z in (-inf, 0]
;;; is q = -r' with r' > 0 = exp s', and exp(s' - pi i) = q, so z = s' - pi i by
;;; injectivity on S, contradicting Im z > -pi.  Conversely a w off (-inf, 0]
;;; is exp z with z in S (2.19), and Im z = -pi would make w = -exp(Re z).
;;; ======================================================================
(define cxs-ipi (list '* +i 'PI))
(define cxs-nipi (list '- cxs-ipi))
(define (cxs-exp-nipi!)                 ; (= (CC-EXP (- (* +i PI))) -1)
  (let ((e (list '= (list 'CC-EXP cxs-nipi) -1)))
    (if (not (dk-asm? e))
        (begin
          (cxs-pi-typ!)
          (cxs-cc-typ! cxs-ipi) (cxs-exp-typ! cxs-ipi) (cxs-exp-typ! cxs-nipi)
          (dk-cite! 'cc-exp-i-pi)
          (dk-cite! 'cc-exp-neg cxs-ipi)
          (dk-have! e
            (lambda ()
              (subst (list '= (list 'CC-EXP cxs-nipi) (list 'recip (list 'CC-EXP cxs-ipi))))
              (subst (list '= (list 'CC-EXP cxs-ipi) -1))
              (arith)))))
    e))
(sp (make-wff '(FORALL cxsz_ (IMPLIES (IN cxsz_ CC) (IMPLIES (< (- PI) (imag-part cxsz_)) (IMPLIES (< (imag-part cxsz_) PI)
  (NOT (AND (= (imag-part (CC-EXP cxsz_)) 0) (<= (real-part (CC-EXP cxsz_)) 0)))))))))
(dk-peel!)
(if (dk-head-is? (dk-goal) 'NOT) (di))
(dk-split-all!)
(cxs-pi-typ!)
(let* ((z 'cxsz_) (u '(CC-EXP cxsz_)) (q (list 'real-part u)) (iu (list 'imag-part u)) (xx (list '+ q (list '* +i iu)))
       (mq (list '- q)) (nti (list '* '(- PI) +i)))
  (fact 'rr-zero-in)
  (cxs-exp-typ! z) (cxs-rr-typ! q) (cxs-rr-typ! iu) (cxs-rr-typ! mq)
  (fact 'cc-exp-nonzero z)
  (fact 'cc-re-im-decompose u)
  (cxs-cc-typ! xx)
  (dk-have! (list '= xx q) (lambda () (subst (list '= iu 0)) (crs)))
  (dk-have! (list '= u q) (lambda () (subst (list '= q xx)) (ass)))
  (dk-have! (list 'NOT (list '= q 0))
    (lambda ()
      (di)
      (dk-have! (list '= u 0) (lambda () (subst (list '= u q)) (ass)))
      (ai (list 'NOT (list '= u 0)))))
  (cxs-and! (list '<= q 0) (list 'NOT (list '= q 0)))
  (fact 'rr-le-ne-lt q 0)
  (dk-have! (list '< 0 mq) (lambda () (dk-ineq! (list '< q 0))))
  (let* ((s (dk-skolem! (dk-fact! 'cc-exp-real-surjective-pos mq)))
         (z2 (list '+ s nti)))
    (fact 'rr-subset-cc s)
    (cxs-rr-typ! '(- PI))
    (cxs-cc-typ! nti) (cxs-cc-typ! z2) (cxs-cc-typ! cxs-nipi)
    (cxs-exp-typ! s) (cxs-exp-typ! nti) (cxs-exp-typ! z2)
    (cxs-exp-nipi!)
    (dk-have! (list '= nti cxs-nipi) (lambda () (crs)))
    (dk-congr! (list '= nti cxs-nipi) (lambda (x) (list 'CC-EXP x)))
    (fact 'cc-exp-add s nti)
    (dk-have! (list '= (list 'CC-EXP z2) q)
      (lambda ()
        (subst (list '= (list 'CC-EXP z2) (list '* (list 'CC-EXP s) (list 'CC-EXP nti))))
        (subst (list '= (list 'CC-EXP s) mq))
        (subst (list '= (list 'CC-EXP nti) (list 'CC-EXP cxs-nipi)))
        (subst (list '= (list 'CC-EXP cxs-nipi) -1))
        (crs)))
    (dk-have! (list '= z2 z2) (lambda () (rfl)))
    (dk-split-all! (list (dk-fact! 'cc-re-im-of z2 s '(- PI))))
    (let ((iz '(imag-part cxsz_)) (iz2 (list 'imag-part z2)))
      (cxs-rr-typ! iz) (cxs-rr-typ! iz2)
      (dk-have! (list '<= '(- PI) iz) (lambda () (dk-ineq! (list '< '(- PI) iz))))
      (dk-have! (list '<= '(- PI) iz2) (lambda () (dk-ineq! (list '= iz2 '(- PI)))))
      (dk-have! (list '< iz2 'PI) (lambda () (dk-ineq! (list '= iz2 '(- PI)) '(< 0 PI))))
      (dk-have! (list '= u (list 'CC-EXP z2)) (lambda () (subst (list '= (list 'CC-EXP z2) q)) (ass)))
      (fact 'cc-exp-injective-strip z z2)
      (dk-congr! (list '= z z2) (lambda (x) (list 'imag-part x)))
      (cxs-absurd! (list '< '(- PI) iz) (list '= iz iz2) (list '= iz2 '(- PI))))))
(qed 'cc-exp-open-strip-avoids-negatives)

(sp (make-wff '(FORALL cxsw_ (IMPLIES (IN cxsw_ CC) (IMPLIES (NOT (AND (= (imag-part cxsw_) 0) (<= (real-part cxsw_) 0)))
  (FORSOME cxsz_ (AND (IN cxsz_ CC) (AND (< (- PI) (imag-part cxsz_)) (AND (< (imag-part cxsz_) PI)
    (= (CC-EXP cxsz_) cxsw_))))))))))
(dk-peel!)
(cxs-pi-typ!)
(let* ((w 'cxsw_) (nh '(NOT (AND (= (imag-part cxsw_) 0) (<= (real-part cxsw_) 0)))))
  (fact 'rr-zero-in)
  (dk-have! (list 'NOT (list '= w 0))
    (lambda ()
      (di)
      (dk-have! (cadr nh)
        (lambda () (subst (list '= w 0)) (dk-conj-close! (lambda () (arith)))))
      (ai nh)))
  (let* ((z (dk-skolem! (dk-fact! 'cc-exp-surjective-strip w)))
         (iz (list 'imag-part z)) (x (list 'real-part z)) (xx (list '+ x (list '* +i iz)))
         (iiz (list '* +i iz)) (e (list 'CC-EXP x)) (me (list '- e)))
    (cxs-rr-typ! iz) (cxs-rr-typ! x)
    (dk-have! (list 'NOT (list '= '(- PI) iz))
      (lambda ()
        (di)
        (fact 'rr-subset-cc x)
        (cxs-cc-typ! iiz) (cxs-cc-typ! xx) (cxs-exp-typ! xx) (cxs-exp-typ! iiz)
        (cxs-exp-rr! x) (cxs-rr-typ! me)
        (dk-split-all! (list (dk-cite! 'cc-exp-real x)))
        (cxs-exp-nipi!)
        (fact 'cc-re-im-decompose z)
        (dk-congr! (list '= z xx) (lambda (y) (list 'CC-EXP y)))
        (fact 'cc-exp-add x iiz)
        (dk-have! (list '= iiz cxs-nipi) (lambda () (subst (list '= iz '(- PI))) (crs)))
        (dk-congr! (list '= iiz cxs-nipi) (lambda (y) (list 'CC-EXP y)))
        (dk-have! (list '= w me)
          (lambda ()
            (subst (list '= w (list 'CC-EXP z)))
            (subst (list '= (list 'CC-EXP z) (list 'CC-EXP xx)))
            (subst (list '= (list 'CC-EXP xx) (list '* e (list 'CC-EXP iiz))))
            (subst (list '= (list 'CC-EXP iiz) (list 'CC-EXP cxs-nipi)))
            (subst (list '= (list 'CC-EXP cxs-nipi) -1))
            (crs)))
        (fact 'rr-subset-cc me)
        (cxs-cc-typ! (list '* 0 +i))
        (dk-have! (list '= me (list '+ me (list '* 0 +i))) (lambda () (crs)))
        (dk-split-all! (list (dk-fact! 'cc-re-im-of me me 0)))
        (cxs-rr-typ! (list 'imag-part w)) (cxs-rr-typ! (list 'real-part w))
        (cxs-rr-typ! (list 'imag-part me)) (cxs-rr-typ! (list 'real-part me))
        (dk-congr! (list '= w me) (lambda (y) (list 'imag-part y)))
        (dk-congr! (list '= w me) (lambda (y) (list 'real-part y)))
        (dk-have! (cadr nh)
          (lambda ()
            (dk-conj-close!
              (lambda ()
                (dk-ineq! (list '= (list 'imag-part w) (list 'imag-part me)) (list '= (list 'imag-part me) 0)
                          (list '= (list 'real-part w) (list 'real-part me)) (list '= (list 'real-part me) me)
                          (list '< 0 e))))))
        (ai nh)))
    (cxs-rr-typ! '(- PI))
    (cxs-and! (list '<= '(- PI) iz) (list 'NOT (list '= '(- PI) iz)))
    (fact 'rr-le-ne-lt '(- PI) iz)
    (ew z)
    (dk-conj-close! (lambda () (ass)))))
(qed 'cc-exp-open-strip-onto)

;;; 2.19, the second assertion: exp is a bijection of the open strip onto
;;; C \ (-inf, 0]
(define cxs-S1 '(SEP cxsq_ CC (AND (< (- PI) (imag-part cxsq_)) (< (imag-part cxsq_) PI))))
(define cxs-Y1 '(SEP cxsu_ CC (NOT (AND (= (imag-part cxsu_) 0) (<= (real-part cxsu_) 0)))))
(sp (make-wff (list 'IN (cxs-es cxs-S1) (list 'BIJECTION cxs-S1 cxs-Y1))))
(cxs-pi-typ!)
(cxs-bij! cxs-S1
  (lambda (v)
    (cxs-open-sep! v cxs-S1)
    (cxs-exp-typ! v)
    (fact 'cc-exp-open-strip-avoids-negatives v)
    (in-sep! (lambda () (ass)) (lambda () (ass))))
  (lambda (a b)
    (cxs-unbeta-eq! cxs-S1 a b)
    (cxs-open-sep! a cxs-S1)
    (cxs-open-sep! b cxs-S1)
    (for-each (lambda (v)
                (cxs-rr-typ! (list 'imag-part v))
                (dk-have! (list '<= '(- PI) (list 'imag-part v)) (lambda () (dk-ineq! (list '< '(- PI) (list 'imag-part v))))))
              (list a b))
    (fact 'cc-exp-injective-strip a b)
    (ass))
  (lambda (w)
    (cxs-open-sep! w cxs-Y1)
    (let ((z (dk-skolem! (dk-fact! 'cc-exp-open-strip-onto w))))
      (dk-have! (list 'IN z cxs-S1) (lambda () (in-sep! (lambda () (ass)) (lambda () (dk-conj-close! (lambda () (ass)))))))
      (ew z)
      (dk-conj-close!
        (lambda ()
          (if (dk-asm? (dk-goal)) (ass)
              (let ((leaf (proof-state-focus *ps*)))
                (dk-lam-b!)
                (if (not (sequent-node-grounded? leaf)) (ass)))))))))
(qed 'cc-exp-bijection-open-strip)
