;;; cc-power-series-laws.scm -- COMPLEX POWER SERIES: THE RADIUS OF CONVERGENCE
;;; (Prop 2.7) AND WHAT FOLLOWS FROM IT, as the notes state them.
;;; Batch 25-A, 2026-09-24.
;;;
;;; THE SOURCE.  complex-analysis.pdf 2.2: the definition of the radius of
;;; convergence (p. 25), the computation "lim sup_k (|a_k| r^k)^(1/k) =
;;; r lim sup_k |a_k|^(1/k)" and Proposition 2.7 with its two special cases
;;; ("The radius of convergence is 0 which is the case if and only if
;;; lim sup_k |a_k|^(1/k) = +infinity and the radius of convergence is +infinity
;;; which is the case if and only if lim sup_k |a_k|^(1/k) = 0").
;;;
;;; VOCABULARY.  CPS-RADIUS (structure-library/cc-power-series.scm).  The lim sup is
;;; ELIMSUP on [0, +inf] and the k-th root is rpow-star(., recip-star(k)), as in
;;; theorem-library/limsup-tests.scm, whose laws this file uses.
;;;
;;; THE FILE IN ORDER.
;;;   (1) rr-power-mul-base: (x y)^k = x^k y^k.
;;;   (2) cps-root-conv, cps-root-div: with rho = lim sup |a_k|^(1/k),
;;;       rho < s and r s < 1  =>  sum |a_k| r^k converges;
;;;       s < rho and 1 <= r s  =>  sum |a_k| r^k diverges.
;;;       (The notes' route runs through the root test on theta_k = |a_k| r^k and
;;;       the identity lim sup (|a_k| r^k)^(1/k) = r lim sup |a_k|^(1/k); the
;;;       proof here compares |a_k| with s^k directly, which needs neither the
;;;       scaling law of lim sup nor the root of a product.)
;;;   (3) Proposition 2.7, in the notes' three cases (cps-radius-infinite,
;;;       cps-radius-zero, cps-radius-recip; together cps-radius-root).
;;;   (4) Lemma 2.8: cps-radius-unfold, cc-closed-ball-origin, cc-magnitude-power,
;;;       cc-sup-norm-bound, cps-radius-approx; cps-normally-convergent (normal
;;;       convergence on the closed ball B(0, r), r < R) and cps-abs-conv-closed-ball.
;;;   (5) cc-series-block-le, cc-series-abs-converges (an absolutely convergent
;;;       complex series converges: the tree had it only for RR), and the sum
;;;       CC-SERIES-LIMIT: cc-series-limit-converges-to, cc-series-limit-in-cc.
;;;   (6) Lemma 2.8, "in particular": cps-converges-closed-ball and
;;;       cps-uniform-closed-ball (the convergence is uniform on B(0, r)).
;;;   (7) Lemma 2.9 from the definition of the radius: rr-power-power,
;;;       cps-poly-geom-bound (k^m q^k is bounded, 0 <= q < 1),
;;;       series-scale-converges, cps-factor-conv, cps-radius-factor.
;;;   NOT here: Proposition 2.10 (see the batch-25 report for the obstacle).
;;;
;;; Helper prefix: cps- (sub-prefix cpsl-).  Theorem binders cps..._.  The free
;;; radius variable of sections (4)-(6) is cpsrad_, because CPS-RADIUS binds cpsr_.

(define (cpsl-head g) (and (pair? g) (car g)))

;;; (IN w (IMAGE phi S)) in context: open it, skolemise, return the witness x;
;;; lands (IN x S) and (= (phi x) w).  The membership is CONSUMED.
(define (cpsl-image-elim! mem)
  (let ((ex (car (dk-landed (lambda () (mac-h 'image-membership-iff mem))))))
    (dk-skolem! ex)))

;;; ======================================================================
;;; (1) (x y)^k = x^k y^k
;;; ======================================================================
(sp (make-wff
  '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN)
     (FORALL cpsx_ (IMPLIES (IN cpsx_ RR) (FORALL cpsy_ (IMPLIES (IN cpsy_ RR)
       (= (power (* cpsx_ cpsy_) cpsk_) (* (power cpsx_ cpsk_) (power cpsy_ cpsk_)))))))))))
(define cpsl-pm-br (use-induction))
(dk-focus! (cdr (assq 'base cpsl-pm-br)))
(dk-peel!)
(fact 'rr-mul-in-rr 'cpsx_ 'cpsy_)
(fact 'rr-subset-cc '(* cpsx_ cpsy_))
(fact 'rr-subset-cc 'cpsx_)
(fact 'rr-subset-cc 'cpsy_)
(mac 'power-zero)
(crs)
(dk-focus! (cdr (assq 'step cpsl-pm-br)))
(define cpsl-pm-v (cdr (assq 'var cpsl-pm-br)))
(define cpsl-pm-ih (cdr (assq 'ih cpsl-pm-br)))
(dk-peel!)
(fact 'rr-mul-in-rr 'cpsx_ 'cpsy_)
(fact 'rr-subset-cc '(* cpsx_ cpsy_))
(fact 'rr-subset-cc 'cpsx_)
(fact 'rr-subset-cc 'cpsy_)
(fact 'power-real-closed '(* cpsx_ cpsy_) cpsl-pm-v)
(fact 'power-real-closed 'cpsx_ cpsl-pm-v)
(fact 'power-real-closed 'cpsy_ cpsl-pm-v)
(mac 'power-succ)
(subst (dk-apply! cpsl-pm-ih 'cpsx_ 'cpsy_))
(crs)
(qed 'rr-power-mul-base)

;;; ======================================================================
;;; (2) The comparison of |a_k| with s^k, both ways.
;;; ======================================================================

(define cpsl-arts '(VNB-LAMBDA cpsj_ NN (rpow-star (magnitude (cf cpsj_)) (recip-star cpsj_))))
(define cpsl-rho (list 'ELIMSUP cpsl-arts))
(define cpsl-tm '(VNB-LAMBDA cpsk_ NN (* (magnitude (cf cpsk_)) (power cpsr_ cpsk_))))
(define cpsl-h1 '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (IN (f cpsk_) RR))))
(define cpsl-h2 '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (<= 0 (f cpsk_)))))

;;; beta-reduce the focus goal and close the reduct from context
(define (cpsl-beta!)
  (let ((leaf (proof-state-focus *ps*)))
    (dk-lam-b!)
    (if (not (sequent-node-grounded? leaf)) (ass))))

(define (cpsl-lt-le! a b)
  (if (not (dk-asm? (list '<= a b)))
      (have! (list '<= a b)
        (lambda () (mac-h '< (dk-ctx-form (list '< a b))) (dk-split-all!) (ass)))))

(define (cpsl-pos-of! t)
  (if (not (dk-asm? (list '< 0 t)))
      (have! (list '< 0 t) (lambda () (mac '<) (dk-conj-close! (lambda () (ass)))))))

(define (cpsl-real-of-le! x y)
  (if (not (dk-asm? (list 'IN x 'RR)))
      (begin
        (if (not (dk-asm? (list 'AND (list 'IN x 'RR-POS-STAR) (list 'IN y 'RR))))
            (have! (list 'AND (list 'IN x 'RR-POS-STAR) (list 'IN y 'RR))))
        (fact 'rr-pos-star-le-real-in-rr x y))))

;;; |a_k| and its root typed, k in NN in context
(define (cpsl-coef-typ! k)
  (let ((m (list 'magnitude (list 'cf k))) (sk (list 'recip-star k)))
    (fact 'fun-apply-type-c 'cf 'NN 'CC k)
    (fact 'cc-magnitude-closed (list 'cf k))
    (fact 'cc-magnitude-nonneg (list 'cf k))
    (fact 'nn-in-rr k)
    (fact 'recip-star-in-rr k)
    (fact 'recip-star-nn-nonneg k)
    (fact 'rpow-star-nonneg-in-rr m sk)
    (fact 'rpow-star-nonneg-nonneg m sk)))

;;; the term |a_k| r^k typed, k in NN in context (r = cpsr_ with 0 <= r)
(define (cpsl-term-typ! k)
  (let ((m (list 'magnitude (list 'cf k))) (p (list 'power 'cpsr_ k)))
    (cpsl-coef-typ! k)
    (fact 'power-real-closed 'cpsr_ k)
    (fact 'rr-power-nonneg k 'cpsr_)
    (fact 'rr-mul-in-rr m p)
    (if (not (dk-asm? (list 'AND (list 'IN m 'RR) (list 'IN p 'RR))))
        (have! (list 'AND (list 'IN m 'RR) (list 'IN p 'RR))))
    (if (not (dk-asm? (list 'AND (list '<= 0 m) (list '<= 0 p))))
        (have! (list 'AND (list '<= 0 m) (list '<= 0 p))))
    (fact 'rr-leq-mul-nonneg m p)))

(define (cpsl-arts-ptwise!)
  (have! (subst-free 'f cpsl-arts cpsl-h1)
    (lambda () (let ((k (dk-di-var!))) (cpsl-coef-typ! k) (cpsl-beta!))))
  (have! (subst-free 'f cpsl-arts cpsl-h2)
    (lambda () (let ((k (dk-di-var!))) (cpsl-coef-typ! k) (cpsl-beta!)))))

(define (cpsl-tm-typ!)
  (have! (list 'IN cpsl-tm '(FUN NN RR))
    (lambda ()
      (dk-lam-t!)
      (let ((k (dk-di-var!))) (cpsl-term-typ! k) (ass))))
  (have! (subst-free 'f cpsl-tm cpsl-h2)
    (lambda () (let ((k (dk-di-var!))) (cpsl-term-typ! k) (cpsl-beta!)))))

(define (cpsl-k-of landed)
  (cadr (car (filter (lambda (f) (and (eq? (cpsl-head f) 'IN) (equal? (caddr f) 'NN))) landed))))

;;; ---- rho < s, r s < 1  =>  sum |a_k| r^k converges -------------------------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cpss_ (list 'IMPLIES '(IN cpss_ RR) (list 'IMPLIES (list '< cpsl-rho 'cpss_)
      (list 'FORALL 'cpsr_ (list 'IMPLIES '(IN cpsr_ RR) (list 'IMPLIES '(<= 0 cpsr_)
        (list 'IMPLIES '(< (* cpsr_ cpss_) 1) (list 'SERIES-CONVERGES cpsl-tm))))))))))))
(dk-peel!)
(cpsl-arts-ptwise!)
(fact 'elimsup-in-rr-pos-star cpsl-arts)
(fact 'rr-pos-star-nonneg cpsl-rho)
(cpsl-lt-le! cpsl-rho 'cpss_)
(cpsl-real-of-le! cpsl-rho 'cpss_)
(have! '(<= 0 cpss_) (lambda () (dk-ineq! (list '<= 0 cpsl-rho) (list '<= cpsl-rho 'cpss_))))
(define cpsl-c-n (dk-skolem! (dk-fact! 'elimsup-eventually-below cpsl-arts 'cpss_)))
(define cpsl-c-ev
  (dk-pick (lambda (f) (and (eq? (cpsl-head f) 'FORALL) (dk-contains? f cpsl-c-n) (dk-contains? f 'cpss_))) "eventually below"))
(cpsl-tm-typ!)
(define cpsl-c-q '(* cpsr_ cpss_))
(fact 'rr-mul-in-rr 'cpsr_ 'cpss_)
(have! '(AND (IN cpsr_ RR) (IN cpss_ RR)))
(have! '(AND (<= 0 cpsr_) (<= 0 cpss_)))
(fact 'rr-leq-mul-nonneg 'cpsr_ 'cpss_)
(define cpsl-c-n1 (list 'succ cpsl-c-n))
(fact 'nn-succ-closed cpsl-c-n)
(fact 'nn-le-succ cpsl-c-n)
(fact 'nn-one-le-succ cpsl-c-n)
(have! '(IN 1 NN) (lambda () (arith)))
(define cpsl-c-dom
  (list 'FORALL 'cpsk_ (list 'IMPLIES '(IN cpsk_ NN) (list 'IMPLIES (list '<= cpsl-c-n1 'cpsk_)
    (list '<= (list cpsl-tm 'cpsk_) (list '* 1 (list 'power cpsl-c-q 'cpsk_)))))))
(have! cpsl-c-dom
  (lambda ()
    (let* ((k (cpsl-k-of (dk-peel!)))
           (m (list 'magnitude (list 'cf k)))
           (y (list 'rpow-star m (list 'recip-star k)))
           (rk (list 'power 'cpsr_ k))
           (sk (list 'power 'cpss_ k))
           (qk (list 'power cpsl-c-q k)))
      (fact 'nn-le-trans-guarded cpsl-c-n cpsl-c-n1 k)
      (fact 'nn-le-trans-guarded 1 cpsl-c-n1 k)
      (cpsl-term-typ! k)
      (dk-lam-b-h! (dk-deepest (lambda () (inst+ cpsl-c-ev k))))
      (fact 'power-real-closed 'cpss_ k)
      (fact 'power-real-closed cpsl-c-q k)
      (fact 'rr-power-nonneg k cpsl-c-q)
      (dk-lam-b!)
      (use-em (list '= 0 m)
        (lambda ()
          (subst (list '= m 0))
          (dk-ineq! (list '<= 0 qk)))
        (lambda ()
          (cpsl-pos-of! m)
          (fact 'rpow-star-root-power k m)
          (cpsl-lt-le! y 'cpss_)
          (fact 'power-real-closed y k)
          (fact 'rr-power-mono-base k y 'cpss_)
          (have! (list '<= m sk)
            (lambda () (dk-ineq! (list '= (list 'power y k) m) (list '<= (list 'power y k) sk))))
          (fact 'rr-mul-le-right m sk rk)
          (fact 'rr-power-mul-base k 'cpsr_ 'cpss_)
          (fact 'rr-mul-in-rr sk rk)
          (fact 'rr-mul-in-rr rk sk)
          (have! (list '= (list '* sk rk) (list '* rk sk)) (lambda () (crs)))
          (dk-ineq! (list '<= (list '* m rk) (list '* sk rk))
                    (list '= (list '* sk rk) (list '* rk sk))
                    (list '= qk (list '* rk sk))))))))
(have! '(<= 0 1) (lambda () (dk-ineq!)))
(fact 'rr-one-in)
(fact 'series-eventually-geometric-converges cpsl-tm cpsl-c-q 1 cpsl-c-n1)
(ass)
(qed 'cps-root-conv)

;;; ---- s < rho, 1 <= r s  =>  sum |a_k| r^k diverges -------------------------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cpss_ (list 'IMPLIES '(IN cpss_ RR) (list 'IMPLIES '(<= 0 cpss_) (list 'IMPLIES (list '< 'cpss_ cpsl-rho)
      (list 'FORALL 'cpsr_ (list 'IMPLIES '(IN cpsr_ RR) (list 'IMPLIES '(<= 0 cpsr_)
        (list 'IMPLIES '(<= 1 (* cpsr_ cpss_)) (list 'NOT (list 'SERIES-CONVERGES cpsl-tm))))))))))))))
(dk-peel!)
(cpsl-arts-ptwise!)
(cpsl-tm-typ!)
(define cpsl-d-q '(* cpsr_ cpss_))
(fact 'rr-mul-in-rr 'cpsr_ 'cpss_)
(fact 'rr-one-in)
(have! '(<= 0 1) (lambda () (dk-ineq!)))
(have! '(IN 1 NN) (lambda () (arith)))
(define cpsl-d-fb (dk-fact! 'elimsup-frequently-above cpsl-arts 'cpss_))
(define cpsl-d-freq
  (list 'FORALL 'cpsn_ (list 'IMPLIES '(IN cpsn_ NN)
    (list 'FORSOME 'cpsk_ (list 'AND '(IN cpsk_ NN) (list 'AND '(<= cpsn_ cpsk_) (list '<= 1 (list cpsl-tm 'cpsk_))))))))
(have! cpsl-d-freq
  (lambda ()
    (let* ((n (dk-di-var!))
           (sn (list 'succ n)))
      (fact 'nn-succ-closed n)
      (fact 'nn-le-succ n)
      (fact 'nn-one-le-succ n)
      (let* ((k (dk-skolem! (dk-deepest (lambda () (inst+ cpsl-d-fb sn)))))
             (m (list 'magnitude (list 'cf k)))
             (skr (list 'recip-star k))
             (y (list 'rpow-star m skr))
             (rk (list 'power 'cpsr_ k))
             (sk (list 'power 'cpss_ k))
             (qk (list 'power cpsl-d-q k)))
        (dk-lam-b-h! (dk-pick (lambda (f) (and (eq? (cpsl-head f) '<) (equal? (cadr f) 'cpss_) (dk-contains? f k))) "s < root"))
        (fact 'nn-le-trans-guarded n sn k)
        (fact 'nn-le-trans-guarded 1 sn k)
        (cpsl-term-typ! k)
        (ew k)
        (dk-conj-close!
          (lambda ()
            (if (dk-asm? (dk-goal))
                (ass)
                (begin
                  (dk-lam-b!)
                  (use-em (list '= 0 m)
                    (lambda ()
                      (fact 'recip-star-nn-pos k)
                      (fact 'rpow-star-zero-base skr)
                      (have! (list '= y 0) (lambda () (subst (list '= m 0)) (ass)))
                      (dk-ineq! (list '< 'cpss_ y) (list '= y 0) '(<= 0 cpss_)))
                    (lambda ()
                      (cpsl-pos-of! m)
                      (fact 'rpow-star-root-power k m)
                      (cpsl-lt-le! 'cpss_ y)
                      (fact 'power-real-closed y k)
                      (fact 'power-real-closed 'cpss_ k)
                      (fact 'power-real-closed cpsl-d-q k)
                      (fact 'power-real-closed 1 k)
                      (fact 'rr-power-mono-base k 'cpss_ y)
                      (have! (list '<= sk m)
                        (lambda () (dk-ineq! (list '= (list 'power y k) m) (list '<= sk (list 'power y k)))))
                      (fact 'rr-mul-le-right sk m rk)
                      (fact 'rr-power-mul-base k 'cpsr_ 'cpss_)
                      (fact 'rr-power-mono-base k 1 cpsl-d-q)
                      (fact 'rr-power-one k)
                      (fact 'rr-mul-in-rr sk rk)
                      (fact 'rr-mul-in-rr rk sk)
                      (have! (list '= (list '* rk sk) (list '* sk rk)) (lambda () (crs)))
                      (dk-ineq! (list '= (list 'power 1 k) 1)
                                (list '<= (list 'power 1 k) qk)
                                (list '= qk (list '* rk sk))
                                (list '= (list '* rk sk) (list '* sk rk))
                                (list '<= (list '* sk rk) (list '* m rk)))))))))))))
(fact 'rr-zero-lt-one)
(fact 'series-frequently-large-diverges cpsl-tm 1)
(ass)
(qed 'cps-root-div)

;;; ======================================================================
;;; (3) PROPOSITION 2.7.  "The radius of convergence of the power series
;;; sum_{k>=0} a_k z^k is 1 / lim sup_k |a_k|^(1/k)", with the notes' convention
;;; for the two special cases: the radius is +infinity when the lim sup is 0,
;;; and 0 when the lim sup is +infinity.  Three theorems, one per case, and
;;; their conjunction cps-radius-root.
;;; ======================================================================

;;; after (mac 'CPS-RADIUS): the SEP term S, (SUBSET S RR-POS-STAR), E = ESUP(S)
;;; typed, and the upper-bound clause; returns S
(define (cpsl-S-setup! s)
  (have! (list 'SUBSET s 'RR-POS-STAR)
    (lambda ()
      (mac 'subset-def)
      (let ((x (dk-di-var!)))
        (sep-me (list 'IN x s))
        (dk-split-all!)
        (mac 'rr-pos-star-membership)
        (oi-l)
        (dk-conj-close! (lambda () (ass))))))
  (fact 'esup-in s)
  (fact 'rr-pos-star-nonneg (list 'ESUP s))
  (dk-fact! 'esup-upper s))

;;; the condition of S at x, landed from (IN x S) without consuming it
(define (cpsl-S-elim! s x)
  (let ((c (list 'AND (list 'IN x 'RR) (list 'AND (list '<= 0 x) (list 'SERIES-CONVERGES (subst-free 'cpsr_ x cpsl-tm))))))
    (have! c (lambda () (sep-me (list 'IN x s)) (dk-split-all!) (dk-conj-close! (lambda () (ass)))))
    (dk-split-all! (list c))))

;; (cpsl-absurd! retired 2026-09-25: the kit's `dk-absurd!', of which it was the model)

;;; (IN r S) from (IN r RR), (<= 0 r) and the convergence at r in context
(define (cpsl-in-S! s r)
  (have! (list 'AND (list '<= 0 r) (list 'SERIES-CONVERGES (subst-free 'cpsr_ r cpsl-tm))))
  (have! (list 'IN r s) (lambda () (dk-close-all! (lambda () (sep-mi))))))

;;; (NOT (= t 0)) from (< 0 t) in context
(define (cpsl-ne0! t)
  (if (not (dk-asm? (list 'NOT (list '= t 0))))
      (have! (list 'NOT (list '= t 0))
        (lambda ()
          (di)
          (have! (list '< 0 0) (lambda () (dk-ineq! (list '< 0 t) (list '= t 0))))
          (fact 'rr-zero-in)
          (fact 'rr-lt-irrefl 0)
          (ai '(NOT (< 0 0)))))))

;;; w = recip(t) as a SYMBOL: from (IN t RR), (< 0 t), land (IN w RR), (< 0 w),
;;; (<= 0 w), (= (* t w) 1); returns w
(define (cpsl-recip! t)
  (cpsl-ne0! t)
  (let ((ex (list 'FORSOME 'cpsw_ (list 'AND '(IN cpsw_ RR) (list 'AND '(< 0 cpsw_) (list '= (list '* t 'cpsw_) 1))))))
    (have! ex
      (lambda ()
        (if (not (dk-asm? (list 'AND (list 'IN t 'RR) (list 'NOT (list '= t 0)))))
            (have! (list 'AND (list 'IN t 'RR) (list 'NOT (list '= t 0)))))
        (fact 'rr-recip-closed t)
        (fact 'rr-recip-pos t)
        (fact 'rr-recip-inverse t)
        (ew (list 'recip t))
        (dk-conj-close! (lambda () (ass)))))
    (let ((w (dk-skolem! ex)))
      (cpsl-lt-le! 0 w)
      w)))

;;; close the focus goal (< s POS-INF) for a real s in context
(define (cpsl-lt-inf-close! s)
  (fact 'rr-subset-rr-star)
  (fact 'subset-mem-fwd 'RR 'RR-STAR s)
  (fact 'pos-inf-upper-bound s)
  (fact 'pos-inf-not-in-rr)
  (mac '<)
  (dk-conj-close!
    (lambda ()
      (if (eq? (cpsl-head (dk-goal)) 'NOT)
          (begin
            (di)
            (have! '(IN POS-INF RR) (lambda () (subst (list '= 'POS-INF s)) (ass)))
            (ai '(NOT (IN POS-INF RR))))
          (ass)))))

;;; a real t as a SYMBOL: `dk-name!' (driver-kit.scm; this file's cpsl-name! retired, batch 40)

;;; for r >= 0 there is s > 0 with r s < 1
(sp (make-wff
  '(FORALL cpsr_ (IMPLIES (IN cpsr_ RR) (IMPLIES (<= 0 cpsr_)
     (FORSOME cpss_ (AND (IN cpss_ RR) (AND (< 0 cpss_) (< (* cpsr_ cpss_) 1)))))))))
(dk-peel!)
(fact 'rr-one-in)
(fact 'rr-add-in-rr 'cpsr_ 1)
(define cpsl-sf-t (dk-name! '(+ cpsr_ 1)))
(have! (list '< 0 cpsl-sf-t) (lambda () (dk-ineq! (list '= cpsl-sf-t '(+ cpsr_ 1)) '(<= 0 cpsr_))))
(define cpsl-sf-w (cpsl-recip! cpsl-sf-t))
(fact 'rr-mul-in-rr 'cpsr_ cpsl-sf-w)
(fact 'rr-mul-in-rr cpsl-sf-t cpsl-sf-w)
(have! (list '= (list '* cpsl-sf-t cpsl-sf-w) (list '+ (list '* 'cpsr_ cpsl-sf-w) cpsl-sf-w))
  (lambda () (subst (list '= cpsl-sf-t '(+ cpsr_ 1))) (crs)))
(ew cpsl-sf-w)
(dk-conj-close!
  (lambda ()
    (if (eq? (cpsl-head (dk-goal)) '<)
        (if (dk-asm? (dk-goal))
            (ass)
            (dk-ineq! (list '= (list '* cpsl-sf-t cpsl-sf-w) 1)
                      (list '= (list '* cpsl-sf-t cpsl-sf-w) (list '+ (list '* 'cpsr_ cpsl-sf-w) cpsl-sf-w))
                      (list '< 0 cpsl-sf-w)))
        (ass))))
(qed 'cps-small-factor)

;;; ---- lim sup = 0  =>  radius = +inf ---------------------------------------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'IMPLIES (list '= cpsl-rho 0) '(= (CPS-RADIUS cf) POS-INF))))))
(dk-peel!)
(mac 'CPS-RADIUS)
(define cpsl-a-s (cadr (cadr (dk-goal))))
(define cpsl-a-e (list 'ESUP cpsl-a-s))
(define cpsl-a-up (cpsl-S-setup! cpsl-a-s))
(define cpsl-a-notex (car (filter (dk-head? 'NOT) (dk-landed (lambda () (pbc))))))
(define cpsl-a-c1 (list 'AND (list 'IN cpsl-a-e 'RR) (list '<= 0 cpsl-a-e)))
(define cpsl-a-dj
  (dk-project! (list 'OR cpsl-a-c1 (list '= cpsl-a-e 'POS-INF)) 'rr-pos-star-membership (list 'IN cpsl-a-e 'RR-POS-STAR)))
(use-cases cpsl-a-dj
  (lambda ()
    (dk-split! (dk-ctx-form cpsl-a-c1))
    (let ((r (list '+ cpsl-a-e 1)))
      (fact 'rr-one-in)
      (fact 'rr-add-in-rr cpsl-a-e 1)
      (have! (list '<= 0 r) (lambda () (dk-ineq! (list '<= 0 cpsl-a-e))))
      (let ((s (dk-skolem! (dk-fact! 'cps-small-factor r))))
        (have! (list '< cpsl-rho s) (lambda () (subst (list '= cpsl-rho 0)) (ass)))
        (fact 'cps-root-conv 'cf s r)
        (cpsl-in-S! cpsl-a-s r)
        (inst+ cpsl-a-up r)
        (have! (list '< cpsl-a-e r) (lambda () (dk-ineq!)))
        (fact 'rr-lt-not-le cpsl-a-e r)
        (ai (list 'NOT (list '<= r cpsl-a-e))))))
  (lambda () (ai cpsl-a-notex)))
(qed 'cps-radius-infinite)

;;; ---- lim sup = +inf  =>  radius = 0 ---------------------------------------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'IMPLIES (list '= cpsl-rho 'POS-INF) '(= (CPS-RADIUS cf) 0))))))
(dk-peel!)
(mac 'CPS-RADIUS)
(define cpsl-b-s (cadr (cadr (dk-goal))))
(define cpsl-b-e (list 'ESUP cpsl-b-s))
(define cpsl-b-up (cpsl-S-setup! cpsl-b-s))
(fact 'rr-zero-in)
(have! '(<= 0 0) (lambda () (dk-ineq!)))
(have! (list '<= cpsl-b-e 0)
  (lambda ()
    (have! (list 'AND '(IN 0 RR-POS-STAR) (list 'FORALL 'cpsx_ (list 'IMPLIES (list 'IN 'cpsx_ cpsl-b-s) '(<= cpsx_ 0))))
      (lambda ()
        (dk-conj-close!
          (lambda ()
            (if (eq? (cpsl-head (dk-goal)) 'FORALL)
                (let ((x (dk-di-var!)))
                  (cpsl-S-elim! cpsl-b-s x)
                  (pbc)
                  (fact 'rr-not-le-lt x 0)
                  (let ((w (cpsl-recip! x)))
                    (have! (list '< w cpsl-rho)
                      (lambda () (subst (list '= cpsl-rho 'POS-INF)) (cpsl-lt-inf-close! w)))
                    (fact 'rr-mul-in-rr x w)
                    (have! (list '<= 1 (list '* x w)) (lambda () (dk-ineq! (list '= (list '* x w) 1))))
                    (fact 'cps-root-div 'cf w x)
                    (ai (list 'NOT (list 'SERIES-CONVERGES (subst-free 'cpsr_ x cpsl-tm))))))
                (begin (mac 'rr-pos-star-membership) (oi-l) (dk-conj-close! (lambda () (ass)))))))))
    (fact 'esup-least cpsl-b-s 0)
    (ass)))
(cpsl-real-of-le! cpsl-b-e 0)
(have! (list 'AND (list 'IN cpsl-b-e 'RR) '(IN 0 RR)))
(have! (list 'AND (list '<= cpsl-b-e 0) (list '<= 0 cpsl-b-e)))
(fact 'rr-leq-antisymmetric cpsl-b-e 0)
(ass)
(qed 'cps-radius-zero)

;;; ---- 0 < lim sup < +inf  =>  radius = 1 / lim sup ---------------------------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'IMPLIES (list 'IN cpsl-rho 'RR) (list 'IMPLIES (list '< 0 cpsl-rho)
      (list '= '(CPS-RADIUS cf) (list 'recip cpsl-rho))))))))
(dk-peel!)
(define cpsl-c-u (list 'recip cpsl-rho))
(cpsl-ne0! cpsl-rho)
(have! (list 'AND (list 'IN cpsl-rho 'RR) (list 'NOT (list '= cpsl-rho 0))))
(fact 'rr-recip-closed cpsl-rho)
(fact 'rr-recip-pos cpsl-rho)
(fact 'rr-recip-inverse cpsl-rho)
(cpsl-lt-le! 0 cpsl-c-u)
(fact 'rr-mul-in-rr cpsl-rho cpsl-c-u)
(mac 'CPS-RADIUS)
(define cpsl-c-s (cadr (cadr (dk-goal))))
(define cpsl-c-e (list 'ESUP cpsl-c-s))
(define cpsl-c-up (cpsl-S-setup! cpsl-c-s))
(have! (list '<= cpsl-c-e cpsl-c-u)
  (lambda ()
    (have! (list 'AND (list 'IN cpsl-c-u 'RR-POS-STAR)
                 (list 'FORALL 'cpsx_ (list 'IMPLIES (list 'IN 'cpsx_ cpsl-c-s) (list '<= 'cpsx_ cpsl-c-u))))
      (lambda ()
        (dk-conj-close!
          (lambda ()
            (if (eq? (cpsl-head (dk-goal)) 'FORALL)
                (let ((x (dk-di-var!)))
                  (cpsl-S-elim! cpsl-c-s x)
                  (pbc)
                  (fact 'rr-not-le-lt x cpsl-c-u)
                  (have! (list '< 0 x) (lambda () (dk-ineq! (list '< cpsl-c-u x) (list '<= 0 cpsl-c-u))))
                  (let* ((w (cpsl-recip! x))
                         (rx (list '* cpsl-rho x))
                         (wx (list '* w x))
                         (xw (list '* x w))
                         (ru (list '* cpsl-rho cpsl-c-u))
                         ;; rho <= w is absurd: rho x <= w x = 1 < rho x
                         (contra! (lambda ()
                                    (fact 'rr-mul-le-right cpsl-rho w x)
                                    (dk-absurd! (list '<= rx wx) (list '= wx xw) (list '= xw 1)
                                              (list '< ru rx) (list '= ru 1)))))
                    (fact 'rr-mul-in-rr cpsl-rho x)
                    (fact 'rr-mul-in-rr w x)
                    (fact 'rr-mul-in-rr x w)
                    (have! (list '= wx xw) (lambda () (crs)))
                    (have! (list 'AND (list '< 0 cpsl-rho) (list '< cpsl-c-u x)))
                    (fact 'rr-lt-scale-pos cpsl-rho cpsl-c-u x)
                    (have! (list '< w cpsl-rho)
                      (lambda ()
                        (mac '<)
                        (dk-conj-close!
                          (lambda ()
                            (if (eq? (cpsl-head (dk-goal)) 'NOT)
                                (begin (di)
                                       (have! (list '<= cpsl-rho w) (lambda () (dk-ineq! (list '= w cpsl-rho))))
                                       (contra!))
                                (begin
                                  (have! (list 'AND (list 'IN w 'RR) (list 'IN cpsl-rho 'RR)))
                                  (fact 'rr-leq-total w cpsl-rho)
                                  (use-cases (list (list '<= w cpsl-rho) (list '<= cpsl-rho w))
                                    (lambda () (ass))
                                    (lambda () (contra!)))))))))
                    (have! (list '<= 1 xw) (lambda () (dk-ineq! (list '= xw 1))))
                    (fact 'cps-root-div 'cf w x)
                    (ai (list 'NOT (list 'SERIES-CONVERGES (subst-free 'cpsr_ x cpsl-tm))))))
                (begin (mac 'rr-pos-star-membership) (oi-l) (dk-conj-close! (lambda () (ass)))))))))
    (fact 'esup-least cpsl-c-s cpsl-c-u)
    (ass)))
(cpsl-real-of-le! cpsl-c-e cpsl-c-u)
(have! (list '<= cpsl-c-u cpsl-c-e)
  (lambda ()
    (pbc)
    (fact 'rr-not-le-lt cpsl-c-u cpsl-c-e)
    (fact 'rr-add-in-rr cpsl-c-e cpsl-c-u)
    (have! '(IN 1/2 RR) (lambda () (arith)))
    (fact 'rr-mul-in-rr 1/2 (list '+ cpsl-c-e cpsl-c-u))
    (let ((r (dk-name! (list '* 1/2 (list '+ cpsl-c-e cpsl-c-u)))))
      (have! (list '< cpsl-c-e r) (lambda () (dk-ineq! (list '= r (list '* 1/2 (list '+ cpsl-c-e cpsl-c-u))) (list '< cpsl-c-e cpsl-c-u))))
      (have! (list '< r cpsl-c-u) (lambda () (dk-ineq! (list '= r (list '* 1/2 (list '+ cpsl-c-e cpsl-c-u))) (list '< cpsl-c-e cpsl-c-u))))
      (have! (list '< 0 r) (lambda () (dk-ineq! (list '< cpsl-c-e r) (list '<= 0 cpsl-c-e))))
      (cpsl-lt-le! 0 r)
      (let* ((w (cpsl-recip! r))
             (rr- (list '* cpsl-rho r))
             (wr (list '* w r))
             (rw (list '* r w))
             (ru (list '* cpsl-rho cpsl-c-u))
             ;; w <= rho is absurd: 1 = r w = w r <= rho r < rho u = 1
             (contra! (lambda ()
                        (fact 'rr-mul-le-right w cpsl-rho r)
                        (dk-absurd! (list '<= wr rr-) (list '= wr rw) (list '= rw 1) (list '< rr- ru) (list '= ru 1)))))
        (fact 'rr-mul-in-rr cpsl-rho r)
        (fact 'rr-mul-in-rr w r)
        (fact 'rr-mul-in-rr r w)
        (have! (list '= wr rw) (lambda () (crs)))
        (have! (list 'AND (list '< 0 cpsl-rho) (list '< r cpsl-c-u)))
        (fact 'rr-lt-scale-pos cpsl-rho r cpsl-c-u)
        (have! (list '< cpsl-rho w)
          (lambda ()
            (mac '<)
            (dk-conj-close!
              (lambda ()
                (if (eq? (cpsl-head (dk-goal)) 'NOT)
                    (begin (di)
                           (have! (list '<= w cpsl-rho) (lambda () (dk-ineq! (list '= cpsl-rho w))))
                           (contra!))
                    (begin
                      (have! (list 'AND (list 'IN cpsl-rho 'RR) (list 'IN w 'RR)))
                      (fact 'rr-leq-total cpsl-rho w)
                      (use-cases (list (list '<= cpsl-rho w) (list '<= w cpsl-rho))
                        (lambda () (ass))
                        (lambda () (contra!)))))))))
        (fact 'rr-add-in-rr cpsl-rho w)
        (fact 'rr-mul-in-rr 1/2 (list '+ cpsl-rho w))
        (let* ((s (dk-name! (list '* 1/2 (list '+ cpsl-rho w))))
               (rs (list '* r s)))
          (fact 'rr-mul-in-rr r s)
          (have! (list '= rs (list '+ (list '* 1/2 rr-) (list '* 1/2 rw)))
            (lambda () (subst (list '= s (list '* 1/2 (list '+ cpsl-rho w)))) (crs)))
          (have! (list '< rs 1)
            (lambda () (dk-ineq! (list '= rs (list '+ (list '* 1/2 rr-) (list '* 1/2 rw)))
                                 (list '< rr- ru) (list '= ru 1) (list '= rw 1))))
          (have! (list '< cpsl-rho s)
            (lambda () (dk-ineq! (list '= s (list '* 1/2 (list '+ cpsl-rho w))) (list '< cpsl-rho w))))
          (fact 'cps-root-conv 'cf s r)
          (cpsl-in-S! cpsl-c-s r)
          (inst+ cpsl-c-up r)
          (fact 'rr-lt-not-le cpsl-c-e r)
          (ai (list 'NOT (list '<= r cpsl-c-e))))))))
(have! (list 'AND (list 'IN cpsl-c-e 'RR) (list 'IN cpsl-c-u 'RR)))
(have! (list 'AND (list '<= cpsl-c-e cpsl-c-u) (list '<= cpsl-c-u cpsl-c-e)))
(fact 'rr-leq-antisymmetric cpsl-c-e cpsl-c-u)
(ass)
(qed 'cps-radius-recip)

;;; ---- Proposition 2.7, the three cases together ----------------------------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'AND (list 'IMPLIES (list '= cpsl-rho 0) '(= (CPS-RADIUS cf) POS-INF))
      (list 'AND (list 'IMPLIES (list '= cpsl-rho 'POS-INF) '(= (CPS-RADIUS cf) 0))
        (list 'IMPLIES (list 'IN cpsl-rho 'RR) (list 'IMPLIES (list '< 0 cpsl-rho)
          (list '= '(CPS-RADIUS cf) (list 'recip cpsl-rho))))))))))
(dk-peel!)
(dk-conj-close!
  (lambda ()
    (let* ((g (dk-goal))
           (thm (cond ((equal? (cadr g) (list '= cpsl-rho 0)) 'cps-radius-infinite)
                      ((equal? (cadr g) (list '= cpsl-rho 'POS-INF)) 'cps-radius-zero)
                      (#t 'cps-radius-recip))))
      (dk-peel!)
      (fact thm 'cf)
      (ass))))
(qed 'cps-radius-root)

;;; ======================================================================
;;; (4) LEMMA 2.8: normal convergence in the closed ball B(0, r), r < R, and
;;; absolute convergence at each point of it.
;;; ======================================================================

(define cpsl-S-body
  '(SEP cpsr_ RR (AND (<= 0 cpsr_)
     (SERIES-CONVERGES (VNB-LAMBDA cpsk_ NN (* (magnitude (cf cpsk_)) (power cpsr_ cpsk_)))))))

;;; the unfold of CPS-RADIUS as a THEOREM, so that mac-h can open a hypothesis
(sp (make-wff (list 'FORALL 'cf (list '== '(CPS-RADIUS cf) (list 'ESUP cpsl-S-body)))))
(di)
(mac 'CPS-RADIUS)
(qrfl)
(qed 'cps-radius-unfold)

;;; a point of the closed ball B(0, r) of CC is a complex number of modulus <= r
(sp (make-wff
  '(FORALL cpsrad_ (FORALL cpsz_ (IMPLIES (IN cpsz_ (CLOSED-BALL CC-MS 0 cpsrad_))
     (AND (IN cpsz_ CC) (<= (magnitude cpsz_) cpsrad_)))))))
(dk-peel!)
(define cpsl-cb-mem '(IN cpsz_ (CLOSED-BALL CC-MS 0 cpsrad_)))
(dk-split! (car (dk-landed (lambda () (mac-h 'closed-ball-membership cpsl-cb-mem)))))
(slot-h 'PTS '(IN cpsz_ (PTS CC-MS)))
(fact 'cc-zero-in)
(define cpsl-cb-d (dk-fact! 'cc-ms-dist 0 'cpsz_))
(have! '(<= (magnitude (- 0 cpsz_)) cpsrad_)
  (lambda () (subst (list '= (caddr cpsl-cb-d) (cadr cpsl-cb-d))) (ass)))
(have! '(= (- 0 cpsz_) (- cpsz_)) (lambda () (crs)))
(fact 'cc-magnitude-neg 'cpsz_)
(have! '(<= (magnitude cpsz_) cpsrad_)
  (lambda ()
    (subst '(= (magnitude cpsz_) (magnitude (- cpsz_))))
    (subst '(= (- cpsz_) (- 0 cpsz_)))
    (ass)))
(dk-conj-close! (lambda () (ass)))
(qed 'cc-closed-ball-origin)

;;; |z^k| = |z|^k
(sp (make-wff
  '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN)
     (FORALL cpsz_ (IMPLIES (IN cpsz_ CC) (= (magnitude (power cpsz_ cpsk_)) (power (magnitude cpsz_) cpsk_))))))))
(define cpsl-mp-br (use-induction))
(dk-focus! (cdr (assq 'base cpsl-mp-br)))
(dk-peel!)
(fact 'cc-magnitude-closed 'cpsz_)
(fact 'rr-subset-cc '(magnitude cpsz_))
(mac 'power-zero)
(fact 'rr-one-in)
(have! '(<= 0 1) (lambda () (dk-ineq!)))
(subst (dk-fact! 'rr-magnitude-is-abs 1))
(subst (dk-fact! 'rr-abs-of-nonneg 1))
(rfl)
(dk-focus! (cdr (assq 'step cpsl-mp-br)))
(define cpsl-mp-v (cdr (assq 'var cpsl-mp-br)))
(define cpsl-mp-ih (cdr (assq 'ih cpsl-mp-br)))
(dk-peel!)
(have! (list 'AND '(IN cpsz_ CC) (list 'IN cpsl-mp-v 'NN)))
(fact 'power-typing-nonneg 'cpsz_ cpsl-mp-v)
(fact 'cc-magnitude-closed 'cpsz_)
(fact 'cc-magnitude-closed (list 'power 'cpsz_ cpsl-mp-v))
(fact 'rr-subset-cc '(magnitude cpsz_))
(fact 'power-real-closed '(magnitude cpsz_) cpsl-mp-v)
(mac 'power-succ)
(have! (list 'AND '(IN cpsz_ CC) (list 'IN (list 'power 'cpsz_ cpsl-mp-v) 'CC)))
(subst (dk-fact! 'cc-magnitude-mul 'cpsz_ (list 'power 'cpsz_ cpsl-mp-v)))
(subst (dk-apply! cpsl-mp-ih 'cpsz_))
(rfl)
(qed 'cc-magnitude-power)

;;; the supremum norm of a function bounded by M is a real in [0, M]
(define cpsl-sn-im '(IMAGE (VNB-LAMBDA cpsx_ cpsxs_ (magnitude (u cpsx_))) cpsxs_))
(define cpsl-sn-n '(CC-SUP-NORM u cpsxs_))
(define cpsl-sn-typ '(FORALL cpsx_ (IMPLIES (IN cpsx_ cpsxs_) (IN (u cpsx_) CC))))
(define cpsl-sn-bd '(FORALL cpsx_ (IMPLIES (IN cpsx_ cpsxs_) (<= (magnitude (u cpsx_)) cpsm_))))
(sp (make-wff
  (list 'FORALL 'u (list 'FORALL 'cpsxs_ (list 'FORALL 'cpsm_ (list 'IMPLIES '(IN cpsm_ RR) (list 'IMPLIES '(<= 0 cpsm_)
    (list 'IMPLIES cpsl-sn-typ (list 'IMPLIES cpsl-sn-bd
      (list 'AND (list 'IN cpsl-sn-n 'RR) (list 'AND (list '<= 0 cpsl-sn-n) (list '<= cpsl-sn-n 'cpsm_))))))))))))
(dk-peel!)
;;; an element w of the image: its preimage x, (IN x X), w = |u(x)| (beta-reduced)
(define (cpsl-sn-elim! w)
  (let ((x (cpsl-image-elim! (dk-pick (lambda (f) (and (eq? (cpsl-head f) 'IN) (eq? (cadr f) w))) "image membership"))))
    (dk-lam-b-h! (dk-pick (lambda (f) (and (eq? (cpsl-head f) '=) (eq? (caddr f) w))) "value equation"))
    (inst+ cpsl-sn-typ x)
    (fact 'cc-magnitude-closed (list 'u x))
    (fact 'cc-magnitude-nonneg (list 'u x))
    (subst (list '= w (list 'magnitude (list 'u x))))
    x))
(define (cpsl-sn-subset!)
  (have! (list 'SUBSET cpsl-sn-im 'RR-POS-STAR)
    (lambda ()
      (mac 'subset-def)
      (let ((w (dk-di-var!)))
        (cpsl-sn-elim! w)
        (mac 'rr-pos-star-membership) (oi-l) (dk-conj-close! (lambda () (ass)))))))
(have! (list 'IN cpsl-sn-n 'RR-POS-STAR)
  (lambda () (mac 'CC-SUP-NORM) (cpsl-sn-subset!) (fact 'esup-in cpsl-sn-im) (ass)))
(have! (list '<= cpsl-sn-n 'cpsm_)
  (lambda ()
    (mac 'CC-SUP-NORM)
    (cpsl-sn-subset!)
    (have! (list 'AND '(IN cpsm_ RR-POS-STAR) (list 'FORALL 'cpsw_ (list 'IMPLIES (list 'IN 'cpsw_ cpsl-sn-im) '(<= cpsw_ cpsm_))))
      (lambda ()
        (dk-conj-close!
          (lambda ()
            (if (eq? (cpsl-head (dk-goal)) 'FORALL)
                (let* ((w (dk-di-var!)) (x (cpsl-sn-elim! w)))
                  (inst+ cpsl-sn-bd x)
                  (ass))
                (begin (mac 'rr-pos-star-membership) (oi-l) (dk-conj-close! (lambda () (ass)))))))))
    (fact 'esup-least cpsl-sn-im 'cpsm_)
    (ass)))
(cpsl-real-of-le! cpsl-sn-n 'cpsm_)
(fact 'rr-pos-star-nonneg cpsl-sn-n)
(dk-conj-close! (lambda () (ass)))
(qed 'cc-sup-norm-bound)

;;; the term k |-> |a_k| r^k at a given r, and its typings
(define (cpsl-tm-of r) (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* '(magnitude (cf cpsk_)) (list 'power r 'cpsk_))))
(define (cpsl-term-typ-r! k r)
  (let ((m (list 'magnitude (list 'cf k))) (p (list 'power r k)))
    (cpsl-coef-typ! k)
    (fact 'power-real-closed r k)
    (fact 'rr-power-nonneg k r)
    (fact 'rr-mul-in-rr m p)
    (if (not (dk-asm? (list 'AND (list 'IN m 'RR) (list 'IN p 'RR))))
        (have! (list 'AND (list 'IN m 'RR) (list 'IN p 'RR))))
    (if (not (dk-asm? (list 'AND (list '<= 0 m) (list '<= 0 p))))
        (have! (list 'AND (list '<= 0 m) (list '<= 0 p))))
    (fact 'rr-leq-mul-nonneg m p)))
(define (cpsl-tm-typ-r! r)
  (have! (list 'IN (cpsl-tm-of r) '(FUN NN RR))
    (lambda ()
      (dk-lam-t!)
      (let ((k (dk-di-var!))) (cpsl-term-typ-r! k r) (ass)))))

;;; ---- r < R  =>  some t > r has sum |a_k| t^k < inf  (the sup is approached) --
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cpsrad_ (list 'IMPLIES '(IN cpsrad_ RR) (list 'IMPLIES '(<= 0 cpsrad_)
      (list 'IMPLIES '(< cpsrad_ (CPS-RADIUS cf))
        (list 'FORSOME 'cpst_ (list 'AND '(IN cpst_ RR)
          (list 'AND '(< cpsrad_ cpst_) (list 'SERIES-CONVERGES (cpsl-tm-of 'cpst_)))))))))))))
(dk-peel!)
(define cpsl-e-e (list 'ESUP cpsl-S-body))
(have! (list '< 'cpsrad_ cpsl-e-e)
  (lambda () (mac-h 'cps-radius-unfold '(< cpsrad_ (CPS-RADIUS cf))) (ass)))
(define cpsl-e-up (cpsl-S-setup! cpsl-S-body))
(define cpsl-e-notex (car (filter (dk-head? 'NOT) (dk-landed (lambda () (pbc))))))
(have! (list '<= cpsl-e-e 'cpsrad_)
  (lambda ()
    (have! (list 'AND '(IN cpsrad_ RR-POS-STAR)
                 (list 'FORALL 'cpsx_ (list 'IMPLIES (list 'IN 'cpsx_ cpsl-S-body) '(<= cpsx_ cpsrad_))))
      (lambda ()
        (dk-conj-close!
          (lambda ()
            (if (eq? (cpsl-head (dk-goal)) 'FORALL)
                (let ((x (dk-di-var!)))
                  (cpsl-S-elim! cpsl-S-body x)
                  (pbc)
                  (fact 'rr-not-le-lt x 'cpsrad_)
                  (have! (cadr cpsl-e-notex) (lambda () (ew x) (dk-conj-close! (lambda () (ass)))))
                  (ai cpsl-e-notex))
                (begin (mac 'rr-pos-star-membership) (oi-l) (dk-conj-close! (lambda () (ass)))))))))
    (fact 'esup-least cpsl-S-body 'cpsrad_)
    (ass)))
(cpsl-lt-le! 'cpsrad_ cpsl-e-e)
(cpsl-real-of-le! cpsl-e-e 'cpsrad_)
(fact 'rr-lt-not-le 'cpsrad_ cpsl-e-e)
(ai (list 'NOT (list '<= cpsl-e-e 'cpsrad_)))
(qed 'cps-radius-approx)

;;; ---- the power series terms as functions on B(0, r) ------------------------
(define cpsl-b '(CLOSED-BALL CC-MS 0 cpsrad_))
(define (cpsl-u k) (list 'VNB-LAMBDA 'cpsz_ cpsl-b (list '* (list 'cf k) (list 'power 'cpsz_ k))))
(define cpsl-ufam (list 'VNB-LAMBDA 'cpsk_ 'NN (cpsl-u 'cpsk_)))

;;; after the peel of a statement with cf, r, 0 <= r, r < R: sum |a_k| r^k converges
(define (cpsl-conv-r!)
  (let* ((t (dk-skolem! (dk-fact! 'cps-radius-approx 'cf 'cpsrad_)))
         (tmr (cpsl-tm-of 'cpsrad_))
         (tmt (cpsl-tm-of t)))
    (cpsl-lt-le! 'cpsrad_ t)
    (have! (list '<= 0 t) (lambda () (dk-ineq! '(<= 0 cpsrad_) (list '< 'cpsrad_ t))))
    (cpsl-tm-typ-r! 'cpsrad_)
    (cpsl-tm-typ-r! t)
    (detach-with! (dk-fact! 'comparison-test tmr tmt)
      (lambda ()
        (dk-conj-close!
          (lambda ()
            (if (eq? (cpsl-head (dk-goal)) 'FORALL)
                (let* ((n (dk-di-var!))
                       (m (list 'magnitude (list 'cf n)))
                       (rn (list 'power 'cpsrad_ n))
                       (tn (list 'power t n)))
                  (cpsl-term-typ-r! n 'cpsrad_)
                  (cpsl-term-typ-r! n t)
                  (fact 'rr-power-mono-base n 'cpsrad_ t)
                  (have! (list 'AND (list '<= 0 m) (list '<= rn tn)))
                  (fact 'rr-le-scale-nonneg m rn tn)
                  (dk-lam-b!)
                  (dk-conj-close! (lambda () (ass))))
                (ass))))))))

;;; x in B(0, r) and k typed: |a_k x^k| <= |a_k| r^k and a_k x^k in CC, with the
;;; equations that read |a_k x^k| as |a_k| |x|^k
(define (cpsl-pt! k x)
  (let* ((m (list 'magnitude (list 'cf k)))
         (xk (list 'power x k))
         (mx (list 'magnitude x))
         (mxk (list 'power mx k))
         (rk (list 'power 'cpsrad_ k))
         (ax (list '* (list 'cf k) xk)))
    (if (not (and (dk-asm? (list 'IN x 'CC)) (dk-asm? (list '<= mx 'cpsrad_))))
        (dk-split! (dk-fact! 'cc-closed-ball-origin 'cpsrad_ x)))
    (cpsl-term-typ-r! k 'cpsrad_)
    (if (not (dk-asm? (list 'AND (list 'IN x 'CC) (list 'IN k 'NN))))
        (have! (list 'AND (list 'IN x 'CC) (list 'IN k 'NN))))
    (fact 'power-typing-nonneg x k)
    (if (not (dk-asm? (list 'AND (list 'IN (list 'cf k) 'CC) (list 'IN xk 'CC))))
        (have! (list 'AND (list 'IN (list 'cf k) 'CC) (list 'IN xk 'CC))))
    (fact 'cc-mul-closed (list 'cf k) xk)
    (fact 'cc-magnitude-closed ax)
    (fact 'cc-magnitude-nonneg ax)
    (fact 'cc-magnitude-mul (list 'cf k) xk)
    (fact 'cc-magnitude-power k x)
    (fact 'cc-magnitude-closed x)
    (fact 'cc-magnitude-nonneg x)
    (fact 'power-real-closed mx k)
    (fact 'rr-power-mono-base k mx 'cpsrad_)
    (if (not (dk-asm? (list 'AND (list '<= 0 m) (list '<= mxk rk))))
        (have! (list 'AND (list '<= 0 m) (list '<= mxk rk))))
    (fact 'rr-le-scale-nonneg m mxk rk)
    (fact 'rr-mul-in-rr m mxk)
    (if (not (dk-asm? (list '<= (list 'magnitude ax) (list '* m rk))))
        (have! (list '<= (list 'magnitude ax) (list '* m rk))
          (lambda ()
            (subst (list '= (list 'magnitude ax) (list '* m (list 'magnitude xk))))
            (subst (list '= (list 'magnitude xk) mxk))
            (ass))))))

;;; the supremum norm of the k-th term on B(0, r): a real in [0, |a_k| r^k]
(define (cpsl-core! k)
  (if (not (dk-asm? (list 'IN cpsl-b 'SET)))
      (begin (fact 'cc-is-metric-space)
             (fact 'closed-ball-is-set 'CC-MS 0 'cpsrad_)))
  (let* ((m (list 'magnitude (list 'cf k)))
         (mm (list '* m (list 'power 'cpsrad_ k)))
         (ch (dk-fact! 'cc-sup-norm-bound (cpsl-u k) cpsl-b mm)))
    (let* ((ch2 (detach-with! ch
                  (lambda ()
                    (let ((x (dk-di-var!)))
                      (cpsl-pt! k x)
                      (cpsl-beta!)))))
           (res (detach-with! ch2
                  (lambda ()
                    (let ((x (dk-di-var!)))
                      (cpsl-pt! k x)
                      (cpsl-beta!))))))
      (dk-split-all! (list res)))))

;; (cpsl-lam-t! retired 2026-09-25: the kit's `dk-lam-type!')

;;; ---- LEMMA 2.8 --------------------------------------------------------------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cpsrad_ (list 'IMPLIES '(IN cpsrad_ RR) (list 'IMPLIES '(<= 0 cpsrad_)
      (list 'IMPLIES '(< cpsrad_ (CPS-RADIUS cf))
        (list 'IS-NORMALLY-CONVERGENT cpsl-ufam cpsl-b)))))))))
(dk-peel!)
(cpsl-conv-r!)
(define cpsl-f-ptw
  (list 'FORALL 'cpsi_ (list 'IMPLIES '(IN cpsi_ NN)
    (list 'IN (list 'CC-SUP-NORM (list cpsl-ufam 'cpsi_) cpsl-b) 'RR))))
(have! cpsl-f-ptw
  (lambda ()
    (let ((i (dk-di-var!)))
      (cpsl-term-typ-r! i 'cpsrad_)
      (cpsl-core! i)
      (cpsl-beta!))))
(mac 'IS-NORMALLY-CONVERGENT)
(dk-conj-close!
  (lambda ()
    (if (eq? (cpsl-head (dk-goal)) 'FORALL)
        (ass)
        (let ((snf (cadr (dk-goal))))
          (have! (list 'IN snf '(FUN NN RR))
            (lambda () (dk-lam-type! (lambda () (ass)))))
          (detach-with! (dk-fact! 'comparison-test snf (cpsl-tm-of 'cpsrad_))
            (lambda ()
              (dk-conj-close!
                (lambda ()
                  (if (eq? (cpsl-head (dk-goal)) 'FORALL)
                      (let ((n (dk-di-var!)))
                        (cpsl-term-typ-r! n 'cpsrad_)
                        (cpsl-core! n)
                        (dk-lam-b!)
                        (dk-conj-close! (lambda () (ass))))
                      (ass))))))
          (ass)))))
(qed 'cps-normally-convergent)

;;; ---- ... and the series converges absolutely at each point of B(0, r) ------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cpsrad_ (list 'IMPLIES '(IN cpsrad_ RR) (list 'IMPLIES '(<= 0 cpsrad_)
      (list 'IMPLIES '(< cpsrad_ (CPS-RADIUS cf))
        (list 'FORALL 'cpsz_ (list 'IMPLIES (list 'IN 'cpsz_ cpsl-b)
          '(SERIES-CONVERGES (VNB-LAMBDA cpsk_ NN (magnitude (* (cf cpsk_) (power cpsz_ cpsk_)))))))))))))))
(dk-peel!)
(cpsl-conv-r!)
(define cpsl-g-az '(VNB-LAMBDA cpsk_ NN (magnitude (* (cf cpsk_) (power cpsz_ cpsk_)))))
(have! (list 'IN cpsl-g-az '(FUN NN RR))
  (lambda ()
    (dk-lam-t!)
    (let ((k (dk-di-var!))) (cpsl-pt! k 'cpsz_) (ass))))
(detach-with! (dk-fact! 'comparison-test cpsl-g-az (cpsl-tm-of 'cpsrad_))
  (lambda ()
    (dk-conj-close!
      (lambda ()
        (if (eq? (cpsl-head (dk-goal)) 'FORALL)
            (let ((n (dk-di-var!)))
              (cpsl-pt! n 'cpsz_)
              (dk-lam-b!)
              (dk-conj-close! (lambda () (ass))))
            (ass))))))
(ass)
(qed 'cps-abs-conv-closed-ball)

;;; ======================================================================
;;; (5) An absolutely convergent complex series converges, and its sum.
;;; (The notes, p. 26: "A normally convergent series of functions is absolutely
;;; convergent pointwise and the convergence is uniform"; the pointwise step
;;; needs this, which the tree did not have for CC.)
;;; ======================================================================

(define cpsl-absh '(FORALL cpsj_ (IMPLIES (IN cpsj_ NN) (= (g cpsj_) (magnitude (f cpsj_))))))

;;; |S_k - S_m| <= T_k - T_m for m <= k, S the partial sums of f, T those of |f|
(sp (make-wff
  (list 'FORALL 'cpsk_ (list 'IMPLIES '(IN cpsk_ NN)
    (list 'FORALL 'cpsm_ (list 'IMPLIES '(IN cpsm_ NN)
      (list 'FORALL 'f (list 'IMPLIES '(IN f (FUN NN CC))
        (list 'FORALL 'g (list 'IMPLIES '(IN g (FUN NN RR))
          (list 'IMPLIES cpsl-absh (list 'IMPLIES '(<= cpsm_ cpsk_)
            '(<= (magnitude (- (CC-SERIES-PARTIAL-SUM f cpsk_) (CC-SERIES-PARTIAL-SUM f cpsm_)))
                 (- (SERIES-PARTIAL-SUM g cpsk_) (SERIES-PARTIAL-SUM g cpsm_)))))))))))))))
(define cpsl-bl-br (use-induction))
;;; |S - S| <= T - T for one index j
(define (cpsl-bl-same! j)
  (let ((s (list 'CC-SERIES-PARTIAL-SUM 'f j)) (t (list 'SERIES-PARTIAL-SUM 'g j)))
    (fact 'cc-series-partial-sum-in-cc j 'f)
    (fact 'series-partial-sum-in-rr j 'g)
    (have! (list '= (list '- s s) 0) (lambda () (crs)))
    (subst (list '= (list '- s s) 0))
    (fact 'cc-magnitude-zero)
    (subst '(= (magnitude 0) 0))
    (dk-ineq!)))
(dk-focus! (cdr (assq 'base cpsl-bl-br)))
(dk-peel!)
(fact 'nn-le-zero-is-zero 'cpsm_)
(subst '(= cpsm_ 0))
(cpsl-bl-same! 0)
(dk-focus! (cdr (assq 'step cpsl-bl-br)))
(define cpsl-bl-v (cdr (assq 'var cpsl-bl-br)))
(define cpsl-bl-ih (cdr (assq 'ih cpsl-bl-br)))
(dk-peel!)
(fact 'nn-succ-closed cpsl-bl-v)
(fact 'nn-le-succ-cases cpsl-bl-v 'cpsm_)
(use-cases (list (list '<= 'cpsm_ cpsl-bl-v) (list '= 'cpsm_ (list 'succ cpsl-bl-v)))
  (lambda ()
    (let* ((v cpsl-bl-v)
           (sv (list 'CC-SERIES-PARTIAL-SUM 'f v))
           (sm '(CC-SERIES-PARTIAL-SUM f cpsm_))
           (tv (list 'SERIES-PARTIAL-SUM 'g v))
           (tm '(SERIES-PARTIAL-SUM g cpsm_))
           (fv (list 'f v))
           (d (list '- sv sm)))
      (dk-apply! cpsl-bl-ih 'cpsm_ 'f 'g)
      (fact 'cc-series-partial-sum-in-cc v 'f)
      (fact 'cc-series-partial-sum-in-cc 'cpsm_ 'f)
      (fact 'series-partial-sum-in-rr v 'g)
      (fact 'series-partial-sum-in-rr 'cpsm_ 'g)
      (fact 'fun-apply-type-c 'f 'NN 'CC v)
      (fact 'fun-apply-type-c 'g 'NN 'RR v)
      (inst+ cpsl-absh v)
      (mac 'cc-series-partial-sum-succ)
      (mac 'series-partial-sum-succ)
      (have! (list '= (list '- (list '+ sv fv) sm) (list '+ d fv)) (lambda () (crs)))
      (subst (list '= (list '- (list '+ sv fv) sm) (list '+ d fv)))
      (fact 'cc-sub-in-cc sv sm)
      (have! (list 'AND (list 'IN d 'CC) (list 'IN fv 'CC)))
      (fact 'cc-magnitude-triangle d fv)
      (fact 'cc-add-closed d fv)
      (fact 'cc-magnitude-closed (list '+ d fv))
      (fact 'cc-magnitude-closed d)
      (fact 'cc-magnitude-closed fv)
      (dk-ineq! (list '<= (list 'magnitude (list '+ d fv)) (list '+ (list 'magnitude d) (list 'magnitude fv)))
                (list '<= (list 'magnitude d) (list '- tv tm))
                (list '= (list 'g v) (list 'magnitude fv)))))
  (lambda ()
    (subst (list '= 'cpsm_ (list 'succ cpsl-bl-v)))
    (cpsl-bl-same! (list 'succ cpsl-bl-v))))
(qed 'cc-series-block-le)

;;; an absolutely convergent complex series converges
(sp (make-wff
  (list 'FORALL 'f (list 'IMPLIES '(IN f (FUN NN CC))
    (list 'FORALL 'g (list 'IMPLIES '(IN g (FUN NN RR))
      (list 'IMPLIES cpsl-absh (list 'IMPLIES '(SERIES-CONVERGES g) '(CC-SERIES-CONVERGES f)))))))))
(dk-peel!)
(define cpsl-ac-p '(VNB-LAMBDA k NN (CC-SERIES-PARTIAL-SUM f k)))
(mac 'cc-series-converges)
(fact 'cc-complete)
(fact 'cc-is-metric-space)
(define cpsl-ac-cplt '(FORALL f (IMPLIES (IS-CAUCHY-SEQ CC-MS f) (CONVERGES CC-MS f))))
(have! cpsl-ac-cplt
  (lambda () (mac-h 'is-complete '(IS-COMPLETE CC-MS)) (dk-split-all!) (ass)))
(have! (list 'IS-CAUCHY-SEQ 'CC-MS cpsl-ac-p)
  (lambda ()
    (mac 'is-cauchy-seq)
    (dk-conj-close!
      (lambda ()
        (let ((h (cpsl-head (dk-goal))))
          (cond
            ((eq? h 'FORALL)
             (let* ((ep (dk-peel!))
                    (eps (cadr (car (filter (dk-head? 'POS-RR) ep))))
                    (bnd (dk-skolem! (dk-fact! 'series-cauchy-criterion 'g eps)))
                    (cc (dk-pick (lambda (f) (and (eq? (cpsl-head f) 'FORALL) (dk-contains? f bnd) (dk-contains? f eps))) "cauchy clause")))
               (fact 'rr-pos-rr-in-rr eps)
               (ew bnd)
               (dk-conj-close!
                 (lambda ()
                   (if (eq? (cpsl-head (dk-goal)) 'FORALL)
                       (let* ((lk (dk-peel!))
                              (dummy (dk-split-all! lk))
                              (gd (cadr (dk-goal)))
                              (m (cadr (cadr gd))) (n (cadr (caddr gd)))
                              (sm (list 'CC-SERIES-PARTIAL-SUM 'f m)) (sn (list 'CC-SERIES-PARTIAL-SUM 'f n))
                              (tm (list 'SERIES-PARTIAL-SUM 'g m)) (tn (list 'SERIES-PARTIAL-SUM 'g n)))
                         (fact 'cc-series-partial-sum-in-cc m 'f)
                         (fact 'cc-series-partial-sum-in-cc n 'f)
                         (fact 'series-partial-sum-in-rr m 'g)
                         (fact 'series-partial-sum-in-rr n 'g)
                         (dk-lam-b!)
                         (subst (dk-fact! 'cc-ms-dist sm sn))
                         (fact 'cc-sub-in-cc sm sn)
                         (fact 'cc-sub-in-cc sn sm)
                         (fact 'cc-magnitude-closed (list '- sm sn))
                         (fact 'cc-magnitude-closed (list '- sn sm))
                         (fact 'cc-magnitude-sub-sym sm sn)
                         (fact 'nn-in-rr m)
                         (fact 'nn-in-rr n)
                         (have! (list 'AND (list 'IN m 'RR) (list 'IN n 'RR)))
                         (fact 'rr-leq-total m n)
                         (use-cases (list (list '<= m n) (list '<= n m))
                           (lambda ()
                             (fact 'cc-series-block-le n m 'f 'g)
                             (have! (list 'AND (list '<= bnd m) (list '<= m n)))
                             (let ((ab (dk-deepest (lambda () (inst*! cc m n)))))
                               (fact 'rr-sub-in-rr tn tm)
                               (fact 'rr-le-abs (list '- tn tm))
                               (fact 'rr-abs-closed (list '- tn tm))
                               (dk-ineq! (list '= (list 'magnitude (list '- sm sn)) (list 'magnitude (list '- sn sm)))
                                         (list '<= (list 'magnitude (list '- sn sm)) (list '- tn tm))
                                         (list '<= (list '- tn tm) (list 'abs (list '- tn tm)))
                                         ab)))
                           (lambda ()
                             (fact 'cc-series-block-le m n 'f 'g)
                             (have! (list 'AND (list '<= bnd n) (list '<= n m)))
                             (let ((ab (dk-deepest (lambda () (inst*! cc n m)))))
                               (fact 'rr-sub-in-rr tm tn)
                               (fact 'rr-le-abs (list '- tm tn))
                               (fact 'rr-abs-closed (list '- tm tn))
                               (dk-ineq! (list '<= (list 'magnitude (list '- sm sn)) (list '- tm tn))
                                         (list '<= (list '- tm tn) (list 'abs (list '- tm tn)))
                                         ab)))))
                       (ass))))))
            ((eq? h 'IN)
             (if (dk-asm? (dk-goal))
                 (ass)
                 (begin
                   (slot 'PTS)
                   (dk-lam-t!)
                   (let ((k (dk-di-var!)))
                     (fact 'cc-series-partial-sum-in-cc k 'f)
                     (ass)))))
            (#t (ass))))))))
(inst+ cpsl-ac-cplt cpsl-ac-p)
(ass)
(qed 'cc-series-abs-converges)

;;; a convergent complex series converges to its sum, and the sum is in CC
(sp (make-wff "forall([f in fun(nn,cc)], cc-series-converges(f) implies
     cc-series-converges-to(f, cc-series-limit(f)))"))
(dk-peel!)
(mac 'cc-series-limit)
(define cpsl-sl-iota '(IOTA cpsl_ (CC-SERIES-CONVERGES-TO f cpsl_)))
(define cpsl-sl-p '(VNB-LAMBDA k NN (CC-SERIES-PARTIAL-SUM f k)))
(have! (list 'IN cpsl-sl-p '(FUN NN CC))
  (lambda ()
    (dk-lam-t!)
    (let ((k (dk-di-var!))) (fact 'cc-series-partial-sum-in-cc k 'f) (ass))))
;;; the limit of the partial sums is in CC, from a CONVERGES-TO in context
(define (cpsl-lim-in! cvt y)
  (have! (list 'IN y 'CC)
    (lambda ()
      (dk-split! (dk-landed-find (lambda () (mac-h 'converges-to cvt)) (lambda (a) (eq? (car a) 'AND))))
      (dk-split-all!)
      (slot-h 'PTS (list 'IN y '(PTS CC-MS)))
      (ass))))
(for-each
  (lambda (l)
    (dk-focus! l)
    (if (eq? (cpsl-head (dk-goal)) 'CC-SERIES-CONVERGES-TO)
        (ass)
        (begin
          (mac-h 'cc-series-converges '(CC-SERIES-CONVERGES f))
          (let* ((cex (dk-landed-1 (lambda () (mac-h 'converges (list 'CONVERGES 'CC-MS cpsl-sl-p)))))
                 (lm (dk-skolem! cex))
                 (cvt (dk-pick (dk-head? 'CONVERGES-TO) "convergence")))
            (dk-have! (list 'CONVERGES-TO 'CC-MS cpsl-sl-p lm) (lambda () (ass)))
            (have! (list 'IN lm 'CC)
              (lambda ()
                (dk-split! (dk-landed-find (lambda () (mac-h 'converges-to cvt)) (lambda (a) (eq? (car a) 'AND))))
                (dk-split-all!)
                (slot-h 'PTS (list 'IN lm '(PTS CC-MS)))
                (ass)))
            (ew lm)
            (dk-conj-close!
              (lambda ()
                (let ((gl (dk-goal)))
                  (cond ((eq? (car gl) 'IN) (ass))
                        ((eq? (car gl) 'CC-SERIES-CONVERGES-TO) (mac 'cc-series-converges-to) (ass))
                        (#t
                         (let* ((lk (dk-peel!))
                                (yt (car (filter (dk-head? 'CC-SERIES-CONVERGES-TO) lk)))
                                (y (caddr yt))
                                (ycv (dk-landed-1 (lambda () (mac-h 'cc-series-converges-to yt)))))
                           (have! (list 'IN y 'CC)
                             (lambda ()
                               (dk-split! (dk-landed-find (lambda () (mac-h 'converges-to ycv)) (lambda (a) (eq? (car a) 'AND))))
                               (dk-split-all!)
                               (slot-h 'PTS (list 'IN y '(PTS CC-MS)))
                               (ass)))
                           (fact 'cc-limit-unique cpsl-sl-p lm y)
                           (ass)))))))))))
  (dk-opened (lambda () (iota-d cpsl-sl-iota))))
(qed 'cc-series-limit-converges-to)

(sp (make-wff "forall([f in fun(nn,cc)], cc-series-converges(f) implies cc-series-limit(f) in cc)"))
(dk-peel!)
(fact 'cc-series-limit-converges-to 'f)
(mac-h 'cc-series-converges-to '(CC-SERIES-CONVERGES-TO f (CC-SERIES-LIMIT f)))
(dk-split! (dk-landed-find (lambda () (mac-h 'converges-to (dk-pick (dk-head? 'CONVERGES-TO) "convergence")))
                           (lambda (a) (eq? (car a) 'AND))))
(dk-split-all!)
(slot-h 'PTS '(IN (CC-SERIES-LIMIT f) (PTS CC-MS)))
(ass)
(qed 'cc-series-limit-in-cc)

;;; ======================================================================
;;; (6) LEMMA 2.8, "in particular": at each z in B(0, r) the power series
;;; converges (absolutely: cps-abs-conv-closed-ball), and the convergence of the
;;; partial sums to the sum is UNIFORM on B(0, r).
;;; ======================================================================

(define (cpsl-tz z) (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* '(cf cpsk_) (list 'power z 'cpsk_))))
(define (cpsl-az z) (list 'VNB-LAMBDA 'cpsk_ 'NN (list 'magnitude (list '* '(cf cpsk_) (list 'power z 'cpsk_)))))

;;; z in B(0, r) in context: the term sequences at z typed, their link, and the
;;; convergence of the series at z (which needs cps-abs-conv-closed-ball)
(define (cpsl-at-z! z)
  (let ((tz (cpsl-tz z)) (az (cpsl-az z)))
    (have! (list 'IN tz '(FUN NN CC))
      (lambda () (dk-lam-t!) (let ((k (dk-di-var!))) (cpsl-pt! k z) (ass))))
    (have! (list 'IN az '(FUN NN RR))
      (lambda () (dk-lam-t!) (let ((k (dk-di-var!))) (cpsl-pt! k z) (ass))))
    (have! (list 'FORALL 'cpsj_ (list 'IMPLIES '(IN cpsj_ NN) (list '= (list az 'cpsj_) (list 'magnitude (list tz 'cpsj_)))))
      (lambda ()
        (let ((j (dk-di-var!)))
          (cpsl-pt! j z)
          (dk-lam-b!)
          (rfl))))
    (fact 'cps-abs-conv-closed-ball 'cf 'cpsrad_ z)
    (fact 'cc-series-abs-converges tz az)))

(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cpsrad_ (list 'IMPLIES '(IN cpsrad_ RR) (list 'IMPLIES '(<= 0 cpsrad_)
      (list 'IMPLIES '(< cpsrad_ (CPS-RADIUS cf))
        (list 'FORALL 'cpsz_ (list 'IMPLIES (list 'IN 'cpsz_ cpsl-b)
          (list 'CC-SERIES-CONVERGES (cpsl-tz 'cpsz_))))))))))))
(dk-peel!)
(cpsl-at-z! 'cpsz_)
(ass)
(qed 'cps-converges-closed-ball)

(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cpsrad_ (list 'IMPLIES '(IN cpsrad_ RR) (list 'IMPLIES '(<= 0 cpsrad_)
      (list 'IMPLIES '(< cpsrad_ (CPS-RADIUS cf))
        (list 'FORALL 'cpse_ (list 'IMPLIES '(POS-RR cpse_)
          (list 'FORSOME 'cpsn_ (list 'AND '(IN cpsn_ NN)
            (list 'FORALL 'cpsm_ (list 'IMPLIES '(IN cpsm_ NN) (list 'IMPLIES '(<= cpsn_ cpsm_)
              (list 'FORALL 'cpsz_ (list 'IMPLIES (list 'IN 'cpsz_ cpsl-b)
                (list '<= (list 'magnitude (list '- (list 'CC-SERIES-LIMIT (cpsl-tz 'cpsz_))
                                                  (list 'CC-SERIES-PARTIAL-SUM (cpsl-tz 'cpsz_) 'cpsm_)))
                      'cpse_))))))))))))))))))
(dk-peel!)
(cpsl-conv-r!)
(define cpsl-u-tm (cpsl-tm-of 'cpsrad_))
(have! (list 'FORALL 'cpsi_ (list 'IMPLIES '(IN cpsi_ NN) (list '<= 0 (list cpsl-u-tm 'cpsi_))))
  (lambda () (let ((i (dk-di-var!))) (cpsl-term-typ-r! i 'cpsrad_) (cpsl-beta!))))
(fact 'rr-pos-rr-in-rr 'cpse_)
(define cpsl-u-d (dk-halve! 'cpse_))
(define cpsl-u-bnd (dk-skolem! (dk-fact! 'series-tail-small cpsl-u-tm cpsl-u-d)))
(define cpsl-u-tail
  (dk-pick (lambda (f) (and (eq? (cpsl-head f) 'FORALL) (dk-contains? f cpsl-u-bnd) (dk-contains? f cpsl-u-d))) "tail small"))
(ew cpsl-u-bnd)
(dk-conj-close!
  (lambda ()
    (if (eq? (cpsl-head (dk-goal)) 'IN)
        (ass)
        (let* ((lk (dk-peel!))
               (g (dk-goal))
               (lhs (cadr (cadr g)))
               (sm (caddr lhs))
               (m (caddr sm))
               (tz (cadr sm))
               (z (cadr (caddr (cadddr tz))))
               (az (cpsl-az z))
               (lv (cadr lhs))
               (pseq (list 'VNB-LAMBDA 'k 'NN (list 'CC-SERIES-PARTIAL-SUM tz 'k)))
               (mseq (list 'VNB-LAMBDA 'cpsj_ 'NN (list 'magnitude (list '- (list 'CC-SERIES-PARTIAL-SUM tz 'cpsj_) lv)))))
          (cpsl-at-z! z)
          (fact 'cc-series-limit-converges-to tz)
          (fact 'cc-series-limit-in-cc tz)
          (have! (list 'IN pseq '(FUN NN CC))
            (lambda () (dk-lam-t!) (let ((k (dk-di-var!))) (fact 'cc-series-partial-sum-in-cc k tz) (ass))))
          (have! (list 'CONVERGES-TO 'CC-MS pseq lv)
            (lambda () (mac-h 'cc-series-converges-to (list 'CC-SERIES-CONVERGES-TO tz lv)) (ass)))
          (have! (list 'IN mseq '(FUN NN RR))
            (lambda ()
              (dk-lam-t!)
              (let ((j (dk-di-var!)))
                (fact 'cc-series-partial-sum-in-cc j tz)
                (fact 'cc-sub-in-cc (list 'CC-SERIES-PARTIAL-SUM tz j) lv)
                (fact 'cc-magnitude-closed (list '- (list 'CC-SERIES-PARTIAL-SUM tz j) lv))
                (ass))))
          (have! (list 'FORALL 'cpsj_ (list 'IMPLIES '(IN cpsj_ NN)
                   (list '= (list mseq 'cpsj_) (list 'magnitude (list '- (list pseq 'cpsj_) lv)))))
            (lambda ()
              (let ((j (dk-di-var!)))
                (fact 'cc-series-partial-sum-in-cc j tz)
                (fact 'cc-sub-in-cc (list 'CC-SERIES-PARTIAL-SUM tz j) lv)
                (fact 'cc-magnitude-closed (list '- (list 'CC-SERIES-PARTIAL-SUM tz j) lv))
                (dk-lam-b!)
                (rfl))))
          (fact 'cc-converges-magnitude-null pseq lv mseq)
          (fact 'rr-zero-in)
          (let* ((kk (dk-skolem! (dk-fact! 'rr-limit-tail-le mseq 0 cpsl-u-d)))
                 (kt (dk-pick (lambda (f) (and (eq? (cpsl-head f) 'FORALL) (dk-contains? f kk))) "limit tail"))
                 (k (list '+ m kk))
                 (sk (list 'CC-SERIES-PARTIAL-SUM tz k))
                 (smm (list 'CC-SERIES-PARTIAL-SUM tz m))
                 (azk (list 'SERIES-PARTIAL-SUM az k))
                 (azm (list 'SERIES-PARTIAL-SUM az m))
                 (tmk (list 'SERIES-PARTIAL-SUM cpsl-u-tm k))
                 (tmm (list 'SERIES-PARTIAL-SUM cpsl-u-tm m))
                 (tmb (list 'SERIES-PARTIAL-SUM cpsl-u-tm cpsl-u-bnd))
                 (p (list '- lv smm))
                 (q (list '- sk smm)))
            (have! (list 'AND (list 'IN m 'NN) (list 'IN kk 'NN)))
            (fact 'nn-add-closed m kk)
            (fact 'nn-le-add-right kk m)
            (fact 'nn-le-add-left m kk)
            (fact 'nn-le-trans-guarded cpsl-u-bnd m k)
            (dk-lam-b-h! (dk-deepest (lambda () (inst+ kt k))))
            (fact 'cc-series-block-le k m tz az)
            (have! (list 'FORALL 'cpsi_ (list 'IMPLIES '(IN cpsi_ NN)
                     (list 'AND (list '<= 0 (list az 'cpsi_)) (list '<= (list az 'cpsi_) (list cpsl-u-tm 'cpsi_)))))
              (lambda ()
                (let ((i (dk-di-var!)))
                  (cpsl-pt! i z)
                  (dk-lam-b!)
                  (dk-conj-close! (lambda () (ass))))))
            (fact 'series-block-le k m az cpsl-u-tm)
            (inst+ cpsl-u-tail k)
            (fact 'series-partial-sum-mono m cpsl-u-bnd cpsl-u-tm)
            (for-each (lambda (j) (fact 'series-partial-sum-in-rr j az) (fact 'series-partial-sum-in-rr j cpsl-u-tm))
                      (list k m))
            (fact 'series-partial-sum-in-rr cpsl-u-bnd cpsl-u-tm)
            (fact 'cc-series-partial-sum-in-cc k tz)
            (fact 'cc-series-partial-sum-in-cc m tz)
            (fact 'cc-sub-in-cc lv smm)
            (fact 'cc-sub-in-cc sk smm)
            (fact 'cc-sub-in-cc sk lv)
            (fact 'cc-sub-in-cc lv sk)
            (fact 'cc-sub-in-cc p q)
            (for-each (lambda (t) (fact 'cc-magnitude-closed t))
                      (list p q (list '- sk lv) (list '- lv sk) (list '- p q)))
            (fact 'cc-magnitude-le-add p q)
            (have! (list '= (list 'magnitude (list '- p q)) (list 'magnitude (list '- sk lv)))
              (lambda ()
                (have! (list '= (list '- p q) (list '- lv sk)) (lambda () (crs)))
                (subst (list '= (list '- p q) (list '- lv sk)))
                (subst (dk-fact! 'cc-magnitude-sub-sym lv sk))
                (rfl)))
            (dk-ineq! (list '<= (list 'magnitude p) (list '+ (list 'magnitude (list '- p q)) (list 'magnitude q)))
                      (list '= (list 'magnitude (list '- p q)) (list 'magnitude (list '- sk lv)))
                      (list '<= (list 'magnitude (list '- sk lv)) (list '+ 0 cpsl-u-d))
                      (list '<= (list 'magnitude q) (list '- azk azm))
                      (list '<= (list '- azk azm) (list '- tmk tmm))
                      (list '<= (list '- tmk tmb) cpsl-u-d)
                      (list '<= tmb tmm)
                      (list '= (list '+ cpsl-u-d cpsl-u-d) 'cpse_)))))))
(qed 'cps-uniform-closed-ball)

;;; ======================================================================
;;; (7) LEMMA 2.9: "If |b_k| <= C k^m for some C, m, then the radius of
;;; convergence of the series sum a_k z^k is <= that of sum a_k b_k z^k."
;;; The notes prove it from Prop 2.7 and lim sup_n n^(m/n) = 1; the tree has no
;;; lim_n n^(1/n) = 1, and the proof here works from the DEFINITION of the radius
;;; instead: k^m q^k is bounded for 0 <= q < 1 (through the m-th root of q and
;;; k s^k (1 - s) <= 1), so sum |a_k b_k| r^k is dominated by a multiple of
;;; sum |a_k| t^k for r < t.  The product coefficients are GIVEN (cfg with
;;; cfg(k) = cf(k) cg(k)), so no lambda is applied under a binder.
;;; ======================================================================

;;; (x^k)^m = (x^m)^k
(sp (make-wff
  '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (FORALL cpsm_ (IMPLIES (IN cpsm_ NN) (FORALL cpsx_ (IMPLIES (IN cpsx_ RR)
     (= (power (power cpsx_ cpsk_) cpsm_) (power (power cpsx_ cpsm_) cpsk_))))))))))
(define cpsl-pp-br (use-induction))
(dk-focus! (cdr (assq 'base cpsl-pp-br)))
(dk-peel!)
(fact 'rr-subset-cc 'cpsx_)
(fact 'power-real-closed 'cpsx_ 'cpsm_)
(fact 'rr-subset-cc '(power cpsx_ cpsm_))
(mac 'power-zero)
(fact 'rr-power-one 'cpsm_)
(ass)
(dk-focus! (cdr (assq 'step cpsl-pp-br)))
(define cpsl-pp-v (cdr (assq 'var cpsl-pp-br)))
(define cpsl-pp-ih (cdr (assq 'ih cpsl-pp-br)))
(dk-peel!)
(fact 'rr-subset-cc 'cpsx_)
(fact 'power-real-closed 'cpsx_ 'cpsm_)
(fact 'power-real-closed 'cpsx_ cpsl-pp-v)
(fact 'rr-subset-cc '(power cpsx_ cpsm_))
(fact 'power-real-closed '(power cpsx_ cpsm_) cpsl-pp-v)
(fact 'power-real-closed (list 'power 'cpsx_ cpsl-pp-v) 'cpsm_)
(mac 'power-succ)
(subst (dk-fact! 'rr-power-mul-base 'cpsm_ 'cpsx_ (list 'power 'cpsx_ cpsl-pp-v)))
(subst (dk-apply! cpsl-pp-ih 'cpsm_ 'cpsx_))
(rfl)
(qed 'rr-power-power)

;;; k^m q^k is bounded, 0 <= q < 1
(sp (make-wff
  '(FORALL cpsm_ (IMPLIES (IN cpsm_ NN) (FORALL cpsq_ (IMPLIES (IN cpsq_ RR) (IMPLIES (<= 0 cpsq_) (IMPLIES (< cpsq_ 1)
     (FORSOME cpsb_ (AND (IN cpsb_ RR) (AND (<= 0 cpsb_)
       (FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (<= (* (power cpsk_ cpsm_) (power cpsq_ cpsk_)) cpsb_))))))))))))))
(dk-peel!)
(fact 'rr-one-in)
(have! '(<= 0 1) (lambda () (dk-ineq!)))
(use-em '(= cpsm_ 0)
  (lambda ()
    (ew 1)
    (dk-conj-close!
      (lambda ()
        (if (eq? (cpsl-head (dk-goal)) 'FORALL)
            (let ((k (dk-di-var!)))
              (fact 'nn-in-rr k)
              (fact 'rr-subset-cc k)
              (subst '(= cpsm_ 0))
              (mac 'power-zero)
              (have! '(AND (<= 0 cpsq_) (<= cpsq_ 1)) (lambda () (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (dk-ineq! '(< cpsq_ 1)))))))
              (fact 'rr-power-le-one k 'cpsq_)
              (fact 'power-real-closed 'cpsq_ k)
              (dk-ineq! (list '<= (list 'power 'cpsq_ k) 1)))
            (ass)))))
  (lambda ()
    (dk-one-le! 'cpsm_)
    (fact 'nn-in-rr 'cpsm_)
    (fact 'recip-star-in-rr 'cpsm_)
    (fact 'recip-star-nn-nonneg 'cpsm_)
    (fact 'recip-star-nn-pos 'cpsm_)
    (let* ((sm '(recip-star cpsm_))
           (s (list 'rpow-star 'cpsq_ sm))
           (sp (list 'power s 'cpsm_))
           ;; 1 <= s is absurd: 1 = 1^m <= s^m = q < 1
           (s-absurd! (lambda ()
                        (fact 'rr-power-mono-base 'cpsm_ 1 s)
                        (fact 'rr-power-one 'cpsm_)
                        (fact 'power-real-closed 1 'cpsm_)
                        (dk-absurd! (list '<= (list 'power 1 'cpsm_) sp) (list '= (list 'power 1 'cpsm_) 1)
                                      (list '= sp 'cpsq_) '(< cpsq_ 1)))))
      (fact 'rpow-star-nonneg-in-rr 'cpsq_ sm)
      (fact 'rpow-star-nonneg-nonneg 'cpsq_ sm)
      (fact 'power-real-closed s 'cpsm_)
      ;; s^m = q, by cases q = 0 / q > 0
      (have! (list '= sp 'cpsq_)
        (lambda ()
          (use-em '(= 0 cpsq_)
            (lambda ()
              (subst '(= cpsq_ 0))
              (fact 'rpow-star-zero-base sm)
              (subst (list '= (list 'rpow-star 0 sm) 0))
              (let ((p (dk-skolem! (dk-fact! 'nn-nonzero-is-succ 'cpsm_))))
                (subst (list '= 'cpsm_ (list 'succ p)))
                (fact 'power-zero-base p)
                (ass)))
            (lambda ()
              (cpsl-pos-of! 'cpsq_)
              (fact 'rpow-star-root-power 'cpsm_ 'cpsq_)
              (ass)))))
      (have! (list '< s 1)
        (lambda ()
          (mac '<)
          (dk-conj-close!
            (lambda ()
              (if (eq? (cpsl-head (dk-goal)) 'NOT)
                  (begin (di) (have! (list '<= 1 s) (lambda () (dk-ineq! (list '= s 1)))) (s-absurd!))
                  (begin (pbc) (fact 'rr-not-le-lt s 1) (cpsl-lt-le! 1 s) (s-absurd!)))))))
      (fact 'rr-sub-in-rr 1 s)
      (let* ((u (list '- 1 s))
             (dummy (have! (list '< 0 u) (lambda () (dk-ineq! (list '< s 1)))))
             (w (cpsl-recip! u))
             (bb (list 'power w 'cpsm_)))
        (fact 'power-real-closed w 'cpsm_)
        (fact 'rr-power-nonneg 'cpsm_ w)
        (ew bb)
        (dk-conj-close!
          (lambda ()
            (if (eq? (cpsl-head (dk-goal)) 'FORALL)
                (let* ((k (dk-di-var!))
                       (sk (list 'power s k))
                       (y (list '* k sk))
                       (km (list 'power k 'cpsm_))
                       (qk (list 'power 'cpsq_ k)))
                  (fact 'nn-in-rr k)
                  (fact 'nn-zero-le k)
                  (fact 'power-real-closed s k)
                  (fact 'rr-power-nonneg k s)
                  (fact 'rr-mul-in-rr k sk)
                  (cpsl-lt-le! s 1)
                  (have! (list 'AND (list '<= 0 s) (list '<= s 1)))
                  (fact 'rr-power-shrink-bound k s)
                  (have! (list 'AND (list 'IN k 'RR) (list 'IN sk 'RR)))
                  (have! (list 'AND (list '<= 0 k) (list '<= 0 sk)))
                  (fact 'rr-leq-mul-nonneg k sk)
                  (fact 'rr-mul-in-rr y u)
                  (fact 'rr-mul-in-rr w u)
                  (fact 'rr-mul-in-rr u w)
                  (fact 'rr-mul-in-rr k u)
                  (fact 'rr-mul-in-rr (list '* k u) sk)
                  (have! (list '= (list '* (list '* k u) sk) (list '* y u)) (lambda () (crs)))
                  (have! (list '= (list '* w u) (list '* u w)) (lambda () (crs)))
                  (have! (list '<= (list '* y u) (list '* w u))
                    (lambda () (dk-ineq! (list '<= (list '* (list '* k u) sk) 1)
                                         (list '= (list '* (list '* k u) sk) (list '* y u))
                                         (list '= (list '* w u) (list '* u w)) (list '= (list '* u w) 1))))
                  (fact 'rr-mul-le-cancel-pos y u w)
                  (fact 'rr-power-mono-base 'cpsm_ y w)
                  (fact 'power-real-closed y 'cpsm_)
                  (fact 'power-real-closed k 'cpsm_)
                  (fact 'power-real-closed 'cpsq_ k)
                  (fact 'power-real-closed sk 'cpsm_)
                  (fact 'rr-mul-in-rr km qk)
                  (have! (list '= (list 'power y 'cpsm_) (list '* km qk))
                    (lambda ()
                      (subst (dk-fact! 'rr-power-mul-base 'cpsm_ k sk))
                      (subst (dk-fact! 'rr-power-power k 'cpsm_ s))
                      (subst (list '= sp 'cpsq_))
                      (rfl)))
                  (dk-ineq! (list '= (list 'power y 'cpsm_) (list '* km qk)) (list '<= (list 'power y 'cpsm_) bb)))
                (ass))))))))
(qed 'cps-poly-geom-bound)

;;; a non-negative multiple of a convergent non-negative series converges
(sp (make-wff
  (list 'FORALL 'f (list 'IMPLIES '(IN f (FUN NN RR)) (list 'IMPLIES cpsl-h2
    '(FORALL cpsc_ (IMPLIES (IN cpsc_ RR) (IMPLIES (<= 0 cpsc_)
       (FORALL h (IMPLIES (IN h (FUN NN RR))
         (IMPLIES (FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (= (h cpsk_) (* cpsc_ (f cpsk_)))))
           (IMPLIES (SERIES-CONVERGES f) (SERIES-CONVERGES h)))))))))))))
(dk-peel!)
(define cpsl-sc-eq (dk-pick (lambda (fm) (and (eq? (cpsl-head fm) 'FORALL) (dk-contains? fm 'cpsc_))) "scale equation"))
(have! '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (IN (f cpsk_) RR)))
  (lambda () (let ((k (dk-di-var!))) (fact 'fun-apply-type-c 'f 'NN 'RR k) (ass))))
(have! '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (<= 0 (h cpsk_))))
  (lambda ()
    (let ((k (dk-di-var!)))
      (fact 'fun-apply-type-c 'f 'NN 'RR k)
      (inst+ cpsl-sc-eq k)
      (inst+ cpsl-h2 k)
      (have! (list 'AND '(IN cpsc_ RR) (list 'IN (list 'f k) 'RR)))
      (have! (list 'AND '(<= 0 cpsc_) (list '<= 0 (list 'f k))))
      (fact 'rr-leq-mul-nonneg 'cpsc_ (list 'f k))
      (fact 'fun-apply-type-c 'h 'NN 'RR k)
      (fact 'rr-mul-in-rr 'cpsc_ (list 'f k))
      (dk-ineq! (list '= (list 'h k) (list '* 'cpsc_ (list 'f k))) (list '<= 0 (list '* 'cpsc_ (list 'f k)))))))
(define cpsl-sc-b (dk-skolem! (dk-fact! 'series-partial-sum-bounded 'f)))
(define cpsl-sc-bd (dk-pick (lambda (fm) (and (eq? (cpsl-head fm) 'FORALL) (dk-contains? fm cpsl-sc-b))) "bound"))
(define cpsl-sc-bb (list '* 'cpsc_ cpsl-sc-b))
(fact 'rr-mul-in-rr 'cpsc_ cpsl-sc-b)
(have! (list 'FORALL 'cpsk_ (list 'IMPLIES '(IN cpsk_ NN) (list '<= '(SERIES-PARTIAL-SUM h cpsk_) cpsl-sc-bb)))
  (lambda ()
    (let* ((k (dk-di-var!)) (fk (list 'SERIES-PARTIAL-SUM 'f k)))
      (fact 'series-partial-sum-scale-ptwise k 'cpsc_ 'f 'h)
      (inst+ cpsl-sc-bd k)
      (fact 'series-partial-sum-in-rr k 'f)
      (have! (list 'AND '(<= 0 cpsc_) (list '<= fk cpsl-sc-b)))
      (fact 'rr-le-scale-nonneg 'cpsc_ fk cpsl-sc-b)
      (fact 'rr-mul-in-rr 'cpsc_ fk)
      (fact 'series-partial-sum-in-rr k 'h)
      (dk-ineq! (list '= (list 'SERIES-PARTIAL-SUM 'h k) (list '* 'cpsc_ fk))
                (list '<= (list '* 'cpsc_ fk) cpsl-sc-bb)))))
(fact 'series-bounded-converges 'h cpsl-sc-bb)
(ass)
(qed 'series-scale-converges)

(define cpsl-prod '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (= (cfg cpsk_) (* (cf cpsk_) (cg cpsk_))))))
(define cpsl-bound '(FORALL cpsk_ (IMPLIES (IN cpsk_ NN) (<= (magnitude (cg cpsk_)) (* cpsc_ (power cpsk_ cpsm_))))))
(define (cpsl-fab r) (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* '(magnitude (cfg cpsk_)) (list 'power r 'cpsk_))))

;;; r < t, sum |a_k| t^k < inf, |b_k| <= C k^m  =>  sum |a_k b_k| r^k < inf
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cg (list 'IMPLIES '(IN cg (FUN NN CC))
      (list 'FORALL 'cfg (list 'IMPLIES '(IN cfg (FUN NN CC))
        (list 'IMPLIES cpsl-prod
          (list 'FORALL 'cpsc_ (list 'IMPLIES '(IN cpsc_ RR)
            (list 'FORALL 'cpsm_ (list 'IMPLIES '(IN cpsm_ NN)
              (list 'IMPLIES cpsl-bound
                (list 'FORALL 'cpst_ (list 'IMPLIES '(IN cpst_ RR)
                  (list 'FORALL 'cpsrad_ (list 'IMPLIES '(IN cpsrad_ RR) (list 'IMPLIES '(<= 0 cpsrad_)
                    (list 'IMPLIES '(< cpsrad_ cpst_)
                      (list 'IMPLIES (list 'SERIES-CONVERGES (cpsl-tm-of 'cpst_))
                        (list 'SERIES-CONVERGES (cpsl-fab 'cpsrad_)))))))))))))))))))))))
(dk-peel!)
(have! '(< 0 cpst_) (lambda () (dk-ineq! '(<= 0 cpsrad_) '(< cpsrad_ cpst_))))
(cpsl-lt-le! 0 'cpst_)
(define cpsl-k-w (cpsl-recip! 'cpst_))
(fact 'rr-mul-in-rr 'cpsrad_ cpsl-k-w)
(define cpsl-k-q (dk-name! (list '* 'cpsrad_ cpsl-k-w)))
(define cpsl-k-rw (list '* 'cpsrad_ cpsl-k-w))
(have! (list 'AND '(IN cpsrad_ RR) (list 'IN cpsl-k-w 'RR)))
(have! (list 'AND '(<= 0 cpsrad_) (list '<= 0 cpsl-k-w)))
(fact 'rr-leq-mul-nonneg 'cpsrad_ cpsl-k-w)
(have! (list '<= 0 cpsl-k-q) (lambda () (dk-ineq! (list '= cpsl-k-q cpsl-k-rw) (list '<= 0 cpsl-k-rw))))
(have! (list 'AND (list '< 0 cpsl-k-w) '(< cpsrad_ cpst_)))
(fact 'rr-lt-scale-pos cpsl-k-w 'cpsrad_ 'cpst_)
(fact 'rr-mul-in-rr cpsl-k-w 'cpsrad_)
(fact 'rr-mul-in-rr cpsl-k-w 'cpst_)
(fact 'rr-mul-in-rr 'cpst_ cpsl-k-w)
(have! (list '= (list '* cpsl-k-w 'cpsrad_) cpsl-k-rw) (lambda () (crs)))
(have! (list '= (list '* cpsl-k-w 'cpst_) (list '* 'cpst_ cpsl-k-w)) (lambda () (crs)))
(have! (list '< cpsl-k-q 1)
  (lambda () (dk-ineq! (list '< (list '* cpsl-k-w 'cpsrad_) (list '* cpsl-k-w 'cpst_))
                       (list '= (list '* cpsl-k-w 'cpsrad_) cpsl-k-rw)
                       (list '= (list '* cpsl-k-w 'cpst_) (list '* 'cpst_ cpsl-k-w))
                       (list '= (list '* 'cpst_ cpsl-k-w) 1)
                       (list '= cpsl-k-q cpsl-k-rw))))
(have! (list '= (list '* cpsl-k-q 'cpst_) 'cpsrad_)
  (lambda ()
    (subst (list '= cpsl-k-q cpsl-k-rw))
    (have! (list '= (list '* cpsl-k-rw 'cpst_) (list '* 'cpsrad_ (list '* 'cpst_ cpsl-k-w))) (lambda () (crs)))
    (subst (list '= (list '* cpsl-k-rw 'cpst_) (list '* 'cpsrad_ (list '* 'cpst_ cpsl-k-w))))
    (subst (list '= (list '* 'cpst_ cpsl-k-w) 1))
    (crs)))
(define cpsl-k-b (dk-skolem! (dk-fact! 'cps-poly-geom-bound 'cpsm_ cpsl-k-q)))
(define cpsl-k-bd
  (dk-pick (lambda (f) (and (eq? (cpsl-head f) 'FORALL) (dk-contains? f cpsl-k-b))) "poly-geom bound"))
;;; C >= 0, from k = 1
(have! '(IN 1 NN) (lambda () (arith)))
(fact 'rr-one-in)
(fact 'fun-apply-type-c 'cg 'NN 'CC 1)
(fact 'cc-magnitude-closed '(cg 1))
(fact 'cc-magnitude-nonneg '(cg 1))
(inst+ cpsl-bound 1)
(fact 'rr-power-one 'cpsm_)
(fact 'power-real-closed 1 'cpsm_)
(fact 'rr-mul-in-rr 'cpsc_ '(power 1 cpsm_))
(have! '(= (* cpsc_ (power 1 cpsm_)) cpsc_) (lambda () (subst '(= (power 1 cpsm_) 1)) (crs)))
(have! '(<= 0 cpsc_)
  (lambda () (dk-ineq! '(<= 0 (magnitude (cg 1))) '(<= (magnitude (cg 1)) (* cpsc_ (power 1 cpsm_)))
                       '(= (* cpsc_ (power 1 cpsm_)) cpsc_))))
(define cpsl-k-tmt (cpsl-tm-of 'cpst_))
(cpsl-tm-typ-r! 'cpst_)
(have! (subst-free 'f cpsl-k-tmt cpsl-h2)
  (lambda () (let ((k (dk-di-var!))) (cpsl-term-typ-r! k 'cpst_) (cpsl-beta!))))
(define cpsl-k-cb (list '* 'cpsc_ cpsl-k-b))
(fact 'rr-mul-in-rr 'cpsc_ cpsl-k-b)
(have! (list 'AND '(IN cpsc_ RR) (list 'IN cpsl-k-b 'RR)))
(have! (list 'AND '(<= 0 cpsc_) (list '<= 0 cpsl-k-b)))
(fact 'rr-leq-mul-nonneg 'cpsc_ cpsl-k-b)
(define cpsl-k-g
  (list 'VNB-LAMBDA 'cpsk_ 'NN (list '* cpsl-k-cb '(* (magnitude (cf cpsk_)) (power cpst_ cpsk_)))))
(define (cpsl-k-gtyp! k)
  (cpsl-term-typ-r! k 'cpst_)
  (fact 'rr-mul-in-rr cpsl-k-cb (list '* (list 'magnitude (list 'cf k)) (list 'power 'cpst_ k))))
(have! (list 'IN cpsl-k-g '(FUN NN RR))
  (lambda () (dk-lam-t!) (let ((k (dk-di-var!))) (cpsl-k-gtyp! k) (ass))))
(have! (list 'FORALL 'cpsk_ (list 'IMPLIES '(IN cpsk_ NN) (list '= (list cpsl-k-g 'cpsk_) (list '* cpsl-k-cb (list cpsl-k-tmt 'cpsk_)))))
  (lambda () (let ((k (dk-di-var!))) (cpsl-k-gtyp! k) (dk-lam-b!) (rfl))))
(fact 'series-scale-converges cpsl-k-tmt cpsl-k-cb cpsl-k-g)
;;; the terms of the product series typed, and dominated by the terms of G
(define (cpsl-k-ab! n)
  (let* ((a (list 'cf n)) (b (list 'cg n)) (ab (list 'cfg n))
         (ma (list 'magnitude a)) (mb (list 'magnitude b)) (mab (list 'magnitude ab))
         (rn (list 'power 'cpsrad_ n)) (tn (list 'power 'cpst_ n)) (qn (list 'power cpsl-k-q n))
         (kn (list 'power n 'cpsm_))
         (yn (list '* kn qn)) (xn (list '* ma tn))
         (cb cpsl-k-cb) (bb cpsl-k-b)
         (mamb (list '* ma mb)) (ckn (list '* 'cpsc_ kn)) (macn (list '* ma ckn))
         (l1a (list '* mamb rn)) (l1b (list '* macn rn))
         (yx (list '* yn xn)) (cyx (list '* 'cpsc_ yx)) (bx (list '* bb xn)) (cbx (list '* 'cpsc_ bx))
         (cbxn (list '* cb xn)) (mabr (list '* mab rn)))
    (fact 'fun-apply-type-c 'cf 'NN 'CC n)
    (fact 'fun-apply-type-c 'cg 'NN 'CC n)
    (fact 'fun-apply-type-c 'cfg 'NN 'CC n)
    (for-each (lambda (z) (fact 'cc-magnitude-closed z) (fact 'cc-magnitude-nonneg z)) (list a b ab))
    (fact 'nn-in-rr n)
    (fact 'power-real-closed 'cpsrad_ n)
    (fact 'power-real-closed 'cpst_ n)
    (fact 'power-real-closed cpsl-k-q n)
    (fact 'power-real-closed n 'cpsm_)
    (fact 'rr-power-nonneg n 'cpsrad_)
    (fact 'rr-power-nonneg n 'cpst_)
    (for-each (lambda (pr) (fact 'rr-mul-in-rr (car pr) (cadr pr)))
              (list (list kn qn) (list ma tn) (list ma mb) (list 'cpsc_ kn) (list ma ckn) (list mamb rn)
                    (list macn rn) (list yn xn) (list 'cpsc_ yx) (list bb xn) (list 'cpsc_ bx) (list cb xn)
                    (list mab rn)))
    (inst+ cpsl-prod n)
    (have! (list 'AND (list 'IN a 'CC) (list 'IN b 'CC)))
    (fact 'cc-magnitude-mul a b)
    (have! (list '= mab mamb)
      (lambda () (subst (list '= ab (list '* a b))) (ass)))
    (inst+ cpsl-bound n)
    (have! (list 'AND (list '<= 0 ma) (list '<= mb ckn)))
    (fact 'rr-le-scale-nonneg ma mb ckn)
    (fact 'rr-mul-le-right mamb macn rn)
    (have! (list '= rn (list '* qn tn))
      (lambda ()
        (subst (list '= 'cpsrad_ (list '* cpsl-k-q 'cpst_)))
        (fact 'rr-power-mul-base n cpsl-k-q 'cpst_)
        (ass)))
    (have! (list '= l1b cyx)
      (lambda () (subst (list '= rn (list '* qn tn))) (crs)))
    (inst+ cpsl-k-bd n)
    (have! (list 'AND (list 'IN ma 'RR) (list 'IN tn 'RR)))
    (have! (list 'AND (list '<= 0 ma) (list '<= 0 tn)))
    (fact 'rr-leq-mul-nonneg ma tn)
    (fact 'rr-mul-le-right yn bb xn)
    (have! (list 'AND '(<= 0 cpsc_) (list '<= yx bx)))
    (fact 'rr-le-scale-nonneg 'cpsc_ yx bx)
    (have! (list '= cbx cbxn) (lambda () (crs)))
    (have! (list '= mabr l1a) (lambda () (subst (list '= mab mamb)) (rfl)))
    (have! (list 'AND (list 'IN mab 'RR) (list 'IN rn 'RR)))
    (have! (list 'AND (list '<= 0 mab) (list '<= 0 rn)))
    (fact 'rr-leq-mul-nonneg mab rn)
    (if (not (dk-asm? (list '<= mabr cbxn)))
        (have! (list '<= mabr cbxn)
          (lambda () (dk-ineq! (list '= mabr l1a) (list '<= l1a l1b) (list '= l1b cyx)
                               (list '<= cyx cbx) (list '= cbx cbxn)))))))
(have! (list 'IN (cpsl-fab 'cpsrad_) '(FUN NN RR))
  (lambda () (dk-lam-t!) (let ((k (dk-di-var!))) (cpsl-k-ab! k) (ass))))
(detach-with! (dk-fact! 'comparison-test (cpsl-fab 'cpsrad_) cpsl-k-g)
  (lambda ()
    (dk-conj-close!
      (lambda ()
        (if (eq? (cpsl-head (dk-goal)) 'FORALL)
            (let ((n (dk-di-var!)))
              (cpsl-k-ab! n)
              (dk-lam-b!)
              (dk-conj-close! (lambda () (ass))))
            (ass))))))
(ass)
(qed 'cps-factor-conv)

;;; ---- LEMMA 2.9 --------------------------------------------------------------
(sp (make-wff
  (list 'FORALL 'cf (list 'IMPLIES '(IN cf (FUN NN CC))
    (list 'FORALL 'cg (list 'IMPLIES '(IN cg (FUN NN CC))
      (list 'FORALL 'cfg (list 'IMPLIES '(IN cfg (FUN NN CC))
        (list 'IMPLIES cpsl-prod
          (list 'FORALL 'cpsc_ (list 'IMPLIES '(IN cpsc_ RR)
            (list 'FORALL 'cpsm_ (list 'IMPLIES '(IN cpsm_ NN)
              (list 'IMPLIES cpsl-bound '(<= (CPS-RADIUS cf) (CPS-RADIUS cfg))))))))))))))))
(dk-peel!)
(mac 'CPS-RADIUS)
(define cpsl-n-sa (cadr (cadr (dk-goal))))
(define cpsl-n-sab (cadr (caddr (dk-goal))))
(define cpsl-n-eab (list 'ESUP cpsl-n-sab))
(cpsl-S-setup! cpsl-n-sa)
(define cpsl-n-up (cpsl-S-setup! cpsl-n-sab))
(have! (list 'AND (list 'IN cpsl-n-eab 'RR-POS-STAR)
             (list 'FORALL 'cpsx_ (list 'IMPLIES (list 'IN 'cpsx_ cpsl-n-sa) (list '<= 'cpsx_ cpsl-n-eab))))
  (lambda ()
    (dk-conj-close!
      (lambda ()
        (if (eq? (cpsl-head (dk-goal)) 'FORALL)
            (let* ((x (dk-di-var!))
                   (dummy (cpsl-S-elim! cpsl-n-sa x))
                   (c1 (list 'AND (list 'IN cpsl-n-eab 'RR) (list '<= 0 cpsl-n-eab)))
                   (dj (dk-project! (list 'OR c1 (list '= cpsl-n-eab 'POS-INF)) 'rr-pos-star-membership
                                    (list 'IN cpsl-n-eab 'RR-POS-STAR))))
              (use-cases dj
                (lambda ()
                  (dk-split! (dk-ctx-form c1))
                  (pbc)
                  (fact 'rr-not-le-lt x cpsl-n-eab)
                  (fact 'rr-add-in-rr cpsl-n-eab x)
                  (have! '(IN 1/2 RR) (lambda () (arith)))
                  (fact 'rr-mul-in-rr 1/2 (list '+ cpsl-n-eab x))
                  (let* ((half (list '* 1/2 (list '+ cpsl-n-eab x)))
                         (r (dk-name! half)))
                    (have! (list '<= 0 r) (lambda () (dk-ineq! (list '= r half) (list '<= 0 cpsl-n-eab) (list '< cpsl-n-eab x))))
                    (have! (list '< r x) (lambda () (dk-ineq! (list '= r half) (list '< cpsl-n-eab x))))
                    (have! (list '< cpsl-n-eab r) (lambda () (dk-ineq! (list '= r half) (list '< cpsl-n-eab x))))
                    (fact 'cps-factor-conv 'cf 'cg 'cfg 'cpsc_ 'cpsm_ x r)
                    (have! (list 'AND (list '<= 0 r) (list 'SERIES-CONVERGES (cpsl-fab r))))
                    (have! (list 'IN r cpsl-n-sab) (lambda () (dk-close-all! (lambda () (sep-mi)))))
                    (inst+ cpsl-n-up r)
                    (fact 'rr-lt-not-le cpsl-n-eab r)
                    (ai (list 'NOT (list '<= r cpsl-n-eab)))))
                (lambda ()
                  (subst (list '= cpsl-n-eab 'POS-INF))
                  (fact 'rr-subset-rr-star)
                  (fact 'subset-mem-fwd 'RR 'RR-STAR x)
                  (fact 'pos-inf-upper-bound x)
                  (ass))))
            (ass))))))
(fact 'esup-least cpsl-n-sa cpsl-n-eab)
(ass)
(qed 'cps-radius-factor)
