;;; clear-first-col-proof.scm -- Brick B3 (LA Phase B): clear the whole first column.
;;; The ROW-op mirror of clear-first-row: left-multiply by elementary row matrices.
;;;   pivot-clears-row -- one row op zeroes an off-pivot column-1 entry (i,1); the
;;;                       euclidean remainder is forced to vanish by class-minimality
;;;                       (mirror of pivot-clears-col, via pivot-row-reduce +
;;;                       elem-g-row-action + mat-equiv-left-mult).
;;;   clear-col-upto   -- ni on k: rows 2..k of column 1 cleared, pivot + ~ kept.
;;;   clear-first-col  -- clear-col-upto at k = m.
;;; Reuses mat-equiv-cod-is-mat + classmin-transport (clear-first-row-proof.scm).

(define (cc-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (cc-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (cc-foc! n) (set-proof-state-focus! *ps* n))
(define (cc-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (cc-find pred) (let lp ((as (cc-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (cc-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (cc-leaf-asms s) (map wff-formula (sequent-node-assumptions s)))
(define (cc-foc-by-asm! f)
  (let ((s (any-pred (lambda (s) (member f (cc-leaf-asms s))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (cc-di*) (let lp () (let* ((g (cc-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (di4) (di)(di)(di)(di))
(define (cc-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((use-or (cc-last)))
    (pbc)
    (cut `(NOT ,P))
    (let ((use-notp (cc-last)))
      (di)
      (cut `(OR ,P (NOT ,P)))
      (let ((use-or2 (cc-last))) (oi-l) (ass) (cc-foc! use-or2))
      (ai `(NOT (OR ,P (NOT ,P))))
      (cc-foc! use-notp))
    (cut `(OR ,P (NOT ,P)))
    (let ((use-or3 (cc-last))) (oi-r) (ass) (cc-foc! use-or3))
    (ai `(NOT (OR ,P (NOT ,P))))
    (cc-foc! use-or)))
(define (cc-cases P) (cc-em P) (ai `(OR ,P (NOT ,P))) (cc-last))
(define (cr-impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))
(define (cr-fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))
(define (cr-pcm P)
  (list 'FORALL 'C (list 'IMPLIES (list 'MAT-EQUIV 'A 'm 'n P 'C)
    (list 'FORALL 'ii (list 'FORALL 'jj
      (list 'IMPLIES '(IN ii (INTERVAL 1 m)) (list 'IMPLIES '(IN jj (INTERVAL 1 n))
        (list 'IMPLIES (list 'NOT (list '= '(ENTRY C ii jj) '(ZERO A)))
          (list '<= (list '(GAUGE A) (list 'ENTRY P 1 1)) '((GAUGE A) (ENTRY C ii jj)))))))))))

;; ===================== pivot-clears-row (mirror of pivot-clears-col) =====================
(define PR-CONCL
  (list 'FORSOME 'Q
    (list 'AND '(MAT-EQUIV A m n P Q)
      (list 'AND '(= (ENTRY Q 1 1) (ENTRY P 1 1))
        (list 'AND '(= (ENTRY Q i 1) (ZERO A))
          (cr-fa* '(rr c)
            (cr-impl* (list '(IN rr (INTERVAL 1 m)) '(IN c (INTERVAL 1 n)) '(NOT (= rr i)))
                      '(= (ENTRY Q rr c) (ENTRY P rr c)))))))))
(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-EUCLIDEAN-RING A)
    (cr-fa* '(m n P i)
      (cr-impl* (list '(IN P (MAT m n (CARR A))) '(IN 1 (INTERVAL 1 m)) '(IN 1 (INTERVAL 1 n))
                      '(IN i (INTERVAL 1 m)) '(NOT (= i 1)) '(NOT (= (ENTRY P 1 1) (ZERO A)))
                      (cr-pcm 'P))
                PR-CONCL))))))
(cc-di*)
(define PR-MINH (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'C)))))
(fact 'euclidean-ring-is-integral-domain 'A)
(fact 'integral-domain-is-commutative-ring 'A)
(fact 'commutative-ring-is-ring 'A)
(fact 'pivot-row-reduce 'A 'm 'n 'P 'i)
(ai 1) (ai 1) (ai 1) (ai 1) (ai 1)
(define PR-DIV (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
             (eq? (car (cadr z)) 'ENTRY) (pair? (cadr (cadr z))) (eq? (car (cadr (cadr z))) 'MATMUL)))))
(define PR-Q    (cadr (cadr PR-DIV)))          ; (MATMUL A (ELEM-G A m ((NEG A) q) i 1) P)
(define PR-R    (caddr PR-DIV))
(define PR-G    (caddr PR-Q))                  ; the ELEM-G (3rd arg of MATMUL A G P)
(define PR-NEGQ (list-ref PR-G 3))
(define PR-QE   (cadr PR-NEGQ))
(define PR-ORASM (cc-find (H? 'OR)))
(define PR-GR   (list '(GAUGE A) PR-R))
(define PR-GP11 (list '(GAUGE A) '(ENTRY P 1 1)))
(define PR-SUCCLE (list '<= (list 'succ PR-GR) PR-GP11))
(define PR-GLE  (list '<= PR-GP11 PR-GR))
(define PR-Qi1  (list 'ENTRY PR-Q 'i 1))
(fact 'ring-neg-in-carr 'A PR-QE)
(fact 'elem-g-invertible 'A 'm PR-NEGQ 'i 1)
(fact 'mat-equiv-left-mult 'A 'm 'n 'P PR-G)
(fact 'neq-sym 'i 1)                            ; NOT(= 1 i)  for the (i_idx=1) if-false
(ew PR-Q) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (ass)
(cc-foc-goal! (H? 'AND)) (di)
;; E11 : (ENTRY Q 1 1) = (ENTRY P 1 1)  (row 1 /= target row i)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY PR-Q 1 1)))))
(fact 'elem-g-row-action 'A 'm 'n 'P PR-NEGQ 'i 1 1 1)
(define PR-IF11 (list 'IF '(= 1 i)
   (list '(ADD A) '(ENTRY P i 1) (list '(MUL A) PR-NEGQ '(ENTRY P 1 1)))
   '(ENTRY P 1 1)))
(subst (list '= (list 'ENTRY PR-Q 1 1) PR-IF11))
(if-false PR-IF11) (define PR-K11 (cc-last)) (ass) (cc-foc! PR-K11)
(subst (list '= PR-IF11 '(ENTRY P 1 1)))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 1 1)
(rfl)
;; split Ei1 and ROWPRES
(cc-foc-goal! (H? 'AND)) (di)
;; Ei1 : (ENTRY Q i 1) = (ZERO A)  (the remainder vanishes)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) PR-Qi1))))
(define PR-NOTR0 (cc-cases (list '= PR-R '(ZERO A))))
(subst PR-DIV) (ass)
(cc-foc! PR-NOTR0)
(cut (list 'NOT (list '= PR-Qi1 '(ZERO A))))
(define PR-CONTMAIN (cc-last))
(subst PR-DIV) (ass)
(cc-foc! PR-CONTMAIN)
(ai PR-ORASM)
(cc-foc-by-asm! (list '= PR-R '(ZERO A)))
(ai (list 'NOT (list '= PR-R '(ZERO A))))
(cc-foc-by-asm! PR-SUCCLE)
(inst+ PR-MINH PR-Q)
(define PR-M2 (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'ii)))))
(inst+ PR-M2 'i)
(define PR-M3 (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'jj)))))
(inst+ PR-M3 1)
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 1 1)
(fact 'gauge-is-degree 'A) (ai 1)
(fact 'fun-apply-type-c '(GAUGE A) '(CARR A) 'NN PR-R)
(fact 'fun-apply-type-c '(GAUGE A) '(CARR A) 'NN '(ENTRY P 1 1))
(fact 'eq-sym PR-Qi1 PR-R)
(cut PR-GLE)
(define PR-CONT (cc-last))
(subst (list '= PR-R PR-Qi1))
(ass)
(cc-foc! PR-CONT)
(fact 'nn-succ-le-antisym PR-GR PR-GP11)
(ai (list 'NOT PR-GLE))
;; ROWPRES : every row rr /= i is preserved
(cc-foc-goal! (H? 'FORALL))
(cc-di*)
(define PR-GC (cc-goal))                       ; (= (ENTRY Q ROW COL) (ENTRY P ROW COL))
(define PR-ROW (list-ref (cadr PR-GC) 2))
(define PR-COL (list-ref (cadr PR-GC) 3))
(fact 'elem-g-row-action 'A 'm 'n 'P PR-NEGQ 'i 1 PR-ROW PR-COL)
(define PR-IFrc (list 'IF (list '= PR-ROW 'i)
   (list '(ADD A) (list 'ENTRY 'P 'i PR-COL) (list '(MUL A) PR-NEGQ (list 'ENTRY 'P 1 PR-COL)))
   (list 'ENTRY 'P PR-ROW PR-COL)))
(subst (list '= (list 'ENTRY PR-Q PR-ROW PR-COL) PR-IFrc))
(if-false PR-IFrc) (define PR-KC (cc-last)) (ass) (cc-foc! PR-KC)
(subst (list '= PR-IFrc (list 'ENTRY 'P PR-ROW PR-COL)))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P PR-ROW PR-COL)
(rfl)
(qed 'pivot-clears-row)
(category! 'pivot-clears-row 'algebra)

;; ===================== clear-col-upto (ni on k) =====================
(define (CU-CLEARED Q kk)
  (list 'FORALL 'i (cr-impl* (list '(IN i (INTERVAL 1 m)) '(NOT (= i 1)) (list '<= 'i kk))
                             (list '= (list 'ENTRY Q 'i 1) '(ZERO A)))))
(define (CU-BODY kk)
  (list 'FORSOME 'Q (list 'AND '(MAT-EQUIV A m n P Q)
    (list 'AND '(= (ENTRY Q 1 1) (ENTRY P 1 1)) (CU-CLEARED 'Q kk)))))
(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-EUCLIDEAN-RING A)
    (cr-fa* '(m n P)
      (cr-impl* (list '(IN P (MAT m n (CARR A))) '(IN 1 (INTERVAL 1 m))
                      '(IN 1 (INTERVAL 1 n)) '(NOT (= (ENTRY P 1 1) (ZERO A))) (cr-pcm 'P))
                (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (CU-BODY 'k)))))))))
(let lp () (let* ((g (cc-goal)) (h (and (pair? g) (car g))))
  (when (and (memq h '(FORALL IMPLIES)) (not (and (eq? h 'FORALL) (eq? (cadr g) 'k))))
    (di) (lp))))
(fact 'euclidean-ring-is-integral-domain 'A)
(fact 'integral-domain-is-commutative-ring 'A)
(fact 'commutative-ring-is-ring 'A)
(ni)

;; --- BASE : CU-BODY(0), witness Q = P ---
(cc-foc-goal! (H? 'FORSOME))
(ew 'P) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (fact 'mat-equiv-refl 'A 'm 'n 'P) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) '(ENTRY P 1 1)))))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 1 1) (rfl)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'i))))
(di4)
(define CU-BI (list-ref (cadr (cc-goal)) 2))
(fact 'interval-elt-in-nn 1 'm CU-BI)
(fact 'interval-lo 1 'm CU-BI)
(fact 'nn-not-le-zero-pos CU-BI)
(ai (list 'NOT (list '<= CU-BI 0)))

;; --- STEP : CU-BODY(k) => CU-BODY(succ k) ---
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'k))))
(di) (di) (di)
(define CU-IH (cc-find (H? 'FORSOME)))
(ai CU-IH) (ai 1) (ai 1)
(define CU-QwEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
                (eq? (car (cadr z)) 'ENTRY) (equal? (caddr z) '(ENTRY P 1 1))))))
(define CU-Qw (cadr (cadr CU-QwEQ)))
(define CU-CLK (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'i)))))
(define CU-VALID (list 'AND (list 'IN '(succ k) '(INTERVAL 1 m)) (list 'NOT (list '= '(succ k) 1))))
(define CU-NOTV (cc-cases CU-VALID))

;; VALIDCOL TRUE : clear row (succ k) via pivot-clears-row
(fact 'mat-equiv-cod-is-mat 'A 'm 'n 'P CU-Qw)
(fact 'classmin-transport 'A 'm 'n 'P CU-Qw)
(cut (list 'NOT (list '= (list 'ENTRY CU-Qw 1 1) '(ZERO A))))
(define CU-TVCONT (cc-last))
(subst CU-QwEQ) (ass)
(cc-foc! CU-TVCONT)
(ai CU-VALID)
(fact 'pivot-clears-row 'A 'm 'n CU-Qw '(succ k))
(ai 1) (ai 1) (ai 1) (ai 1)
(define CU-QpEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
                (eq? (car (cadr z)) 'ENTRY) (equal? (caddr z) (list 'ENTRY CU-Qw 1 1))))))
(define CU-Qp (cadr (cadr CU-QpEQ)))
(define CU-ROWS (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'rr)))))
(ew CU-Qp) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (fact 'mat-equiv-trans 'A 'm 'n 'P CU-Qw CU-Qp) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY CU-Qp 1 1)))))
(subst CU-QpEQ) (ass)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'i))))
(di4)
(define CU-TI (list-ref (cadr (cc-goal)) 2))
(fact 'interval-elt-in-nn 1 'm CU-TI)
(fact 'nn-le-succ-cases 'k CU-TI)
(define CU-TOR (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'OR) (equal? (caddr z) (list '= CU-TI '(succ k)))))))
(ai CU-TOR)
(cc-foc-by-asm! (list '<= CU-TI 'k))
(fact 'nn-le-imp-neq-succ 'k CU-TI)
(inst+ CU-ROWS CU-TI)
(define CU-ROWSc (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'c)))))
(inst+ CU-ROWSc 1)
(inst+ CU-CLK CU-TI)
(define CU-RPRES (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (equal? (cadr z) (list 'ENTRY CU-Qp CU-TI 1))))))
(subst CU-RPRES)
(ass)
(cc-foc-by-asm! (list '= CU-TI '(succ k)))
(subst (list '= CU-TI '(succ k)))
(ass)

;; VALIDCOL FALSE : keep Q = Qw
(cc-foc! CU-NOTV)
(ew CU-Qw) (di)
(cc-foc-by-asm! (list 'NOT CU-VALID))
(cc-foc-goal! (H? 'MAT-EQUIV)) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY CU-Qw 1 1)))))
(ass)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'i))))
(di4)
(define CU-FI (list-ref (cadr (cc-goal)) 2))
(fact 'interval-elt-in-nn 1 'm CU-FI)
(fact 'nn-le-succ-cases 'k CU-FI)
(define CU-FOR (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'OR) (equal? (caddr z) (list '= CU-FI '(succ k)))))))
(ai CU-FOR)
(cc-foc-by-asm! (list '<= CU-FI 'k))
(inst+ CU-CLK CU-FI)
(ass)
(cc-foc-by-asm! (list '= CU-FI '(succ k)))
(cut CU-VALID)
(define CU-FVCONT (cc-last))
(di)
(fact 'eq-sym CU-FI '(succ k))
(cc-foc-goal! (H? 'IN)) (subst (list '= '(succ k) CU-FI)) (ass)
(cc-foc-goal! (H? 'NOT)) (subst (list '= '(succ k) CU-FI)) (ass)
(cc-foc! CU-FVCONT)
(ai (list 'NOT CU-VALID))
(qed 'clear-col-upto)
(category! 'clear-col-upto 'algebra)

;; ===================== clear-first-col (clear-col-upto at k = m) =====================
(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-EUCLIDEAN-RING A)
    (cr-fa* '(m n P)
      (cr-impl* (list '(IN P (MAT m n (CARR A))) '(IN m NN) '(IN n NN)
                      '(IN 1 (INTERVAL 1 m)) '(IN 1 (INTERVAL 1 n))
                      '(NOT (= (ENTRY P 1 1) (ZERO A))) (cr-pcm 'P))
        (list 'FORSOME 'Q (list 'AND '(MAT-EQUIV A m n P Q)
          (list 'AND '(= (ENTRY Q 1 1) (ENTRY P 1 1))
            (list 'FORALL 'i (cr-impl* (list '(IN i (INTERVAL 1 m)) '(NOT (= i 1)))
                                       '(= (ENTRY Q i 1) (ZERO A)))))))))))))
(cc-di*)
(fact 'clear-col-upto 'A 'm 'n 'P)
(define FC-UP (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'k)))))
(inst+ FC-UP 'm)
(define FC-BODY (cc-find (H? 'FORSOME)))
(ai FC-BODY) (ai 1) (ai 1)
(define FC-QEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
               (eq? (car (cadr z)) 'ENTRY) (equal? (caddr z) '(ENTRY P 1 1))))))
(define FC-Q (cadr (cadr FC-QEQ)))
(define FC-CLK (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'i)))))
(ew FC-Q) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY FC-Q 1 1)))))
(ass)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'i))))
(di) (di) (di)
(define FC-I (list-ref (cadr (cc-goal)) 2))
(fact 'interval-hi 1 'm FC-I)
(inst+ FC-CLK FC-I)
(ass)
(qed 'clear-first-col)
(category! 'clear-first-col 'algebra)
