;;; clear-first-row-proof.scm -- Brick B3 (LA Phase B): clear the whole first row.
;;; Iterates pivot-clears-col across columns 2..n by NN-induction on the number of
;;; cleared columns, then instantiates at n.  With a class-minimal pivot at (1,1),
;;; the result is a matrix ~ P, same pivot, whose first row is zero off the pivot.
;;;
;;;   mat-equiv-cod-is-mat -- MAT-EQUIV(X,Y) => IN Y MAT  (typing along ~)
;;;   classmin-transport   -- transport class-minimality of the pivot along ~
;;;   clear-row-upto       -- ni on k: cols 2..k cleared, pivot + ~ maintained
;;;   clear-first-row      -- clear-row-upto at k = n (interval-hi drops the k-guard)
;;; Depends on pivot-clears-col, mat-equiv-{refl,trans}, the NN/interval order
;;; read-offs (order-lemmas.scm), class-min-pivot's shape.

(define (cc-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (cc-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (cc-foc! n) (set-proof-state-focus! *ps* n))
(define (cc-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (cc-find pred) (let lp ((as (cc-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (cc-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (cc-leaf-asms s) (map wff-formula (sequent-node-assumptions s)))
(define (cc-foc-by-asm! f)
  (let ((s (any-pred (lambda (s) (member f (cc-leaf-asms s))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (cc-di*) (let lp () (let* ((g (cc-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (di4) (di)(di)(di)(di))
(define (cc-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((use-or (cc-last)))
    (pbc)
    (cut `(NOT ,P))
    (let ((use-notp (cc-last)))
      (di)
      (cut `(OR ,P (NOT ,P)))
      (let ((use-or2 (cc-last))) (oi-l) (ass) (cc-foc! use-or2))
      (ai `(NOT (OR ,P (NOT ,P))))
      (cc-foc! use-notp))
    (cut `(OR ,P (NOT ,P)))
    (let ((use-or3 (cc-last))) (oi-r) (ass) (cc-foc! use-or3))
    (ai `(NOT (OR ,P (NOT ,P))))
    (cc-foc! use-or)))
(define (cc-cases P) (cc-em P) (ai `(OR ,P (NOT ,P))) (cc-last))
(define (cr-impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))
(define (cr-fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))
(define (cr-pcm P)
  (list 'FORALL 'C (list 'IMPLIES (list 'MAT-EQUIV 'A 'm 'n P 'C)
    (list 'FORALL 'ii (list 'FORALL 'jj
      (list 'IMPLIES '(IN ii (INTERVAL 1 m)) (list 'IMPLIES '(IN jj (INTERVAL 1 n))
        (list 'IMPLIES (list 'NOT (list '= '(ENTRY C ii jj) '(ZERO A)))
          (list '<= (list '(GAUGE A) (list 'ENTRY P 1 1)) '((GAUGE A) (ENTRY C ii jj)))))))))))

;; ===================== mat-equiv-cod-is-mat =====================
(sp (make-wff '(FORALL A (IMPLIES (IS-RING A) (FORALL m (FORALL n (FORALL X (FORALL Y
    (IMPLIES (IN X (MAT m n (CARR A)))
    (IMPLIES (MAT-EQUIV A m n X Y)
      (IN Y (MAT m n (CARR A)))))))))))))
(cc-di*)
(mac-h 'MAT-EQUIV '(MAT-EQUIV A m n X Y))
(ai 1) (ai 1) (ai 1) (ai 1)
(define YEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (eq? (cadr z) 'Y)))))
(define RHS (caddr YEQ))                      ; (MATMUL A (MATMUL A U X) V)
(define INNER (caddr RHS))                    ; (MATMUL A U X)
(define CU (caddr INNER))
(define CV (cadddr RHS))
(fact 'invertible-mat-is-mat 'A 'm CU)
(fact 'invertible-mat-is-mat 'A 'n CV)
(fact 'matmul-type 'A 'm 'm 'n CU 'X)
(fact 'matmul-type 'A 'm 'n 'n INNER CV)
(subst YEQ)
(ass)
(qed 'mat-equiv-cod-is-mat)
(category! 'mat-equiv-cod-is-mat 'plumbing)

;; ===================== classmin-transport =====================
(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-RING A)
    (cr-fa* '(m n P Q)
      (cr-impl* (list '(IN P (MAT m n (CARR A)))
                      '(MAT-EQUIV A m n P Q)
                      '(= (ENTRY Q 1 1) (ENTRY P 1 1))
                      (cr-pcm 'P))
                (cr-pcm 'Q)))))))
(cc-di*)
(define CT-GG (cc-goal))
(define CT-ECIJ (cadr (caddr CT-GG)))
(define CT-C (cadr CT-ECIJ)) (define CT-II (caddr CT-ECIJ)) (define CT-JJ (cadddr CT-ECIJ))
(define CT-PCMH (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'C)
                (let ((b (caddr z))) (and (pair? b) (eq? (car b) 'IMPLIES)
                  (equal? (list-ref (cadr b) 4) 'P)))))))
(fact 'mat-equiv-trans 'A 'm 'n 'P 'Q CT-C)
(inst+ CT-PCMH CT-C)
(define CT-PII (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'ii)))))
(inst+ CT-PII CT-II)
(define CT-PJJ (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'jj)))))
(inst+ CT-PJJ CT-JJ)
(subst '(= (ENTRY Q 1 1) (ENTRY P 1 1)))
(ass)
(qed 'classmin-transport)
(category! 'classmin-transport 'algebra)

;; ===================== clear-row-upto (ni on k) =====================
(define (RU-CLEARED Q kk)
  (list 'FORALL 'j (cr-impl* (list '(IN j (INTERVAL 1 n)) '(NOT (= j 1)) (list '<= 'j kk))
                             (list '= (list 'ENTRY Q 1 'j) '(ZERO A)))))
(define (RU-BODY kk)
  (list 'FORSOME 'Q (list 'AND '(MAT-EQUIV A m n P Q)
    (list 'AND '(= (ENTRY Q 1 1) (ENTRY P 1 1)) (RU-CLEARED 'Q kk)))))
(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-EUCLIDEAN-RING A)
    (cr-fa* '(m n P)
      (cr-impl* (list '(IN P (MAT m n (CARR A))) '(IN 1 (INTERVAL 1 m))
                      '(IN 1 (INTERVAL 1 n)) '(NOT (= (ENTRY P 1 1) (ZERO A))) (cr-pcm 'P))
                (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (RU-BODY 'k)))))))))
;; strip fixed hyps down to (FORALL k (IMPLIES (IN k NN) ...))
(let lp () (let* ((g (cc-goal)) (h (and (pair? g) (car g))))
  (when (and (memq h '(FORALL IMPLIES)) (not (and (eq? h 'FORALL) (eq? (cadr g) 'k))))
    (di) (lp))))
(fact 'euclidean-ring-is-integral-domain 'A)
(fact 'integral-domain-is-commutative-ring 'A)
(fact 'commutative-ring-is-ring 'A)
(ni)

;; --- BASE : RU-BODY(0), witness Q = P ---
(cc-foc-goal! (H? 'FORSOME))
(ew 'P) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (fact 'mat-equiv-refl 'A 'm 'n 'P) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) '(ENTRY P 1 1)))))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 1 1) (rfl)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'j))))
(di4)
(define RU-BJ (list-ref (cadr (cc-goal)) 3))
(fact 'interval-elt-in-nn 1 'n RU-BJ)
(fact 'interval-lo 1 'n RU-BJ)
(fact 'nn-not-le-zero-pos RU-BJ)
(ai (list 'NOT (list '<= RU-BJ 0)))

;; --- STEP : RU-BODY(k) => RU-BODY(succ k) ---
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'k))))
(di) (di) (di)                                     ; k ; IN k NN ; IH
(define RU-IH (cc-find (H? 'FORSOME)))
(ai RU-IH) (ai 1) (ai 1)
(define RU-QwEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
                (eq? (car (cadr z)) 'ENTRY) (equal? (caddr z) '(ENTRY P 1 1))))))
(define RU-Qw (cadr (cadr RU-QwEQ)))
(define RU-CLK (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'j)))))
(define RU-VALID (list 'AND (list 'IN '(succ k) '(INTERVAL 1 n)) (list 'NOT (list '= '(succ k) 1))))
(define RU-NOTV (cc-cases RU-VALID))

;; VALIDCOL TRUE : clear column (succ k) via pivot-clears-col
(fact 'mat-equiv-cod-is-mat 'A 'm 'n 'P RU-Qw)
(fact 'classmin-transport 'A 'm 'n 'P RU-Qw)
(cut (list 'NOT (list '= (list 'ENTRY RU-Qw 1 1) '(ZERO A))))
(define RU-TVCONT (cc-last))
(subst RU-QwEQ) (ass)
(cc-foc! RU-TVCONT)
(ai RU-VALID)
(fact 'neq-sym '(succ k) 1)
(fact 'pivot-clears-col 'A 'm 'n RU-Qw '(succ k))
(ai 1) (ai 1) (ai 1) (ai 1)
(define RU-QpEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
                (eq? (car (cadr z)) 'ENTRY) (equal? (caddr z) (list 'ENTRY RU-Qw 1 1))))))
(define RU-Qp (cadr (cadr RU-QpEQ)))
(define RU-COLS (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'ii)
                (let ((b (caddr z))) (and (pair? b) (eq? (car b) 'FORALL)))))))
(ew RU-Qp) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (fact 'mat-equiv-trans 'A 'm 'n 'P RU-Qw RU-Qp) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY RU-Qp 1 1)))))
(subst RU-QpEQ) (ass)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'j))))
(di4)
(define RU-TJ (list-ref (cadr (cc-goal)) 3))
(fact 'interval-elt-in-nn 1 'n RU-TJ)
(fact 'nn-le-succ-cases 'k RU-TJ)
(define RU-TOR (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'OR) (equal? (caddr z) (list '= RU-TJ '(succ k)))))))
(ai RU-TOR)
(cc-foc-by-asm! (list '<= RU-TJ 'k))
(fact 'nn-le-imp-neq-succ 'k RU-TJ)
(inst+ RU-COLS 1)
(define RU-COLSj (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'c)))))
(inst+ RU-COLSj RU-TJ)
(inst+ RU-CLK RU-TJ)
(define RU-CPRES (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (equal? (cadr z) (list 'ENTRY RU-Qp 1 RU-TJ))))))
(subst RU-CPRES)
(ass)
(cc-foc-by-asm! (list '= RU-TJ '(succ k)))
(subst (list '= RU-TJ '(succ k)))
(ass)

;; VALIDCOL FALSE : keep Q = Qw
(cc-foc! RU-NOTV)
(ew RU-Qw) (di)
(cc-foc-by-asm! (list 'NOT RU-VALID))
(cc-foc-goal! (H? 'MAT-EQUIV)) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY RU-Qw 1 1)))))
(ass)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'j))))
(di4)
(define RU-FJ (list-ref (cadr (cc-goal)) 3))
(fact 'interval-elt-in-nn 1 'n RU-FJ)
(fact 'nn-le-succ-cases 'k RU-FJ)
(define RU-FOR (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'OR) (equal? (caddr z) (list '= RU-FJ '(succ k)))))))
(ai RU-FOR)
(cc-foc-by-asm! (list '<= RU-FJ 'k))
(inst+ RU-CLK RU-FJ)
(ass)
(cc-foc-by-asm! (list '= RU-FJ '(succ k)))
(cut RU-VALID)
(define RU-FVCONT (cc-last))
(di)
(fact 'eq-sym RU-FJ '(succ k))
(cc-foc-goal! (H? 'IN)) (subst (list '= '(succ k) RU-FJ)) (ass)
(cc-foc-goal! (H? 'NOT)) (subst (list '= '(succ k) RU-FJ)) (ass)
(cc-foc! RU-FVCONT)
(ai (list 'NOT RU-VALID))
(qed 'clear-row-upto)
(category! 'clear-row-upto 'algebra)

;; ===================== clear-first-row (clear-row-upto at k = n) =====================
(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-EUCLIDEAN-RING A)
    (cr-fa* '(m n P)
      (cr-impl* (list '(IN P (MAT m n (CARR A))) '(IN m NN) '(IN n NN)
                      '(IN 1 (INTERVAL 1 m)) '(IN 1 (INTERVAL 1 n))
                      '(NOT (= (ENTRY P 1 1) (ZERO A))) (cr-pcm 'P))
        (list 'FORSOME 'Q (list 'AND '(MAT-EQUIV A m n P Q)
          (list 'AND '(= (ENTRY Q 1 1) (ENTRY P 1 1))
            (list 'FORALL 'j (cr-impl* (list '(IN j (INTERVAL 1 n)) '(NOT (= j 1)))
                                       '(= (ENTRY Q 1 j) (ZERO A)))))))))))))
(cc-di*)
(fact 'clear-row-upto 'A 'm 'n 'P)
(define FR-UP (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'k)))))
(inst+ FR-UP 'n)
(define FR-BODY (cc-find (H? 'FORSOME)))
(ai FR-BODY) (ai 1) (ai 1)
(define FR-QEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
               (eq? (car (cadr z)) 'ENTRY) (equal? (caddr z) '(ENTRY P 1 1))))))
(define FR-Q (cadr (cadr FR-QEQ)))
(define FR-CLK (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'j)))))
(ew FR-Q) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY FR-Q 1 1)))))
(ass)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'j))))
(di) (di) (di)
(define FR-J (list-ref (cadr (cc-goal)) 3))
(fact 'interval-hi 1 'n FR-J)
(inst+ FR-CLK FR-J)
(ass)
(qed 'clear-first-row)
(category! 'clear-first-row 'algebra)
