;;; det-alternating-form.scm -- Hoffman-Kunze 5.3 Theorem 2 (batch 26-B, 2026-09-24):
;;; an ALTERNATING n-LINEAR function D on the n x n matrices over a commutative ring
;;; R satisfies  D(A) = det(A) D(I)  for every A.  Proven WITHOUT permutations.
;;;
;;; THE PROPERTY is not a definition: it is written by the formula builders
;;; daf-fun / daf-lin / daf-alt below, in the shape of det-row-linear and
;;; det-alternating-rows (theorem-library/det-rows.scm) with (D X) in place of
;;; DET(R, n, X).
;;;
;;; THE ROUTE (induction on n; no permutation signs):
;;;   * the determinant is such a function (daf-det-fun/-lin/-alt), and so is
;;;     X |-> D(X Q) for any Q (daf-rm-*; X |-> det(X Q) is daf-det-rm-*), and so is
;;;     M |-> D(BORDER(1, M)) at the size below (daf-bd-*);
;;;   * a D-matrix with a zero row is 0 (daf-zero-row); interchanging two rows
;;;     negates D (daf-swap), hence D(F[k,l]) = - D(I) (daf-elem-f);
;;;   * CLEARING: if row 1 of Y is e_1, subtracting multiples of row 1 from the
;;;     other rows (column 1 cleared) does not change D (daf-clear), and the
;;;     cleared matrix is BORDER(1, M) for M its lower-right block (daf-bordered);
;;;   * the step: for Y with row 1 = e_1, D(Y) = det(M) D(I) by the induction
;;;     hypothesis at M |-> D(BORDER(1, M)) (daf-cl); for X with row 1 = e_j,
;;;     j /= 1, Y = X F[1,j] has row 1 = e_1 and X = Y F[1,j], so D(X) = det(M) D(F)
;;;     and det(X) = det(M) det(F) with the SAME M, and D(F) = - D(I), det F = -1
;;;     (daf-basis); a general A is reached by linearity in row 1, one entry at a
;;;     time (daf-psum: the partial rows (a_11, ..., a_1m, 0, ..., 0)).
;;;
;;; Helper prefix: daf-.  Binders the driver builds: df*_ (statement binders),
;;; dri_ / drk_ (the row clauses, as in det-rows.scm), dav_ / daw_ (matrix
;;; tabulations), ddl_ / dql_ / dbl_ (the lambda functions).

;;; =====================================================================
;;; The file's kit (copied from det-rows.scm, where it is file-local).
;;; =====================================================================
(define (daf-done! name)
  (if (not (proof-done? *ps*))
      (begin
        (display "\n*** det-alternating-form: ") (display name) (display " did NOT close.\n")
        (for-each (lambda (l)
                    (display ";;   leaf: ")
                    (display (expression->string (dk-goal-of l))) (newline))
                  (dk-open-leaves))))
  (qed name))

;; (daf-if-branch! retired 2026-09-25: the kit's dk-if-branch!)

;; (daf-case-if! retired 2026-09-25: the kit's dk-case-if!)

;; (daf-lift! retired 2026-09-25: the kit's dk-nn!)

;; (daf-nn! retired 2026-09-25: the kit's dk-nn!)

;; (daf-have! retired 2026-09-25: the kit's dk-have!)
;; (daf-nn-have! retired 2026-09-25: the kit's dk-have! + dk-nn!)

(define (daf-iv! i a b)
  (fact 'interval-elt-in-nn a b i)
  (fact 'interval-lo a b i)
  (fact 'interval-hi a b i))

(define (daf-in-iv! x a b terms prems)
  (dk-have! (list 'IN x (list 'INTERVAL a b)) (lambda ()
      (dk-have! (list '<= a x) (lambda () (apply dk-nn! prems)))
      (dk-have! (list '<= x b) (lambda () (apply dk-nn! prems)))
      (fact 'interval-mem-intro a b x)
      (ass))))

(define (daf-beta!) (if (dk--redex? (dk-goal)) (dk-lam-b!)))

;; (daf-chain! retired 2026-09-25: the kit's dk-chain!)

(define (daf-find-decided-if e)
  (cond ((not (pair? e)) #f)
        ((and (eq? (car e) 'IF) (= (length e) 4)
              (or (dk-asm? (cadr e)) (dk-asm? (list 'NOT (cadr e)))))
         (cons (dk-asm? (cadr e)) e))
        (#t (let loop ((l e))
              (cond ((not (pair? l)) #f)
                    ((daf-find-decided-if (car l)))
                    (#t (loop (cdr l))))))))
(define (daf-if-auto!)
  (let loop ()
    (let ((hit (daf-find-decided-if (dk-goal))))
      (if hit (begin (dk-if-branch! (car hit) (cdr hit) #f (lambda () #t)) (loop))))))

(define (daf-absurd! prems)
  (dk-have! '(<= 1 0) (lambda () (apply dk-nn! prems)))
  (dk-focus-having! '(<= 1 0))
  (have! '(NOT (<= 1 0)) (lambda () (arith)))
  (dk-focus-having! '(NOT (<= 1 0)))
  (pbc)
  (ai '(NOT (<= 1 0))))

;; (daf-pred! P N): with (IN P (INTERVAL 1 (succ N))), (IN N NN), (NOT (= P 1)):
;; land (IN Q (INTERVAL 1 N)) and (= P (succ Q)) for a fresh Q; return Q.
(define (daf-pred! p n)
  (daf-iv! p 1 (list 'succ n))
  (dk-have! (list 'NOT (list '= p 0)) (lambda () (apply dk-nn! (list (list '<= 1 p)))))
  (let ((q (dk-skolem! (dk-fact! 'nn-nonzero-is-succ p))))
    (let ((peq (list '= p (list 'succ q))))
      (dk-have! (list 'NOT (list '= q 0)) (lambda ()
          (di)
          (have! (list '= p 1)
            (lambda () (apply dk-nn! (list peq (list '= q 0)))))
          (ai (list 'NOT (list '= p 1)))))
      (dk-one-le! q)
      (daf-in-iv! q 1 n (list q p n (list 'succ q) (list 'succ n))
                  (list peq (list '<= p (list 'succ n)) (list '<= 1 q)))
      q)))

;; (daf-neq! A B TERMS PREMS): prove (NOT (= A B)) from NN facts: assume A = B,
;; derive the equation CONTRA (whose negation is in context) by ineq, NOT-elim.
(define (daf-neq-via! a b contra terms prems)
  (dk-have! (list 'NOT (list '= a b)) (lambda ()
      (di)
      (have! contra (lambda () (apply dk-nn! (cons (list '= a b) prems))))
      (ai (list 'NOT contra)))))

(define (daf-ctx f)
  (or (dk-ctx-form f) (error "daf-ctx: not in context" (expression->string f))))

(define (daf-tsubst e alist)
  (cond ((assq e alist) => cdr)
        ((pair? e) (map (lambda (x) (daf-tsubst x alist)) e))
        (#t e)))

(define daf-ag   '(RING-ADDITIVE-AG R))
(define daf-neg1 '((NEG R) (ONE R)))

;;; =====================================================================
;;; The property, as formula builders (NOT a def-predicate).
;;; =====================================================================
(define (daf-mat n) (list 'MAT n n '(CARR R)))
(define (daf-iv n) (list 'INTERVAL 1 n))
(define (daf-rowhyp X Y p n)        ; rows of X and Y agree off row p
  (list 'FORALL 'dri_ (list 'IMPLIES (list 'IN 'dri_ (daf-iv n))
    (list 'IMPLIES (list 'NOT (list '= 'dri_ p))
      (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv n))
        (list '= (list 'ENTRY X 'dri_ 'drk_) (list 'ENTRY Y 'dri_ 'drk_))))))))
(define (daf-combhyp C A B p sc n)  ; row p of C is sc * (row p of A) + row p of B
  (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv n))
    (list '= (list 'ENTRY C p 'drk_)
             (list '(ADD R) (list '(MUL R) sc (list 'ENTRY A p 'drk_)) (list 'ENTRY B p 'drk_))))))
(define (daf-eqrows X p q n)        ; rows p and q of X are equal
  (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv n))
    (list '= (list 'ENTRY X p 'drk_) (list 'ENTRY X q 'drk_)))))
(define (daf-fun n D) (list 'IN D (list 'FUN (daf-mat n) '(CARR R))))
(define (daf-lin n D)
  (forall-guarded '(dfa_ dfb_ dfc_ dfp_ dfs_)
    (list (list 'IN 'dfa_ (daf-mat n)) (list 'IN 'dfb_ (daf-mat n)) (list 'IN 'dfc_ (daf-mat n))
          (list 'IN 'dfp_ (daf-iv n)) '(IN dfs_ (CARR R))
          (daf-rowhyp 'dfb_ 'dfa_ 'dfp_ n) (daf-rowhyp 'dfc_ 'dfa_ 'dfp_ n)
          (daf-combhyp 'dfc_ 'dfa_ 'dfb_ 'dfp_ 'dfs_ n))
    (list '= (list D 'dfc_)
             (list '(ADD R) (list '(MUL R) 'dfs_ (list D 'dfa_)) (list D 'dfb_)))))
(define (daf-alt n D)
  (forall-guarded '(dfa_ dfp_ dfq_)
    (list (list 'IN 'dfa_ (daf-mat n)) (list 'IN 'dfp_ (daf-iv n)) (list 'IN 'dfq_ (daf-iv n))
          '(NOT (= dfp_ dfq_)) (daf-eqrows 'dfa_ 'dfp_ 'dfq_ n))
    (list '= (list D 'dfa_) '(ZERO R))))
;; the whole hypothesis block, for a D alternating n-linear over R
(define (daf-form-hyps n D)
  (list '(IS-COMMUTATIVE-RING R) (daf-fun n D) (daf-lin n D) (daf-alt n D)))

;;; lambda functions
(define (daf-DL n)   (list 'VNB-LAMBDA 'ddl_ (daf-mat n) (list 'DET 'R n 'ddl_)))
(define (daf-DQ n D Q) (list 'VNB-LAMBDA 'dql_ (daf-mat n) (list D (list 'MATMUL 'R 'dql_ Q))))
(define (daf-DQdet n Q) (list 'VNB-LAMBDA 'dql_ (daf-mat n) (list 'DET 'R n (list 'MATMUL 'R 'dql_ Q))))
(define (daf-DB n D) (list 'VNB-LAMBDA 'dbl_ (daf-mat n)
                       (list D (list 'BORDER 'R '(ONE R) 'dbl_ n n))))

;;; =====================================================================
;;; (1) ring identities (crs, cited so the matrix terms stay atoms)
;;; =====================================================================
(define (daf-carr-guards vs) (map (lambda (v) (list 'IN v '(CARR R))) vs))
;; (s a + b) q = s (a q) + b q
(sp (make-wff
  (list 'FORALL 'R (list 'IMPLIES '(IS-COMMUTATIVE-RING R)
    (forall-guarded '(dfs_ dfx_ dfy_ dfz_) (daf-carr-guards '(dfs_ dfx_ dfy_ dfz_))
      '(= ((MUL R) ((ADD R) ((MUL R) dfs_ dfx_) dfy_) dfz_)
          ((ADD R) ((MUL R) dfs_ ((MUL R) dfx_ dfz_)) ((MUL R) dfy_ dfz_))))))))
(dk-peel!)
(crs)
(daf-done! 'daf-ring-rdist)
(topic! 'daf-ring-rdist 'plumbing)

;; x = s 0 + y  =>  y = x
(sp (make-wff
  (list 'FORALL 'R (list 'IMPLIES '(IS-COMMUTATIVE-RING R)
    (forall-guarded '(dfs_ dfx_ dfy_)
      (append (daf-carr-guards '(dfs_ dfx_ dfy_))
              (list '(= dfx_ ((ADD R) ((MUL R) dfs_ (ZERO R)) dfy_))))
      '(= dfy_ dfx_))))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'ring-zero-in 'R)
(have! '(= dfx_ dfy_)
  (lambda ()
    (subst '(= dfx_ ((ADD R) ((MUL R) dfs_ (ZERO R)) dfy_)))
    (crs)))
(subst '(= dfy_ dfx_))
(rfl)
(daf-done! 'daf-ring-cancel0)
(topic! 'daf-ring-cancel0 'plumbing)

;;; =====================================================================
;;; (2) the determinant is an alternating n-linear function
;;; =====================================================================
;; land (IN LAM (FUN DOM COD)): lam-t, peel the point v, beta, (THUNK v).
(define (daf-fun! lam dom cod thunk)
  (dk-have! (list 'IN lam (list 'FUN dom cod)) (lambda ()
      (if (and (pair? dom) (eq? (car dom) 'MAT))
          (begin (fact 'ring-carr-in-set 'R) (fact 'mat-is-set '(CARR R) (cadr dom) (caddr dom))))
      (dk-lam-t!)
      (let ((v (dk-di-var!)))
        (daf-beta!)
        (thunk v)))))

(sp (make-wff
  (forall-guarded '(R n) '((IS-COMMUTATIVE-RING R) (IN n NN))
    (daf-fun 'n (daf-DL 'n)))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(daf-fun! (daf-DL 'n) (daf-mat 'n) '(CARR R)
  (lambda (v) (fact 'det-in-carrier 'R 'n v) (ass)))
(daf-done! 'daf-det-fun)
(topic! 'daf-det-fun 'algebra)

;; the (IN x (INTERVAL 1 N)) hypotheses landed by a peel, in order
(define (daf-iv-vars landed N)
  (reverse (map cadr (filter (lambda (f) (and (pair? f) (eq? (car f) 'IN) (symbol? (cadr f))
                                     (equal? (caddr f) (daf-iv N))))
                    landed))))

(sp (make-wff
  (forall-guarded '(R n) '((IS-COMMUTATIVE-RING R) (IN n NN))
    (daf-lin 'n (daf-DL 'n)))))
(define daf-dl-hyps (dk-peel!))
(fact 'commutative-ring-is-ring 'R)
(dk-lam-b!)
(let* ((g (dk-goal))
       (c (cadddr (cadr g)))
       (s (cadr (cadr (caddr g))))
       (a (cadddr (caddr (cadr (caddr g)))))
       (b (cadddr (caddr (caddr g))))
       (p (car (daf-iv-vars daf-dl-hyps 'n))))
  (fact 'det-row-linear 'R 'n a b c p s)
  (ass))
(daf-done! 'daf-det-lin)
(topic! 'daf-det-lin 'algebra)

(sp (make-wff
  (forall-guarded '(R n) '((IS-COMMUTATIVE-RING R) (IN n NN))
    (daf-alt 'n (daf-DL 'n)))))
(define daf-da-hyps (dk-peel!))
(dk-lam-b!)
(let* ((a (cadddr (cadr (dk-goal))))
       (pq (daf-iv-vars daf-da-hyps 'n)))
  (dk-chain! (dk-fact! 'det-alternating-rows 'R 'n a (car pq) (cadr pq)) (lambda (ante) (lambda () (ass))))
  (ass))
(daf-done! 'daf-det-alt)
(topic! 'daf-det-alt 'algebra)

;;; =====================================================================
;;; (3) right multiplication: rows of X Q are linear in the rows of X
;;; =====================================================================
;; the typing guard of matmul-type at three equal sizes N
(define (daf-mm-guard! N)
  (dk-have! (list 'IMPLIES (list '= N 0) (list 'OR (list '= N 0) (list '= N 0))) (lambda () (prop))))
(define (daf-mm-type! X Q N)
  (daf-mm-guard! N)
  (fact 'matmul-type 'R N N N X Q))
;; rewrite ENTRY(MATMUL R X Q, i, k) in the goal by matmul-entry; return the summand lambda
(define (daf-mm-entry! X Q i k N)
  (let ((e (dk-fact! 'matmul-entry 'R N N N X Q i k)))
    (subst e)
    (caddr (caddr e))))
(define (daf-type-entry! e N)          ; e = (ENTRY M i k), M N-square
  (fact 'entry-in-carrier N N '(CARR R) (cadr e) (caddr e) (cadddr e)))
(define (daf-mm-setup! i)
  (fact 'commutative-ring-is-ring 'R)
  (daf-iv! i 1 'n)
  (dk-have! '(<= 1 n) (lambda () (apply dk-nn! (list (list '<= 1 i) (list '<= i 'n)))))
  (fact 'ring-additive-ag-is-abelian-group 'R)
  (fact 'ras-carr 'R)
  (fact 'interval-in-set 1 'n)
  (fact 'interval-card-in-nn 1 'n))
(define (daf-type-prod! a b)
  (daf-type-entry! a 'n) (daf-type-entry! b 'n)
  (fact 'ring-carrier-closed-mul 'R a b))

;; equal rows give equal rows of the product
(sp (make-wff
  (forall-guarded '(R n X Y Q dfi_ dfj_ dfk_)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (list 'IN 'X (daf-mat 'n)) (list 'IN 'Y (daf-mat 'n))
          (list 'IN 'Q (daf-mat 'n)) (list 'IN 'dfi_ (daf-iv 'n)) (list 'IN 'dfj_ (daf-iv 'n))
          (list 'IN 'dfk_ (daf-iv 'n))
          (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv 'n))
                                     '(= (ENTRY X dfi_ drk_) (ENTRY Y dfj_ drk_)))))
    '(= (ENTRY (MATMUL R X Q) dfi_ dfk_) (ENTRY (MATMUL R Y Q) dfj_ dfk_)))))
(define daf-mre-hyps (dk-peel!))
(define daf-mre-row (find-first (dk-head? 'FORALL) daf-mre-hyps))
(daf-mm-setup! 'dfi_)
(let* ((LX (daf-mm-entry! 'X 'Q 'dfi_ 'dfk_ 'n))
       (LY (daf-mm-entry! 'Y 'Q 'dfj_ 'dfk_ 'n)))
  (dk-chain! (dk-fact! 'finsum-congruence daf-ag (daf-iv 'n) LX LY) (lambda (ante)
      (let ((body (caddr (caddr ante))))
        (if (eq? (car body) '=)
            (lambda ()
              (let ((v (dk-di-var!)))
                (daf-beta!)
                (dk-apply! daf-mre-row v)
                (subst (list '= (list 'ENTRY 'X 'dfi_ v) (list 'ENTRY 'Y 'dfj_ v)))
                (daf-type-prod! (list 'ENTRY 'Y 'dfj_ v) (list 'ENTRY 'Q v 'dfk_))
                (rfl)))
            (lambda ()
              (let ((v (dk-di-var!)))
                (daf-beta!)
                (daf-type-prod! (list 'ENTRY 'X 'dfi_ v) (list 'ENTRY 'Q v 'dfk_))
                (subst (list '= (list 'CARR daf-ag) '(CARR R)))
                (ass)))))))
  (ass))
(daf-done! 'daf-mm-row-eq)
(topic! 'daf-mm-row-eq 'algebra)

;; a row combination passes to the product
(sp (make-wff
  (forall-guarded '(R n A B C Q dfp_ dfs_ dfk_)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (list 'IN 'A (daf-mat 'n)) (list 'IN 'B (daf-mat 'n))
          (list 'IN 'C (daf-mat 'n)) (list 'IN 'Q (daf-mat 'n)) (list 'IN 'dfp_ (daf-iv 'n))
          '(IN dfs_ (CARR R)) (list 'IN 'dfk_ (daf-iv 'n))
          (daf-combhyp 'C 'A 'B 'dfp_ 'dfs_ 'n))
    '(= (ENTRY (MATMUL R C Q) dfp_ dfk_)
        ((ADD R) ((MUL R) dfs_ (ENTRY (MATMUL R A Q) dfp_ dfk_)) (ENTRY (MATMUL R B Q) dfp_ dfk_))))))
(dk-peel!)
(define daf-mrl-comb (daf-ctx (daf-combhyp 'C 'A 'B 'dfp_ 'dfs_ 'n)))
(daf-mm-setup! 'dfp_)
(let* ((LC (daf-mm-entry! 'C 'Q 'dfp_ 'dfk_ 'n))
       (LA (daf-mm-entry! 'A 'Q 'dfp_ 'dfk_ 'n))
       (LB (daf-mm-entry! 'B 'Q 'dfp_ 'dfk_ 'n)))
  (dk-chain! (dk-fact! 'dtr-finsum-lin 'R (daf-iv 'n) 'dfs_ LA LB LC) (lambda (ante)
      (let ((body (caddr (caddr ante))))
        (if (eq? (car body) 'IN)
            (let ((X (if (equal? (car (cadr body)) LA) 'A 'B)))
              (lambda ()
                (let ((v (dk-di-var!)))
                  (daf-beta!)
                  (daf-type-prod! (list 'ENTRY X 'dfp_ v) (list 'ENTRY 'Q v 'dfk_))
                  (ass))))
            (lambda ()
              (let ((v (dk-di-var!)))
                (daf-beta!)
                (dk-apply! daf-mrl-comb v)
                (subst (list '= (list 'ENTRY 'C 'dfp_ v)
                             (list '(ADD R) (list '(MUL R) 'dfs_ (list 'ENTRY 'A 'dfp_ v))
                                   (list 'ENTRY 'B 'dfp_ v))))
                (daf-type-entry! (list 'ENTRY 'A 'dfp_ v) 'n)
                (daf-type-entry! (list 'ENTRY 'B 'dfp_ v) 'n)
                (daf-type-entry! (list 'ENTRY 'Q v 'dfk_) 'n)
                (fact 'daf-ring-rdist 'R 'dfs_ (list 'ENTRY 'A 'dfp_ v) (list 'ENTRY 'B 'dfp_ v)
                      (list 'ENTRY 'Q v 'dfk_))
                (ass)))))))
  (ass))
(daf-done! 'daf-mm-row-lin)
(topic! 'daf-mm-row-lin 'algebra)

;;; ---- X |-> D(X Q) and X |-> det(X Q) are alternating n-linear
;; after the peel and beta, the goal of a linearity proof is
;;   (= (F (MATMUL R c Q)) ((ADD R) ((MUL R) s (F (MATMUL R a Q))) (F (MATMUL R b Q))))
;; with F = D or DET R n; return (a b c s).
(define (daf-lin-parts g)
  (let* ((lhs (cadr g)) (rhs (caddr g)))
    (list (last (caddr (cadr rhs))) (last (caddr rhs)) (last lhs) (cadr (cadr rhs)))))

(define (daf-rm-lin-body! hyps start)
  (fact 'commutative-ring-is-ring 'R)
  (dk-lam-b!)
  (let* ((parts (daf-lin-parts (dk-goal)))
         (a (caddr (car parts))) (b (caddr (cadr parts))) (c (caddr (caddr parts)))
         (s (cadddr parts))
         (p (car (daf-iv-vars hyps 'n)))
         (mq (lambda (X) (list 'MATMUL 'R X 'Q))))
    (for-each (lambda (X) (daf-mm-type! X 'Q 'n)) (list a b c))
    (dk-chain! (start (mq a) (mq b) (mq c) p s) (lambda (ante)
        (if (eq? (cadr ante) 'dri_)
            (lambda ()
              (let* ((i (dk-di-var!))
                     (ne (dk-landed-1 (lambda () (di))))
                     (k (dk-di-var!))
                     (X (caddr (cadr (cadr (dk-goal))))))
                (dk-apply! (daf-ctx (daf-rowhyp X a p 'n)) i)
                (fact 'daf-mm-row-eq 'R 'n X a 'Q i i k)
                (ass)))
            (lambda ()
              (let ((k (dk-di-var!)))
                (fact 'daf-mm-row-lin 'R 'n a b c 'Q p s k)
                (ass))))))
    (ass)))

(define (daf-rm-alt-body! hyps start)
  (fact 'commutative-ring-is-ring 'R)
  (dk-lam-b!)
  (let* ((aq (last (cadr (dk-goal)))) (a (caddr aq))
         (pq (daf-iv-vars hyps 'n)) (p (car pq)) (q (cadr pq)))
    (daf-mm-type! a 'Q 'n)
    (dk-chain! (start aq p q) (lambda (ante)
        (lambda ()
          (let ((k (dk-di-var!)))
            (fact 'daf-mm-row-eq 'R 'n a a 'Q p q k)
            (ass)))))
    (ass)))

(sp (make-wff
  (forall-guarded '(R n D Q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun 'n 'D) (list 'IN 'Q (daf-mat 'n)))
    (daf-fun 'n (daf-DQ 'n 'D 'Q)))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(daf-fun! (daf-DQ 'n 'D 'Q) (daf-mat 'n) '(CARR R)
  (lambda (v)
    (daf-mm-type! v 'Q 'n)
    (fact 'fun-apply-type-c 'D (daf-mat 'n) '(CARR R) (list 'MATMUL 'R v 'Q))
    (ass)))
(daf-done! 'daf-rm-fun)
(topic! 'daf-rm-fun 'algebra)

(sp (make-wff
  (forall-guarded '(R n D Q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun 'n 'D) (daf-lin 'n 'D) (list 'IN 'Q (daf-mat 'n)))
    (daf-lin 'n (daf-DQ 'n 'D 'Q)))))
(daf-rm-lin-body! (dk-peel!)
  (lambda (aq bq cq p s) (inst*! (daf-ctx (daf-lin 'n 'D)) aq bq cq p s)))
(daf-done! 'daf-rm-lin)
(topic! 'daf-rm-lin 'algebra)

(sp (make-wff
  (forall-guarded '(R n D Q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun 'n 'D) (daf-alt 'n 'D) (list 'IN 'Q (daf-mat 'n)))
    (daf-alt 'n (daf-DQ 'n 'D 'Q)))))
(daf-rm-alt-body! (dk-peel!)
  (lambda (aq p q) (inst*! (daf-ctx (daf-alt 'n 'D)) aq p q)))
(daf-done! 'daf-rm-alt)
(topic! 'daf-rm-alt 'algebra)

(sp (make-wff
  (forall-guarded '(R n Q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (list 'IN 'Q (daf-mat 'n)))
    (daf-fun 'n (daf-DQdet 'n 'Q)))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(daf-fun! (daf-DQdet 'n 'Q) (daf-mat 'n) '(CARR R)
  (lambda (v)
    (daf-mm-type! v 'Q 'n)
    (fact 'det-in-carrier 'R 'n (list 'MATMUL 'R v 'Q))
    (ass)))
(daf-done! 'daf-det-rm-fun)
(topic! 'daf-det-rm-fun 'algebra)

(sp (make-wff
  (forall-guarded '(R n Q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (list 'IN 'Q (daf-mat 'n)))
    (daf-lin 'n (daf-DQdet 'n 'Q)))))
(daf-rm-lin-body! (dk-peel!)
  (lambda (aq bq cq p s) (dk-fact! 'det-row-linear 'R 'n aq bq cq p s)))
(daf-done! 'daf-det-rm-lin)
(topic! 'daf-det-rm-lin 'algebra)

(sp (make-wff
  (forall-guarded '(R n Q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (list 'IN 'Q (daf-mat 'n)))
    (daf-alt 'n (daf-DQdet 'n 'Q)))))
(daf-rm-alt-body! (dk-peel!)
  (lambda (aq p q) (dk-fact! 'det-alternating-rows 'R 'n aq p q)))
(daf-done! 'daf-det-rm-alt)
(topic! 'daf-det-rm-alt 'algebra)

;;; =====================================================================
;;; (4) a zero row gives D = 0
;;; =====================================================================
(define (daf-zrow A k n)
  (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv n))
    (list '= (list 'ENTRY A k 'drk_) '(ZERO R)))))
(sp (make-wff
  (forall-guarded '(R n D A dfk_)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun 'n 'D) (daf-lin 'n 'D)
          (list 'IN 'A (daf-mat 'n)) (list 'IN 'dfk_ (daf-iv 'n)) (daf-zrow 'A 'dfk_ 'n))
    '(= (D A) (ZERO R)))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'ring-one-in 'R)
(fact 'ring-zero-in 'R)
(fact 'ring-neg-in-carr 'R '(ONE R))
(dk-chain! (inst*! (daf-ctx (daf-lin 'n 'D)) 'A 'A 'A 'dfk_ daf-neg1) (lambda (ante)
    (if (eq? (cadr ante) 'dri_)
        (lambda ()
          (dk-peel!)
          (let ((g (dk-goal))) (daf-type-entry! (cadr g) 'n) (rfl)))
        (lambda ()
          (let ((c (dk-di-var!)))
            (dk-apply! (daf-ctx (daf-zrow 'A 'dfk_ 'n)) c)
            (subst (list '= (list 'ENTRY 'A 'dfk_ c) '(ZERO R)))
            (crs))))))
(fact 'fun-apply-type-c 'D (daf-mat 'n) '(CARR R) 'A)
(fact 'dtr-ring-negself 'R '(D A))
(ass)
(daf-done! 'daf-zero-row)
(topic! 'daf-zero-row 'algebra)

;;; =====================================================================
;;; (5) M |-> D(BORDER(1, M)) is alternating n-linear when D is (succ n)-so
;;; =====================================================================
(define (daf-bord X) (list 'BORDER 'R '(ONE R) X 'n 'n))
(define (daf-bd-setup!)
  (fact 'commutative-ring-is-ring 'R)
  (fact 'ring-one-in 'R)
  (fact 'ring-zero-in 'R)
  (fact 'nn-succ-closed 'n))
;; the matrices M of the (ENTRY (BORDER R (ONE R) M n n) _ _) subterms of E
(define (daf-bd-mats e)
  (let loop ((ts (dk-subterms e)) (acc '()))
    (cond ((null? ts) (reverse acc))
          ((and (pair? (car ts)) (eq? (car (car ts)) 'ENTRY) (pair? (cadr (car ts)))
                (eq? (car (cadr (car ts))) 'BORDER)
                (not (member (cadddr (cadr (car ts))) acc)))
           (loop (cdr ts) (cons (cadddr (cadr (car ts))) acc)))
          (#t (loop (cdr ts) acc)))))
;; rewrite every border entry of the goal by the theorem NAME at ARGS (after R ONE M n n)
(define (daf-bd-rw! name mats args)
  (for-each (lambda (M) (subst (apply dk-fact! name 'R '(ONE R) M 'n 'n args))) mats))
(define (daf-close-const!)
  (let ((g (dk-goal))) (if (equal? (cadr g) (caddr g)) (rfl) (crs))))
;; goal: an equation between border entries at (i, k), i and k eigenvariables in
;; [1, succ n].  Resolve the four cases; in the block case call (BLOCK! i1 k1).
(define (daf-bd-cases! i k block!)
  (let ((mats (daf-bd-mats (dk-goal))))
    (use-em (list '= i 1)
      (lambda ()
        (subst (list '= i 1))
        (use-em (list '= k 1)
          (lambda () (subst (list '= k 1)) (daf-bd-rw! 'border-entry-11 mats '()) (daf-close-const!))
          (lambda () (daf-bd-rw! 'border-entry-1j mats (list k)) (daf-close-const!))))
      (lambda ()
        (let ((i1 (daf-pred! i 'n)))
          (use-em (list '= k 1)
            (lambda () (subst (list '= k 1)) (daf-bd-rw! 'border-entry-i1 mats (list i)) (daf-close-const!))
            (lambda ()
              (let ((k1 (daf-pred! k 'n)))
                (subst (list '= i (list 'succ i1)))
                (subst (list '= k (list 'succ k1)))
                (daf-bd-rw! 'border-entry-block mats (list i1 k1))
                (block! i1 k1)))))))))
;; the same with the row fixed at (succ P), P in [1, n]
(define (daf-bd-row-cases! p k block!)
  (let ((mats (daf-bd-mats (dk-goal))))
    (dk-have! (list 'NOT (list '= (list 'succ p) 1)) (lambda () (apply dk-nn! (list (list '<= 1 p)))))
    (fact 'dtr-succ-in 'n p)
    (use-em (list '= k 1)
      (lambda () (subst (list '= k 1)) (daf-bd-rw! 'border-entry-i1 mats (list (list 'succ p)))
                 (daf-close-const!))
      (lambda ()
        (let ((k1 (daf-pred! k 'n)))
          (subst (list '= k (list 'succ k1)))
          (daf-bd-rw! 'border-entry-block mats (list p k1))
          (block! k1))))))

(sp (make-wff
  (forall-guarded '(R n D)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun '(succ n) 'D))
    (daf-fun 'n (daf-DB 'n 'D)))))
(dk-peel!)
(daf-bd-setup!)
(daf-fun! (daf-DB 'n 'D) (daf-mat 'n) '(CARR R)
  (lambda (v)
    (fact 'border-type 'R '(ONE R) v 'n 'n)
    (fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) (daf-bord v))
    (ass)))
(daf-done! 'daf-bd-fun)
(topic! 'daf-bd-fun 'algebra)

(sp (make-wff
  (forall-guarded '(R n D)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun '(succ n) 'D) (daf-lin '(succ n) 'D))
    (daf-lin 'n (daf-DB 'n 'D)))))
(define daf-bl-hyps (dk-peel!))
(daf-bd-setup!)
(dk-lam-b!)
(let* ((parts (daf-lin-parts (dk-goal)))
       (a (cadddr (car parts))) (b (cadddr (cadr parts))) (c (cadddr (caddr parts)))
       (s (cadddr parts))
       (p (car (daf-iv-vars daf-bl-hyps 'n))))
  (daf-iv! p 1 'n)
  (fact 'dtr-succ-in 'n p)
  (for-each (lambda (X) (fact 'border-type 'R '(ONE R) X 'n 'n)) (list a b c))
  (dk-chain! (inst*! (daf-ctx (daf-lin '(succ n) 'D)) (daf-bord a) (daf-bord b) (daf-bord c)
                      (list 'succ p) s) (lambda (ante)
      (if (eq? (cadr ante) 'dri_)
          (lambda ()
            (let* ((i (dk-di-var!))
                   (ne (dk-landed-1 (lambda () (di))))
                   (k (dk-di-var!))
                   (X (cadddr (cadr (cadr (dk-goal))))))
              (daf-bd-cases! i k
                (lambda (i1 k1)
                  (daf-neq-via! i1 p (list '= i (list 'succ p))
                                (list i i1 p (list 'succ i1) (list 'succ p))
                                (list (list '= i (list 'succ i1))))
                  (dk-apply! (dk-apply! (daf-ctx (daf-rowhyp X a p 'n)) i1) k1)
                  (ass)))))
          (lambda ()
            (let ((k (dk-di-var!)))
              (daf-bd-row-cases! p k
                (lambda (k1)
                  (dk-apply! (daf-ctx (daf-combhyp c a b p s 'n)) k1)
                  (ass))))))))
  (ass))
(daf-done! 'daf-bd-lin)
(topic! 'daf-bd-lin 'algebra)

(sp (make-wff
  (forall-guarded '(R n D)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun '(succ n) 'D) (daf-alt '(succ n) 'D))
    (daf-alt 'n (daf-DB 'n 'D)))))
(define daf-ba-hyps (dk-peel!))
(daf-bd-setup!)
(dk-lam-b!)
(let* ((a (cadddr (last (cadr (dk-goal)))))
       (pq (daf-iv-vars daf-ba-hyps 'n)) (p (car pq)) (q (cadr pq)))
  (daf-iv! p 1 'n)
  (daf-iv! q 1 'n)
  (fact 'dtr-succ-in 'n p)
  (fact 'dtr-succ-in 'n q)
  (fact 'border-type 'R '(ONE R) a 'n 'n)
  (daf-neq-via! (list 'succ p) (list 'succ q) (list '= p q)
                (list p q (list 'succ p) (list 'succ q)) '())
  (dk-chain! (inst*! (daf-ctx (daf-alt '(succ n) 'D)) (daf-bord a) (list 'succ p) (list 'succ q)) (lambda (ante)
      (lambda ()
        (let* ((k (dk-di-var!))
               (mats (list a)))
          (dk-have! (list 'NOT (list '= (list 'succ q) 1)) (lambda () (apply dk-nn! (list (list '<= 1 q)))))
          (dk-have! (list 'NOT (list '= (list 'succ p) 1)) (lambda () (apply dk-nn! (list (list '<= 1 p)))))
          (use-em (list '= k 1)
            (lambda ()
              (subst (list '= k 1))
              (subst (dk-fact! 'border-entry-i1 'R '(ONE R) a 'n 'n (list 'succ p)))
              (subst (dk-fact! 'border-entry-i1 'R '(ONE R) a 'n 'n (list 'succ q)))
              (rfl))
            (lambda ()
              (let ((k1 (daf-pred! k 'n)))
                (subst (list '= k (list 'succ k1)))
                (subst (dk-fact! 'border-entry-block 'R '(ONE R) a 'n 'n p k1))
                (subst (dk-fact! 'border-entry-block 'R '(ONE R) a 'n 'n q k1))
                (dk-apply! (daf-ctx (daf-eqrows a p q 'n)) k1)
                (ass))))))))
  (ass))
(daf-done! 'daf-bd-alt)
(topic! 'daf-bd-alt 'algebra)

;;; =====================================================================
;;; The tabulation kit: auxiliary matrices MATOF(N, N, (dav_, daw_) |-> body),
;;; their typing and their entry read-offs.  daf-N is the size, set before use.
;;; =====================================================================
(define daf-N 'n)
(define (daf-I) (daf-iv daf-N))
(define (daf-mk body)
  (list 'MATOF daf-N daf-N
        (list 'VNB-LAMBDA '(LIST dav_ daw_) (list 'CARTESIAN (daf-I) (daf-I)) body)))

;; land (IN T (CARR R)) for T built of ENTRY M _ _ (M daf-N-square), ADD, MUL, NEG, ONE, ZERO
(define (daf-type-carr! t)
  (cond ((dk-asm? (list 'IN t '(CARR R))) #t)
        ((and (pair? t) (eq? (car t) 'ENTRY)) (daf-type-entry! t daf-N))
        ((equal? t '(ONE R)) (fact 'ring-one-in 'R))
        ((equal? t '(ZERO R)) (fact 'ring-zero-in 'R))
        ((and (pair? t) (equal? (car t) '(NEG R)))
         (daf-type-carr! (cadr t)) (fact 'ring-neg-in-carr 'R (cadr t)))
        ((symbol? t) (if (not (dk-asm? (list 'IN t '(CARR R)))) (error "daf-type-carr!: untyped" t)))
        ((and (pair? t) (equal? (car t) '(ADD R)))
         (daf-type-carr! (cadr t)) (daf-type-carr! (caddr t))
         (fact 'ring-add-closed 'R (cadr t) (caddr t)))
        ((and (pair? t) (equal? (car t) '(MUL R)))
         (daf-type-carr! (cadr t)) (daf-type-carr! (caddr t))
         (fact 'ring-carrier-closed-mul 'R (cadr t) (caddr t)))
        (#t (error "daf-type-carr!: cannot type" t))))

;; goal (IN T C), T an IF tower over typable leaves: split and type
(define (daf-if-type!)
  (let* ((g (dk-goal)) (t (cadr g)))
    (if (and (pair? t) (eq? (car t) 'IF))
        (dk-case-if! t (lambda (b v) (daf-if-type!)))
        (begin
          (daf-type-carr! t)
          (if (eq? (caddr g) 'SET) (fact 'membership-implies-sethood t '(CARR R)))
          (ass)))))

(define (daf-mk-type! M)
  (dk-have! (list 'IN M (daf-mat daf-N)) (lambda ()
      (detach-with! (dk-fact! 'matof-in-mat daf-N daf-N '(CARR R) (cadddr M))
        (lambda () (dk-peel!) (daf-beta!) (daf-if-type!)))
      (ass))))

;; land (= (ENTRY M i k) body[i,k]) for M = (daf-mk body); return it
(define (daf-mk-entry! M i k)
  (let* ((G (cadddr M))
         (body (daf-tsubst (cadddr G) (list (cons 'dav_ i) (cons 'daw_ k))))
         (tgt (list '= (list 'ENTRY M i k) body)))
    (if (not (dk-asm? tgt))
        (let ((r (dk-fact! 'entry-of-matof daf-N daf-N G i k)))
          (if (and (pair? r) (eq? (car r) 'IMPLIES) (not (dk-asm? (cadr r))))
              (set! r (detach-with! r (lambda () (dk-peel!) (daf-beta!) (daf-if-type!)))))
          (let loop ()
            (if (and (pair? r) (eq? (car r) 'IMPLIES) (dk-asm? (cadr r)))
                (begin (set! r (dk-landed-1 (lambda () (detach! r)))) (loop))))
          (if (and (not (dk-asm? tgt)) (dk--redex? r)) (lam-b-h r))
          (if (not (dk-asm? tgt))
              (error "daf-mk-entry!: read-off did not land" tgt (expression->string r)))))
    tgt))

(define (daf-find-mk-entry e)
  (cond ((not (pair? e)) #f)
        ((and (eq? (car e) 'ENTRY) (pair? (cadr e)) (eq? (car (cadr e)) 'MATOF)) e)
        (#t (let loop ((l e))
              (cond ((not (pair? l)) #f)
                    ((daf-find-mk-entry (car l)))
                    (#t (loop (cdr l))))))))
;; rewrite every ENTRY of a tabulated matrix in the goal, then resolve decided IFs
(define (daf-mk-rewrite!)
  (let loop ()
    (let ((e (daf-find-mk-entry (dk-goal))))
      (if e (begin (subst (daf-mk-entry! (cadr e) (caddr e) (cadddr e))) (loop)))))
  (daf-if-auto!))

;; close an equation of ring terms: drop 1 *, rfl if syntactic, crs otherwise
(define (daf-ring-close!)
  (let ((g (dk-goal)))
    (daf-type-carr! (cadr g))
    (daf-type-carr! (caddr g))
    (if (equal? (cadr g) (caddr g)) (rfl) (crs))))

;;; =====================================================================
;;; (6) interchanging two rows negates D (the proof of det-swap-rows, for D)
;;; =====================================================================
(define (daf-sw-hBo n)
  (list 'FORALL 'dri_ (list 'IMPLIES (list 'IN 'dri_ (daf-iv n))
    (list 'IMPLIES '(NOT (= dri_ p)) (list 'IMPLIES '(NOT (= dri_ q))
      (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv n))
        '(= (ENTRY B dri_ drk_) (ENTRY A dri_ drk_)))))))))
(define (daf-sw-hrow n r s)          ; row r of B is row s of A
  (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv n))
    (list '= (list 'ENTRY 'B r 'drk_) (list 'ENTRY 'A s 'drk_)))))
(define (daf-mk2 r1 r2 E1 E2)
  (daf-mk (list 'IF (list '= 'dav_ r1) E1 (list 'IF (list '= 'dav_ r2) E2 '(ENTRY A dav_ daw_)))))

;; after the rewrite: 1 * x away, entries of B by the hypotheses, index equations, rfl
(define (daf-sw-close! i k)
  (if (and i (dk-asm? (list '= i 'p)) (dk-contains? (dk-goal) i)) (subst (list '= i 'p)))
  (if (and i (dk-asm? (list '= i 'q)) (dk-contains? (dk-goal) i)) (subst (list '= i 'q)))
  (let loop ()
    (let ((e (find-first (lambda (x) (and (pair? x) (eq? (car x) 'ENTRY) (eq? (cadr x) 'B)))
                         (dk-subterms (dk-goal)))))
      (if e
          (let ((r (caddr e)))
            (cond ((eq? r 'p) (dk-apply! (daf-sw-hrow 'n 'p 'q) k)
                              (subst (list '= e (list 'ENTRY 'A 'q k))))
                  ((eq? r 'q) (dk-apply! (daf-sw-hrow 'n 'q 'p) k)
                              (subst (list '= e (list 'ENTRY 'A 'p k))))
                  (#t (dk-apply! (dk-apply! (daf-sw-hBo 'n) r) k)
                      (subst (list '= e (list 'ENTRY 'A r k)))))
            (loop)))))
  (daf-ring-close!))

(define (daf-sw-thunk ante)
  (if (eq? (cadr ante) 'dri_)
      (lambda ()
        (let* ((i (dk-di-var!))
               (ne (dk-landed-1 (lambda () (di))))
               (lin (caddr (cadr ne)))
               (k (dk-di-var!)))
          (use-em (list '= i (if (eq? lin 'p) 'q 'p))
            (lambda () (daf-mk-rewrite!) (daf-sw-close! i k))
            (lambda () (daf-mk-rewrite!) (daf-sw-close! i k)))))
      (lambda ()
        (let ((k (dk-di-var!)))
          (daf-mk-rewrite!)
          (daf-sw-close! #f k)))))

(sp (make-wff
  (forall-guarded '(R n D A B p q)
    (append (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun 'n 'D) (daf-lin 'n 'D) (daf-alt 'n 'D)
                  (list 'IN 'A (daf-mat 'n)) (list 'IN 'B (daf-mat 'n))
                  '(IN p (INTERVAL 1 n)) '(IN q (INTERVAL 1 n)) '(NOT (= p q))
                  (daf-sw-hBo 'n) (daf-sw-hrow 'n 'p 'q) (daf-sw-hrow 'n 'q 'p)))
    '(= (D B) ((NEG R) (D A))))))
(dk-peel!)
(set! daf-N 'n)
(fact 'commutative-ring-is-ring 'R)
(fact 'ring-one-in 'R)
(fact 'ring-zero-in 'R)
(fact 'neq-sym 'p 'q)
(have! '(= p p) (lambda () (rfl)))
(have! '(= q q) (lambda () (rfl)))
(let* ((ap '(ENTRY A p daw_)) (aq '(ENTRY A q daw_)) (s (list '(ADD R) ap aq))
       (SS (daf-mk2 'p 'q s s)) (PS (daf-mk2 'p 'q ap s)) (QS (daf-mk2 'p 'q aq s))
       (PP (daf-mk2 'p 'q ap ap)) (QQ (daf-mk2 'p 'q aq aq))
       (lin (daf-ctx (daf-lin 'n 'D))) (alt (daf-ctx (daf-alt 'n 'D)))
       (d (lambda (M) (list 'D M))))
  (for-each daf-mk-type! (list SS PS QS PP QQ))
  (dk-chain! (inst*! lin PS QS SS 'p '(ONE R)) daf-sw-thunk)
  (dk-chain! (inst*! lin PP 'A PS 'q '(ONE R)) daf-sw-thunk)
  (dk-chain! (inst*! lin 'B QQ QS 'q '(ONE R)) daf-sw-thunk)
  (for-each (lambda (M) (dk-chain! (inst*! alt M 'p 'q) daf-sw-thunk)) (list SS PP QQ))
  (for-each (lambda (M) (fact 'fun-apply-type-c 'D (daf-mat 'n) '(CARR R) M))
            (list 'A 'B SS PS QS PP QQ))
  (let ((f1 (dk-fact! 'dtr-ring-swap 'R (d 'A) (d 'B) (d SS))))
    (dk-apply! f1 (d PS) (d QS) (d PP) (d QQ)))
  (ass))
(daf-done! 'daf-swap)
(topic! 'daf-swap 'algebra)

;; D(F[k,l]) = - D(I)
(sp (make-wff
  (forall-guarded '(R n D k l)
    (append (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun 'n 'D) (daf-lin 'n 'D) (daf-alt 'n 'D)
                  '(IN k (INTERVAL 1 n)) '(IN l (INTERVAL 1 n)) '(NOT (= k l))))
    '(= (D (ELEM-F R n k l)) ((NEG R) (D (IDENTMAT R n)))))))
(dk-peel!)
(set! daf-N 'n)
(fact 'commutative-ring-is-ring 'R)
(fact 'ring-one-in 'R)
(fact 'ring-zero-in 'R)
(fact 'neq-sym 'k 'l)
(have! '(= k k) (lambda () (rfl)))
(have! '(= l l) (lambda () (rfl)))
(fact 'elem-f-type 'R 'n 'k 'l)
(fact 'identmat-type 'R 'n)
(define daf-ef-F '(ELEM-F R n k l))
(define daf-ef-I '(IDENTMAT R n))
(fact 'identmat-right-identity 'R 'n 'n daf-ef-F)
(define (daf-ef-lane!)
  ;; goal (= (ENTRY F i c) (ENTRY I j c)): F = F I, row action, resolve
  (let* ((g (dk-goal)) (i (caddr (cadr g))) (c (cadddr (cadr g))))
    (subst (list '= daf-ef-F (list 'MATMUL 'R daf-ef-F daf-ef-I)))
    (subst (dk-fact! 'elem-f-row-action 'R 'n 'n daf-ef-I 'k 'l i c))
    (daf-if-auto!)
    (daf-ring-close!)))
(dk-chain! (dk-fact! 'daf-swap 'R 'n 'D daf-ef-I daf-ef-F 'k 'l) (lambda (ante)
    (if (eq? (cadr ante) 'dri_)
        (lambda ()
          (dk-di-var!) (di) (di)
          (dk-di-var!)
          (daf-ef-lane!))
        (lambda () (dk-di-var!) (daf-ef-lane!)))))
(ass)
(daf-done! 'daf-elem-f)
(topic! 'daf-elem-f 'algebra)

;;; =====================================================================
;;; (7) CLEARING.  Y of size succ n with row 1 = e_1.  H_m = Y with column 1
;;; cleared in rows 2 .. succ m; K_m = H_m with row succ(succ m) := row 1 of Y.
;;; D(H_m) = D(K_m)-multiple + D(H_{m+1}) by linearity in row succ(succ m), and
;;; D(K_m) = 0 (rows 1 and succ(succ m) equal); so D(H_n) = D(H_0) = D(Y).
;;; =====================================================================
(define (daf-mkN N body)
  (list 'MATOF N N (list 'VNB-LAMBDA '(LIST dav_ daw_) (list 'CARTESIAN (daf-iv N) (daf-iv N)) body)))
(define (daf-row1-off Y N)
  (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv N))
    (list 'IMPLIES '(NOT (= drk_ 1)) (list '= (list 'ENTRY Y 1 'drk_) '(ZERO R))))))
(define (daf-Hbody Y m)
  (list 'IF '(= daw_ 1)
        (list 'IF '(= dav_ 1) (list 'ENTRY Y 'dav_ 'daw_)
              (list 'IF (list '<= 'dav_ (list 'succ m)) '(ZERO R) (list 'ENTRY Y 'dav_ 'daw_)))
        (list 'ENTRY Y 'dav_ 'daw_)))
(define (daf-H Y m) (daf-mkN '(succ n) (daf-Hbody Y m)))
(define (daf-K Y m)
  (daf-mkN '(succ n) (list 'IF (list '= 'dav_ (list 'succ (list 'succ m))) (list 'ENTRY Y 1 'daw_)
                           (daf-Hbody Y m))))
(define (daf-e1-hyps Y)                ; row 1 of Y is e_1
  (list (list '= (list 'ENTRY Y 1 1) '(ONE R)) (daf-row1-off Y '(succ n))))
(define (daf-clr-body m)
  (forall-guarded '(R n D Y)
    (append (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun '(succ n) 'D) (daf-lin '(succ n) 'D)
                  (daf-alt '(succ n) 'D) (list 'IN 'Y (daf-mat '(succ n))))
            (daf-e1-hyps 'Y) (list (list '<= m 'n)))
    (list '= (list 'D (daf-H 'Y m)) '(D Y))))

;; (daf-refute! ATOM CONTRA TERMS PREMS): prove (NOT ATOM) -- assume ATOM, derive
;; CONTRA by ineq, and (NOT CONTRA) is in context.
(define (daf-refute! atom contra terms prems)
  (dk-have! (list 'NOT atom) (lambda ()
      (di)
      (have! contra (lambda () (apply dk-nn! (cons atom prems))))
      (ai (list 'NOT contra)))))
(define (daf-sz-setup!)
  (set! daf-N '(succ n))
  (fact 'commutative-ring-is-ring 'R)
  (fact 'ring-one-in 'R)
  (fact 'ring-zero-in 'R)
  (fact 'nn-succ-closed 'n)
  (fact 'nn-one-in)
  (fact 'nn-le-refl 1)
  (fact 'nn-one-le-succ 'n)
  (fact 'interval-mem-intro 1 '(succ n) 1)
  (have! '(= 1 1) (lambda () (rfl))))

(sp (make-wff (list 'FORALL 'm (list 'IMPLIES '(IN m NN) (daf-clr-body 'm)))))
(define daf-clr-ind (use-induction))
;; ---- base: H_0 = Y
(dk-focus! (cdr (assq 'base daf-clr-ind)))
(dk-peel!)
(daf-sz-setup!)
(let ((H0 (daf-H 'Y 0)))
  (daf-mk-type! H0)
  (detach-with! (dk-fact! 'matrix-entry-extensionality '(succ n) '(succ n) '(CARR R) H0 'Y)
    (lambda ()
      (dk-peel!)
      (let* ((g (dk-goal)) (i (caddr (cadr g))) (j (cadddr (cadr g))))
        (daf-iv! i 1 '(succ n))
        (daf-mk-rewrite!)
        (use-em (list '= j 1)
          (lambda ()
            (daf-if-auto!)
            (use-em (list '= i 1)
              (lambda () (daf-if-auto!) (daf-ring-close!))
              (lambda ()
                (daf-refute! (list '<= i '(succ 0)) (list '= i 1) (list i '(succ 0)) (list (list '<= 1 i)))
                (daf-if-auto!)
                (daf-ring-close!))))
          (lambda () (daf-if-auto!) (daf-ring-close!))))))
  (fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) 'Y)
  (subst (list '= H0 'Y))
  (rfl))
;; ---- step
(dk-focus! (cdr (assq 'step daf-clr-ind)))
(define daf-clr-ih (cdr (assq 'ih daf-clr-ind)))
(dk-peel!)
(daf-sz-setup!)
(fact 'nn-succ-closed 'm)
(fact 'nn-succ-closed '(succ m))
(dk-have! '(<= m n) (lambda () (apply dk-nn! '((<= (succ m) n)))))
(define daf-clr-r1 (dk-apply! daf-clr-ih 'R 'n 'D 'Y))
(define daf-clr-p '(succ (succ m)))

(define (daf-clr-rowlane!)
  (let* ((i (dk-di-var!)) (ne (dk-landed-1 (lambda () (di)))) (k (dk-di-var!)))
    (daf-iv! i 1 '(succ n))
    (daf-mk-rewrite!)
    (use-em (list '= k 1)
      (lambda ()
        (daf-if-auto!)
        (use-em (list '= i 1)
          (lambda () (daf-if-auto!) (daf-ring-close!))
          (lambda ()
            (use-em (list '<= i '(succ m))
              (lambda ()
                (dk-have! (list '<= i daf-clr-p) (lambda () (apply dk-nn! (list (list '<= i '(succ m))))))
                (daf-if-auto!) (daf-ring-close!))
              (lambda ()
                (fact 'nn-not-le-succ-le i '(succ m))
                (daf-refute! (list '<= i daf-clr-p) (list '= i daf-clr-p)
                             (list i '(succ m) daf-clr-p 'm) (list (list '<= daf-clr-p i)))
                (daf-if-auto!) (daf-ring-close!))))))
      (lambda () (daf-if-auto!) (daf-ring-close!)))))
(define (daf-clr-comblane!)
  (let ((k (dk-di-var!)))
    (daf-iv! k 1 '(succ n))
    (daf-mk-rewrite!)
    (use-em (list '= k 1)
      (lambda ()
        (daf-if-auto!)
        (subst (list '= k 1))
        (subst '(= (ENTRY Y 1 1) (ONE R)))
        (daf-ring-close!))
      (lambda ()
        (daf-if-auto!)
        (dk-apply! (daf-ctx (daf-row1-off 'Y '(succ n))) k)
        (subst (list '= (list 'ENTRY 'Y 1 k) '(ZERO R)))
        (daf-ring-close!)))))
(define (daf-clr-altlane!)
  (let ((k (dk-di-var!)))
    (daf-iv! k 1 '(succ n))
    (daf-mk-rewrite!)
    (use-em (list '= k 1)
      (lambda () (daf-if-auto!) (daf-ring-close!))
      (lambda () (daf-if-auto!) (daf-ring-close!)))))

(let* ((p daf-clr-p)
       (Hm (daf-H 'Y 'm)) (H1 (daf-H 'Y '(succ m))) (K (daf-K 'Y 'm))
       (sc (list 'ENTRY 'Y p 1))
       (tms (list p '(succ m) 'm 'n '(succ n)))
       (d (lambda (M) (list 'D M))))
  (daf-in-iv! p 1 '(succ n) tms '((<= (succ m) n)))
  (dk-have! (list 'NOT (list '= p 1)) (lambda () (apply dk-nn! '())))
  (fact 'neq-sym p 1)
  (dk-have! (list 'NOT (list '<= p '(succ m))) (lambda () (apply dk-nn! '())))
  (dk-have! (list '<= p p) (lambda () (apply dk-nn! '())))
  (have! (list '= p p) (lambda () (rfl)))
  (for-each daf-mk-type! (list Hm H1 K))
  (daf-type-entry! sc '(succ n))
  (dk-chain! (inst*! (daf-ctx (daf-lin '(succ n) 'D)) K H1 Hm p sc) (lambda (ante)
      (if (eq? (cadr ante) 'dri_) daf-clr-rowlane! daf-clr-comblane!)))
  (dk-chain! (inst*! (daf-ctx (daf-alt '(succ n) 'D)) K 1 p) (lambda (ante) daf-clr-altlane!))
  (for-each (lambda (M) (fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) M)) (list Hm H1 K))
  (dk-have! (list '= (d Hm) (list '(ADD R) (list '(MUL R) sc '(ZERO R)) (d H1))) (lambda ()
      (subst (list '= (d Hm) (list '(ADD R) (list '(MUL R) sc (d K)) (d H1))))
      (subst (list '= (d K) '(ZERO R)))
      (daf-ring-close!)))
  (fact 'daf-ring-cancel0 'R sc (d Hm) (d H1))
  (subst (list '= (d H1) (d Hm)))
  (ass))
(daf-done! 'daf-clear-ind)
(topic! 'daf-clear-ind 'algebra)

(sp (make-wff
  (forall-guarded '(R n D Y)
    (append (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun '(succ n) 'D) (daf-lin '(succ n) 'D)
                  (daf-alt '(succ n) 'D) (list 'IN 'Y (daf-mat '(succ n))))
            (daf-e1-hyps 'Y))
    (list '= (list 'D (daf-H 'Y 'n)) '(D Y)))))
(dk-peel!)
(fact 'nn-le-refl 'n)
(fact 'daf-clear-ind 'n 'R 'n 'D 'Y)
(ass)
(daf-done! 'daf-clear)
(topic! 'daf-clear 'algebra)

;; the cleared matrix is BORDER(1, its lower-right block)
(define (daf-M Y) (list 'SUBMAT (daf-H Y 'n) 'n 'n))
(sp (make-wff
  (forall-guarded '(R n Y)
    (append (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (list 'IN 'Y (daf-mat '(succ n))))
            (daf-e1-hyps 'Y))
    (list '= (daf-H 'Y 'n) (list 'BORDER 'R '(ONE R) (daf-M 'Y) 'n 'n)))))
(dk-peel!)
(daf-sz-setup!)
(let ((H (daf-H 'Y 'n)))
  (daf-mk-type! H)
  (dk-chain! (dk-fact! 'bordered-eq-border 'R 'n 'n H) (lambda (ante)
      (lambda ()
        (let* ((v (dk-di-var!)) (ne (dk-landed-1 (lambda () (di)))))
          (daf-iv! v 1 '(succ n))
          (daf-mk-rewrite!)
          (let ((g (dk-goal)))
            (if (equal? (cadr g) (caddr g))
                (daf-ring-close!)
                (begin (dk-apply! (daf-ctx (daf-row1-off 'Y '(succ n))) v) (ass))))))))
  (dk-have! (list '= (list 'ENTRY H 1 1) '(ONE R)) (lambda () (daf-mk-rewrite!) (ass)))
  (subst (list '= '(ONE R) (list 'ENTRY H 1 1)))
  (ass))
(daf-done! 'daf-bordered)
(topic! 'daf-bordered 'algebra)

;;; =====================================================================
;;; (8) the statement of the theorem at size N (the induction body), and the
;;; step for a first row e_1: D(Y) = det(M) D(I) with M the block of daf-bordered.
;;; =====================================================================
(define (daf-thm-body N)
  (forall-guarded '(R D) (daf-form-hyps N 'D)
    (list 'FORALL 'dfx_ (list 'IMPLIES (list 'IN 'dfx_ (daf-mat N))
      (list '= '(D dfx_) (list '(MUL R) (list 'DET 'R N 'dfx_) (list 'D (list 'IDENTMAT 'R N))))))))

(sp (make-wff
  (list 'FORALL 'n (list 'IMPLIES '(IN n NN) (list 'IMPLIES (daf-thm-body 'n)
    (forall-guarded '(R D Y)
      (append (daf-form-hyps '(succ n) 'D) (list (list 'IN 'Y (daf-mat '(succ n)))) (daf-e1-hyps 'Y))
      (list '= '(D Y) (list '(MUL R) (list 'DET 'R 'n (daf-M 'Y)) '(D (IDENTMAT R (succ n)))))))))))
(dk-peel!)
(define daf-cl-ih (daf-ctx (daf-thm-body 'n)))
(daf-sz-setup!)
(let* ((H (daf-H 'Y 'n)) (M (daf-M 'Y)) (B (list 'BORDER 'R '(ONE R) M 'n 'n))
       (DB (daf-DB 'n 'D)) (In '(IDENTMAT R n)) (I1 '(IDENTMAT R (succ n)))
       (Bin (list 'BORDER 'R '(ONE R) In 'n 'n)))
  (daf-mk-type! H)
  (fact 'submat-type 'R 'n 'n H)
  (fact 'identmat-type 'R 'n)
  (fact 'identmat-type 'R '(succ n))
  (fact 'daf-clear 'R 'n 'D 'Y)
  (fact 'daf-bordered 'R 'n 'Y)
  (fact 'daf-bd-fun 'R 'n 'D)
  (fact 'daf-bd-lin 'R 'n 'D)
  (fact 'daf-bd-alt 'R 'n 'D)
  (dk-lam-b-h! (dk-apply! (dk-apply! daf-cl-ih 'R DB) M))
  (if (not (dk-asm? (list '= (list 'D B) (list '(MUL R) (list 'DET 'R 'n M) (list 'D Bin)))))
      (error "daf-cl: the beta-reduced instance did not land"))
  (fact 'border-identity 'R 'n)
  (fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) H)
  (fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) I1)
  (fact 'det-in-carrier 'R 'n M)
  (dk-have! (list '= (list 'D H) (list 'D B)) (lambda () (subst (list '= B H)) (rfl)))
  (subst (list '= '(D Y) (list 'D H)))
  (subst (list '= (list 'D H) (list 'D B)))
  (subst (list '= (list 'D B) (list '(MUL R) (list 'DET 'R 'n M) (list 'D Bin))))
  (subst (list '= Bin I1))
  (daf-ring-close!))
(daf-done! 'daf-cl)
(topic! 'daf-cl 'algebra)

;;; =====================================================================
;;; (9) the step for a first row e_j.  j = 1 is daf-cl for D and for det.
;;; j /= 1: Y = X F[1,j] has first row e_1 and Y F[j,1] = X, so daf-cl at
;;; X |-> D(X F[j,1]) and at X |-> det(X F[j,1]) gives, with ONE block M,
;;;   D(X) = det(M) D(F[j,1]) = det(M) (- D(I)),  det(X) = det(M) det F[j,1] = det(M) (-1).
;;; =====================================================================
(define (daf-row1-ej X j N)
  (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (daf-iv N))
    (list '= (list 'ENTRY X 1 'drk_) (list 'IF (list '= 'drk_ j) '(ONE R) '(ZERO R))))))
(define (daf-concl N X)
  (list '= (list 'D X) (list '(MUL R) (list 'DET 'R N X) (list 'D (list 'IDENTMAT 'R N)))))

(sp (make-wff
  (list 'FORALL 'n (list 'IMPLIES '(IN n NN) (list 'IMPLIES (daf-thm-body 'n)
    (forall-guarded '(R D X j)
      (append (daf-form-hyps '(succ n) 'D)
              (list (list 'IN 'X (daf-mat '(succ n))) (list 'IN 'j (daf-iv '(succ n)))
                    (daf-row1-ej 'X 'j '(succ n))))
      (daf-concl '(succ n) 'X)))))))
(dk-peel!)
(daf-sz-setup!)
(define daf-bs-row (daf-ctx (daf-row1-ej 'X 'j '(succ n))))
(define daf-I1 '(IDENTMAT R (succ n)))
(daf-iv! 'j 1 '(succ n))
(fact 'identmat-type 'R '(succ n))
(fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) daf-I1)
(fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) 'X)
(fact 'det-in-carrier 'R '(succ n) 'X)
(have! '(= j j) (lambda () (rfl)))
;; (daf-bs-read! C): rewrite ENTRY(X, 1, C) in the goal by the first-row hypothesis, resolve
(define (daf-bs-read! c)
  (dk-apply! daf-bs-row c)
  (subst (list '= (list 'ENTRY 'X 1 c) (list 'IF (list '= c 'j) '(ONE R) '(ZERO R))))
  (daf-if-auto!))
(define (daf-bs-block! Y)            ; type the block M of Y; return M
  (let ((H (daf-H Y 'n)) (M (daf-M Y)))
    (daf-mk-type! H)
    (fact 'submat-type 'R 'n 'n H)
    (fact 'det-in-carrier 'R 'n M)
    M))
(use-em '(= j 1)
  ;; ---- j = 1
  (lambda ()
    (have! '(= 1 j) (lambda () (subst '(= j 1)) (rfl)))
    (dk-have! '(= (ENTRY X 1 1) (ONE R)) (lambda () (daf-bs-read! 1) (daf-ring-close!)))
    (dk-have! (daf-row1-off 'X '(succ n)) (lambda ()
        (let* ((k (dk-di-var!)) (ne (dk-landed-1 (lambda () (di)))))
          (daf-iv! k 1 '(succ n))
          (daf-refute! (list '= k 'j) (list '= k 1) (list k 'j) (list '(= j 1)))
          (daf-bs-read! k)
          (daf-ring-close!))))
    (let* ((M (daf-bs-block! 'X))
           (rD (dk-fact! 'daf-cl 'n 'R 'D 'X)))
      (fact 'daf-det-fun 'R '(succ n))
      (fact 'daf-det-lin 'R '(succ n))
      (fact 'daf-det-alt 'R '(succ n))
      (dk-lam-b-h! (dk-fact! 'daf-cl 'n 'R (daf-DL '(succ n)) 'X))
      (fact 'det-identity-ind 'R '(succ n))
      (subst rD)
      (subst (list '= '(DET R (succ n) X) (list '(MUL R) (list 'DET 'R 'n M) (list 'DET 'R '(succ n) daf-I1))))
      (subst (list '= (list 'DET 'R '(succ n) daf-I1) '(ONE R)))
      (daf-ring-close!)))
  ;; ---- j /= 1
  (lambda ()
    (let* ((F1j '(ELEM-F R (succ n) 1 j)) (Fj1 '(ELEM-F R (succ n) j 1))
           (Y (list 'MATMUL 'R 'X F1j))
           (YQ (list 'MATMUL 'R Y Fj1)) (IQ (list 'MATMUL 'R daf-I1 Fj1))
           (act (lambda (c)
                  (subst (dk-fact! 'elem-f-action 'R '(succ n) '(succ n) 'X 1 'j 1 c))
                  (daf-if-auto!))))
      (fact 'neq-sym 'j 1)
      (fact 'elem-f-type 'R '(succ n) 1 'j)
      (fact 'elem-f-type 'R '(succ n) 'j 1)
      (daf-mm-type! 'X F1j '(succ n))
      (daf-mm-type! Y Fj1 '(succ n))
      (daf-mm-type! daf-I1 Fj1 '(succ n))
      ;; row 1 of Y is e_1
      (dk-have! (list '= (list 'ENTRY Y 1 1) '(ONE R)) (lambda () (act 1) (daf-bs-read! 'j) (daf-ring-close!)))
      (dk-have! (daf-row1-off Y '(succ n)) (lambda ()
          (let* ((c (dk-di-var!)) (ne (dk-landed-1 (lambda () (di)))))
            (act c)
            (use-em (list '= c 'j)
              (lambda () (daf-if-auto!) (daf-bs-read! 1) (daf-ring-close!))
              (lambda () (daf-if-auto!) (daf-bs-read! c) (daf-ring-close!))))))
      (let ((M (daf-bs-block! Y)))
        ;; D side and det side of daf-cl
        (fact 'daf-rm-fun 'R '(succ n) 'D Fj1)
        (fact 'daf-rm-lin 'R '(succ n) 'D Fj1)
        (fact 'daf-rm-alt 'R '(succ n) 'D Fj1)
        (dk-lam-b-h! (dk-fact! 'daf-cl 'n 'R (daf-DQ '(succ n) 'D Fj1) Y))
        (fact 'daf-det-rm-fun 'R '(succ n) Fj1)
        (fact 'daf-det-rm-lin 'R '(succ n) Fj1)
        (fact 'daf-det-rm-alt 'R '(succ n) Fj1)
        (dk-lam-b-h! (dk-fact! 'daf-cl 'n 'R (daf-DQdet '(succ n) Fj1) Y))
        ;; Y F[j,1] = X and I F[j,1] = F[j,1]
        (dk-have! (list '= YQ 'X) (lambda ()
            (subst (dk-chain! (dk-fact! 'matmul-assoc 'R '(succ n) '(succ n) '(succ n) '(succ n) 'X F1j Fj1) (lambda (ante) (lambda () (prop)))))
            (subst (dk-fact! 'elem-f-inverse 'R '(succ n) 1 'j))
            (subst (dk-fact! 'identmat-right-identity 'R '(succ n) '(succ n) 'X))
            (rfl)))
        (fact 'identmat-left-identity 'R '(succ n) '(succ n) Fj1)
        (for-each (lambda (T) (fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) T)) (list YQ IQ Fj1))
        (for-each (lambda (T) (fact 'det-in-carrier 'R '(succ n) T)) (list YQ IQ Fj1))
        (dk-have! (list '= '(D X) (list 'D YQ)) (lambda () (subst (list '= YQ 'X)) (rfl)))
        (dk-have! (list '= (list 'D IQ) (list 'D Fj1)) (lambda () (subst (list '= IQ Fj1)) (rfl)))
        (dk-have! (list '= '(DET R (succ n) X) (list 'DET 'R '(succ n) YQ)) (lambda () (subst (list '= YQ 'X)) (rfl)))
        (dk-have! (list '= (list 'DET 'R '(succ n) IQ) (list 'DET 'R '(succ n) Fj1)) (lambda () (subst (list '= IQ Fj1)) (rfl)))
        (fact 'daf-elem-f 'R '(succ n) 'D 'j 1)
        (fact 'det-elem-f 'R '(succ n) 'j 1)
        (subst (list '= '(D X) (list 'D YQ)))
        (subst (list '= (list 'D YQ) (list '(MUL R) (list 'DET 'R 'n M) (list 'D IQ))))
        (subst (list '= (list 'D IQ) (list 'D Fj1)))
        (subst (list '= (list 'D Fj1) (list '(NEG R) (list 'D daf-I1))))
        (subst (list '= '(DET R (succ n) X) (list 'DET 'R '(succ n) YQ)))
        (subst (list '= (list 'DET 'R '(succ n) YQ)
                     (list '(MUL R) (list 'DET 'R 'n M) (list 'DET 'R '(succ n) IQ))))
        (subst (list '= (list 'DET 'R '(succ n) IQ) (list 'DET 'R '(succ n) Fj1)))
        (subst (list '= (list 'DET 'R '(succ n) Fj1) '((NEG R) (ONE R))))
        (daf-ring-close!)))))
(daf-done! 'daf-basis)
(topic! 'daf-basis 'algebra)

;;; =====================================================================
;;; (10) a general first row, one entry at a time.  X_j = A with row 1 := e_j;
;;; S_m = A with row 1 := (a_11, ..., a_1m, 0, ..., 0).  Both D and det are
;;; linear in row 1, so D(S_m) = det(S_m) D(I) passes from m to succ m.
;;; =====================================================================
(define (daf-Xj A jv)
  (daf-mkN '(succ n) (list 'IF '(= dav_ 1) (list 'IF (list '= 'daw_ jv) '(ONE R) '(ZERO R))
                           (list 'ENTRY A 'dav_ 'daw_))))
(define (daf-S A m)
  (daf-mkN '(succ n) (list 'IF '(= dav_ 1) (list 'IF (list '<= 'daw_ m) (list 'ENTRY A 1 'daw_) '(ZERO R))
                           (list 'ENTRY A 'dav_ 'daw_))))
(define (daf-perj A)
  (list 'FORALL 'dpj_ (list 'IMPLIES (list 'IN 'dpj_ (daf-iv '(succ n)))
    (daf-concl '(succ n) (daf-Xj A 'dpj_)))))
(define (daf-ps-hyps)
  (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun '(succ n) 'D) (daf-lin '(succ n) 'D)
        (daf-alt '(succ n) 'D) (list 'IN 'A (daf-mat '(succ n))) (daf-perj 'A)))
(define (daf-ps-body m)
  (forall-guarded '(R n D A) (append (daf-ps-hyps) (list (list '<= m '(succ n))))
    (daf-concl '(succ n) (daf-S 'A m))))

(sp (make-wff (list 'FORALL 'm (list 'IMPLIES '(IN m NN) (daf-ps-body 'm)))))
(define daf-ps-ind (use-induction))
;; ---- base: row 1 of S_0 is zero
(dk-focus! (cdr (assq 'base daf-ps-ind)))
(dk-peel!)
(daf-sz-setup!)
(let ((S0 (daf-S 'A 0)) (I1 '(IDENTMAT R (succ n))))
  (daf-mk-type! S0)
  (dk-have! (daf-zrow S0 1 '(succ n)) (lambda ()
      (let ((k (dk-di-var!)))
        (daf-iv! k 1 '(succ n))
        (fact 'nn-not-le-zero-pos k)
        (daf-mk-rewrite!)
        (daf-ring-close!))))
  (fact 'daf-zero-row 'R '(succ n) 'D S0 1)
  (fact 'dtr-zero-row-s 'n 'R S0 1)
  (fact 'identmat-type 'R '(succ n))
  (fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) I1)
  (subst (list '= (list 'D S0) '(ZERO R)))
  (subst (list '= (list 'DET 'R '(succ n) S0) '(ZERO R)))
  (daf-ring-close!))
;; ---- step
(dk-focus! (cdr (assq 'step daf-ps-ind)))
(define daf-ps-ih (cdr (assq 'ih daf-ps-ind)))
(dk-peel!)
(daf-sz-setup!)
(fact 'nn-succ-closed 'm)
(define (daf-ps-rowlane!)
  (let* ((i (dk-di-var!)) (ne (dk-landed-1 (lambda () (di)))) (k (dk-di-var!)))
    (daf-mk-rewrite!)
    (daf-ring-close!)))
(define (daf-ps-comblane!)
  (let* ((k (dk-di-var!)) (tms (list k 'm '(succ m))))
    (daf-iv! k 1 '(succ n))
    (daf-mk-rewrite!)
    (use-em (list '= k '(succ m))
      (lambda ()
        (dk-have! (list '<= k '(succ m)) (lambda () (apply dk-nn! (list (list '= k '(succ m))))))
        (dk-have! (list 'NOT (list '<= k 'm)) (lambda () (apply dk-nn! (list (list '= k '(succ m))))))
        (daf-if-auto!)
        (subst (list '= k '(succ m)))
        (daf-ring-close!))
      (lambda ()
        (use-em (list '<= k 'm)
          (lambda ()
            (dk-have! (list '<= k '(succ m)) (lambda () (apply dk-nn! (list (list '<= k 'm)))))
            (daf-if-auto!)
            (daf-ring-close!))
          (lambda ()
            (fact 'nn-not-le-succ-le k 'm)
            (daf-refute! (list '<= k '(succ m)) (list '= k '(succ m)) tms (list (list '<= '(succ m) k)))
            (daf-if-auto!)
            (daf-ring-close!)))))))
(let* ((Sm (daf-S 'A 'm)) (S1 (daf-S 'A '(succ m))) (X (daf-Xj 'A '(succ m)))
       (a '(ENTRY A 1 (succ m))) (I1 '(IDENTMAT R (succ n)))
       (lane (lambda (ante) (if (eq? (cadr ante) 'dri_) daf-ps-rowlane! daf-ps-comblane!))))
  (dk-have! '(<= m (succ n)) (lambda () (apply dk-nn! '((<= (succ m) (succ n))))))
  (daf-in-iv! '(succ m) 1 '(succ n) '(m (succ m) n (succ n)) '((<= (succ m) (succ n))))
  (for-each daf-mk-type! (list Sm S1 X))
  (daf-type-entry! a '(succ n))
  (let* ((r1 (dk-apply! daf-ps-ih 'R 'n 'D 'A))
         (r2 (dk-apply! (daf-ctx (daf-perj 'A)) '(succ m)))
         (rD (dk-chain! (inst*! (daf-ctx (daf-lin '(succ n) 'D)) X Sm S1 1 a) lane))
         (rT (dk-chain! (dk-fact! 'det-row-linear 'R '(succ n) X Sm S1 1 a) lane)))
    (fact 'identmat-type 'R '(succ n))
    (for-each (lambda (T) (fact 'fun-apply-type-c 'D (daf-mat '(succ n)) '(CARR R) T)) (list I1 X Sm S1))
    (for-each (lambda (T) (fact 'det-in-carrier 'R '(succ n) T)) (list X Sm S1))
    (subst rD)
    (subst rT)
    (subst r2)
    (subst r1)
    (daf-ring-close!)))
(daf-done! 'daf-psum-ind)
(topic! 'daf-psum-ind 'algebra)

(sp (make-wff (forall-guarded '(R n D A) (daf-ps-hyps) (daf-concl '(succ n) 'A))))
(dk-peel!)
(daf-sz-setup!)
(let ((S (daf-S 'A '(succ n))))
  (fact 'nn-le-refl '(succ n))
  (fact 'daf-psum-ind '(succ n) 'R 'n 'D 'A)
  (daf-mk-type! S)
  (detach-with! (dk-fact! 'matrix-entry-extensionality '(succ n) '(succ n) '(CARR R) S 'A)
    (lambda ()
      (dk-peel!)
      (let* ((g (dk-goal)) (i (caddr (cadr g))) (j (cadddr (cadr g))))
        (daf-iv! j 1 '(succ n))
        (daf-mk-rewrite!)
        (use-em (list '= i 1)
          (lambda () (daf-if-auto!) (subst (list '= i 1)) (daf-ring-close!))
          (lambda () (daf-if-auto!) (daf-ring-close!))))))
  (subst (list '= 'A S))
  (ass))
(daf-done! 'daf-psum)
(topic! 'daf-psum 'algebra)

;;; =====================================================================
;;; (11) HOFFMAN-KUNZE 5.3 THEOREM 2 (the uniqueness half)
;;; =====================================================================
(sp (make-wff (list 'FORALL 'n (list 'IMPLIES '(IN n NN) (daf-thm-body 'n)))))
(define daf-mi (use-induction))
;; ---- base: the only 0 x 0 matrix is IDENTMAT(R, 0), and det of it is 1
(dk-focus! (cdr (assq 'base daf-mi)))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'nn-zero-in)
(fact 'identmat-type 'R 0)
(let* ((a (cadr (cadr (dk-goal)))) (I0 '(IDENTMAT R 0)))
  (detach-with! (dk-fact! 'matrix-entry-extensionality 0 0 '(CARR R) a I0)
    (lambda ()
      (dk-peel!)
      (let* ((g (dk-goal)) (i (caddr (cadr g))))
        (daf-iv! i 1 0)
        (daf-absurd! (list (list '<= 1 i) (list '<= i 0))))))
  (subst (list '= a I0))
  (subst (dk-fact! 'det-zero 'R I0))
  (fact 'fun-apply-type-c 'D (daf-mat 0) '(CARR R) I0)
  (set! daf-N 0)
  (daf-ring-close!))
;; ---- step
(dk-focus! (cdr (assq 'step daf-mi)))
(define daf-mi-ih (cdr (assq 'ih daf-mi)))
(dk-peel!)
(daf-sz-setup!)
(let ((A (cadr (cadr (dk-goal)))))
  (dk-have! (daf-perj A) (lambda ()
      (let* ((j (dk-di-var!)) (X (daf-Xj A j)))
        (daf-mk-type! X)
        (dk-have! (daf-row1-ej X j '(succ n)) (lambda ()
            (let ((k (dk-di-var!)))
              (daf-mk-rewrite!)
              (use-em (list '= k j)
                (lambda () (daf-if-auto!) (daf-ring-close!))
                (lambda () (daf-if-auto!) (daf-ring-close!))))))
        (fact 'daf-basis 'n 'R 'D X j)
        (ass))))
  (fact 'daf-psum 'R 'n 'D A)
  (ass))
(daf-done! 'det-alternating-form-ind)
(topic! 'det-alternating-form-ind 'algebra)

;;; headline: Hoffman-Kunze 5.3 Theorem 2, D(A) = (det A) D(I)
(sp (make-wff
  (forall-guarded '(R n D A)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) (daf-fun 'n 'D) (daf-lin 'n 'D) (daf-alt 'n 'D)
          (list 'IN 'A (daf-mat 'n)))
    (daf-concl 'n 'A))))
(dk-peel!)
(fact 'det-alternating-form-ind 'n 'R 'D 'A)
(ass)
(daf-done! 'det-alternating-form)
(topic! 'det-alternating-form 'algebra)
(gloss! 'det-alternating-form
  "Hoffman-Kunze 5.3 Theorem 2 (uniqueness): if D is an alternating n-linear function
   on the n x n matrices over a commutative ring R -- linear in each row, zero on a
   matrix with two equal rows -- then D(A) = det(A) D(I) for every A.")
