;;; det-transpose.scm -- the transpose of a matrix and det(A^t) = det A; the COLUMN
;;; clauses of the linear-algebra notes' 3.18 (linearity in each column, two equal
;;; columns give 0, interchanging two columns negates det), 3.19 (det under an
;;; elementary COLUMN operation) and 3.22 (expansion along any column).  Batch 32
;;; (2026-09-25).  Over a COMMUTATIVE ring throughout.
;;;
;;; TRANSPOSE is defined in structure-library/transpose.scm (the user's decision,
;;; 2026-09-25): TRANSPOSE(A, m, n) = MATOF(n, m, (i, j) |-> ENTRY(A, j, i)).
;;;
;;; THE ROUTE.
;;;   (1) transpose-in-mat, transpose-entry (entry-of-matof), transpose-transpose
;;;       and transpose-identity (matrix-entry-extensionality), transpose-matmul
;;;       (matmul-entry + finsum-congruence + commutativity).
;;;   (2) 3.19 for COLUMN operations first, since they are corollaries of
;;;       det-multiplicative (theorem-library/det-multiplicative.scm) and
;;;       det-elem-{f,g,h} (det-mul.scm): det(A F) = - det A, det(A G) = det A,
;;;       det(A H) = r det A.  They are the bricks of the column clauses.
;;;   (3) LINEARITY IN COLUMN 1, by induction on the size (dtt-col1-ind): the
;;;       first-row cofactor expansion keeps column 1 in every minor it does not
;;;       delete, so for j /= 1 the minors are linear in THEIR column 1 (induction
;;;       hypothesis) and for j = 1 the minors coincide and the entry is linear.
;;;       Linearity in column p /= 1 is moved to column 1 by right multiplication
;;;       with F[1, p], which negates det on all three matrices (det-col-linear).
;;;   (4) a zero column gives det 0 (linearity with sc = -1); two equal columns p, q
;;;       give 0 because A G[-1, p, q] has a zero column q and the same det
;;;       (det-equal-cols-zero); interchanging two columns is right
;;;       multiplication by F[p, q] (det-swap-cols).
;;;   (5) det(A^t) = det A BY UNIQUENESS (Hoffman-Kunze 5.3 Thm 2 =
;;;       det-alternating-form): X |-> det(X^t) is alternating n-linear in the ROWS
;;;       of X because det is so in the COLUMNS; it takes the value
;;;       det(I^t) = det(I) = 1 at the identity.
;;;   (6) 3.22 along a column: det A = det A^t, expanded along ROW j
;;;       (det-expand-row); the minor of A^t at (j, i) is the transpose of the minor
;;;       of A at (i, j) (dtt-minor-transpose).
;;;
;;; LOAD WINDOW [2034, -): lo = det-multiplicative (theorem-library/det-multiplicative,
;;; load.scm:2034), then det-alternating-form 2033, det-mul 1965 (det-elem-{f,g,h}),
;;; det-rows 1964 (det-expand-row and the dtr- bricks: dtr-minor1-entry, dtr-succ-in,
;;; dtr-skip-in, dtr-sign-type, dtr-finsum-lin, dtr-ring-lin1/2), elem-actions-proof
;;; 1949 (elem-f-action, elem-g-action).  window.py reports lo = 1949: it does not see a
;;; qed wrapped in a file's done! helper.  Nothing in the tree cites the file.
;;; PROPOSED SLOT: immediately after "theorem-library/det-multiplicative"; and
;;; "structure-library/transpose" immediately after "structure-library/matrix".
;;; No axiom, support or stamp.  Helper prefix: dtt-.  Binders the driver builds:
;;; dci_ / dcj_ (the column clauses), dti_ / dtj_ (entrywise lanes), dtx_ (the
;;; lambda of (5)), dce_ (the row of (6)); ring identities: dts_ dta_ dtb_
;;; dtc_ dtd_ dtx_ dty_ dtz_.

;;; =====================================================================
;;; The file's kit.
;;; =====================================================================
(define (dtt-done! name)
  (if (not (proof-done? *ps*))
      (begin
        (display "\n*** det-transpose: ") (display name) (display " did NOT close.\n")
        (for-each (lambda (l)
                    (display ";;   leaf: ")
                    (display (expression->string (dk-goal-of l))) (newline))
                  (dk-open-leaves))))
  (qed name))

(define (dtt-have! f thunk)
  (if (alpha-equiv? (dk-goal) f) (thunk) (dk-have! f thunk)))

;; interval membership bookkeeping: from (IN i (INTERVAL a b)) land i in NN,
;; a <= i, i <= b.
(define (dtt-iv! i a b)
  (fact 'interval-elt-in-nn a b i)
  (fact 'interval-lo a b i)
  (fact 'interval-hi a b i))

;; land (IN X (INTERVAL A B)) for an NN term X by dk-nn! over PREMS
(define (dtt-in-iv! x a b prems)
  (dtt-have! (list 'IN x (list 'INTERVAL a b))
    (lambda ()
      (dtt-have! (list '<= a x) (lambda () (apply dk-nn! prems)))
      (dtt-have! (list '<= x b) (lambda () (apply dk-nn! prems)))
      (fact 'interval-mem-intro a b x)
      (ass))))

(define (dtt-nn-have! f prems)
  (dtt-have! f (lambda () (apply dk-nn! prems))))

(define (dtt-beta!) (if (dk--redex? (dk-goal)) (dk-lam-b!)))

(define (dtt-ctx f)
  (or (dk-ctx-form f) (error "dtt-ctx: not in context" (expression->string f))))

(define dtt-ag   '(RING-ADDITIVE-AG R))
(define dtt-mm   '(RING-MULTIPLICATIVE-MONOID R))
(define dtt-neg1 '((NEG R) (ONE R)))
(define (dtt-mat n) (list 'MAT n n '(CARR R)))
(define (dtt-iv n) (list 'INTERVAL 1 n))

;; the (IN x (INTERVAL 1 N)) hypotheses landed by a peel, in order
(define (dtt-iv-vars landed N)
  (reverse (map cadr (filter (lambda (f) (and (pair? f) (eq? (car f) 'IN) (symbol? (cadr f))
                                     (equal? (caddr f) (dtt-iv N))))
                    landed))))

;; the typing guard of matmul-type at three equal sizes N
(define (dtt-mm-guard! N)
  (dtt-have! (list 'IMPLIES (list '= N 0) (list 'OR (list '= N 0) (list '= N 0)))
    (lambda () (prop))))

;; entry-of-matof on the goal (= (ENTRY (MATOF m n LAM) a b) RHS), indices
;; typed: the definedness hypothesis is proved by DEFINED! (focus on
;; (IN (LAM x y) SET) beta-reduced, x and y typed), the read-off is beta-reduced
;; by lam-b-h and returned.  (elem-entry-readoffs.scm's eer-matof-eqn!, copied.)
(define (dtt-index-vars landed)
  (map cadr (filter (lambda (f) (and (pair? f) (eq? (car f) 'IN)
                                     (pair? (caddr f)) (eq? (car (caddr f)) 'INTERVAL)))
                    landed)))
(define (dtt-matof-eqn! defined!)
  (let* ((e   (cadr (dk-goal)))
         (mf  (cadr e))
         (mv  (cadr mf)) (nv (caddr mf)) (lam (cadddr mf))
         (a   (caddr e)) (b (cadddr e))
         (def (list 'FORALL 'i_ (list 'IMPLIES (list 'IN 'i_ (list 'INTERVAL 1 mv))
                (list 'FORALL 'j_ (list 'IMPLIES (list 'IN 'j_ (list 'INTERVAL 1 nv))
                  (list 'IN (list lam 'i_ 'j_) 'SET))))))
         (eqn (list '= e (list lam a b))))
    (have! def
      (lambda ()
        (let ((xy (dtt-index-vars (dk-peel!))))
          (lam-b)
          (defined! (car xy) (cadr xy)))))
    (dk-focus-having! def)
    (have! eqn (lambda () (fact 'entry-of-matof mv nv lam a b) (ass)))
    (dk-focus-having! eqn)
    (lam-b-h eqn)
    (let ((q (find-first (lambda (f) (and (pair? f) (eq? (car f) '=) (equal? (cadr f) e)
                                          (not (equal? f eqn))))
                         (dk-asms))))
      (if (not q) (error "dtt-matof-eqn!: lam-b-h landed no reduced equation"))
      q)))

;; the entrywise-equality antecedent of matrix-entry-extensionality at M x N
(define (dtt-ext-hyp P Q M N)
  (list 'FORALL 'dti_ (list 'IMPLIES (list 'IN 'dti_ (list 'INTERVAL 1 M))
    (list 'FORALL 'dtj_ (list 'IMPLIES (list 'IN 'dtj_ (list 'INTERVAL 1 N))
      (list '= (list 'ENTRY P 'dti_ 'dtj_) (list 'ENTRY Q 'dti_ 'dtj_)))))))

;; prove P = Q (both in MAT(M, N, X) in context) entrywise: THUNK gets the two
;; index eigenvariables with focus on (= (ENTRY P i j) (ENTRY Q i j)).
(define (dtt-ext! P Q M N X thunk)
  (let ((h (dtt-ext-hyp P Q M N)))
    (have! h
      (lambda ()
        (dk-peel!)
        (let* ((g (dk-goal)) (i (caddr (cadr g))) (j (cadddr (cadr g))))
          (thunk i j))))
    (dk-focus-having! h)
    (fact 'matrix-entry-extensionality M N X P Q)
    (ass)))

;;; =====================================================================
;;; (1) TRANSPOSE: typing, entries, involution, identity, product.
;;; =====================================================================
(sp (make-wff
  (forall-guarded '(A m n X) '((IN A (MAT m n X)))
    '(IN (TRANSPOSE A m n) (MAT n m X)))))
(dk-peel!)
(fact 'mat-rows-in-nn 'm 'n 'X 'A)
(fact 'mat-cols-in-nn 'm 'n 'X 'A)
(mac 'TRANSPOSE)
(dk-matof!)
(dk-peel!)                                     ; i in [1,n], j in [1,m]
(lam-b)                                        ; (IN (ENTRY A j i) X)
(let* ((e (cadr (dk-goal))))
  (fact 'entry-in-carrier 'm 'n 'X 'A (caddr e) (cadddr e))
  (ass))
(dtt-done! 'transpose-in-mat)
(topic! 'transpose-in-mat 'algebra)
(gloss! 'transpose-in-mat
  "The transpose of an m-by-n matrix over X is an n-by-m matrix over X.")

(sp (make-wff
  (forall-guarded '(A m n X i j)
    '((IN A (MAT m n X)) (IN i (INTERVAL 1 n)) (IN j (INTERVAL 1 m)))
    '(= (ENTRY (TRANSPOSE A m n) i j) (ENTRY A j i)))))
(dk-peel!)
(fact 'mat-rows-in-nn 'm 'n 'X 'A)
(fact 'mat-cols-in-nn 'm 'n 'X 'A)
(mac 'TRANSPOSE)
(dtt-matof-eqn!
  (lambda (x y)                                ; goal (IN (ENTRY A y x) SET)
    (fact 'entry-in-carrier 'm 'n 'X 'A y x)
    (fact 'membership-implies-sethood (list 'ENTRY 'A y x) 'X)
    (ass)))
(ass)
(dtt-done! 'transpose-entry)
(topic! 'transpose-entry 'algebra)
(gloss! 'transpose-entry
  "The (i, j) entry of the transpose is the (j, i) entry of the matrix.")

(sp (make-wff
  (forall-guarded '(A m n X) '((IN A (MAT m n X)))
    '(= (TRANSPOSE (TRANSPOSE A m n) n m) A))))
(dk-peel!)
(fact 'transpose-in-mat 'A 'm 'n 'X)
(fact 'transpose-in-mat '(TRANSPOSE A m n) 'n 'm 'X)
(dtt-ext! '(TRANSPOSE (TRANSPOSE A m n) n m) 'A 'm 'n 'X
  (lambda (i j)
    (subst (dk-fact! 'transpose-entry '(TRANSPOSE A m n) 'n 'm 'X i j))
    (subst (dk-fact! 'transpose-entry 'A 'm 'n 'X j i))
    (fact 'entry-in-carrier 'm 'n 'X 'A i j)
    (rfl)))
(dtt-done! 'transpose-transpose)
(topic! 'transpose-transpose 'algebra)
(gloss! 'transpose-transpose "Transposing twice gives the matrix back: (A^t)^t = A.")

(sp (make-wff
  (forall-guarded '(R n) '((IS-RING R) (IN n NN))
    '(= (TRANSPOSE (IDENTMAT R n) n n) (IDENTMAT R n)))))
(dk-peel!)
(fact 'identmat-type 'R 'n)
(fact 'transpose-in-mat '(IDENTMAT R n) 'n 'n '(CARR R))
(dtt-ext! '(TRANSPOSE (IDENTMAT R n) n n) '(IDENTMAT R n) 'n 'n '(CARR R)
  (lambda (i j)
    (use-em (list '= i j)
      (lambda ()
        (subst (list '= i j))
        (subst (dk-fact! 'transpose-entry '(IDENTMAT R n) 'n 'n '(CARR R) j j))
        (fact 'entry-in-carrier 'n 'n '(CARR R) '(IDENTMAT R n) j j)
        (rfl))
      (lambda ()
        (subst (dk-fact! 'transpose-entry '(IDENTMAT R n) 'n 'n '(CARR R) i j))
        (fact 'neq-sym i j)
        (subst (dk-fact! 'identmat-entry-off 'R 'n j i))
        (subst (dk-fact! 'identmat-entry-off 'R 'n i j))
        (fact 'ring-zero-in 'R)
        (rfl)))))
(dtt-done! 'transpose-identity)
(topic! 'transpose-identity 'algebra)
(gloss! 'transpose-identity "The identity matrix is its own transpose.")

;; (P Q)^t = Q^t P^t.  The guard is matmul-type's: with an empty inner dimension
;; and nonempty outer ones the product is m-by-0, not m-by-kc, and its transpose
;; tabulates entries that do not exist.
(sp (make-wff
  (forall-guarded '(R m n kc P Q)
    '((IS-COMMUTATIVE-RING R) (IN P (MAT m n (CARR R))) (IN Q (MAT n kc (CARR R)))
      (IMPLIES (= n 0) (OR (= m 0) (= kc 0))))
    '(= (TRANSPOSE (MATMUL R P Q) m kc)
        (MATMUL R (TRANSPOSE Q n kc) (TRANSPOSE P m n))))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'mat-rows-in-nn 'm 'n '(CARR R) 'P)
(fact 'mat-cols-in-nn 'm 'n '(CARR R) 'P)
(fact 'mat-cols-in-nn 'n 'kc '(CARR R) 'Q)
(fact 'matmul-type 'R 'm 'n 'kc 'P 'Q)
(fact 'transpose-in-mat '(MATMUL R P Q) 'm 'kc '(CARR R))
(fact 'transpose-in-mat 'Q 'n 'kc '(CARR R))
(fact 'transpose-in-mat 'P 'm 'n '(CARR R))
(dtt-have! '(IMPLIES (= n 0) (OR (= kc 0) (= m 0))) (lambda () (prop)))
(fact 'matmul-type 'R 'kc 'n 'm '(TRANSPOSE Q n kc) '(TRANSPOSE P m n))
(fact 'ring-additive-ag-is-abelian-group 'R)
(fact 'ras-carr 'R)
(dtt-ext! '(TRANSPOSE (MATMUL R P Q) m kc) '(MATMUL R (TRANSPOSE Q n kc) (TRANSPOSE P m n))
          'kc 'm '(CARR R)
  (lambda (i j)
    (dtt-iv! i 1 'kc)
    (dtt-iv! j 1 'm)
    (dtt-nn-have! '(NOT (= kc 0)) (list (list '<= 1 i) (list '<= i 'kc)))
    (dtt-nn-have! '(NOT (= m 0)) (list (list '<= 1 j) (list '<= j 'm)))
    (dtt-have! '(NOT (= n 0))
      (lambda ()
        (keep '(IMPLIES (= n 0) (OR (= m 0) (= kc 0))) '(NOT (= kc 0)) '(NOT (= m 0)))
        (prop)))
    (dk-one-le! 'n)
    (fact 'interval-in-set 1 'n)
    (fact 'nn-one-in)
    (fact 'interval-card-in-nn 1 'n)
    (subst (dk-fact! 'transpose-entry '(MATMUL R P Q) 'm 'kc '(CARR R) i j))
    (let* ((e1 (dk-fact! 'matmul-entry 'R 'm 'n 'kc 'P 'Q j i))
           (LX (caddr (caddr e1)))
           (e2 (dk-fact! 'matmul-entry 'R 'kc 'n 'm '(TRANSPOSE Q n kc) '(TRANSPOSE P m n) i j))
           (LY (caddr (caddr e2))))
      (subst e1)
      (subst e2)
      (dk-chain! (dk-fact! 'finsum-congruence dtt-ag '(INTERVAL 1 n) LX LY)
        (lambda (ante)
          (let ((body (caddr (caddr ante))))
            (if (eq? (car body) '=)
                (lambda ()
                  (let ((v (dk-di-var!)))
                    (dtt-beta!)
                    (subst (dk-fact! 'transpose-entry 'Q 'n 'kc '(CARR R) i v))
                    (subst (dk-fact! 'transpose-entry 'P 'm 'n '(CARR R) v j))
                    (fact 'entry-in-carrier 'm 'n '(CARR R) 'P j v)
                    (fact 'entry-in-carrier 'n 'kc '(CARR R) 'Q v i)
                    (fact 'commutative-ring-mul-comm 'R (list 'ENTRY 'P j v) (list 'ENTRY 'Q v i))
                    (ass)))
                (lambda ()
                  (let ((v (dk-di-var!)))
                    (dtt-beta!)
                    (fact 'entry-in-carrier 'm 'n '(CARR R) 'P j v)
                    (fact 'entry-in-carrier 'n 'kc '(CARR R) 'Q v i)
                    (fact 'ring-carrier-closed-mul 'R (list 'ENTRY 'P j v) (list 'ENTRY 'Q v i))
                    (subst (list '= (list 'CARR dtt-ag) '(CARR R)))
                    (ass)))))))
      (ass))))
(dtt-done! 'transpose-matmul)
(topic! 'transpose-matmul 'algebra)
(gloss! 'transpose-matmul "The transpose of a product is the product of the transposes in reverse order: (PQ)^t = Q^t P^t.")

;;; =====================================================================
;;; (2) ring identities (crs), and the notes' 3.19: det under an elementary
;;; COLUMN operation, from det-multiplicative.
;;; =====================================================================
(define (dtt-carr-guards vs) (map (lambda (v) (list 'IN v '(CARR R))) vs))
(define (dtt-ring-id! name vars lhs rhs)
  (sp (make-wff
    (list 'FORALL 'R (list 'IMPLIES '(IS-COMMUTATIVE-RING R)
      (forall-guarded vars (dtt-carr-guards vars) (list '= lhs rhs))))))
  (dk-peel!)
  (crs)
  (dtt-done! name)
  (topic! name 'plumbing))

(dtt-ring-id! 'dtt-ring-mul-neg1 '(dtx_) '((MUL R) dtx_ ((NEG R) (ONE R))) '((NEG R) dtx_))
(dtt-ring-id! 'dtt-ring-mul-one '(dtx_) '((MUL R) dtx_ (ONE R)) 'dtx_)
;; -c = s (-a) + (-b)  is  c = s a + b, read backwards: - (s (-a) + (-b)) = s a + b
(dtt-ring-id! 'dtt-ring-neg-lin '(dts_ dta_ dtb_)
  '((NEG R) ((ADD R) ((MUL R) dts_ ((NEG R) dta_)) ((NEG R) dtb_)))
  '((ADD R) ((MUL R) dts_ dta_) dtb_))
(dtt-ring-id! 'dtt-ring-neg-neg '(dtx_) '((NEG R) ((NEG R) dtx_)) 'dtx_)
;; (-1) x + x = 0
(dtt-ring-id! 'dtt-ring-negx-x '(dtx_) '((ADD R) ((MUL R) ((NEG R) (ONE R)) dtx_) dtx_) '(ZERO R))
;; 0 = (-1) 0 + 0
(dtt-ring-id! 'dtt-ring-zero-lin '() '(ZERO R) '((ADD R) ((MUL R) ((NEG R) (ONE R)) (ZERO R)) (ZERO R)))
;; a + b (-1) with a = b is 0:  a + a (-1) = 0
(dtt-ring-id! 'dtt-ring-x-xneg '(dtx_) '((ADD R) dtx_ ((MUL R) dtx_ ((NEG R) (ONE R)))) '(ZERO R))

(define dtt-EF '(ELEM-F R n k l))
(define dtt-EG '(ELEM-G R n sc k l))
(define dtt-EH '(ELEM-H R n sc k))

;; det(A F^col[k,l]) = det A det F^col[k,l]  and  = - det A
(sp (make-wff
  (forall-guarded '(R n A k l)
    '((IS-COMMUTATIVE-RING R) (IN n NN) (IN A (MAT n n (CARR R)))
      (IN k (INTERVAL 1 n)) (IN l (INTERVAL 1 n)) (NOT (= k l)))
    (list '= (list 'DET 'R 'n (list 'MATMUL 'R 'A dtt-EF))
             (list '(MUL R) '(DET R n A) (list 'DET 'R 'n dtt-EF))))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'elem-f-type 'R 'n 'k 'l)
(fact 'det-multiplicative 'R 'n 'A dtt-EF)
(ass)
(dtt-done! 'det-mul-elem-f-col)
(topic! 'det-mul-elem-f-col 'algebra)

(sp (make-wff
  (forall-guarded '(R n A k l)
    '((IS-COMMUTATIVE-RING R) (IN n NN) (IN A (MAT n n (CARR R)))
      (IN k (INTERVAL 1 n)) (IN l (INTERVAL 1 n)) (NOT (= k l)))
    (list '= (list 'DET 'R 'n (list 'MATMUL 'R 'A dtt-EF)) '((NEG R) (DET R n A))))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'det-in-carrier 'R 'n 'A)
(subst (dk-fact! 'det-mul-elem-f-col 'R 'n 'A 'k 'l))
(subst (dk-fact! 'det-elem-f 'R 'n 'k 'l))
(fact 'dtt-ring-mul-neg1 'R '(DET R n A))
(ass)
(dtt-done! 'det-elem-f-col)
(topic! 'det-elem-f-col 'algebra)
(gloss! 'det-elem-f-col
  "Interchanging columns k and l (right multiplication by F^col[k,l]) negates the determinant.")

;; det(A G^col[r,k,l]) = det A det G^col[r,k,l]  and  = det A
(sp (make-wff
  (forall-guarded '(R n A sc k l)
    '((IS-COMMUTATIVE-RING R) (IN n NN) (IN A (MAT n n (CARR R))) (IN sc (CARR R))
      (IN k (INTERVAL 1 n)) (IN l (INTERVAL 1 n)) (NOT (= k l)))
    (list '= (list 'DET 'R 'n (list 'MATMUL 'R 'A dtt-EG))
             (list '(MUL R) '(DET R n A) (list 'DET 'R 'n dtt-EG))))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'elem-g-type 'R 'n 'sc 'k 'l)
(fact 'det-multiplicative 'R 'n 'A dtt-EG)
(ass)
(dtt-done! 'det-mul-elem-g-col)
(topic! 'det-mul-elem-g-col 'algebra)

(sp (make-wff
  (forall-guarded '(R n A sc k l)
    '((IS-COMMUTATIVE-RING R) (IN n NN) (IN A (MAT n n (CARR R))) (IN sc (CARR R))
      (IN k (INTERVAL 1 n)) (IN l (INTERVAL 1 n)) (NOT (= k l)))
    (list '= (list 'DET 'R 'n (list 'MATMUL 'R 'A dtt-EG)) '(DET R n A)))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'det-in-carrier 'R 'n 'A)
(subst (dk-fact! 'det-mul-elem-g-col 'R 'n 'A 'sc 'k 'l))
(subst (dk-fact! 'det-elem-g 'R 'n 'sc 'k 'l))
(fact 'dtt-ring-mul-one 'R '(DET R n A))
(ass)
(dtt-done! 'det-elem-g-col)
(topic! 'det-elem-g-col 'algebra)
(gloss! 'det-elem-g-col
  "Adding sc times column k to column l (right multiplication by G^col[sc,k,l], k /= l) leaves the determinant unchanged.")

;; det(A H^col[r,k]) = det A det H^col[r,k]  and  = r det A
(sp (make-wff
  (forall-guarded '(R n A sc k)
    '((IS-COMMUTATIVE-RING R) (IN n NN) (IN A (MAT n n (CARR R))) (IN sc (CARR R))
      (IN k (INTERVAL 1 n)))
    (list '= (list 'DET 'R 'n (list 'MATMUL 'R 'A dtt-EH))
             (list '(MUL R) '(DET R n A) (list 'DET 'R 'n dtt-EH))))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'elem-h-type 'R 'n 'sc 'k)
(fact 'det-multiplicative 'R 'n 'A dtt-EH)
(ass)
(dtt-done! 'det-mul-elem-h-col)
(topic! 'det-mul-elem-h-col 'algebra)

(sp (make-wff
  (forall-guarded '(R n A sc k)
    '((IS-COMMUTATIVE-RING R) (IN n NN) (IN A (MAT n n (CARR R))) (IN sc (CARR R))
      (IN k (INTERVAL 1 n)))
    (list '= (list 'DET 'R 'n (list 'MATMUL 'R 'A dtt-EH)) '((MUL R) sc (DET R n A))))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'det-in-carrier 'R 'n 'A)
(subst (dk-fact! 'det-mul-elem-h-col 'R 'n 'A 'sc 'k))
(subst (dk-fact! 'det-elem-h 'R 'n 'sc 'k))
(fact 'commutative-ring-mul-comm 'R '(DET R n A) 'sc)
(ass)
(dtt-done! 'det-elem-h-col)
(topic! 'det-elem-h-col 'algebra)
(gloss! 'det-elem-h-col
  "Scaling column k by sc (right multiplication by H^col[sc,k]) scales the determinant by sc.")

;;; =====================================================================
;;; (3) det is LINEAR IN EACH COLUMN (the notes' 3.18, column clause).
;;; =====================================================================
(define (dtt-colhyp X Y p n)        ; columns of X and Y agree off column p
  (list 'FORALL 'dcj_ (list 'IMPLIES (list 'IN 'dcj_ (dtt-iv n))
    (list 'IMPLIES (list 'NOT (list '= 'dcj_ p))
      (list 'FORALL 'dci_ (list 'IMPLIES (list 'IN 'dci_ (dtt-iv n))
        (list '= (list 'ENTRY X 'dci_ 'dcj_) (list 'ENTRY Y 'dci_ 'dcj_))))))))
(define (dtt-colcomb C A B p sc n)  ; column p of C is sc * (column p of A) + column p of B
  (list 'FORALL 'dci_ (list 'IMPLIES (list 'IN 'dci_ (dtt-iv n))
    (list '= (list 'ENTRY C 'dci_ p)
             (list '(ADD R) (list '(MUL R) sc (list 'ENTRY A 'dci_ p)) (list 'ENTRY B 'dci_ p))))))

;; close ANY goal from contradictory NN premises (1 <= 0 by dk-nn!)
(define (dtt-absurd! prems)
  (dk-have! '(<= 1 0) (lambda () (apply dk-nn! prems)))
  (dk-focus-having! '(<= 1 0))
  (have! '(NOT (<= 1 0)) (lambda () (arith)))
  (dk-focus-having! '(NOT (<= 1 0)))
  (pbc)
  (ai '(NOT (<= 1 0))))

;; resolve every IF of the goal whose condition, or its negation, is in context
(define (dtt-find-decided-if e)
  (cond ((not (pair? e)) #f)
        ((and (eq? (car e) 'IF) (= (length e) 4)
              (or (dk-asm? (cadr e)) (dk-asm? (list 'NOT (cadr e)))))
         (cons (dk-asm? (cadr e)) e))
        (#t (let loop ((l e))
              (cond ((not (pair? l)) #f)
                    ((dtt-find-decided-if (car l)))
                    (#t (loop (cdr l))))))))
(define (dtt-if-auto!)
  (let loop ()
    (let ((hit (dtt-find-decided-if (dk-goal))))
      (if hit (begin (dk-if-branch! (car hit) (cdr hit) #f (lambda () #t)) (loop))))))

(define (dtt-skip w v) (list 'IF (list '< w v) w (list 'succ w)))
;; rewrite ENTRY(MINOR(X,1,v,n),u,w) in the goal: the entry (succ u, skip(w, v)) of X
(define (dtt-m1! X v u w)
  (subst (dk-fact! 'dtr-minor1-entry 'R 'n X v u w)))

;; (dtt-pred! P N): with (IN P (INTERVAL 1 (succ N))), (IN N NN), (NOT (= P 1)):
;; land (IN Q (INTERVAL 1 N)) and (= P (succ Q)) for a fresh Q; return Q.
(define (dtt-pred! p n)
  (dtt-iv! p 1 (list 'succ n))
  (dtt-nn-have! (list 'NOT (list '= p 0)) (list (list '<= 1 p)))
  (let ((q (dk-skolem! (dk-fact! 'nn-nonzero-is-succ p))))
    (let ((peq (list '= p (list 'succ q))))
      (dtt-have! (list 'NOT (list '= q 0))
        (lambda ()
          (di)
          (have! (list '= p 1) (lambda () (dk-nn! peq (list '= q 0))))
          (ai (list 'NOT (list '= p 1)))))
      (dk-one-le! q)
      (dtt-in-iv! q 1 n (list peq (list '<= p (list 'succ n)) (list '<= 1 q)))
      q)))

;; the cofactor summand along row 1, and the typings of its pieces
(define (dtt-sign j) (list 'MPOW dtt-mm dtt-neg1 j))
(define (dtt-cof X j n)
  (list '(MUL R) (dtt-sign (list 'succ j))
        (list '(MUL R) (list 'ENTRY X 1 j) (list 'DET 'R n (list 'MINOR X 1 j n)))))
(define (dtt-cof-type! X j n)
  (dtt-iv! j 1 (list 'succ n))
  (fact 'nn-one-in)
  (fact 'nn-succ-closed n)
  (fact 'nn-succ-closed j)
  (fact 'dtr-sign-type 'R (list 'succ j))
  (fact 'nn-le-refl 1)
  (fact 'nn-one-le-succ n)
  (fact 'interval-mem-intro 1 (list 'succ n) 1)
  (fact 'entry-in-carrier (list 'succ n) (list 'succ n) '(CARR R) X 1 j)
  (fact 'minor-type 'R X 1 j n)
  (fact 'det-in-carrier 'R n (list 'MINOR X 1 j n))
  (fact 'ring-carrier-closed-mul 'R (list 'ENTRY X 1 j) (list 'DET 'R n (list 'MINOR X 1 j n)))
  (fact 'ring-carrier-closed-mul 'R (dtt-sign (list 'succ j)) (caddr (dtt-cof X j n))))

;; matrices agreeing off column p = 1 have the same first-row minor at column p
(sp (make-wff
  (forall-guarded '(R n X Y p)
    (list '(IS-RING R) '(IN n NN) '(IN X (MAT (succ n) (succ n) (CARR R)))
          '(IN Y (MAT (succ n) (succ n) (CARR R))) '(= p 1)
          (dtt-colhyp 'X 'Y 'p '(succ n)))
    '(= (MINOR X 1 p n) (MINOR Y 1 p n)))))
(dk-peel!)
(define dtt-mc-ch (dtt-ctx (dtt-colhyp 'X 'Y 'p '(succ n))))
(fact 'nn-one-in)
(fact 'nn-succ-closed 'n)
(dtt-have! '(IN p NN) (lambda () (subst '(= p 1)) (ass)))
(fact 'minor-type 'R 'X 1 'p 'n)
(fact 'minor-type 'R 'Y 1 'p 'n)
(dtt-ext! '(MINOR X 1 p n) '(MINOR Y 1 p n) 'n 'n '(CARR R)
  (lambda (u w)
    (dtt-iv! u 1 'n)
    (dtt-iv! w 1 'n)
    (dtt-m1! 'X 'p u w)
    (dtt-m1! 'Y 'p u w)
    (dtt-nn-have! (list 'NOT (list '< w 'p)) (list '(= p 1) (list '<= 1 w)))
    (dk-if-branch! #f (dtt-skip w 'p) #f (lambda () #t))
    (fact 'dtr-succ-in 'n u)
    (fact 'dtr-succ-in 'n w)
    (dtt-nn-have! (list 'NOT (list '= (list 'succ w) 'p)) (list '(= p 1) (list '<= 1 w)))
    (dk-apply! (dk-apply! dtt-mc-ch (list 'succ w)) (list 'succ u))
    (ass)))
(dtt-done! 'dtt-minor1-colcongr)
(topic! 'dtt-minor1-colcongr 'algebra)

;; the induction statement (linearity in column p = 1), n outermost for `ni'
(define (dtt-c1-body n)
  (forall-guarded '(R A B C p dsc_)
    (list '(IS-COMMUTATIVE-RING R) (list 'IN 'A (dtt-mat n)) (list 'IN 'B (dtt-mat n))
          (list 'IN 'C (dtt-mat n)) (list 'IN 'p (dtt-iv n)) '(= p 1) '(IN dsc_ (CARR R))
          (dtt-colhyp 'B 'A 'p n) (dtt-colhyp 'C 'A 'p n) (dtt-colcomb 'C 'A 'B 'p 'dsc_ n))
    (list '= (list 'DET 'R n 'C)
             (list '(ADD R) (list '(MUL R) 'dsc_ (list 'DET 'R n 'A)) (list 'DET 'R n 'B)))))

(define dtt-I '(INTERVAL 1 (succ n)))
(define (dtt-apply-lin! lamA lamB lamC eq-thunk)
  (fact 'interval-in-set 1 '(succ n))
  (fact 'interval-card-in-nn 1 '(succ n))
  (dk-chain! (dk-fact! 'dtr-finsum-lin 'R dtt-I 'dsc_ lamA lamB lamC)
    (lambda (ante)
      (let ((body (caddr (caddr ante))))
        (if (eq? (car body) 'IN)
            (let ((X (if (equal? (car (cadr body)) lamA) 'A 'B)))
              (lambda ()
                (let ((v (dk-di-var!)))
                  (dtt-beta!)
                  (dtt-cof-type! X v 'n)
                  (ass))))
            (lambda ()
              (let ((v (dk-di-var!)))
                (dtt-beta!)
                (eq-thunk v)))))))
  (ass))

(sp (make-wff (list 'FORALL 'n (list 'IMPLIES '(IN n NN) (dtt-c1-body 'n)))))
(define dtt-c1-ind (use-induction))
;; ---- base: [1, 0] is empty
(dk-focus! (cdr (assq 'base dtt-c1-ind)))
(dk-peel!)
(dtt-iv! 'p 1 0)
(dtt-absurd! '((<= 1 p) (<= p 0)))
;; ---- step
(dk-focus! (cdr (assq 'step dtt-c1-ind)))
(define dtt-c1-ih (cdr (assq 'ih dtt-c1-ind)))
(define dtt-c1-hyps (dk-peel!))
(define dtt-c1-hB (dtt-ctx (dtt-colhyp 'B 'A 'p '(succ n))))
(define dtt-c1-hC (dtt-ctx (dtt-colhyp 'C 'A 'p '(succ n))))
(define dtt-c1-hP (dtt-ctx (dtt-colcomb 'C 'A 'B 'p 'dsc_ '(succ n))))
(fact 'commutative-ring-is-ring 'R)
(fact 'nn-succ-closed 'n)
(fact 'nn-one-in)
(mac 'det-cofactor)
(define dtt-c1-goal (dk-goal))
(define dtt-c1-lamC (caddr (cadr dtt-c1-goal)))
(define dtt-c1-lamA (caddr (caddr (cadr (caddr dtt-c1-goal)))))
(define dtt-c1-lamB (caddr (caddr (caddr dtt-c1-goal))))
(dtt-iv! 'p 1 '(succ n))
(fact 'nn-le-refl 1)
(fact 'nn-one-le-succ 'n)
(fact 'interval-mem-intro 1 '(succ n) 1)

;; column v /= p = 1 of the expansion: the minors inherit column 1
(define (dtt-c1-colagree! v)
  (let* ((w (dk-di-var!)))
    (di)
    (let* ((u (dk-di-var!))
           (X (cadr (cadr (cadr (dk-goal))))))      ; the MINOR's matrix, B or C
      (dtt-iv! u 1 'n)
      (dtt-iv! w 1 'n)
      (dtt-m1! X v u w)
      (dtt-m1! 'A v u w)
      (fact 'dtr-succ-in 'n u)
      (fact 'dtr-skip-in 'n v w)
      (dtt-have! (list 'NOT (list '= (dtt-skip w v) 'p))
        (lambda ()
          (dk-case-if! (dtt-skip w v)
            (lambda (b val)
              (if b
                  (ass)
                  (dk-nn! '(= p 1) (list '<= 1 w)))))))
      (let ((hX (if (eq? X 'B) dtt-c1-hB dtt-c1-hC)))
        (dk-apply! (dk-apply! hX (dtt-skip w v)) (list 'succ u)))
      (ass))))

(define (dtt-c1-comb! v)
  (let ((u (dk-di-var!)))
    (dtt-iv! u 1 'n)
    (dtt-m1! 'C v u 'p) (dtt-m1! 'A v u 'p) (dtt-m1! 'B v u 'p)
    (dk-if-branch! #t (dtt-skip 'p v) #f (lambda () #t))
    (fact 'dtr-succ-in 'n u)
    (dk-apply! dtt-c1-hP (list 'succ u))
    (ass)))

(dtt-apply-lin! dtt-c1-lamA dtt-c1-lamB dtt-c1-lamC
  (lambda (v)
    (use-em (list '= v 'p)
      ;; ---- the expansion column is column p = 1: the minors coincide
      (lambda ()
        (subst (list '= v 'p))
        (dtt-cof-type! 'A 'p 'n)
        (dtt-cof-type! 'B 'p 'n)
        (dtt-cof-type! 'C 'p 'n)
        (subst (dk-fact! 'dtt-minor1-colcongr 'R 'n 'C 'A 'p))
        (subst (dk-fact! 'dtt-minor1-colcongr 'R 'n 'B 'A 'p))
        (subst (dk-apply! dtt-c1-hP 1))
        (fact 'dtr-ring-lin1 'R (dtt-sign '(succ p)) '(ENTRY A 1 p) '(ENTRY B 1 p) 'dsc_
              '(DET R n (MINOR A 1 p n)))
        (ass))
      ;; ---- another column: row-1 entries common, minors linear in column 1
      (lambda ()
        (dtt-cof-type! 'A v 'n)
        (dtt-cof-type! 'B v 'n)
        (dtt-cof-type! 'C v 'n)
        (subst (dk-apply! (dk-apply! dtt-c1-hB v) 1))
        (subst (dk-apply! (dk-apply! dtt-c1-hC v) 1))
        (dtt-have! (list 'NOT (list '= v 1))
          (lambda () (subst '(= 1 p)) (ass)))
        (let* ((q (dtt-pred! v 'n)))
          (dtt-iv! q 1 'n)
          (dtt-in-iv! 'p 1 'n (list '(= p 1) (list '<= 1 q) (list '<= q 'n)))
          (dtt-nn-have! (list '< 'p v) (list '(= p 1) (list '= v (list 'succ q)) (list '<= 1 q)))
          (let* ((MA (list 'MINOR 'A 1 v 'n)) (MB (list 'MINOR 'B 1 v 'n))
                 (MC (list 'MINOR 'C 1 v 'n))
                 (res (dk-chain! (inst*! dtt-c1-ih 'R MA MB MC 'p 'dsc_)
                        (lambda (ante)
                          (if (eq? (cadr ante) 'dcj_)
                              (lambda () (dtt-c1-colagree! v))
                              (lambda () (dtt-c1-comb! v)))))))
            (subst res)
            (fact 'dtr-ring-lin2 'R (dtt-sign (list 'succ v)) (list 'ENTRY 'A 1 v) 'dsc_
                  (list 'DET 'R 'n MA) (list 'DET 'R 'n MB))
            (ass)))))))
(dtt-done! 'dtt-col1-ind)
(topic! 'dtt-col1-ind 'algebra)

;; (dtt-ext-have! P Q M N X THUNK) -- land (= P Q) entrywise (dtt-ext! on a lane)
(define (dtt-ext-have! P Q M N X thunk)
  (let ((claim (list '= P Q)))
    (dtt-have! claim (lambda () (dtt-ext! P Q M N X thunk)))
    (dk-focus-having! claim)
    claim))

;; the entry of X F[k,l] / X G[r,k,l] at (i, c), staged (fact with fewer terms),
;; substituted into the goal, and the IFs whose condition is decided resolved
(define (dtt-act! act X E-args i c)
  (subst (dk-apply! (apply dk-fact! act 'R 'n 'n X E-args) i c))
  (dtt-if-auto!))

;;; headline: linearity in each column
(sp (make-wff
  (forall-guarded '(R n A B C p sc)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) '(IN A (MAT n n (CARR R)))
          '(IN B (MAT n n (CARR R))) '(IN C (MAT n n (CARR R)))
          '(IN p (INTERVAL 1 n)) '(IN sc (CARR R))
          (dtt-colhyp 'B 'A 'p 'n) (dtt-colhyp 'C 'A 'p 'n) (dtt-colcomb 'C 'A 'B 'p 'sc 'n))
    '(= (DET R n C) ((ADD R) ((MUL R) sc (DET R n A)) (DET R n B))))))
(dk-peel!)
(define dtt-cl-hB (dtt-ctx (dtt-colhyp 'B 'A 'p 'n)))
(define dtt-cl-hC (dtt-ctx (dtt-colhyp 'C 'A 'p 'n)))
(define dtt-cl-hP (dtt-ctx (dtt-colcomb 'C 'A 'B 'p 'sc 'n)))
(fact 'commutative-ring-is-ring 'R)
(use-em '(= p 1)
  ;; ---- column 1: the induction
  (lambda ()
    (fact 'dtt-col1-ind 'n 'R 'A 'B 'C 'p 'sc)
    (ass))
  ;; ---- column p /= 1: move it to column 1 by F[1, p]
  (lambda ()
    (let* ((F '(ELEM-F R n 1 p))
           (mf (lambda (X) (list 'MATMUL 'R X F)))
           (AF (mf 'A)) (BF (mf 'B)) (CF (mf 'C)))
      (dtt-iv! 'p 1 'n)
      (fact 'nn-one-in)
      (dtt-in-iv! 1 1 'n '((<= 1 p) (<= p n)))
      (fact 'neq-sym 'p 1)
      (dtt-have! '(= 1 1) (lambda () (rfl)))
      (fact 'elem-f-type 'R 'n 1 'p)
      (dtt-mm-guard! 'n)
      (for-each (lambda (X)
                  (fact 'matmul-type 'R 'n 'n 'n X F)
                  (fact 'det-in-carrier 'R 'n X)
                  (fact 'det-elem-f-col 'R 'n X 1 'p))
                '(A B C))
      (let ((res (dk-chain! (dk-fact! 'dtt-col1-ind 'n 'R AF BF CF 1 'sc)
                   (lambda (ante)
                     (cond ((eq? (car ante) '=) (lambda () (rfl)))
                           ((eq? (cadr ante) 'dcj_)
                            (lambda ()
                              (let* ((c (dk-di-var!)))
                                (di)
                                (let* ((i (dk-di-var!))
                                       (X (caddr (cadr (cadr (dk-goal)))))
                                       (hX (if (eq? X 'B) dtt-cl-hB dtt-cl-hC)))
                                  (dtt-act! 'elem-f-action X '(1 p) i c)
                                  (dtt-act! 'elem-f-action 'A '(1 p) i c)
                                  (use-em (list '= c 'p)
                                    (lambda ()
                                      (dtt-if-auto!)
                                      (dk-apply! (dk-apply! hX 1) i)
                                      (ass))
                                    (lambda ()
                                      (dtt-if-auto!)
                                      (dk-apply! (dk-apply! hX c) i)
                                      (ass)))))))
                           (#t
                            (lambda ()
                              (let ((i (dk-di-var!)))
                                (dtt-act! 'elem-f-action 'C '(1 p) i 1)
                                (dtt-act! 'elem-f-action 'A '(1 p) i 1)
                                (dtt-act! 'elem-f-action 'B '(1 p) i 1)
                                (dk-apply! dtt-cl-hP i)
                                (ass)))))))))
        ;; res: det(C F) = sc det(A F) + det(B F), each det(X F) = - det X
        (let ((e1 '(= ((NEG R) (DET R n C))
                      ((ADD R) ((MUL R) sc ((NEG R) (DET R n A))) ((NEG R) (DET R n B))))))
          (dtt-have! e1
            (lambda ()
              (for-each (lambda (X)
                          (subst (list '= (list '(NEG R) (list 'DET 'R 'n X))
                                       (list 'DET 'R 'n (mf X)))))
                        '(C A B))
              (ass)))
          (fact 'dtt-ring-neg-lin 'R 'sc '(DET R n A) '(DET R n B))
          (subst '(= ((ADD R) ((MUL R) sc (DET R n A)) (DET R n B))
                     ((NEG R) ((ADD R) ((MUL R) sc ((NEG R) (DET R n A))) ((NEG R) (DET R n B))))))
          (subst (list '= (caddr e1) (cadr e1)))
          (subst (dk-fact! 'dtt-ring-neg-neg 'R '(DET R n C)))
          (rfl))))))
(dtt-done! 'det-col-linear)
(topic! 'det-col-linear 'algebra)
(gloss! 'det-col-linear
  "The determinant is linear in each column: if C agrees with A and with B off column p,
   and column p of C is sc times column p of A plus column p of B, then
   det C = sc det A + det B (commutative ring).")

;;; a zero column gives det 0 (linearity with sc = -1 and A = B = C)
(sp (make-wff
  (forall-guarded '(R n C q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) '(IN C (MAT n n (CARR R))) '(IN q (INTERVAL 1 n))
          '(FORALL dci_ (IMPLIES (IN dci_ (INTERVAL 1 n)) (= (ENTRY C dci_ q) (ZERO R)))))
    '(= (DET R n C) (ZERO R)))))
(dk-peel!)
(define dtt-zc-h (dtt-ctx '(FORALL dci_ (IMPLIES (IN dci_ (INTERVAL 1 n)) (= (ENTRY C dci_ q) (ZERO R))))))
(fact 'commutative-ring-is-ring 'R)
(fact 'ring-one-in 'R)
(fact 'ring-neg-in-carr 'R '(ONE R))
(fact 'ring-zero-in 'R)
(fact 'det-in-carrier 'R 'n 'C)
(let ((res (dk-chain! (dk-fact! 'det-col-linear 'R 'n 'C 'C 'C 'q dtt-neg1)
             (lambda (ante)
               (if (eq? (cadr ante) 'dcj_)
                   (lambda ()
                     (let* ((c (dk-di-var!)))
                       (di)
                       (let ((i (dk-di-var!)))
                         (fact 'entry-in-carrier 'n 'n '(CARR R) 'C i c)
                         (rfl))))
                   (lambda ()
                     (let ((i (dk-di-var!)))
                       (subst (dk-apply! dtt-zc-h i))
                       (fact 'dtt-ring-zero-lin 'R)
                       (ass))))))))
  (subst res)
  (fact 'dtt-ring-negx-x 'R '(DET R n C))
  (ass))
(dtt-done! 'dtt-zero-col)
(topic! 'dtt-zero-col 'algebra)

;;; two equal columns give det 0: A G[-1, p, q] has a zero column q and the same det
(sp (make-wff
  (forall-guarded '(R n A p q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) '(IN A (MAT n n (CARR R)))
          '(IN p (INTERVAL 1 n)) '(IN q (INTERVAL 1 n)) '(NOT (= p q))
          '(FORALL dci_ (IMPLIES (IN dci_ (INTERVAL 1 n)) (= (ENTRY A dci_ p) (ENTRY A dci_ q)))))
    '(= (DET R n A) (ZERO R)))))
(dk-peel!)
(define dtt-ec-h (dtt-ctx '(FORALL dci_ (IMPLIES (IN dci_ (INTERVAL 1 n)) (= (ENTRY A dci_ p) (ENTRY A dci_ q))))))
(define dtt-ec-G (list 'ELEM-G 'R 'n dtt-neg1 'p 'q))
(define dtt-ec-AG (list 'MATMUL 'R 'A dtt-ec-G))
(fact 'commutative-ring-is-ring 'R)
(fact 'ring-one-in 'R)
(fact 'ring-neg-in-carr 'R '(ONE R))
(fact 'elem-g-type 'R 'n dtt-neg1 'p 'q)
(dtt-mm-guard! 'n)
(fact 'matmul-type 'R 'n 'n 'n 'A dtt-ec-G)
(fact 'det-elem-g-col 'R 'n 'A dtt-neg1 'p 'q)
(dtt-have! '(= q q) (lambda () (rfl)))
(let ((res (dk-chain! (dk-fact! 'dtt-zero-col 'R 'n dtt-ec-AG 'q)
             (lambda (ante)
               (lambda ()
                 (let ((i (dk-di-var!)))
                   (dtt-act! 'elem-g-action 'A (list dtt-neg1 'p 'q) i 'q)
                   (subst (dk-apply! dtt-ec-h i))
                   (fact 'entry-in-carrier 'n 'n '(CARR R) 'A i 'q)
                   (fact 'dtt-ring-x-xneg 'R (list 'ENTRY 'A i 'q))
                   (ass)))))))
  (subst (list '= '(DET R n A) (list 'DET 'R 'n dtt-ec-AG)))
  (ass))
(dtt-done! 'det-equal-cols-zero)
(topic! 'det-equal-cols-zero 'algebra)
(gloss! 'det-equal-cols-zero "A square matrix with two equal columns has determinant zero (commutative ring).")

;;; interchanging two columns negates det: B = A F[p, q]
(define (dtt-sw-hBo)
  (list 'FORALL 'dcj_ (list 'IMPLIES '(IN dcj_ (INTERVAL 1 n))
    (list 'IMPLIES '(NOT (= dcj_ p)) (list 'IMPLIES '(NOT (= dcj_ q))
      (list 'FORALL 'dci_ (list 'IMPLIES '(IN dci_ (INTERVAL 1 n))
        '(= (ENTRY B dci_ dcj_) (ENTRY A dci_ dcj_)))))))))
(define (dtt-sw-hcol r s)             ; column r of B is column s of A
  (list 'FORALL 'dci_ (list 'IMPLIES '(IN dci_ (INTERVAL 1 n))
    (list '= (list 'ENTRY 'B 'dci_ r) (list 'ENTRY 'A 'dci_ s)))))
(sp (make-wff
  (forall-guarded '(R n A B p q)
    (list '(IS-COMMUTATIVE-RING R) '(IN n NN) '(IN A (MAT n n (CARR R))) '(IN B (MAT n n (CARR R)))
          '(IN p (INTERVAL 1 n)) '(IN q (INTERVAL 1 n)) '(NOT (= p q))
          (dtt-sw-hBo) (dtt-sw-hcol 'p 'q) (dtt-sw-hcol 'q 'p))
    '(= (DET R n B) ((NEG R) (DET R n A))))))
(dk-peel!)
(define dtt-sw-o (dtt-ctx (dtt-sw-hBo)))
(define dtt-sw-p (dtt-ctx (dtt-sw-hcol 'p 'q)))
(define dtt-sw-q (dtt-ctx (dtt-sw-hcol 'q 'p)))
(define dtt-sw-AF '(MATMUL R A (ELEM-F R n p q)))
(fact 'commutative-ring-is-ring 'R)
(fact 'elem-f-type 'R 'n 'p 'q)
(dtt-mm-guard! 'n)
(fact 'matmul-type 'R 'n 'n 'n 'A '(ELEM-F R n p q))
(fact 'det-elem-f-col 'R 'n 'A 'p 'q)
(dtt-ext-have! 'B dtt-sw-AF 'n 'n '(CARR R)
  (lambda (i c)
    (dtt-act! 'elem-f-action 'A '(p q) i c)
    (use-em (list '= c 'p)
      (lambda ()
        (dtt-if-auto!)
        (subst (list '= c 'p))
        (dk-apply! dtt-sw-p i)
        (ass))
      (lambda ()
        (use-em (list '= c 'q)
          (lambda ()
            (dtt-if-auto!)
            (subst (list '= c 'q))
            (dk-apply! dtt-sw-q i)
            (ass))
          (lambda ()
            (dtt-if-auto!)
            (dk-apply! (dk-apply! dtt-sw-o c) i)
            (ass)))))))
(subst (list '= 'B dtt-sw-AF))
(ass)
(dtt-done! 'det-swap-cols)
(topic! 'det-swap-cols 'algebra)
(gloss! 'det-swap-cols
  "Interchanging two distinct columns of a square matrix negates its determinant (commutative ring).")

;;; =====================================================================
;;; (5) det(A^t) = det A, by uniqueness (det-alternating-form, HK 5.3 Thm 2).
;;; The alternating n-linear property, as det-alternating-form.scm writes it
;;; (daf-rowhyp / daf-combhyp / daf-eqrows / daf-lin / daf-alt, copied: they are
;;; file-local there; the formulas are the same, so the citation matches).
;;; =====================================================================
(define (dtt-rowhyp X Y p n)
  (list 'FORALL 'dri_ (list 'IMPLIES (list 'IN 'dri_ (dtt-iv n))
    (list 'IMPLIES (list 'NOT (list '= 'dri_ p))
      (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (dtt-iv n))
        (list '= (list 'ENTRY X 'dri_ 'drk_) (list 'ENTRY Y 'dri_ 'drk_))))))))
(define (dtt-combhyp C A B p sc n)
  (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (dtt-iv n))
    (list '= (list 'ENTRY C p 'drk_)
             (list '(ADD R) (list '(MUL R) sc (list 'ENTRY A p 'drk_)) (list 'ENTRY B p 'drk_))))))
(define (dtt-eqrows X p q n)
  (list 'FORALL 'drk_ (list 'IMPLIES (list 'IN 'drk_ (dtt-iv n))
    (list '= (list 'ENTRY X p 'drk_) (list 'ENTRY X q 'drk_)))))
(define (dtt-fun n D) (list 'IN D (list 'FUN (dtt-mat n) '(CARR R))))
(define (dtt-lin n D)
  (forall-guarded '(dfa_ dfb_ dfc_ dfp_ dfs_)
    (list (list 'IN 'dfa_ (dtt-mat n)) (list 'IN 'dfb_ (dtt-mat n)) (list 'IN 'dfc_ (dtt-mat n))
          (list 'IN 'dfp_ (dtt-iv n)) '(IN dfs_ (CARR R))
          (dtt-rowhyp 'dfb_ 'dfa_ 'dfp_ n) (dtt-rowhyp 'dfc_ 'dfa_ 'dfp_ n)
          (dtt-combhyp 'dfc_ 'dfa_ 'dfb_ 'dfp_ 'dfs_ n))
    (list '= (list D 'dfc_)
             (list '(ADD R) (list '(MUL R) 'dfs_ (list D 'dfa_)) (list D 'dfb_)))))
(define (dtt-alt n D)
  (forall-guarded '(dfa_ dfp_ dfq_)
    (list (list 'IN 'dfa_ (dtt-mat n)) (list 'IN 'dfp_ (dtt-iv n)) (list 'IN 'dfq_ (dtt-iv n))
          '(NOT (= dfp_ dfq_)) (dtt-eqrows 'dfa_ 'dfp_ 'dfq_ n))
    (list '= (list D 'dfa_) '(ZERO R))))

;; X |-> det(X^t)
(define (dtt-DT n) (list 'VNB-LAMBDA 'dtx_ (dtt-mat n) (list 'DET 'R n (list 'TRANSPOSE 'dtx_ n n))))
(define (dtt-T X) (list 'TRANSPOSE X 'n 'n))

(sp (make-wff
  (forall-guarded '(R n) '((IS-COMMUTATIVE-RING R) (IN n NN))
    (dtt-fun 'n (dtt-DT 'n)))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'ring-carr-in-set 'R)
(fact 'mat-is-set '(CARR R) 'n 'n)
(dk-lam-t!)
(let ((v (dk-di-var!)))
  (dtt-beta!)
  (fact 'transpose-in-mat v 'n 'n '(CARR R))
  (fact 'det-in-carrier 'R 'n (dtt-T v))
  (ass))
(dtt-done! 'dtt-tr-fun)
(topic! 'dtt-tr-fun 'algebra)

(sp (make-wff
  (forall-guarded '(R n) '((IS-COMMUTATIVE-RING R) (IN n NN))
    (dtt-lin 'n (dtt-DT 'n)))))
(define dtt-tl-hyps (dk-peel!))
(fact 'commutative-ring-is-ring 'R)
(dk-lam-b!)
(let* ((g  (dk-goal))
       (c  (cadr (cadddr (cadr g))))
       (sa (cadr (caddr g)))
       (s  (cadr sa))
       (a  (cadr (cadddr (caddr sa))))
       (b  (cadr (cadddr (caddr (caddr g)))))
       (p  (car (dtt-iv-vars dtt-tl-hyps 'n))))
  (for-each (lambda (X) (fact 'transpose-in-mat X 'n 'n '(CARR R))) (list a b c))
  (dk-chain! (dk-fact! 'det-col-linear 'R 'n (dtt-T a) (dtt-T b) (dtt-T c) p s)
    (lambda (ante)
      (if (eq? (cadr ante) 'dcj_)
          (lambda ()
            (let* ((cc (dk-di-var!)))
              (di)
              (let* ((i (dk-di-var!))
                     (X (cadr (cadr (cadr (dk-goal))))))     ; TRANSPOSE's matrix
                (subst (dk-fact! 'transpose-entry X 'n 'n '(CARR R) i cc))
                (subst (dk-fact! 'transpose-entry a 'n 'n '(CARR R) i cc))
                (dk-apply! (dk-apply! (dtt-ctx (dtt-rowhyp X a p 'n)) cc) i)
                (ass))))
          (lambda ()
            (let ((i (dk-di-var!)))
              (for-each (lambda (X) (subst (dk-fact! 'transpose-entry X 'n 'n '(CARR R) i p)))
                        (list c a b))
              (dk-apply! (dtt-ctx (dtt-combhyp c a b p s 'n)) i)
              (ass))))))
  (ass))
(dtt-done! 'dtt-tr-lin)
(topic! 'dtt-tr-lin 'algebra)

(sp (make-wff
  (forall-guarded '(R n) '((IS-COMMUTATIVE-RING R) (IN n NN))
    (dtt-alt 'n (dtt-DT 'n)))))
(define dtt-ta-hyps (dk-peel!))
(dk-lam-b!)
(let* ((a  (cadr (cadddr (cadr (dk-goal)))))
       (pq (dtt-iv-vars dtt-ta-hyps 'n))
       (p (car pq)) (q (cadr pq)))
  (fact 'transpose-in-mat a 'n 'n '(CARR R))
  (dk-chain! (dk-fact! 'det-equal-cols-zero 'R 'n (dtt-T a) p q)
    (lambda (ante)
      (lambda ()
        (let ((i (dk-di-var!)))
          (subst (dk-fact! 'transpose-entry a 'n 'n '(CARR R) i p))
          (subst (dk-fact! 'transpose-entry a 'n 'n '(CARR R) i q))
          (dk-apply! (dtt-ctx (dtt-eqrows a p q 'n)) i)
          (ass)))))
  (ass))
(dtt-done! 'dtt-tr-alt)
(topic! 'dtt-tr-alt 'algebra)

;;; headline: det(A^t) = det A
(sp (make-wff
  (forall-guarded '(R n A)
    '((IS-COMMUTATIVE-RING R) (IN n NN) (IN A (MAT n n (CARR R))))
    '(= (DET R n (TRANSPOSE A n n)) (DET R n A)))))
(dk-peel!)
(fact 'commutative-ring-is-ring 'R)
(fact 'identmat-type 'R 'n)
(fact 'dtt-tr-fun 'R 'n)
(fact 'dtt-tr-lin 'R 'n)
(fact 'dtt-tr-alt 'R 'n)
(dk-lam-b-h! (dk-fact! 'det-alternating-form 'R 'n (dtt-DT 'n) 'A))
(define dtt-dt-res
  '(= (DET R n (TRANSPOSE A n n))
      ((MUL R) (DET R n A) (DET R n (TRANSPOSE (IDENTMAT R n) n n)))))
(if (not (dk-asm? dtt-dt-res)) (error "det-transpose: the beta-reduced instance did not land"))
(subst dtt-dt-res)
(subst (dk-fact! 'transpose-identity 'R 'n))
(subst (dk-fact! 'det-identity-ind 'R 'n))
(fact 'det-in-carrier 'R 'n 'A)
(fact 'dtt-ring-mul-one 'R '(DET R n A))
(ass)
(dtt-done! 'det-transpose)
(topic! 'det-transpose 'algebra)
(gloss! 'det-transpose "The determinant of the transpose equals the determinant: det(A^t) = det A (commutative ring).")

;;; =====================================================================
;;; (6) the notes' 3.22, column half: expansion along any column.
;;; =====================================================================
;; the minor of S^t at (q, p) is the transpose of the minor of S at (p, q)
(sp (make-wff
  (forall-guarded '(R n S p q)
    '((IS-RING R) (IN n NN) (IN S (MAT (succ n) (succ n) (CARR R))) (IN p NN) (IN q NN))
    '(= (MINOR (TRANSPOSE S (succ n) (succ n)) q p n) (TRANSPOSE (MINOR S p q n) n n)))))
(dk-peel!)
(fact 'nn-succ-closed 'n)
(define dtt-mt-TS '(TRANSPOSE S (succ n) (succ n)))
(fact 'transpose-in-mat 'S '(succ n) '(succ n) '(CARR R))
(fact 'minor-type 'R dtt-mt-TS 'q 'p 'n)
(fact 'minor-type 'R 'S 'p 'q 'n)
(fact 'transpose-in-mat '(MINOR S p q n) 'n 'n '(CARR R))
(dtt-ext! (list 'MINOR dtt-mt-TS 'q 'p 'n) '(TRANSPOSE (MINOR S p q n) n n) 'n 'n '(CARR R)
  (lambda (u w)
    (subst (dk-fact! 'minor-entry 'R dtt-mt-TS 'q 'p 'n u w))
    (subst (dk-fact! 'transpose-entry '(MINOR S p q n) 'n 'n '(CARR R) u w))
    (subst (dk-fact! 'minor-entry 'R 'S 'p 'q 'n w u))
    (fact 'dtr-skip-in 'n 'q u)
    (fact 'dtr-skip-in 'n 'p w)
    (subst (dk-fact! 'transpose-entry 'S '(succ n) '(succ n) '(CARR R) (dtt-skip u 'q) (dtt-skip w 'p)))
    (fact 'entry-in-carrier '(succ n) '(succ n) '(CARR R) 'S (dtt-skip w 'p) (dtt-skip u 'q))
    (rfl)))
(dtt-done! 'dtt-minor-transpose)
(topic! 'dtt-minor-transpose 'algebra)

;;; headline: det A = sum_i (-1)^(i+j) a_ij det A[i,j], for each column j
(sp (make-wff
  (forall-guarded '(R n A j)
    '((IS-COMMUTATIVE-RING R) (IN n NN) (IN A (MAT (succ n) (succ n) (CARR R)))
      (IN j (INTERVAL 1 (succ n))))
    (list '= '(DET R (succ n) A)
          (list 'FINSUM dtt-ag
                (list 'VNB-LAMBDA 'dce_ '(INTERVAL 1 (succ n))
                      (list '(MUL R) (list 'MPOW dtt-mm dtt-neg1 '(+ dce_ j))
                            '((MUL R) (ENTRY A dce_ j) (DET R n (MINOR A dce_ j n)))))
                '(INTERVAL 1 (succ n)))))))
(dk-peel!)
(define dtt-ec-TA '(TRANSPOSE A (succ n) (succ n)))
(fact 'commutative-ring-is-ring 'R)
(fact 'nn-succ-closed 'n)
(fact 'nn-one-in)
(fact 'transpose-in-mat 'A '(succ n) '(succ n) '(CARR R))
(fact 'det-transpose 'R '(succ n) 'A)
(subst (list '= '(DET R (succ n) A) (list 'DET 'R '(succ n) dtt-ec-TA)))
(define dtt-ec-e (dk-fact! 'det-expand-row 'R 'n dtt-ec-TA 'j))
(subst dtt-ec-e)
(fact 'ring-additive-ag-is-abelian-group 'R)
(fact 'ras-carr 'R)
(fact 'interval-in-set 1 '(succ n))
(fact 'interval-card-in-nn 1 '(succ n))
(dtt-iv! 'j 1 '(succ n))
;; the typings of the summand of the row expansion of A^t at column v
(define (dtt-ec-type! v)
  (dtt-iv! v 1 '(succ n))
  (dtt-have! (list 'AND '(IN j NN) (list 'IN v 'NN)) (lambda () (dk-conj-close! ass)))
  (fact 'nn-add-closed 'j v)
  (fact 'dtr-sign-type 'R (list '+ 'j v))
  (fact 'entry-in-carrier '(succ n) '(succ n) '(CARR R) dtt-ec-TA 'j v)
  (fact 'minor-type 'R dtt-ec-TA 'j v 'n)
  (fact 'det-in-carrier 'R 'n (list 'MINOR dtt-ec-TA 'j v 'n))
  (fact 'ring-carrier-closed-mul 'R (list 'ENTRY dtt-ec-TA 'j v)
        (list 'DET 'R 'n (list 'MINOR dtt-ec-TA 'j v 'n)))
  (fact 'ring-carrier-closed-mul 'R (list 'MPOW dtt-mm dtt-neg1 (list '+ 'j v))
        (list '(MUL R) (list 'ENTRY dtt-ec-TA 'j v) (list 'DET 'R 'n (list 'MINOR dtt-ec-TA 'j v 'n)))))
(let* ((L1 (caddr (cadr (dk-goal))))
       (L2 (caddr (caddr (dk-goal)))))
  (dk-chain! (dk-fact! 'finsum-congruence dtt-ag '(INTERVAL 1 (succ n)) L1 L2)
    (lambda (ante)
      (let ((body (caddr (caddr ante))))
        (if (eq? (car body) '=)
            (lambda ()
              (let ((v (dk-di-var!)))
                (dtt-beta!)
                (dtt-ec-type! v)
                (subst (dk-fact! 'transpose-entry 'A '(succ n) '(succ n) '(CARR R) 'j v))
                (subst (dk-fact! 'dtt-minor-transpose 'R 'n 'A v 'j))
                (fact 'minor-type 'R 'A v 'j 'n)
                (subst (dk-fact! 'det-transpose 'R 'n (list 'MINOR 'A v 'j 'n)))
                (subst (dk-fact! 'nn-add-comm 'j v))
                (dtt-have! (list 'AND (list 'IN v 'NN) '(IN j NN)) (lambda () (dk-conj-close! ass)))
                (fact 'nn-add-closed v 'j)
                (let* ((sg (list 'MPOW dtt-mm dtt-neg1 (list '+ v 'j)))
                       (ent (list (quote ENTRY) (quote A) v (quote j)))
                       (dm (list 'DET 'R 'n (list 'MINOR 'A v 'j 'n))))
                  (fact 'dtr-sign-type 'R (list '+ v 'j))
                  (fact 'entry-in-carrier '(succ n) '(succ n) '(CARR R) 'A v 'j)
                  (fact 'det-in-carrier 'R 'n (list 'MINOR 'A v 'j 'n))
                  (fact (quote ring-carrier-closed-mul) (quote R) ent dm)
                  (fact 'ring-carrier-closed-mul 'R sg (list (quote (MUL R)) ent dm)))
                (rfl)))
            (lambda ()
              (let ((v (dk-di-var!)))
                (dtt-beta!)
                (dtt-ec-type! v)
                (subst (list '= (list 'CARR dtt-ag) '(CARR R)))
                (ass)))))))
  (ass))
(dtt-done! 'det-expand-col)
(topic! 'det-expand-col 'algebra)
(gloss! 'det-expand-col
  "Expansion by minors along any column j: det A = sum_i (-1)^(i+j) a_ij det A[i,j] (commutative ring).")
