;;; elem-inverses-proof.scm -- Cor 3.6 (algebraic-numbers.pdf ch.3): the elementary
;;; column matrices are invertible, with elementary inverses.  Each reduces, via
;;; matrix-entry-extensionality, to an entry identity whose LHS is the PROVEN
;;; Prop 3.5 action (with P = the would-be inverse) and whose RHS is entry-of-identmat;
;;; a case split on the column then matches them.
;;;   F[k,l]^-1 = F[l,k]  (involution -- clean permutation composition)
;;;   G[r,k,l]^-1 = G[-r,k,l]  (r + (-r) = 0 cancels the off-diagonal)
;;;   H[r,k]^-1 = H[r^-1,k]  (r.s = 1 hypothesis at the (k,k) diagonal)

;; --- shared proof helpers ---
(define (ei-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (ei-foc! n) (set-proof-state-focus! *ps* n))
(define (ei-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (ei-di*) (let lp () (let* ((g (ei-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (ei-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((uo (ei-last)))
    (pbc) (cut `(NOT ,P))
    (let ((un (ei-last)))
      (di) (cut `(OR ,P (NOT ,P)))
      (let ((u2 (ei-last))) (oi-l) (ass) (ei-foc! u2))
      (ai `(NOT (OR ,P (NOT ,P)))) (ei-foc! un))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (ei-last))) (oi-r) (ass) (ei-foc! u3))
    (ai `(NOT (OR ,P (NOT ,P)))) (ei-foc! uo)))
(define (ei-cases P) (ei-em P) (ai `(OR ,P (NOT ,P))) (ei-last))

;;; ===================== elem-h-inverse ============================
(define EI-HR '(ELEM-H A n r k))
(define EI-HS '(ELEM-H A n s k))
(define EI-HPROD `(MATMUL A ,EI-HR ,EI-HS))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL n (FORALL r (FORALL s (FORALL k
       (IMPLIES (IN r (CARR A))
       (IMPLIES (IN s (CARR A))
       (IMPLIES (= ((MUL A) r s) (ONE A))
       (IMPLIES (IN k (INTERVAL 1 n))
         (= (MATMUL A (ELEM-H A n r k) (ELEM-H A n s k)) (IDENTMAT A n))))))))))))))
(ei-di*)
(fact 'elem-h-type 'A 'n 'r 'k)
(fact 'elem-h-type 'A 'n 's 'k)
(fact 'matmul-type 'A 'n 'n 'n EI-HR EI-HS)
(fact 'identmat-type 'A 'n)
(cut `(FORALL i (IMPLIES (IN i (INTERVAL 1 n))
        (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
          (= (ENTRY ,EI-HPROD i c) (ENTRY (IDENTMAT A n) i c)))))))
(define ei-hmain (ei-last))
  (di) (di) (di) (di)
  (fact 'elem-h-action 'A 'n 'n EI-HR 's 'k 'i 'c)
  (subst `(= (ENTRY ,EI-HPROD i c)
             (IF (= c k) ((MUL A) (ENTRY ,EI-HR i k) s) (ENTRY ,EI-HR i c))))
  (fact 'entry-of-identmat 'A 'n 'i 'c)
  (subst '(= (ENTRY (IDENTMAT A n) i c) (IF (= i c) (ONE A) (ZERO A))))
  (define ei-h-notck (ei-cases '(= c k)))
  ;; c = k
  (subst '(= c k))
  (if-true `(IF (= k k) ((MUL A) (ENTRY ,EI-HR i k) s) (ENTRY ,EI-HR i k)))
  (define ei-hu1 (ei-last)) (rfl) (ei-foc! ei-hu1)
  (subst `(= (IF (= k k) ((MUL A) (ENTRY ,EI-HR i k) s) (ENTRY ,EI-HR i k))
             ((MUL A) (ENTRY ,EI-HR i k) s)))
  (define ei-h-notik (ei-cases '(= i k)))
  ;; i = k
  (subst '(= i k))
  (fact 'elem-h-entry-diag 'A 'n 'r 'k 'k)
  (subst `(= (ENTRY ,EI-HR k k) (IF (= k k) r (ONE A))))
  (if-true '(IF (= k k) r (ONE A)))
  (define ei-hu2 (ei-last)) (rfl) (ei-foc! ei-hu2)
  (subst '(= (IF (= k k) r (ONE A)) r))
  (subst '(= ((MUL A) r s) (ONE A)))
  (if-true '(IF (= k k) (ONE A) (ZERO A)))
  (define ei-hu3 (ei-last)) (rfl) (ei-foc! ei-hu3)
  (subst '(= (IF (= k k) (ONE A) (ZERO A)) (ONE A)))
  (rfl)
  ;; i /= k
  (ei-foc! ei-h-notik)
  (fact 'elem-h-entry-off-diag 'A 'n 'r 'k 'i 'k)
  (subst `(= (ENTRY ,EI-HR i k) (ZERO A)))
  (fact 'ring-mul-zero-left 'A 's)
  (subst '(= ((MUL A) (ZERO A) s) (ZERO A)))
  (if-false '(IF (= i k) (ONE A) (ZERO A)))
  (define ei-hu4 (ei-last)) (ass) (ei-foc! ei-hu4)
  (subst '(= (IF (= i k) (ONE A) (ZERO A)) (ZERO A)))
  (rfl)
  ;; c /= k
  (ei-foc! ei-h-notck)
  (if-false `(IF (= c k) ((MUL A) (ENTRY ,EI-HR i k) s) (ENTRY ,EI-HR i c)))
  (define ei-hu5 (ei-last)) (ass) (ei-foc! ei-hu5)
  (subst `(= (IF (= c k) ((MUL A) (ENTRY ,EI-HR i k) s) (ENTRY ,EI-HR i c)) (ENTRY ,EI-HR i c)))
  (define ei-h-notic (ei-cases '(= i c)))
  ;; i = c
  (subst '(= i c))
  (fact 'elem-h-entry-diag 'A 'n 'r 'k 'c)
  (subst `(= (ENTRY ,EI-HR c c) (IF (= c k) r (ONE A))))
  (if-false '(IF (= c k) r (ONE A)))
  (define ei-hu6 (ei-last)) (ass) (ei-foc! ei-hu6)
  (subst '(= (IF (= c k) r (ONE A)) (ONE A)))
  (if-true '(IF (= c c) (ONE A) (ZERO A)))
  (define ei-hu7 (ei-last)) (rfl) (ei-foc! ei-hu7)
  (subst '(= (IF (= c c) (ONE A) (ZERO A)) (ONE A)))
  (rfl)
  ;; i /= c
  (ei-foc! ei-h-notic)
  (fact 'elem-h-entry-off-diag 'A 'n 'r 'k 'i 'c)
  (subst `(= (ENTRY ,EI-HR i c) (ZERO A)))
  (if-false '(IF (= i c) (ONE A) (ZERO A)))
  (define ei-hu8 (ei-last)) (ass) (ei-foc! ei-hu8)
  (subst '(= (IF (= i c) (ONE A) (ZERO A)) (ZERO A)))
  (rfl)
(ei-foc! ei-hmain)
(fact 'matrix-entry-extensionality 'n 'n '(CARR A) EI-HPROD '(IDENTMAT A n))
(ass)
(qed 'elem-h-inverse)
(topic! 'elem-h-inverse 'algebra)

;;; ===================== elem-g-inverse ============================
(define EI-NEGr '((NEG A) r))
(define EI-GR '(ELEM-G A n r k l))
(define EI-GNR `(ELEM-G A n ,EI-NEGr k l))
(define EI-GPROD `(MATMUL A ,EI-GR ,EI-GNR))
(define EI-GIL `(ENTRY ,EI-GR i l))
(define EI-GIK `(ENTRY ,EI-GR i k))
(define EI-GIC `(ENTRY ,EI-GR i c))
(define EI-GARHS `(IF (= c l) ((ADD A) ,EI-GIL ((MUL A) ,EI-GIK ,EI-NEGr)) ,EI-GIC))
(define EI-GILx '(IF (= i l) (ONE A) (IF (= i k) r (ZERO A))))
(define EI-GIKx '(IF (= i k) (ONE A) (ZERO A)))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL n (FORALL r (FORALL k (FORALL l
       (IMPLIES (IN r (CARR A))
       (IMPLIES (IN k (INTERVAL 1 n))
       (IMPLIES (IN l (INTERVAL 1 n))
       (IMPLIES (NOT (= k l))
         (= (MATMUL A (ELEM-G A n r k l) (ELEM-G A n ((NEG A) r) k l))
            (IDENTMAT A n))))))))))))))
(ei-di*)
(fact 'ring-neg-in-carr 'A 'r)
(fact 'elem-g-type 'A 'n 'r 'k 'l)
(fact 'elem-g-type 'A 'n EI-NEGr 'k 'l)
(fact 'matmul-type 'A 'n 'n 'n EI-GR EI-GNR)
(fact 'identmat-type 'A 'n)
(cut `(FORALL i (IMPLIES (IN i (INTERVAL 1 n))
        (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
          (= (ENTRY ,EI-GPROD i c) (ENTRY (IDENTMAT A n) i c)))))))
(define ei-gmain (ei-last))
  (di) (di) (di) (di)
  (fact 'elem-g-action 'A 'n 'n EI-GR EI-NEGr 'k 'l 'i 'c)
  (subst `(= (ENTRY ,EI-GPROD i c) ,EI-GARHS))
  (fact 'entry-of-identmat 'A 'n 'i 'c)
  (subst '(= (ENTRY (IDENTMAT A n) i c) (IF (= i c) (ONE A) (ZERO A))))
  (define ei-g-notcl (ei-cases '(= c l)))
  ;; c = l
  (if-true EI-GARHS)
  (define ei-gu1 (ei-last)) (ass) (ei-foc! ei-gu1)
  (subst `(= ,EI-GARHS ((ADD A) ,EI-GIL ((MUL A) ,EI-GIK ,EI-NEGr))))
  (subst '(= c l))
  (fact 'elem-g-col-l 'A 'n 'r 'k 'l 'i)
  (subst `(= ,EI-GIL ,EI-GILx))
  (fact 'elem-g-col-k 'A 'n 'r 'k 'l 'i)
  (subst `(= ,EI-GIK ,EI-GIKx))
  (cut '(NOT (= l k)))
  (define ei-gml (ei-last)) (di) (fact 'eq-sym 'l 'k) (ai '(NOT (= k l))) (ei-foc! ei-gml)
  (define ei-g-notil (ei-cases '(= i l)))
  ;; i = l
  (subst '(= i l))
  (if-true '(IF (= l l) (ONE A) (IF (= l k) r (ZERO A))))
  (define ei-gu2 (ei-last)) (rfl) (ei-foc! ei-gu2)
  (subst '(= (IF (= l l) (ONE A) (IF (= l k) r (ZERO A))) (ONE A)))
  (if-false '(IF (= l k) (ONE A) (ZERO A)))
  (define ei-gu3 (ei-last)) (ass) (ei-foc! ei-gu3)
  (subst '(= (IF (= l k) (ONE A) (ZERO A)) (ZERO A)))
  (fact 'ring-mul-zero-left 'A EI-NEGr)
  (subst `(= ((MUL A) (ZERO A) ,EI-NEGr) (ZERO A)))
  (fact 'ring-one-in 'A)
  (fact 'ring-add-right-id 'A '(ONE A))
  (subst '(= ((ADD A) (ONE A) (ZERO A)) (ONE A)))
  (if-true '(IF (= l l) (ONE A) (ZERO A)))
  (define ei-gu4 (ei-last)) (rfl) (ei-foc! ei-gu4)
  (subst '(= (IF (= l l) (ONE A) (ZERO A)) (ONE A)))
  (rfl)
  ;; i /= l
  (ei-foc! ei-g-notil)
  (if-false '(IF (= i l) (ONE A) (IF (= i k) r (ZERO A))))
  (define ei-gu5 (ei-last)) (ass) (ei-foc! ei-gu5)
  (subst '(= (IF (= i l) (ONE A) (IF (= i k) r (ZERO A))) (IF (= i k) r (ZERO A))))
  (if-false '(IF (= i l) (ONE A) (ZERO A)))
  (define ei-gu6 (ei-last)) (ass) (ei-foc! ei-gu6)
  (subst '(= (IF (= i l) (ONE A) (ZERO A)) (ZERO A)))
  (define ei-g-notik (ei-cases '(= i k)))
  ;; i = k
  (subst '(= i k))
  (if-true '(IF (= k k) r (ZERO A)))
  (define ei-gu7 (ei-last)) (rfl) (ei-foc! ei-gu7)
  (subst '(= (IF (= k k) r (ZERO A)) r))
  (if-true '(IF (= k k) (ONE A) (ZERO A)))
  (define ei-gu8 (ei-last)) (rfl) (ei-foc! ei-gu8)
  (subst '(= (IF (= k k) (ONE A) (ZERO A)) (ONE A)))
  (fact 'ring-mul-left-id 'A EI-NEGr)
  (subst `(= ((MUL A) (ONE A) ,EI-NEGr) ,EI-NEGr))
  (fact 'ring-add-right-inv 'A 'r)
  (subst `(= ((ADD A) r ,EI-NEGr) (ZERO A)))
  (rfl)
  ;; i /= k
  (ei-foc! ei-g-notik)
  (if-false '(IF (= i k) r (ZERO A)))
  (define ei-gu9 (ei-last)) (ass) (ei-foc! ei-gu9)
  (subst '(= (IF (= i k) r (ZERO A)) (ZERO A)))
  (if-false '(IF (= i k) (ONE A) (ZERO A)))
  (define ei-gu10 (ei-last)) (ass) (ei-foc! ei-gu10)
  (subst '(= (IF (= i k) (ONE A) (ZERO A)) (ZERO A)))
  (fact 'ring-mul-zero-left 'A EI-NEGr)
  (subst `(= ((MUL A) (ZERO A) ,EI-NEGr) (ZERO A)))
  (fact 'ring-zero-in 'A)
  (fact 'ring-add-right-id 'A '(ZERO A))
  (subst '(= ((ADD A) (ZERO A) (ZERO A)) (ZERO A)))
  (rfl)
  ;; c /= l
  (ei-foc! ei-g-notcl)
  (if-false EI-GARHS)
  (define ei-gu11 (ei-last)) (ass) (ei-foc! ei-gu11)
  (subst `(= ,EI-GARHS ,EI-GIC))
  (fact 'elem-g-col-other 'A 'n 'r 'k 'l 'i 'c)
  (subst `(= ,EI-GIC (IF (= i c) (ONE A) (ZERO A))))
  (rfl)
(ei-foc! ei-gmain)
(fact 'matrix-entry-extensionality 'n 'n '(CARR A) EI-GPROD '(IDENTMAT A n))
(ass)
(qed 'elem-g-inverse)
(topic! 'elem-g-inverse 'algebra)

;;; ===================== elem-f-inverse ============================
(define EI-FKL '(ELEM-F A n k l))
(define EI-FLK '(ELEM-F A n l k))
(define EI-FPROD `(MATMUL A ,EI-FKL ,EI-FLK))
(define EI-FARHS `(IF (= c l) (ENTRY ,EI-FKL i k) (IF (= c k) (ENTRY ,EI-FKL i l) (ENTRY ,EI-FKL i c))))
(define EI-FINNER `(IF (= c k) (ENTRY ,EI-FKL i l) (ENTRY ,EI-FKL i c)))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL n (FORALL k (FORALL l
       (IMPLIES (IN k (INTERVAL 1 n))
       (IMPLIES (IN l (INTERVAL 1 n))
       (IMPLIES (NOT (= k l))
         (= (MATMUL A (ELEM-F A n k l) (ELEM-F A n l k)) (IDENTMAT A n))))))))))))
(ei-di*)
(cut '(NOT (= l k)))
(define ei-fm0 (ei-last)) (di) (fact 'eq-sym 'l 'k) (ai '(NOT (= k l))) (ei-foc! ei-fm0)
(fact 'elem-f-type 'A 'n 'k 'l)
(fact 'elem-f-type 'A 'n 'l 'k)
(fact 'matmul-type 'A 'n 'n 'n EI-FKL EI-FLK)
(fact 'identmat-type 'A 'n)
(cut `(FORALL i (IMPLIES (IN i (INTERVAL 1 n))
        (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
          (= (ENTRY ,EI-FPROD i c) (ENTRY (IDENTMAT A n) i c)))))))
(define ei-fmain (ei-last))
  (di) (di) (di) (di)
  (fact 'elem-f-action 'A 'n 'n EI-FKL 'l 'k 'i 'c)
  (subst `(= (ENTRY ,EI-FPROD i c) ,EI-FARHS))
  (fact 'entry-of-identmat 'A 'n 'i 'c)
  (subst '(= (ENTRY (IDENTMAT A n) i c) (IF (= i c) (ONE A) (ZERO A))))
  (define ei-f-notcl (ei-cases '(= c l)))
  ;; c = l
  (if-true EI-FARHS)
  (define ei-fu1 (ei-last)) (ass) (ei-foc! ei-fu1)
  (subst `(= ,EI-FARHS (ENTRY ,EI-FKL i k)))
  (fact 'elem-f-col-k 'A 'n 'k 'l 'i)
  (subst `(= (ENTRY ,EI-FKL i k) (IF (= i l) (ONE A) (ZERO A))))
  (subst '(= c l))
  (rfl)
  ;; c /= l
  (ei-foc! ei-f-notcl)
  (if-false EI-FARHS)
  (define ei-fu2 (ei-last)) (ass) (ei-foc! ei-fu2)
  (subst `(= ,EI-FARHS ,EI-FINNER))
  (define ei-f-notck (ei-cases '(= c k)))
  ;; c = k
  (if-true EI-FINNER)
  (define ei-fu3 (ei-last)) (ass) (ei-foc! ei-fu3)
  (subst `(= ,EI-FINNER (ENTRY ,EI-FKL i l)))
  (fact 'elem-f-col-l 'A 'n 'k 'l 'i)
  (subst `(= (ENTRY ,EI-FKL i l) (IF (= i k) (ONE A) (ZERO A))))
  (subst '(= c k))
  (rfl)
  ;; c /= k, c /= l
  (ei-foc! ei-f-notck)
  (if-false EI-FINNER)
  (define ei-fu4 (ei-last)) (ass) (ei-foc! ei-fu4)
  (subst `(= ,EI-FINNER (ENTRY ,EI-FKL i c)))
  (fact 'elem-f-col-other 'A 'n 'k 'l 'i 'c)
  (subst `(= (ENTRY ,EI-FKL i c) (IF (= i c) (ONE A) (ZERO A))))
  (rfl)
(ei-foc! ei-fmain)
(fact 'matrix-entry-extensionality 'n 'n '(CARR A) EI-FPROD '(IDENTMAT A n))
(ass)
(qed 'elem-f-inverse)
(topic! 'elem-f-inverse 'algebra)
