;;; elem-actions-proof.scm -- Prop 3.5 (algebraic-numbers.pdf ch.3): the action of
;;; the elementary column matrices on a matrix by right-multiplication.  Each is
;;; the matmul-entry expansion + a finsum collapse (single-support for H, and for
;;; the off-l column of G; two-support for G's l-column), closed by an
;;; excluded-middle case split -- the same shape as matunit-shift-proof.scm.

;; --- shared proof helpers ---
(define (ea-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (ea-foc! n) (set-proof-state-focus! *ps* n))
(define (ea-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (ea-di*) (let lp () (let* ((g (ea-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (ea-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((uo (ea-last)))
    (pbc) (cut `(NOT ,P))
    (let ((un (ea-last)))
      (di) (cut `(OR ,P (NOT ,P)))
      (let ((u2 (ea-last))) (oi-l) (ass) (ea-foc! u2))
      (ai `(NOT (OR ,P (NOT ,P)))) (ea-foc! un))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (ea-last))) (oi-r) (ass) (ea-foc! u3))
    (ai `(NOT (OR ,P (NOT ,P)))) (ea-foc! uo)))
(define (ea-cases P) (ea-em P) (ai `(OR ,P (NOT ,P))) (ea-last))

(define EA-RAG '(RING-ADDITIVE-AG A))
(define EA-INT '(INTERVAL 1 n))

;;; ===================== elem-h-action ============================
;;; (P . H[r,k])_{ic} = P_{ik}.r  if c=k,  else P_{ic}.
(define EA-HFF '(VNB-LAMBDA j ((MUL A) (ENTRY P i j) (ENTRY (ELEM-H A n r k) j c))))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL m (FORALL n (FORALL P (FORALL r (FORALL k
       (IMPLIES (IN P (MAT m n (CARR A)))
       (IMPLIES (IN r (CARR A))
       (IMPLIES (IN k (INTERVAL 1 n))
       (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
       (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
         (= (ENTRY (MATMUL A P (ELEM-H A n r k)) i c)
            (IF (= c k) ((MUL A) (ENTRY P i k) r) (ENTRY P i c)))))))))))))))))))
(ea-di*)
(fact 'elem-h-type 'A 'n 'r 'k)
(fact 'matmul-entry 'A 'm 'n 'n 'P '(ELEM-H A n r k) 'i 'c)
(subst `(= (ENTRY (MATMUL A P (ELEM-H A n r k)) i c) (FINSUM ,EA-RAG ,EA-HFF ,EA-INT)))
(fact 'ring-additive-ag-is-abelian-group 'A)
(fact 'interval-in-set 1 'n)
(fact 'interval-card-in-nn 1 'n)
(fact 'matprod-summand-type 'A 'm 'n 'n 'P '(ELEM-H A n r k) 'i 'c)
(cut `(FORALL jz (IMPLIES (IN jz ,EA-INT)
        (IMPLIES (NOT (= jz c)) (= (,EA-HFF jz) (ID ,EA-RAG))))))
(define ea-h-main (ea-last))
  (di) (di) (di)
  (lam-b)
  (fact 'elem-h-entry-off-diag 'A 'n 'r 'k 'jz 'c)
  (subst `(= (ENTRY (ELEM-H A n r k) jz c) (ZERO A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'jz)
  (fact 'ring-mul-zero-right 'A '(ENTRY P i jz))
  (subst `(= ((MUL A) (ENTRY P i jz) (ZERO A)) (ZERO A)))
  (fact 'ras-id 'A)
  (subst `(= (ID (RING-ADDITIVE-AG A)) (ZERO A)))
  (rfl)
(ea-foc! ea-h-main)
(fact 'finsum-single-support EA-RAG EA-INT EA-HFF 'c)
(subst `(= (FINSUM ,EA-RAG ,EA-HFF ,EA-INT) (,EA-HFF c)))
(lam-b)
(fact 'elem-h-entry-diag 'A 'n 'r 'k 'c)
(subst `(= (ENTRY (ELEM-H A n r k) c c) (IF (= c k) r (ONE A))))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'c)
(define ea-h-not (ea-cases '(= c k)))
;; c=k
(if-true '(IF (= c k) r (ONE A)))
(define ea-h-pl (ea-last)) (ass) (ea-foc! ea-h-pl)
(subst '(= (IF (= c k) r (ONE A)) r))
(if-true '(IF (= c k) ((MUL A) (ENTRY P i k) r) (ENTRY P i c)))
(define ea-h-pr (ea-last)) (ass) (ea-foc! ea-h-pr)
(subst '(= (IF (= c k) ((MUL A) (ENTRY P i k) r) (ENTRY P i c)) ((MUL A) (ENTRY P i k) r)))
(subst '(= c k))
(rfl)
;; c/=k
(ea-foc! ea-h-not)
(if-false '(IF (= c k) r (ONE A)))
(define ea-h-nl (ea-last)) (ass) (ea-foc! ea-h-nl)
(subst '(= (IF (= c k) r (ONE A)) (ONE A)))
(if-false '(IF (= c k) ((MUL A) (ENTRY P i k) r) (ENTRY P i c)))
(define ea-h-nr (ea-last)) (ass) (ea-foc! ea-h-nr)
(subst '(= (IF (= c k) ((MUL A) (ENTRY P i k) r) (ENTRY P i c)) (ENTRY P i c)))
(fact 'ring-mul-right-id 'A '(ENTRY P i c))
(subst '(= ((MUL A) (ENTRY P i c) (ONE A)) (ENTRY P i c)))
(rfl)
(qed 'elem-h-action)
(category! 'elem-h-action 'algebra)

;;; ===================== elem-g-action ============================
;;; (P . G[r,k,l])_{ic} = P_{il} + P_{ik}.r  if c=l,  else P_{ic}.  Case-split on
;;; (c=l): the l-column has TWO supports (diagonal l, value 1; unit's k, value r,
;;; k/=l) -> finsum-two-support; off l it is a single-support identity column.
(define EA-GFF '(VNB-LAMBDA j ((MUL A) (ENTRY P i j) (ENTRY (ELEM-G A n r k l) j c))))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL m (FORALL n (FORALL P (FORALL r (FORALL k (FORALL l
       (IMPLIES (IN P (MAT m n (CARR A)))
       (IMPLIES (IN r (CARR A))
       (IMPLIES (IN k (INTERVAL 1 n))
       (IMPLIES (IN l (INTERVAL 1 n))
       (IMPLIES (NOT (= k l))
       (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
       (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
         (= (ENTRY (MATMUL A P (ELEM-G A n r k l)) i c)
            (IF (= c l)
                ((ADD A) (ENTRY P i l) ((MUL A) (ENTRY P i k) r))
                (ENTRY P i c))))))))))))))))))))))
(ea-di*)
(fact 'elem-g-type 'A 'n 'r 'k 'l)
(fact 'matmul-entry 'A 'm 'n 'n 'P '(ELEM-G A n r k l) 'i 'c)
(subst `(= (ENTRY (MATMUL A P (ELEM-G A n r k l)) i c) (FINSUM ,EA-RAG ,EA-GFF ,EA-INT)))
(fact 'ring-additive-ag-is-abelian-group 'A)
(fact 'interval-in-set 1 'n)
(fact 'interval-card-in-nn 1 'n)
(fact 'matprod-summand-type 'A 'm 'n 'n 'P '(ELEM-G A n r k l) 'i 'c)
(define ea-g-not (ea-cases '(= c l)))
;; ---- c = l branch (two-support) ----
(if-true '(IF (= c l) ((ADD A) (ENTRY P i l) ((MUL A) (ENTRY P i k) r)) (ENTRY P i c)))
(define ea-g-rhs (ea-last)) (ass) (ea-foc! ea-g-rhs)
(subst '(= (IF (= c l) ((ADD A) (ENTRY P i l) ((MUL A) (ENTRY P i k) r)) (ENTRY P i c))
           ((ADD A) (ENTRY P i l) ((MUL A) (ENTRY P i k) r))))
(cut '(NOT (= l k)))
(define ea-g-m1 (ea-last))
  (di) (fact 'eq-sym 'l 'k) (ai '(NOT (= k l)))
(ea-foc! ea-g-m1)
(cut `(FORALL jz (IMPLIES (IN jz ,EA-INT)
        (IMPLIES (NOT (= jz l)) (IMPLIES (NOT (= jz k)) (= (,EA-GFF jz) (ID ,EA-RAG)))))))
(define ea-g-m2 (ea-last))
  (di) (di) (di) (di)
  (lam-b)
  (fact 'elem-g-entry-l-vanish 'A 'n 'r 'k 'l 'jz 'c)
  (subst `(= (ENTRY (ELEM-G A n r k l) jz c) (ZERO A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'jz)
  (fact 'ring-mul-zero-right 'A '(ENTRY P i jz))
  (subst `(= ((MUL A) (ENTRY P i jz) (ZERO A)) (ZERO A)))
  (fact 'ras-id 'A)
  (subst `(= (ID (RING-ADDITIVE-AG A)) (ZERO A)))
  (rfl)
(ea-foc! ea-g-m2)
(fact 'finsum-two-support EA-RAG EA-INT EA-GFF 'l 'k)
(subst `(= (FINSUM ,EA-RAG ,EA-GFF ,EA-INT) ((MUL ,EA-RAG) (,EA-GFF l) (,EA-GFF k))))
(lam-b)
(fact 'elem-g-entry-l-at-l 'A 'n 'r 'k 'l 'c)
(subst `(= (ENTRY (ELEM-G A n r k l) l c) (ONE A)))
(fact 'elem-g-entry-l-at-k 'A 'n 'r 'k 'l 'c)
(subst `(= (ENTRY (ELEM-G A n r k l) k c) r))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'l)
(fact 'ring-mul-right-id 'A '(ENTRY P i l))
(subst `(= ((MUL A) (ENTRY P i l) (ONE A)) (ENTRY P i l)))
(mac 'ras-op)
(rfl)
;; ---- c /= l branch (single-support) ----
(ea-foc! ea-g-not)
(if-false '(IF (= c l) ((ADD A) (ENTRY P i l) ((MUL A) (ENTRY P i k) r)) (ENTRY P i c)))
(define ea-g-nrhs (ea-last)) (ass) (ea-foc! ea-g-nrhs)
(subst '(= (IF (= c l) ((ADD A) (ENTRY P i l) ((MUL A) (ENTRY P i k) r)) (ENTRY P i c))
           (ENTRY P i c)))
(cut `(FORALL jz (IMPLIES (IN jz ,EA-INT)
        (IMPLIES (NOT (= jz c)) (= (,EA-GFF jz) (ID ,EA-RAG))))))
(define ea-g-nm (ea-last))
  (di) (di) (di)
  (lam-b)
  (fact 'elem-g-entry-off-l-off-diag 'A 'n 'r 'k 'l 'jz 'c)
  (subst `(= (ENTRY (ELEM-G A n r k l) jz c) (ZERO A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'jz)
  (fact 'ring-mul-zero-right 'A '(ENTRY P i jz))
  (subst `(= ((MUL A) (ENTRY P i jz) (ZERO A)) (ZERO A)))
  (fact 'ras-id 'A)
  (subst `(= (ID (RING-ADDITIVE-AG A)) (ZERO A)))
  (rfl)
(ea-foc! ea-g-nm)
(fact 'finsum-single-support EA-RAG EA-INT EA-GFF 'c)
(subst `(= (FINSUM ,EA-RAG ,EA-GFF ,EA-INT) (,EA-GFF c)))
(lam-b)
(fact 'elem-g-entry-off-l-diag 'A 'n 'r 'k 'l 'c)
(subst `(= (ENTRY (ELEM-G A n r k l) c c) (ONE A)))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'c)
(fact 'ring-mul-right-id 'A '(ENTRY P i c))
(subst `(= ((MUL A) (ENTRY P i c) (ONE A)) (ENTRY P i c)))
(rfl)
(qed 'elem-g-action)
(category! 'elem-g-action 'algebra)

;;; ===================== elem-f-action ============================
;;; (P . F[k,l])_{ic} = P_{il} (c=k), P_{ik} (c=l), P_{ic} (else).  F[k,l] is the
;;; transposition permutation matrix, so each column is a single unit vector:
;;; column k supported at row l, column l at row k, any other column c at row c.
;;; Three-way case split on (c=k) then (c=l); each branch a single-support collapse.
(define EA-FFF '(VNB-LAMBDA j ((MUL A) (ENTRY P i j) (ENTRY (ELEM-F A n k l) j c))))
;; collapse a single-support column at row ROW: goal (= (FINSUM..) (ENTRY P i ROW));
;; offpss/atpss are the off-support / at-support entry read-offs for that column.
(define (ea-collapse ROW offpss atpss)
  (cut `(FORALL jz (IMPLIES (IN jz ,EA-INT)
          (IMPLIES (NOT (= jz ,ROW)) (= (,EA-FFF jz) (ID ,EA-RAG))))))
  (let ((mn (ea-last)))
    (di) (di) (di)
    (lam-b)
    (fact offpss 'A 'n 'k 'l 'jz 'c)
    (subst `(= (ENTRY (ELEM-F A n k l) jz c) (ZERO A)))
    (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'jz)
    (fact 'ring-mul-zero-right 'A '(ENTRY P i jz))
    (subst `(= ((MUL A) (ENTRY P i jz) (ZERO A)) (ZERO A)))
    (fact 'ras-id 'A)
    (subst `(= (ID (RING-ADDITIVE-AG A)) (ZERO A)))
    (rfl)
    (ea-foc! mn))
  (fact 'finsum-single-support EA-RAG EA-INT EA-FFF ROW)
  (subst `(= (FINSUM ,EA-RAG ,EA-FFF ,EA-INT) (,EA-FFF ,ROW)))
  (lam-b)
  (fact atpss 'A 'n 'k 'l 'c)
  (subst `(= (ENTRY (ELEM-F A n k l) ,ROW c) (ONE A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i ROW)
  (fact 'ring-mul-right-id 'A `(ENTRY P i ,ROW))
  (subst `(= ((MUL A) (ENTRY P i ,ROW) (ONE A)) (ENTRY P i ,ROW)))
  (rfl))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL m (FORALL n (FORALL P (FORALL k (FORALL l
       (IMPLIES (IN P (MAT m n (CARR A)))
       (IMPLIES (IN k (INTERVAL 1 n))
       (IMPLIES (IN l (INTERVAL 1 n))
       (IMPLIES (NOT (= k l))
       (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
       (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
         (= (ENTRY (MATMUL A P (ELEM-F A n k l)) i c)
            (IF (= c k) (ENTRY P i l)
                (IF (= c l) (ENTRY P i k) (ENTRY P i c)))))))))))))))))))))
(ea-di*)
(fact 'elem-f-type 'A 'n 'k 'l)
(fact 'matmul-entry 'A 'm 'n 'n 'P '(ELEM-F A n k l) 'i 'c)
(subst `(= (ENTRY (MATMUL A P (ELEM-F A n k l)) i c) (FINSUM ,EA-RAG ,EA-FFF ,EA-INT)))
(fact 'ring-additive-ag-is-abelian-group 'A)
(fact 'interval-in-set 1 'n)
(fact 'interval-card-in-nn 1 'n)
(fact 'matprod-summand-type 'A 'm 'n 'n 'P '(ELEM-F A n k l) 'i 'c)
(define ea-f-notk (ea-cases '(= c k)))
;; c = k : RHS = P_{il}, support at row l
(if-true '(IF (= c k) (ENTRY P i l) (IF (= c l) (ENTRY P i k) (ENTRY P i c))))
(define ea-f-rk (ea-last)) (ass) (ea-foc! ea-f-rk)
(subst '(= (IF (= c k) (ENTRY P i l) (IF (= c l) (ENTRY P i k) (ENTRY P i c))) (ENTRY P i l)))
(ea-collapse 'l 'elem-f-ck-off 'elem-f-ck-at)
;; c /= k
(ea-foc! ea-f-notk)
(if-false '(IF (= c k) (ENTRY P i l) (IF (= c l) (ENTRY P i k) (ENTRY P i c))))
(define ea-f-rnk (ea-last)) (ass) (ea-foc! ea-f-rnk)
(subst '(= (IF (= c k) (ENTRY P i l) (IF (= c l) (ENTRY P i k) (ENTRY P i c)))
           (IF (= c l) (ENTRY P i k) (ENTRY P i c))))
(define ea-f-notl (ea-cases '(= c l)))
;; c = l : RHS = P_{ik}, support at row k
(if-true '(IF (= c l) (ENTRY P i k) (ENTRY P i c)))
(define ea-f-rl (ea-last)) (ass) (ea-foc! ea-f-rl)
(subst '(= (IF (= c l) (ENTRY P i k) (ENTRY P i c)) (ENTRY P i k)))
(ea-collapse 'k 'elem-f-cl-off 'elem-f-cl-at)
;; c /= k, c /= l : RHS = P_{ic}, support at row c
(ea-foc! ea-f-notl)
(if-false '(IF (= c l) (ENTRY P i k) (ENTRY P i c)))
(define ea-f-rnl (ea-last)) (ass) (ea-foc! ea-f-rnl)
(subst '(= (IF (= c l) (ENTRY P i k) (ENTRY P i c)) (ENTRY P i c)))
(ea-collapse 'c 'elem-f-co-off 'elem-f-co-at)
(qed 'elem-f-action)
(category! 'elem-f-action 'algebra)
