;;; elem-row-actions-proof.scm -- Prop 3.29 (row form, algebraic-numbers.pdf ch.3):
;;; the action of the elementary matrices by LEFT-multiplication (row operations).
;;; Each mirrors theorem-library/elem-actions-proof.scm with the elementary matrix
;;; as the LEFT factor of matmul-entry: (E.P)_{ic} = FINSUM_j E_{ij}.P_{jc}, so a
;;; row of E picks a row of P.  Same collapse shape (matmul-entry + finsum single/
;;; two-support + excluded-middle case split); ZERO/ONE now on the LEFT of MUL
;;; (ring-mul-zero-left / ring-mul-left-id).  Row read-offs elem-{f,g,h}-r* in
;;; structure-library/elementary-matrix.scm.

;; --- shared proof helpers (copied from elem-actions-proof.scm) ---
(define (ea-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (ea-foc! n) (set-proof-state-focus! *ps* n))
(define (ea-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (ea-di*) (let lp () (let* ((g (ea-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (ea-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((uo (ea-last)))
    (pbc) (cut `(NOT ,P))
    (let ((un (ea-last)))
      (di) (cut `(OR ,P (NOT ,P)))
      (let ((u2 (ea-last))) (oi-l) (ass) (ea-foc! u2))
      (ai `(NOT (OR ,P (NOT ,P)))) (ea-foc! un))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (ea-last))) (oi-r) (ass) (ea-foc! u3))
    (ai `(NOT (OR ,P (NOT ,P)))) (ea-foc! uo)))
(define (ea-cases P) (ea-em P) (ai `(OR ,P (NOT ,P))) (ea-last))

(define EA-RAG '(RING-ADDITIVE-AG A))
(define EA-INT '(INTERVAL 1 m))   ; row action: FINSUM over the m rows

;;; ===================== elem-h-row-action ============================
;;; (H[r,k] . P)_{ic} = r.P_{kc} if i=k, else P_{ic}.  H is diagonal: row i has a
;;; single support at column i.  Case-split on (i=k).
(define EA-HFF '(VNB-LAMBDA j ((MUL A) (ENTRY (ELEM-H A m r k) i j) (ENTRY P j c))))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL m (FORALL n (FORALL P (FORALL r (FORALL k
       (IMPLIES (IN P (MAT m n (CARR A)))
       (IMPLIES (IN r (CARR A))
       (IMPLIES (IN k (INTERVAL 1 m))
       (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
       (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
         (= (ENTRY (MATMUL A (ELEM-H A m r k) P) i c)
            (IF (= i k) ((MUL A) r (ENTRY P k c)) (ENTRY P i c)))))))))))))))))))
(ea-di*)
(fact 'elem-h-type 'A 'm 'r 'k)
(fact 'matmul-entry 'A 'm 'm 'n '(ELEM-H A m r k) 'P 'i 'c)
(subst `(= (ENTRY (MATMUL A (ELEM-H A m r k) P) i c) (FINSUM ,EA-RAG ,EA-HFF ,EA-INT)))
(fact 'ring-additive-ag-is-abelian-group 'A)
(fact 'interval-in-set 1 'm)
(fact 'interval-card-in-nn 1 'm)
(fact 'matprod-summand-type 'A 'm 'm 'n '(ELEM-H A m r k) 'P 'i 'c)
;; VANISH: off the support column i, the summand is the group identity.
(cut `(FORALL jz (IMPLIES (IN jz ,EA-INT)
        (IMPLIES (NOT (= jz i)) (= (,EA-HFF jz) (IDEN ,EA-RAG))))))
(define rh-main (ea-last))
  (di) (di) (di)
  (lam-b)
  (fact 'elem-h-ro-off 'A 'm 'r 'k 'i 'jz)
  (subst `(= (ENTRY (ELEM-H A m r k) i jz) (ZERO A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'jz 'c)
  (fact 'ring-mul-zero-left 'A '(ENTRY P jz c))
  (subst `(= ((MUL A) (ZERO A) (ENTRY P jz c)) (ZERO A)))
  (fact 'ras-id 'A)
  (subst `(= (IDEN (RING-ADDITIVE-AG A)) (ZERO A)))
  (rfl)
(ea-foc! rh-main)
(fact 'finsum-single-support EA-RAG EA-INT EA-HFF 'i)
(subst `(= (FINSUM ,EA-RAG ,EA-HFF ,EA-INT) (,EA-HFF i)))
(lam-b)
(fact 'elem-h-ro-at 'A 'm 'r 'k 'i)
(subst `(= (ENTRY (ELEM-H A m r k) i i) (IF (= i k) r (ONE A))))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'c)
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'k 'c)
(define rh-not (ea-cases '(= i k)))
;; i=k
(if-true '(IF (= i k) r (ONE A)))
(define rh-pl (ea-last)) (ass) (ea-foc! rh-pl)
(subst '(= (IF (= i k) r (ONE A)) r))
(if-true '(IF (= i k) ((MUL A) r (ENTRY P k c)) (ENTRY P i c)))
(define rh-pr (ea-last)) (ass) (ea-foc! rh-pr)
(subst '(= (IF (= i k) ((MUL A) r (ENTRY P k c)) (ENTRY P i c)) ((MUL A) r (ENTRY P k c))))
(subst '(= i k))
(rfl)
;; i/=k
(ea-foc! rh-not)
(if-false '(IF (= i k) r (ONE A)))
(define rh-nl (ea-last)) (ass) (ea-foc! rh-nl)
(subst '(= (IF (= i k) r (ONE A)) (ONE A)))
(if-false '(IF (= i k) ((MUL A) r (ENTRY P k c)) (ENTRY P i c)))
(define rh-nr (ea-last)) (ass) (ea-foc! rh-nr)
(subst '(= (IF (= i k) ((MUL A) r (ENTRY P k c)) (ENTRY P i c)) (ENTRY P i c)))
(fact 'ring-mul-left-id 'A '(ENTRY P i c))
(subst '(= ((MUL A) (ONE A) (ENTRY P i c)) (ENTRY P i c)))
(rfl)
(qed 'elem-h-row-action)
(category! 'elem-h-row-action 'algebra)

;;; ===================== elem-g-row-action ============================
;;; (G[r,k,l] . P)_{ic} = P_{kc} + r.P_{lc} if i=k, else P_{ic}.  Row k has two
;;; supports (col k val 1, col l val r); split on (i=k).
(define EA-GFF '(VNB-LAMBDA j ((MUL A) (ENTRY (ELEM-G A m r k l) i j) (ENTRY P j c))))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL m (FORALL n (FORALL P (FORALL r (FORALL k (FORALL l
       (IMPLIES (IN P (MAT m n (CARR A)))
       (IMPLIES (IN r (CARR A))
       (IMPLIES (IN k (INTERVAL 1 m))
       (IMPLIES (IN l (INTERVAL 1 m))
       (IMPLIES (NOT (= k l))
       (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
       (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
         (= (ENTRY (MATMUL A (ELEM-G A m r k l) P) i c)
            (IF (= i k)
                ((ADD A) (ENTRY P k c) ((MUL A) r (ENTRY P l c)))
                (ENTRY P i c))))))))))))))))))))))
(ea-di*)
(fact 'elem-g-type 'A 'm 'r 'k 'l)
(fact 'matmul-entry 'A 'm 'm 'n '(ELEM-G A m r k l) 'P 'i 'c)
(subst `(= (ENTRY (MATMUL A (ELEM-G A m r k l) P) i c) (FINSUM ,EA-RAG ,EA-GFF ,EA-INT)))
(fact 'ring-additive-ag-is-abelian-group 'A)
(fact 'interval-in-set 1 'm)
(fact 'interval-card-in-nn 1 'm)
(fact 'matprod-summand-type 'A 'm 'm 'n '(ELEM-G A m r k l) 'P 'i 'c)
(define rg-not (ea-cases '(= i k)))
;; ---- i = k branch (two-support at columns k and l) ----
(if-true '(IF (= i k) ((ADD A) (ENTRY P k c) ((MUL A) r (ENTRY P l c))) (ENTRY P i c)))
(define rg-rhs (ea-last)) (ass) (ea-foc! rg-rhs)
(subst '(= (IF (= i k) ((ADD A) (ENTRY P k c) ((MUL A) r (ENTRY P l c))) (ENTRY P i c))
           ((ADD A) (ENTRY P k c) ((MUL A) r (ENTRY P l c)))))
(cut `(FORALL jz (IMPLIES (IN jz ,EA-INT)
        (IMPLIES (NOT (= jz k)) (IMPLIES (NOT (= jz l)) (= (,EA-GFF jz) (IDEN ,EA-RAG)))))))
(define rg-m2 (ea-last))
  (di) (di) (di) (di)
  (lam-b)
  (fact 'elem-g-rk-vanish 'A 'm 'r 'k 'l 'i 'jz)
  (subst `(= (ENTRY (ELEM-G A m r k l) i jz) (ZERO A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'jz 'c)
  (fact 'ring-mul-zero-left 'A '(ENTRY P jz c))
  (subst `(= ((MUL A) (ZERO A) (ENTRY P jz c)) (ZERO A)))
  (fact 'ras-id 'A)
  (subst `(= (IDEN (RING-ADDITIVE-AG A)) (ZERO A)))
  (rfl)
(ea-foc! rg-m2)
(fact 'finsum-two-support EA-RAG EA-INT EA-GFF 'k 'l)
(subst `(= (FINSUM ,EA-RAG ,EA-GFF ,EA-INT) ((MUL ,EA-RAG) (,EA-GFF k) (,EA-GFF l))))
(lam-b)
(fact 'elem-g-rk-at-k 'A 'm 'r 'k 'l 'i)
(subst `(= (ENTRY (ELEM-G A m r k l) i k) (ONE A)))
(fact 'elem-g-rk-at-l 'A 'm 'r 'k 'l 'i)
(subst `(= (ENTRY (ELEM-G A m r k l) i l) r))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'k 'c)
(fact 'ring-mul-left-id 'A '(ENTRY P k c))
(subst `(= ((MUL A) (ONE A) (ENTRY P k c)) (ENTRY P k c)))
(mac 'ras-op)
(rfl)
;; ---- i /= k branch (single support at column i) ----
(ea-foc! rg-not)
(if-false '(IF (= i k) ((ADD A) (ENTRY P k c) ((MUL A) r (ENTRY P l c))) (ENTRY P i c)))
(define rg-nrhs (ea-last)) (ass) (ea-foc! rg-nrhs)
(subst '(= (IF (= i k) ((ADD A) (ENTRY P k c) ((MUL A) r (ENTRY P l c))) (ENTRY P i c))
           (ENTRY P i c)))
(cut `(FORALL jz (IMPLIES (IN jz ,EA-INT)
        (IMPLIES (NOT (= jz i)) (= (,EA-GFF jz) (IDEN ,EA-RAG))))))
(define rg-nm (ea-last))
  (di) (di) (di)
  (lam-b)
  (fact 'elem-g-ro-off 'A 'm 'r 'k 'l 'i 'jz)
  (subst `(= (ENTRY (ELEM-G A m r k l) i jz) (ZERO A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'jz 'c)
  (fact 'ring-mul-zero-left 'A '(ENTRY P jz c))
  (subst `(= ((MUL A) (ZERO A) (ENTRY P jz c)) (ZERO A)))
  (fact 'ras-id 'A)
  (subst `(= (IDEN (RING-ADDITIVE-AG A)) (ZERO A)))
  (rfl)
(ea-foc! rg-nm)
(fact 'finsum-single-support EA-RAG EA-INT EA-GFF 'i)
(subst `(= (FINSUM ,EA-RAG ,EA-GFF ,EA-INT) (,EA-GFF i)))
(lam-b)
(fact 'elem-g-ro-at 'A 'm 'r 'k 'l 'i)
(subst `(= (ENTRY (ELEM-G A m r k l) i i) (ONE A)))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'c)
(fact 'ring-mul-left-id 'A '(ENTRY P i c))
(subst `(= ((MUL A) (ONE A) (ENTRY P i c)) (ENTRY P i c)))
(rfl)
(qed 'elem-g-row-action)
(category! 'elem-g-row-action 'algebra)

;;; ===================== elem-f-row-action ============================
;;; (F[k,l] . P)_{ic} = P_{lc} (i=k), P_{kc} (i=l), P_{ic} (else).  Each row of F
;;; is a unit vector; three-way split on (i=k) then (i=l).
(define EA-FFF '(VNB-LAMBDA j ((MUL A) (ENTRY (ELEM-F A m k l) i j) (ENTRY P j c))))
(define (ea-collapse-row SUPP offpss atpss)
  (cut `(FORALL jz (IMPLIES (IN jz ,EA-INT)
          (IMPLIES (NOT (= jz ,SUPP)) (= (,EA-FFF jz) (IDEN ,EA-RAG))))))
  (let ((mn (ea-last)))
    (di) (di) (di)
    (lam-b)
    (fact offpss 'A 'm 'k 'l 'i 'jz)
    (subst `(= (ENTRY (ELEM-F A m k l) i jz) (ZERO A)))
    (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'jz 'c)
    (fact 'ring-mul-zero-left 'A '(ENTRY P jz c))
    (subst `(= ((MUL A) (ZERO A) (ENTRY P jz c)) (ZERO A)))
    (fact 'ras-id 'A)
    (subst `(= (IDEN (RING-ADDITIVE-AG A)) (ZERO A)))
    (rfl)
    (ea-foc! mn))
  (fact 'finsum-single-support EA-RAG EA-INT EA-FFF SUPP)
  (subst `(= (FINSUM ,EA-RAG ,EA-FFF ,EA-INT) (,EA-FFF ,SUPP)))
  (lam-b)
  (fact atpss 'A 'm 'k 'l 'i)
  (subst `(= (ENTRY (ELEM-F A m k l) i ,SUPP) (ONE A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P SUPP 'c)
  (fact 'ring-mul-left-id 'A `(ENTRY P ,SUPP c))
  (subst `(= ((MUL A) (ONE A) (ENTRY P ,SUPP c)) (ENTRY P ,SUPP c)))
  (rfl))
(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL m (FORALL n (FORALL P (FORALL k (FORALL l
       (IMPLIES (IN P (MAT m n (CARR A)))
       (IMPLIES (IN k (INTERVAL 1 m))
       (IMPLIES (IN l (INTERVAL 1 m))
       (IMPLIES (NOT (= k l))
       (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
       (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
         (= (ENTRY (MATMUL A (ELEM-F A m k l) P) i c)
            (IF (= i k) (ENTRY P l c)
                (IF (= i l) (ENTRY P k c) (ENTRY P i c)))))))))))))))))))))
(ea-di*)
(fact 'elem-f-type 'A 'm 'k 'l)
(fact 'matmul-entry 'A 'm 'm 'n '(ELEM-F A m k l) 'P 'i 'c)
(subst `(= (ENTRY (MATMUL A (ELEM-F A m k l) P) i c) (FINSUM ,EA-RAG ,EA-FFF ,EA-INT)))
(fact 'ring-additive-ag-is-abelian-group 'A)
(fact 'interval-in-set 1 'm)
(fact 'interval-card-in-nn 1 'm)
(fact 'matprod-summand-type 'A 'm 'm 'n '(ELEM-F A m k l) 'P 'i 'c)
(define rf-notk (ea-cases '(= i k)))
;; i = k : RHS = P_{lc}, support at column l
(if-true '(IF (= i k) (ENTRY P l c) (IF (= i l) (ENTRY P k c) (ENTRY P i c))))
(define rf-rk (ea-last)) (ass) (ea-foc! rf-rk)
(subst '(= (IF (= i k) (ENTRY P l c) (IF (= i l) (ENTRY P k c) (ENTRY P i c))) (ENTRY P l c)))
(ea-collapse-row 'l 'elem-f-rk-off 'elem-f-rk-at)
;; i /= k
(ea-foc! rf-notk)
(if-false '(IF (= i k) (ENTRY P l c) (IF (= i l) (ENTRY P k c) (ENTRY P i c))))
(define rf-rnk (ea-last)) (ass) (ea-foc! rf-rnk)
(subst '(= (IF (= i k) (ENTRY P l c) (IF (= i l) (ENTRY P k c) (ENTRY P i c)))
           (IF (= i l) (ENTRY P k c) (ENTRY P i c))))
(define rf-notl (ea-cases '(= i l)))
;; i = l : RHS = P_{kc}, support at column k
(if-true '(IF (= i l) (ENTRY P k c) (ENTRY P i c)))
(define rf-rl (ea-last)) (ass) (ea-foc! rf-rl)
(subst '(= (IF (= i l) (ENTRY P k c) (ENTRY P i c)) (ENTRY P k c)))
(ea-collapse-row 'k 'elem-f-rl-off 'elem-f-rl-at)
;; i /= k, i /= l : RHS = P_{ic}, support at column i
(ea-foc! rf-notl)
(if-false '(IF (= i l) (ENTRY P k c) (ENTRY P i c)))
(define rf-ro (ea-last)) (ass) (ea-foc! rf-ro)
(subst '(= (IF (= i l) (ENTRY P k c) (ENTRY P i c)) (ENTRY P i c)))
(ea-collapse-row 'i 'elem-f-ro-off 'elem-f-ro-at)
(qed 'elem-f-row-action)
(category! 'elem-f-row-action 'algebra)
