;;; goursat-bricks.scm -- the definition-free bricks of Cauchy-Goursat
;;; (complex-analysis.pdf ch. 3, s. 3.2).  Batch 29-B, 2026-09-25.
;;;
;;; (3) quarter-step           J <= J1 + J2 + J3 + J4, 0 <= Ji  =>  J <= 4 Ji for some i
;;;                            (the notes' (62): one of the four sub-triangles carries
;;;                            at least a quarter of the integral)
;;;     four-power-halving     4^n * (recip(2^n) * recip(2^n)) = 1  (the arithmetic of
;;;                            "4^(n-1) (2^-(n-1) len)^2 = len^2")
;;; (2) line-int-closed-road-of-derivative   Cor 3.3 for a road: the hypotheses of
;;;                            line-int-of-derivative plus pgam(b) = pgam(a) give 0
;;;     affine-has-primitive-cc  F(z) == c0 z + c1 ((z - a0)(z - a0)) recip(2) is
;;;                            holomorphic on CC with F'(z) = c0 + c1 (z - a0)
;;;     affine-closed-road-integral  the integral of z |-> c0 + c1 (z - a0) over a
;;;                            closed road is 0 (the step of (65) that uses Cor 3.3)
;;; (4) caratheodory-remainder-small   the notes' (65): IS-DIFF-ON over CC gives, for
;;;                            eps > 0, r > 0 with |f(z) - f(a) - L (z - a)| <= eps |z - a|
;;; (1) nn-succ-le-power-two   k + 1 <= 2^k
;;;     cc-telescoping-limit-bound  steps bounded by C 2^-k => a limit L in CC with
;;;                            |s(n) - L| <= 2 C 2^-n (the common point of the nested
;;;                            triangles, with no Cantor intersection and no diameter)
;;;
;;; NOTHING asserted, no definition.  Helper prefix gb-, binders gbv_, gbk_, ...
;;; LOAD WINDOW: lo = theorem-library/line-int-fundamental (line-int-of-derivative);
;;; also cc-power-series-deriv (cc-diff-on-quadratic), road-laws, cc-int-laws.  hi: none.

;;; ======================================================================
;;; (3a) quarter-step
;;; ======================================================================
(sp (make-wff
  '(FORALL gbj_ (IMPLIES (IN gbj_ RR)
    (FORALL gba_ (IMPLIES (IN gba_ RR)
    (FORALL gbb_ (IMPLIES (IN gbb_ RR)
    (FORALL gbc_ (IMPLIES (IN gbc_ RR)
    (FORALL gbd_ (IMPLIES (IN gbd_ RR)
     (IMPLIES (<= 0 gba_) (IMPLIES (<= 0 gbb_) (IMPLIES (<= 0 gbc_) (IMPLIES (<= 0 gbd_)
      (IMPLIES (<= gbj_ (+ (+ (+ gba_ gbb_) gbc_) gbd_))
       (OR (<= gbj_ (* 4 gba_))
        (OR (<= gbj_ (* 4 gbb_))
         (OR (<= gbj_ (* 4 gbc_)) (<= gbj_ (* 4 gbd_))))))))))))))))))))))
(dk-peel!)
(define gb-qs-sum (dk-pick (lambda (f) (and (pair? f) (eq? (car f) '<=) (pair? (caddr f))
                                            (eq? (car (caddr f)) '+)))
                           "J <= J1 + J2 + J3 + J4"))
;;; on (OR (<= J (* 4 X)) REST): split on the left disjunct; in the NOT case
;;; land 4X < J and go right.  FAILS accumulates the landed strict atoms.
(define (gb-qs! fails)
  (let ((g (dk-goal)))
    (if (and (pair? g) (eq? (car g) 'OR))
        (let* ((p (cadr g)) (j (cadr p)) (fx (caddr p)))
          (use-em p
            (lambda () (oi-l) (ass))
            (lambda ()
              (dk-type! fx 'RR)
              (let ((lt (dk-cite! 'rr-not-le-lt j fx)))
                (oi-r)
                (gb-qs! (cons lt fails))))))
        (apply dk-ineq! gb-qs-sum fails))))
(gb-qs! '())
(qed 'quarter-step)

;;; ======================================================================
;;; (3b) four-power-halving: 4^n * (recip(2^n) * recip(2^n)) = 1
;;; ======================================================================
(sp (make-wff
  '(FORALL gbn_ (IMPLIES (IN gbn_ NN)
     (= (* (power 4 gbn_) (* (recip (power 2 gbn_)) (recip (power 2 gbn_)))) 1)))))
(dk-peel!)
(define gb-n (cadr (dk-pick (lambda (f) (and (pair? f) (eq? (car f) 'IN) (eq? (caddr f) 'NN))) "n in NN")))
(define gb-x (list 'power 2 gb-n))
(define gb-rx (list 'recip gb-x))
(dk-type! gb-x 'RR)
(fact 'power-two-pos gb-n)
(fact 'rr-pos-ne-zero gb-x)
(dk-have! (list 'AND (list 'IN gb-x 'RR) (list 'NOT (list '= gb-x 0))) (lambda () (dk-conj-close! ass)))
(dk-cite! 'rr-recip-inverse gb-x)
(dk-cite! 'rr-recip-closed gb-x)
(dk-have! '(= 4 (* 2 2)) (lambda () (arith)))
(subst '(= 4 (* 2 2)))
(dk-have! '(IN 2 RR) (lambda () (arith)))
(dk-cite! 'rr-power-mul-base gb-n 2 2)
(subst (list '= (list 'power '(* 2 2) gb-n) (list '* gb-x gb-x)))
(dk-have! (list '= (list '* (list '* gb-x gb-x) (list '* gb-rx gb-rx))
                   (list '* (list '* gb-x gb-rx) (list '* gb-x gb-rx)))
          (lambda ()
            (let ((gen '(FORALL gbu_ (IMPLIES (IN gbu_ RR) (FORALL gbw_ (IMPLIES (IN gbw_ RR)
                          (= (* (* gbu_ gbu_) (* gbw_ gbw_)) (* (* gbu_ gbw_) (* gbu_ gbw_)))))))))
              (dk-have! gen (lambda () (dk-peel!) (crs)))
              (dk-apply! gen gb-x gb-rx)
              (ass))))
(subst (list '= (list '* (list '* gb-x gb-x) (list '* gb-rx gb-rx))
                (list '* (list '* gb-x gb-rx) (list '* gb-x gb-rx))))
(subst (list '= (list '* gb-x gb-rx) 1))
(arith)
(qed 'four-power-halving)

;;; ======================================================================
;;; local typing helpers (CC and RR terms built from context-typed atoms)
;;; ======================================================================
(define (gb-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (gb-and! a b)
  (let ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! (lambda () (ass))))))
    f))
(define (gb-cc-typ! t)
  (let ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((number? t) (dk-have! typ (lambda () (arith))) typ)
          ((dk-asm? (list 'IN t 'RR)) (fact 'rr-subset-cc t) typ)
          ((gb-op? t 'magnitude 2) (gb-cc-typ! (cadr t)) (fact 'cc-magnitude-closed (cadr t))
           (fact 'rr-subset-cc t) typ)
          ((gb-op? t '- 3) (gb-cc-typ! (cadr t)) (gb-cc-typ! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((gb-op? t '- 2) (gb-cc-typ! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((gb-op? t '+ 3) (gb-cc-typ! (cadr t)) (gb-cc-typ! (caddr t))
           (gb-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((gb-op? t '* 3) (gb-cc-typ! (cadr t)) (gb-cc-typ! (caddr t))
           (gb-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((gb-op? t 'recip 2) (gb-cc-typ! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (dk-have! (list 'NOT (list '= (cadr t) 0)) (lambda () (arith))))
           (gb-and! (list 'IN (cadr t) 'CC) (list 'NOT (list '= (cadr t) 0)))
           (fact 'cc-recip-closed (cadr t)) typ)
          (#t (error "gb-cc-typ!: cannot type" (expression->string t))))))

;;; ======================================================================
;;; (2a) line-int-closed-road-of-derivative: Corollary 3.3 for a road
;;; ======================================================================
(sp (make-wff "forall([u, f, df, pgam, dgam, a, b],
   holomorphic-on(u, f) implies
   df in fun(u, cc) implies
   forall([hbz_ in u], is-diff-on(cc-normed-field, u, f, hbz_, df(hbz_))) implies
   is-road(pgam, dgam, a, b) implies
   subset(trace(pgam, a, b), u) implies
   pgam(b) = pgam(a) implies
   line-int(df, pgam, dgam, a, b) = 0)"))
(dk-peel!)
(define gb-cr-ho (dk-pick (dk-head? 'HOLOMORPHIC-ON) "holomorphic-on(u, f)"))
(define gb-cr-u (cadr gb-cr-ho))
(define gb-cr-f (caddr gb-cr-ho))
(define gb-cr-li (cadr (dk-goal)))
(define gb-cr-pg (list-ref gb-cr-li 2))
(define gb-cr-dg (list-ref gb-cr-li 3))
(define gb-cr-a (list-ref gb-cr-li 4))
(define gb-cr-b (list-ref gb-cr-li 5))
(define gb-cr-eq (dk-cite! 'line-int-of-derivative gb-cr-u gb-cr-f (list-ref gb-cr-li 1)
                           gb-cr-pg gb-cr-dg gb-cr-a gb-cr-b))
(subst gb-cr-eq)
(subst (list '= (list gb-cr-pg gb-cr-b) (list gb-cr-pg gb-cr-a)))
;; f(pgam(a)) in CC: a in [a, b], pgam(a) in the trace, the trace inside u
(define gb-cr-pa (list gb-cr-pg gb-cr-a))
(define gb-cr-ip (dk-fact! 'is-road-is-path gb-cr-pg gb-cr-dg gb-cr-a gb-cr-b))
(dk-split-all! (list (dk-fact! 'is-path-endpoints gb-cr-pg gb-cr-a gb-cr-b)))
(fact 'is-path-in-fun gb-cr-pg gb-cr-a gb-cr-b)
(define gb-cr-cc (list 'CCINT gb-cr-a gb-cr-b))
(dk-have! (list 'IN gb-cr-a gb-cr-cc)
  (lambda ()
    (mac 'ccint-membership)
    (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (dk-ineq! (list '< gb-cr-a gb-cr-b))))))) 
(define gb-cr-tr (list 'TRACE gb-cr-pg gb-cr-a gb-cr-b))
(dk-have! (list 'IN gb-cr-pa gb-cr-tr)
  (lambda ()
    (mac 'trace-unfold)
    (mac 'image-membership-iff)
    (ew gb-cr-a)
    (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (rfl))))))
(fact 'subset-mem-fwd gb-cr-tr gb-cr-u gb-cr-pa)
(fact 'holomorphic-on-in-fun gb-cr-u gb-cr-f)
(fact 'fun-apply-type-c gb-cr-f gb-cr-u 'CC gb-cr-pa)
(crs)
(qed 'line-int-closed-road-of-derivative)

;;; ======================================================================
;;; (2b) affine-has-primitive-cc: the polynomial of (65) has a primitive.
;;; F(z) == c0 z + c1 ((z - a0)(z - a0)) recip(2) is holomorphic on CC with
;;; F'(z) = c0 + c1 (z - a0).  F is given by its values (F in FUN(CC, CC)), the
;;; form in which Cor 3.3 consumes it.  Route: cc-diff-on-quadratic with
;;; M = |c1 recip(2)|: F(x) - F(a) - (x - a) F'(a) = (c1 recip(2)) (x - a)^2.
;;; ======================================================================
(define gb-ap-val
  '(FORALL gbz_ (IMPLIES (IN gbz_ CC)
     (== (gbf_ gbz_) (+ (* gbp_ gbz_) (* (* gbq_ (* (- gbz_ gbw_) (- gbz_ gbw_))) (recip 2)))))))
(sp (make-wff
  (list 'FORALL 'gbp_ (list 'IMPLIES '(IN gbp_ CC)
  (list 'FORALL 'gbq_ (list 'IMPLIES '(IN gbq_ CC)
  (list 'FORALL 'gbw_ (list 'IMPLIES '(IN gbw_ CC)
  (list 'FORALL 'gbf_ (list 'IMPLIES '(IN gbf_ (FUN CC CC))
    (list 'IMPLIES gb-ap-val
      (list 'AND '(HOLOMORPHIC-ON CC gbf_)
        '(FORALL gbz_ (IMPLIES (IN gbz_ CC)
           (IS-DIFF-ON CC-NORMED-FIELD CC gbf_ gbz_ (+ gbp_ (* gbq_ (- gbz_ gbw_))))))))))))))))))
(dk-peel!)
(define gb-ap-vh (dk-pick (lambda (f) (and (pair? f) (eq? (car f) 'FORALL) (dk-contains? f '==))) "F's values"))
(define gb-ap-fun (dk-pick (lambda (f) (and (gb-op? f 'IN 3) (gb-op? (caddr f) 'FUN 3) (eq? (cadr (caddr f)) 'CC)))
                           "F in FUN(CC, CC)"))
(define gb-f (cadr gb-ap-fun))
;; the parameters, read off the value equation
(define gb-ap-e (caddr (caddr (caddr gb-ap-vh))))          ; (+ (* p z) (* (* q ...) (recip 2)))
(define gb-p (cadr (cadr gb-ap-e)))
(define gb-q (cadr (cadr (caddr gb-ap-e))))
(define gb-w (caddr (cadr (caddr (cadr (caddr gb-ap-e))))))
(define gb-h '(recip 2))
(gb-cc-typ! gb-h)
(fact 'cc-is-metric-space)
(dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
(fact 'carrier-is-open 'CC-MS)
(dk-have! '(IS-OPEN CC-MS CC) (lambda () (subst '(= CC (PTS CC-MS))) (ass)))
(define gb-ap-oiff (dk-fact! 'cc-ms-open-iff 'CC))
(dk-have! '(IS-OPEN (NF-METRIC-SPACE CC-NORMED-FIELD) CC)
  (lambda () (dk-only! gb-ap-oiff '(IS-OPEN CC-MS CC)) (prop)))
;; the generalised identity: F(x) - F(a) - (x - a) L = (q h)(x - a)^2 + (q (x - a))(a - w)(2 h - 1)
(define (gb-ap-expr z)
  (list '+ (list '* 'gbvp_ z) (list '* (list '* 'gbvq_ (list '* (list '- z 'gbvw_) (list '- z 'gbvw_))) 'gbvh_)))
(define gb-ap-gen
  (list 'FORALL 'gbvp_ (list 'IMPLIES '(IN gbvp_ CC)
  (list 'FORALL 'gbvq_ (list 'IMPLIES '(IN gbvq_ CC)
  (list 'FORALL 'gbvw_ (list 'IMPLIES '(IN gbvw_ CC)
  (list 'FORALL 'gbvh_ (list 'IMPLIES '(IN gbvh_ CC)
  (list 'FORALL 'gbvx_ (list 'IMPLIES '(IN gbvx_ CC)
  (list 'FORALL 'gbva_ (list 'IMPLIES '(IN gbva_ CC)
    (list '= (list '- (list '- (gb-ap-expr 'gbvx_) (gb-ap-expr 'gbva_))
                      (list '* '(- gbvx_ gbva_) '(+ gbvp_ (* gbvq_ (- gbva_ gbvw_)))))
             '(+ (* (* gbvq_ gbvh_) (* (- gbvx_ gbva_) (- gbvx_ gbva_)))
                 (* (* (* gbvq_ (- gbvx_ gbva_)) (- gbva_ gbvw_)) (- (* 2 gbvh_) 1)))))))))))))))))
(dk-have! gb-ap-gen (lambda () (dk-peel!) (crs)))
(define gb-ap-zero
  '(FORALL gbvu_ (IMPLIES (IN gbvu_ CC) (FORALL gbvv_ (IMPLIES (IN gbvv_ CC)
     (= (+ gbvu_ (* gbvv_ (- 1 1))) gbvu_))))))
(dk-have! gb-ap-zero (lambda () (dk-peel!) (crs)))
(gb-cc-typ! 2)
(gb-and! '(IN 2 CC) '(NOT (= 2 0)))
(define gb-ap-two (dk-cite! 'cc-recip-inverse 2))          ; 2 * recip(2) = 1
;; the derivative at every point
(define gb-ap-d
  (list 'FORALL 'gbz_ (list 'IMPLIES '(IN gbz_ CC)
    (list 'IS-DIFF-ON 'CC-NORMED-FIELD 'CC gb-f 'gbz_ (list '+ gb-p (list '* gb-q (list '- 'gbz_ gb-w)))))))
(dk-have! gb-ap-d
  (lambda ()
    (let* ((a (dk-di-var!))
           (L (list '+ gb-p (list '* gb-q (list '- a gb-w))))
           (M (list 'magnitude (list '* gb-q gb-h))))
      (gb-cc-typ! L)
      (gb-cc-typ! (list '* gb-q gb-h))
      (fact 'cc-magnitude-closed (list '* gb-q gb-h))
      (fact 'cc-magnitude-nonneg (list '* gb-q gb-h))
      (dk-have! (list 'FORALL 'cpdx_ (list 'IMPLIES '(IN cpdx_ CC)
                  (list '<= (list 'magnitude (list '- (list '- (list gb-f 'cpdx_) (list gb-f a))
                                                   (list '* (list '- 'cpdx_ a) L)))
                        (list '* M (list '* (list 'magnitude (list '- 'cpdx_ a))
                                            (list 'magnitude (list '- 'cpdx_ a)))))))
        (lambda ()
          (let* ((x (dk-di-var!))
                 (d (list '- x a))
                 (Ex (dk-apply! gb-ap-vh x))
                 (Ea (dk-apply! gb-ap-vh a)))
            (subst Ex)
            (subst Ea)
            (let ((id (dk-apply! (dk-ctx-form gb-ap-gen) gb-p gb-q gb-w gb-h x a)))
              (subst id))
            (subst gb-ap-two)
            (let* ((u (list '* (list '* gb-q gb-h) (list '* d d)))
                   (v (list '* (list '* gb-q d) (list '- a gb-w))))
              (gb-cc-typ! u) (gb-cc-typ! v)
              (subst (dk-apply! (dk-ctx-form gb-ap-zero) u v))
              (gb-cc-typ! d)
              (gb-and! (list 'IN (list '* gb-q gb-h) 'CC) (list 'IN (list '* d d) 'CC))
              (subst (dk-cite! 'cc-magnitude-mul (list '* gb-q gb-h) (list '* d d)))
              (gb-and! (list 'IN d 'CC) (list 'IN d 'CC))
              (subst (dk-cite! 'cc-magnitude-mul d d))
              (fact 'cc-magnitude-closed d)
              (let ((t (cadr (dk-goal))))
                (dk-real! t)
                (dk-cite! 'rr-leq-reflexive t)
                (ass))))))
      (fact 'cc-diff-on-quadratic 'CC gb-f a L M)
      (ass))))
(dk-conj-close!
  (lambda ()
    (if (dk-asm? (dk-goal))
        (ass)
        (begin
          (mac 'HOLOMORPHIC-ON)
          (dk-conj-close!
            (lambda ()
              (if (not (dk-head-is? (dk-goal) 'FORALL))
                  (ass)
                  (let ((a (dk-di-var!)))
                    (dk-apply! (dk-ctx-form gb-ap-d) a)
                    (ew (list '+ gb-p (list '* gb-q (list '- a gb-w))))
                    (ass)))))))))
(qed 'affine-has-primitive-cc)

;;; ======================================================================
;;; (2c) affine-closed-road-integral: the integral of z |-> c0 + c1 (z - a0)
;;; over a closed road is 0 (the notes' (65) step "applying Corollary 3.3 to
;;; the polynomial f(a) + f'(a)(z - a)").  g given by its values on CC.
;;; ======================================================================
(sp (make-wff
  '(FORALL gbp_ (IMPLIES (IN gbp_ CC)
    (FORALL gbq_ (IMPLIES (IN gbq_ CC)
    (FORALL gbw_ (IMPLIES (IN gbw_ CC)
    (FORALL gbg_ (IMPLIES (IN gbg_ (FUN CC CC))
     (IMPLIES (FORALL gbz_ (IMPLIES (IN gbz_ CC) (== (gbg_ gbz_) (+ gbp_ (* gbq_ (- gbz_ gbw_))))))
      (FORALL pgam (FORALL dgam (FORALL a (FORALL b
       (IMPLIES (IS-ROAD pgam dgam a b)
        (IMPLIES (= (pgam b) (pgam a))
         (= (LINE-INT gbg_ pgam dgam a b) 0))))))))))))))))))
(dk-peel!)
(define gb-cl-vh (dk-pick (lambda (f) (and (pair? f) (eq? (car f) 'FORALL) (dk-contains? f '==))) "g's values"))
(define gb-cl-e (caddr (caddr (caddr gb-cl-vh))))                 ; (+ p (* q (- z w)))
(define gb-cl-p (cadr gb-cl-e))
(define gb-cl-q (cadr (caddr gb-cl-e)))
(define gb-cl-w (caddr (caddr (caddr gb-cl-e))))
(define gb-cl-g (car (cadr (caddr (caddr gb-cl-vh)))))              ; the g of (g z)
(define gb-cl-li (cadr (dk-goal)))
(define gb-cl-pg (list-ref gb-cl-li 2))
(define gb-cl-dg (list-ref gb-cl-li 3))
(define gb-cl-a (list-ref gb-cl-li 4))
(define gb-cl-b (list-ref gb-cl-li 5))
(define (gb-cl-val z)
  (list '+ (list '* gb-cl-p z)
           (list '* (list '* gb-cl-q (list '* (list '- z gb-cl-w) (list '- z gb-cl-w))) '(recip 2))))
(define gb-cl-F (list 'VNB-LAMBDA 'gbvz_ 'CC (gb-cl-val 'gbvz_)))
(gb-cc-typ! '(recip 2))
(dk-have! (list 'IN gb-cl-F '(FUN CC CC))
  (lambda ()
    (dk-lam-type! (lambda () (let ((z (dk-di-var!))) (gb-cc-typ! (gb-cl-val z)) (ass))))))
(define gb-cl-fv
  (list 'FORALL 'gbz_ (list 'IMPLIES '(IN gbz_ CC) (list '== (list gb-cl-F 'gbz_) (gb-cl-val 'gbz_)))))
(dk-have! gb-cl-fv
  (lambda ()
    (let ((z (dk-di-var!)))
      (gb-cc-typ! (gb-cl-val z))
      (if (not (dk-lam-b!)) (qrfl)))))
(define gb-cl-ap (dk-cite! 'affine-has-primitive-cc gb-cl-p gb-cl-q gb-cl-w gb-cl-F))
(dk-split-all! (list gb-cl-ap))
(define gb-cl-dd (dk-pick (lambda (f) (and (pair? f) (eq? (car f) 'FORALL) (dk-contains? f 'IS-DIFF-ON))) "F' = g"))
(define gb-cl-dg-h
  (list 'FORALL 'hbz_ (list 'IMPLIES '(IN hbz_ CC)
    (list 'IS-DIFF-ON 'CC-NORMED-FIELD 'CC gb-cl-F 'hbz_ (list gb-cl-g 'hbz_)))))
(dk-have! gb-cl-dg-h
  (lambda ()
    (let ((z (dk-di-var!)))
      (dk-apply! gb-cl-dd z)
      (subst (dk-apply! gb-cl-vh z))
      (ass))))
(fact 'is-road-is-path gb-cl-pg gb-cl-dg gb-cl-a gb-cl-b)
(fact 'is-path-in-fun gb-cl-pg gb-cl-a gb-cl-b)
(fact 'trace-subset-cc gb-cl-pg gb-cl-a gb-cl-b)
(dk-cite! 'line-int-closed-road-of-derivative 'CC gb-cl-F gb-cl-g gb-cl-pg gb-cl-dg gb-cl-a gb-cl-b)
(ass)
(qed 'affine-closed-road-integral)

;;; ======================================================================
;;; (4) caratheodory-remainder-small: the notes' (65).  From IS-DIFF-ON over
;;; CC with derivative L: for every eps > 0 there is r > 0 with
;;; |f(z) - (f(a) + L (z - a))| <= eps |z - a| for z in U, |z - a| < r.
;;; The Caratheodory factor phi is read off the definition (dk-skolem! on its
;;; FORSOME); its continuity at a gives r; f(z) - f(a) - L(z - a) = (phi(z) - L)(z - a).
;;; ======================================================================
(define gb-nfm '(NF-METRIC-SPACE CC-NORMED-FIELD))
(sp (make-wff
  '(FORALL gbs_ (FORALL gbf_ (FORALL gba_ (FORALL gbl_
    (IMPLIES (IS-DIFF-ON CC-NORMED-FIELD gbs_ gbf_ gba_ gbl_)
     (FORALL gbe_ (IMPLIES (POS-RR gbe_)
      (FORSOME gbr_ (AND (POS-RR gbr_)
       (FORALL gbz_ (IMPLIES (IN gbz_ gbs_)
        (IMPLIES (< (magnitude (- gbz_ gba_)) gbr_)
         (<= (magnitude (- (gbf_ gbz_) (+ (gbf_ gba_) (* gbl_ (- gbz_ gba_)))))
             (* gbe_ (magnitude (- gbz_ gba_))))))))))))))))))
(dk-peel!)
(define gb-cr-d (dk-pick (dk-head? 'IS-DIFF-ON) "the derivative"))
(define gb-s (list-ref gb-cr-d 2))
(define gb-cf (list-ref gb-cr-d 3))
(define gb-a (list-ref gb-cr-d 4))
(define gb-l (list-ref gb-cr-d 5))
(define gb-eps (cadr (dk-pick (dk-head? 'POS-RR) "eps")))
(define gb-sub (list 'SUBSPACE-MS gb-nfm gb-s))
(fact 'rr-pos-rr-in-rr gb-eps)
(fact 'rr-lt-of-pos-rr gb-eps)
(fact 'cc-is-normed-field)
(fact 'nf-cc-is-metric-space)
(fact 'nf-metric-carrier 'CC-NORMED-FIELD)
(fact 'cc-nf-carr)
(fact 'cc-is-metric-space)
(dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
(dk-have! (list '== (list 'PTS gb-nfm) 'CC)
  (lambda () (subst (list '== (list 'PTS gb-nfm) '(CARR CC-NORMED-FIELD))) (ass)))
(mac-h 'IS-DIFF-ON gb-cr-d)
(dk-split-all!)
(define gb-phi
  (dk-skolem! (dk-pick (dk-head? 'FORSOME) "the Caratheodory factor")))
(dk-have! (list 'SUBSET gb-s (list 'PTS gb-nfm))
  (lambda () (mac-h 'is-open (list 'IS-OPEN gb-nfm gb-s)) (dk-split-all!) (ass)))
(dk-have! (list 'SUBSET gb-s 'CC) (lambda () (subst (list '== 'CC (list 'PTS gb-nfm))) (ass)))
(fact 'subspace-pts gb-nfm gb-s)
(define (gb-cr-cc! t) (fact 'subset-mem-fwd gb-s 'CC t))
(dk-have! (list 'IN gb-cf (list 'FUN gb-s 'CC)) (lambda () (subst '(= CC (CARR CC-NORMED-FIELD))) (ass)))
(dk-have! (list 'IN gb-phi (list 'FUN gb-s 'CC)) (lambda () (subst '(= CC (CARR CC-NORMED-FIELD))) (ass)))
(dk-have! (list 'IN gb-l 'CC) (lambda () (subst '(= CC (CARR CC-NORMED-FIELD))) (ass)))
(gb-cr-cc! gb-a)
(fact 'fun-apply-type-c gb-cf gb-s 'CC gb-a)
;; continuity of phi at a, at eps
(define gb-cont (dk-pick (dk-head? 'IS-CONTINUOUS-AT) "phi continuous at a"))
(mac-h 'is-continuous-at gb-cont)
(dk-split-all!)
(define gb-ce (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f 'POS-RR) (dk-contains? f 'DIST)))
                       "the eps-delta clause"))
(define gb-del (dk-skolem! (dk-apply! gb-ce gb-eps)))
(define gb-dcl (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f 'DIST))) "the delta clause"))
(define gb-pa (dk-pick (lambda (f) (and (gb-op? f '= 3) (equal? (cadr f) (list gb-phi gb-a)))) "phi(a) = L"))
(define gb-fac (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f '(MUL CC-NORMED-FIELD)))) "the factorisation"))
(ew gb-del)
(dk-conj-close!
  (lambda ()
    (if (not (dk-head-is? (dk-goal) 'FORALL))
        (ass)
        (let* ((lk (dk-peel!))
               (z (cadr (car (filter (dk-head? 'IN) lk))))
               (d (list '- z gb-a))
               (dz (list '- gb-a z))
               (md (list 'magnitude d))
               (mdz (list 'magnitude dz))
               (pz (list gb-phi z))
               (fz (list gb-cf z))
               (fa (list gb-cf gb-a))
               (fd (list '- fz fa)))
          (gb-cr-cc! z)
          (fact 'fun-apply-type-c gb-cf gb-s 'CC z)
          (fact 'fun-apply-type-c gb-phi gb-s 'CC z)
          (for-each gb-cc-typ! (list d dz fd pz (list '- pz gb-l) (list '- gb-l pz)))
          (fact 'cc-magnitude-closed d)
          (fact 'cc-magnitude-closed dz)
          (fact 'cc-magnitude-nonneg d)
          (fact 'cc-magnitude-sub-sym z gb-a)
          (fact 'rr-pos-rr-in-rr gb-del)
          ;; |a - z| <= delta, as the subspace distance
          (dk-have! (list 'IN z (list 'PTS gb-sub)) (lambda () (subst (list '== (list 'PTS gb-sub) gb-s)) (ass)))
          (dk-have! (list 'IN gb-a (list 'PTS gb-sub)) (lambda () (subst (list '== (list 'PTS gb-sub) gb-s)) (ass)))
          (dk-have! (list 'IN gb-a '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
          (dk-have! (list 'IN z '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
          (fact 'subspace-dist gb-nfm gb-s gb-a z)
          (fact 'nf-cc-agree-dist gb-a z)
          (fact 'cc-ms-dist gb-a z)
          (dk-have! (list '<= (list (list 'DIST gb-sub) gb-a z) gb-del)
            (lambda ()
              (subst (list '== (list (list 'DIST gb-sub) gb-a z) (list (list 'DIST gb-nfm) gb-a z)))
              (subst (list '== (list (list 'DIST gb-nfm) gb-a z) (list '(DIST CC-MS) gb-a z)))
              (subst (list '== (list '(DIST CC-MS) gb-a z) mdz))
              (subst (list '= mdz md))
              (dk-ineq! (list '< md gb-del))))
          ;; |L - phi(z)| <= eps
          (let* ((pa (list gb-phi gb-a))
                 (mlp (list 'magnitude (list '- gb-l pz))))
            (fact 'fun-apply-type-c gb-phi gb-s 'CC gb-a)
            (dk-apply! gb-dcl z)
            (dk-have! (list 'IN pa '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
            (dk-have! (list 'IN pz '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
            (fact 'nf-cc-agree-dist pa pz)
            (fact 'cc-ms-dist pa pz)
            (dk-have! (list '<= mlp gb-eps)
              (lambda ()
                (subst (list '= gb-l pa))
                (subst (list '= (list 'magnitude (list '- pa pz)) (list '(DIST CC-MS) pa pz)))
                (subst (list '= (list '(DIST CC-MS) pa pz) (list (list 'DIST gb-nfm) pa pz)))
                (ass)))
            ;; f(z) - f(a) = phi(z) (z - a), from the factorisation over the field
            (dk-apply! gb-fac z)
            (dk-have! (list '= fd (list '* pz d))
              (lambda ()
                (fact 'cc-nf-sub fz fa)
                (fact 'cc-nf-sub z gb-a)
                (gb-and! (list 'IN pz 'CC) (list 'IN d 'CC))
                (fact 'cc-nf-mul-apply pz d)
                (subst (list '= (list '* pz d) (list '(MUL CC-NORMED-FIELD) pz d)))
                (subst (list '= d (list '(ADD CC-NORMED-FIELD) z (list '(NEG CC-NORMED-FIELD) gb-a))))
                (subst (list '= fd (list '(ADD CC-NORMED-FIELD) fz (list '(NEG CC-NORMED-FIELD) fa))))
                (ass)))
            ;; the remainder
            (let* ((ld (list '* gb-l d))
                   (e1 (list '= (list '- fz (list '+ fa ld)) (list '- fd ld)))
                   (e2 (list '= (list '- (list '* pz d) ld) (list '* (list '- pz gb-l) d))))
              (dk-have! e1 (lambda () (crs)))
              (subst e1)
              (subst (list '= fd (list '* pz d)))
              (dk-have! e2 (lambda () (crs)))
              (subst e2)
              (gb-and! (list 'IN (list '- pz gb-l) 'CC) (list 'IN d 'CC))
              (subst (dk-cite! 'cc-magnitude-mul (list '- pz gb-l) d))
              (subst (dk-cite! 'cc-magnitude-sub-sym pz gb-l))
              (fact 'cc-magnitude-closed (list '- gb-l pz))
              (gb-and! (list '<= 0 md) (list '<= mlp gb-eps))
              (let ((sc (dk-cite! 'rr-le-scale-nonneg md mlp gb-eps))
                    (c1 (list '= (list '* mlp md) (list '* md mlp)))
                    (c2 (list '= (list '* gb-eps md) (list '* md gb-eps))))
                (dk-real! (list '* mlp md)) (dk-real! (list '* md mlp))
                (dk-real! (list '* gb-eps md)) (dk-real! (list '* md gb-eps))
                (dk-have! c1 (lambda () (crs)))
                (dk-have! c2 (lambda () (crs)))
                (dk-ineq! sc c1 c2))))))))
(qed 'caratheodory-remainder-small)

;;; ======================================================================
;;; (1a) nn-succ-le-power-two: k + 1 <= 2^k  (recip(2^k) <= recip(k + 1) is
;;; what makes the dyadic tail small)
;;; ======================================================================
(sp (make-wff '(FORALL gbk_ (IMPLIES (IN gbk_ NN) (<= (+ gbk_ 1) (power 2 gbk_))))))
(define gb-pl-br (use-induction))
(dk-focus! (cdr (assq 'base gb-pl-br)))
(dk-have! '(IN 2 CC) (lambda () (arith)))
(fact 'power-zero 2)
(subst '(= (power 2 0) 1))
(arith)
(dk-focus! (cdr (assq 'step gb-pl-br)))
(let ((k (cdr (assq 'var gb-pl-br)))
      (ih (cdr (assq 'ih gb-pl-br))))
  (dk-have! '(IN 2 CC) (lambda () (arith)))
  (gb-and! '(IN 2 CC) (list 'IN k 'NN))
  (subst (dk-cite! 'power-succ 2 k))
  (subst (dk-cite! 'nn-succ-plus-one k))
  (fact 'nn-in-rr k)
  (fact 'nn-zero-le k)
  (dk-type! (list 'power 2 k) 'RR)
  (dk-ineq! ih (list '<= 0 k)))
(qed 'nn-succ-le-power-two)

;;; ======================================================================
;;; (1b) cc-telescoping-limit-bound: a sequence whose steps are bounded by
;;; C 2^-k converges, and |s(n) - L| <= 2 C 2^-n.  Route: the tail bound
;;; |s(m) - s(n)| <= D(n) - D(m) for n <= m (D(k) = 2 C 2^-k; induction on m),
;;; Cauchy, cc-complete; the bound by rr-le-of-le-add-all-pos at s(n + N).
;;; ======================================================================
(sp (make-wff
  '(FORALL gbs_ (IMPLIES (IN gbs_ (FUN NN CC))
    (FORALL gbc_ (IMPLIES (IN gbc_ RR) (IMPLIES (<= 0 gbc_)
     (IMPLIES (FORALL gbk_ (IMPLIES (IN gbk_ NN)
                (<= (magnitude (- (gbs_ (succ gbk_)) (gbs_ gbk_))) (* gbc_ (recip (power 2 gbk_))))))
      (FORSOME gbv_ (AND (IN gbv_ CC) (AND (CONVERGES-TO CC-MS gbs_ gbv_)
        (FORALL gbn_ (IMPLIES (IN gbn_ NN)
          (<= (magnitude (- (gbs_ gbn_) gbv_)) (* (* 2 gbc_) (recip (power 2 gbn_)))))))))))))))))
(dk-peel!)
(define gb-t-s (cadr (dk-pick (lambda (f) (and (gb-op? f 'IN 3) (equal? (caddr f) '(FUN NN CC)))) "s")))
(define gb-t-c (caddr (dk-pick (lambda (f) (and (gb-op? f '<= 3) (eqv? (cadr f) 0))) "0 <= C")))
(define gb-t-h (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f 'magnitude))) "the step bound"))
(define (gb-R k) (list 'recip (list 'power 2 k)))
(define (gb-D k) (list '* (list '* 2 gb-t-c) (gb-R k)))
(define (gb-sv k) (list gb-t-s k))
(define (gb-mag x) (list 'magnitude x))
(fact 'rr-zero-in)
(fact 'cc-is-metric-space)
(dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
(dk-have! '(IN 2 CC) (lambda () (arith)))
(dk-real! (list '* 2 gb-t-c))
(define (gb-nn! k)
  (let ((typ (list 'IN k 'NN)))
    (cond ((dk-asm? typ) typ)
          ((eqv? k 0) (fact 'nn-zero-in) typ)
          ((gb-op? k 'succ 2) (gb-nn! (cadr k)) (fact 'nn-succ-closed (cadr k)) typ)
          ((gb-op? k '+ 3) (gb-nn! (cadr k)) (gb-nn! (caddr k))
           (gb-and! (list 'IN (cadr k) 'NN) (list 'IN (caddr k) 'NN))
           (fact 'nn-add-closed (cadr k) (caddr k)) typ)
          (#t (error "gb-nn!: cannot type" (expression->string k))))))
(define (gb-sv! k)
  (gb-nn! k)
  (if (not (dk-asm? (list 'IN (gb-sv k) 'CC)))
      (fact 'fun-apply-type-c gb-t-s 'NN 'CC k)))
;; 0 <= D(k)
(define (gb-dnn! k)
  (let* ((r (gb-R k)) (cr (list '* gb-t-c r)))
    (dk-real! cr)
    (gb-and! (list '<= 0 gb-t-c) (list '<= 0 r))
    (let ((sc (dk-cite! 'rr-le-scale-nonneg gb-t-c 0 r)))
      (dk-real! (list '* gb-t-c 0))
      (dk-have! (list '= (list '* gb-t-c 0) 0) (lambda () (crs)))
      (dk-have! (list '= (gb-D k) (list '* 2 cr)) (lambda () (dk-crs-opaque!)))
      (dk-have! (list '<= 0 (gb-D k))
        (lambda () (dk-ineq! sc (list '= (list '* gb-t-c 0) 0) (list '= (gb-D k) (list '* 2 cr))))))))
;; the facts about R(k) = recip(2^k), D(k)
(define (gb-r! k)
  (let* ((p (list 'power 2 k)) (r (gb-R k)))
    (gb-nn! k)
    (if (not (dk-asm? (list '< 0 r)))
        (begin
          (dk-type! p 'RR)
          (fact 'power-two-pos k)
          (fact 'rr-pos-ne-zero p)
          (gb-and! (list 'IN p 'RR) (list 'NOT (list '= p 0)))
          (fact 'rr-recip-closed p)
          (fact 'rr-recip-pos p)
          (fact 'rr-lt-implies-le 0 r)
          (dk-real! (gb-D k))
          (gb-dnn! k)))))
;; R(m) = 2 R(succ m)
(define (gb-half! m)
  (let ((f (list '= (gb-R m) (list '* 2 (gb-R (list 'succ m))))))
    (dk-have! f
      (lambda ()
        (fact 'recip-power-two-halves m)
        (gb-and! '(IN 2 CC) (list 'IN m 'NN))
        (subst (dk-cite! 'power-succ 2 m))
        (ass)))
    f))
;; |x - z| <= |x - y| + |y - z| for x, y, z in CC
(define (gb-tri! x y z)
  (let* ((a (list '- x y)) (b (list '- y z)) (xz (list '- x z))
         (f (list '<= (gb-mag xz) (list '+ (gb-mag a) (gb-mag b)))))
    (for-each gb-cc-typ! (list a b xz))
    (for-each (lambda (t) (fact 'cc-magnitude-closed t)) (list a b xz))
    (dk-have! f
      (lambda ()
        (dk-have! (list '= xz (list '+ a b)) (lambda () (crs)))
        (subst (list '= xz (list '+ a b)))
        (gb-and! (list 'IN a 'CC) (list 'IN b 'CC))
        (dk-cite! 'cc-magnitude-triangle a b)
        (ass)))
    f))
;; the goal |s(k) - s(k)| <= D(k) - D(k)
(define (gb-zero-close! k)
  (let ((x (gb-sv k)))
    (gb-sv! k)
    (dk-have! (list '= (list '- x x) 0) (lambda () (crs)))
    (subst (list '= (list '- x x) 0))
    (fact 'cc-magnitude-zero)
    (subst '(= (magnitude 0) 0))
    (gb-r! k)
    (dk-ineq!)))

;;; ---- the tail bound, by induction on m
(define gb-T
  (list 'FORALL 'gbm_ (list 'IMPLIES '(IN gbm_ NN)
    (list 'FORALL 'gbj_ (list 'IMPLIES '(IN gbj_ NN) (list 'IMPLIES '(<= gbj_ gbm_)
      (list '<= (gb-mag (list '- (gb-sv 'gbm_) (gb-sv 'gbj_))) (list '- (gb-D 'gbj_) (gb-D 'gbm_)))))))))
(dk-have! gb-T
  (lambda ()
    (let ((br (use-induction)))
      (dk-focus! (cdr (assq 'base br)))
      (let* ((lk (dk-peel!))
             (j (cadr (car (filter (lambda (f) (gb-op? f 'IN 3)) lk)))))
        (subst (dk-cite! 'nn-le-zero-is-zero j))
        (gb-zero-close! 0))
      (dk-focus! (cdr (assq 'step br)))
      (let* ((m (cdr (assq 'var br)))
             (ih (cdr (assq 'ih br)))
             (sm (list 'succ m))
             (lk (dk-peel!))
             (j (cadr (car (filter (lambda (f) (gb-op? f 'IN 3)) lk))))
             (orf (begin (gb-nn! sm) (dk-cite! 'nn-le-succ-cases m j))))
        (for-each
          (lambda (leaf)
            (dk-focus! leaf)
            (if (dk-asm? (list '= j sm))
                (begin (subst (list '= j sm)) (gb-zero-close! sm))
                (let* ((ihj (dk-apply! ih j))
                       (hm (dk-apply! gb-t-h m))
                       (tri (begin (gb-sv! sm) (gb-sv! m) (gb-sv! j)
                                   (gb-tri! (gb-sv sm) (gb-sv m) (gb-sv j))))
                       (p (list '* gb-t-c (gb-R m)))
                       (q (list '* gb-t-c (gb-R sm))))
                  (gb-r! m) (gb-r! sm) (gb-r! j)
                  (let* ((hf (gb-half! m))
                         (epq (list '= p (list '* 2 q)))
                         (ex (list '= (gb-D m) (list '* 2 p)))
                         (ey (list '= (gb-D sm) (list '* 2 q))))
                    (dk-have! epq (lambda () (subst hf) (dk-crs-opaque!)))
                    (dk-have! ex (lambda () (dk-crs-opaque!)))
                    (dk-have! ey (lambda () (dk-crs-opaque!)))
                    (dk-ineq! tri hm ihj epq ex ey)))))
          (dk-opened (lambda () (ai orf))))))))

;;; ---- s is Cauchy
(define (gb-pos! t)
  (fact 'rr-lt-implies-le 0 t)
  (fact 'rr-pos-ne-zero t)
  (fact 'neq-sym t 0)
  (dk-have! (list 'POS-RR t) (lambda () (mac 'pos-rr) (from-context!))))
(define (gb-cauchy-eps!)
  (let* ((lk (dk-peel!))
         (eps (cadr (car (filter (dk-head? 'POS-RR) lk))))
         (m1 (list '+ (list '* 4 gb-t-c) 1))
         (rm1 (list 'recip m1))
         (del (list '* eps rm1)))
    (fact 'rr-pos-rr-in-rr eps)
    (fact 'rr-lt-of-pos-rr eps)
    (dk-real! m1)
    (dk-have! (list '< 0 m1) (lambda () (dk-ineq! (list '<= 0 gb-t-c))))
    (fact 'rr-pos-ne-zero m1)
    (gb-and! (list 'IN m1 'RR) (list 'NOT (list '= m1 0)))
    (fact 'rr-recip-closed m1)
    (fact 'rr-recip-inverse m1)
    (fact 'rr-recip-pos m1)
    (fact 'rr-mul-in-rr eps rm1)
    (fact 'rr-mul-pos eps rm1)
    (gb-pos! del)
    (dk-real! (list '* m1 del))
    (let ((edel (list '= (list '* m1 del) eps))
          (esplit (list '= (list '* m1 del) (list '+ (list '* 4 (list '* gb-t-c del)) del))))
      (dk-real! (list '* gb-t-c del))
      (dk-have! edel
        (lambda ()
          (let ((ex (list '* eps (list '* m1 rm1))))
            (dk-have! (list '= (list '* m1 del) ex) (lambda () (dk-crs-opaque!)))
            (subst (list '= (list '* m1 del) ex))
            (subst (list '= (list '* m1 rm1) 1))
            (crs))))
      (dk-have! esplit (lambda () (dk-crs-opaque!)))
      ;; N with recip(N + 1) < delta, hence R(N) < delta
      (let* ((n (dk-skolem! (dk-cite! 'nn-recip-succ-small del)))
             (n1 (list '+ n 1))
             (rn1 (list 'recip n1)))
        (gb-r! n)
        (fact 'nn-in-rr n)
        (fact 'nn-zero-le n)
        (dk-real! n1)
        (dk-have! (list '< 0 n1) (lambda () (dk-ineq! (list '<= 0 n))))
        (dk-cite! 'nn-succ-le-power-two n)
        (fact 'rr-pos-ne-zero n1)
        (gb-and! (list 'IN n1 'RR) (list 'NOT (list '= n1 0)))
        (fact 'rr-recip-closed n1)
        (let* ((anti (dk-cite! 'rr-recip-antitone n1 (list 'power 2 n)))
               (rlt (list '<= (gb-R n) del))
               (crn (list '* gb-t-c (gb-R n)))
               (cdl (list '* gb-t-c del)))
          (dk-have! rlt (lambda () (dk-ineq! anti (list '< rn1 del))))
          (gb-and! (list '<= 0 gb-t-c) rlt)
          (let ((sc (dk-cite! 'rr-le-scale-nonneg gb-t-c (gb-R n) del))
                (exn (list '= (gb-D n) (list '* 2 crn))))
            (dk-have! exn (lambda () (dk-crs-opaque!)))
            (ew n)
            (dk-conj-close!
              (lambda ()
                (if (not (dk-head-is? (dk-goal) 'FORALL))
                    (ass)
                    (let* ((lk2 (dk-peel!))
                           (ig (dk-split-all!))
                           (g (dk-goal))
                           (x (cadr (cadr (cadr g))))
                           (y (cadr (caddr (cadr g))))
                           (sx (gb-sv x)) (sy (gb-sv y)) (sn (gb-sv n)))
                      (gb-sv! x) (gb-sv! y) (gb-sv! n)
                      (subst (dk-cite! 'cc-ms-dist sx sy))
                      (gb-r! x) (gb-r! y)
                      (let ((ta (dk-apply! (dk-ctx-form gb-T) x n))
                            (tb (dk-apply! (dk-ctx-form gb-T) y n))
                            (tri (gb-tri! sx sn sy))
                            (sym (dk-cite! 'cc-magnitude-sub-sym sn sy)))
                        (gb-cc-typ! (list '- sy sn))
                        (fact 'cc-magnitude-closed (list '- sy sn))
                        (dk-ineq! ta tb tri sym exn sc esplit edel
                                  (list '<= 0 (gb-D x)) (list '<= 0 (gb-D y))
                                  (list '< 0 del)))))))))))))
(dk-have! (list 'IS-CAUCHY-SEQ 'CC-MS gb-t-s)
  (lambda ()
    (mac 'is-cauchy-seq)
    (dk-conj-close!
      (lambda ()
        (let ((g (dk-goal)))
          (cond ((dk-asm? g) (ass))
                ((gb-op? g 'IN 3) (subst '(== (PTS CC-MS) CC)) (ass))
                (#t (gb-cauchy-eps!))))))))

;;; ---- the limit
(fact 'cc-complete)
(mac-h 'is-complete '(IS-COMPLETE CC-MS))
(dk-split-all!)
(define gb-cv (dk-apply! (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f 'IS-CAUCHY-SEQ)))
                                  "complete: Cauchy converges")
                         gb-t-s))
(mac-h 'converges gb-cv)
(define gb-lim (dk-skolem! (dk-pick (dk-head? 'FORSOME) "converges-to some l")))
(define gb-ct (list 'CONVERGES-TO 'CC-MS gb-t-s gb-lim))
(dk-have! (list 'IN gb-lim 'CC)
  (lambda ()
    (mac-h 'converges-to gb-ct)
    (dk-split-all!)
    (subst '(= CC (PTS CC-MS)))
    (ass)))
(ew gb-lim)
(define (gb-bound!)
  (let* ((n (dk-di-var!))
         (sn (gb-sv n))
         (a (gb-mag (list '- sn gb-lim))))
    (gb-sv! n)
    (gb-r! n)
    (gb-cc-typ! (list '- sn gb-lim))
    (fact 'cc-magnitude-closed (list '- sn gb-lim))
    (mac-h 'converges-to gb-ct)
    (dk-split-all!)
    (let* ((ce (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f 'POS-RR))) "the eps clause"))
           (imp (dk-cite! 'rr-le-of-le-add-all-pos a (gb-D n))))
      (dk-have! (cadr imp)
        (lambda ()
          (let* ((lk (dk-peel!))
                 (d (cadr (car (filter (dk-head? 'POS-RR) lk))))
                 (n0 (dk-skolem! (dk-apply! ce d)))
                 (cl (dk-pick (lambda (f) (and (dk-head-is? f 'FORALL) (dk-contains? f 'DIST))) "the N0 clause"))
                 (j (list '+ n n0))
                 (sj (gb-sv j)))
            (fact 'rr-pos-rr-in-rr d)
            (gb-sv! j)
            (gb-r! j)
            (fact 'nn-le-add-left n n0)
            (fact 'nn-le-add-right n0 n)
            (dk-apply! cl j)
            (dk-have! (list 'IN sj '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
            (dk-have! (list 'IN gb-lim '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
            (fact 'cc-ms-dist sj gb-lim)
            (gb-cc-typ! (list '- sj gb-lim))
            (fact 'cc-magnitude-closed (list '- sj gb-lim))
            (let ((dl (list '<= (gb-mag (list '- sj gb-lim)) d))
                  (tj (dk-apply! (dk-ctx-form gb-T) j n))
                  (tri (gb-tri! sn sj gb-lim))
                  (sym (dk-cite! 'cc-magnitude-sub-sym sn sj)))
              (gb-cc-typ! (list '- sj sn))
              (fact 'cc-magnitude-closed (list '- sj sn))
              (dk-have! dl
                (lambda ()
                  (subst (list '= (gb-mag (list '- sj gb-lim)) (list '(DIST CC-MS) sj gb-lim)))
                  (ass)))
              (dk-ineq! dl tj tri sym (list '<= 0 (gb-D j)))))))
      (detach! imp)
      (ass))))
(dk-conj-close!
  (lambda ()
    (if (dk-head-is? (dk-goal) 'FORALL)
        (gb-bound!)
        (ass))))
(qed 'cc-telescoping-limit-bound)
