;;; goursat-exceptional.scm -- CAUCHY-GOURSAT WITH ONE EXCEPTIONAL POINT
;;; (complex-analysis.pdf ch. 3, s. 3.2: Prop 3.6, Cor 3.7, Prop 3.8, Cor 3.9 in the
;;; notes' form: f CONTINUOUS on the open set U and HOLOMORPHIC on U \ {x} for some
;;; x in U).  Batch 35, 2026-09-26.
;;;
;;; THE HYPOTHESES, as the notes state them (the user's decision of 2026-09-26):
;;;     is-open(nf-metric-space(cc-normed-field), u)          U open
;;;     f in fun(u, cc), f continuous at every point of u     f continuous on U
;;;     goxx_ in u                                            x in U
;;;     holomorphic-on(difference(u, singleton(goxx_)),
;;;                    restrict(f, difference(u, singleton(goxx_))))
;;;                                                           f holomorphic on U \ {x}
;;; HOLOMORPHIC-ON(V, g) demands g in FUN(V, CC) EXACTLY (diff-on.scm: a member of
;;; FUN(A, B) is defined exactly on A), so f, a member of FUN(u, CC), cannot be
;;; holomorphic on the smaller V itself: the RESTRICT is the only spelling.  The
;;; openness of V = u \ {x} is a conjunct of that hypothesis (holomorphic-on-open),
;;; so no lemma "an open set minus a point is open" is needed.
;;;
;;; (A) congruence    seg-int-congruence, tri-int-restrict: the segment integral sees
;;;                   only the values on the segment, so f and restrict(f, V) have the
;;;                   same triangle integral on a triangle whose hull lies in V
;;; (B) algebra       tri-int-fan (0), tri-int-collinear (1): segment integrals only
;;; (C) geometry      cc-cross-coords, cc-affinely-independent, conv3-avoids-vertex,
;;;                   conv3-near-vertex, collinear-cases (2); conv3-vertex-shrink and
;;;                   tri-int-vertex-split (the decomposition of the vertex case)
;;; (D) goursat-vertex (3): Rudin 10.13, the vertex at the exceptional point
;;; (E) goursat-triangle-except: PROP 3.6
;;; (F) cc-diff-on-of-eps-bound: differentiability from a little-o bound (the
;;;     converse of caratheodory-remainder-small; cc-diff-on-local-quadratic of
;;;     goursat.scm is the instance delta = min(r, eps / M)), and
;;;     cc-continuous-at-add-const (f + k is continuous where f is)
;;; (G) cauchy-convex-segments-except (COR 3.7), cauchy-convex-primitive-except
;;;     (PROP 3.8, by CONTINUITY of f at the base point only, the notes' proof),
;;;     cauchy-convex-closed-except (COR 3.9)
;;;
;;; NOTHING asserted, no definition.  Helper prefix gox-; binders gox*_ (none used
;;; elsewhere in the tree); u, f, rgy_, pgam, dgam, a, b as in goursat.scm.
;;; LOAD WINDOW: lo = theorem-library/goursat (load.scm:3502; every seg-int / tri-int /
;;; conv3 law, goursat-triangle, seg-int-sum, seg-int-const, seg-int-abs-bound); hi: none.
;;; Tactics of the early kit only (use-cases, use-em, prop, crs, ineq, keep, dk-*).

;;; ======================================================================
;;; local helpers (goursat.scm's gou- helpers, copied: that file is not ours)
;;; ======================================================================
(define (gox-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (gox-hd t) (and (pair? t) (car t)))
(define (gox-and! a b)
  (let ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! (lambda () (ass))))))
    f))

(define (gox-rr! t)
  (let ((typ (list 'IN t 'RR)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'rr-zero-in) typ)
          ((eqv? t 1) (fact 'rr-one-in) typ)
          ((number? t) (dk-have! typ (lambda () (arith))) typ)
          ((gox-op? t '* 3) (gox-rr! (cadr t)) (gox-rr! (caddr t)) (fact 'rr-mul-in-rr (cadr t) (caddr t)) typ)
          ((gox-op? t '+ 3) (gox-rr! (cadr t)) (gox-rr! (caddr t)) (fact 'rr-add-in-rr (cadr t) (caddr t)) typ)
          ((gox-op? t '- 3) (gox-rr! (cadr t)) (gox-rr! (caddr t)) (fact 'rr-sub-in-rr (cadr t) (caddr t)) typ)
          ((gox-op? t '- 2) (gox-rr! (cadr t)) (fact 'rr-neg-closed (cadr t)) typ)
          ((gox-op? t 'magnitude 2) (gox-cc! (cadr t)) (fact 'cc-magnitude-closed (cadr t)) typ)
          ((gox-op? t 'real-part 2) (gox-cc! (cadr t)) (fact 'real-part-in-rr (cadr t)) typ)
          ((gox-op? t 'imag-part 2) (gox-cc! (cadr t)) (fact 'imag-part-in-rr (cadr t)) typ)
          ((gox-op? t 'abs 2) (gox-rr! (cadr t)) (fact 'rr-abs-closed (cadr t)) typ)
          ((gox-op? t 'recip 2)
           (gox-rr! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (if (dk-asm? (list '< 0 (cadr t)))
                   (fact 'rr-pos-ne-zero (cadr t))
                   (dk-have! (list 'NOT (list '= (cadr t) 0)) (lambda () (arith)))))
           (gox-and! (list 'IN (cadr t) 'RR) (list 'NOT (list '= (cadr t) 0)))
           (fact 'rr-recip-closed (cadr t))
           typ)
          (#t (dk-real! t) typ))))

(define (gox-cc! t)
  (let ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((or (number? t) (dk-asm? (list 'IN t 'RR))
               (gox-op? t 'magnitude 2) (gox-op? t 'real-part 2) (gox-op? t 'imag-part 2))
           (gox-rr! t) (fact 'rr-subset-cc t) typ)
          ((gox-op? t '- 3) (gox-cc! (cadr t)) (gox-cc! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((gox-op? t '- 2) (gox-cc! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((gox-op? t '+ 3) (gox-cc! (cadr t)) (gox-cc! (caddr t))
           (gox-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((gox-op? t '* 3) (gox-cc! (cadr t)) (gox-cc! (caddr t))
           (gox-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((gox-op? t 'conjugate 2) (gox-cc! (cadr t)) (fact 'cc-conjugate-closed (cadr t)) typ)
          (#t (error "gox-cc!: cannot type" (expression->string t))))))

;;; the standing hypotheses of the line-integral laws (line-int-exists, verbatim)
(define gox-nfm '(NF-METRIC-SPACE CC-NORMED-FIELD))
(define (gox-cont u f)
  (list 'FORALL 'rgy_ (list 'IMPLIES (list 'IN 'rgy_ u)
    (list 'IS-CONTINUOUS-AT (list 'SUBSPACE-MS gox-nfm u) gox-nfm f 'rgy_))))
(define gox-H (list '(SUBSET u CC) '(IN f (FUN u CC)) (gox-cont 'u 'f)))
(define (gox-imps hyps body)
  (if (null? hyps) body (list 'IMPLIES (car hyps) (gox-imps (cdr hyps) body))))
(define (gox-all-in vars cls body)       ; forall v in cls. ... body
  (if (null? vars) body
      (list 'FORALL (car vars) (list 'IMPLIES (list 'IN (car vars) cls) (gox-all-in (cdr vars) cls body)))))
(define (gox-under-H body)
  (list 'FORALL 'u (list 'FORALL 'f (gox-imps gox-H body))))
(define (gox-segtr a b) (list 'TRACE (list 'SEG-PATH a b) 0 1))

;;; the exceptional hypotheses: u open, f continuous on u, x in u, f holomorphic off x
(define gox-V '(DIFFERENCE u (SINGLETON goxx_)))
(define gox-E
  (list (list 'IS-OPEN gox-nfm 'u) '(IN f (FUN u CC)) (gox-cont 'u 'f) '(IN goxx_ u)
        (list 'HOLOMORPHIC-ON gox-V (list 'RESTRICT 'f gox-V))))
(define (gox-under-E body)
  (list 'FORALL 'u (list 'FORALL 'f (list 'FORALL 'goxx_ (gox-imps gox-E body)))))

;;; in a proof under E: land u subset CC, V open, V subset u, restrict(f, V) in fun(V, CC)
;;; and its continuity on V
(define (gox-E-setup!)
  (fact 'nf-cc-is-metric-space)          ; certifies NF-METRIC-SPACE(CC-NORMED-FIELD) as defined
  (dk-cite! 'cc-open-subset-cc 'u)
  (let ((hol (list 'HOLOMORPHIC-ON gox-V (list 'RESTRICT 'f gox-V))))
    (dk-cite! 'holomorphic-on-open gox-V (list 'RESTRICT 'f gox-V))
    (dk-cite! 'holomorphic-on-in-fun gox-V (list 'RESTRICT 'f gox-V))
    (dk-cite! 'holomorphic-on-continuous gox-V (list 'RESTRICT 'f gox-V))
    (dk-cite! 'cc-open-subset-cc gox-V)
    (dk-have! (list 'SUBSET gox-V 'u)
      (lambda ()
        (let ((z (subset-by-element!)))
          (fact 'difference-membership 'u '(SINGLETON goxx_) z)
          (prop))))))

;;; ======================================================================
;;; (A) THE SEGMENT INTEGRAL SEES ONLY THE VALUES ON THE SEGMENT
;;; ======================================================================
(sp (make-wff (gox-under-H
  (list 'FORALL 'goxw_ (list 'FORALL 'goxg_ (list 'IMPLIES '(IN goxg_ (FUN goxw_ CC))
    (gox-all-in '(goxa_ goxb_) 'CC
      (gox-imps (list (list 'SUBSET (gox-segtr 'goxa_ 'goxb_) 'u) (list 'SUBSET (gox-segtr 'goxa_ 'goxb_) 'goxw_)
                      (list 'FORALL 'goxz_ (list 'IMPLIES (list 'IN 'goxz_ (gox-segtr 'goxa_ 'goxb_))
                                                  '(== (goxg_ goxz_) (f goxz_)))))
        '(= (SEG-INT goxg_ goxa_ goxb_) (SEG-INT f goxa_ goxb_))))))))))
(dk-peel!)
(let* ((a 'goxa_) (b 'goxb_) (w '(- goxb_ goxa_))
       (hyp (dk-pick (lambda (fm) (and (gox-op? fm 'FORALL 3) (dk-contains? fm 'goxg_) (dk-contains? fm '==)))
                     "the values agree on the segment")))
  (gox-cc! w)
  (dk-have! (list '= a a) (lambda () (rfl)))
  (dk-have! (list '= w w) (lambda () (rfl)))
  (let* ((r (dk-cite! 'segment-is-road a w)) (sg (list-ref r 1)) (dsg (list-ref r 2)))
    (fact 'is-road-is-path sg dsg 0 1)
    (fact 'is-path-in-fun sg 0 1)
    (fact 'is-road-dgam-in-fun sg dsg 0 1)
    (dk-cite! 'seg-trace-bridge a b a w)
    (for-each (lambda (s)
                (dk-have! (list 'SUBSET (list 'TRACE sg 0 1) s)
                  (lambda () (subst (list '= (list 'TRACE sg 0 1) (gox-segtr a b))) (ass))))
              '(u goxw_))
    (subst (dk-cite! 'seg-int-bridge 'goxg_ a b a w))
    (subst (dk-cite! 'seg-int-bridge 'f a b a w))
    (subst (dk-cite! 'line-int-unfold 'goxg_ sg dsg 0 1))
    (subst (dk-cite! 'line-int-unfold 'f sg dsg 0 1))
    (let* ((g (dk-goal))
           (psi (cadr (cadr g)))
           (phi (cadr (caddr g)))
           (ex (dk-cite! 'line-int-exists 'u 'f sg dsg 0 1))
           (p1 (dk-skolem! ex))
           (p2 (dk-skolem! (dk-pick (lambda (fm) (and (gox-op? fm 'FORSOME 3) (dk-contains? fm p1))) "the second primitive"))))
      (fact 'rr-zero-in)
      (fact 'rr-one-in)
      (dk-cite! 'line-int-integrand-in-fun 0 1 sg dsg 'goxg_ 'goxw_)
      (dk-have! (list 'FORALL 'liy_ (list 'IMPLIES '(IN liy_ (CCINT 0 1)) (list '== (list phi 'liy_) (list psi 'liy_))))
        (lambda ()
          (let* ((y (dk-di-var!))
                 (pt (list '+ a (list '* y w))))
            (dk-lam-b!)
            (dk-cite! 'seg-trace-intro a b y)
            (subst (dk-apply! hyp pt))
            (qrfl))))
      (subst (dk-cite! 'cc-int-congruence phi psi 0 1 p1 p2))
      (rfl))))
(qed 'seg-int-congruence)

;;; restricting f to a set that holds the hull does not change the triangle integral
(sp (make-wff (gox-under-H
  (list 'FORALL 'goxw_ (list 'IMPLIES '(SUBSET goxw_ u)
    (gox-all-in '(goxa_ goxb_ goxc_) 'CC
      (list 'IMPLIES '(SUBSET (CONV3 goxa_ goxb_ goxc_) goxw_)
        '(= (TRI-INT (RESTRICT f goxw_) goxa_ goxb_ goxc_) (TRI-INT f goxa_ goxb_ goxc_)))))))))
(dk-peel!)
(let ((fr '(RESTRICT f goxw_)) (c3 '(CONV3 goxa_ goxb_ goxc_)))
  (dk-cite! 'restrict-in-fun 'f 'u 'CC 'goxw_)
  (dk-split-all! (list (dk-cite! 'seg-trace-in-conv3 'goxa_ 'goxb_ 'goxc_)))
  (subst (dk-cite! 'tri-int-unfold fr 'goxa_ 'goxb_ 'goxc_))
  (subst (dk-cite! 'tri-int-unfold 'f 'goxa_ 'goxb_ 'goxc_))
  (for-each
   (lambda (pq)
     (let* ((p (car pq)) (q (cadr pq)) (tr (gox-segtr p q)))
       (fact 'subset-trans tr c3 'goxw_)
       (fact 'subset-trans tr 'goxw_ 'u)
       (dk-have! (list 'FORALL 'goxz_ (list 'IMPLIES (list 'IN 'goxz_ tr) (list '== (list fr 'goxz_) '(f goxz_))))
         (lambda ()
           (let ((z (dk-di-var!)))
             (fact 'subset-mem-fwd tr 'goxw_ z)
             (dk-cite! 'restrict-apply 'f 'goxw_ z)
             (ass))))
       (dk-cite! 'seg-int-in-cc 'u 'f p q)
       (subst (dk-cite! 'seg-int-congruence 'u 'f 'goxw_ fr p q))))
   '((goxa_ goxb_) (goxb_ goxc_) (goxc_ goxa_)))
  (gox-cc! (cadr (dk-goal)))
  (rfl))
(qed 'tri-int-restrict)

;;; ======================================================================
;;; (B) THE ALGEBRA OF SEGMENT INTEGRALS
;;; ======================================================================
;;; under H with conv3(a, b, c) subset u in context: the trace of the segment between two
;;; points of the hull lies in u (both points given as members of the hull)
(define (gox-tr-u! a b c p q)
  (let ((c3 (list 'CONV3 a b c)) (tr (gox-segtr p q)))
    (dk-cite! 'conv3-seg-trace a b c p q)
    (fact 'subset-trans tr c3 'u)
    (dk-cite! 'seg-int-in-cc 'u 'f p q)))
(define (gox-vertices! a b c)
  (dk-split-all! (list (dk-cite! 'conv3-vertices-in a b c))))

;;; (0) THE FAN: with x in the hull, the triangle integral is the sum over the three
;;; triangles with vertex x (the six segments through x cancel in pairs)
(sp (make-wff (gox-under-H (gox-all-in '(goxa_ goxb_ goxc_) 'CC
  (list 'IMPLIES '(SUBSET (CONV3 goxa_ goxb_ goxc_) u)
    (list 'FORALL 'goxx_ (list 'IMPLIES '(IN goxx_ (CONV3 goxa_ goxb_ goxc_))
      '(= (TRI-INT f goxa_ goxb_ goxc_)
          (+ (+ (TRI-INT f goxa_ goxb_ goxx_) (TRI-INT f goxb_ goxc_ goxx_)) (TRI-INT f goxc_ goxa_ goxx_))))))))))
(dk-peel!)
(gox-vertices! 'goxa_ 'goxb_ 'goxc_)
(fact 'subset-mem-fwd '(CONV3 goxa_ goxb_ goxc_) 'u 'goxx_)
(fact 'subset-mem-fwd 'u 'CC 'goxx_)
(for-each (lambda (pq) (gox-tr-u! 'goxa_ 'goxb_ 'goxc_ (car pq) (cadr pq)))
          '((goxa_ goxb_) (goxb_ goxc_) (goxc_ goxa_) (goxb_ goxx_) (goxc_ goxx_) (goxa_ goxx_)
            (goxx_ goxb_) (goxx_ goxc_) (goxx_ goxa_)))
(for-each (lambda (tr) (subst (apply dk-cite! 'tri-int-unfold 'f tr)))
          '((goxa_ goxb_ goxc_) (goxa_ goxb_ goxx_) (goxb_ goxc_ goxx_) (goxc_ goxa_ goxx_)))
(for-each (lambda (p) (subst (dk-cite! 'seg-int-reverse-at 'u 'f p 'goxx_))) '(goxb_ goxc_ goxa_))
(crs)
(qed 'tri-int-fan)

;;; (1) A DEGENERATE TRIANGLE: when one vertex lies on the segment joining the other two,
;;; the triangle integral is 0 (Lemma 3.4 and two reversals), in each of the three placements
(define (gox-on p q r) (list 'IN r (gox-segtr p q)))
(sp (make-wff (gox-under-H (gox-all-in '(goxa_ goxb_ goxc_) 'CC
  (list 'IMPLIES '(SUBSET (CONV3 goxa_ goxb_ goxc_) u)
    (list 'IMPLIES (list 'OR (gox-on 'goxa_ 'goxb_ 'goxc_) (list 'OR (gox-on 'goxb_ 'goxc_ 'goxa_) (gox-on 'goxc_ 'goxa_ 'goxb_)))
      '(= (TRI-INT f goxa_ goxb_ goxc_) 0)))))))
(dk-peel!)
(gox-vertices! 'goxa_ 'goxb_ 'goxc_)
(for-each (lambda (pq) (gox-tr-u! 'goxa_ 'goxb_ 'goxc_ (car pq) (cadr pq)))
          '((goxa_ goxb_) (goxb_ goxc_) (goxc_ goxa_) (goxb_ goxa_) (goxc_ goxb_) (goxa_ goxc_)))
(subst (dk-cite! 'tri-int-unfold 'f 'goxa_ 'goxb_ 'goxc_))
;; r on <p, q>: S(p,q) = S(p,r) + S(r,q), S(q,r) = -S(r,q), S(r,p) = -S(p,r)
(define (gox-col-case! p q r)
  (lambda ()
    (subst (dk-cite! 'seg-int-split-at 'u 'f p q r))
    (subst (dk-cite! 'seg-int-reverse-at 'u 'f r q))
    (subst (dk-cite! 'seg-int-reverse-at 'u 'f p r))
    (crs)))
(use-cases (dk-pick (dk-head? 'OR) "the three placements")
  (gox-col-case! 'goxa_ 'goxb_ 'goxc_)
  (gox-col-case! 'goxb_ 'goxc_ 'goxa_)
  (gox-col-case! 'goxc_ 'goxa_ 'goxb_))
(qed 'tri-int-collinear)

;;; ======================================================================
;;; (C) THE GEOMETRY: CROSS PRODUCT, INDEPENDENCE, THE HULL AVOIDS THE VERTEX,
;;; THE THREE COLLINEAR PLACEMENTS
;;; ======================================================================
;;; the real cross product of b - a and c - a: zero iff a, b, c are collinear
(define (gox-cross a b c) (list 'imag-part (list '* (list '- b a) (list 'conjugate (list '- c a)))))

;;; z in CC in context: skolemize z = x + y i (cc-generated-by-rr), land re z = x, im z = y;
;;; returns (x y)
(define (gox-coords! z)
  (let* ((x (dk-skolem! (dk-cite! 'cc-generated-by-rr z)))
         (y (dk-skolem! (dk-pick (lambda (fm) (and (gox-op? fm 'FORSOME 3) (dk-contains? fm x) (dk-contains? fm z)))
                                 "the second coordinate"))))
    (dk-split-all! (list (dk-cite! 'cc-re-im-of z x y)))
    (list x y)))

;;; imag(v conj(w)) = im v re w - re v im w
(sp (make-wff (gox-all-in '(goxp_ goxq_) 'CC
  '(= (imag-part (* goxp_ (conjugate goxq_)))
      (- (* (imag-part goxp_) (real-part goxq_)) (* (real-part goxp_) (imag-part goxq_)))))))
(dk-peel!)
(fact 'cc-i-in)
(let* ((c1 (gox-coords! 'goxp_)) (x1 (car c1)) (y1 (cadr c1))
       (c2 (gox-coords! 'goxq_)) (x2 (car c2)) (y2 (cadr c2))
       (iy2 (list '* y2 '+i)))
  (for-each (lambda (e) (subst e))
            (list (list '= '(imag-part goxp_) y1) (list '= '(real-part goxp_) x1)
                  (list '= '(imag-part goxq_) y2) (list '= '(real-part goxq_) x2)))
  (for-each gox-cc! (list x1 y1 x2 y2 iy2 (list '* y1 '+i)))
  (dk-have! (list '= '(conjugate goxq_) (list '- x2 iy2))
    (lambda ()
      (subst (list '= 'goxq_ (list '+ x2 iy2)))
      (gox-and! (list 'IN x2 'CC) (list 'IN iy2 'CC))
      (subst (dk-cite! 'cc-conjugate-add x2 iy2))
      (gox-and! (list 'IN y2 'CC) '(IN +i CC))
      (subst (dk-cite! 'cc-conjugate-mul y2 '+i))
      (subst (dk-cite! 'cc-conjugate-fixes-rr x2))
      (subst (dk-cite! 'cc-conjugate-fixes-rr y2))
      (subst (dk-cite! 'cc-conjugate-i))
      (crs)))
  (subst (list '= '(conjugate goxq_) (list '- x2 iy2)))
  (subst (list '= 'goxp_ (list '+ x1 (list '* y1 '+i))))
  (let* ((P (cadr (cadr (dk-goal))))
         (A (list '+ (list '* x1 x2) (list '* y1 y2)))
         (B (list '- (list '* y1 x2) (list '* x1 y2))))
    (gox-rr! A) (gox-rr! B)
    (gox-cc! P)
    (dk-have! (list '= P (list '+ A (list '* B '+i))) (lambda () (crs)))
    (dk-split-all! (list (dk-cite! 'cc-re-im-of P A B)))
    (subst (list '= (list 'imag-part P) B))
    (rfl)))
(qed 'cc-cross-coords)

;;; (2) NOT COLLINEAR => b - a and c - a are independent over RR
(sp (make-wff (gox-all-in '(goxa_ goxb_ goxc_) 'CC
  (list 'IMPLIES (list 'NOT (list '= (gox-cross 'goxa_ 'goxb_ 'goxc_) 0))
    (gox-all-in '(goxp_ goxq_) 'RR
      '(IMPLIES (= (+ (* goxp_ (- goxb_ goxa_)) (* goxq_ (- goxc_ goxa_))) 0)
                (AND (= goxp_ 0) (= goxq_ 0))))))))
(dk-peel!)
(fact 'cc-i-in)
(define gox-ai-cr (gox-cross 'goxa_ 'goxb_ 'goxc_))
(let* ((v '(- goxb_ goxa_)) (w '(- goxc_ goxa_))
       (p 'goxp_) (q 'goxq_))
  (gox-cc! v) (gox-cc! w)
  (let* ((ce (dk-cite! 'cc-cross-coords v w))
         (c1 (gox-coords! v)) (x1 (car c1)) (y1 (cadr c1))
         (c2 (gox-coords! w)) (x2 (car c2)) (y2 (cadr c2))
         (D (list '- (list '* y1 x2) (list '* x1 y2)))
         (A (list '+ (list '* p x1) (list '* q x2)))
         (B (list '+ (list '* p y1) (list '* q y2)))
         (AB (list '+ A (list '* B '+i)))
         (pq (list '+ (list '* p v) (list '* q w))))
    (for-each gox-rr! (list D A B))
    (for-each gox-cc! (list x1 y1 x2 y2 (list '* y1 '+i) (list '* y2 '+i) AB (list '* p v) (list '* q w)))
    (dk-have! (list '= gox-ai-cr D)
      (lambda ()
        (subst ce)
        (for-each (lambda (e) (subst e))
                  (list (list '= (list 'imag-part v) y1) (list '= (list 'real-part v) x1)
                        (list '= (list 'imag-part w) y2) (list '= (list 'real-part w) x2)))
        (rfl)))
    (dk-have! (list 'NOT (list '= D 0))
      (lambda ()
        (di)
        (dk-have! (list '= gox-ai-cr 0) (lambda () (subst (list '= gox-ai-cr D)) (ass)))
        (ai (list 'NOT (list '= gox-ai-cr 0)))))
    (dk-have! (list '= pq AB)
      (lambda ()
        (subst (list '= v (list '+ x1 (list '* y1 '+i))))
        (subst (list '= w (list '+ x2 (list '* y2 '+i))))
        (crs)))
    (dk-have! (list '= 0 AB)
      (lambda () (subst (list '= AB pq)) (subst (list '= pq 0)) (rfl)))
    (dk-split-all! (list (dk-cite! 'cc-re-im-of 0 A B)))
    (dk-have! (list '= A 0) (lambda () (subst (list '= A '(real-part 0))) (arith)))
    (dk-have! (list '= B 0) (lambda () (subst (list '= B '(imag-part 0))) (arith)))
    (for-each
     (lambda (cf)
       (let ((c (car cf)) (rhs (cadr cf)))
         (gox-rr! (list '* c D))
         (dk-have! (list '= (list '* c D) 0)
           (lambda ()
             (dk-have! (list '= (list '* c D) rhs) (lambda () (crs)))
             (subst (list '= (list '* c D) rhs))
             (subst (list '= A 0))
             (subst (list '= B 0))
             (crs)))
         (dk-cite! 'rr-no-zero-divisors c D)))
     (list (list p (list '- (list '* x2 B) (list '* y2 A)))
           (list q (list '- (list '* y1 A) (list '* x1 B)))))
    (dk-conj-close!
      (lambda ()
        (let ((g (dk-goal)))
          (if (dk-only! (list 'OR g (list '= D 0)) (list 'NOT (list '= D 0)))
              (prop)))))))
(qed 'cc-affinely-independent)

;;; v in [0,1] in context: land v in RR, 0 <= v, v <= 1 (the membership survives)
(define (gox-unit! v)
  (let ((mem (list 'IN v '(CCINT 0 1))))
    (fact 'ccint-elt-in-rr 0 1 v)
    (let ((cj (list 'AND (list '<= 0 v) (list '<= v 1))))
      (if (not (and (dk-asm? (list '<= 0 v)) (dk-asm? (list '<= v 1))))
          (begin
            (dk-have! cj (lambda () (mac-h 'ccint-membership mem) (dk-split-all!)
                                    (dk-conj-close! (lambda () (ass)))))
            (dk-split! cj))))))

;;; open a hull membership (consumed): the three coefficients, typed and in [0, 1]
(define (gox-conv3-open! mem)
  (let* ((new (dk-landed* (lambda () (mac-h 'conv3-member-iff mem))))
         (parts (dk-split-all! new))
         (ex1 (find-first (dk-head? 'FORSOME) (append parts new)))
         (l (dk-skolem! ex1))
         (m (dk-skolem! (dk-pick (lambda (f) (and (gox-op? f 'FORSOME 3) (dk-contains? f l)))
                                 "the second coefficient")))
         (n (dk-skolem! (dk-pick (lambda (f) (and (gox-op? f 'FORSOME 3) (dk-contains? f m)))
                                 "the third coefficient"))))
    (for-each gox-unit! (list l m n))
    (list l m n)))
(define (gox-comb l m n a b c)
  (list '+ (list '+ (list '* l a) (list '* m b)) (list '* n c)))
(define (gox-nonneg-prod! a b)
  (let ((f (list '<= 0 (list '* a b))))
    (gox-rr! (list '* a b))
    (if (not (dk-asm? f))
        (begin
          (gox-and! (list 'IN a 'RR) (list 'IN b 'RR))
          (gox-and! (list '<= 0 a) (list '<= 0 b))
          (fact 'rr-leq-mul-nonneg a b)))
    f))

;;; the two side triangles of the vertex case avoid the vertex a, for a, b, c not collinear
(define (gox-bt t) (list '+ 'goxa_ (list '* t '(- goxb_ goxa_))))
(define (gox-ct t) (list '+ 'goxa_ (list '* t '(- goxc_ goxa_))))
(sp (make-wff (gox-all-in '(goxa_ goxb_ goxc_) 'CC
  (list 'IMPLIES (list 'NOT (list '= (gox-cross 'goxa_ 'goxb_ 'goxc_) 0))
    (list 'FORALL 'goxt_ (list 'IMPLIES '(IN goxt_ RR) (list 'IMPLIES '(< 0 goxt_) (list 'IMPLIES '(<= goxt_ 1)
      (list 'AND (list 'NOT (list 'IN 'goxa_ (list 'CONV3 (gox-bt 'goxt_) 'goxb_ 'goxc_)))
                 (list 'NOT (list 'IN 'goxa_ (list 'CONV3 (gox-bt 'goxt_) 'goxc_ (gox-ct 'goxt_)))))))))))))
(dk-peel!)
(fact 'rr-lt-implies-le 0 'goxt_)
(define (gox-av-case! mem pqr pq-of absurd!)
  ;; mem: a in conv3(P, Q, R); pq-of: (l m n) -> (p q), the coefficients of b - a, c - a
  (let* ((lmn (gox-conv3-open! mem)) (l (car lmn)) (m (cadr lmn)) (n (caddr lmn))
         (comb (gox-comb l m n (car pqr) (cadr pqr) (caddr pqr)))
         (sum (list '+ (list '+ l m) n))
         (pq (pq-of l m n)) (p (car pq)) (q (cadr pq))
         (v '(- goxb_ goxa_)) (w '(- goxc_ goxa_))
         (E (list '+ (list '* p v) (list '* q w))))
    (for-each gox-rr! (list p q))
    (for-each gox-cc! (list l m n p q E comb))
    (dk-have! (list '= E 0)
      (lambda ()
        (dk-have! (list '= E (list '- comb (list '* sum 'goxa_))) (lambda () (crs)))
        (subst (list '= E (list '- comb (list '* sum 'goxa_))))
        (subst (list '= comb 'goxa_))
        (subst (list '= sum 1))
        (crs)))
    (dk-split-all! (list (dk-cite! 'cc-affinely-independent 'goxa_ 'goxb_ 'goxc_ p q)))
    (absurd! l m n)))
(dk-conj-close!
  (lambda ()
    (di)
    (let ((mem (dk-pick (lambda (fm) (and (gox-op? fm 'IN 3) (eq? (cadr fm) 'goxa_) (gox-op? (caddr fm) 'CONV3 4)))
                        "a in the side hull")))
      (if (equal? (caddr (caddr mem)) 'goxb_)
          ;; conv3(b_t, b, c): (l t + m)(b - a) + n (c - a) = 0
          (gox-av-case! mem (list (gox-bt 'goxt_) 'goxb_ 'goxc_)
            (lambda (l m n) (list (list '+ (list '* l 'goxt_) m) n))
            (lambda (l m n)
              (let ((lt (list '* l 'goxt_)))
                (gox-nonneg-prod! l 'goxt_)
                (dk-have! (list '= l 1)
                  (lambda () (dk-ineq! (list 'IN lt 'RR) (list 'IN l 'RR) (list 'IN m 'RR) (list 'IN n 'RR)
                                       (list '= (list '+ lt m) 0) (list '<= 0 m) (list '<= 0 lt) (list '= n 0)
                                       (list '= (list '+ (list '+ l m) n) 1))))
                (dk-have! (list '= lt 'goxt_) (lambda () (subst (list '= l 1)) (crs)))
                (dk-absurd! (list 'IN lt 'RR) (list 'IN m 'RR) '(IN goxt_ RR)
                            (list '= lt 'goxt_) (list '= (list '+ lt m) 0) (list '<= 0 m) '(< 0 goxt_)))))
          ;; conv3(b_t, c, c_t): (l t)(b - a) + (m + n t)(c - a) = 0
          (gox-av-case! mem (list (gox-bt 'goxt_) 'goxc_ (gox-ct 'goxt_))
            (lambda (l m n) (list (list '* l 'goxt_) (list '+ m (list '* n 'goxt_))))
            (lambda (l m n)
              (let ((lt (list '* l 'goxt_)) (nt (list '* n 'goxt_)))
                (gox-nonneg-prod! n 'goxt_)
                (gox-rr! (list '+ l n))
                (dk-have! (list '= (list '+ l n) 1)
                  (lambda () (dk-ineq! (list 'IN nt 'RR) (list 'IN l 'RR) (list 'IN m 'RR) (list 'IN n 'RR)
                                       (list '= (list '+ m nt) 0) (list '<= 0 m) (list '<= 0 nt)
                                       (list '= (list '+ (list '+ l m) n) 1))))
                (gox-rr! (list '+ lt nt))
                (dk-have! (list '= (list '+ lt nt) 'goxt_)
                  (lambda ()
                    (dk-have! (list '= (list '+ lt nt) (list '* (list '+ l n) 'goxt_)) (lambda () (crs)))
                    (subst (list '= (list '+ lt nt) (list '* (list '+ l n) 'goxt_)))
                    (subst (list '= (list '+ l n) 1))
                    (crs)))
                (dk-absurd! (list 'IN lt 'RR) (list 'IN nt 'RR) (list 'IN m 'RR) '(IN goxt_ RR)
                            (list '= lt 0) (list '= (list '+ m nt) 0) (list '<= 0 m)
                            (list '= (list '+ lt nt) 'goxt_) '(< 0 goxt_)))))))))
(qed 'conv3-avoids-vertex)

;;; a point of the hull is within |b - a| + |c - a| of the vertex a
(sp (make-wff (gox-all-in '(goxa_ goxb_ goxc_) 'CC
  (gox-all-in '(goxz_) '(CONV3 goxa_ goxb_ goxc_)
    '(<= (magnitude (- goxz_ goxa_)) (+ (magnitude (- goxb_ goxa_)) (magnitude (- goxc_ goxa_))))))))
(dk-peel!)
(fact 'subset-mem-fwd '(CONV3 goxa_ goxb_ goxc_) 'CC 'goxz_)
(let* ((lmn (gox-conv3-open! (dk-pick (lambda (fm) (equal? fm '(IN goxz_ (CONV3 goxa_ goxb_ goxc_)))) "z in the hull")))
       (l (car lmn)) (m (cadr lmn)) (n (caddr lmn))
       (comb (gox-comb l m n 'goxa_ 'goxb_ 'goxc_))
       (sum (list '+ (list '+ l m) n))
       (v '(- goxb_ goxa_)) (w '(- goxc_ goxa_))
       (mv (list '* m v)) (nw (list '* n w))
       (mag (lambda (e) (list 'magnitude e))))
  (for-each gox-cc! (list l m n v w mv nw comb (list '+ mv nw)))
  (dk-have! (list '= '(- goxz_ goxa_) (list '+ mv nw))
    (lambda ()
      (subst (list '= 'goxz_ comb))
      (dk-have! (list '= (list '- comb 'goxa_) (list '+ (list '+ mv nw) (list '* (list '- sum 1) 'goxa_))) (lambda () (crs)))
      (subst (list '= (list '- comb 'goxa_) (list '+ (list '+ mv nw) (list '* (list '- sum 1) 'goxa_))))
      (subst (list '= sum 1))
      (crs)))
  (subst (list '= '(- goxz_ goxa_) (list '+ mv nw)))
  (gox-and! (list 'IN mv 'CC) (list 'IN nw 'CC))
  (fact 'cc-magnitude-triangle mv nw)
  (for-each
   (lambda (cd)
     (let ((c (car cd)) (d (cadr cd)))
       (gox-and! (list 'IN c 'CC) (list 'IN d 'CC))
       (fact 'cc-magnitude-mul c d)
       (fact 'rr-magnitude-is-abs c)
       (dk-cite! 'rr-abs-of-nonneg c)
       (fact 'cc-magnitude-nonneg d)
       (gox-rr! (mag d))
       (gox-and! (list '<= c 1) (list '<= 0 (mag d)))
       (fact 'rr-mul-le-right c 1 (mag d))
       (gox-rr! (list '* c (mag d)))
       (gox-rr! (list '* 1 (mag d)))
       (gox-rr! (mag (list '* c d)))
       (dk-have! (list '= (mag (list '* c d)) (list '* c (mag d)))
         (lambda ()
           (subst (list '= (mag (list '* c d)) (list '* (mag c) (mag d))))
           (subst (list '= (mag c) (list 'abs c)))
           (subst (list '= (list 'abs c) c))
           (rfl)))))
   (list (list m v) (list n w)))
  (gox-rr! (mag (list '+ mv nw)))
  (dk-ineq! (list 'IN (mag (list '+ mv nw)) 'RR) (list 'IN (mag mv) 'RR) (list 'IN (mag nw) 'RR)
            (list 'IN (list '* m (mag v)) 'RR) (list 'IN (list '* n (mag w)) 'RR)
            (list 'IN (mag v) 'RR) (list 'IN (mag w) 'RR)
            (list '<= (mag (list '+ mv nw)) (list '+ (mag mv) (mag nw)))
            (list '= (mag mv) (list '* m (mag v))) (list '= (mag nw) (list '* n (mag w)))
            (list '<= (list '* m (mag v)) (list '* 1 (mag v))) (list '<= (list '* n (mag w)) (list '* 1 (mag w)))))
(qed 'conv3-near-vertex)

;;; name a real term: land (IN n RR), (= n T) for a fresh n, and return n (so that `crs'
;;; can treat a quotient as an atom)
(define (gox-name! t)
  (gox-rr! t)
  (let ((ex (list 'FORSOME 'goxn_ (list 'AND '(IN goxn_ RR) (list '= 'goxn_ t)))))
    (dk-have! ex (lambda () (ew t) (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (rfl))))))
    (dk-skolem! ex)))
;;; land (IN v (CCINT 0 1)) from the named premises
(define (gox-in-unit! v prems)
  (gox-rr! v)
  (dk-have! (list 'IN v '(CCINT 0 1))
    (lambda ()
      (mac 'ccint-membership)
      (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (apply dk-ineq! prems)))))))
;;; 0 < t, t in RR: land recip(t) in RR, 0 < recip(t), t recip(t) = 1; return recip(t)
(define (gox-recip! t)
  (let ((r (list 'recip t)))
    (if (not (dk-asm? (list 'NOT (list '= t 0)))) (fact 'rr-pos-ne-zero t))
    (gox-rr! r)
    (fact 'rr-recip-inverse t)
    (fact 'rr-recip-pos t)
    (fact 'rr-lt-implies-le 0 r)
    r))

;;; (2') COLLINEAR => one vertex lies on the segment joining the other two (the degenerate
;;; triangle b = a is the placement b = a + 1 (a - c) on <c, a>)
(sp (make-wff (gox-all-in '(goxa_ goxb_ goxc_) 'CC
  (list 'IMPLIES (list '= (gox-cross 'goxa_ 'goxb_ 'goxc_) 0)
    (list 'OR (gox-on 'goxa_ 'goxb_ 'goxc_) (list 'OR (gox-on 'goxb_ 'goxc_ 'goxa_) (gox-on 'goxc_ 'goxa_ 'goxb_)))))))
(dk-peel!)
(fact 'cc-i-in)
(define (gox-cl-finish! disj) (if (dk-only! disj) (prop)))
(let* ((a 'goxa_) (b 'goxb_) (c 'goxc_) (v '(- goxb_ goxa_)) (w '(- goxc_ goxa_))
       (cr (gox-cross a b c)))
  (gox-cc! v) (gox-cc! w)
  (let* ((ce (dk-cite! 'cc-cross-coords v w))
         (c1 (gox-coords! v)) (x1 (car c1)) (y1 (cadr c1))
         (c2 (gox-coords! w)) (x2 (car c2)) (y2 (cadr c2))
         (D (list '- (list '* y1 x2) (list '* x1 y2)))
         (N (list '+ (list '* x1 x1) (list '* y1 y1)))
         (K (list '+ (list '* x1 x2) (list '* y1 y2)))
         (iv (list '+ x1 (list '* y1 '+i)))
         (iw (list '+ x2 (list '* y2 '+i))))
    (for-each gox-rr! (list D N K (list '* x1 x1) (list '* y1 y1)))
    (for-each gox-cc! (list x1 y1 x2 y2 (list '* y1 '+i) (list '* y2 '+i)))
    (dk-have! (list '= D 0)
      (lambda ()
        (dk-have! (list '= cr D)
          (lambda ()
            (subst ce)
            (for-each (lambda (e) (subst e))
                      (list (list '= (list 'imag-part v) y1) (list '= (list 'real-part v) x1)
                            (list '= (list 'imag-part w) y2) (list '= (list 'real-part w) x2)))
            (rfl)))
        (subst (list '= D cr))
        (ass)))
    (fact 'rr-sq-nonneg x1)
    (fact 'rr-sq-nonneg y1)
    (dk-have! (list '<= 0 N)
      (lambda () (dk-ineq! (list 'IN (list '* x1 x1) 'RR) (list 'IN (list '* y1 y1) 'RR)
                           (list '<= 0 (list '* x1 x1)) (list '<= 0 (list '* y1 y1)))))
    (use-em (list '= N 0)
      ;; b - a = 0: b = a, which is the endpoint of <c, a>
      (lambda ()
        (for-each
         (lambda (sq)
           (dk-have! (list '= (list '* sq sq) 0)
             (lambda () (dk-ineq! (list 'IN (list '* x1 x1) 'RR) (list 'IN (list '* y1 y1) 'RR) (list '= N 0)
                                  (list '<= 0 (list '* x1 x1)) (list '<= 0 (list '* y1 y1)))))
           (let ((dj (dk-cite! 'rr-no-zero-divisors sq sq)))
             (dk-have! (list '= sq 0) (lambda () (if (dk-only! dj) (prop))))))
         (list x1 y1))
        (dk-have! (list '= b a)
          (lambda ()
            (dk-have! (list '= b (list '+ a v)) (lambda () (crs)))
            (subst (list '= b (list '+ a v)))
            (subst (list '= v iv))
            (subst (list '= x1 0))
            (subst (list '= y1 0))
            (crs)))
        (gox-in-unit! 1 '())
        (dk-cite! 'seg-trace-intro c a 1)
        (let ((pt (list '+ c (list '* 1 (list '- a c)))))
          (gox-cc! pt)
          (dk-have! (list '= pt b) (lambda () (subst (list '= b a)) (crs)))
          (dk-cite! 'in-transport-eq pt b (gox-segtr c a)))
        (gox-cl-finish! (gox-on c a b)))
      ;; b /= a: c - a = L (b - a) with L = K / N real
      (lambda ()
        (fact 'neq-sym N 0)
        (gox-and! (list '<= 0 N) (list 'NOT (list '= 0 N)))
        (fact 'rr-le-ne-lt 0 N)
        (let* ((r (gox-recip! N))
               (L (gox-name! (list '* K r)))
               (Lv (list '* L v)))
          (gox-cc! Lv)
          (dk-have! (list '= x2 (list '* L x1))
            (lambda ()
              (subst (list '= L (list '* K r)))
              (let ((ex (list '- (list '* x2 (list '* N r)) (list '* (list '* y1 D) r))))
                (dk-have! (list '= (list '* (list '* K r) x1) ex) (lambda () (dk-crs-opaque!)))
                (subst (list '= (list '* (list '* K r) x1) ex)))
              (subst (list '= (list '* N r) 1))
              (subst (list '= D 0))
              (dk-crs-opaque!)))
          (dk-have! (list '= y2 (list '* L y1))
            (lambda ()
              (subst (list '= L (list '* K r)))
              (let ((ex (list '+ (list '* y2 (list '* N r)) (list '* (list '* x1 D) r))))
                (dk-have! (list '= (list '* (list '* K r) y1) ex) (lambda () (dk-crs-opaque!)))
                (subst (list '= (list '* (list '* K r) y1) ex)))
              (subst (list '= (list '* N r) 1))
              (subst (list '= D 0))
              (dk-crs-opaque!)))
          (dk-have! (list '= w Lv)
            (lambda ()
              (subst (list '= w iw))
              (subst (list '= v iv))
              (let ((ex (list '+ (list '* L x1) (list '* (list '* L y1) '+i))))
                (dk-have! (list '= (list '* L iv) ex) (lambda () (crs)))
                (subst (list '= (list '* L iv) ex)))
              (subst (list '= (list '* L x1) x2))
              (subst (list '= (list '* L y1) y2))
              (rfl)))
          (use-em (list '<= 0 K)
            (lambda ()
              (use-em (list '<= K N)
                ;; 0 <= L <= 1: c on <a, b>
                (lambda ()
                  (gox-nonneg-prod! K r)
                  (gox-and! (list '<= K N) (list '<= 0 r))
                  (fact 'rr-mul-le-right K N r)
                  (gox-rr! (list '* N r))
                  (gox-in-unit! L (list (list 'IN (list '* K r) 'RR) (list 'IN (list '* N r) 'RR) (list 'IN L 'RR)
                                        (list '= L (list '* K r)) (list '<= 0 (list '* K r))
                                        (list '<= (list '* K r) (list '* N r)) (list '= (list '* N r) 1)))
                  (dk-cite! 'seg-trace-intro a b L)
                  (let ((pt (list '+ a Lv)))
                    (gox-cc! pt)
                    (dk-have! (list '= pt c) (lambda () (subst (list '= Lv w)) (crs)))
                    (dk-cite! 'in-transport-eq pt c (gox-segtr a b)))
                  (gox-cl-finish! (gox-on a b c)))
                ;; L > 1: b on <c, a>, b = c + S (a - c) with S = (K - N) / K
                (lambda ()
                  (fact 'rr-not-le-lt K N)
                  (dk-have! (list '< 0 K) (lambda () (dk-ineq! (list 'IN K 'RR) (list 'IN N 'RR) (list '< 0 N) (list '< N K))))
                  (let* ((rk (gox-recip! K))
                         (kn (list '- K N))
                         (S (gox-name! (list '* kn rk))))
                    (gox-rr! kn)
                    (dk-have! (list '<= 0 kn) (lambda () (dk-ineq! (list 'IN K 'RR) (list 'IN N 'RR) (list '< N K))))
                    (gox-nonneg-prod! kn rk)
                    (dk-have! (list '<= kn K) (lambda () (dk-ineq! (list 'IN K 'RR) (list 'IN N 'RR) (list '< 0 N))))
                    (gox-and! (list '<= kn K) (list '<= 0 rk))
                    (fact 'rr-mul-le-right kn K rk)
                    (gox-rr! (list '* kn rk)) (gox-rr! (list '* K rk))
                    (gox-in-unit! S (list (list 'IN (list '* kn rk) 'RR) (list 'IN (list '* K rk) 'RR) (list 'IN S 'RR)
                                          (list '= S (list '* kn rk)) (list '<= 0 (list '* kn rk))
                                          (list '<= (list '* kn rk) (list '* K rk)) (list '= (list '* K rk) 1)))
                    (gox-rr! (list '* (list '- 1 S) L))
                    (dk-have! (list '= (list '* (list '- 1 S) L) 1)
                      (lambda ()
                        (subst (list '= S (list '* kn rk)))
                        (subst (list '= L (list '* K r)))
                        (let ((ex (list '+ (list '* (list '* K r) (list '- 1 (list '* K rk))) (list '* (list '* N r) (list '* K rk)))))
                          (dk-have! (list '= (list '* (list '- 1 (list '* kn rk)) (list '* K r)) ex) (lambda () (dk-crs-opaque!)))
                          (subst (list '= (list '* (list '- 1 (list '* kn rk)) (list '* K r)) ex)))
                        (subst (list '= (list '* K rk) 1))
                        (subst (list '= (list '* N r) 1))
                        (dk-crs-opaque!)))
                    (gox-cc! S)
                    (dk-cite! 'seg-trace-intro c a S)
                    (let ((pt (list '+ c (list '* S (list '- a c))))
                          (ex1 (list '+ a (list '* (list '- 1 S) w)))
                          (ex2 (list '* (list '* (list '- 1 S) L) v)))
                      (for-each gox-cc! (list pt ex1 ex2))
                      (dk-have! (list '= pt b)
                        (lambda ()
                          (dk-have! (list '= pt ex1) (lambda () (crs)))
                          (subst (list '= pt ex1))
                          (subst (list '= w Lv))
                          (dk-have! (list '= (list '* (list '- 1 S) Lv) ex2) (lambda () (crs)))
                          (subst (list '= (list '* (list '- 1 S) Lv) ex2))
                          (subst (list '= (list '* (list '- 1 S) L) 1))
                          (crs)))
                      (dk-cite! 'in-transport-eq pt b (gox-segtr c a)))
                    (gox-cl-finish! (gox-on c a b))))))
            ;; L < 0: a on <b, c>, a = b + S (c - b) with S = N / (N - K)
            (lambda ()
              (fact 'rr-not-le-lt 0 K)
              (let ((q (list '- N K)))
                (gox-rr! q)
                (dk-have! (list '< 0 q) (lambda () (dk-ineq! (list 'IN K 'RR) (list 'IN N 'RR) (list '< 0 N) (list '< K 0))))
                (let* ((rq (gox-recip! q))
                       (S (gox-name! (list '* N rq))))
                  (fact 'rr-lt-implies-le 0 N)
                  (gox-nonneg-prod! N rq)
                  (dk-have! (list '<= N q) (lambda () (dk-ineq! (list 'IN K 'RR) (list 'IN N 'RR) (list '< K 0))))
                  (gox-and! (list '<= N q) (list '<= 0 rq))
                  (fact 'rr-mul-le-right N q rq)
                  (gox-rr! (list '* N rq)) (gox-rr! (list '* q rq))
                  (gox-in-unit! S (list (list 'IN (list '* N rq) 'RR) (list 'IN (list '* q rq) 'RR) (list 'IN S 'RR)
                                        (list '= S (list '* N rq)) (list '<= 0 (list '* N rq))
                                        (list '<= (list '* N rq) (list '* q rq)) (list '= (list '* q rq) 1)))
                  (let ((E2 (list '+ 1 (list '* S (list '- L 1)))))
                    (gox-rr! E2)
                    (dk-have! (list '= E2 0)
                      (lambda ()
                        (subst (list '= S (list '* N rq)))
                        (subst (list '= L (list '* K r)))
                        (let ((lhs (cadr (dk-goal)))
                              (ex (list '+ (list '- 1 (list '* q rq)) (list '* (list '- (list '* N r) 1) (list '* K rq)))))
                          (dk-have! (list '= lhs ex) (lambda () (dk-crs-opaque!)))
                          (subst (list '= lhs ex)))
                        (subst (list '= (list '* q rq) 1))
                        (subst (list '= (list '* N r) 1))
                        (dk-crs-opaque!)))
                    (gox-cc! S) (gox-cc! E2)
                    (dk-cite! 'seg-trace-intro b c S)
                    (let* ((pt (list '+ b (list '* S (list '- c b))))
                           (ex1 (list '+ a (list '+ v (list '* S (list '- w v)))))
                           (mid (list '+ v (list '* S (list '- Lv v))))
                           (ex2 (list '* v E2)))
                      (for-each gox-cc! (list pt ex1 mid ex2))
                      (dk-have! (list '= pt a)
                        (lambda ()
                          (dk-have! (list '= pt ex1) (lambda () (crs)))
                          (subst (list '= pt ex1))
                          (subst (list '= w Lv))
                          (dk-have! (list '= mid ex2) (lambda () (crs)))
                          (subst (list '= mid ex2))
                          (subst (list '= E2 0))
                          (crs)))
                      (dk-cite! 'in-transport-eq pt a (gox-segtr b c)))
                    (gox-cl-finish! (gox-on b c a))))))))))))
(qed 'collinear-cases)

;;; the three triangles of the vertex decomposition lie in the hull: for t in [0, 1],
;;; b_t = a + t (b - a) and c_t = a + t (c - a)
(define gox-C3a '(CONV3 goxa_ goxb_ goxc_))
(sp (make-wff (gox-all-in '(goxa_ goxb_ goxc_) 'CC
  (list 'FORALL 'goxt_ (list 'IMPLIES '(IN goxt_ (CCINT 0 1))
    (list 'AND (list 'SUBSET (list 'CONV3 'goxa_ (gox-bt 'goxt_) (gox-ct 'goxt_)) gox-C3a)
      (list 'AND (list 'SUBSET (list 'CONV3 (gox-bt 'goxt_) 'goxb_ 'goxc_) gox-C3a)
                 (list 'SUBSET (list 'CONV3 (gox-bt 'goxt_) 'goxc_ (gox-ct 'goxt_)) gox-C3a))))))))
(dk-peel!)
(gox-unit! 'goxt_)
(let* ((tt 'goxt_) (omt (list '- 1 tt)) (bt (gox-bt tt)) (ct (gox-ct tt)))
  (gox-in-unit! omt (list (list 'IN tt 'RR) (list '<= 0 tt) (list '<= tt 1)))
  (gox-in-unit! 0 '())
  (gox-cc! bt) (gox-cc! ct)
  (for-each
   (lambda (spec)
     (let* ((pt (car spec)) (l (cadr spec)) (mm (caddr spec)) (n (cadddr spec))
            (sum (list '+ (list '+ l mm) n)) (comb (gox-comb l mm n 'goxa_ 'goxb_ 'goxc_)))
       (gox-cc! comb)
       (dk-have! (list '= sum 1) (lambda () (crs)))
       (dk-have! (list '= pt comb) (lambda () (crs)))
       (dk-cite! 'conv3-intro 'goxa_ 'goxb_ 'goxc_ l mm n pt)))
   (list (list bt omt tt 0) (list ct omt 0 tt)))
  (gox-vertices! 'goxa_ 'goxb_ 'goxc_)
  (dk-cite! 'conv3-sub-hull 'goxa_ 'goxb_ 'goxc_ 'goxa_ bt ct)
  (dk-cite! 'conv3-sub-hull 'goxa_ 'goxb_ 'goxc_ bt 'goxb_ 'goxc_)
  (dk-cite! 'conv3-sub-hull 'goxa_ 'goxb_ 'goxc_ bt 'goxc_ ct)
  (dk-conj-close! (lambda () (ass))))
(qed 'conv3-vertex-shrink)

;;; the vertex decomposition: int_T(a, b, c) = int_T(a, b_t, c_t) + int_T(b_t, b, c)
;;; + int_T(b_t, c, c_t), for t in [0, 1] (Lemma 3.4 twice and two reversals)
(sp (make-wff (gox-under-H (gox-all-in '(goxa_ goxb_ goxc_) 'CC
  (list 'IMPLIES (list 'SUBSET gox-C3a 'u)
    (list 'FORALL 'goxt_ (list 'IMPLIES '(IN goxt_ (CCINT 0 1))
      (list '= '(TRI-INT f goxa_ goxb_ goxc_)
               (list '+ (list '+ (list 'TRI-INT 'f 'goxa_ (gox-bt 'goxt_) (gox-ct 'goxt_))
                                 (list 'TRI-INT 'f (gox-bt 'goxt_) 'goxb_ 'goxc_))
                        (list 'TRI-INT 'f (gox-bt 'goxt_) 'goxc_ (gox-ct 'goxt_)))))))))))
(dk-peel!)
(gox-unit! 'goxt_)
(let* ((a 'goxa_) (b 'goxb_) (c 'goxc_) (tt 'goxt_) (omt (list '- 1 tt)) (bt (gox-bt tt)) (ct (gox-ct tt))
       (h1 (list 'CONV3 a bt ct)))
  (gox-cc! bt) (gox-cc! ct)
  (dk-split-all! (list (dk-cite! 'conv3-vertex-shrink a b c tt)))
  (dk-split-all! (list (dk-cite! 'conv3-vertices-in a bt ct)))
  (fact 'subset-mem-fwd h1 gox-C3a bt)
  (fact 'subset-mem-fwd h1 gox-C3a ct)
  (gox-vertices! a b c)
  (for-each (lambda (pq) (gox-tr-u! a b c (car pq) (cadr pq)))
            (list (list a bt) (list bt b) (list a b) (list c ct) (list ct a) (list c a) (list bt ct)
                  (list ct bt) (list b c) (list c bt) (list bt c)))
  (dk-cite! 'seg-trace-intro a b tt)
  (gox-in-unit! omt (list (list 'IN tt 'RR) (list '<= 0 tt) (list '<= tt 1)))
  (let ((cpt (list '+ c (list '* omt (list '- a c)))))
    (gox-cc! cpt)
    (dk-cite! 'seg-trace-intro c a omt)
    (dk-have! (list '= cpt ct) (lambda () (crs)))
    (dk-cite! 'in-transport-eq cpt ct (gox-segtr c a)))
  (for-each (lambda (tr) (subst (apply dk-cite! 'tri-int-unfold 'f tr)))
            (list (list a b c) (list a bt ct) (list bt b c) (list bt c ct)))
  (subst (dk-cite! 'seg-int-split-at 'u 'f a b bt))
  (subst (dk-cite! 'seg-int-split-at 'u 'f c a ct))
  (subst (dk-cite! 'seg-int-reverse-at 'u 'f bt ct))
  (subst (dk-cite! 'seg-int-reverse-at 'u 'f bt c))
  (crs))
(qed 'tri-int-vertex-split)

;;; ======================================================================
;;; (D) THE VERTEX CASE (Rudin 10.13): the triangle with a vertex at the exceptional point
;;; ======================================================================
(define (gox-pts-cc!)
  (if (not (dk-asm? '(== (PTS CC-MS) CC)))
      (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))))
(define (gox-pos-rr! t)          ; t in RR, 0 < t  ==>  POS-RR(t)
  (fact 'rr-lt-implies-le 0 t)
  (fact 'rr-pos-ne-zero t)
  (fact 'neq-sym t 0)
  (dk-have! (list 'POS-RR t) (lambda () (mac 'pos-rr) (from-context!))))
;;; d0 = t d1 (a ring identity), t in RR with 0 <= t:  land |d0| = t |d1|
(define (gox-scaled-mag! t d0 d1)
  (let ((m (lambda (e) (list 'magnitude e))))
    (gox-cc! d0) (gox-cc! d1) (gox-cc! t)
    (gox-rr! (m d0)) (gox-rr! (m d1)) (gox-rr! (list '* t (m d1)))
    (dk-have! (list '= d0 (list '* t d1)) (lambda () (crs)))
    (gox-and! (list 'IN t 'CC) (list 'IN d1 'CC))
    (fact 'cc-magnitude-mul t d1)
    (fact 'rr-magnitude-is-abs t)
    (dk-cite! 'rr-abs-of-nonneg t)
    (fact 'cc-magnitude-nonneg d1)
    (dk-have! (list '= (m d0) (list '* t (m d1)))
      (lambda ()
        (subst (list '= d0 (list '* t d1)))
        (subst (list '= (m (list '* t d1)) (list '* (m t) (m d1))))
        (subst (list '= (m t) (list 'abs t)))
        (subst (list '= (list 'abs t) t))
        (rfl)))))
;;; t <= num recip(X + 1), 0 <= X, 0 < t, all real  ==>  t X <= num; returns num recip(X + 1)
(define (gox-bound-by! num x)
  (let* ((x1 (list '+ x 1)))
    (gox-rr! x1)
    (dk-have! (list '< 0 x1) (lambda () (dk-ineq! (list 'IN x 'RR) (list '<= 0 x))))
    (let* ((rq (gox-recip! x1)) (d (list '* num rq)))
      (gox-rr! d)
      (list d
        (lambda (t)
          (fact 'rr-lt-implies-le 0 x1)
          (gox-and! (list '<= t d) (list '<= 0 x1))
          (fact 'rr-mul-le-right t d x1)
          (for-each gox-rr! (list (list '* t x1) (list '* d x1) (list '* t x)))
          (dk-have! (list '= (list '* d x1) num)
            (lambda ()
              (let ((ex (list '* num (list '* x1 rq))))
                (dk-have! (list '= (list '* d x1) ex) (lambda () (dk-crs-opaque!)))
                (subst (list '= (list '* d x1) ex)))
              (subst (list '= (list '* x1 rq) 1))
              (crs)))
          (dk-have! (list '= (list '* t x1) (list '+ (list '* t x) t)) (lambda () (crs)))
          (dk-have! (list '<= (list '* t x) num)
            (lambda () (dk-ineq! (list 'IN (list '* t x) 'RR) (list 'IN (list '* t x1) 'RR) (list 'IN (list '* d x1) 'RR)
                                 (list 'IN num 'RR) (list 'IN t 'RR)
                                 (list '<= (list '* t x1) (list '* d x1)) (list '= (list '* d x1) num)
                                 (list '= (list '* t x1) (list '+ (list '* t x) t)) (list '< 0 t)))))))))
;;; a hull H with H subset u and NOT(x in H) in context: land H subset V
(define (gox-hull-in-V! h)
  (dk-have! (list 'SUBSET h gox-V)
    (lambda ()
      (let* ((z (subset-by-element!))
             (i1 (dk-cite! 'difference-membership 'u '(SINGLETON goxx_) z))
             (i2 (dk-cite! 'singleton-membership 'goxx_ z)))
        (fact 'subset-mem-fwd h 'u z)
        (dk-have! (list 'NOT (list '= z 'goxx_))
          (lambda ()
            (di)
            (dk-cite! 'in-transport-eq z 'goxx_ h)
            (ai (list 'NOT (list 'IN 'goxx_ h)))))
        (if (dk-only! i1 i2 (list 'IN z 'u) (list 'NOT (list '= z 'goxx_)))
            (prop))))))

(define gox-J '(TRI-INT f goxx_ goxb_ goxc_))
(sp (make-wff (gox-under-E (gox-all-in '(goxb_ goxc_) 'u
  (list 'IMPLIES '(SUBSET (CONV3 goxx_ goxb_ goxc_) u) (list '= gox-J 0))))))
(dk-peel!)
(gox-E-setup!)
(for-each (lambda (pp) (fact 'subset-mem-fwd 'u 'CC pp)) '(goxx_ goxb_ goxc_))
(dk-cite! 'tri-int-in-cc 'u 'f 'goxx_ 'goxb_ 'goxc_)
(define gox-vx-cr (gox-cross 'goxx_ 'goxb_ 'goxc_))
(use-em (list '= gox-vx-cr 0)
  ;; collinear: a degenerate triangle
  (lambda ()
    (dk-cite! 'collinear-cases 'goxx_ 'goxb_ 'goxc_)
    (dk-cite! 'tri-int-collinear 'u 'f 'goxx_ 'goxb_ 'goxc_)
    (ass))
  ;; not collinear: the limiting argument
  (lambda ()
    (let* ((x 'goxx_) (b 'goxb_) (c 'goxc_) (c3 '(CONV3 goxx_ goxb_ goxc_))
           (S (list 'SUBSPACE-MS gox-nfm 'u))
           (mg (lambda (e) (list 'magnitude e)))
           (fx '(f goxx_))
           (M (list '+ (mg fx) 1))
           (dbx (mg '(- goxb_ goxx_))) (dcb (mg '(- goxc_ goxb_))) (dxc (mg '(- goxx_ goxc_))) (dcx (mg '(- goxc_ goxx_)))
           (P (list '+ (list '+ dbx dcb) dxc))
           (Rr (list '+ dbx dcx))
           (PM (list '* P M))
           (mJ (mg gox-J)))
      (fact 'cc-is-metric-space)
      (gox-pts-cc!)
      (fact 'fun-apply-type-c 'f 'u 'CC x)
      (for-each (lambda (e) (gox-cc! (cadr e)) (gox-rr! e) (fact 'cc-magnitude-nonneg (cadr e))) (list dbx dcb dxc dcx))
      (for-each gox-rr! (list M P Rr PM mJ))
      (fact 'cc-magnitude-nonneg fx)
      (fact 'cc-magnitude-nonneg gox-J)
      (dk-have! (list '<= 0 M) (lambda () (dk-ineq! (list 'IN (mg fx) 'RR) (list '<= 0 (mg fx)))))
      (dk-have! (list '<= 0 P) (lambda () (dk-ineq! (list 'IN dbx 'RR) (list 'IN dcb 'RR) (list 'IN dxc 'RR)
                                                    (list '<= 0 dbx) (list '<= 0 dcb) (list '<= 0 dxc))))
      (dk-have! (list '<= 0 Rr) (lambda () (dk-ineq! (list 'IN dbx 'RR) (list 'IN dcx 'RR) (list '<= 0 dbx) (list '<= 0 dcx))))
      (gox-nonneg-prod! P M)
      ;; continuity of f at x, at eps = 1
      (let* ((cx (dk-apply! (dk-ctx-form (gox-cont 'u 'f)) x))
             (iff (dk-cite! 'is-continuous-at S gox-nfm 'f x))
             (edf (let loop ((r (caddr iff))) (if (eq? (car r) 'AND) (loop (caddr r)) r))))
        (dk-have! edf (lambda () (if (dk-only! iff cx) (prop))))
        (fact 'rr-one-in)
        (dk-have! '(< 0 1) (lambda () (dk-ineq!)))
        (dk-have! '(POS-RR 1) (lambda () (mac 'pos-rr) (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (arith))))))
        (let* ((del (dk-skolem! (dk-apply! edf 1)))
               (ub (dk-pick (lambda (fm) (and (gox-op? fm 'FORALL 3) (dk-contains? fm del))) "the continuity bound"))
               (bnd (list 'FORALL 'goxz_ (list 'IMPLIES '(IN goxz_ u)
                      (list 'IMPLIES (list '<= '(magnitude (- goxz_ goxx_)) del) (list '<= '(magnitude (f goxz_)) M))))))
          (fact 'rr-pos-rr-in-rr del)
          (fact 'rr-lt-of-pos-rr del)
          (fact 'subspace-pts gox-nfm 'u)
          ;; |f| <= |f(x)| + 1 within del of x
          (dk-have! bnd
            (lambda ()
              (let* ((z (dk-di-var!))
                     (fz (list 'f z)))
                (di)
                (fact 'subset-mem-fwd 'u 'CC z)
                (fact 'fun-apply-type-c 'f 'u 'CC z)
                (dk-have! (list 'IN z (list 'PTS S)) (lambda () (subst (list '== (list 'PTS S) 'u)) (ass)))
                (for-each (lambda (pp) (dk-have! (list 'IN pp '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass))))
                          (list x z fx fz))
                (fact 'subspace-dist gox-nfm 'u x z)
                (fact 'nf-cc-agree-dist x z)
                (fact 'cc-ms-dist x z)
                (gox-cc! (list '- x z)) (gox-rr! (mg (list '- x z)))
                (gox-cc! (list '- z x)) (gox-rr! (mg (list '- z x)))
                (dk-cite! 'cc-magnitude-sub-sym x z)
                (dk-have! (list '<= (list (list 'DIST S) x z) del)
                  (lambda ()
                    (subst (list '== (list (list 'DIST S) x z) (list (list 'DIST gox-nfm) x z)))
                    (subst (list '== (list (list 'DIST gox-nfm) x z) (list '(DIST CC-MS) x z)))
                    (subst (list '== (list '(DIST CC-MS) x z) (mg (list '- x z))))
                    (subst (list '= (mg (list '- x z)) (mg (list '- z x))))
                    (ass)))
                (dk-apply! ub z)
                (fact 'nf-cc-agree-dist fx fz)
                (fact 'cc-ms-dist fx fz)
                (gox-cc! (list '- fx fz)) (gox-rr! (mg (list '- fx fz)))
                (gox-cc! (list '- fz fx)) (gox-rr! (mg (list '- fz fx))) (gox-rr! (mg fz))
                (dk-have! (list '<= (mg (list '- fx fz)) 1)
                  (lambda ()
                    (subst (list '== (mg (list '- fx fz)) (list '(DIST CC-MS) fx fz)))
                    (subst (list '== (list '(DIST CC-MS) fx fz) (list (list 'DIST gox-nfm) fx fz)))
                    (ass)))
                (dk-cite! 'cc-magnitude-sub-sym fz fx)
                (dk-cite! 'cc-magnitude-le-add fz fx)
                (dk-ineq! (list 'IN (mg fz) 'RR) (list 'IN (mg fx) 'RR) (list 'IN (mg (list '- fx fz)) 'RR)
                          (list 'IN (mg (list '- fz fx)) 'RR)
                          (list '<= (mg fz) (list '+ (mg (list '- fz fx)) (mg fx)))
                          (list '= (mg (list '- fz fx)) (mg (list '- fx fz)))
                          (list '<= (mg (list '- fx fz)) 1)))))
          ;; for every e > 0: |J| <= e
          (dk-have! (list 'FORALL 'goxe_ (list 'IMPLIES '(POS-RR goxe_) (list '<= mJ 'goxe_)))
            (lambda ()
              (let* ((e (cadr (car (filter (dk-head? 'POS-RR) (dk-peel!)))))
                     (b0 (begin (fact 'rr-pos-rr-in-rr e) (fact 'rr-lt-of-pos-rr e)))
                     (b1 (gox-bound-by! del Rr))
                     (b2 (gox-bound-by! e PM)))
                (fact 'rr-mul-pos del (caddr (car b1)))
                (fact 'rr-mul-pos e (caddr (car b2)))
                (let* ((tmid (dk-skolem! (dk-cite! 'rr-min-pos 1 (car b1))))
                       (tt (dk-skolem! (dk-cite! 'rr-min-pos tmid (car b2))))
                       (bt (list '+ x (list '* tt '(- goxb_ goxx_))))
                       (ct (list '+ x (list '* tt '(- goxc_ goxx_))))
                       (h1 (list 'CONV3 x bt ct)) (h2 (list 'CONV3 bt b c)) (h3 (list 'CONV3 bt c ct))
                       (T1 (list 'TRI-INT 'f x bt ct)) (T2 (list 'TRI-INT 'f bt b c)) (T3 (list 'TRI-INT 'f bt c ct)))
                  (dk-have! (list '<= tt 1) (lambda () (dk-ineq! (list 'IN tt 'RR) (list 'IN tmid 'RR) (list '<= tt tmid) (list '<= tmid 1))))
                  (dk-have! (list '<= tt (car b1))
                    (lambda () (dk-ineq! (list 'IN tt 'RR) (list 'IN tmid 'RR) (list 'IN (car b1) 'RR) (list '<= tt tmid) (list '<= tmid (car b1)))))
                  ((cadr b1) tt)
                  ((cadr b2) tt)
                  (fact 'rr-lt-implies-le 0 tt)
                  ;; the three triangles lie in the hull; the decomposition J = T1 + T2 + T3
                  (gox-in-unit! tt (list (list 'IN tt 'RR) (list '< 0 tt) (list '<= tt 1)))
                  (gox-cc! bt) (gox-cc! ct)
                  (dk-split-all! (list (dk-cite! 'conv3-vertex-shrink x b c tt)))
                  (for-each (lambda (h) (fact 'subset-trans h c3 'u)) (list h1 h2 h3))
                  (for-each (lambda (tr) (apply dk-cite! 'tri-int-in-cc 'u 'f (cdr tr))) (list h1 h2 h3))
                  (dk-cite! 'tri-int-vertex-split 'u 'f x b c tt)
                  ;; the two side triangles avoid x: Goursat on V = u \ {x}
                  (dk-split-all! (list (dk-cite! 'conv3-avoids-vertex x b c tt)))
                  (for-each
                   (lambda (h)
                     (let* ((pqr (cdr h)) (fr (list 'RESTRICT 'f gox-V)))
                       (gox-hull-in-V! h)
                       (dk-split-all! (list (apply dk-cite! 'conv3-vertices-in pqr)))
                       (for-each (lambda (pp) (fact 'subset-mem-fwd h gox-V pp)) pqr)
                       (apply dk-cite! 'goursat-triangle gox-V fr pqr)
                       (apply dk-cite! 'tri-int-restrict 'u 'f gox-V pqr)
                       (dk-have! (list '= (cons 'TRI-INT (cons 'f pqr)) 0)
                         (lambda () (subst (list '= (cons 'TRI-INT (cons 'f pqr)) (cons 'TRI-INT (cons fr pqr)))) (ass)))))
                   (list h2 h3))
                  ;; the small triangle: perimeter t P, |f| <= M on its hull
                  (gox-scaled-mag! tt (list '- bt x) '(- goxb_ goxx_))
                  (gox-scaled-mag! tt (list '- ct bt) '(- goxc_ goxb_))
                  (gox-scaled-mag! tt (list '- x ct) '(- goxx_ goxc_))
                  (gox-scaled-mag! tt (list '- ct x) '(- goxc_ goxx_))
                  (gox-rr! (list '* tt Rr))
                  (dk-have! (list 'FORALL 'goxy_ (list 'IMPLIES (list 'IN 'goxy_ h1) (list '<= '(magnitude (f goxy_)) M)))
                    (lambda ()
                      (let* ((z (dk-di-var!)) (dz (mg (list '- z x))))
                        (fact 'subset-mem-fwd h1 'u z)
                        (fact 'subset-mem-fwd 'u 'CC z)
                        (dk-cite! 'conv3-near-vertex x bt ct z)
                        (gox-cc! (list '- z x)) (gox-rr! dz)
                        (dk-have! (list '= (list '* tt Rr) (list '+ (list '* tt dbx) (list '* tt dcx))) (lambda () (crs)))
                        (dk-have! (list '<= dz del)
                          (lambda ()
                            (dk-ineq! (list 'IN dz 'RR) (list 'IN (mg (list '- bt x)) 'RR) (list 'IN (mg (list '- ct x)) 'RR)
                                      (list 'IN (list '* tt dbx) 'RR) (list 'IN (list '* tt dcx) 'RR) (list 'IN (list '* tt Rr) 'RR)
                                      (list 'IN del 'RR)
                                      (list '<= dz (list '+ (mg (list '- bt x)) (mg (list '- ct x))))
                                      (list '= (mg (list '- bt x)) (list '* tt dbx)) (list '= (mg (list '- ct x)) (list '* tt dcx))
                                      (list '= (list '* tt Rr) (list '+ (list '* tt dbx) (list '* tt dcx)))
                                      (list '<= (list '* tt Rr) del))))
                        (dk-apply! bnd z)
                        (ass))))
                  (let* ((bd (dk-apply! (dk-cite! 'tri-int-abs-bound 'u 'f x bt ct) M))
                         (per (list '+ (list '+ (mg (list '- bt x)) (mg (list '- ct bt))) (mg (list '- x ct))))
                         (tpm (list '* tt PM)))
                    (gox-rr! (list '* per M)) (gox-rr! tpm) (gox-rr! (mg T1))
                    (dk-have! (list '= (list '* per M) tpm)
                      (lambda ()
                        (subst (list '= (mg (list '- bt x)) (list '* tt dbx)))
                        (subst (list '= (mg (list '- ct bt)) (list '* tt dcb)))
                        (subst (list '= (mg (list '- x ct)) (list '* tt dxc)))
                        (crs)))
                    (dk-have! (list '= mJ (mg T1))
                      (lambda ()
                        (subst (list '= gox-J (list '+ (list '+ T1 T2) T3)))
                        (subst (list '= T2 0))
                        (subst (list '= T3 0))
                        (dk-have! (list '= (list '+ (list '+ T1 0) 0) T1) (lambda () (crs)))
                        (subst (list '= (list '+ (list '+ T1 0) 0) T1))
                        (rfl)))
                    (dk-ineq! (list 'IN mJ 'RR) (list 'IN (mg T1) 'RR) (list 'IN (list '* per M) 'RR) (list 'IN tpm 'RR)
                              (list 'IN e 'RR)
                              (list '= mJ (mg T1)) bd (list '= (list '* per M) tpm) (list '<= tpm e)))))))
          (dk-cite! 'rr-le-all-pos-nonpos mJ)
          (dk-have! (list '= mJ 0) (lambda () (dk-ineq! (list 'IN mJ 'RR) (list '<= mJ 0) (list '<= 0 mJ))))
          (let ((zi (dk-cite! 'cc-magnitude-zero-iff gox-J)))
            (if (dk-only! zi (list '= mJ 0)) (prop))))))))

(qed 'goursat-vertex)

;;; ======================================================================
;;; (E) PROPOSITION 3.6: CAUCHY-GOURSAT FOR A TRIANGLE, f continuous on u, holomorphic off x
;;; ======================================================================
(sp (make-wff (gox-under-E (gox-all-in '(goxa_ goxb_ goxc_) 'u
  (list 'IMPLIES '(SUBSET (CONV3 goxa_ goxb_ goxc_) u) '(= (TRI-INT f goxa_ goxb_ goxc_) 0))))))
(dk-peel!)
(gox-E-setup!)
(for-each (lambda (pp) (fact 'subset-mem-fwd 'u 'CC pp)) '(goxx_ goxa_ goxb_ goxc_))
(define gox-C3 '(CONV3 goxa_ goxb_ goxc_))
(use-em (list 'IN 'goxx_ gox-C3)
  ;; x in the hull: the fan, and the vertex case three times
  (lambda ()
    (gox-vertices! 'goxa_ 'goxb_ 'goxc_)
    (for-each (lambda (pq) (gox-tr-u! 'goxa_ 'goxb_ 'goxc_ (car pq) (cadr pq)))
              '((goxa_ goxb_) (goxb_ goxc_) (goxc_ goxa_) (goxb_ goxx_) (goxc_ goxx_) (goxa_ goxx_)
                (goxx_ goxb_) (goxx_ goxc_) (goxx_ goxa_)))
    (for-each
     (lambda (pq)
       (let* ((p (car pq)) (q (cadr pq))
              (tv (list 'TRI-INT 'f 'goxx_ p q)) (tl (list 'TRI-INT 'f p q 'goxx_))
              (h (list 'CONV3 'goxx_ p q)))
         (dk-cite! 'conv3-sub-hull 'goxa_ 'goxb_ 'goxc_ 'goxx_ p q)
         (fact 'subset-trans h gox-C3 'u)
         (dk-cite! 'goursat-vertex 'u 'f 'goxx_ p q)
         (let ((uv (dk-cite! 'tri-int-unfold 'f 'goxx_ p q))
               (ul (dk-cite! 'tri-int-unfold 'f p q 'goxx_)))
           (dk-have! (list '= tl 0)
             (lambda ()
               (subst ul)
               (dk-have! (list '= (caddr ul) (caddr uv)) (lambda () (crs)))
               (subst (list '= (caddr ul) (caddr uv)))
               (subst (list '= (caddr uv) tv))
               (subst (list '= tv 0))
               (rfl))))))
     '((goxa_ goxb_) (goxb_ goxc_) (goxc_ goxa_)))
    (subst (dk-cite! 'tri-int-fan 'u 'f 'goxa_ 'goxb_ 'goxc_ 'goxx_))
    (for-each (lambda (pq) (subst (list '= (list 'TRI-INT 'f (car pq) (cadr pq) 'goxx_) 0)))
              '((goxa_ goxb_) (goxb_ goxc_) (goxc_ goxa_)))
    (crs))
  ;; x off the hull: the hull lies in V, where f is holomorphic
  (lambda ()
    (let ((fr (list 'RESTRICT 'f gox-V)))
      (gox-hull-in-V! gox-C3)
      (gox-vertices! 'goxa_ 'goxb_ 'goxc_)
      (for-each (lambda (pp) (fact 'subset-mem-fwd gox-C3 gox-V pp)) '(goxa_ goxb_ goxc_))
      (dk-cite! 'goursat-triangle gox-V fr 'goxa_ 'goxb_ 'goxc_)
      (dk-cite! 'tri-int-restrict 'u 'f gox-V 'goxa_ 'goxb_ 'goxc_)
      (subst (list '= '(TRI-INT f goxa_ goxb_ goxc_) (list 'TRI-INT fr 'goxa_ 'goxb_ 'goxc_)))
      (ass))))
(qed 'goursat-triangle-except)

;;; ======================================================================
;;; (F) DIFFERENTIABILITY FROM A LITTLE-O BOUND.  If |g(y) - g(a) - (y - a) L| <= eps |y - a|
;;; near a, for every eps > 0, then g is differentiable at a with derivative L -- the
;;; converse of caratheodory-remainder-small.  The proof is cc-diff-on-local-quadratic's
;;; (goursat.scm; the Caratheodory factor as an IF term), with the continuity of the factor
;;; read off the bound at eps itself; cc-diff-on-local-quadratic is the instance
;;; eps -> delta = min(r, eps / M).
;;; ======================================================================
(define gxd-sub '(SUBSPACE-MS (NF-METRIC-SPACE CC-NORMED-FIELD) goxs_))
(define (gxd-dq v) (list '* (list '- (list 'goxg_ v) '(goxg_ goxa_)) (list 'recip (list '- v 'goxa_))))
(define (gxd-ift v) (list 'IF (list '= v 'goxa_) 'goxl_ (gxd-dq v)))
(define gxd-phi (list 'VNB-LAMBDA 'goxv_ 'goxs_ (gxd-ift 'goxv_)))
(define (gxd-err x) (list '- (list '- (list 'goxg_ x) '(goxg_ goxa_)) (list '* (list '- x 'goxa_) 'goxl_)))
(define gxd-eb
  (list 'FORALL 'goxe_ (list 'IMPLIES '(POS-RR goxe_)
    (list 'FORSOME 'goxd_ (list 'AND '(POS-RR goxd_)
      (list 'FORALL 'goxy_ (list 'IMPLIES '(IN goxy_ goxs_)
        (list 'IMPLIES '(< (magnitude (- goxy_ goxa_)) goxd_)
          (list '<= (list 'magnitude (gxd-err 'goxy_)) '(* goxe_ (magnitude (- goxy_ goxa_))))))))))))

;;; An IF term on the side the context decides: the kit's (dk-if-branch! TRUE? IFT #f K).


;;; v in U  ==>  v in CC, f(v) in CC
(define (gxd-qd-pt! v)
  (fact 'subset-mem-fwd 'goxs_ 'CC v)
  (fact 'fun-apply-type-c 'goxg_ 'goxs_ 'CC v))

;;; NOT(v = a)  ==>  NOT(v - a = 0), recip(v - a) in CC, (v - a) recip(v - a) = 1
(define (gxd-qd-nz! v)
  (let ((d (list '- v 'goxa_)))
    (gox-cc! d)
    (dk-have! (list 'NOT (list '= d 0))
      (lambda ()
        (di)
        (dk-have! (list '= v 'goxa_)
          (lambda ()
            (dk-have! (list '= v (list '+ d 'goxa_)) (lambda () (crs)))
            (subst (list '= v (list '+ d 'goxa_)))
            (subst (list '= d 0))
            (crs)))
        (ai (list 'NOT (list '= v 'goxa_)))))
    (gox-and! (list 'IN d 'CC) (list 'NOT (list '= d 0)))
    (fact 'cc-recip-closed d)
    (fact 'cc-recip-inverse d)
    (gox-cc! (gxd-dq v))))

(sp (make-wff
  (list 'FORALL 'goxs_ (list 'IMPLIES (list 'IS-OPEN gox-nfm 'goxs_)
    (list 'FORALL 'goxg_ (list 'IMPLIES '(IN goxg_ (FUN goxs_ CC))
      (list 'FORALL 'goxa_ (list 'IMPLIES '(IN goxa_ goxs_)
        (list 'FORALL 'goxl_ (list 'IMPLIES '(IN goxl_ CC)
          (list 'IMPLIES gxd-eb '(IS-DIFF-ON CC-NORMED-FIELD goxs_ goxg_ goxa_ goxl_))))))))))))
(dk-peel!)
(fact 'cc-is-normed-field)
(fact 'nf-cc-is-metric-space)
(fact 'nf-metric-carrier 'CC-NORMED-FIELD)
(fact 'cc-nf-carr)
(dk-have! (list '== (list 'PTS gox-nfm) 'CC)
  (lambda () (subst (list '== (list 'PTS gox-nfm) '(CARR CC-NORMED-FIELD))) (ass)))
(dk-have! (list 'SUBSET 'goxs_ (list 'PTS gox-nfm))
  (lambda () (mac-h 'is-open (list 'IS-OPEN gox-nfm 'goxs_)) (dk-split-all!) (ass)))
(dk-have! '(SUBSET goxs_ CC) (lambda () (subst (list '== 'CC (list 'PTS gox-nfm))) (ass)))
(fact 'nf-open-is-set 'CC-NORMED-FIELD 'goxs_)
(fact 'subspace-is-metric-space gox-nfm 'goxs_)
(fact 'subspace-pts gox-nfm 'goxs_)
(gox-pts-cc!)
(gxd-qd-pt! 'goxa_)
;; the factor is a function U -> CC
(define gxd-qd-pt
  (list 'FORALL 'goxv_ (list 'IMPLIES '(IN goxv_ goxs_) (list 'IN (gxd-ift 'goxv_) 'CC))))
(dk-have! gxd-qd-pt
  (lambda ()
    (let ((v (dk-di-var!)))
      (gxd-qd-pt! v)
      (use-em (list '= v 'goxa_)
        (lambda () (dk-if-branch! #t (gxd-ift v) #f (lambda () (ass))))
        (lambda () (gxd-qd-nz! v) (dk-if-branch! #f (gxd-ift v) #f (lambda () (ass))))))))
(dk-have! (list 'IN gxd-phi '(FUN goxs_ CC))
  (lambda ()
    (for-each
     (lambda (leaf)
       (dk-focus! leaf)
       (let ((g (dk-goal)))
         (cond ((equal? g '(IN goxs_ SET)) (ass))
               ((eq? (gox-hd g) 'FORALL)
                (let ((v (dk-di-var!))) (inst+ gxd-qd-pt v) (ass)))
               (#t (error "gxd: unexpected lam-t leaf" (expression->string g))))))
     (dk-opened (lambda () (lam-t))))))
(dk-have! (list 'IN gxd-phi '(FUN goxs_ (CARR CC-NORMED-FIELD)))
  (lambda () (subst '(== (CARR CC-NORMED-FIELD) CC)) (ass)))
(dk-have! '(IN goxg_ (FUN goxs_ (CARR CC-NORMED-FIELD)))
  (lambda () (subst '(== (CARR CC-NORMED-FIELD) CC)) (ass)))
(dk-have! '(IN goxl_ (CARR CC-NORMED-FIELD))
  (lambda () (subst '(== (CARR CC-NORMED-FIELD) CC)) (ass)))
;; phi(a) = L
(define gxd-qd-pa (list '= (list gxd-phi 'goxa_) 'goxl_))
(dk-have! gxd-qd-pa
  (lambda ()
    (dk-lam-b!)
    (for-each
     (lambda (leaf)
       (dk-focus! leaf)
       (if (dk-contains? (dk-goal) (gxd-ift 'goxa_))
           (begin (subst (list '= (gxd-ift 'goxa_) 'goxl_)) (rfl))
           (rfl)))
     (dk-opened (lambda () (if-true (gxd-ift 'goxa_)))))))
;; continuity of phi at a
(fact 'cc-magnitude-closed 'goxl_)
(dk-have! (list 'IS-CONTINUOUS-AT gxd-sub gox-nfm gxd-phi 'goxa_)
  (lambda ()
    (mac 'is-continuous-at)
    (dk-conj-close!
     (lambda ()
       (let ((g (dk-goal)))
         (cond
          ((eq? (gox-hd g) 'FORALL)
           (let* ((ep (dk-peel!))
                  (eps (cadr (car (filter (dk-head? 'POS-RR) ep)))))
             (fact 'rr-pos-rr-in-rr eps)
             (fact 'rr-lt-of-pos-rr eps)
             (let* ((d1 (dk-skolem! (dk-apply! (dk-ctx-form gxd-eb) eps)))
                    (eb (dk-pick (lambda (fm) (and (gox-op? fm 'FORALL 3) (dk-contains? fm d1))) "the bound at eps")))
             (fact 'rr-pos-rr-in-rr d1)
             (fact 'rr-lt-of-pos-rr d1)
             (let ((gxd-go! (lambda (del)
             (ew del)
             (dk-conj-close!
              (lambda ()
                (if (not (eq? (gox-hd (dk-goal)) 'FORALL))
                    (ass)
                    (let* ((lk (dk-peel!))
                           (b (cadr (car (filter (dk-head? 'IN) lk))))
                           (dab (list 'magnitude (list '- 'goxa_ b)))
                           (dba (list 'magnitude (list '- b 'goxa_))))
                      (dk-have! (list 'IN b 'goxs_) (lambda () (subst (list '== 'goxs_ (list 'PTS gxd-sub))) (ass)))
                      (gxd-qd-pt! b)
                      (inst+ gxd-qd-pt b)
                      ;; the hypothesis dist(a, b) <= delta, read as |b - a| <= delta
                      (fact 'subspace-dist gox-nfm 'goxs_ 'goxa_ b)
                      (dk-have! (list 'IN 'goxa_ '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
                      (dk-have! (list 'IN b '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
                      (fact 'nf-cc-agree-dist 'goxa_ b)
                      (fact 'cc-ms-dist 'goxa_ b)
                      (gox-rr! dab) (gox-rr! dba)
                      (fact 'cc-magnitude-sub-sym 'goxa_ b)
                      (dk-have! (list '<= dba del)
                        (lambda ()
                          (subst (list '= dba dab))
                          (subst (list '== dab (list '(DIST CC-MS) 'goxa_ b)))
                          (subst (list '== (list '(DIST CC-MS) 'goxa_ b) (list (list 'DIST gox-nfm) 'goxa_ b)))
                          (subst (list '== (list (list 'DIST gox-nfm) 'goxa_ b) (list (list 'DIST gxd-sub) 'goxa_ b)))
                          (ass)))
                      ;; the goal, read as |L - phi(b)| <= eps
                      (subst gxd-qd-pa)
                      (dk-lam-b!)
                      (let ((pb (gxd-ift b)))
                        (dk-have! (list 'IN 'goxl_ '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
                        (dk-have! (list 'IN pb '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
                        (fact 'nf-cc-agree-dist 'goxl_ pb)
                        (fact 'cc-ms-dist 'goxl_ pb)
                        (subst (list '== (list (list 'DIST gox-nfm) 'goxl_ pb) (list '(DIST CC-MS) 'goxl_ pb)))
                        (subst (list '== (list '(DIST CC-MS) 'goxl_ pb) (list 'magnitude (list '- 'goxl_ pb))))
                        (use-em (list '= b 'goxa_)
                          (lambda ()
                            (dk-if-branch! #t pb #f (lambda ()
                                (dk-have! '(= (- goxl_ goxl_) 0) (lambda () (crs)))
                                (subst '(= (- goxl_ goxl_) 0))
                                (fact 'cc-magnitude-zero)
                                (subst '(= (magnitude 0) 0))
                                (dk-ineq! (list '< 0 eps)))))
                          (lambda ()
                            (gxd-qd-nz! b)
                            (dk-if-branch! #f pb #f (lambda ()
                                (let* ((q (gxd-dq b)) (lq (list '- 'goxl_ q)) (d (list '- b 'goxa_))
                                       (e (gxd-err b)) (mlq (list 'magnitude lq)))
                                  (for-each gox-cc! (list q lq e))
                                  (gox-rr! mlq)
                                  (gox-rr! (list 'magnitude e))
                                  ;; (L - Q)(b - a) = -(f(b) - f(a) - (b - a) L)
                                  (dk-have! (list '= (list '* lq d) (list '- e))
                                    (lambda ()
                                      (let ((ex (list '- (list '* 'goxl_ d)
                                                         (list '* (list '- (list 'goxg_ b) '(goxg_ goxa_))
                                                                  (list '* d (list 'recip d))))))
                                        (dk-have! (list '= (list '* lq d) ex) (lambda () (crs)))
                                        (subst (list '= (list '* lq d) ex))
                                        (subst (list '= (list '* d (list 'recip d)) 1))
                                        (crs))))
                                  (gox-and! (list 'IN lq 'CC) (list 'IN d 'CC))
                                  (fact 'cc-magnitude-mul lq d)
                                  (fact 'cc-magnitude-neg e)
                                  (dk-have! (list '< dba d1)
                                    (lambda () (dk-ineq! (list 'IN dba 'RR) (list 'IN del 'RR) (list 'IN d1 'RR)
                                                         (list '<= dba del) (list '< del d1))))
                                  (dk-apply! eb b)
                                  (gox-rr! (list '* mlq dba))
                                  (gox-rr! (list '* eps dba))
                                  (dk-have! (list '<= (list '* mlq dba) (list '* eps dba))
                                    (lambda ()
                                      (dk-have! (list '= (list '* mlq dba) (list 'magnitude e))
                                        (lambda ()
                                          (subst (list '= (list '* mlq dba) (list 'magnitude (list '* lq d))))
                                          (subst (list '= (list '* lq d) (list '- e)))
                                          (subst (list '= (list 'magnitude (list '- e)) (list 'magnitude e)))
                                          (rfl)))
                                      (dk-ineq! (list '= (list '* mlq dba) (list 'magnitude e))
                                                (list '<= (list 'magnitude e) (list '* eps dba)))))
                                  ;; |b - a| > 0: cancel it
                                  (fact 'cc-magnitude-nonneg d)
                                  (fact 'cc-magnitude-zero-iff d)
                                  (dk-have! (list 'NOT (list '= dba 0))
                                    (lambda ()
                                      (if (dk-only! (list 'IFF (list '= dba 0) (list '= d 0)) (list 'NOT (list '= d 0)))
                                          (prop))))
                                  (fact 'neq-sym dba 0)
                                  (gox-and! (list '<= 0 dba) (list 'NOT (list '= 0 dba)))
                                  (fact 'rr-le-ne-lt 0 dba)
                                  (fact 'rr-mul-le-cancel-pos mlq dba eps)
                                  (ass))))))))))))))
               (let ((del1 (list '* 1/2 d1)))
                 (gox-rr! del1)
                 (dk-have! (list '< 0 del1) (lambda () (dk-ineq! (list 'IN d1 'RR) (list '< 0 d1))))
                 (gox-pos-rr! del1)
                 (fact 'rr-lt-implies-le 0 del1)
                 (dk-have! (list '< del1 d1) (lambda () (dk-ineq! (list 'IN d1 'RR) (list '< 0 d1))))
                 (gxd-go! del1))))))
          ((eq? (gox-hd g) 'IN)
           (cond ((dk-asm? g) (ass))
                 ((equal? g (list 'IN 'goxa_ (list 'PTS gxd-sub)))
                  (subst (list '== (list 'PTS gxd-sub) 'goxs_)) (ass))
                 (#t (subst (list '== (list 'PTS gxd-sub) 'goxs_))
                     (subst (list '== (list 'PTS gox-nfm) 'CC))
                     (ass))))
          (#t (ass))))))))
;; the definition
(mac 'IS-DIFF-ON)
(dk-conj-close!
 (lambda ()
   (let ((g (dk-goal)))
     (cond
      ((eq? (gox-hd g) 'FORSOME)
       (ew gxd-phi)
       (dk-conj-close!
        (lambda ()
          (if (not (eq? (gox-hd (dk-goal)) 'FORALL))
              (ass)
              (let* ((x (dk-di-var!)) (d (list '- x 'goxa_)) (px (gxd-ift x))
                     (fd (list '- (list 'goxg_ x) '(goxg_ goxa_))))
                (gxd-qd-pt! x)
                (inst+ gxd-qd-pt x)
                (dk-lam-b!)
                (gox-cc! d) (gox-cc! fd)
                (fact 'cc-nf-sub (list 'goxg_ x) '(goxg_ goxa_))
                (fact 'cc-nf-sub x 'goxa_)
                (subst (list '== (list '(ADD CC-NORMED-FIELD) (list 'goxg_ x) '((NEG CC-NORMED-FIELD) (goxg_ goxa_))) fd))
                (subst (list '== (list '(ADD CC-NORMED-FIELD) x '((NEG CC-NORMED-FIELD) goxa_)) d))
                (gox-and! (list 'IN px 'CC) (list 'IN d 'CC))
                (fact 'cc-nf-mul-apply px d)
                (subst (list '== (list '(MUL CC-NORMED-FIELD) px d) (list '* px d)))
                (use-em (list '= x 'goxa_)
                  (lambda ()
                    (dk-if-branch! #t px #f (lambda ()
                        (subst (list '= x 'goxa_))
                        (crs))))
                  (lambda ()
                    (gxd-qd-nz! x)
                    (dk-if-branch! #f px #f (lambda ()
                        (let ((ex (list '* fd (list '* d (list 'recip d)))))
                          (dk-have! (list '= (list '* (gxd-dq x) d) ex) (lambda () (crs)))
                          (subst (list '= (list '* (gxd-dq x) d) ex))
                          (subst (list '= (list '* d (list 'recip d)) 1))
                          (crs)))))))))))
      (#t (ass))))))
(qed 'cc-diff-on-of-eps-bound)

;;; f continuous at every point of u, g = f + k with k a constant: g continuous at every point
(sp (make-wff
  (list 'FORALL 'u (list 'IMPLIES '(SUBSET u CC)
   (list 'FORALL 'f (list 'IMPLIES '(IN f (FUN u CC))
    (list 'FORALL 'goxg_ (list 'IMPLIES '(IN goxg_ (FUN u CC))
     (list 'FORALL 'goxk_ (list 'IMPLIES '(IN goxk_ CC)
      (list 'IMPLIES '(FORALL goxz_ (IMPLIES (IN goxz_ u) (== (goxg_ goxz_) (+ (f goxz_) goxk_))))
       (list 'IMPLIES (gox-cont 'u 'f) (gox-cont 'u 'goxg_)))))))))))))
(dk-peel!)
(fact 'nf-cc-is-metric-space)
(let* ((S (list 'SUBSPACE-MS gox-nfm 'u))
       (y (list-ref (dk-goal) 4))
       (vals (dk-pick (lambda (fm) (and (gox-op? fm 'FORALL 3) (dk-contains? fm 'goxk_))) "the values of g"))
       (cf (dk-apply! (dk-ctx-form (gox-cont 'u 'f)) y))
       (iff (dk-cite! 'is-continuous-at S gox-nfm 'f y))
       (conj (caddr iff)))
  (dk-have! conj (lambda () (if (dk-only! iff cf) (prop))))
  (dk-split-all! (list conj))
  (fact 'cc-is-metric-space)
  (gox-pts-cc!)
  (fact 'nf-metric-carrier 'CC-NORMED-FIELD)
  (fact 'cc-nf-carr)
  (dk-have! (list '== (list 'PTS gox-nfm) 'CC)
    (lambda () (subst (list '== (list 'PTS gox-nfm) '(CARR CC-NORMED-FIELD))) (ass)))
  (fact 'subspace-pts gox-nfm 'u)
  (let ((edf (let loop ((r conj)) (if (eq? (car r) 'AND) (loop (caddr r)) r))))
    (mac 'is-continuous-at)
    (dk-conj-close!
     (lambda ()
       (let ((g (dk-goal)))
         (cond
          ((dk-asm? g) (ass))
          ((eq? (gox-hd g) 'IN)
           (subst (list '== (list 'PTS S) 'u))
           (subst (list '== (list 'PTS gox-nfm) 'CC))
           (ass))
          ((eq? (gox-hd g) 'FORALL)
           (let* ((eps (cadr (car (filter (dk-head? 'POS-RR) (dk-peel!)))))
                  (del (dk-skolem! (dk-apply! edf eps)))
                  (ub (dk-pick (lambda (fm) (and (gox-op? fm 'FORALL 3) (dk-contains? fm del))) "the bound for f")))
             (ew del)
             (dk-conj-close!
              (lambda ()
                (if (not (eq? (gox-hd (dk-goal)) 'FORALL))
                    (ass)
                    (let* ((lk (dk-peel!))
                           (b (cadr (car (filter (dk-head? 'IN) lk))))
                           (fy (list 'f y)) (fb (list 'f b)) (gy (list 'goxg_ y)) (gb (list 'goxg_ b))
                           (ds (lambda (p q) (list (list 'DIST gox-nfm) p q)))
                           (dc (lambda (p q) (list '(DIST CC-MS) p q)))
                           (mg (lambda (p q) (list 'magnitude (list '- p q)))))
                      (dk-apply! ub b)
                      (dk-have! (list 'IN b 'u) (lambda () (subst (list '== 'u (list 'PTS S))) (ass)))
                      (for-each (lambda (p) (fact 'fun-apply-type-c 'f 'u 'CC p) (fact 'fun-apply-type-c 'goxg_ 'u 'CC p)) (list y b))
                      (for-each (lambda (p) (dk-have! (list 'IN p '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass))))
                                (list fy fb gy gb))
                      (for-each (lambda (pq) (fact 'nf-cc-agree-dist (car pq) (cadr pq)) (fact 'cc-ms-dist (car pq) (cadr pq)))
                                (list (list fy fb) (list gy gb)))
                      (dk-apply! vals y)
                      (dk-apply! vals b)
                      (gox-cc! (list '- fy fb))
                      (gox-cc! (list '+ fy 'goxk_)) (gox-cc! (list '+ fb 'goxk_))
                      (gox-cc! (list '- (list '+ fy 'goxk_) (list '+ fb 'goxk_)))
                      (subst (list '== (ds gy gb) (dc gy gb)))
                      (subst (list '== (dc gy gb) (mg gy gb)))
                      (subst (list '== gy (list '+ fy 'goxk_)))
                      (subst (list '== gb (list '+ fb 'goxk_)))
                      (dk-have! (list '= (list '- (list '+ fy 'goxk_) (list '+ fb 'goxk_)) (list '- fy fb)) (lambda () (crs)))
                      (subst (list '= (list '- (list '+ fy 'goxk_) (list '+ fb 'goxk_)) (list '- fy fb)))
                      (subst (list '= (mg fy fb) (dc fy fb)))
                      (subst (list '= (dc fy fb) (ds fy fb)))
                      (ass)))))))
          (#t (error "cc-continuous-at-add-const: unexpected leaf" (expression->string g)))))))))
(qed 'cc-continuous-at-add-const)

;;; ======================================================================
;;; (G) COROLLARY 3.7, PROPOSITION 3.8, COROLLARY 3.9 on a convex open set
;;; ======================================================================
(define (gox-under-CE body)
  (list 'FORALL 'u (list 'FORALL 'f (list 'FORALL 'goxx_ (list 'IMPLIES '(IS-CONVEX u) (gox-imps gox-E body))))))

;;; COROLLARY 3.7
(sp (make-wff (gox-under-CE (gox-all-in '(goxa_ goxb_ goxc_) 'u
  '(= (SEG-INT f goxa_ goxc_) (+ (SEG-INT f goxa_ goxb_) (SEG-INT f goxb_ goxc_)))))))
(dk-peel!)
(gox-E-setup!)
(for-each (lambda (v) (fact 'subset-mem-fwd 'u 'CC v)) '(goxa_ goxb_ goxc_))
(dk-cite! 'conv3-in-convex 'u 'goxa_ 'goxb_ 'goxc_)
(dk-cite! 'goursat-triangle-except 'u 'f 'goxx_ 'goxa_ 'goxb_ 'goxc_)
(for-each (lambda (pq) (dk-cite! 'seg-trace-in-convex 'u (car pq) (cadr pq)) (dk-cite! 'seg-int-in-cc 'u 'f (car pq) (cadr pq)))
          '((goxa_ goxb_) (goxb_ goxc_) (goxc_ goxa_) (goxa_ goxc_)))
(let* ((sab '(SEG-INT f goxa_ goxb_)) (sbc '(SEG-INT f goxb_ goxc_)) (sca '(SEG-INT f goxc_ goxa_))
       (s3 (list '+ (list '+ sab sbc) sca))
       (rv (dk-cite! 'seg-int-reverse-at 'u 'f 'goxa_ 'goxc_)))
  (dk-cite! 'tri-int-unfold 'f 'goxa_ 'goxb_ 'goxc_)
  (gox-cc! s3)
  (dk-have! (list '= s3 0) (lambda () (subst (list '= s3 '(TRI-INT f goxa_ goxb_ goxc_))) (ass)))
  (dk-have! (list '= (list '+ sab sbc) (list '- s3 sca)) (lambda () (crs)))
  (subst (list '= (list '+ sab sbc) (list '- s3 sca)))
  (subst (list '= s3 0))
  (subst rv)
  (crs))
(qed 'cauchy-convex-segments-except)

;;; PROPOSITION 3.8, for a given base point o in u: g(b) = int_<o, b> f is a primitive.
;;; The derivative at z uses only the CONTINUITY of f at z (the notes' proof):
;;; |g(y) - g(z) - (y - z) f(z)| = |int_<z,y> (f - f(z))| <= |y - z| sup_<z,y> |f - f(z)|.
;;; In context: H(u, f), z in u, POS-RR(e).  Returns (del . claim), claim =
;;; forall w in u, |w - z| <= del => |f(w) - f(z)| <= e.
(define (gox-cont-mag! z e)
  (let* ((S (list 'SUBSPACE-MS gox-nfm 'u))
         (mg (lambda (p) (list 'magnitude p)))
         (fz (list 'f z))
         (cz (dk-apply! (dk-ctx-form (gox-cont 'u 'f)) z))
         (iff (dk-cite! 'is-continuous-at S gox-nfm 'f z))
         (edf (let loop ((r (caddr iff))) (if (eq? (car r) 'AND) (loop (caddr r)) r))))
    (dk-have! edf (lambda () (if (dk-only! iff cz) (prop))))
    (let* ((del (dk-skolem! (dk-apply! edf e)))
           (ub (dk-pick (lambda (fm) (and (gox-op? fm 'FORALL 3) (dk-contains? fm del))) "the continuity bound"))
           (claim (list 'FORALL 'goxcw_ (list 'IMPLIES '(IN goxcw_ u)
                    (list 'IMPLIES (list '<= (list 'magnitude (list '- 'goxcw_ z)) del)
                                   (list '<= (list 'magnitude (list '- '(f goxcw_) fz)) e))))))
      (fact 'rr-pos-rr-in-rr del)
      (fact 'rr-lt-of-pos-rr del)
      (fact 'subspace-pts gox-nfm 'u)
      (fact 'cc-is-metric-space)
      (gox-pts-cc!)
      (dk-have! claim
        (lambda ()
          (let* ((w (dk-di-var!)) (fw (list 'f w)))
            (di)
            (fact 'subset-mem-fwd 'u 'CC w)
            (fact 'fun-apply-type-c 'f 'u 'CC w)
            (fact 'fun-apply-type-c 'f 'u 'CC z)
            (dk-have! (list 'IN w (list 'PTS S)) (lambda () (subst (list '== (list 'PTS S) 'u)) (ass)))
            (for-each (lambda (pp) (dk-have! (list 'IN pp '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass))))
                      (list z w fz fw))
            (fact 'subspace-dist gox-nfm 'u z w)
            (fact 'nf-cc-agree-dist z w)
            (fact 'cc-ms-dist z w)
            (gox-cc! (list '- z w)) (gox-rr! (mg (list '- z w)))
            (gox-cc! (list '- w z)) (gox-rr! (mg (list '- w z)))
            (dk-cite! 'cc-magnitude-sub-sym z w)
            (dk-have! (list '<= (list (list 'DIST S) z w) del)
              (lambda ()
                (subst (list '== (list (list 'DIST S) z w) (list (list 'DIST gox-nfm) z w)))
                (subst (list '== (list (list 'DIST gox-nfm) z w) (list '(DIST CC-MS) z w)))
                (subst (list '== (list '(DIST CC-MS) z w) (mg (list '- z w))))
                (subst (list '= (mg (list '- z w)) (mg (list '- w z))))
                (ass)))
            (dk-apply! ub w)
            (fact 'nf-cc-agree-dist fz fw)
            (fact 'cc-ms-dist fz fw)
            (gox-cc! (list '- fz fw)) (gox-rr! (mg (list '- fz fw)))
            (gox-cc! (list '- fw fz)) (gox-rr! (mg (list '- fw fz)))
            (dk-cite! 'cc-magnitude-sub-sym fw fz)
            (subst (list '= (mg (list '- fw fz)) (mg (list '- fz fw))))
            (subst (list '== (mg (list '- fz fw)) (list '(DIST CC-MS) fz fw)))
            (subst (list '== (list '(DIST CC-MS) fz fw) (list (list 'DIST gox-nfm) fz fw)))
            (ass))))
      (cons del claim))))

(sp (make-wff (gox-under-CE
  '(FORALL goxo_ (IMPLIES (IN goxo_ u)
     (FORSOME goxg_ (AND (IN goxg_ (FUN u CC)) (AND (HOLOMORPHIC-ON u goxg_)
       (FORALL goxz_ (IMPLIES (IN goxz_ u) (IS-DIFF-ON CC-NORMED-FIELD u goxg_ goxz_ (f goxz_))))))))))))
(dk-peel!)
(gox-E-setup!)
(fact 'cc-is-normed-field)
(fact 'nf-open-is-set 'CC-NORMED-FIELD 'u)
(fact 'subset-mem-fwd 'u 'CC 'goxo_)
(define gox-pr-G (list 'VNB-LAMBDA 'goxpb_ 'u '(SEG-INT f goxo_ goxpb_)))
(define (gox-pr-seg! b)   ;; b in u: b in CC, the segment from o to b in u, its integral in CC
  (fact 'subset-mem-fwd 'u 'CC b)
  (dk-cite! 'seg-trace-in-convex 'u 'goxo_ b)
  (dk-cite! 'seg-int-in-cc 'u 'f 'goxo_ b))
(dk-have! (list 'IN gox-pr-G '(FUN u CC))
  (lambda () (dk-lam-type! (lambda () (let ((b (dk-di-var!))) (gox-pr-seg! b) (ass))))))
(define gox-pr-val
  (list 'FORALL 'goxz_ (list 'IMPLIES '(IN goxz_ u) (list '== (list gox-pr-G 'goxz_) '(SEG-INT f goxo_ goxz_)))))
(dk-have! gox-pr-val
  (lambda () (let ((b (dk-di-var!))) (gox-pr-seg! b) (if (not (dk-lam-b!)) (qrfl)))))
;; the derivative at every point
(define gox-pr-d
  (list 'FORALL 'goxpz_ (list 'IMPLIES '(IN goxpz_ u) (list 'IS-DIFF-ON 'CC-NORMED-FIELD 'u gox-pr-G 'goxpz_ '(f goxpz_)))))
(dk-have! gox-pr-d
  (lambda ()
    (let* ((z (dk-di-var!))
           (fz (list 'f z))
           (k  (list 'VNB-LAMBDA 'goxpv_ 'u (list '+ fz (list '* 0 (list '- 'goxpv_ z)))))
           (h  (list 'VNB-LAMBDA 'goxpv_ 'u (list '+ '(f goxpv_) (list '- fz))))
           (mg (lambda (p) (list 'magnitude p))))
      (gox-pr-seg! z)
      (fact 'fun-apply-type-c 'f 'u 'CC z)
      (gox-cc! (list '- fz))
      (gox-cc! 0)
      ;; k, h = f - f(z) as functions on u; k holomorphic, h continuous
      (for-each
       (lambda (lam)
         (dk-have! (list 'IN lam '(FUN u CC))
           (lambda ()
             (dk-lam-type!
               (lambda ()
                 (let ((y (dk-di-var!)))
                   (fact 'subset-mem-fwd 'u 'CC y)
                   (fact 'fun-apply-type-c 'f 'u 'CC y)
                   (gox-cc! (subst-free 'goxpv_ y (list-ref lam 3)))
                   (ass)))))))
       (list k h))
      (for-each
       (lambda (lam)
         (dk-have! (list 'FORALL 'goxz_ (list 'IMPLIES '(IN goxz_ u) (list '== (list lam 'goxz_) (subst-free 'goxpv_ 'goxz_ (list-ref lam 3)))))
           (lambda ()
             (let ((y (dk-di-var!)))
               (fact 'subset-mem-fwd 'u 'CC y)
               (fact 'fun-apply-type-c 'f 'u 'CC y)
               (gox-cc! (subst-free 'goxpv_ y (list-ref lam 3)))
               (if (not (dk-lam-b!)) (qrfl))))))
       (list k h))
      (dk-cite! 'affine-holomorphic 'u fz 0 z k)
      (dk-cite! 'holomorphic-on-continuous 'u k)
      (dk-cite! 'cc-continuous-at-add-const 'u 'f h (list '- fz))
      (dk-have! (list 'FORALL 'goxz_ (list 'IMPLIES '(IN goxz_ u) (list '== '(f goxz_) (list '+ (list h 'goxz_) (list k 'goxz_)))))
        (lambda ()
          (let* ((y (dk-di-var!)) (fy (list 'f y)))
            (fact 'subset-mem-fwd 'u 'CC y)
            (fact 'fun-apply-type-c 'f 'u 'CC y)
            (gox-cc! (subst-free 'goxpv_ y (list-ref k 3)))
            (gox-cc! (subst-free 'goxpv_ y (list-ref h 3)))
            (dk-lam-b!)
            (let ((rhs (caddr (dk-goal))))
              (dk-have! (list '= rhs fy) (lambda () (crs)))
              (subst (list '= rhs fy))
              (qrfl)))))
      ;; the little-o bound at z, from the continuity of f at z
      (dk-have! (list 'FORALL 'goxe_ (list 'IMPLIES '(POS-RR goxe_)
                  (list 'FORSOME 'goxd_ (list 'AND '(POS-RR goxd_)
                    (list 'FORALL 'goxy_ (list 'IMPLIES '(IN goxy_ u)
                      (list 'IMPLIES (list '< (list 'magnitude (list '- 'goxy_ z)) 'goxd_)
                        (list '<= (list 'magnitude (list '- (list '- (list gox-pr-G 'goxy_) (list gox-pr-G z)) (list '* (list '- 'goxy_ z) fz)))
                                  (list '* 'goxe_ (list 'magnitude (list '- 'goxy_ z)))))))))))
        (lambda ()
          (let* ((e (cadr (car (filter (dk-head? 'POS-RR) (dk-peel!)))))
                 (dc (begin (fact 'rr-pos-rr-in-rr e) (fact 'rr-lt-of-pos-rr e) (gox-cont-mag! z e)))
                 (del (car dc)) (cb (cdr dc)))
            (ew del)
            (dk-conj-close!
              (lambda ()
                (if (not (eq? (gox-hd (dk-goal)) 'FORALL))
                    (ass)
                    (let* ((ls (dk-peel!))
                           (x (cadr (find-first (lambda (fm) (and (gox-op? fm 'IN 3) (eq? (caddr fm) 'u))) ls)))
                           (dx (mg (list '- x z)))
                           (hb (list 'FORALL 'goxcy_ (list 'IMPLIES (list 'IN 'goxcy_ (gox-segtr z x))
                                 (list '<= (list 'magnitude (list h 'goxcy_)) e)))))
                      (gox-pr-seg! x)
                      (dk-cite! 'seg-trace-in-convex 'u z x)
                      (dk-cite! 'seg-int-in-cc 'u 'f z x)
                      (subst (dk-apply! (dk-ctx-form gox-pr-val) x))
                      (subst (dk-apply! (dk-ctx-form gox-pr-val) z))
                      (subst (dk-cite! 'cauchy-convex-segments-except 'u 'f 'goxx_ 'goxo_ z x))
                      (subst (dk-cite! 'seg-int-sum 'u h k 'f z x))
                      (subst (dk-cite! 'seg-int-const 'u fz z k z x))
                      (dk-cite! 'seg-int-in-cc 'u h z x)
                      (dk-cite! 'seg-int-in-cc 'u k z x)
                      (let* ((shx (list 'SEG-INT h z x))
                             (lhs (cadr (cadr (dk-goal)))))
                        (gox-cc! lhs)
                        (dk-have! (list '= lhs shx) (lambda () (crs)))
                        (subst (list '= lhs shx))
                        (gox-cc! (list '- x z)) (gox-rr! dx)
                        (fact 'cc-magnitude-nonneg (list '- x z))
                        ;; |h| <= e on the segment from z to x
                        (dk-have! hb
                          (lambda ()
                            (let* ((y (dk-di-var!))
                                   (tt (dk-skolem! (dk-cite! 'seg-trace-elim z x y)))
                                   (dy (list '- y z)) (mdy (mg dy)))
                              (gox-unit! tt)
                              (fact 'subset-mem-fwd (gox-segtr z x) 'u y)
                              (fact 'subset-mem-fwd 'u 'CC y)
                              (fact 'fun-apply-type-c 'f 'u 'CC y)
                              (gox-cc! dy) (gox-rr! mdy)
                              (dk-have! (list '= dy (list '* tt (list '- x z)))
                                (lambda () (subst (list '= y (list '+ z (list '* tt (list '- x z))))) (crs)))
                              (gox-scaled-mag! tt dy (list '- x z))
                              (gox-and! (list '<= tt 1) (list '<= 0 dx))
                              (fact 'rr-mul-le-right tt 1 dx)
                              (gox-rr! (list '* 1 dx))
                              (dk-have! (list '<= mdy del)
                                (lambda () (dk-ineq! (list 'IN mdy 'RR) (list 'IN (list '* tt dx) 'RR) (list 'IN dx 'RR)
                                                     (list 'IN del 'RR)
                                                     (list '= mdy (list '* tt dx)) (list '<= (list '* tt dx) (list '* 1 dx))
                                                     (list '< dx del))))
                              (dk-apply! cb y)
                              (dk-lam-b!)
                              (let ((fy (list 'f y)))
                                (gox-cc! (list '+ fy (list '- fz))) (gox-cc! (list '- fy fz))
                                (dk-have! (list '= (list '+ fy (list '- fz)) (list '- fy fz)) (lambda () (crs)))
                                (subst (list '= (list '+ fy (list '- fz)) (list '- fy fz)))
                                (ass)))))
                        (dk-apply! (dk-cite! 'seg-int-abs-bound 'u h z x) e)
                        (gox-rr! (list '* dx e))
                        (gox-rr! (list '* e dx))
                        (gox-rr! (mg shx))
                        (dk-have! (list '= (list '* dx e) (list '* e dx)) (lambda () (crs)))
                        (dk-ineq! (list 'IN (mg shx) 'RR) (list 'IN (list '* dx e) 'RR) (list 'IN (list '* e dx) 'RR)
                                  (list '<= (mg shx) (list '* dx e)) (list '= (list '* dx e) (list '* e dx)))))))))))
      (dk-cite! 'cc-diff-on-of-eps-bound 'u gox-pr-G z fz)
      (ass))))
(ew gox-pr-G)
(dk-conj-close!
  (lambda ()
    (let ((g (dk-goal)))
      (cond ((dk-asm? g) (ass))
            ((dk-head-is? g 'HOLOMORPHIC-ON)
             (mac 'HOLOMORPHIC-ON)
             (dk-conj-close!
               (lambda ()
                 (if (not (dk-head-is? (dk-goal) 'FORALL))
                     (ass)
                     (let ((a (dk-di-var!)))
                       (dk-apply! (dk-ctx-form gox-pr-d) a)
                       (ew (list 'f a))
                       (ass))))))
            (#t (error "cauchy-convex-primitive-except: unexpected leaf" (expression->string g)))))))
(qed 'cauchy-convex-primitive-except)

;;; COROLLARY 3.9
(sp (make-wff (gox-under-CE
  '(FORALL pgam (FORALL dgam (FORALL a (FORALL b
    (IMPLIES (IS-ROAD pgam dgam a b) (IMPLIES (SUBSET (TRACE pgam a b) u)
      (IMPLIES (= (pgam b) (pgam a)) (= (LINE-INT f pgam dgam a b) 0)))))))))))
(dk-peel!)
(gox-E-setup!)
(fact 'is-road-is-path 'pgam 'dgam 'a 'b)
(fact 'is-path-in-fun 'pgam 'a 'b)
(dk-split-all! (list (dk-cite! 'is-path-endpoints 'pgam 'a 'b)))
(dk-have! '(IN a (CCINT a b))
  (lambda ()
    (mac 'ccint-membership)
    (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (dk-ineq! '(IN a RR) '(IN b RR) '(< a b)))))))
(dk-cite! 'trace-value-in 'pgam 'a 'b 'a)
(fact 'subset-mem-fwd '(TRACE pgam a b) 'u '(pgam a))
(define gox-cc-g (dk-skolem! (dk-cite! 'cauchy-convex-primitive-except 'u 'f 'goxx_ '(pgam a))))
(dk-cite! 'line-int-closed-road-of-derivative 'u gox-cc-g 'f 'pgam 'dgam 'a 'b)
(ass)
(qed 'cauchy-convex-closed-except)
