;;; morera.scm -- MORERA'S THEOREM AND LOCALLY UNIFORM LIMITS OF HOLOMORPHIC FUNCTIONS
;;; (complex-analysis.pdf 3.6: Proposition 3.43, Proposition 3.44), both CONDITIONAL on
;;; "the derivative of a holomorphic function is holomorphic" (Corollary 3.37).
;;; Agent CA-4 of week 2 of the October roadmap (scratchpad/triage/WEEK2.md), 2026-10-04.
;;;
;;; CONTENTS.
;;;  (1) diff-on-local                          differentiable at a on an open v inside u (of
;;;                                             RESTRICT(f, v)) => differentiable at a on u
;;;  (2) cauchy-convex-segments-of-triangles    Cor 3.7  } from vanishing triangle integrals on
;;;      cauchy-convex-primitive-of-triangles   Prop 3.8 } a convex open set: a holomorphic primitive
;;;  (3) morera-conditional                     Prop 3.43, hypothesis mrr-H (below)
;;;  (4) holomorphic-uniform-limit-conditional  Prop 3.44, hypothesis mrr-H, convergence LOCALLY
;;;                                             uniform (each point has a disc in u on which it
;;;                                             is uniform; on an open subset of CC this is the
;;;                                             notes' "uniformly on compact subsets")
;;;  (5) deriv-holomorphic-bridge               CA-3's statement => mrr-H
;;;      morera-of-deriv-holomorphic            (3) with CA-3's holomorphic-deriv-holomorphic,
;;;      holomorphic-uniform-limit-of-deriv-holomorphic   verbatim, as the hypothesis
;;;
;;; THE HYPOTHESES.  mrr-H (independent of any derivative operator):
;;;   forall v g dg. HOLOMORPHIC-ON(v, g) => dg in FUN(v, CC)
;;;        => (forall z in v. IS-DIFF-ON(CC-NORMED-FIELD, v, g, z, dg(z))) => HOLOMORPHIC-ON(v, dg)
;;; mrr-HCIF (CA-3's holomorphic-deriv-holomorphic, theorem-library/cauchy-integral-formula.scm):
;;;   forall u f. HOLOMORPHIC-ON(u, f)
;;;        => HOLOMORPHIC-ON(u, VNB-LAMBDA(cifdw_, u, DERIV-ON(CC-NORMED-FIELD, u, f, cifdw_)))
;;; The unconditional theorems are one detachment of mrr-HCIF from (5)'s two corollaries.
;;; THE TRIANGLE HYPOTHESIS of Morera is the notes' (84): every a, b, c in u with
;;; CONV3(a, b, c) inside u has TRI-INT(f, a, b, c) = 0.
;;; THE PROOF of (3), at a point a of u: a disc B about a inside u is convex; (2) gives a
;;; holomorphic primitive G of f on B; mrr-H makes f = G' holomorphic on B; (1) lifts the
;;; derivative at a from B to u.  (2) is goursat-exceptional.scm's proof of Cor 3.7 / Prop 3.8
;;; with the triangle hypothesis in place of Goursat (its gox- helpers copied as mrr-).
;;; THE PROOF of (4): the limit is continuous on u (eps/4 three times on the uniform disc), each
;;; triangle integral in the disc is the limit of the members' integrals (0 by Goursat, through
;;; line-int-of-uniform-limit over TRI-ROAD and cc-limit-unique), then the local step of (3).
;;;
;;; NOTHING asserted, no definition.  Helper prefix mrr-; binders mr*_ (none used elsewhere in
;;; the tree).  LOAD WINDOW: lo = theorem-library/analytic-from-integral (load.scm:3541;
;;; line-int-of-uniform-limit), above winding-number-laws (3540; cc-ball-is-convex), cc-exp-kernel,
;;; road-juxtaposition-laws (tri-road-*), goursat (goursat-triangle, seg-int-*), deriv-on-read-off
;;; (2948; cc-deriv-on-of-is-diff-on); hi: none.  Independent of cauchy-centre-mean-value.scm and
;;; of CA-3's files.  Tactics: the early kit only.

;;; ======================================================================
;;; local helpers (typers after winding-number-laws.scm's wnd-, copied)
;;; ======================================================================
(define (mrr-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (mrr-hd t) (and (pair? t) (car t)))
(define mrr-nfm '(NF-METRIC-SPACE CC-NORMED-FIELD))
(define (mrr-sub u) (list 'SUBSPACE-MS mrr-nfm u))
(define (mrr-cont u f)
  (list 'FORALL 'rgy_ (list 'IMPLIES (list 'IN 'rgy_ u)
    (list 'IS-CONTINUOUS-AT (mrr-sub u) mrr-nfm f 'rgy_))))
(define (mrr-imps hyps body)
  (if (null? hyps) body (list 'IMPLIES (car hyps) (mrr-imps (cdr hyps) body))))
(define (mrr-all vars body)
  (if (null? vars) body (list 'FORALL (car vars) (mrr-all (cdr vars) body))))
(define (mrr-and! a b)
  (let ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! dk-ass!))))
    f))
(define (mrr-rr! t)
  (let ((typ (list 'IN t 'RR)))
    (cond ((dk-asm? typ) typ)
          ((eq? t 'PI) (dk-split-all! (list (dk-cite! 'pi-pos))) typ)
          ((eqv? t 0) (fact 'rr-zero-in) typ)
          ((eqv? t 1) (fact 'rr-one-in) typ)
          ((mrr-op? t '* 3) (mrr-rr! (cadr t)) (mrr-rr! (caddr t)) (fact 'rr-mul-in-rr (cadr t) (caddr t)) typ)
          ((mrr-op? t 'magnitude 2) (mrr-cc! (cadr t)) (fact 'cc-magnitude-closed (cadr t)) typ)
          (#t (dk-type! t 'RR)))))
(define (mrr-cc! t)
  (let ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((mrr-op? t 'recip 2)
           (mrr-cc! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (error "mrr-cc!: land the non-vanishing first" (expression->string (cadr t))))
           (mrr-and! (list 'IN (cadr t) 'CC) (list 'NOT (list '= (cadr t) 0)))
           (fact 'cc-recip-closed (cadr t)) typ)
          ((mrr-op? t '* 3) (mrr-cc! (cadr t)) (mrr-cc! (caddr t))
           (mrr-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((mrr-op? t '+ 3) (mrr-cc! (cadr t)) (mrr-cc! (caddr t))
           (mrr-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((mrr-op? t '- 3) (mrr-cc! (cadr t)) (mrr-cc! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((mrr-op? t '- 2) (mrr-cc! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((eqv? t 1) (fact 'cc-one-in) typ)
          ((eqv? t +i) (fact 'cc-i-in) typ)
          ((mrr-op? t 'CC-EXP 2) (mrr-cc! (cadr t))
           (dk-split-all! (list (dk-cite! 'cc-exp-converges (cadr t)))) typ)
          ((or (eq? t 'PI) (and (number? t) (real? t)) (dk-asm? (list 'IN t 'RR))
               (mrr-op? t 'magnitude 2) (mrr-op? t 'real-part 2) (mrr-op? t 'imag-part 2))
           (mrr-rr! t) (fact 'rr-subset-cc t) typ)
          (#t (dk-type! t 'CC)))))
(define (mrr-pts-cc!)
  (if (not (dk-asm? '(== (PTS CC-MS) CC)))
      (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))))
;;; the metric facts on NFM and on the subspace u (u subset CC in context)
(define (mrr-ms! u)
  (fact 'nf-cc-is-metric-space)
  (fact 'nf-metric-carrier 'CC-NORMED-FIELD)
  (fact 'cc-nf-carr)
  (if (not (dk-asm? (list '== (list 'PTS mrr-nfm) 'CC)))
      (dk-have! (list '== (list 'PTS mrr-nfm) 'CC)
        (lambda () (subst (list '== (list 'PTS mrr-nfm) '(CARR CC-NORMED-FIELD))) (ass))))
  (if (not (dk-asm? (list 'SUBSET u (list 'PTS mrr-nfm))))
      (dk-have! (list 'SUBSET u (list 'PTS mrr-nfm))
        (lambda () (subst (list '== (list 'PTS mrr-nfm) 'CC)) (ass))))
  (if (not (dk-asm? (list 'IN u 'SET)))
      (dk-have! (list 'IN u 'SET)
        (lambda () (fact 'cc-is-set) (fact 'subclass-of-set-is-set u 'CC) (ass))))
  (fact 'subspace-is-metric-space mrr-nfm u)
  (fact 'subspace-pts mrr-nfm u))

;;; ======================================================================
;;; (1) DIFFERENTIABILITY IS LOCAL: differentiable at a on an open v inside u => on u
;;; (the converse of diff-on-shrink)
;;; ======================================================================
(sp (make-wff (list 'FORALL 'u (list 'IMPLIES (list 'IS-OPEN mrr-nfm 'u) (list 'FORALL 'f (list 'IMPLIES '(IN f (FUN u CC))
  (list 'FORALL 'mrrv_ (mrr-imps (list (list 'IS-OPEN mrr-nfm 'mrrv_) '(SUBSET mrrv_ u))
    (list 'FORALL 'mrra_ (list 'IMPLIES '(IN mrra_ mrrv_)
      (list 'FORALL 'mrrl_ (list 'IMPLIES '(IS-DIFF-ON CC-NORMED-FIELD mrrv_ (RESTRICT f mrrv_) mrra_ mrrl_)
        '(IS-DIFF-ON CC-NORMED-FIELD u f mrra_ mrrl_)))))))))))))
(dk-peel!)
(let* ((v 'mrrv_) (a 'mrra_) (l 'mrrl_) (rf '(RESTRICT f mrrv_))
       (mg (lambda (t) (list 'magnitude t))))
  (fact 'cc-open-subset-cc 'u)
  (fact 'cc-open-subset-cc v)
  (fact 'subset-mem-fwd v 'u a)
  (fact 'subset-mem-fwd 'u 'CC a)
  (fact 'fun-apply-type-c 'f 'u 'CC a)
  (fact 'cc-nf-carr)
  (dk-cite! 'diff-on-deriv-in-carr 'CC-NORMED-FIELD v rf a l)
  (dk-have! (list 'IN l 'CC) (lambda () (subst '(== CC (CARR CC-NORMED-FIELD))) (ass)))
  (fact 'cc-is-metric-space) (mrr-pts-cc!)
  (dk-split-all! (list (dk-cite! 'cc-ms-open-iff v)))
  (dk-have! (list 'IS-OPEN 'CC-MS v) (lambda () (prop)))
  (let* ((oiff (dk-cite! 'is-open 'CC-MS v))
         (oball (let loop ((r (caddr oiff))) (if (eq? (car r) 'AND) (loop (caddr r)) r)))
         (inst (dk-cite! 'cc-diff-on-of-eps-bound 'u 'f a l))
         (E (let ((imp (dk-pick (lambda (fm) (and (mrr-op? fm 'IMPLIES 3)
                                                  (equal? (caddr fm) '(IS-DIFF-ON CC-NORMED-FIELD u f mrra_ mrrl_))))
                                "the eps-bound implication")))
              (cadr imp))))
    (dk-have! oball (lambda () (if (dk-only! oiff (list 'IS-OPEN 'CC-MS v)) (prop))))
    (let* ((rho (dk-skolem! (dk-apply! oball a))))
      (dk-split-all!)
      (fact 'rr-pos-rr-in-rr rho)
      (fact 'rr-lt-of-pos-rr rho)
      (dk-have! E
        (lambda ()
          (let* ((eps (cadr (car (filter (dk-head? 'POS-RR) (dk-peel!)))))
                 (r (dk-skolem! (dk-apply! (dk-cite! 'caratheodory-remainder-small v rf a l) eps)))
                 (ub (dk-pick (lambda (fm) (and (mrr-op? fm 'FORALL 3) (dk-contains? fm r) (dk-contains? fm eps))) "the bound on v")))
            (dk-split-all!)
            (fact 'rr-pos-rr-in-rr eps)
            (fact 'rr-pos-rr-in-rr r)
            (fact 'rr-lt-of-pos-rr r)
            (let ((w0 (dk-skolem! (dk-cite! 'rr-min-pos r rho))))
              (dk-split-all!)
              (dk-cite! 'rr-pos-rr-of-lt w0)
              (ew w0)
              (dk-conj-close!
                (lambda ()
                  (if (not (eq? (mrr-hd (dk-goal)) 'FORALL))
                      (dk-ass!)
                      (let* ((lk (dk-peel!))
                             (y (cadr (car (filter (dk-head? 'IN) lk))))
                             (dy (list '- y a)) (fy (list 'f y)) (fa '(f mrra_)))
                        (fact 'subset-mem-fwd 'u 'CC y)
                        (fact 'fun-apply-type-c 'f 'u 'CC y)
                        (mrr-cc! dy)
                        (mrr-rr! (mg dy))
                        ;; y in the ball about a of radius rho, hence in v
                        (dk-have! (list 'IN y (list 'BALL 'CC-MS a rho))
                          (lambda ()
                            (mac 'ball-membership)
                            (fact 'cc-ms-dist a y)
                            (dk-cite! 'cc-magnitude-sub-sym a y)
                            (subst (list '== (list '(DIST CC-MS) a y) (mg (list '- a y))))
                            (subst (list '= (mg (list '- a y)) (mg dy)))
                            (dk-conj-close!
                              (lambda ()
                                (let ((g2 (dk-goal)))
                                  (cond ((dk-asm? g2) (ass))
                                        ((eq? (mrr-hd g2) 'IN) (subst '(== (PTS CC-MS) CC)) (ass))
                                        ((eq? (mrr-hd g2) 'NOT) (di) (dk-absurd! (list '= (mg dy) rho) (list '< (mg dy) w0) (list '<= w0 rho)))
                                        (#t (dk-ineq! (list '< (mg dy) w0) (list '<= w0 rho)))))))))
                        (fact 'subset-mem-fwd (list 'BALL 'CC-MS a rho) v y)
                        (dk-have! (list '< (mg dy) r) (lambda () (dk-ineq! (list '< (mg dy) w0) (list '<= w0 r))))
                        (dk-apply! ub y)
                        (fact 'restrict-apply 'f v y)
                        (fact 'restrict-apply 'f v a)
                        (mrr-cc! (list '* l dy))
                        (let ((lhs (list '- (list '- fy fa) (list '* dy l)))
                              (rhs (list '- fy (list '+ fa (list '* l dy)))))
                          (mrr-cc! lhs) (mrr-cc! rhs)
                          (dk-have! (list '= lhs rhs) (lambda () (crs)))
                          (subst (list '= lhs rhs))
                          (subst (list '== fy (list rf y)))
                          (subst (list '== fa (list rf a)))
                          (dk-ass!))))))))))
      (dk-cite! 'cc-diff-on-of-eps-bound 'u 'f a l)
      (dk-ass!))))
(qed 'diff-on-local)

;;; ======================================================================
;;; (2) COROLLARY 3.7 AND PROPOSITION 3.8 FROM VANISHING TRIANGLE INTEGRALS
;;; (goursat-exceptional.scm's proofs of cauchy-convex-segments-except and
;;; cauchy-convex-primitive-except, copied with the triangle hypothesis (84) of the
;;; notes in place of goursat-triangle-except; its gox- helpers renamed mrr-)
;;; ======================================================================
(define (mrr-all-in vars cls body)       ; forall v in cls. ... body
  (if (null? vars) body
      (list 'FORALL (car vars) (list 'IMPLIES (list 'IN (car vars) cls) (mrr-all-in (cdr vars) cls body)))))
(define (mrr-segtr a b) (list 'TRACE (list 'SEG-PATH a b) 0 1))
(define (mrr-unit! v)
  (let ((mem (list 'IN v '(CCINT 0 1))))
    (fact 'ccint-elt-in-rr 0 1 v)
    (let ((cj (list 'AND (list '<= 0 v) (list '<= v 1))))
      (if (not (and (dk-asm? (list '<= 0 v)) (dk-asm? (list '<= v 1))))
          (begin
            (dk-have! cj (lambda () (mac-h 'ccint-membership mem) (dk-split-all!)
                                    (dk-conj-close! (lambda () (ass)))))
            (dk-split! cj))))))
(define (mrr-scaled-mag! t d0 d1)
  (let ((m (lambda (e) (list 'magnitude e))))
    (mrr-cc! d0) (mrr-cc! d1) (mrr-cc! t)
    (mrr-rr! (m d0)) (mrr-rr! (m d1)) (mrr-rr! (list '* t (m d1)))
    (dk-have! (list '= d0 (list '* t d1)) (lambda () (crs)))
    (mrr-and! (list 'IN t 'CC) (list 'IN d1 'CC))
    (fact 'cc-magnitude-mul t d1)
    (fact 'rr-magnitude-is-abs t)
    (dk-cite! 'rr-abs-of-nonneg t)
    (fact 'cc-magnitude-nonneg d1)
    (dk-have! (list '= (m d0) (list '* t (m d1)))
      (lambda ()
        (subst (list '= d0 (list '* t d1)))
        (subst (list '= (m (list '* t d1)) (list '* (m t) (m d1))))
        (subst (list '= (m t) (list 'abs t)))
        (subst (list '= (list 'abs t) t))
        (rfl)))))
;;; the hypothesis (84) of the notes: every triangle integral in u vanishes
(define mrr-tz-hyp
  '(FORALL mrta_ (IMPLIES (IN mrta_ u) (FORALL mrtb_ (IMPLIES (IN mrtb_ u) (FORALL mrtc_ (IMPLIES (IN mrtc_ u)
     (IMPLIES (SUBSET (CONV3 mrta_ mrtb_ mrtc_) u) (= (TRI-INT f mrta_ mrtb_ mrtc_) 0)))))))))
(define mrr-M (list '(IS-CONVEX u) (list 'IS-OPEN mrr-nfm 'u) '(IN f (FUN u CC)) (mrr-cont 'u 'f) mrr-tz-hyp))
(define (mrr-under-M body) (list 'FORALL 'u (list 'FORALL 'f (mrr-imps mrr-M body))))
(define (mrr-M-setup!)
  (fact 'nf-cc-is-metric-space)
  (dk-cite! 'cc-open-subset-cc 'u))

;;; COROLLARY 3.7
(sp (make-wff (mrr-under-M (mrr-all-in '(mrra_ mrrb_ mrrc_) 'u
  '(= (SEG-INT f mrra_ mrrc_) (+ (SEG-INT f mrra_ mrrb_) (SEG-INT f mrrb_ mrrc_)))))))
(dk-peel!)
(mrr-M-setup!)
(for-each (lambda (v) (fact 'subset-mem-fwd 'u 'CC v)) '(mrra_ mrrb_ mrrc_))
(dk-cite! 'conv3-in-convex 'u 'mrra_ 'mrrb_ 'mrrc_)
(dk-apply! (dk-ctx-form mrr-tz-hyp) 'mrra_ 'mrrb_ 'mrrc_)
(for-each (lambda (pq) (dk-cite! 'seg-trace-in-convex 'u (car pq) (cadr pq)) (dk-cite! 'seg-int-in-cc 'u 'f (car pq) (cadr pq)))
          '((mrra_ mrrb_) (mrrb_ mrrc_) (mrrc_ mrra_) (mrra_ mrrc_)))
(let* ((sab '(SEG-INT f mrra_ mrrb_)) (sbc '(SEG-INT f mrrb_ mrrc_)) (sca '(SEG-INT f mrrc_ mrra_))
       (s3 (list '+ (list '+ sab sbc) sca))
       (rv (dk-cite! 'seg-int-reverse-at 'u 'f 'mrra_ 'mrrc_)))
  (dk-cite! 'tri-int-unfold 'f 'mrra_ 'mrrb_ 'mrrc_)
  (mrr-cc! s3)
  (dk-have! (list '= s3 0) (lambda () (subst (list '= s3 '(TRI-INT f mrra_ mrrb_ mrrc_))) (ass)))
  (dk-have! (list '= (list '+ sab sbc) (list '- s3 sca)) (lambda () (crs)))
  (subst (list '= (list '+ sab sbc) (list '- s3 sca)))
  (subst (list '= s3 0))
  (subst rv)
  (crs))
(qed 'cauchy-convex-segments-of-triangles)

;;; PROPOSITION 3.8, for a given base point o in u: g(b) = int_<o, b> f is a primitive.
;;; The derivative at z uses only the CONTINUITY of f at z (the notes' proof):
;;; |g(y) - g(z) - (y - z) f(z)| = |int_<z,y> (f - f(z))| <= |y - z| sup_<z,y> |f - f(z)|.
;;; In context: H(u, f), z in u, POS-RR(e).  Returns (del . claim), claim =
;;; forall w in u, |w - z| <= del => |f(w) - f(z)| <= e.
(define (mrr-cont-mag! z e)
  (let* ((S (list 'SUBSPACE-MS mrr-nfm 'u))
         (mg (lambda (p) (list 'magnitude p)))
         (fz (list 'f z))
         (cz (dk-apply! (dk-ctx-form (mrr-cont 'u 'f)) z))
         (iff (dk-cite! 'is-continuous-at S mrr-nfm 'f z))
         (edf (let loop ((r (caddr iff))) (if (eq? (car r) 'AND) (loop (caddr r)) r))))
    (dk-have! edf (lambda () (if (dk-only! iff cz) (prop))))
    (let* ((del (dk-skolem! (dk-apply! edf e)))
           (ub (dk-pick (lambda (fm) (and (mrr-op? fm 'FORALL 3) (dk-contains? fm del))) "the continuity bound"))
           (claim (list 'FORALL 'mrrcw_ (list 'IMPLIES '(IN mrrcw_ u)
                    (list 'IMPLIES (list '<= (list 'magnitude (list '- 'mrrcw_ z)) del)
                                   (list '<= (list 'magnitude (list '- '(f mrrcw_) fz)) e))))))
      (fact 'rr-pos-rr-in-rr del)
      (fact 'rr-lt-of-pos-rr del)
      (fact 'subspace-pts mrr-nfm 'u)
      (fact 'cc-is-metric-space)
      (mrr-pts-cc!)
      (dk-have! claim
        (lambda ()
          (let* ((w (dk-di-var!)) (fw (list 'f w)))
            (di)
            (fact 'subset-mem-fwd 'u 'CC w)
            (fact 'fun-apply-type-c 'f 'u 'CC w)
            (fact 'fun-apply-type-c 'f 'u 'CC z)
            (dk-have! (list 'IN w (list 'PTS S)) (lambda () (subst (list '== (list 'PTS S) 'u)) (ass)))
            (for-each (lambda (pp) (dk-have! (list 'IN pp '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass))))
                      (list z w fz fw))
            (fact 'subspace-dist mrr-nfm 'u z w)
            (fact 'nf-cc-agree-dist z w)
            (fact 'cc-ms-dist z w)
            (mrr-cc! (list '- z w)) (mrr-rr! (mg (list '- z w)))
            (mrr-cc! (list '- w z)) (mrr-rr! (mg (list '- w z)))
            (dk-cite! 'cc-magnitude-sub-sym z w)
            (dk-have! (list '<= (list (list 'DIST S) z w) del)
              (lambda ()
                (subst (list '== (list (list 'DIST S) z w) (list (list 'DIST mrr-nfm) z w)))
                (subst (list '== (list (list 'DIST mrr-nfm) z w) (list '(DIST CC-MS) z w)))
                (subst (list '== (list '(DIST CC-MS) z w) (mg (list '- z w))))
                (subst (list '= (mg (list '- z w)) (mg (list '- w z))))
                (ass)))
            (dk-apply! ub w)
            (fact 'nf-cc-agree-dist fz fw)
            (fact 'cc-ms-dist fz fw)
            (mrr-cc! (list '- fz fw)) (mrr-rr! (mg (list '- fz fw)))
            (mrr-cc! (list '- fw fz)) (mrr-rr! (mg (list '- fw fz)))
            (dk-cite! 'cc-magnitude-sub-sym fw fz)
            (subst (list '= (mg (list '- fw fz)) (mg (list '- fz fw))))
            (subst (list '== (mg (list '- fz fw)) (list '(DIST CC-MS) fz fw)))
            (subst (list '== (list '(DIST CC-MS) fz fw) (list (list 'DIST mrr-nfm) fz fw)))
            (ass))))
      (cons del claim))))

(sp (make-wff (mrr-under-M
  '(FORALL mrro_ (IMPLIES (IN mrro_ u)
     (FORSOME mrrg_ (AND (IN mrrg_ (FUN u CC)) (AND (HOLOMORPHIC-ON u mrrg_)
       (FORALL mrrz_ (IMPLIES (IN mrrz_ u) (IS-DIFF-ON CC-NORMED-FIELD u mrrg_ mrrz_ (f mrrz_))))))))))))
(dk-peel!)
(mrr-M-setup!)
(fact 'cc-is-normed-field)
(fact 'nf-open-is-set 'CC-NORMED-FIELD 'u)
(fact 'subset-mem-fwd 'u 'CC 'mrro_)
(define mrr-pr-G (list 'VNB-LAMBDA 'mrrpb_ 'u '(SEG-INT f mrro_ mrrpb_)))
(define (mrr-pr-seg! b)   ;; b in u: b in CC, the segment from o to b in u, its integral in CC
  (fact 'subset-mem-fwd 'u 'CC b)
  (dk-cite! 'seg-trace-in-convex 'u 'mrro_ b)
  (dk-cite! 'seg-int-in-cc 'u 'f 'mrro_ b))
(dk-have! (list 'IN mrr-pr-G '(FUN u CC))
  (lambda () (dk-lam-type! (lambda () (let ((b (dk-di-var!))) (mrr-pr-seg! b) (ass))))))
(define mrr-pr-val
  (list 'FORALL 'mrrz_ (list 'IMPLIES '(IN mrrz_ u) (list '== (list mrr-pr-G 'mrrz_) '(SEG-INT f mrro_ mrrz_)))))
(dk-have! mrr-pr-val
  (lambda () (let ((b (dk-di-var!))) (mrr-pr-seg! b) (if (not (dk-lam-b!)) (qrfl)))))
;; the derivative at every point
(define mrr-pr-d
  (list 'FORALL 'mrrpz_ (list 'IMPLIES '(IN mrrpz_ u) (list 'IS-DIFF-ON 'CC-NORMED-FIELD 'u mrr-pr-G 'mrrpz_ '(f mrrpz_)))))
(dk-have! mrr-pr-d
  (lambda ()
    (let* ((z (dk-di-var!))
           (fz (list 'f z))
           (k  (list 'VNB-LAMBDA 'mrrpv_ 'u (list '+ fz (list '* 0 (list '- 'mrrpv_ z)))))
           (h  (list 'VNB-LAMBDA 'mrrpv_ 'u (list '+ '(f mrrpv_) (list '- fz))))
           (mg (lambda (p) (list 'magnitude p))))
      (mrr-pr-seg! z)
      (fact 'fun-apply-type-c 'f 'u 'CC z)
      (mrr-cc! (list '- fz))
      (mrr-cc! 0)
      ;; k, h = f - f(z) as functions on u; k holomorphic, h continuous
      (for-each
       (lambda (lam)
         (dk-have! (list 'IN lam '(FUN u CC))
           (lambda ()
             (dk-lam-type!
               (lambda ()
                 (let ((y (dk-di-var!)))
                   (fact 'subset-mem-fwd 'u 'CC y)
                   (fact 'fun-apply-type-c 'f 'u 'CC y)
                   (mrr-cc! (subst-free 'mrrpv_ y (list-ref lam 3)))
                   (ass)))))))
       (list k h))
      (for-each
       (lambda (lam)
         (dk-have! (list 'FORALL 'mrrz_ (list 'IMPLIES '(IN mrrz_ u) (list '== (list lam 'mrrz_) (subst-free 'mrrpv_ 'mrrz_ (list-ref lam 3)))))
           (lambda ()
             (let ((y (dk-di-var!)))
               (fact 'subset-mem-fwd 'u 'CC y)
               (fact 'fun-apply-type-c 'f 'u 'CC y)
               (mrr-cc! (subst-free 'mrrpv_ y (list-ref lam 3)))
               (if (not (dk-lam-b!)) (qrfl))))))
       (list k h))
      (dk-cite! 'affine-holomorphic 'u fz 0 z k)
      (dk-cite! 'holomorphic-on-continuous 'u k)
      (dk-cite! 'cc-continuous-at-add-const 'u 'f h (list '- fz))
      (dk-have! (list 'FORALL 'mrrz_ (list 'IMPLIES '(IN mrrz_ u) (list '== '(f mrrz_) (list '+ (list h 'mrrz_) (list k 'mrrz_)))))
        (lambda ()
          (let* ((y (dk-di-var!)) (fy (list 'f y)))
            (fact 'subset-mem-fwd 'u 'CC y)
            (fact 'fun-apply-type-c 'f 'u 'CC y)
            (mrr-cc! (subst-free 'mrrpv_ y (list-ref k 3)))
            (mrr-cc! (subst-free 'mrrpv_ y (list-ref h 3)))
            (dk-lam-b!)
            (let ((rhs (caddr (dk-goal))))
              (dk-have! (list '= rhs fy) (lambda () (crs)))
              (subst (list '= rhs fy))
              (qrfl)))))
      ;; the little-o bound at z, from the continuity of f at z
      (dk-have! (list 'FORALL 'mrre_ (list 'IMPLIES '(POS-RR mrre_)
                  (list 'FORSOME 'mrrd_ (list 'AND '(POS-RR mrrd_)
                    (list 'FORALL 'mrry_ (list 'IMPLIES '(IN mrry_ u)
                      (list 'IMPLIES (list '< (list 'magnitude (list '- 'mrry_ z)) 'mrrd_)
                        (list '<= (list 'magnitude (list '- (list '- (list mrr-pr-G 'mrry_) (list mrr-pr-G z)) (list '* (list '- 'mrry_ z) fz)))
                                  (list '* 'mrre_ (list 'magnitude (list '- 'mrry_ z)))))))))))
        (lambda ()
          (let* ((e (cadr (car (filter (dk-head? 'POS-RR) (dk-peel!)))))
                 (dc (begin (fact 'rr-pos-rr-in-rr e) (fact 'rr-lt-of-pos-rr e) (mrr-cont-mag! z e)))
                 (del (car dc)) (cb (cdr dc)))
            (ew del)
            (dk-conj-close!
              (lambda ()
                (if (not (eq? (mrr-hd (dk-goal)) 'FORALL))
                    (ass)
                    (let* ((ls (dk-peel!))
                           (x (cadr (find-first (lambda (fm) (and (mrr-op? fm 'IN 3) (eq? (caddr fm) 'u))) ls)))
                           (dx (mg (list '- x z)))
                           (hb (list 'FORALL 'mrrcy_ (list 'IMPLIES (list 'IN 'mrrcy_ (mrr-segtr z x))
                                 (list '<= (list 'magnitude (list h 'mrrcy_)) e)))))
                      (mrr-pr-seg! x)
                      (dk-cite! 'seg-trace-in-convex 'u z x)
                      (dk-cite! 'seg-int-in-cc 'u 'f z x)
                      (subst (dk-apply! (dk-ctx-form mrr-pr-val) x))
                      (subst (dk-apply! (dk-ctx-form mrr-pr-val) z))
                      (subst (dk-cite! 'cauchy-convex-segments-of-triangles 'u 'f 'mrro_ z x))
                      (subst (dk-cite! 'seg-int-sum 'u h k 'f z x))
                      (subst (dk-cite! 'seg-int-const 'u fz z k z x))
                      (dk-cite! 'seg-int-in-cc 'u h z x)
                      (dk-cite! 'seg-int-in-cc 'u k z x)
                      (let* ((shx (list 'SEG-INT h z x))
                             (lhs (cadr (cadr (dk-goal)))))
                        (mrr-cc! lhs)
                        (dk-have! (list '= lhs shx) (lambda () (crs)))
                        (subst (list '= lhs shx))
                        (mrr-cc! (list '- x z)) (mrr-rr! dx)
                        (fact 'cc-magnitude-nonneg (list '- x z))
                        ;; |h| <= e on the segment from z to x
                        (dk-have! hb
                          (lambda ()
                            (let* ((y (dk-di-var!))
                                   (tt (dk-skolem! (dk-cite! 'seg-trace-elim z x y)))
                                   (dy (list '- y z)) (mdy (mg dy)))
                              (mrr-unit! tt)
                              (fact 'subset-mem-fwd (mrr-segtr z x) 'u y)
                              (fact 'subset-mem-fwd 'u 'CC y)
                              (fact 'fun-apply-type-c 'f 'u 'CC y)
                              (mrr-cc! dy) (mrr-rr! mdy)
                              (dk-have! (list '= dy (list '* tt (list '- x z)))
                                (lambda () (subst (list '= y (list '+ z (list '* tt (list '- x z))))) (crs)))
                              (mrr-scaled-mag! tt dy (list '- x z))
                              (mrr-and! (list '<= tt 1) (list '<= 0 dx))
                              (fact 'rr-mul-le-right tt 1 dx)
                              (mrr-rr! (list '* 1 dx))
                              (dk-have! (list '<= mdy del)
                                (lambda () (dk-ineq! (list 'IN mdy 'RR) (list 'IN (list '* tt dx) 'RR) (list 'IN dx 'RR)
                                                     (list 'IN del 'RR)
                                                     (list '= mdy (list '* tt dx)) (list '<= (list '* tt dx) (list '* 1 dx))
                                                     (list '< dx del))))
                              (dk-apply! cb y)
                              (dk-lam-b!)
                              (let ((fy (list 'f y)))
                                (mrr-cc! (list '+ fy (list '- fz))) (mrr-cc! (list '- fy fz))
                                (dk-have! (list '= (list '+ fy (list '- fz)) (list '- fy fz)) (lambda () (crs)))
                                (subst (list '= (list '+ fy (list '- fz)) (list '- fy fz)))
                                (ass)))))
                        (dk-apply! (dk-cite! 'seg-int-abs-bound 'u h z x) e)
                        (mrr-rr! (list '* dx e))
                        (mrr-rr! (list '* e dx))
                        (mrr-rr! (mg shx))
                        (dk-have! (list '= (list '* dx e) (list '* e dx)) (lambda () (crs)))
                        (dk-ineq! (list 'IN (mg shx) 'RR) (list 'IN (list '* dx e) 'RR) (list 'IN (list '* e dx) 'RR)
                                  (list '<= (mg shx) (list '* dx e)) (list '= (list '* dx e) (list '* e dx)))))))))))
      (dk-cite! 'cc-diff-on-of-eps-bound 'u mrr-pr-G z fz)
      (ass))))
(ew mrr-pr-G)
(dk-conj-close!
  (lambda ()
    (let ((g (dk-goal)))
      (cond ((dk-asm? g) (ass))
            ((dk-head-is? g 'HOLOMORPHIC-ON)
             (mac 'HOLOMORPHIC-ON)
             (dk-conj-close!
               (lambda ()
                 (if (not (dk-head-is? (dk-goal) 'FORALL))
                     (ass)
                     (let ((a (dk-di-var!)))
                       (dk-apply! (dk-ctx-form mrr-pr-d) a)
                       (ew (list 'f a))
                       (ass))))))
            (#t (error "cauchy-convex-primitive-except: unexpected leaf" (expression->string g)))))))
(qed 'cauchy-convex-primitive-of-triangles)


;;; ======================================================================
;;; (3) MORERA'S THEOREM (Proposition 3.43), CONDITIONAL on "the derivative of a
;;; holomorphic function is holomorphic" (Corollary 3.37), stated as the antecedent
;;; mrr-H below: the composition with CA-3's theorem is one detachment.
;;; ======================================================================
(define mrr-H
  '(FORALL mrhv_ (FORALL mrhg_ (FORALL mrhd_ (IMPLIES (HOLOMORPHIC-ON mrhv_ mrhg_)
     (IMPLIES (IN mrhd_ (FUN mrhv_ CC))
       (IMPLIES (FORALL mrhz_ (IMPLIES (IN mrhz_ mrhv_) (IS-DIFF-ON CC-NORMED-FIELD mrhv_ mrhg_ mrhz_ (mrhd_ mrhz_))))
         (HOLOMORPHIC-ON mrhv_ mrhd_))))))))
(define (mrr-tz u f)
  (list 'FORALL 'mrta_ (list 'IMPLIES (list 'IN 'mrta_ u) (list 'FORALL 'mrtb_ (list 'IMPLIES (list 'IN 'mrtb_ u)
    (list 'FORALL 'mrtc_ (list 'IMPLIES (list 'IN 'mrtc_ u)
      (list 'IMPLIES (list 'SUBSET '(CONV3 mrta_ mrtb_ mrtc_) u) (list '= (list 'TRI-INT f 'mrta_ 'mrtb_ 'mrtc_) 0)))))))))

;;; in a context holding H, u open, f in FUN(u, CC) continuous on u, a in u, B = BALL(CC-MS, a, rho)
;;; inside u (rho in RR, 0 < rho), and the triangle hypothesis for f on B (landed by the
;;; caller, for RESTRICT(f, B)): land IS-DIFF-ON(CC-NORMED-FIELD, u, f, a, l) and return l
(define (mrr-local-diff! a rho)
  (let* ((B (list 'BALL 'CC-MS a rho)) (rf (list 'RESTRICT 'f B)))
    (dk-cite! 'cauchy-convex-primitive-of-triangles B rf a)
    (let ((G (dk-skolem! (dk-pick (lambda (fm) (and (mrr-op? fm 'FORSOME 3) (dk-contains? fm rf) (dk-contains? fm 'HOLOMORPHIC-ON)))
                                  "the primitive on the disc"))))
      (dk-split-all!)
      (dk-apply! (dk-ctx-form mrr-H) B G rf)
      (let ((l (dk-skolem! (dk-apply! (dk-cite! 'holomorphic-on-diff B rf) a))))
        (dk-cite! 'diff-on-local 'u 'f B a l)
        l))))

;;; the disc about a in u: land its facts (open, convex, inside u, a in it, the restriction
;;; of f a continuous function on it); return rho
(define (mrr-disc! a)
  (fact 'cc-open-subset-cc 'u)
  (fact 'subset-mem-fwd 'u 'CC a)
  (fact 'cc-is-metric-space) (mrr-pts-cc!)
  (dk-have! (list 'IN a '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass)))
  (dk-split-all! (list (dk-cite! 'cc-ms-open-iff 'u)))
  (dk-have! '(IS-OPEN CC-MS u) (lambda () (prop)))
  (let* ((oiff (dk-cite! 'is-open 'CC-MS 'u))
         (oball (let loop ((r (caddr oiff))) (if (eq? (car r) 'AND) (loop (caddr r)) r))))
    (dk-have! oball (lambda () (if (dk-only! oiff '(IS-OPEN CC-MS u)) (prop))))
    (let ((rho (dk-skolem! (dk-apply! oball a))))
      (dk-split-all!)
      (mrr-disc-facts! a rho)
      rho)))

;;; (POS-RR rho), BALL(CC-MS, a, rho) subset u, a in u, u open, f in FUN(u, CC) continuous
;;; on u in context: the disc's facts, and RESTRICT(f, B) continuous on B
(define (mrr-disc-facts! a rho)
  (fact 'cc-open-subset-cc 'u)
  (fact 'subset-mem-fwd 'u 'CC a)
  (fact 'cc-is-metric-space) (mrr-pts-cc!)
  (if (not (dk-asm? (list 'IN a '(PTS CC-MS))))
      (dk-have! (list 'IN a '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass))))
    (let* ((B (list 'BALL 'CC-MS a rho)) (rf (list 'RESTRICT 'f B)))
      (fact 'rr-pos-rr-in-rr rho)
      (fact 'rr-lt-of-pos-rr rho)
      (dk-have! (list '<= 0 rho) (lambda () (dk-ineq! (list '< 0 rho))))
      (dk-have! (list 'NOT (list '= 0 rho)) (lambda () (di) (dk-absurd! (list '= 0 rho) (list '< 0 rho))))
      (mrr-and! (list 'IN rho 'RR) (mrr-and! (list '<= 0 rho) (list 'NOT (list '= 0 rho))))
      (dk-cite! 'ball-is-open 'CC-MS a rho)
      (dk-split-all! (list (dk-cite! 'cc-ms-open-iff B)))
      (dk-have! (list 'IS-OPEN mrr-nfm B) (lambda () (prop)))
      (dk-cite! 'cc-ball-is-convex a rho)
      (dk-cite! 'ball-center-in 'CC-MS a rho)
      (fact 'cc-open-subset-cc B)
      (mrr-ms! 'u)
      (mrr-ms! B)
      (fact 'restrict-in-fun 'f 'u 'CC B)
      (dk-have! (mrr-cont B rf)
        (lambda ()
          (let ((y (dk-di-var!)))
            (fact 'subset-mem-fwd B 'u y)
            (dk-apply! (dk-ctx-form (mrr-cont 'u 'f)) y)
            (dk-cite! 'subspace-restrict-continuous-at mrr-nfm 'u B mrr-nfm 'f y)
            (dk-ass!))))))

(sp (make-wff (list 'IMPLIES mrr-H
  (list 'FORALL 'u (list 'IMPLIES (list 'IS-OPEN mrr-nfm 'u) (list 'FORALL 'f
    (mrr-imps (list '(IN f (FUN u CC)) (mrr-cont 'u 'f) (mrr-tz 'u 'f)) '(HOLOMORPHIC-ON u f))))))))
(dk-peel!)
(mac 'HOLOMORPHIC-ON)
(dk-conj-close!
  (lambda ()
    (if (not (eq? (mrr-hd (dk-goal)) 'FORALL))
        (dk-ass!)
        (let* ((a (dk-di-var!))
               (rho (mrr-disc! a))
               (B (list 'BALL 'CC-MS a rho)) (rf (list 'RESTRICT 'f B)))
          ;; the triangle hypothesis for RESTRICT(f, B) on B
          (dk-have! (mrr-tz B rf)
            (lambda ()
              (let* ((ls (dk-peel!))
                     (vs (map cadr (filter (lambda (fm) (and (mrr-op? fm 'IN 3) (equal? (caddr fm) B))) ls)))
                     (x1 (car vs)) (x2 (cadr vs)) (x3 (caddr vs)))
                (for-each (lambda (x) (fact 'subset-mem-fwd B 'u x) (fact 'subset-mem-fwd 'u 'CC x)) vs)
                (fact 'subset-trans (list 'CONV3 x1 x2 x3) B 'u)
                (dk-cite! 'tri-int-restrict 'u 'f B x1 x2 x3)
                (dk-apply! (dk-ctx-form (mrr-tz 'u 'f)) x1 x2 x3)
                (subst (list '= (list 'TRI-INT rf x1 x2 x3) (list 'TRI-INT 'f x1 x2 x3)))
                (dk-ass!))))
          (let ((l (mrr-local-diff! a rho)))
            (ew l)
            (dk-ass!))))))
(qed 'morera-conditional)

;;; ======================================================================
;;; (4) LOCALLY UNIFORM LIMITS OF HOLOMORPHIC FUNCTIONS ARE HOLOMORPHIC (Proposition
;;; 3.44), conditional on the same mrr-H.  "Uniformly on compact subsets" is written
;;; LOCALLY: every point of u has a disc inside u on which the convergence is uniform
;;; (on an open subset of CC the two are equivalent; the local form is the one the
;;; proof uses, and needs no compactness vocabulary).
;;; ======================================================================
(define (mrr-unif S)
  (list 'FORALL 'eps (list 'IMPLIES '(POS-RR eps)
    (list 'FORSOME 'aicap_ (list 'AND '(IN aicap_ NN)
      (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (list 'IMPLIES '(<= aicap_ k)
        (list 'FORALL 'aiy_ (list 'IMPLIES (list 'IN 'aiy_ S)
          '(<= (magnitude (- ((fam k) aiy_) (f aiy_))) eps)))))))))))
(define mrr-LU
  (list 'FORALL 'mrlz_ (list 'IMPLIES '(IN mrlz_ u)
    (list 'FORSOME 'mrlr_ (list 'AND '(POS-RR mrlr_)
      (list 'AND '(SUBSET (BALL CC-MS mrlz_ mrlr_) u) (mrr-unif '(BALL CC-MS mrlz_ mrlr_))))))))
(define mrr-famhol '(FORALL k (IMPLIES (IN k NN) (HOLOMORPHIC-ON u (fam k)))))

;;; the disc about z0 of the locally uniform hypothesis: returns rho; lands POS-RR(rho),
;;; the disc inside u and the uniform bound on it
(define (mrr-lu-disc! z0)
  (let ((rho (dk-skolem! (dk-apply! (dk-ctx-form mrr-LU) z0))))
    (dk-split-all!)
    rho))

(sp (make-wff (list 'IMPLIES mrr-H
  (list 'FORALL 'u (list 'IMPLIES (list 'IS-OPEN mrr-nfm 'u)
    (list 'FORALL 'fam (list 'IMPLIES mrr-famhol
      (list 'FORALL 'f (mrr-imps (list '(IN f (FUN u CC)) mrr-LU) '(HOLOMORPHIC-ON u f))))))))))
(dk-peel!)
(fact 'cc-open-subset-cc 'u)
(mrr-ms! 'u)
(fact 'cc-is-metric-space) (mrr-pts-cc!)
;; the members of the sequence: functions on u, continuous on u
(dk-have! '(FORALL k (IMPLIES (IN k NN) (IN (fam k) (FUN u CC))))
  (lambda () (let ((k (dk-di-var!))) (dk-apply! (dk-ctx-form mrr-famhol) k) (dk-cite! 'holomorphic-on-in-fun 'u (list 'fam k)) (dk-ass!))))
(dk-have! (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (mrr-cont 'u '(fam k))))
  (lambda ()
    (let* ((ls (dk-peel!))
           (k (cadr (car (filter (lambda (fm) (and (mrr-op? fm 'IN 3) (eq? (caddr fm) 'NN))) ls))))
           (y (cadr (car (filter (lambda (fm) (and (mrr-op? fm 'IN 3) (eq? (caddr fm) 'u))) ls)))))
      (dk-apply! (dk-ctx-form mrr-famhol) k)
      (dk-apply! (dk-cite! 'holomorphic-on-continuous 'u (list 'fam k)) y)
      (dk-ass!))))
;; (A) the limit is continuous on u (eps / 4 three times)
(dk-have! (mrr-cont 'u 'f)
  (lambda ()
    (let* ((y0 (dk-di-var!))
           (rho (mrr-lu-disc! y0))
           (B (list 'BALL 'CC-MS y0 rho))
           (ub (dk-ctx-form (mrr-unif B)))
           (S (mrr-sub 'u))
           (dn (lambda (p q) (list (list 'DIST mrr-nfm) p q)))
           (dc (lambda (p q) (list '(DIST CC-MS) p q)))
           (mg (lambda (t) (list 'magnitude t))))
      (fact 'subset-mem-fwd 'u 'CC y0)
      (fact 'fun-apply-type-c 'f 'u 'CC y0)
      (fact 'rr-pos-rr-in-rr rho)
      (fact 'rr-lt-of-pos-rr rho)
      (mac 'is-continuous-at)
      (dk-conj-close!
       (lambda ()
         (let ((g (dk-goal)))
           (cond
            ((dk-asm? g) (ass))
            ((eq? (mrr-hd g) 'IN)
             (if (dk-contains? g (list 'PTS S)) (subst (list '== (list 'PTS S) 'u)))
             (if (dk-contains? (dk-goal) (list 'PTS mrr-nfm)) (subst (list '== (list 'PTS mrr-nfm) 'CC)))
             (ass))
            ((eq? (mrr-hd g) 'FORALL)
             (let* ((eps (cadr (car (filter (dk-head? 'POS-RR) (dk-peel!)))))
                    (e2 (dk-halve! eps))
                    (e4 (dk-halve! e2))
                    (N (dk-skolem! (dk-apply! ub e4)))
                    (ubN (dk-pick (lambda (fm) (and (mrr-op? fm 'FORALL 3) (dk-contains? fm N) (dk-contains? fm e4))) "the uniform bound"))
                    (fN (list 'fam N)))
               (dk-split-all!)
               (fact 'rr-pos-rr-in-rr eps)
               (fact 'nn-le-refl N)
               (dk-apply! (dk-ctx-form mrr-famhol) N)
               (dk-apply! (dk-ctx-form '(FORALL k (IMPLIES (IN k NN) (IN (fam k) (FUN u CC))))) N)
               (let* ((cN (dk-apply! (dk-ctx-form (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (mrr-cont 'u '(fam k))))) N y0))
                      (iff (dk-cite! 'is-continuous-at S mrr-nfm fN y0))
                      (edf (let loop ((r (caddr iff))) (if (eq? (car r) 'AND) (loop (caddr r)) r))))
                 (dk-have! edf (lambda () (if (dk-only! iff cN) (prop))))
                 (let* ((d1 (dk-skolem! (dk-apply! edf e4)))
                        (cb (dk-pick (lambda (fm) (and (mrr-op? fm 'FORALL 3) (dk-contains? fm d1))) "the continuity bound of fam(N)")))
                   (fact 'rr-pos-rr-in-rr d1)
                   (fact 'rr-lt-of-pos-rr d1)
                   (let ((rh (dk-halve! rho)))
                     (dk-split-all!)
                     (let ((w0 (dk-skolem! (dk-cite! 'rr-min-pos d1 rh))))
                       (dk-split-all!)
                       (dk-cite! 'rr-pos-rr-of-lt w0)
                       (ew w0)
                       (dk-conj-close!
                        (lambda ()
                          (if (not (eq? (mrr-hd (dk-goal)) 'FORALL))
                              (dk-ass!)
                              (let* ((lk (dk-peel!))
                                     (bpt (cadr (car (filter (dk-head? 'IN) lk))))
                                     (fy (list 'f y0)) (fb (list 'f bpt)) (gy (list fN y0)) (gb (list fN bpt)))
                                (dk-have! (list 'IN bpt 'u) (lambda () (subst (list '== 'u (list 'PTS S))) (ass)))
                                (fact 'subset-mem-fwd 'u 'CC bpt)
                                (fact 'fun-apply-type-c 'f 'u 'CC bpt)
                                (fact 'fun-apply-type-c fN 'u 'CC bpt)
                                (fact 'fun-apply-type-c fN 'u 'CC y0)
                                (for-each (lambda (p) (dk-have! (list 'IN p '(PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (ass))))
                                          (list y0 bpt fy fb gy gb))
                                (for-each (lambda (pq) (fact 'nf-cc-agree-dist (car pq) (cadr pq)) (fact 'cc-ms-dist (car pq) (cadr pq)))
                                          (list (list y0 bpt) (list fy fb) (list gy gb)))
                                (fact 'subspace-dist mrr-nfm 'u y0 bpt)
                                (mrr-cc! (list '- y0 bpt))
                                (mrr-rr! (mg (list '- y0 bpt)))
                                (dk-have! (list '<= (mg (list '- y0 bpt)) w0)
                                  (lambda ()
                                    (subst (list '== (mg (list '- y0 bpt)) (dc y0 bpt)))
                                    (subst (list '== (dc y0 bpt) (dn y0 bpt)))
                                    (subst (list '== (dn y0 bpt) (list (list 'DIST S) y0 bpt)))
                                    (dk-ass!)))
                                ;; fam(N) moves by at most e4 between y0 and bpt
                                (dk-have! (list '<= (list (list 'DIST S) y0 bpt) d1)
                                  (lambda ()
                                    (subst (list '== (list (list 'DIST S) y0 bpt) (dn y0 bpt)))
                                    (subst (list '== (dn y0 bpt) (dc y0 bpt)))
                                    (subst (list '== (dc y0 bpt) (mg (list '- y0 bpt))))
                                    (dk-ineq! (list '<= (mg (list '- y0 bpt)) w0) (list '<= w0 d1))))
                                (dk-apply! cb bpt)
                                (mrr-cc! (list '- gy gb))
                                (mrr-rr! (mg (list '- gy gb)))
                                (dk-have! (list '<= (mg (list '- gy gb)) e4)
                                  (lambda ()
                                    (subst (list '== (mg (list '- gy gb)) (dc gy gb)))
                                    (subst (list '== (dc gy gb) (dn gy gb)))
                                    (dk-ass!)))
                                ;; bpt in the disc, so the uniform bound holds at bpt and at y0
                                (dk-have! (list 'IN bpt B)
                                  (lambda ()
                                    (mac 'ball-membership)
                                    (subst (list '== (dc y0 bpt) (mg (list '- y0 bpt))))
                                    (dk-conj-close!
                                      (lambda ()
                                        (let ((g2 (dk-goal)))
                                          (cond ((dk-asm? g2) (ass))
                                                ((eq? (mrr-hd g2) 'IN) (subst '(== (PTS CC-MS) CC)) (ass))
                                                ((eq? (mrr-hd g2) 'NOT)
                                                 (di)
                                                 (dk-absurd! (list '= (mg (list '- y0 bpt)) rho) (list '<= (mg (list '- y0 bpt)) w0)
                                                             (list '<= w0 rh) (list '= (list '+ rh rh) rho) (list '< 0 rh)))
                                                (#t (dk-ineq! (list '<= (mg (list '- y0 bpt)) w0) (list '<= w0 rh)
                                                              (list '= (list '+ rh rh) rho) (list '< 0 rh)))))))))
                                (dk-have! (list '<= 0 rho) (lambda () (dk-ineq! (list '< 0 rho))))
                                (dk-have! (list 'NOT (list '= 0 rho)) (lambda () (di) (dk-absurd! (list '= 0 rho) (list '< 0 rho))))
                                (mrr-and! (list 'IN rho 'RR) (mrr-and! (list '<= 0 rho) (list 'NOT (list '= 0 rho))))
                                (dk-cite! 'ball-center-in 'CC-MS y0 rho)
                                (dk-apply! ubN N bpt)
                                (dk-apply! (dk-pick (lambda (fm) (and (mrr-op? fm 'FORALL 3) (eq? (cadr fm) 'aiy_) (dk-contains? fm N)
                                                                      (dk-contains? fm e4)))
                                                    "the uniform bound at N")
                                           y0)
                                ;; the triangle inequality, twice
                                (let* ((p1 (list '- fy gy)) (p2 (list '- gy gb)) (p3 (list '- gb fb))
                                       (s12 (list '+ p1 p2)))
                                  (for-each mrr-cc! (list p1 p3 s12 (list '- gy fy) (list '- gb fb) (list '- fy fb)))
                                  (for-each (lambda (t) (mrr-rr! (mg t))) (list p1 p3 s12 (list '- gy fy) (list '- fy fb)))
                                  (dk-cite! 'cc-magnitude-sub-sym fy gy)
                                  (mrr-and! (list 'IN p1 'CC) (list 'IN p2 'CC))
                                  (dk-cite! 'cc-magnitude-triangle p1 p2)
                                  (mrr-and! (list 'IN s12 'CC) (list 'IN p3 'CC))
                                  (dk-cite! 'cc-magnitude-triangle s12 p3)
                                  (mrr-cc! (list '+ s12 p3))
                                  (dk-have! (list '= (list '- fy fb) (list '+ s12 p3)) (lambda () (crs)))
                                  (mrr-rr! (mg (list '+ s12 p3)))
                                  (subst (list '== (dn fy fb) (dc fy fb)))
                                  (subst (list '== (dc fy fb) (mg (list '- fy fb))))
                                  (subst (list '= (list '- fy fb) (list '+ s12 p3)))
                                  (dk-ineq! (list '<= (mg (list '+ s12 p3)) (list '+ (mg s12) (mg p3)))
                                            (list '<= (mg s12) (list '+ (mg p1) (mg p2)))
                                            (list '= (mg p1) (mg (list '- gy fy)))
                                            (list '<= (mg (list '- gy fy)) e4)
                                            (list '<= (mg p2) e4)
                                            (list '<= (mg p3) e4)
                                            (list '< 0 e4)
                                            (list '= (list '+ e4 e4) e2) (list '= (list '+ e2 e2) eps)))))))))))))
            (#t (error "uniform limit continuity: unexpected leaf" (expression->string g))))))))))
;; (B) on a disc about a, every triangle integral of the limit vanishes; Morera's local step
(mac 'HOLOMORPHIC-ON)
(dk-conj-close!
  (lambda ()
    (if (not (eq? (mrr-hd (dk-goal)) 'FORALL))
        (dk-ass!)
        (let* ((a (dk-di-var!))
               (rho (mrr-lu-disc! a))
               (B (list 'BALL 'CC-MS a rho)) (rf (list 'RESTRICT 'f B))
               (ub (dk-ctx-form (mrr-unif B))))
          (mrr-disc-facts! a rho)
          (dk-have! (mrr-tz B rf)
            (lambda ()
              (let* ((ls (dk-peel!))
                     (vs (map cadr (filter (lambda (fm) (and (mrr-op? fm 'IN 3) (equal? (caddr fm) B))) ls)))
                     (x1 (car vs)) (x2 (cadr vs)) (x3 (caddr vs))
                     (cv (list 'CONV3 x1 x2 x3))
                     (TR (list 'TRI-ROAD x1 x2 x3)) (TRD (list 'TRI-ROAD-DERIV x1 x2 x3))
                     (TT (list 'TRACE TR 0 3))
                     (li (lambda (g) (list 'LINE-INT g TR TRD 0 3)))
                     (sq (list 'VNB-LAMBDA 'k 'NN (list 'LINE-INT '(fam k) TR TRD 0 3))))
                (for-each (lambda (x) (fact 'subset-mem-fwd B 'u x) (fact 'subset-mem-fwd 'u 'CC x)) vs)
                (fact 'subset-trans cv B 'u)
                (dk-cite! 'tri-int-restrict 'u 'f B x1 x2 x3)
                (dk-cite! 'tri-int-is-line-int-conv3 'u 'f x1 x2 x3)
                (dk-cite! 'tri-road-is-road x1 x2 x3)
                ;; the trace of the triangle road lies in its hull
                (dk-split-all! (list (dk-cite! 'seg-trace-in-conv3 x1 x2 x3)))
                (dk-cite! 'tri-road-trace x1 x2 x3)
                (dk-have! (list 'SUBSET TT cv)
                  (lambda ()
                    (let* ((y (subset-by-element!))
                           (s12 (mrr-segtr x1 x2)) (s23 (mrr-segtr x2 x3)) (s31 (mrr-segtr x3 x1))
                           (un (list 'UNION (list 'UNION s12 s23) s31)))
                      (dk-have! (list 'IN y un) (lambda () (subst (list '= un TT)) (dk-ass!)))
                      (fact 'union-membership (list 'UNION s12 s23) s31 y)
                      (fact 'union-membership s12 s23 y)
                      (for-each (lambda (sg) (dk-have! (list 'IMPLIES (list 'IN y sg) (list 'IN y cv))
                                               (lambda () (di) (fact 'subset-mem-fwd sg cv y) (dk-ass!))))
                                (list s12 s23 s31))
                      (if (dk-only! (list 'IN y un)
                                    (list 'IFF (list 'IN y un) (list 'OR (list 'IN y (list 'UNION s12 s23)) (list 'IN y s31)))
                                    (list 'IFF (list 'IN y (list 'UNION s12 s23)) (list 'OR (list 'IN y s12) (list 'IN y s23)))
                                    (list 'IMPLIES (list 'IN y s12) (list 'IN y cv))
                                    (list 'IMPLIES (list 'IN y s23) (list 'IN y cv))
                                    (list 'IMPLIES (list 'IN y s31) (list 'IN y cv)))
                          (prop)))))
                (fact 'subset-trans TT cv B)
                (fact 'subset-trans TT B 'u)
                ;; each member of the sequence has triangle integral 0 (Goursat), as a line integral
                (dk-have! (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (list '= (li '(fam k)) 0)))
                  (lambda ()
                    (let ((k (dk-di-var!)))
                      (dk-apply! (dk-ctx-form mrr-famhol) k)
                      (dk-apply! (dk-ctx-form '(FORALL k (IMPLIES (IN k NN) (IN (fam k) (FUN u CC))))) k)
                      (dk-apply! (dk-ctx-form (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (mrr-cont 'u '(fam k))))) k)
                      (dk-cite! 'goursat-triangle 'u (list 'fam k) x1 x2 x3)
                      (dk-cite! 'tri-int-is-line-int-conv3 'u (list 'fam k) x1 x2 x3)
                      (subst (list '= (li (list 'fam k)) (list 'TRI-INT (list 'fam k) x1 x2 x3)))
                      (dk-ass!))))
                ;; the uniform bound on the trace
                (dk-have! (mrr-unif TT)
                  (lambda ()
                    (let* ((eps (cadr (car (filter (dk-head? 'POS-RR) (dk-peel!)))))
                           (N (dk-skolem! (dk-apply! ub eps)))
                           (ubN (dk-pick (lambda (fm) (and (mrr-op? fm 'FORALL 3) (dk-contains? fm N) (dk-contains? fm eps))) "the uniform bound")))
                      (dk-split-all!)
                      (ew N)
                      (dk-conj-close!
                        (lambda ()
                          (if (not (eq? (mrr-hd (dk-goal)) 'FORALL))
                              (dk-ass!)
                              (let* ((lk (dk-peel!))
                                     (k (cadr (car (filter (lambda (fm) (and (mrr-op? fm 'IN 3) (eq? (caddr fm) 'NN))) lk))))
                                     (y (cadr (car (filter (lambda (fm) (and (mrr-op? fm 'IN 3) (equal? (caddr fm) TT))) lk)))))
                                (fact 'subset-mem-fwd TT B y)
                                (dk-apply! ubN k y)
                                (dk-ass!))))))))
                (dk-cite! 'line-int-of-uniform-limit 'u TR TRD 0 3 'f 'fam)
                ;; the sequence of integrals is constantly 0, so its limit is 0
                (dk-have! (list 'IN sq '(FUN NN CC))
                  (lambda ()
                    (dk-lam-type!
                      (lambda ()
                        (let ((k (dk-di-var!)))
                          (dk-apply! (dk-ctx-form (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (list '= (li '(fam k)) 0)))) k)
                          (fact 'cc-zero-in)
                          (subst (list '= (li (list 'fam k)) 0))
                          (dk-ass!))))))
                (dk-have! (list 'CONVERGES-TO 'CC-MS sq 0)
                  (lambda ()
                    (mac 'converges-to)
                    (fact 'cc-zero-in)
                    (dk-conj-close!
                      (lambda ()
                        (let ((g (dk-goal)))
                          (cond ((dk-asm? g) (ass))
                                ((eq? (mrr-hd g) 'IN) (subst '(== (PTS CC-MS) CC)) (dk-ass!))
                                (#t
                                 (let ((eps (cadr (car (filter (dk-head? 'POS-RR) (dk-peel!))))))
                                   (fact 'rr-pos-rr-in-rr eps)
                                   (fact 'rr-lt-of-pos-rr eps)
                                   (fact 'nn-zero-in)
                                   (ew 0)
                                   (dk-conj-close!
                                     (lambda ()
                                       (if (not (eq? (mrr-hd (dk-goal)) 'FORALL))
                                           (dk-ass!)
                                           (let* ((lk (dk-peel!))
                                                  (nk (cadr (car (filter (lambda (fm) (and (mrr-op? fm 'IN 3) (eq? (caddr fm) 'NN))) lk)))))
                                             (dk-apply! (dk-ctx-form (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (list '= (li '(fam k)) 0)))) nk)
                                             (dk-lam-b!)
                                             (subst (list '= (li (list 'fam nk)) 0))
                                             (dk-have! '(IN 0 (PTS CC-MS)) (lambda () (subst '(== (PTS CC-MS) CC)) (dk-ass!)))
                                             (fact 'cc-ms-dist 0 0)
                                             (subst '(== ((DIST CC-MS) 0 0) (magnitude (- 0 0))))
                                             (dk-have! '(= (- 0 0) 0) (lambda () (crs)))
                                             (subst '(= (- 0 0) 0))
                                             (fact 'cc-magnitude-zero)
                                             (subst '(= (magnitude 0) 0))
                                             (dk-ineq! (list '< 0 eps))))))))))))))
                (dk-cite! 'line-int-in-cc 'u 'f TR TRD 0 3)
                (dk-cite! 'cc-limit-unique sq (li 'f) 0)
                (subst (list '= (list 'TRI-INT rf x1 x2 x3) (list 'TRI-INT 'f x1 x2 x3)))
                (subst (list '= (list 'TRI-INT 'f x1 x2 x3) (li 'f)))
                (dk-ass!))))
          (let ((l (mrr-local-diff! a rho)))
            (ew l)
            (dk-ass!))))))
(qed 'holomorphic-uniform-limit-conditional)

;;; ======================================================================
;;; (5) THE BRIDGE TO CA-3's `holomorphic-deriv-holomorphic' AND THE TWO THEOREMS
;;; CONDITIONAL ON IT VERBATIM: mrr-H follows from it (the derivative read off by
;;; cc-deriv-on-of-is-diff-on), so at integration each theorem below is one detachment.
;;; ======================================================================
(define mrr-HCIF
  '(FORALL u (FORALL f (IMPLIES (HOLOMORPHIC-ON u f)
     (HOLOMORPHIC-ON u (VNB-LAMBDA cifdw_ u (DERIV-ON CC-NORMED-FIELD u f cifdw_)))))))

(sp (make-wff (list 'IMPLIES mrr-HCIF mrr-H)))
(dk-peel!)
(let* ((dl '(VNB-LAMBDA cifdw_ mrhv_ (DERIV-ON CC-NORMED-FIELD mrhv_ mrhg_ cifdw_)))
       (ptw (dk-ctx-form '(FORALL mrhz_ (IMPLIES (IN mrhz_ mrhv_) (IS-DIFF-ON CC-NORMED-FIELD mrhv_ mrhg_ mrhz_ (mrhd_ mrhz_)))))))
  (dk-apply! (dk-ctx-form mrr-HCIF) 'mrhv_ 'mrhg_)
  (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES '(IN hbx_ mrhv_) (list '== '(mrhd_ hbx_) (list dl 'hbx_))))
    (lambda ()
      (let ((z (dk-di-var!)))
        (dk-apply! ptw z)
        (dk-cite! 'cc-deriv-on-of-is-diff-on 'mrhv_ 'mrhg_ z (list 'mrhd_ z))
        (fact 'fun-apply-type-c 'mrhd_ 'mrhv_ 'CC z)
        (dk-lam-b!)
        (subst (list '= (list 'DERIV-ON 'CC-NORMED-FIELD 'mrhv_ 'mrhg_ z) (list 'mrhd_ z)))
        (if (pair? (dk-open-leaves)) (if (dk-asm? (dk-goal)) (ass) (qrfl))))))
  (dk-cite! 'holomorphic-transfer-ptwise-eq 'mrhv_ 'mrhd_ dl)
  (dk-ass!))
(qed 'deriv-holomorphic-bridge)

(define (mrr-via-bridge! name)
  (di)
  (dk-cite! 'deriv-holomorphic-bridge)
  (dk-cite! name)
  (dk-ass!))

(sp (make-wff (list 'IMPLIES mrr-HCIF
  (list 'FORALL 'u (list 'IMPLIES (list 'IS-OPEN mrr-nfm 'u) (list 'FORALL 'f
    (mrr-imps (list '(IN f (FUN u CC)) (mrr-cont 'u 'f) (mrr-tz 'u 'f)) '(HOLOMORPHIC-ON u f))))))))
(mrr-via-bridge! 'morera-conditional)
(qed 'morera-of-deriv-holomorphic)

(sp (make-wff (list 'IMPLIES mrr-HCIF
  (list 'FORALL 'u (list 'IMPLIES (list 'IS-OPEN mrr-nfm 'u)
    (list 'FORALL 'fam (list 'IMPLIES mrr-famhol
      (list 'FORALL 'f (mrr-imps (list '(IN f (FUN u CC)) mrr-LU) '(HOLOMORPHIC-ON u f))))))))))
(mrr-via-bridge! 'holomorphic-uniform-limit-conditional)
(qed 'holomorphic-uniform-limit-of-deriv-holomorphic)


;;; ======================================================================
;;; THE UNCONDITIONAL THEOREMS (integration, 2026-10-04).  CA-3's
;;; `holomorphic-deriv-holomorphic' (theorem-library/cauchy-integral-formula.scm,
;;; loaded before this file) is the hypothesis HCIF of the two theorems above:
;;; one citation discharges it.
;;; ======================================================================
(sp (make-wff (list 'FORALL 'u (list 'IMPLIES (list 'IS-OPEN mrr-nfm 'u)
  (list 'FORALL 'f (mrr-imps (list '(IN f (FUN u CC)) (mrr-cont 'u 'f) (mrr-tz 'u 'f))
                             '(HOLOMORPHIC-ON u f)))))))
(fact 'holomorphic-deriv-holomorphic)
(fact 'morera-of-deriv-holomorphic)
(dk-ass!)
(qed 'morera)
(topic! 'morera 'analysis)
(alias! 'morera "Morera's theorem: a continuous function on an open set whose integral over every triangle in the set vanishes is holomorphic")

(sp (make-wff (list 'FORALL 'u (list 'IMPLIES (list 'IS-OPEN mrr-nfm 'u)
  (list 'FORALL 'fam (list 'IMPLIES mrr-famhol
    (list 'FORALL 'f (mrr-imps (list '(IN f (FUN u CC)) mrr-LU) '(HOLOMORPHIC-ON u f)))))))))
(fact 'holomorphic-deriv-holomorphic)
(fact 'holomorphic-uniform-limit-of-deriv-holomorphic)
(dk-ass!)
(qed 'holomorphic-uniform-limit)
(topic! 'holomorphic-uniform-limit 'analysis)
(alias! 'holomorphic-uniform-limit "a locally uniform limit of holomorphic functions on an open set is holomorphic")
