;;; onesided-limits.scm -- docs/calculus.pdf Ch 4 Sec 1.
;;; Continuity at x gives BOTH one-sided limits at x, with value f(x).  Both
;;; `modulo 0'.  The two drivers are the same text with IS-RIGHT-LIMIT swapped
;;; for IS-LEFT-LIMIT: the interval side is the only difference, and `ineq!'
;;; closes the |x - t| bound from the same premises either way.
;;;
;;; With these, "a function continuous on [a,b] is REGULATED there" -- hence
;;; integrable in the notes' sense -- is assembly rather than an eps/delta
;;; argument.
;;; Continuity at x gives BOTH one-sided limits at x, with value f(x).
;;; Both `modulo 0'.  The two drivers are literally the same text with
;;; IS-RIGHT-LIMIT swapped for IS-LEFT-LIMIT: the interval side is the only
;;; difference and `ineq' closes the bound from the same three premises.
(define (rl-focus-goal! pred)
  (let ((hit (find-first (lambda (n) (pred (wff-formula (sequent-node-assertion n))))
                         (proof-leaves))))
    (if (not hit) (error "rl-focus-goal!: no open leaf matches"))
    (dk-focus! hit)))
(sp (make-wff '(FORALL f (FORALL x
   (IMPLIES (IN f (FUN RR RR))
   (IMPLIES (IN x RR)
   (IMPLIES (IS-CONTINUOUS-AT RR-MS RR-MS f x)
            (IS-RIGHT-LIMIT f x (f x)))))))))
(quietly (lambda ()
  (di) (di) (di) (di) (mac 'IS-RIGHT-LIMIT)
  (fact 'fun-apply-type-c 'f 'RR 'RR 'x)
  (di) (focus 2) (di) (focus 3) (di) (focus 4)
  (ass-all) (focus 1) (di) (di)
  (mac-h 'IS-CONTINUOUS-AT '(IS-CONTINUOUS-AT RR-MS RR-MS f x))
  (dk-split! (car (dk-asms)))))
(quietly (lambda () (inst+ 1 (quote eps_))))
(define rl-witness #f)
(quietly (lambda ()
  (let ((before (free-vars (if (wff? (car (dk-asms))) (wff-formula (car (dk-asms))) (car (dk-asms))))))
    (ai 1)
    (let* ((after (free-vars (if (wff? (car (dk-asms))) (wff-formula (car (dk-asms))) (car (dk-asms)))))
           (new   (filter (lambda (v) (not (memq v before))) after)))
      (if (not (= 1 (length new)))
          (error "rl: expected exactly one new eigenvariable" new))
      (set! rl-witness (car new))))))
(quietly (lambda ()
  (dk-split! (car (dk-asms)))
  (ew rl-witness)))
(quietly (lambda ()
  (di) (focus 1) (ass-all) (focus 1) (di) (di) (di)))
(quietly (lambda () (dk-split! (car (dk-asms)))))
(quietly (lambda ()
  (mac-h 'pos-rr (list 'POS-RR rl-witness))
  (dk-split! (car (dk-asms)))
  (fact 'rr-sub-in-rr 'x 't_)))
(have! (list '<= (list 'ABS (list '- 'x 't_)) rl-witness)
       (lambda ()
         (mac 'rr-abs-bound)
         (di) (ineq!)
         (rl-focus-goal! (lambda (g) (equal? g (list '<= (list '- 'x 't_) rl-witness))))
         (ineq!)))
(quietly (lambda () (fact 'fun-apply-type-c 'f 'RR 'RR 't_)))
;; the metric-space forms of what we have
(have! (list '<= (list (list 'DIST 'RR-MS) 'x 't_) rl-witness)
       (lambda () (mac 'rr-ms-dist) (ass)))
(have! '(IN t_ (PTS RR-MS)) (lambda () (slot 'PTS) (ass)))
(define (rl-asm-index pred)
  (let loop ((as (dk-asms)) (i 1))
    (cond ((null? as) (error "rl-asm-index: no assumption matches"))
          ((pred (if (wff? (car as)) (wff-formula (car as)) (car as))) i)
          (else (loop (cdr as) (+ i 1))))))
(define (rl-mentions? f sub)
  (cond ((equal? f sub) #t)
        ((pair? f) (or (rl-mentions? (car f) sub) (rl-mentions? (cdr f) sub)))
        (else #f)))
(quietly (lambda ()
  (inst+ (rl-asm-index (lambda (f) (and (pair? f) (eq? (car f) 'FORALL)
                                        (rl-mentions? f (list 'PTS 'RR-MS))
                                        (rl-mentions? f 'eps_))))
         't_)))
(quietly (lambda ()
  (mac-h 'rr-ms-dist (list '<= (list (list 'DIST 'RR-MS) (list 'f 'x) (list 'f 't_)) 'eps_))
  (mac 'rr-abs-sub-sym)
  (ass)))
(qed 'continuous-at-right-limit)

(sp (make-wff '(FORALL f (FORALL x
   (IMPLIES (IN f (FUN RR RR))
   (IMPLIES (IN x RR)
   (IMPLIES (IS-CONTINUOUS-AT RR-MS RR-MS f x)
            (IS-LEFT-LIMIT f x (f x)))))))))
(quietly (lambda ()
  (di) (di) (di) (di) (mac 'IS-LEFT-LIMIT)
  (fact 'fun-apply-type-c 'f 'RR 'RR 'x)
  (di) (focus 2) (di) (focus 3) (di) (focus 4)
  (ass-all) (focus 1) (di) (di)
  (mac-h 'IS-CONTINUOUS-AT '(IS-CONTINUOUS-AT RR-MS RR-MS f x))
  (dk-split! (car (dk-asms)))))
(quietly (lambda () (inst+ 1 (quote eps_))))
(define rl-witness #f)
(quietly (lambda ()
  (let ((before (free-vars (if (wff? (car (dk-asms))) (wff-formula (car (dk-asms))) (car (dk-asms))))))
    (ai 1)
    (let* ((after (free-vars (if (wff? (car (dk-asms))) (wff-formula (car (dk-asms))) (car (dk-asms)))))
           (new   (filter (lambda (v) (not (memq v before))) after)))
      (if (not (= 1 (length new)))
          (error "rl: expected exactly one new eigenvariable" new))
      (set! rl-witness (car new))))))
(quietly (lambda ()
  (dk-split! (car (dk-asms)))
  (ew rl-witness)))
(quietly (lambda ()
  (di) (focus 1) (ass-all) (focus 1) (di) (di) (di)))
(quietly (lambda () (dk-split! (car (dk-asms)))))
(quietly (lambda ()
  (mac-h 'pos-rr (list 'POS-RR rl-witness))
  (dk-split! (car (dk-asms)))
  (fact 'rr-sub-in-rr 'x 't_)))
(have! (list '<= (list 'ABS (list '- 'x 't_)) rl-witness)
       (lambda ()
         (mac 'rr-abs-bound)
         (di) (ineq!)
         (rl-focus-goal! (lambda (g) (equal? g (list '<= (list '- 'x 't_) rl-witness))))
         (ineq!)))
(quietly (lambda () (fact 'fun-apply-type-c 'f 'RR 'RR 't_)))
;; the metric-space forms of what we have
(have! (list '<= (list (list 'DIST 'RR-MS) 'x 't_) rl-witness)
       (lambda () (mac 'rr-ms-dist) (ass)))
(have! '(IN t_ (PTS RR-MS)) (lambda () (slot 'PTS) (ass)))
(define (rl-asm-index pred)
  (let loop ((as (dk-asms)) (i 1))
    (cond ((null? as) (error "rl-asm-index: no assumption matches"))
          ((pred (if (wff? (car as)) (wff-formula (car as)) (car as))) i)
          (else (loop (cdr as) (+ i 1))))))
(define (rl-mentions? f sub)
  (cond ((equal? f sub) #t)
        ((pair? f) (or (rl-mentions? (car f) sub) (rl-mentions? (cdr f) sub)))
        (else #f)))
(quietly (lambda ()
  (inst+ (rl-asm-index (lambda (f) (and (pair? f) (eq? (car f) 'FORALL)
                                        (rl-mentions? f (list 'PTS 'RR-MS))
                                        (rl-mentions? f 'eps_))))
         't_)))
(quietly (lambda ()
  (mac-h 'rr-ms-dist (list '<= (list (list 'DIST 'RR-MS) (list 'f 'x) (list 'f 't_)) 'eps_))
  (mac 'rr-abs-sub-sym)
  (ass)))
(qed 'continuous-at-left-limit)
