;;; pivot-row-reduce-proof.scm -- Brick B3a (LA Phase B, algebraic-numbers.pdf
;;; ch.3): the ROW-reduction step, mirror of pivot-col-reduce.  Over a euclidean
;;; ring A, for P with nonzero pivot P_{1,1} and target row i/=1, there are q,r
;;; with (ELEM-G[-q,i,1] . P)_{i,1} = r and (r=0 or deg(r) < deg(P_{1,1})) -- one
;;; elementary ROW op (subtract q.(row 1) from row i) puts the euclidean remainder
;;; in the (i,1) slot.  Clears the first COLUMN, as pivot-col-reduce clears the
;;; first row.  Proof identical to pivot-col-reduce with elem-g-ROW-action (left
;;; mult) in place of elem-g-action; crs closes q.p11 + r + (-q).p11 = r.
(define (pc-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (pc-di*) (let lp () (let* ((g (pc-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (pc-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (pc-foc! n) (dk-focus! n))
(define (pc-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (pc-find pred) (let lp ((as (pc-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (pc-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (dk-focus! s) s)))
(sp (make-wff (quote (FORALL A (IMPLIES (IS-EUCLIDEAN-RING A) (FORALL m (FORALL n (FORALL P (FORALL i (IMPLIES (IN P (MAT m n (CARR A))) (IMPLIES (IN 1 (INTERVAL 1 m)) (IMPLIES (IN 1 (INTERVAL 1 n)) (IMPLIES (IN i (INTERVAL 1 m)) (IMPLIES (NOT (= i 1)) (IMPLIES (NOT (= (ENTRY P 1 1) (ZERO A))) (FORSOME q (AND (IN q (CARR A)) (FORSOME r (AND (IN r (CARR A)) (AND (= (ENTRY (MATMUL A (ELEM-G A m ((NEG A) q) i 1) P) i 1) r) (OR (= r (ZERO A)) (<= (succ ((GAUGE A) r)) ((GAUGE A) (ENTRY P 1 1))))))))))))))))))))))))
(pc-di*)
(fact 'euclidean-ring-is-integral-domain 'A)
(fact 'integral-domain-is-commutative-ring 'A)
(fact 'commutative-ring-is-ring 'A)
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i '1)
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P '1 '1)
(fact 'euclidean-division 'A '(ENTRY P i 1) '(ENTRY P 1 1))
(ai 1) (ai 1) (ai 1) (ai 1) (ai 1)
(define DIV (pc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (equal? (cadr z) '(ENTRY P i 1))))))
(define Q (cadr (cadr (caddr DIV))))
(define R (caddr (caddr DIV)))
(define NEGQ (list (list 'NEG 'A) Q))
(define Pi1 '(ENTRY P i 1))
(define P11 '(ENTRY P 1 1))
(define NEWENT (list 'ENTRY (list 'MATMUL 'A (list 'ELEM-G 'A 'm NEGQ 'i 1) 'P) 'i 1))
(define GRHS (list (list 'ADD 'A) Pi1 (list (list 'MUL 'A) NEGQ P11)))
(define GIF (list 'IF '(= i i) GRHS Pi1))
(fact 'ring-neg-in-carr 'A Q)
(ew Q)
(di)
(pc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORSOME))))
(ew R)
(di)
(pc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'AND))))
(di)
(pc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (pair? (cadr g))
                               (eq? (car (cadr g)) 'ENTRY) (pair? (cadr (cadr g)))
                               (eq? (car (cadr (cadr g))) 'MATMUL))))
(fact 'elem-g-row-action 'A 'm 'n 'P NEGQ 'i 1 'i 1)
(subst (list '= NEWENT GIF))
(if-true GIF)
(define cont (pc-last)) (rfl) (pc-foc! cont)
(subst (list '= GIF GRHS))
(subst DIV)
(crs)
(pc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'IN) (equal? (cadr g) Q)))) (ass)
(pc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'IN) (equal? (cadr g) R)))) (ass)
(pc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'OR)))) (ass)
(qed 'pivot-row-reduce)
(topic! 'pivot-row-reduce 'algebra)
