;;; pss-categories.scm -- the PSS partition (PSS review, 2026-06-26).
;;;
;;; One (category! 'name 'cat) per live PSS support, filing it under a bucket
;;; from *pss-category-order* (macetes.scm).  The category is also the INTAKE
;;; DISCIPLINE: when a proof is blocked and a fact is asserted instead of
;;; ground out, the bucket records WHAT KIND of fact it is and why grinding is
;;; not worth it (see each section title's "why not grind" line in PSS.md).
;;;
;;; Loaded LAST (after every support is installed) so the -rev propagation and
;;; write-pss-md grouping see a complete table.  NEW supports should add their
;;; own (category! ...) -- inline after the statement (like warrant!) or here;
;;; load.scm soft-nudges any that stay unfiled.
;;;
;;; The eight buckets:
;;;   plumbing      typing / SEP-IMAGE-membership slices / base cases / carrier
;;;                 readouts / ord-segment + set-algebra -- the engine can't
;;;                 unfold these in the needed direction; naming them is cheaper
;;;                 than re-deriving a definition by hand.
;;;   inequalities  order chains, abs, SOS scalar + finite-sum inequalities,
;;;                 root monotonicity, eps-density -- the ineq/sos oracle does
;;;                 not reach it (roots, or it IS the oracle's spec).
;;;   combinatorial pigeonhole / diagonal / block / counting / choice-construction
;;;                 soundness / permutation-reindex / well-ordering -- a genuine
;;;                 but long induction+choice with no library payoff in grinding.
;;;   analysis      limits / series / completeness / summability / monotone
;;;                 convergence / sup-inf -- rests on order-completeness of RR
;;;                 not yet built as named lemmas; assert + cite the book.
;;;   algebra       ring / power / finsum-ring / sum-set / ideal identities and
;;;                 recurrences -- routine structural induction over a monoid /
;;;                 ring / group; the recursion is mechanical, the law reusable.
;;;   topology      open/closed sets, continuity, ball geometry, compactness
;;;                 characterisations -- textbook calculus.pdf; the statement is
;;;                 the interface other proofs cite, the proof is standard.
;;;   constructions metric-space constructions (bounded / product / completion /
;;;                 normed) -- mechanical re-verification of carrier + axioms
;;;                 for a built metric object.
;;;   set-quotient  set & quotient constructions (setoid equivalence, classes,
;;;                 descent, the universal property) -- mechanical verification
;;;                 of a quotient's defining mapping property.

;;; ===== plumbing & typing =====
(category! 'centres-mem-build 'plumbing)
(category! 'centres-in-carrier 'plumbing)
(category! 'centres-ball-eq 'plumbing)
(category! 'ball-cover-mem-fwd 'plumbing)
(category! 'centre-set-contains-choice 'plumbing)
(category! 'centre-set-finite 'plumbing)
(category! 'open-cover-covers-point 'plumbing)
(category! 'subset-mem-fwd 'plumbing)
(category! 'ball-point-le 'plumbing)
(category! 'ball-point-ne 'plumbing)
(category! 'range-membership 'plumbing)
(category! 'fun-range-membership 'plumbing)
(category! 'ran-subset-codomain 'plumbing)
(category! 'compose-type-2 'plumbing)
(category! 'compose-type-3 'plumbing)
(category! 'compose-type-4 'plumbing)
(category! 'compose-type-5 'plumbing)
(category! 'compose-apply 'plumbing)
(category! 'compose-type 'plumbing)
(category! 'gauges-mem-build 'plumbing)
(category! 'gauges-in-fun 'plumbing)
(category! 'gauges-spec 'plumbing)
(category! 'choose-in-nn 'plumbing)
(category! 'falling-in-nn 'plumbing)
(category! 'cauchy-seq-is-fun 'plumbing)
(category! 'subseq-is-fun 'plumbing)
(category! 'ball-membership 'plumbing)
(category! 'ball-is-set 'plumbing)
(category! 'metric-dist-real 'plumbing)
(category! 'nag-metric-carrier 'plumbing)
(category! 'nf-metric-carrier 'plumbing)
(category! 'bdd-metric-carrier 'plumbing)
(category! 'product-metric-carrier 'plumbing)
(category! 'nn-in-rr 'plumbing)
(category! 'nn-le-refl 'plumbing)
(category! 'fun-apply-type-c 'plumbing)
(category! 'ring-power-type 'plumbing)
(category! 'prod-ring-type 'plumbing)
(category! 'rpow-pos 'plumbing)
(category! 'sqrt-nonneg 'plumbing)
(category! 'power-real-closed 'plumbing)
(category! 'nn-minus-in-nn 'plumbing)
(category! 'ord-segment-insert 'plumbing)
(category! 'finsum-comm-monoid-type 'plumbing)
(category! 'finsum-type 'plumbing)
(category! 'finsum-empty 'plumbing)
(category! 'finsum-singleton 'plumbing)
(category! 'prod-ring-empty 'plumbing)
(category! 'prod-ring-singleton 'plumbing)
(category! 'card-singleton 'plumbing)
(category! 'enum-fam-in-fun 'plumbing)
(category! 'fin-enum-is-bijection 'plumbing)
(category! 'ord-segment-nn-subset 'plumbing)
(category! 'ord-segment-nn-succ 'plumbing)
(category! 'ord-segment-self 'plumbing)
(category! 'ord-segment-trans 'plumbing)
(category! 'ord-segment-zero-no-members 'plumbing)
(category! 'difference-membership 'plumbing)
(category! 'difference-set 'plumbing)
(category! 'card-subset-nn 'plumbing)
(category! 'card-power-nn 'plumbing)
(category! 'succ-nn-ord 'plumbing)
(category! 'union-empty-left 'plumbing)
(category! 'class-subset-carrier 'plumbing)
(category! 'class-is-set 'plumbing)
(category! 'quotient-is-set 'plumbing)
(category! 'proj-in-fun 'plumbing)
(category! 'class-in-quotient 'plumbing)
(category! 'class-self 'plumbing)

;;; ===== inequalities & order =====
(category! 'rr-lt-implies-le 'inequalities)
(category! 'rr-lt-trans 'inequalities)
(category! 'rr-le-trans 'inequalities)
(category! 'rr-le-trans-c 'inequalities)
(category! 'rr-lt-le-trans 'inequalities)
(category! 'rr-le-lt-trans 'inequalities)
(category! 'rr-le-add 'inequalities)
(category! 'rr-add-nonneg 'inequalities)
(category! 'rr-lt-add 'inequalities)
(category! 'rr-le-scale-nonneg 'inequalities)
(category! 'rr-lt-scale-pos 'inequalities)
(category! 'rr-le-abs 'inequalities)
(category! 'rr-abs-bound 'inequalities)
(category! 'rr-abs-reverse-triangle 'inequalities)
(category! 'rr-sq-nonneg 'inequalities)
(category! 'rr-le-from-diff-nonneg 'inequalities)
(category! 'rr-double-nonneg 'inequalities)
(category! 'nn-pair-upper-bound 'inequalities)
(category! 'rr-pos-halvable 'inequalities)
(category! 'rr-pos-shrink 'inequalities)
(category! 'rr-young-2 'inequalities)
(category! 'rr-amgm-2 'inequalities)
(category! 'rr-qm-am-2 'inequalities)
(category! 'rr-cauchy-schwarz-2 'inequalities)
(category! 'rr-bernoulli 'inequalities)
(category! 'bdd-fn-nonneg 'inequalities)
(category! 'bdd-fn-lt-one 'inequalities)
(category! 'bdd-fn-le-arg 'inequalities)
(category! 'bdd-fn-mono 'inequalities)
(category! 'bdd-fn-subadd 'inequalities)
(category! 'rpow-mono-base 'inequalities)
(category! 'rpow-mono-exp-ge1 'inequalities)
(category! 'rpow-mono-exp-le1 'inequalities)
(category! 'sqrt-mono 'inequalities)
(category! 'amgm-2-sqrt 'inequalities)
(category! 'young-inequality 'inequalities)
(category! 'bernoulli-rpow 'inequalities)
(category! 'finsum-sq-nonneg 'inequalities)
(category! 'finsum-le-termwise 'inequalities)
(category! 'finsum-abs-triangle 'inequalities)
(category! 'cauchy-schwarz-finite 'inequalities)
(category! 'cauchy-schwarz-sqrt 'inequalities)
(category! 'minkowski-l2 'inequalities)
(category! 'holder-finite 'inequalities)

;;; ===== combinatorial constructions =====
(category! 'injection-extension-recurrence 'combinatorial)
(category! 'permutations-zero 'combinatorial)
(category! 'permutation-recurrence 'combinatorial)
(category! 'choose-n-0 'combinatorial)
(category! 'choose-0-succ 'combinatorial)
(category! 'choose-succ 'combinatorial)
(category! 'injection-count-falling 'combinatorial)
(category! 'choose-times-factorial 'combinatorial)
(category! 'binomial-theorem 'combinatorial)
(category! 'cover-block-step 'combinatorial)
(category! 'block-family-combinatorial 'combinatorial)
(category! 'tb-has-eps-cauchy-subseq 'combinatorial)
(category! 'tb-block-step 'combinatorial)
(category! 'tb-rad-ball-cover 'combinatorial)
(category! 'cauchy-block-estimate 'combinatorial)
(category! 'block-family 'combinatorial)
(category! 'totally-bounded-has-cauchy-subseq-rad 'combinatorial)
(category! 'strictly-mono-ge-id 'combinatorial)
(category! 'null-rr-seq-exists 'combinatorial)
(category! 'dc-on-nn 'combinatorial)
(category! 'dc-on-nn-pred 'combinatorial)
;; diagonalization is now PROVEN (not a support); its three generic leaves:
(category! 'nn-step-strictly-mono 'combinatorial)
(category! 'nn-nested-subset-chain 'combinatorial)
(category! 'inf-subset-nn-unbounded 'combinatorial)
(category! 'pigeonhole-infinite 'combinatorial)
(category! 'convergence-block-tower 'combinatorial)
(category! 'coordinatewise-diagonal-subseq 'combinatorial)
(category! 'subsequence-capture 'combinatorial)
(category! 'nn-enum-spec 'combinatorial)
(category! 'well-ordering-principle 'combinatorial)
(category! 'ord-well-ordered 'combinatorial)
(category! 'power-insert-cover 'combinatorial)
(category! 'power-insert-disjoint 'combinatorial)
(category! 'prod-of-sums-expansion 'combinatorial)
(category! 'finsum-fubini 'combinatorial)
(category! 'finsum-reindex 'combinatorial)
(category! 'sum-ag-permutation-invariance 'combinatorial)
(category! 'finsum-comm-monoid-permutation-invariance 'combinatorial)
(category! 'finsum-well-defined 'combinatorial)
(category! 'finsum-comm-monoid-well-defined 'combinatorial)
(category! 'chosen-centre-is-centre 'combinatorial)
(category! 'finite-ball-subcover-r-net 'combinatorial)

;;; ===== real analysis: limits, series, completeness =====
(category! 'ratio-test-converges 'analysis)
(category! 'ps-abs-term 'analysis)
(category! 'ps-absolute-implies-convergent 'analysis)
(category! 'ps-partial-sum-as-series 'analysis)
(category! 'ps-converges-as-series 'analysis)
(category! 'geometric-partial-sum 'analysis)
(category! 'geometric-series-converges-to 'analysis)
(category! 'comparison-test 'analysis)
(category! 'monotone-convergence-rr 'analysis)
(category! 'series-partial-sum-monotone-nonneg 'analysis)
(category! 'series-partial-sum-le-termwise 'analysis)
(category! 'series-partial-sum-abs-le 'analysis)
(category! 'series-cauchy-criterion 'analysis)
(category! 'absolute-summable-implies-summable 'analysis)
(category! 'summable-bound-implies-cauchy 'analysis)
(category! 'summable-bound-converges 'analysis)
(category! 'esum-finite-iff-bounded 'analysis)
(category! 'rr-le-all-pos-nonpos 'analysis)
(category! 'cauchy-cluster-converges 'analysis)
(category! 'cauchy-rapid-subsequence 'analysis)

;;; ===== algebraic & ring-structure facts =====
(category! 'ring-power-zero 'algebra)
(category! 'ring-power-one 'algebra)
(category! 'ring-power-add 'algebra)
(category! 'ring-power-mult 'algebra)
(category! 'ring-power-succ 'algebra)
(category! 'rpow-zero 'algebra)
(category! 'rpow-one 'algebra)
(category! 'rpow-add 'algebra)
(category! 'rpow-mul-base 'algebra)
(category! 'rpow-pow 'algebra)
(category! 'rpow-neg 'algebra)
(category! 'rpow-nat 'algebra)
(category! 'rpow-zero-base 'algebra)
(category! 'rpow-zero-zero 'algebra)
(category! 'sqrt-sq 'algebra)
(category! 'sqrt-of-sq 'algebra)
(category! 'sqrt-rpow 'algebra)
(category! 'sqrt-mul 'algebra)
(category! 'finsum-add 'algebra)
(category! 'finsum-ring-distrib-left 'algebra)
(category! 'finsum-ring-scalar-zz 'algebra)
(category! 'finsum-insert 'algebra)
(category! 'prod-ring-insert 'algebra)
(category! 'sum-set-left-scalar 'algebra)
(category! 'sum-set-right-scalar 'algebra)
(category! 'euclidean-ring-has-gauge 'algebra)
(category! 'gauge-is-degree 'algebra)
(category! 'ideal-elt-in-carrier 'algebra)
(category! 'principal-ideal-in-ideal 'algebra)
(category! 'euclidean-ideal-has-generator 'algebra)

;;; ===== metric topology & continuity =====
(category! 'compact-iff-tb-complete 'topology)
(category! 'compact-iff-cluster-point 'topology)
(category! 'compact-iff-fip 'topology)
(category! 'ball-cover-is-open-cover 'topology)
(category! 'compact-implies-totally-bounded 'topology)
(category! 'compact-implies-complete 'topology)
(category! 'compact-seq-has-cluster 'topology)
(category! 'empty-is-open 'topology)
(category! 'carrier-is-open 'topology)
(category! 'ball-is-open 'topology)
(category! 'union-of-opens-open 'topology)
(category! 'inter-of-opens-open 'topology)
(category! 'continuous-implies-open-preimage 'topology)
(category! 'open-preimage-implies-continuous 'topology)
(category! 'preimage-complement 'topology)
(category! 'continuous-implies-closed-preimage 'topology)
(category! 'closed-preimage-implies-continuous 'topology)
(category! 'ball-mem-from-le 'topology)
(category! 'ball-center-in 'topology)
(category! 'ball-2r-triangle 'topology)
(category! 'continuous-is-continuous-at 'topology)
(category! 'uniformly-continuous-is-continuous 'topology)
(category! 'compact-iff-seq-compact 'topology)
(category! 'seq-compact-countable-product 'topology)

;;; ===== metric-space + quotient constructions =====
(category! 'bdd-metric-distance 'constructions)
(category! 'bdd-metric-is-metric-space 'constructions)
(category! 'bdd-metric-bounded 'constructions)
(category! 'bdd-metric-id-bicontinuous 'constructions)
(category! 'rr-bounded-ms-is-metric-space 'constructions)
(category! 'rr-bounded-ms-bounded 'constructions)
(category! 'rr-bounded-equivalent 'constructions)
(category! 'product-weighted-summable 'constructions)
(category! 'product-is-metric-space 'constructions)
(category! 'product-projection-continuous 'constructions)
(category! 'product-convergence-coordinatewise 'constructions)
(category! 'product-weights-equivalent 'constructions)
(category! 'product-metric-default-summable 'constructions)
(category! 'completion-is-metric-space 'constructions)
(category! 'completion-is-complete 'constructions)
(category! 'embed-in-fun 'constructions)
(category! 'embed-isometry 'constructions)
(category! 'nag-metric-distance 'constructions)
(category! 'nag-metric-space-is-metric-space 'constructions)
(category! 'nf-metric-distance 'constructions)
(category! 'nf-metric-space-is-metric-space 'constructions)

;;; ===== set & quotient constructions =====
;;; The setoid/quotient construction (equivalence classes, descent, the
;;; universal property).  Why not grind: mechanical verification of the
;;; quotient's defining mapping property over the CLASS/QUOTIENT/DESCEND
;;; machinery.  (The plumbing-grade quotient TYPING slices -- class-is-set,
;;; quotient-is-set, proj-in-fun, class-in-quotient, class-subset-carrier,
;;; class-self -- stay under `plumbing' by KIND, not topic.)
(category! 'cauchy-setoid-is-setoid 'set-quotient)
(category! 'class-eq-iff 'set-quotient)
(category! 'class-disjoint 'set-quotient)
(category! 'descend-computes 'set-quotient)
(category! 'descend-in-fun 'set-quotient)
(category! 'quotient-universal 'set-quotient)
