;;; theorem-library/rake-algebra3.scm -- rake batch 5, batch V (algebra leftovers).
;;;
;;; FOUR theorems, each PROVEN modulo 0, each the LITERAL statement of an
;;; asserted PSS support (copied from its site) except `card-bijection-eq',
;;; which is new and is the brick the other two needed:
;;;
;;;   qq-nonneg-is-fraction   structure-library/qq-fractions.scm:43   (retire)
;;;   card-bijection-eq       NEW
;;;   finsum-reindex          theorem-library/finsum-additive.scm:173 (retire)
;;;   finsum-reindex-ag       theorem-library/finsum-additive.scm:213 (retire)
;;;
;;; LOAD WINDOW [266, end).  lo = 266 is forced by `bijection-in-fun' /
;;; `bijection-surjective' (structure-library/bijection-derived, 265); the next
;;; deepest citations are enum-fam-value (rake-finsum-laws, 245),
;;; finsum-well-defined / finsum-comm-monoid-well-defined /
;;; sum-ag-segment-congruence (rake-finsum-welldef, 230), zz-trichotomy /
;;; zz-nonneg-in-nn (zz-order, 222), fin-enum-is-bijection (rake-inverse-bij,
;;; 194), bijection-compose / fun-domain-in-set (rake-analysis2, 193),
;;; fun-apply-type-c (fun-apply-type-proof, 162), eq-sym (equality-basics, 148).
;;; NOTHING forces hi: none of the three retired supports is cited by any proof
;;; in the tree (checked by grep; they are all off-bill, which is why they are
;;; in batch 5 at all).
;;;
;;; Helper prefix: r5v-.

;;; ---- plumbing ---------------------------------------------------------

;;; The arithmetic premises of the context, by 1-BASED index (the oracle's
;;; convention, ineq-oracle.scm:206).  A bare `(ineq)' names none and refuses;
;;; a non-relational premise poisons the call.  zz-order.scm's `zo-ineq!'.
;;; NAME THE PREMISES, never a shape scan: the context here holds
;;; q = za * recip(zb), an `=' that is arithmetic in SHAPE, and the atom
;;; recip(zb) can never be certified in RR -- one such premise refuses the
;;; whole call and the message blames the goal (CLAUDE.md, the `contra' entry).
(define (r5v-ineq-on! . fs)
  (let ((asms (dk-asms)))
    (apply ineq
           (map (lambda (f)
                  (let loop ((l asms) (i 1))
                    (cond ((null? l) (error "r5v-ineq-on!: premise not in context"
                                            (expression->string f)))
                          ((equal? (car l) f) i)
                          (#t (loop (cdr l) (+ i 1))))))
                fs))))

(define (r5v-done! name)
  (if (proof-done? *ps*)
      (begin (qed name) (topic! name 'algebra))
      (begin
        (display "\n*** rake-algebra3: ") (display name)
        (display " did NOT close.  Open goals:\n")
        (for-each (lambda (l)
                    (display "   GOAL: ")
                    (display (expression->string (dk-goal-of l))) (newline)
                    (for-each (lambda (a)
                                (display "      asm: ")
                                (display (expression->string a)) (newline))
                              (dk-asms-of l)))
                  (proof-leaves))
        (display "*** end ") (display name) (newline))))

;;; =====================================================================
;;; (1) qq-nonneg-is-fraction -- structure-library/qq-fractions.scm:43
;;;
;;;   forall q. q in QQ and 0 <= q  =>
;;;     forsome a in NN, b in NN with b /= 0 and q * b = a.
;;;
;;; The support's warrant says this is asserted because "number-systems.scm
;;; introduces QQ as a primitive field containing ZZ and never says it is
;;; generated by quotients".  That changed on 2026-08-01: `qq-is-fraction'
;;; (number-systems.scm:324, PRIMITIVE) says exactly that, with recip.  The
;;; note in qq-fractions.scm says deriving the non-negative form from it
;;; "needs a sign split and a ZZ -> NN bridge the library does not have" --
;;; the bridge is `zz-nonneg-in-nn' (theorem-library/zz-order.scm, PROVEN
;;; 2026-09-16) and the sign split is `zz-trichotomy' from the same file.
;;;
;;; q = za * recip(zb) with za, zb in ZZ, zb /= 0.  If zb > 0 take
;;; (a, b) := (za, zb); if zb < 0 take (a, b) := (-za, -zb).  In both cases
;;; q * b = a is one `crs' either side of rr-recip-inverse, and 0 <= a is
;;; rr-leq-mul-nonneg on 0 <= q and 0 <= b.
;;; =====================================================================

(define r5v-qq-stmt
  '(FORALL q
     (IMPLIES (AND (IN q QQ) (<= 0 q))
       (FORSOME a
         (AND (IN a NN)
              (FORSOME b
                (AND (IN b NN)
                     (AND (NOT (= b 0))
                          (= (* q b) a)))))))))

;; close (AND (IN A NN) (FORSOME b ...)) by exhibiting B; every conjunct is
;; already in the context.
(define (r5v-witness! bb)
  (dk-conj-close!
   (lambda ()
     (let ((g (dk-goal)))
       (if (and (pair? g) (eq? (car g) 'FORSOME))
           (begin (ew bb) (dk-conj-close!))
           (from-context!))))))

;; q * B = A, where q = za * recip(zb) is in context and B is zb or (- zb).
;; recip(zb) is opaque to `crs', so the reciprocal is cancelled by hand.
(define (r5v-prod-eq! qeq za zb bb aa recip-eq)
  (let ((rz (list 'recip zb)))
    (have! (list '= (list '* 'q bb) aa)
      (lambda ()
        (subst qeq)                              ; q := za * recip(zb)
        (let ((lhs (list '* (list '* za rz) bb))
              (mid (if (equal? bb zb)
                       (list '* za (list '* zb rz))
                       (list '- (list '* za (list '* zb rz))))))
          (have! (list '= lhs mid) (lambda () (crs)))
          (subst (list '= lhs mid))
          (subst recip-eq)                       ; zb * recip(zb) := 1
          (crs))))
    (list '= (list '* 'q bb) aa)))

(sp (make-wff r5v-qq-stmt))
(dk-peel!)
(dk-split! '(AND (IN q QQ) (<= 0 q)))
(fact 'rr-zero-in)
(fact 'qq-subset-rr 'q)                          ; q in RR

(let* ((ex   (dk-fact! 'qq-is-fraction 'q))
       (za   (dk-skolem! ex))
       (inner (dk-pick (dk-head? 'FORSOME) "the inner fraction existential"))
       (zb   (dk-skolem! inner))
       (rz   (list 'recip zb))
       (qeq  (list '= 'q (list '* za rz)))
       (nzb  (list 'NOT (list '= zb 0))))
  (fact 'zz-in-rr za)
  (fact 'zz-in-rr zb)
  (have! (list 'AND (list 'IN zb 'RR) nzb))
  (fact 'rr-recip-closed zb)                     ; recip(zb) in RR -- `crs' wants it typed
  (fact 'rr-recip-inverse zb)                    ; zb * recip(zb) = 1
  (fact 'zz-trichotomy zb)                       ; zb < 0 or zb = 0 or 0 < zb
  (let ((recip-eq (list '= (list '* zb rz) 1)))
    (use-cases (list (list '< zb 0) (list '= zb 0) (list '< 0 zb))
      ;; ---- zb < 0 : (a, b) := (-za, -zb) -------------------------------
      (lambda ()
        (let ((bb (list '- zb)) (aa (list '- za)))
          (fact 'zz-neg-closed zb)
          (fact 'rr-neg-closed zb)
          (fact 'zz-neg-closed za)
          (fact 'rr-neg-closed za)
          (have! (list '< 0 bb) (lambda () (r5v-ineq-on! (list '< zb 0))))
          (have! (list '<= 0 bb) (lambda () (r5v-ineq-on! (list '< zb 0))))
          (fact 'rr-pos-ne-zero bb)
          (have! (list 'AND '(IN q RR) (list 'IN bb 'RR)))
          (have! (list 'AND '(<= 0 q) (list '<= 0 bb)))
          (fact 'rr-leq-mul-nonneg 'q bb)        ; 0 <= q * (-zb)
          (let ((pe (r5v-prod-eq! qeq za zb bb aa recip-eq)))
            (have! (list '<= 0 aa)
              (lambda () (fact 'eq-sym (list '* 'q bb) aa)
                         (subst (list '= aa (list '* 'q bb)))
                         (ass)))
            (fact 'zz-nonneg-in-nn aa)
            (fact 'zz-nonneg-in-nn bb)
            (ew aa)
            (r5v-witness! bb))))
      ;; ---- zb = 0 : contradicts the hypothesis --------------------------
      (lambda () (ai nzb))
      ;; ---- 0 < zb : (a, b) := (za, zb) ---------------------------------
      (lambda ()
        (have! (list '<= 0 zb) (lambda () (r5v-ineq-on! (list '< 0 zb))))
        (have! (list 'AND '(IN q RR) (list 'IN zb 'RR)))
        (have! (list 'AND '(<= 0 q) (list '<= 0 zb)))
        (fact 'rr-leq-mul-nonneg 'q zb)          ; 0 <= q * zb
        (let ((pe (r5v-prod-eq! qeq za zb zb za recip-eq)))
          (have! (list '<= 0 za)
            (lambda () (fact 'eq-sym (list '* 'q zb) za)
                       (subst (list '= za (list '* 'q zb)))
                       (ass)))
          (fact 'zz-nonneg-in-nn za)
          (fact 'zz-nonneg-in-nn zb)
          (ew za)
          (r5v-witness! zb))))))

(r5v-done! 'qq-nonneg-is-fraction)

;;; =====================================================================
;;; (2) card-bijection-eq -- NEW.  A bijection out of a finite set transports
;;; the cardinal:
;;;
;;;   phi in BIJECTION(dm, cod), dm in SET, CARD dm in NN  =>  CARD cod = CARD dm.
;;;
;;; This is the card-layer lemma rake batch N left `finsum-reindex' /
;;; `finsum-reindex-ag' one short of ("they need CARD S = CARD T from a
;;; bijection, which the tree cannot conclude"; CLAUDE.md, the finsum floor
;;; entry).  It does NOT need pigeonhole: `card-image-injection' (primitive,
;;; structure-library/injection.scm:161) already says an injection preserves
;;; the cardinal of its domain, and a bijection is an injection whose IMAGE is
;;; the whole codomain.  So the only content is IMAGE(phi, dm) = cod, which is
;;; surjectivity (bijection-surjective) one way and fun-apply-type-c the other.
;;; =====================================================================

(sp (make-wff
  '(FORALL dm (FORALL cod (FORALL phi
     (IMPLIES (IN dm SET)
     (IMPLIES (IN (CARD dm) NN)
     (IMPLIES (IN phi (BIJECTION dm cod))
       (= (CARD cod) (CARD dm))))))))))
(dk-peel!)
(fact 'bijection-in-fun 'dm 'cod 'phi)
(fact 'bijection-is-injection 'dm 'cod 'phi)
(have! '(AND (IN phi (INJECTION dm cod)) (AND (IN dm SET) (IN (CARD dm) NN))))
(fact 'card-image-injection 'dm 'cod 'phi)       ; CARD(IMAGE phi dm) = CARD dm

(have! '(FORALL w_ (IFF (IN w_ (IMAGE phi dm)) (IN w_ cod)))
  (lambda ()
    (di)                                         ; peel w_; the IFF is left
    (for-each
     (lambda (l)
       (dk-focus! l)
       (if (equal? (dk-goal) '(IN w_ cod))
           ;; ---- w_ = phi(z) for some z in dm, and phi lands in cod --------
           (let* ((ex (dk-landed-1
                       (lambda () (mac-h 'image-membership-iff
                                         '(IN w_ (IMAGE phi dm))))))
                  (z  (dk-skolem! ex)))
             (fact 'fun-apply-type-c 'phi 'dm 'cod z)
             (fact 'eq-sym (list 'phi z) 'w_)
             (subst (list '= 'w_ (list 'phi z)))
             (ass))
           ;; ---- surjectivity -------------------------------------------
           (let* ((ex (dk-fact! 'bijection-surjective 'dm 'cod 'phi 'w_))
                  (z  (dk-skolem! ex)))
             (mac 'image-membership-iff)
             (ew z)
             (dk-conj-close!))))
     (dk-opened (lambda () (di))))))            ; split the IFF; antecedents land

(dk-focus-having! '(FORALL w_ (IFF (IN w_ (IMAGE phi dm)) (IN w_ cod))))
(fact 'class-extensionality '(IMAGE phi dm) 'cod)
(fact 'eq-sym '(IMAGE phi dm) 'cod)
(subst '(= cod (IMAGE phi dm)))
(ass)
(r5v-done! 'card-bijection-eq)

;;; =====================================================================
;;; (3) finsum-reindex  -- theorem-library/finsum-additive.scm:173
;;;     finsum-reindex-ag -- theorem-library/finsum-additive.scm:213
;;;
;;;   FINSUM(m, f, S) = FINSUM(m, z |-> f(phi z), T)   for phi : T -> S bijective
;;;
;;; Rake batch N left these two asserted for one reason only: "they need
;;; CARD S = CARD T from a bijection, which the tree cannot conclude"
;;; (CLAUDE.md).  With `card-bijection-eq' above they are a five-line
;;; assembly on top of the ENUMERATION-INDEPENDENCE floor batch N proved:
;;;
;;;   * FIN-ENUM(T) : OS(|T|) -> T is a bijection (fin-enum-is-bijection);
;;;   * so enm = (x_ |-> phi(FIN-ENUM(T)(x_))) : OS(|T|) -> S is one
;;;     (bijection-compose), and |S| = |T| makes it an enumeration OF S;
;;;   * finsum-well-defined evaluates FINSUM(m,f,S) along THAT enumeration;
;;;   * the two enumerated families then agree pointwise on the segment --
;;;     both are i |-> f(phi(FIN-ENUM(T)(i))) -- so the folds are equal
;;;     (sum-ag-segment-congruence).
;;;
;;; No permutation, no inverse bijection, no index shifting.
;;; =====================================================================

;; beta-reduce every applied VNB-LAMBDA in the goal (`lam-b' fires on one
;; redex; a second call on a goal with none is an inert no-op notice).
(define (r5v-redex? x)
  (cond ((not (pair? x)) #f)
        ((and (pair? (car x)) (eq? (caar x) 'VNB-LAMBDA)) #t)
        (#t (let loop ((l x))
              (cond ((not (pair? l)) #f)
                    ((r5v-redex? (car l)) #t)
                    (#t (loop (cdr l))))))))

(define (r5v-beta!)
  (let loop ((k 0))
    (if (and (< k 6) (r5v-redex? (dk-goal)))
        (begin (lam-b) (loop (+ k 1))))))

(define (r5v-reindex-stmt sv pred)
  `(FORALL ,sv (IMPLIES ,pred
     (FORALL S (IMPLIES (IN S SET) (IMPLIES (IN (CARD S) NN)
       (FORALL T (IMPLIES (AND (IN T SET) (IN (CARD T) NN))
         (FORALL phi (IMPLIES (IN phi (BIJECTION T S))
           (FORALL f (IMPLIES (IN f (FUN S (CARR ,sv)))
             (= (FINSUM ,sv f S)
                (FINSUM ,sv (VNB-LAMBDA z T (f (phi z))) T))))))))))))))

(define (r5v-reindex! name sv pred wd)
  (sp (make-wff (r5v-reindex-stmt sv pred)))
  (dk-peel!)
  (dk-split! '(AND (IN T SET) (IN (CARD T) NN)))
  (let* ((n   '(CARD T))
         (fe  '(FIN-ENUM T))
         (seg (list 'ORD-SEGMENT n))
         (enm (list 'VNB-LAMBDA 'x_ seg (list 'phi (list fe 'x_))))
         (gg  '(VNB-LAMBDA z T (f (phi z))))
         (f1  (list 'ENUM-FAM sv 'f enm n))
         (f2  (list 'ENUM-FAM sv gg fe n))
         (cS  '(CARD S)))
    (fact 'fin-enum-is-bijection 'T)                 ; fe in BIJECTION(OS |T|, T)
    (fact 'bijection-in-fun seg 'T fe)
    (fact 'bijection-in-fun 'T 'S 'phi)
    (have! (list 'AND (list 'IN fe (list 'BIJECTION seg 'T))
                      '(IN phi (BIJECTION T S))))
    (fact 'bijection-compose seg 'T 'S fe 'phi)      ; enm in BIJECTION(OS |T|, S)
    (fact 'card-bijection-eq 'T 'S 'phi)             ; |S| = |T|
    (have! (list 'IN enm (list 'BIJECTION (list 'ORD-SEGMENT cS) 'S))
           (lambda () (subst (list '= cS n)) (ass)))
    (fact wd 'S sv 'f enm)
    (subst (list '= (list 'FINSUM sv 'f 'S)
                 (list 'SUM-AG sv (list 'ENUM-FAM sv 'f enm cS) cS)))
    (subst (list '= cS n))
    ;; the RHS along ITS chosen enumeration.  This is also what certifies the
    ;; fold as DEFINED: `rfl' at the end needs the term equated in context
    ;; (SUM-AG of an ENUM-FAM over FIN-ENUM is CHOICE-bodied, so `pi--defined?'
    ;; refuses it on its own -- the LUTINS rule, CLAUDE.md 2026-09-18).
    (have! (list 'IN gg (list 'FUN 'T (list 'CARR sv)))
      (lambda ()
        (dk-lam-t!)
        (let ((zv (dk-di-var!)))
          (fact 'fun-apply-type-c 'phi 'T 'S zv)
          (fact 'fun-apply-type-c 'f 'S (list 'CARR sv) (list 'phi zv))
          (ass))))
    (fact wd 'T sv gg fe)
    (subst (list '= (list 'FINSUM sv gg 'T) (list 'SUM-AG sv f2 n)))
    (have! (list 'FORALL 'i_ (list 'IMPLIES (list 'IN 'i_ seg)
             (list '== (list f1 'i_) (list f2 'i_))))
      (lambda ()
        (let ((iv (dk-di-var!)))
          (fact 'enum-fam-value n sv 'f enm iv)
          (fact 'enum-fam-value n sv gg fe iv)
          (subst (list '== (list f1 iv) (list 'f (list enm iv))))
          (subst (list '== (list f2 iv) (list gg (list fe iv))))
          (fact 'fun-apply-type-c fe seg 'T iv)      ; FIN-ENUM(T)(i) in T
          (r5v-beta!)
          (qrfl))))
    (fact 'sum-ag-segment-congruence n sv f1 f2)
    (subst (list '== (list 'SUM-AG sv f1 n) (list 'SUM-AG sv f2 n)))
    (rfl))
  (r5v-done! name))

(r5v-reindex! 'finsum-reindex 'm '(IS-COMM-MONOID m)
              'finsum-comm-monoid-well-defined)

(r5v-reindex! 'finsum-reindex-ag 'ag '(IS-ABELIAN-GROUP ag)
              'finsum-well-defined)

;;; =====================================================================
;;; THE REST OF BATCH V -- what was found, and the route each one wants.
;;; (Nothing below is code; it is the report kept beside the file.)
;;;
;;; det-1x1 / det-2x2 / det-identity (structure-library/determinant.scm:86,
;;; :95, :106).  determinant.scm's header calls the literal size a
;;; "COMPUTE-PHASE OBSTACLE" -- "`mac det-cofactor' does not fire on a goal
;;; with a LITERAL size like DET(R,1,A) ... the numeral<->succ bridge is the
;;; first thing the property proofs need".  THAT IS STALE: the bridge is one
;;; line, measured (scratchpad/r5v/det-explore.scm),
;;;
;;;     (have! '(= 1 (succ 0)) (lambda () (arith))) (subst '(= 1 (succ 0)))
;;;
;;; after which `mac det-cofactor' fires and leaves, verbatim,
;;;
;;;     FINSUM(RING-ADDITIVE-AG r,
;;;            j |-> (MUL r)(MPOW(RING-MULTIPLICATIVE-MONOID r, (NEG r)(ONE r),
;;;                               succ j),
;;;                          (MUL r)(ENTRY(a,1,j), DET(r, 0, MINOR(a,1,j,0)))),
;;;            INTERVAL(1, succ 0))  =  ENTRY(a, succ 0, succ 0)
;;;
;;; So what is left is not the numeral but the SINGLETON SUM, and it wants two
;;; bricks the tree does not have:
;;;   (a) INTERVAL(1,1) = PAIR(1,1) -- there is no singleton-interval lemma
;;;       (interval-1-0-empty, theorem-library/mat-basics.scm:480, is the
;;;       worked model: class-extensionality over the membership iff, ~30
;;;       lines).  Without it neither `finsum-singleton' nor
;;;       `finsum-interval-peel' (which wants INTERVAL(1, succ n)) reads the
;;;       one-term sum.
;;;   (b) MPOW(m, x, succ(succ 0)) = (MUL)(x, x): two `mpow-succ' and one
;;;       `mpow-zero' (both definitional), then ring-neg-mul-left +
;;;       ring-neg-neg (rake-algebra2, PROVEN) give (-1)(-1) = 1.
;;; Route, once (a) exists: peel with finsum-interval-peel at n := 0, close the
;;; FINSUM over INTERVAL(1,0) by interval-1-0-empty + finsum-empty, compute the
;;; j = 1 term by (b) + det-zero + ring-mul-right-id + entry-in-carrier.
;;; NOTE the typing trap: finsum-interval-peel wants the summand in
;;; FUN(INTERVAL(1, succ n), CARR ag), whose pointwise leaf needs `mpow-type'
;;; -- STILL ASSERTED (monoid-power.scm:43, `informal'), and not redundant here
;;; because a ring's multiplicative monoid is not commutative.  Going through
;;; the untyped `finsum-congruence' first (rewrite the summand to the constant
;;; j |-> ENTRY(a,1,1) on the index set) avoids it and keeps the bill at 0.
;;; det-2x2 is the same with one more level of recursion plus MINOR read-offs;
;;; det-identity is an NN induction needing "the minor of IDENTMAT is IDENTMAT".
;;;
;;; border-entry-block (structure-library/mat-equiv.scm:118).  The lane is
;;; theorem-library/elem-entry-readoffs.scm's `eer-run!' (mac the constructor,
;;; entry-of-matof, lam-b, resolve the IF tower), and it needs BORDER's own
;;; "entries defined" lemma -- the tabulator's value at every index pair is a
;;; SET.  Two of its three branches are b and ZERO(A) (membership-implies-
;;; sethood off IS-RING); the third is ENTRY(M, NN-MINUS i 1, NN-MINUS j 1),
;;; which needs `entry-in-carrier' (PROVEN) at an index supplied by
;;; `pred-in-interval' (structure-library/order-lemmas.scm) -- STILL ASSERTED,
;;; so that is the leaf to clear first (CLAUDE.md's batch E entry says it is
;;; provable, ~45 lines, and was inlined once as `rkm-pred-in-interval!').
;;; Note also that eer-run!'s resolver is file-local to elem-entry-readoffs.scm
;;; and would have to be copied or moved to driver-kit.scm.
;;;
;;; sum-set-left-scalar / sum-set-right-scalar (theorem-library/
;;; sum-set-left-scalar.scm:16, sum-set-right-scalar.scm:15).  BLOCKED, and the
;;; obstacle is in the AXIOMS, not the driver.  The warrant proposes
;;; finite-set-induction with `sum-set-disjoint-union' at the step -- but that
;;; axiom (structure-library/sequences.scm:220) requires
;;; (IN f (FUN (UNION S1 S2) (CARR r))), the EXACT union as the domain, while
;;; the induction hypothesis is about an f typed on S alone.  Splitting
;;; S u {x} therefore hands SUM-SET(r, S, f) an f typed on S u {x}, which the
;;; IH cannot accept, and there is no way back: SUM-SET has no congruence and
;;; no restriction law, so SUM-SET(r, S, f) for f typed on a strict superset of
;;; S is not determined by the four axioms except through the very union split
;;; that created it.  (`sum-set-type' is already stated with a superset X, so
;;; the intended reading is that SUM-SET(r,S,f) makes sense there.)  Two exits,
;;; both one-line edits to sequences.scm: relax sum-set-disjoint-union to
;;; (IN f (FUN W (CARR r))) with (SUBSET (UNION S1 S2) W), or add
;;; sum-set-congruence (f = g on S => SUM-SET(r,S,f) = SUM-SET(r,S,g)).
;;;
;;; rq-add-computes (structure-library/ringoid.scm:139).  NOT attempted; the
;;; route is complete and its pieces are all proven, so it is an assignment.
;;; `descend2-computes' (theorem-library/rake-setoid2.scm, modulo 0) is exactly
;;; the conclusion once (i) ADD(RINGOID-QUOTIENT-RING r) is rewritten by the
;;; definitional read-off `rq-add' -- `subst' reaches OPERATOR position since
;;; 2026-09-16, so this is one step -- (ii) the class-of-sum map is typed
;;; FUN(CARTESIAN(PTS s, PTS s), QUOTIENT s) by lam-t + class-in-quotient
;;; (PTS s = CARR r is the definitional `ringoid-setoid-pts'), and (iii) it
;;; RESPECTS2 the congruence.  (iii) is the only content: by class-eq-iff it is
;;; ((a+b) + -(a'+b')) in IDL(r) from (a + -a') and (b + -b') in IDL(r), i.e.
;;; ringoid-ideal-add plus the additive regrouping
;;; (a+b) + -(a'+b') = (a + -a') + (b + -b').  `crs' does NOT reach a
;;; structure's (ADD r), so that regrouping is hand-chained through the
;;; RING-ADDITIVE-AG view (abelian-group-opr-interchange, proven) plus a
;;; "-(x+y) = -x + -y" step.  lo would be 489 (ringoid-setoid-is-setoid).
;;; ringoid-quotient-is-ring (:164) is the same driver ten times over, one per
;;; ring law, on top of rq-add-computes / rq-mul-computes / rq-neg-computes.
;;;
;;; monalg-comm (structure-library/polynomial.scm:197).  NOT attempted.  Its
;;; convolution kit is monalg-is-ring.scm, whose header says `monalg-mul-assoc'
;;; waits on `finsum-reindex-inverse' (a reindexing along a pair of mutually
;;; inverse maps rather than a BIJECTION term).  Commutativity does NOT need
;;; that one: it is the swap reindex (p,q) |-> (q,p), which monalg-laws.scm:230
;;; already says `finsum-reindex-ag' covers -- and finsum-reindex-ag is PROVEN
;;; above, so monalg-comm is now unblocked and is the next assignment in this
;;; area.  (IS-COMMUTATIVE-RING(MONALG A M) also needs MONALG's ring-hood,
;;; which is monalg-is-ring, itself still billing monalg-mul-assoc.)
;;; =====================================================================
