;;; reference-topics.scm -- curated TOPIC pages for the browser reference section.
;;;
;;; "No new math" -- pure organization.  Each topic page groups already-installed
;;; results under reading-order headings, so the browser has an "Elementary
;;; calculus" page and a "Metric spaces" page (same shape) as entry points for
;;; future work.  No result is unique to a topic page; it is a curated view.
;;;
;;; Generated into reference/<TOPIC>.md and surfaced as hub cards by
;;; reference/build-reference-html.py (its DOCS list).  Loaded last, after every
;;; result is installed.  Re-emit by hand with (write-topic-pages).
;;; ====================================================================

;;; render one entry: reuse the catalog renderer when the name is an installed
;;; result; otherwise list it as a vocabulary pointer (def-functoid/-predicate
;;; names are not theorems, but belong on the page as the topic's vocabulary).
(define (topic--known? name) (hash-table-ref *theorem-table* name (lambda () #f)))

;;; inline " · [`file`](file)" link to the .scm that states/proves `name'
;;; (relative to *prover-dir*, forced to .scm -- same pathing as the structure
;;; source links).  Empty when no source was stamped (e.g. REPL installs).
(define (topic--file-link name)
  (let ((p (hash-table-ref *theorem-source* name (lambda () #f))))
    (if (not p) ""
        (let* ((s   (->namestring (pathname-new-type (->pathname p) "scm")))
               (pd  *prover-dir*)
               (rel (if (and (>= (string-length s) (string-length pd))
                             (string=? (substring s 0 (string-length pd)) pd))
                        (substring s (string-length pd) (string-length s))
                        s)))
          (string-append "  (proof: [" rel "](" rel "))")))))

;;; textbook entry: name -- statement -- [warrant] -- link to its proof file.
;;; (Vocabulary names that are not installed results list as plain pointers.)
(define (topic--line name)
  (cond
    ((topic--known? name)
     (display "- `") (display name) (display "` — ")
     (display (expression->string (lookup-theorem name)))
     (let ((w (warrant-of name)))
       (when w (display "  _[warrant: ") (display (car w)) (display "]_")))
     (display (topic--file-link name))
     (newline))
    (else
     (display "- `") (display name) (display "` — _(definition / vocabulary)_") (newline))))

(define (write-topic-md filename title blurb sections)
  (let ((path (string-append *reference-dir* filename)))
    (with-output-to-file path
      (lambda ()
        (display "# ") (display title) (newline) (newline)
        (display blurb) (newline) (newline)
        (display "Auto-generated by `(write-topic-pages)` (reference-topics.scm).  ")
        (display "Reading-order organization only -- every backticked name links ")
        (display "to where it is actually stated; no result lives only here.\n\n")
        (for-each
          (lambda (sec)
            (display "## ") (display (car sec)) (newline) (newline)
            (for-each topic--line (cdr sec))
            (newline))
          sections)))
    path))

;;; ---- Elementary calculus (the differential arc on RR) ----
(define *elementary-calculus-sections*
  '(("Vocabulary"
     IS-DIFF-AT DERIV NTH-DERIV LITTLE-O-AT TAYLOR-POLY TAYLOR-DIFFERENTIABLE)
    ("Differentiation rules"
     derivative-unique diff-implies-continuous deriv-const deriv-identity
     deriv-sum deriv-product deriv-chain deriv-neg nth-deriv-one)
    ("Little-o calculus"
     diff-iff-little-o little-o-sum little-o-scalar)
    ("Extreme & interior values (Fermat)"
     extreme-value-max extreme-value-min
     interior-max-deriv-zero interior-min-deriv-zero)
    ("Mean value theorems"
     rolle mvt generalized-mvt)
    ("Consequences of the mean value theorem"
     deriv-zero-implies-constant mvt-upper-bound mvt-lower-bound
     deriv-pos-strictly-increasing)
    ("Taylor's theorem"
     taylor-poly-at-center taylor-lagrange)))

;;; ---- Metric spaces ----
(define *metric-spaces-sections*
  '(("Vocabulary"
     IS-MS-SEQUENCE CONVERGES-TO CONVERGES IS-CAUCHY-SEQ IS-COMPLETE
     BALL IS-OPEN IS-CLOSED IS-CONTINUOUS-AT IS-CONTINUOUS IS-UNIFORMLY-CONTINUOUS
     TOTALLY-BOUNDED IS-R-NET PRODUCT-METRIC COMPLETION)
    ("Sequences, limits, completeness"
     complete-cauchy-converges)
    ("Open / closed sets, balls"
     ball-is-open ball-membership ball-center-in empty-is-open
     carrier-is-open inter-of-opens-open)
    ("Continuity"
     continuous-is-continuous-at
     continuous-implies-open-preimage open-preimage-implies-continuous
     continuous-implies-closed-preimage closed-preimage-implies-continuous)
    ("Completion"
     completion-is-metric-space completion-is-complete embed-isometry)
    ("Compactness / total boundedness"
     totally-bounded-has-cauchy-subsequence cauchy-rapid-subsequence)
    ("Product metric spaces"
     product-is-metric-space product-projection-continuous
     product-convergence-coordinatewise compact-countable-product)
    ("Normed-field metric"
     nf-metric-space-is-metric-space)))

(define (write-topic-pages)
  (write-topic-md "ELEMENTARY-CALCULUS.md" "Elementary calculus"
    (string-append
     "The differential calculus arc on RR: the derivative (Caratheodory form), "
     "the differentiation rules, the mean value theorems (Fermat, Rolle, MVT, "
     "Cauchy MVT) and their consequences, and Taylor's theorem with Lagrange "
     "remainder.  Each biggish theorem has its own proof file.")
    *elementary-calculus-sections*)
  (write-topic-md "METRIC-SPACES.md" "Metric spaces"
    (string-append
     "Metric-space topology: sequences and completeness, open/closed sets and "
     "balls, continuity (epsilon-delta and the open/closed-preimage "
     "characterizations), completion, compactness / total boundedness, and "
     "product metric spaces.")
    *metric-spaces-sections*))

;;; emit at load (every result above is installed by now)
(write-topic-pages)
(display ";; reference-topics: wrote ELEMENTARY-CALCULUS.md + METRIC-SPACES.md\n")
