;;; smith-proof.scm -- Brick B3 (LA Phase B): the Smith normal-form reduction,
;;; built on the ~ equivalence infrastructure (mat-equiv-proof.scm).
;;;   equiv-mul-both  -- A ~ U.A.V for U,V invertible (sandwiching preserves ~);
;;;   swap-to-corner  -- bring any entry (i0,j0) to position (1,1) preserving ~
;;;                      (row swap F[1,i0] on the left, col swap F[1,j0] on the
;;;                      right; the (1,1) value is A_{i0,j0} by the elem-f actions).
;;; Local mq-* proof helpers (leaf focus by goal head, etc.).

(define (mq-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mq-di*) (let lp () (let* ((g (mq-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (mq-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (mq-node! n) (set-proof-state-focus! *ps* n))
(define (mq-foc! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))

;; ---- equiv-mul-both ----
(sp (make-wff '(FORALL R (IMPLIES (IS-RING R) (FORALL m (FORALL n (FORALL A (FORALL U (FORALL V (IMPLIES (IN A (MAT m n (CARR R))) (IMPLIES (IS-INVERTIBLE-MAT R m U) (IMPLIES (IS-INVERTIBLE-MAT R n V) (MAT-EQUIV R m n A (MATMUL R (MATMUL R U A) V))))))))))))))
(mq-di*)
(fact 'invertible-mat-is-mat 'R 'm 'U)
(fact 'matmul-type 'R 'm 'm 'n 'U 'A)
(fact 'mat-equiv-left-mult 'R 'm 'n 'A 'U)
(fact 'mat-equiv-right-mult 'R 'm 'n '(MATMUL R U A) 'V)
(fact 'mat-equiv-trans 'R 'm 'n 'A '(MATMUL R U A) '(MATMUL R (MATMUL R U A) V))
(ass)
 (qed 'equiv-mul-both)
(category! 'equiv-mul-both 'algebra)

;; ---- swap-to-corner ----
(define Fm '(ELEM-F R m 1 i0))
(define Fn '(ELEM-F R n 1 j0))
(define P  (list 'MATMUL 'R Fm 'A))
(define B  (list 'MATMUL 'R P Fn))
(define IFo (list 'IF '(= 1 1) (list 'ENTRY P 1 'j0) (list 'IF '(= 1 j0) (list 'ENTRY P 1 1) (list 'ENTRY P 1 1))))
(define IFr (list 'IF '(= 1 1) '(ENTRY A i0 j0) (list 'IF '(= 1 i0) '(ENTRY A 1 j0) '(ENTRY A 1 j0))))
(sp (make-wff '(FORALL R (IMPLIES (IS-RING R) (FORALL m (FORALL n (FORALL A (FORALL i0 (FORALL j0 (IMPLIES (IN A (MAT m n (CARR R))) (IMPLIES (IN 1 (INTERVAL 1 m)) (IMPLIES (IN 1 (INTERVAL 1 n)) (IMPLIES (IN i0 (INTERVAL 1 m)) (IMPLIES (IN j0 (INTERVAL 1 n)) (IMPLIES (NOT (= 1 i0)) (IMPLIES (NOT (= 1 j0)) (FORSOME B (AND (MAT-EQUIV R m n A B) (= (ENTRY B 1 1) (ENTRY A i0 j0))))))))))))))))))))
(mq-di*)
(fact 'elem-f-invertible 'R 'm 1 'i0)
(fact 'elem-f-invertible 'R 'n 1 'j0)
(fact 'equiv-mul-both 'R 'm 'n 'A Fm Fn)
(fact 'elem-f-type 'R 'm 1 'i0)
(fact 'matmul-type 'R 'm 'm 'n Fm 'A)
(fact 'entry-in-carrier 'm 'n '(CARR R) 'A 'i0 'j0)
(ew B)
(di)
;; L1: MAT-EQUIV -- from equiv-mul-both ; L2: the (1,1) value
(mq-foc! (H? 'MAT-EQUIV))
(ass)
(mq-foc! (H? '=))
(fact 'elem-f-action 'R 'm 'n P 1 'j0 1 1)
(subst (list '= (list 'ENTRY B 1 1) IFo))
(if-true IFo) (define c1 (mq-last)) (rfl) (mq-node! c1)
(subst (list '= IFo (list 'ENTRY P 1 'j0)))
(fact 'elem-f-row-action 'R 'm 'n 'A 1 'i0 1 'j0)
(subst (list '= (list 'ENTRY P 1 'j0) IFr))
(if-true IFr) (define c2 (mq-last)) (rfl) (mq-node! c2)
(subst (list '= IFr '(ENTRY A i0 j0)))
(rfl)
(qed 'swap-to-corner)
(category! 'swap-to-corner 'algebra)

;;; --- swap-to-corner-gen: bring ANY entry to (1,1) (4 cases: pivot in
;;; row 1 and/or col 1 need only a half-swap or none; interior cites swap-to-corner) ---
(define (mq-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (mq-find pred) (let lp ((as (mq-asms))) (cond ((null? as) #f)((pred (car as))(car as))(else (lp (cdr as))))))
(define (mq-em P)
  (cut (list 'OR P (list 'NOT P)))
  (let ((uo (mq-last)))
    (pbc) (cut (list 'NOT P))
    (let ((un (mq-last)))
      (di) (cut (list 'OR P (list 'NOT P)))
      (let ((u2 (mq-last))) (oi-l) (ass) (mq-node! u2))
      (ai (list 'NOT (list 'OR P (list 'NOT P)))) (mq-node! un))
    (cut (list 'OR P (list 'NOT P)))
    (let ((u3 (mq-last))) (oi-r) (ass) (mq-node! u3))
    (ai (list 'NOT (list 'OR P (list 'NOT P)))) (mq-node! uo)))
(define (mq-cases P) (mq-em P) (ai (list 'OR P (list 'NOT P))) (mq-last))
(define (foc-meq! B) (mq-foc! (lambda (g)(and (pair? g)(eq?(car g)'MAT-EQUIV)(equal?(list-ref g 5) B)))))
(define (foc-val! B) (mq-foc! (lambda (g)(and (pair? g)(eq?(car g)'=)(pair?(cadr g))(eq?(car(cadr g))'ENTRY)(equal?(cadr(cadr g)) B)))))

(define Fm '(ELEM-F R m 1 i0))
(define Fn '(ELEM-F R n 1 j0))
(define Bri (list 'MATMUL 'R 'A Fn))
(define Ble (list 'MATMUL 'R Fm 'A))

(sp (make-wff '(FORALL R (IMPLIES (IS-RING R) (FORALL m (FORALL n (FORALL A (FORALL i0 (FORALL j0 (IMPLIES (IN A (MAT m n (CARR R))) (IMPLIES (IN 1 (INTERVAL 1 m)) (IMPLIES (IN 1 (INTERVAL 1 n)) (IMPLIES (IN i0 (INTERVAL 1 m)) (IMPLIES (IN j0 (INTERVAL 1 n)) (FORSOME B (AND (MAT-EQUIV R m n A B) (= (ENTRY B 1 1) (ENTRY A i0 j0))))))))))))))))))
(mq-di*)
(fact 'entry-in-carrier 'm 'n '(CARR R) 'A 'i0 'j0)
(fact 'entry-in-carrier 'm 'n '(CARR R) 'A 1 1)
;; ===== case (= 1 i0) =====
(define NOTi (mq-cases '(= 1 i0)))
  (define NOTj-a (mq-cases '(= 1 j0)))
    ;; both =1 : B = A
    (fact 'mat-equiv-refl 'R 'm 'n 'A) (fact 'eq-sym 1 'i0) (fact 'eq-sym 1 'j0)
    (ew 'A) (di)
    (foc-meq! 'A) (ass)
    (foc-val! 'A) (subst '(= i0 1)) (subst '(= j0 1)) (rfl)
  (mq-node! NOTj-a)
    ;; i0=1, NOT j0=1 : B = A.F[1,j0]
    (fact 'elem-f-invertible 'R 'n 1 'j0)
    (fact 'mat-equiv-right-mult 'R 'm 'n 'A Fn) (fact 'eq-sym 1 'i0)
    (ew Bri) (di)
    (foc-meq! Bri) (ass)
    (foc-val! Bri)
    (fact 'elem-f-action 'R 'm 'n 'A 1 'j0 1 1)
    (define IFa (list 'IF '(= 1 1) '(ENTRY A 1 j0) (list 'IF '(= 1 j0) '(ENTRY A 1 1) '(ENTRY A 1 1))))
    (subst (list '= (list 'ENTRY Bri 1 1) IFa))
    (if-true IFa) (define ca (mq-last)) (rfl) (mq-node! ca)
    (subst (list '= IFa '(ENTRY A 1 j0)))
    (subst '(= i0 1)) (rfl)
;; ===== case NOT (= 1 i0) =====
(mq-node! NOTi)
(define NOTj-b (mq-cases '(= 1 j0)))
    ;; NOT i0=1, j0=1 : B = F[1,i0].A
    (fact 'elem-f-invertible 'R 'm 1 'i0)
    (fact 'mat-equiv-left-mult 'R 'm 'n 'A Fm) (fact 'eq-sym 1 'j0)
    (ew Ble) (di)
    (foc-meq! Ble) (ass)
    (foc-val! Ble)
    (fact 'elem-f-row-action 'R 'm 'n 'A 1 'i0 1 1)
    (define IFb (list 'IF '(= 1 1) '(ENTRY A i0 1) (list 'IF '(= 1 i0) '(ENTRY A 1 1) '(ENTRY A 1 1))))
    (subst (list '= (list 'ENTRY Ble 1 1) IFb))
    (if-true IFb) (define cb (mq-last)) (rfl) (mq-node! cb)
    (subst (list '= IFb '(ENTRY A i0 1)))
    (subst '(= j0 1)) (rfl)
  (mq-node! NOTj-b)
    ;; NOT i0=1, NOT j0=1 : swap-to-corner
    (fact 'swap-to-corner 'R 'm 'n 'A 'i0 'j0)
    (ai 1) (ai 1)
    (define B0eq (mq-find (lambda (z) (and (pair? z)(eq?(car z)'MAT-EQUIV)))))
    (define B0 (list-ref B0eq 5))
    (ew B0) (di)
    (foc-meq! B0) (ass)
    (foc-val! B0) (ass)
(qed 'swap-to-corner-gen)
(category! 'swap-to-corner-gen 'algebra)

;;; --- place-min-pivot: B ~ P with a minimal-degree nonzero pivot at (1,1)
;;; (min-degree-entry picks the minimal entry, swap-to-corner-gen brings it to (1,1);
;;; the minimality transfers via the captured (= B_{1,1} P_{i*,j*})).  Sets up the
;;; Smith descent: deg(B_{1,1}) = mu(P), so any euclidean remainder is strictly smaller. ---
(sp (make-wff '(FORALL A (IMPLIES (IS-EUCLIDEAN-RING A) (FORALL m (FORALL n (FORALL P (IMPLIES (IN P (MAT m n (CARR A))) (IMPLIES (IN 1 (INTERVAL 1 m)) (IMPLIES (IN 1 (INTERVAL 1 n)) (IMPLIES (FORSOME i0 (FORSOME j0 (AND (IN i0 (INTERVAL 1 m)) (AND (IN j0 (INTERVAL 1 n)) (NOT (= (ENTRY P i0 j0) (ZERO A))))))) (FORSOME B (AND (MAT-EQUIV A m n P B) (AND (NOT (= (ENTRY B 1 1) (ZERO A))) (FORALL i (FORALL j (IMPLIES (IN i (INTERVAL 1 m)) (IMPLIES (IN j (INTERVAL 1 n)) (IMPLIES (NOT (= (ENTRY P i j) (ZERO A))) (<= ((GAUGE A) (ENTRY B 1 1)) ((GAUGE A) (ENTRY P i j))))))))))))))))))))))
(mq-di*)
(fact 'min-degree-entry 'A 'm 'n 'P)
(ai 1)(ai 1)(ai 1)(ai 1)(ai 1)
;; capture istar,jstar from the (NOT (= (ENTRY P istar jstar)(ZERO A))) assumption
(define NEasm (mq-find (lambda (z)(and (pair? z)(eq?(car z)'NOT)(pair?(cadr z))(eq?(car(cadr z))'=)
                                       (pair?(cadr(cadr z)))(eq?(car(cadr(cadr z)))'ENTRY)))))
(define istar (list-ref (cadr (cadr NEasm)) 2))
(define jstar (list-ref (cadr (cadr NEasm)) 3))
(define MINIM (mq-find (lambda (z)(and (pair? z)(eq?(car z)'FORALL)))))
;; coerce euclidean -> ring
(fact 'euclidean-ring-is-integral-domain 'A)
(fact 'integral-domain-is-commutative-ring 'A)
(fact 'commutative-ring-is-ring 'A)
;; place istar,jstar at (1,1)
(fact 'swap-to-corner-gen 'A 'm 'n 'P istar jstar)
(ai 1)(ai 1)
(define B0eq (mq-find (lambda (z)(and (pair? z)(eq?(car z)'MAT-EQUIV)))))
(define B0 (list-ref B0eq 5))
(define B0val (list '= (list 'ENTRY B0 1 1) (list 'ENTRY 'P istar jstar)))
(ew B0) (di)
(mq-foc! (H? 'MAT-EQUIV)) (ass)
(mq-foc! (H? 'AND)) (di)
;; NE leaf: (NOT (= (ENTRY B0 1 1)(ZERO A)))
(mq-foc! (H? 'NOT))
(subst B0val) (ass)
;; minimality leaf
(mq-foc! (H? 'FORALL))
(mq-di*)
(subst B0val)
(inst+ MINIM 'i)
(define MINj (mq-find (lambda (z)(and (pair? z)(eq? (car z) 'FORALL)(eq? (cadr z) 'j))))) 
(inst+ MINj 'j)
(ass)
(qed 'place-min-pivot)
(category! 'place-min-pivot 'algebra)
