;;; submodule-fg-proof.scm -- submodule-fg, PROVEN as a corollary of the
;;; SPANS-relativized statement it should always have had.
;;;
;;;   submodule-subset            IS-SUBMODULE md sm  =>  SUBSET sm (VEC md)
;;;   whole-module-is-submodule   VEC md is a submodule of md
;;;   generates-implies-spans-vec GENERATES md n u  =>  SPANS md n u (VEC md)
;;;   submodule-fg                a submodule of an n-generated module over a
;;;                               euclidean ring is spanned by <= n elements
;;;
;;; THE FINDING.  submodule-fg used to be ASSERTED, warranted 'informal, and the
;;; induction its warrant describes does not work.  The step forms the submodule
;;; generated by u_1..u_{n-1} and closes with "the induction hypothesis applies
;;; to sm' inside the module generated by u_1..u_{n-1}".  But that is a
;;; SUBMODULE, while the hypothesis GENERATES md (n-1) u' asserts it is all of
;;; VEC md -- false in general.  VNB has no submodule-as-module view to launder
;;; the step (MODULE-VECTOR-AG forgets the scalars; IS-SUBMODULE is a predicate
;;; on (m,s), not a structure), and building one would restate GENERATES/SPANS
;;; across two structures.
;;;
;;; So the induction must be stated about a submodule of a SPANNED submodule,
;;; staying inside md.  That is `spans-submodule-fg' (submodule-free.scm), which
;;; DOES apply to itself at n-1 with bm := span(u_1..u_{n-1}).  submodule-fg is
;;; the bm := VEC md case, and this file machine-checks that reduction.  The debt
;;; has moved off a statement whose stated proof is wrong, onto one whose stated
;;; proof is right.
;;;
;;; Needs: module.scm (module-vzero-in / module-vadd-type / module-vneg-type /
;;; module-act-type), finite-dimensional.scm (IS-SUBMODULE), mod-seq.scm
;;; (GENERATES, SPANS), matrix.scm (entry-in-carrier), order-lemmas
;;; (one-in-interval-1), submodule-free.scm (spans-submodule-fg).

;;; ---- driver helpers (sfg- prefix)
(define (sfg-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (sfg-foc! n) (set-proof-state-focus! *ps* n))
(define (sfg-foc-goal! g)                ; ERRORS on a miss, by design
  (let loop ((ls (proof-leaves)))
    (cond ((null? ls) (error "sfg-foc-goal!: no open leaf with goal" g))
          ((equal? (wff-formula (sequent-node-assertion (car ls))) g)
           (sfg-foc! (car ls)) (car ls))
          (else (loop (cdr ls))))))
(define (sfg-di*)
  (let lp () (let* ((g (sfg-goal)) (h (and (pair? g) (car g))))
               (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
;; `mac' of a def-predicate leaves the whole conjunctive body as ONE goal.
;; Split every open AND goal so each conjunct becomes its own leaf.
(define (sfg-split-and-goals!)
  (let lp ((n 0))
    (let ((leaf (any-pred (lambda (s)
                            (let ((g (wff-formula (sequent-node-assertion s))))
                              (and (pair? g) (eq? (car g) 'AND))))
                          (proof-leaves))))
      (when (and leaf (< n 20)) (sfg-foc! leaf) (di) (lp (+ n 1))))))

;;; The body of IS-SUBMODULE(md, S), for a given carrier term S.
(define (sfg-submodule-body s)
  (list 'AND (list 'SUBSET s '(VEC md))
   (list 'AND (list 'IN '(VZERO md) s)
    (list 'AND (list 'FORALL 'x_ (list 'IMPLIES (list 'IN 'x_ s)
                     (list 'FORALL 'y_ (list 'IMPLIES (list 'IN 'y_ s)
                       (list 'IN '((VADD md) x_ y_) s)))))
     (list 'AND (list 'FORALL 'x_ (list 'IMPLIES (list 'IN 'x_ s)
                       (list 'IN '((VNEG md) x_) s)))
           (list 'FORALL 'r_ (list 'IMPLIES '(IN r_ (CARR (SCAL md)))
             (list 'FORALL 'x_ (list 'IMPLIES (list 'IN 'x_ s)
               (list 'IN '((ACT md) r_ x_) s))))))))))

;;; submodule-subset (the SUBSET conjunct) is now a definitional projection in
;;; finite-dimensional.scm (alongside submodule-vzero-in / -vadd-closed / etc.),
;;; so it is available to the span-bricks, which -- since the descent moved ahead
;;; of this file -- now load before it.  It used to be proved here.

;;; ===================================================================
;;; whole-module-is-submodule -- VEC md is a submodule of md.
;;; Each conjunct is the corresponding module closure law, in applied form.
;;; ===================================================================
(sp (make-wff '(FORALL md (IMPLIES (IS-MODULE md) (IS-SUBMODULE md (VEC md))))))
(sfg-di*)
(fact 'module-vzero-in 'md)
(mac 'IS-SUBMODULE)
(sfg-split-and-goals!)                   ; five conjuncts, five leaves

;; (1) VEC md subset VEC md
(sfg-foc-goal! '(SUBSET (VEC md) (VEC md)))
(mac 'subset-def)
(di)                                     ; peels the forall, absorbs the bound
(ass)

;; (2) the zero vector is a vector
(sfg-foc-goal! '(IN (VZERO md) (VEC md)))
(ass)

;; (3) closed under VADD
(sfg-foc-goal! (list 'FORALL 'x_ (list 'IMPLIES '(IN x_ (VEC md))
                 (list 'FORALL 'y_ (list 'IMPLIES '(IN y_ (VEC md))
                   '(IN ((VADD md) x_ y_) (VEC md)))))))
(di)                                     ; peels x_, y_ and absorbs both bounds
(let* ((g  (sfg-goal))                   ; (IN ((VADD md) xx yy) (VEC md))
       (ap (cadr g)))
  (fact 'module-vadd-type 'md (cadr ap) (caddr ap))
  (ass))

;; (4) closed under VNEG
(sfg-foc-goal! (list 'FORALL 'x_ (list 'IMPLIES '(IN x_ (VEC md))
                                       '(IN ((VNEG md) x_) (VEC md)))))
(di)
(let* ((g (sfg-goal)) (ap (cadr g)))
  (fact 'module-vneg-type 'md (cadr ap))
  (ass))

;; (5) closed under the scalar action
(sfg-foc-goal! (list 'FORALL 'r_ (list 'IMPLIES '(IN r_ (CARR (SCAL md)))
                 (list 'FORALL 'x_ (list 'IMPLIES '(IN x_ (VEC md))
                   '(IN ((ACT md) r_ x_) (VEC md)))))))
(di)
(let* ((g (sfg-goal)) (ap (cadr g)))
  (fact 'module-act-type 'md (cadr ap) (caddr ap))
  (ass))

(qed 'whole-module-is-submodule)
(category! 'whole-module-is-submodule 'algebra)

;;; ===================================================================
;;; generates-implies-spans-vec -- GENERATES is the sm = VEC md case of SPANS.
;;; SPANS adds only "u's own entries lie in sm", vacuous when sm = VEC md.
;;; ===================================================================
(sp (make-wff
  '(FORALL md (IMPLIES (IS-MODULE md)
     (FORALL n (IMPLIES (IN n NN)
       (FORALL u (IMPLIES (IN u (MAT n 1 (VEC md)))
         (IMPLIES (GENERATES md n u) (SPANS md n u (VEC md)))))))))))
(sfg-di*)
(fact 'one-in-interval-1)
(mac 'SPANS)
(sfg-split-and-goals!)                   ; the entry clause and the spanning clause

;; u's entries are vectors
(sfg-foc-goal! (list 'FORALL 'j_ (list 'IMPLIES '(IN j_ (INTERVAL 1 n))
                                       '(IN (ENTRY u j_ 1) (VEC md)))))
(di)
(let* ((g  (sfg-goal))                   ; (IN (ENTRY u jj 1) (VEC md))
       (jj (caddr (cadr g))))
  (fact 'entry-in-carrier 'n 1 '(VEC md) 'u jj 1)
  (ass))

;; every vector is a combination of u -- verbatim GENERATES
(sfg-foc-goal! (list 'FORALL 'x_ (list 'IMPLIES '(IN x_ (VEC md))
                 (list 'FORSOME 'c_ (list 'AND '(IN c_ (MAT 1 n (CARR (SCAL md))))
                                          '(= x_ (ENTRY (MATACT md c_ u) 1 1)))))))
(mac-h 'GENERATES '(GENERATES md n u))
(ass)

(qed 'generates-implies-spans-vec)
(category! 'generates-implies-spans-vec 'algebra)

;;; ===================================================================
;;; submodule-fg -- the bm := VEC md case of spans-submodule-fg.
;;; ===================================================================
(define sfg-euclid '(AND (IS-MODULE md) (IS-EUCLIDEAN-RING (SCAL md))))
(sp (make-wff
  (list 'FORALL 'md (list 'IMPLIES sfg-euclid
    '(FORALL n (IMPLIES (IN n NN)
      (FORALL u (IMPLIES (IN u (MAT n 1 (VEC md)))
        (IMPLIES (GENERATES md n u)
          (FORALL sm (IMPLIES (IS-SUBMODULE md sm)
            (FORSOME k (AND (AND (IN k NN) (<= k n))
              (FORSOME w (AND (IN w (MAT k 1 (VEC md))) (SPANS md k w sm))))))))))))))))
(sfg-di*)
(define sfg-concl (sfg-goal))            ; the FORSOME k ... goal

;; Peel the euclid conjunction WITHOUT consuming it: spans-submodule-fg's own
;; antecedent is that same AND, and `fact' detaches it from context.
(cut '(IS-MODULE md))
  (ai sfg-euclid) (ass)
(sfg-foc-goal! sfg-concl)
(cut '(IS-EUCLIDEAN-RING (SCAL md)))
  (ai sfg-euclid) (ass)
(sfg-foc-goal! sfg-concl)

(fact 'whole-module-is-submodule 'md)
(fact 'generates-implies-spans-vec 'md 'n 'u)
(fact 'submodule-subset 'md 'sm)
(fact 'spans-submodule-fg 'md 'n 'u '(VEC md) 'sm)
(ass)

(qed 'submodule-fg)
(category! 'submodule-fg 'algebra)
