;;; theorem-library/submodule-free.scm
;;; ====================================================================
;;; Phase C, Cor 3.46: a submodule of a free module of rank n over a euclidean
;;; ring is free of rank <= n.  (linear-algebra.tex cor:22195-45888-207248.)
;;;
;;; THE CIRCULARITY IN THE NOTES.  linear-algebra.tex proves
;;;   cor:26329  "any subgroup F of an E generated by n elements is generated
;;;               by <= n elements"
;;; as a COROLLARY of cor:22195, which rests on prop:20401, whose proof opens
;;; "F has a finite number of generators v_1..v_m.  The result follows from the
;;; preceding remarks."  But the preceding remarks (tex 1936-1949) begin "suppose
;;; ... v generates a subgroup F", and form the matrix A with v = A.u from that
;;; generating sequence.  So Smith normal form CONSUMES a finite generating set
;;; for F; it cannot produce one.  And cor:26329 is word-for-word the statement
;;; of the lemma the notes \iffalse'd out at tex:1651.  The chapter therefore
;;; derives finite generation from something that assumes it.
;;;
;;; Smith DOES give the freeness and the rank bound.  It does NOT give finite
;;; generation.  That is the content of spans-submodule-fg below -- the
;;; \iffalse'd induction -- and it is load-bearing, not redundant.
;;;
;;; DEPENDENCY (honest order):
;;;   spans-submodule-fg      F <= (submodule spanned by n elts)
;;;     |                       =>  F spanned by <= n elts
;;;     |                     [induction on n, INSIDE md; the last-coefficient
;;;     |                      set is an IDEAL of the scalar ring, whose
;;;     |                      generator euclidean-ideal-has-generator supplies
;;;     |                      (PROVEN, one minimize! call)]
;;;     v
;;;   submodule-fg            the bm := VEC md case   [QED, submodule-fg-proof.scm]
;;;     |                     NOT provable directly: see the note on the support
;;;     |                     below -- its old warrant's induction needed a
;;;     |                     submodule to be a module.
;;;     v
;;;   generates-coeff-matrix  v = A . u                         [warranted]
;;;     v
;;;   smith-staircase         B = V A U^-1 diagonal, nonzeros   [QED trust:none]
;;;     |                     an INITIAL SEGMENT of length k
;;;     v
;;;   free-transport          U.u still freely generates E      [QED]
;;;   generates-transport     V.v still generates F             [QED]
;;;     v
;;;   submodule-of-free-is-free   b_1.e_1 .. b_k.e_k free-generate F
;;;
;;; Cor 3.46 needs only the DIAGONAL form with its nonzeros up front -- exactly
;;; what SMITH-STAIRCASE records.  The divisibility chain b_i | b_{i+1} is NOT
;;; needed here; it is needed later, for uniqueness of the invariant factors
;;; (tex prop:22194-20879-92458).
;;;
;;; Loads after mod-seq (GENERATES/REL-FREE/SPANS/MATACT), finite-dimensional
;;; (IS-SUBMODULE), euclidean-ring, smith-staircase-proof.
;;; ====================================================================

;; typed universal: (tf v TYPE BODY) = (FORALL v (IMPLIES TYPE BODY)) -- keeps
;; every quantifier level locally balanced, no deep paren counting.
(define (sf-tf v type body) (list 'FORALL v (list 'IMPLIES type body)))
(define (sf-ex v type body) (list 'FORSOME v (list 'AND type body)))
;; the scalar ring of md is euclidean
(define sf-euclid '(AND (IS-MODULE md) (IS-EUCLIDEAN-RING (SCAL md))))

;;; =======================================================================
;;; The load-bearing brick: a submodule of an n-generated module over a
;;; euclidean ring is generated by at most n elements.  (tex:1651, \iffalse'd.)
;;;
;;; WHY THE STATEMENT IS RELATIVIZED TO A SUBMODULE `bm'.
;;;
;;; The old `submodule-fg' support was stated with GENERATES md n u -- u
;;; generates the WHOLE of VEC md -- and its warrant closed with "the induction
;;; hypothesis applies to sm' inside the module generated by u_1..u_{n-1}".
;;; That sentence is where the argument breaks.  u_1..u_{n-1} generates a proper
;;; SUBMODULE of md, not a module: GENERATES md (n-1) u' is simply false, so the
;;; induction hypothesis does not apply.  Informally one promotes the submodule
;;; to a module and recurses; VNB has no such view (MODULE-VECTOR-AG forgets the
;;; scalars, and IS-SUBMODULE is a predicate on (m,s), not a structure), and
;;; building one would change GENERATES/SPANS across two structures.
;;;
;;; So the induction must stay inside md, and its statement must be about a
;;; submodule of a SPANNED submodule.  That is `spans-submodule-fg' below; it is
;;; what the induction actually proves, and it does apply to itself at n-1 with
;;; bm := span(u_1..u_{n-1}).  The library had already conceded this once --
;;; spans-transport-proof.scm exists "because F is a submodule, not the whole
;;; module".  The old statement is now a COROLLARY, machine-proven in
;;; theorem-library/submodule-fg-proof.scm by taking bm := VEC md.
;;; =======================================================================
;;; spans-submodule-fg is now PROVEN by induction on n in
;;; theorem-library/spans-submodule-fg-proof.scm (loaded just before this file),
;;; from the six bricks + euclidean-ideal-has-generator.  It used to be asserted
;;; here ('informal).  submodule-fg-proof.scm (the bm := VEC md corollary)
;;; consumes it exactly as before, now against a proved theorem rather than a
;;; warranted support.

;;; =======================================================================
;;; Cor 3.46 -- submodule of a free module is free of rank <= n.
;;; =======================================================================
(support 'submodule-of-free-is-free
  (sf-tf 'md sf-euclid
   (sf-tf 'n '(IN n NN)
    (sf-tf 'u '(IN u (MAT n 1 (VEC md)))
     (list 'IMPLIES '(AND (GENERATES md n u) (REL-FREE md n u))
      (sf-tf 'sm '(IS-SUBMODULE md sm)
       (sf-ex 'k '(AND (IN k NN) (<= k n))
        (sf-ex 'w '(IN w (MAT k 1 (VEC md)))
               '(AND (SPANS md k w sm) (REL-FREE md k w))))))))))
(warrant! 'submodule-of-free-is-free 'reference
  "linear-algebra.tex cor:22195-45888-207248.  submodule-fg gives generators
   v_1..v_m of sm with m <= n; generates-coeff-matrix writes v = A.u for an
   m-by-n coefficient matrix A.  smith-staircase supplies invertible V, U with
   B = V A U^-1 diagonal and its NONZERO diagonal entries b_1..b_k an initial
   segment (k <= min(m,n) <= n).  free-transport: e = U.u still freely generates
   md.  generates-transport: V.v still generates sm.  But V.v = B.e, whose i-th
   entry is b_i.e_i -- so b_1.e_1 .. b_k.e_k generate sm (rows past k are 0).
   They are REL-FREE: if sum c_i.(b_i.e_i) = 0 then sum (c_i b_i).e_i = 0, so
   each c_i b_i = 0 by REL-FREE of e, and b_i /= 0 forces c_i = 0
   (integral-domain-cancel-zero; a euclidean ring is an integral domain).
   Hence sm is free of rank k <= n.  ASSEMBLY IS THE PROOF TARGET: every cited
   piece is installed, and the only asserted input is submodule-fg.
   No divisibility chain b_i | b_{i+1} is used -- that is needed only for
   uniqueness of the invariant factors (tex prop:22194-20879-92458).")
