;;; tuple-extensionality.scm -- two tuples with the same length and the same
;;; entry at every index are equal; and, on top of it, matrix-entry-extensionality.
;;;
;;;   tuple-extensionality
;;;     forall A, L, M.  L in TUPLES(A) and M in TUPLES(A)
;;;                      and LENGTH(L) = LENGTH(M)
;;;                      and (forall k in NN. 1 <= k <= LENGTH(L) => NTH(k,L) = NTH(k,M))
;;;                      =>  L = M
;;;
;;;   matrix-entry-extensionality   (the statement verbatim from matrix.scm)
;;;     forall m n X P Q.  P in MAT(m,n,X) and Q in MAT(m,n,X)
;;;                        and (forall i in [1,m], j in [1,n]. ENTRY(P,i,j) = ENTRY(Q,i,j))
;;;                        =>  P = Q
;;;
;;; WHAT `=' ON TUPLES MEANS HERE.  Nothing in the tree says what a tuple IS
;;; beyond LENGTH, NTH and the CONS equations of list-recursion.scm, and that
;;; is enough: TUPLES(A) is GENERATED by [] and CONS (tuple-length-zero,
;;; tuple-cons-decompose), so a proof by tuples-induction reduces
;;; extensionality to two facts about the constructors -- the empty tuple is
;;; the only tuple of length 0, and CONS is a congruence, which is nothing more
;;; than Leibniz substitution of the head equation and the tail equation into
;;; the goal `CONS(x,M) = CONS(x',M')'.  No extensionality AXIOM is added.
;;;
;;; THE PROOF is `tuples-induction' (theorem-library/tuples-induction.scm) at
;;; the class
;;;
;;;   C  =  { l_ | forall m_ in TUPLES(A). LENGTH(l_) = LENGTH(m_)
;;;                  => (forall k_ ...) => l_ = m_ }
;;;
;;; a COMP term, read out by `comp-me' and put in by `comp-mi'.  This is the
;;; first proof in the tree to instantiate a class-form induction principle at
;;; a COMPREHENSION rather than at a set-former (matof-in-mat.scm uses it at
;;; TUPLES(B)); the sethood obligation `comp-mi' posts is discharged by
;;; `membership-implies-sethood' off the constructor typing.
;;;
;;;   base:  LENGTH([]) = LENGTH(m_) = 0, so m_ = [] by tuple-length-zero.
;;;   step:  LENGTH(m_) = succ(LENGTH(M)), so m_ = CONS(x', M') by
;;;          tuple-cons-decompose; the entry hypothesis at succ(k) with
;;;          nth-cons-succ on both sides gives the tail hypothesis, the class
;;;          property of M (the induction hypothesis) gives M = M'; the entry
;;;          hypothesis at 1 with nth-cons-1 on both sides gives x = x'; two
;;;          `subst's close CONS(x,M) = m_.
;;;
;;; matrix-entry-extensionality is then tuple-extensionality twice: once per
;;; row (row i of P and row i of Q are tuples over X of length n -- the equilong
;;; conjunct of matrix-membership against SIZE = [m,n] -- with equal entries by
;;; the hypothesis, ENTRY being NTH(j, NTH(i, _))), and once at TUPLES(X) for
;;; the matrices themselves (length m each).  Index conditions cross between
;;; the two shapes -- `i in INTERVAL(1,m)' on the matrix side, `i in NN and
;;; 1 <= i <= LENGTH(P)' on the tuple side -- through interval's own unfolding
;;; (mac INTERVAL + sep-mi), never through interval-membership /
;;; interval-mem-intro, which are asserted.
;;;
;;; Two plumbing equations are proved on the way, both `modulo 0' and both the
;;; shape mat-basics.scm uses: `nth2-pair' (NTH(2,[a,b]) == b, the sibling of
;;; nth1-pair) and `entry-unfold' (ENTRY(M,i,j) == NTH(j,NTH(i,M)), the
;;; functoid's own equation, citable so a `subst' can move between the two
;;; spellings).
;;;
;;; BILL: tuples-induction is proven but bills tuple-length-zero and
;;; tuple-cons-decompose (list-recursion.scm, well-known), and the step here
;;; cites tuple-cons-decompose directly as well; nothing else asserted is
;;; cited.  Same bill as matof-in-mat.
;;;
;;; LOAD WINDOW: after theorem-library/tuples-induction (the latest citation;
;;; also needs list-recursion, matrix, equality-basics, mat-basics,
;;; nn-order-ord, nn-order-basics -- all earlier) and before
;;; theorem-library/matmul-assoc-proof, the earliest citer of
;;; matrix-entry-extensionality.  Beside matof-in-mat is the natural slot.
;;; Helper prefix: tx-.

;;; --------------------------------------------------------------------
;;; helpers

;; The conclusion under all leading FORALL/IMPLIES (discriminate on the
;; CONSEQUENT, never on a binder or a head).
(define (tx-final f)
  (if (and (pair? f) (memq (car f) '(FORALL IMPLIES))) (tx-final (caddr f)) f))

;; The in-context universal whose consequent satisfies PRED.
(define (tx-pick-univ pred what)
  (dk-pick (lambda (f) (and (pair? f) (eq? (car f) 'FORALL) (pred (tx-final f))))
           what))

;; i in INTERVAL(lo, hi), from `i in NN', `lo <= i', `i <= hi' in context --
;; by the functoid's own unfolding (no asserted interval fact).
(define (tx-in-interval! i lo hi)
  (have! (list 'IN i (list 'INTERVAL lo hi))
    (lambda ()
      (mac 'INTERVAL)
      (for-each (lambda (l) (dk-focus! l) (dk-conj-close!))
                (dk-opened (lambda () (sep-mi)))))))

;; have! a conjunction whose conjuncts are all in context, closed by `ass'
;; alone: the default closer `from-context!' sends a numeral membership such
;; as (IN 1 NN) to the arith ORACLE even when it is an assumption, and the
;; oracle would then appear on the bill.
(define (tx-have-and! f)
  (have! f (lambda () (dk-conj-close! (lambda () (ass))))))

;;; --------------------------------------------------------------------
;;; plumbing equations

(sp (make-wff '(FORALL a (FORALL b (== (NTH 2 (LIST a b)) b)))))
(di)
(nth-r)
(qrfl)
(qed 'nth2-pair)
(topic! 'nth2-pair 'plumbing)

(sp (make-wff '(FORALL M (FORALL i (FORALL j (== (ENTRY M i j) (NTH j (NTH i M))))))))
(di)
(mac 'ENTRY)
(qrfl)
(qed 'entry-unfold)
(topic! 'entry-unfold 'plumbing)

;;; --------------------------------------------------------------------
;;; tuple-extensionality

;; The class property with l_ := LHS: "every tuple over A of the same length
;; with the same entries equals LHS".
(define (tx-ext-body lhs a)
  `(FORALL m_ (IMPLIES (IN m_ (TUPLES ,a))
     (IMPLIES (= (LENGTH ,lhs) (LENGTH m_))
       (IMPLIES (FORALL k_ (IMPLIES (AND (IN k_ NN) (AND (<= 1 k_) (<= k_ (LENGTH ,lhs))))
                                    (= (NTH k_ ,lhs) (NTH k_ m_))))
         (= ,lhs m_))))))

(define (tx-class a) (list 'COMP 'l_ (tx-ext-body 'l_ a)))

;; The entry premise of the class property, for a pair of tuples.  The binder
;; is chosen NOT free in L or M: the row lane of matrix-entry-extensionality
;; builds this for L = NTH(k_, P), where k_ is the row index the OUTER copy
;; of this same premise minted, and a template that always bound k_ captured
;; it (found on the first probe, 2026-09-15).  Alpha-equivalence makes the
;; binder's name irrelevant to every citation that matches this premise.
(define (tx-ext-body-entries l m)
  (let* ((fv (append (free-vars l) (free-vars m)))
         (k  (if (memq 'k_ fv) 'kk_ 'k_)))
    `(FORALL ,k (IMPLIES (AND (IN ,k NN) (AND (<= 1 ,k) (<= ,k (LENGTH ,l))))
                         (= (NTH ,k ,l) (NTH ,k ,m))))))

;; BASE:  goal (IN (LIST) C).
(define (tx-base! a)
  (for-each
   (lambda (leaf)
     (dk-focus! leaf)
     (let ((g (dk-goal)))
       (if (and (eq? (car g) 'IN) (eq? (caddr g) 'SET))
           (begin                                            ; [] is a set
             (fact 'empty-in-tuples a)
             (fact 'membership-implies-sethood '(LIST) (list 'TUPLES a))
             (ass))
           (begin                                            ; the property of []
             (dk-peel!)
             (let* ((g2 (dk-goal))                           ; (= (LIST) mm)
                    (mm (caddr g2)))
               (if (not (and (eq? (car g2) '=) (equal? (cadr g2) '(LIST))))
                   (error "tx-base!: unexpected goal" g2))
               (fact 'length-of-empty)
               (have! (list '= (list 'LENGTH mm) 0)
                 (lambda () (subst (list '= (list 'LENGTH mm) '(LENGTH (LIST)))) (ass)))
               (tx-have-and! (list 'AND (list 'IN mm (list 'TUPLES a)) (list '= (list 'LENGTH mm) 0)))
               (fact 'tuple-length-zero a mm)                ; (= mm (LIST))
               (subst (list '= mm '(LIST)))
               (rfl))))))
   (dk-opened (lambda () (comp-mi)))))

;; The tail hypothesis:  forall k. k in NN, 1 <= k <= LENGTH(t0) => NTH(k,t0) = NTH(k,t1),
;; from the entry hypothesis NTHH of CONS(x0,t0) against mm = CONS(x1,t1), at succ k.
(define (tx-tail-entries! x0 t0 x1 t1 mm nthh)
  (dk-split-all! (dk-peel!))
  (let* ((g   (dk-goal))                                    ; (= (NTH k t0) (NTH k t1))
         (k   (cadr (cadr g)))
         (sk  (list 'succ k))
         (cx  (list 'CONS x0 t0))
         (cx1 (list 'CONS x1 t1))
         (lt0 (list 'LENGTH t0))
         (lt1 (list 'LENGTH t1)))
    (fact 'nn-succ-closed k)                                 ; succ k in NN
    (fact 'nn-one-le-succ k)                                 ; 1 <= succ k
    (fact 'nn-succ-mono k lt0)                               ; succ k <= succ LENGTH(t0)
    (have! (list '<= sk (list 'LENGTH cx))
      (lambda () (subst (list '= (list 'LENGTH cx) (list 'succ lt0))) (ass)))
    (tx-have-and! (list 'AND (list 'IN sk 'NN) (list 'AND (list '<= 1 sk) (list '<= sk (list 'LENGTH cx)))))
    (dk-apply! nthh sk)                                      ; NTH(succ k, cx) = NTH(succ k, mm)
    (tx-have-and! (list 'AND (list 'IN k 'NN) (list 'AND (list '<= 1 k) (list '<= k lt0))))
    (fact 'nth-cons-succ k x0 t0)                            ; NTH(succ k, cx) = NTH(k, t0)
    (have! (list '<= k lt1) (lambda () (subst (list '= lt1 lt0)) (ass)))
    (tx-have-and! (list 'AND (list 'IN k 'NN) (list 'AND (list '<= 1 k) (list '<= k lt1))))
    (fact 'nth-cons-succ k x1 t1)                            ; NTH(succ k, cx1) = NTH(k, t1)
    (subst (list '= (list 'NTH k t0) (list 'NTH sk cx)))
    (subst (list '= (list 'NTH sk cx) (list 'NTH sk mm)))
    (subst (list '= mm cx1))
    (ass)))

;; The heads:  lands (= x0 x1), from NTHH at 1 and nth-cons-1 on both sides.
(define (tx-head-eq! x0 t0 x1 t1 mm nthh)
  (let* ((cx  (list 'CONS x0 t0))
         (cx1 (list 'CONS x1 t1))
         (lt0 (list 'LENGTH t0)))
    (fact 'nn-one-in)
    (fact 'nn-le-refl 1)
    (fact 'nn-one-le-succ lt0)                               ; 1 <= succ LENGTH(t0)
    (have! (list '<= 1 (list 'LENGTH cx))
      (lambda () (subst (list '= (list 'LENGTH cx) (list 'succ lt0))) (ass)))
    (tx-have-and! (list 'AND '(IN 1 NN) (list 'AND '(<= 1 1) (list '<= 1 (list 'LENGTH cx)))))
    (dk-apply! nthh 1)                                       ; NTH(1, cx) = NTH(1, mm)
    (fact 'nth-cons-1 x0 t0)                                 ; NTH(1, cx)  = x0
    (fact 'nth-cons-1 x1 t1)                                 ; NTH(1, cx1) = x1
    (have! (list '= x0 x1)
      (lambda ()
        (subst (list '= x0 (list 'NTH 1 cx)))
        (subst (list '= (list 'NTH 1 cx) (list 'NTH 1 mm)))
        (subst (list '= mm cx1))
        (ass)))))

;; STEP, the property half:  goal is the class property of CONS(x0,t0).
(define (tx-step-property! a x0 t0 cls)
  (dk-peel!)
  (let* ((g    (dk-goal))                                   ; (= (CONS x0 t0) mm)
         (mm   (caddr g))
         (cx   (list 'CONS x0 t0))
         (lt0  (list 'LENGTH t0))
         (nthh (tx-pick-univ
                (lambda (c) (and (pair? c) (eq? (car c) '=)
                                 (pair? (cadr c)) (eq? (car (cadr c)) 'NTH)
                                 (equal? (caddr (cadr c)) cx)))
                "the entry hypothesis of CONS(x0,t0)")))
    (if (not (and (eq? (car g) '=) (equal? (cadr g) cx)))
        (error "tx-step-property!: unexpected goal" g))
    (fact 'length-cons x0 t0)                                ; LENGTH(cx) = succ LENGTH(t0)
    (fact 'length-in-nn a t0)                                ; LENGTH(t0) in NN
    (have! (list '= (list 'LENGTH mm) (list 'succ lt0))
      (lambda () (subst (list '= (list 'LENGTH mm) (list 'LENGTH cx))) (ass)))
    (tx-have-and! (list 'AND (list 'IN lt0 'NN)
                 (list 'AND (list 'IN mm (list 'TUPLES a))
                       (list '= (list 'LENGTH mm) (list 'succ lt0)))))
    (let* ((ex1 (dk-fact! 'tuple-cons-decompose a lt0 mm))
           (x1  (dk-skolem! ex1))                            ; the head of mm
           (ex2 (dk-pick (lambda (f) (and (pair? f) (eq? (car f) 'FORSOME)
                                          (memq x1 (free-vars f))))
                         "the tail existential"))
           (t1  (dk-skolem! ex2))                            ; the tail of mm
           (cx1 (list 'CONS x1 t1)))
      ;; the induction hypothesis: the class property of the tail t0
      (comp-me (list 'IN t0 cls))
      (let ((ih (tx-pick-univ (lambda (c) (and (pair? c) (eq? (car c) '=) (eq? (cadr c) t0)))
                              "the class property of the tail")))
        (fact 'eq-sym (list 'LENGTH t1) lt0)                 ; LENGTH(t0) = LENGTH(t1)
        (have! (tx-ext-body-entries t0 t1)
          (lambda () (tx-tail-entries! x0 t0 x1 t1 mm nthh)))
        (dk-apply! ih t1)                                    ; t0 = t1
        (tx-head-eq! x0 t0 x1 t1 mm nthh)                    ; x0 = x1
        (subst (list '= x0 x1))
        (subst (list '= t0 t1))
        (subst (list '= cx1 mm))
        (rfl)))))

;; STEP:  goal (FORALL x (FORALL M (IMPLIES (AND x in A, M in TUPLES(A), M in C) (IN (CONS x M) C)))).
(define (tx-step! a)
  (dk-split-all! (dk-peel!))
  (let* ((g   (dk-goal))                                    ; (IN (CONS x0 t0) cls)
         (x0  (cadr (cadr g)))
         (t0  (caddr (cadr g)))
         (cls (caddr g)))
    (if (not (and (eq? (car g) 'IN) (pair? (cadr g)) (eq? (car (cadr g)) 'CONS)))
        (error "tx-step!: unexpected goal" g))
    (for-each
     (lambda (leaf)
       (dk-focus! leaf)
       (let ((g1 (dk-goal)))
         (if (and (eq? (car g1) 'IN) (eq? (caddr g1) 'SET))
             (begin                                          ; CONS(x0,t0) is a set
               (tx-have-and! (list 'AND (list 'IN x0 a) (list 'IN t0 (list 'TUPLES a))))
               (fact 'cons-in-tuples a x0 t0)
               (fact 'membership-implies-sethood (list 'CONS x0 t0) (list 'TUPLES a))
               (ass))
             (tx-step-property! a x0 t0 cls))))
     (dk-opened (lambda () (comp-mi))))))

(sp (make-wff '(FORALL A (FORALL L (FORALL M
   (IMPLIES (IN L (TUPLES A))
   (IMPLIES (IN M (TUPLES A))
   (IMPLIES (= (LENGTH L) (LENGTH M))
   (IMPLIES (FORALL k_ (IMPLIES (AND (IN k_ NN) (AND (<= 1 k_) (<= k_ (LENGTH L))))
                                (= (NTH k_ L) (NTH k_ M))))
     (= L M))))))))))
(dk-peel!)
(let* ((g   (dk-goal))                                      ; (= l0 m0)
       (l0  (cadr g))
       (m0  (caddr g))
       (hyp (dk-pick (lambda (f) (and (pair? f) (eq? (car f) 'IN) (eq? (cadr f) l0)
                                      (pair? (caddr f)) (eq? (car (caddr f)) 'TUPLES)))
                     "L in TUPLES(A)"))
       (a   (cadr (caddr hyp)))
       (cls (tx-class a))
       (imp (dk-fact! 'tuples-induction a cls)))
  (if (not (and (pair? imp) (eq? (car imp) 'IMPLIES)))
      (error "tuple-extensionality: tuples-induction did not land its implication" imp))
  ;; the two induction premises, as one conjunction
  (have! (cadr imp)
    (lambda ()
      (dk-conj-close!
       (lambda ()
         (if (eq? (car (dk-goal)) 'IN) (tx-base! a) (tx-step! a))))))
  (let ((all (dk-apply! imp)))                              ; (FORALL L (IMPLIES (IN L (TUPLES a)) (IN L cls)))
    (inst*! all l0)                                         ; (IN l0 cls)
    (comp-me (list 'IN l0 cls))
    (let ((prop (tx-pick-univ (lambda (c) (and (pair? c) (eq? (car c) '=) (eq? (cadr c) l0)))
                              "the class property of L")))
      (dk-apply! prop m0)                                   ; (= l0 m0)
      (ass))))
(qed 'tuple-extensionality)
(topic! 'tuple-extensionality 'combinatorial)

;;; --------------------------------------------------------------------
;;; matrix-entry-extensionality

;; Open (IN P (MAT m n X)) through mat-basics' read-offs, landing
;;   P in TUPLES(TUPLES X), the equilong law, LENGTH(P) in NN, LENGTH(P) = m.
;; The column count LENGTH(NTH 1 P) = n is NOT landed here: it is guarded on
;; 1 <= m (`mat-cols'), which only the row lane, holding a row index, can supply.
;; Returns the equilong law.
(define (tx-open-mat! p m n x)
  (begin
    (fact 'mat-in-matrix m n x p)                            ; P in MATRIX(X)
    (dk-split! (dk-landed-1 (lambda () (mac-h 'matrix-membership (list 'IN p (list 'MATRIX x))))))
    (fact 'length-in-nn (list 'TUPLES x) p)                  ; LENGTH(P) in NN
    (fact 'mat-length m n x p)                               ; LENGTH(P) = m
    (tx-pick-univ (lambda (c) (and (pair? c) (eq? (car c) '=)
                                   (pair? (cadr c)) (eq? (car (cadr c)) 'LENGTH)
                                   (pair? (cadr (cadr c))) (eq? (car (cadr (cadr c))) 'NTH)
                                   (equal? (caddr (cadr (cadr c))) p)))
                  "the equilong law")))

;; One row:  goal (= (NTH i P) (NTH i Q)) under i in NN, 1 <= i <= LENGTH(P).
(define (tx-row-lane! p q m n x eqlp eqlq ehyp)
  (dk-split-all! (dk-peel!))
  (let* ((g   (dk-goal))
         (i   (cadr (cadr g)))
         (lp  (list 'LENGTH p))
         (lq  (list 'LENGTH q))
         (rp  (list 'NTH i p))
         (rq  (list 'NTH i q))
         (r1p (list 'NTH 1 p))
         (r1q (list 'NTH 1 q))
         (tt  (list 'TUPLES x)))
    (if (not (and (eq? (car g) '=) (equal? (cadr g) rp)))
        (error "tx-row-lane!: unexpected goal" g))
    ;; the index, on the matrix side
    (have! (list '<= i m) (lambda () (subst (list '= m lp)) (ass)))
    (tx-in-interval! i 1 m)
    ;; 1 <= LENGTH(P), 1 <= LENGTH(Q), i <= LENGTH(Q)
    (fact 'nn-one-in)
    (fact 'nn-le-refl 1)
    (fact 'nn-le-trans-guarded 1 i lp)
    (have! (list '<= i lq) (lambda () (subst (list '= lq m)) (ass)))
    (fact 'nn-le-trans-guarded 1 i lq)
    ;; the column counts: P and Q have a row, so mat-cols applies
    (have! (list '<= 1 m) (lambda () (subst (list '= m lp)) (ass)))
    (fact 'mat-cols m n x p)                                 ; LENGTH(NTH 1 P) = n
    (fact 'mat-cols m n x q)                                 ; LENGTH(NTH 1 Q) = n
    ;; the rows are tuples over X
    (tx-have-and! (list 'AND (list 'IN i 'NN)
                 (list 'AND (list 'IN p (list 'TUPLES tt))
                       (list 'AND (list '<= 1 i) (list '<= i lp)))))
    (fact 'nth-in-range tt i p)                              ; NTH(i,P) in TUPLES(X)
    (tx-have-and! (list 'AND (list 'IN i 'NN)
                 (list 'AND (list 'IN q (list 'TUPLES tt))
                       (list 'AND (list '<= 1 i) (list '<= i lq)))))
    (fact 'nth-in-range tt i q)                              ; NTH(i,Q) in TUPLES(X)
    ;; the rows have length n
    (tx-have-and! (list 'AND (list 'IN i 'NN) (list 'AND (list '<= 1 i) (list '<= i lp))))
    (tx-have-and! (list 'AND '(IN 1 NN) (list 'AND '(<= 1 1) (list '<= 1 lp))))
    (dk-apply! eqlp i 1)                                     ; LENGTH(NTH i P) = LENGTH(NTH 1 P)
    (tx-have-and! (list 'AND (list 'IN i 'NN) (list 'AND (list '<= 1 i) (list '<= i lq))))
    (tx-have-and! (list 'AND '(IN 1 NN) (list 'AND '(<= 1 1) (list '<= 1 lq))))
    (dk-apply! eqlq i 1)                                     ; LENGTH(NTH i Q) = LENGTH(NTH 1 Q)
    (fact 'eq-trans (list 'LENGTH rp) (list 'LENGTH r1p) n)  ; LENGTH(NTH i P) = n
    (fact 'eq-trans (list 'LENGTH rq) (list 'LENGTH r1q) n)  ; LENGTH(NTH i Q) = n
    (fact 'eq-sym (list 'LENGTH rq) n)
    (fact 'eq-trans (list 'LENGTH rp) n (list 'LENGTH rq))   ; LENGTH(NTH i P) = LENGTH(NTH i Q)
    ;; the entries of the two rows agree
    (have! (tx-ext-body-entries rp rq)
      (lambda ()
        (dk-split-all! (dk-peel!))
        (let* ((g2 (dk-goal))                                ; (= (NTH j rp) (NTH j rq))
               (j  (cadr (cadr g2))))
          (have! (list '<= j n) (lambda () (subst (list '= n (list 'LENGTH rp))) (ass)))
          (tx-in-interval! j 1 n)
          (dk-apply! ehyp i j)                               ; ENTRY(P,i,j) = ENTRY(Q,i,j)
          (fact 'entry-unfold p i j)
          (fact 'entry-unfold q i j)
          (subst (list '== (list 'NTH j rp) (list 'ENTRY p i j)))
          (subst (list '== (list 'NTH j rq) (list 'ENTRY q i j)))
          (ass))))
    (fact 'tuple-extensionality x rp rq)                     ; NTH(i,P) = NTH(i,Q)
    (ass)))

(sp (make-wff '(FORALL m (FORALL n (FORALL X (FORALL P (FORALL Q
     (IMPLIES (IN P (MAT m n X))
     (IMPLIES (IN Q (MAT m n X))
     (IMPLIES (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
                (FORALL j (IMPLIES (IN j (INTERVAL 1 n))
                  (= (ENTRY P i j) (ENTRY Q i j))))))
       (= P Q)))))))))))
(dk-peel!)
(let* ((g    (dk-goal))                                     ; (= p q)
       (p    (cadr g))
       (q    (caddr g))
       (hp   (dk-pick (lambda (f) (and (pair? f) (eq? (car f) 'IN) (eq? (cadr f) p)
                                       (pair? (caddr f)) (eq? (car (caddr f)) 'MAT)))
                      "P in MAT(m,n,X)"))
       (mat  (caddr hp))
       (m    (cadr mat))
       (n    (caddr mat))
       (x    (cadddr mat))
       (ehyp (tx-pick-univ (lambda (c) (and (pair? c) (eq? (car c) '=)
                                            (pair? (cadr c)) (eq? (car (cadr c)) 'ENTRY)))
                           "the entry hypothesis")))
  (let ((eqlp (tx-open-mat! p m n x))
        (eqlq (tx-open-mat! q m n x)))
    (have! (tx-ext-body-entries p q)
      (lambda () (tx-row-lane! p q m n x eqlp eqlq ehyp)))
    (fact 'eq-sym (list 'LENGTH q) m)
    (fact 'eq-trans (list 'LENGTH p) m (list 'LENGTH q))     ; LENGTH(P) = LENGTH(Q)
    (fact 'tuple-extensionality (list 'TUPLES x) p q)
    (ass)))
(qed 'matrix-entry-extensionality)
