;;; winding-number-components.scm -- THE WINDING NUMBER IS LOCALLY CONSTANT OFF THE
;;; TRACE, CONSTANT ON A CONNECTED SET OFF THE TRACE, AND 0 ON THE UNBOUNDED COMPONENT
;;; (complex-analysis.pdf ch. 3: Proposition 3.27, second half; Corollary 3.30).
;;; Agent CA-5 of week 3 of the October roadmap, 2026-10-04.
;;; Definitions: structure-library/winding-number.scm (WINDING), structure-library/
;;; metric-connected.scm (IS-CONNECTED, new this batch).
;;;
;;; CONTENTS.
;;;  (1) winding-disc-constant        a closed road, every point of its trace at distance
;;;                                   >= r from c: WINDING(z) = WINDING(c) for |z - c| < r.
;;;                                   The proof of `winding-circle-inside'
;;;                                   (cauchy-integral-formula.scm) for a GENERAL closed
;;;                                   road: Lemma 3.33 (`cauchy-kernel-integral-series')
;;;                                   with the weight 1 expands int 1/(w - z) as
;;;                                   sum_k a_k (z - c)^k, a_k = int (1/(w - c))^(k+1), and
;;;                                   a_k = 0 for k >= 1 (`cif-recip-power-closed-zero').
;;;                                   No integrality is needed for local constancy.
;;;  (2) winding-locally-constant     z0 off the trace: a ball about z0 misses the trace
;;;                                   and WINDING is constant on it.  The radius is
;;;                                   1/(M + 1) for a bound M of |1/(w - z0)| on the trace
;;;                                   (`aif-trace-bounded': a continuous function is bounded
;;;                                   on the trace of a path).
;;;  (3) winding-constant-on-connected  WINDING is constant on every connected set off the
;;;                                   trace (3.27, "constant on the connected components";
;;;                                   a component is such a set).
;;;  (4) winding-zero-unbounded       ... and 0 on a connected set off the trace that
;;;                                   reaches outside a disc containing the trace (3.30;
;;;                                   the unbounded component is such a set).
;;;  (5) winding-juxta                the winding number of a juxtaposition (JUXTA) is the
;;;                                   sum of the two (both pieces off z; no closedness).
;;;  (6) winding-opposite             of the opposite road (written as line-int-opposite-road
;;;                                   writes it, by its pointwise equations) the negative.
;;;
;;; THE NOTES' ROUTE AND THIS ONE.  The notes prove continuity in u, then use "a continuous
;;; integer-valued function is constant on connected components".  Here local constancy
;;; is proven directly from Lemma 3.33, which is stronger than continuity and needs no
;;; integrality (integrality is `winding-number-integer', winding-number-integer.scm);
;;; the passage to connected sets is `connected-locally-constant'
;;; (metric-connected-laws.scm).
;;;
;;; Helper prefix wnc-; the cif- helpers of cauchy-integral-formula.scm are copied under
;;; it (that file is not ours).  NOTHING asserted; no definition here.
;;; LOAD WINDOW: lo = theorem-library/cauchy-integral-formula (cif-recip-power-closed-zero),
;;; above analytic-from-integral (cauchy-kernel-integral-series, aif-trace-bounded,
;;; aif-magnitude-recip, aif-cont-*), winding-number-laws (winding-in-cc,
;;; winding-zero-outside-disc), road-juxtaposition-laws (line-int-juxta), line-int-laws
;;; (line-int-opposite-road), and theorem-library/metric-connected-laws
;;; (connected-locally-constant).  hi: none.  Tactics: the early kit.


;;; ======================================================================
;;; local helpers (copies of cauchy-integral-formula.scm's cif- helpers)
;;; ======================================================================
(define wnc-nfm '(NF-METRIC-SPACE CC-NORMED-FIELD))
(define (wnc-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (wnc-cont u f)
  (list 'FORALL 'rgy_ (list 'IMPLIES (list 'IN 'rgy_ u)
    (list 'IS-CONTINUOUS-AT (list 'SUBSPACE-MS wnc-nfm u) wnc-nfm f 'rgy_))))
(define (wnc-imps hyps body)
  (if (null? hyps) body (list 'IMPLIES (car hyps) (wnc-imps (cdr hyps) body))))
(define (wnc-all vars body)
  (if (null? vars) body (list 'FORALL (car vars) (wnc-all (cdr vars) body))))
(define (wnc-and! a b)
  (let* ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! dk-ass!))))
    f))
(define (wnc-pz z) (list 'DIFFERENCE 'CC (list 'SINGLETON z)))

(define (wnc-rr! t)
  (let* ((typ (list 'IN t 'RR)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'rr-zero-in) typ)
          ((eqv? t 1) (fact 'rr-one-in) typ)
          ((eq? t 'PI) (dk-split-all! (list (dk-cite! 'pi-pos))) typ)
          ((number? t) (dk-have! typ (lambda () (arith))) typ)
          ((dk-asm? (list 'IN t 'NN)) (fact 'nn-in-rr t) typ)
          ((wnc-op? t 'succ 2) (wnc-nn! t) (fact 'nn-in-rr t) typ)
          ((wnc-op? t '* 3) (wnc-rr! (cadr t)) (wnc-rr! (caddr t)) (fact 'rr-mul-in-rr (cadr t) (caddr t)) typ)
          ((wnc-op? t '+ 3) (wnc-rr! (cadr t)) (wnc-rr! (caddr t)) (fact 'rr-add-in-rr (cadr t) (caddr t)) typ)
          ((wnc-op? t '- 3) (wnc-rr! (cadr t)) (wnc-rr! (caddr t)) (fact 'rr-sub-in-rr (cadr t) (caddr t)) typ)
          ((wnc-op? t '- 2) (wnc-rr! (cadr t)) (fact 'rr-neg-closed (cadr t)) typ)
          ((wnc-op? t 'magnitude 2) (wnc-cc! (cadr t)) (fact 'cc-magnitude-closed (cadr t)) typ)
          ((wnc-op? t 'real-part 2) (wnc-cc! (cadr t)) (fact 'real-part-in-rr (cadr t)) typ)
          ((wnc-op? t 'imag-part 2) (wnc-cc! (cadr t)) (fact 'imag-part-in-rr (cadr t)) typ)
          ((wnc-op? t 'abs 2) (wnc-rr! (cadr t)) (fact 'rr-abs-closed (cadr t)) typ)
          ((wnc-op? t 'recip 2)
           (wnc-rr! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (if (dk-asm? (list '< 0 (cadr t)))
                   (fact 'rr-pos-ne-zero (cadr t))
                   (error "wnc-rr!: land the non-vanishing first" (expression->string (cadr t)))))
           (wnc-and! (list 'IN (cadr t) 'RR) (list 'NOT (list '= (cadr t) 0)))
           (fact 'rr-recip-closed (cadr t))
           typ)
          (#t (dk-real! t) typ))))
(define (wnc-nn! t)
  (let* ((typ (list 'IN t 'NN)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'nn-zero-in) typ)
          ((wnc-op? t 'succ 2) (wnc-nn! (cadr t)) (fact 'nn-succ-closed (cadr t)) typ)
          (#t (dk-type! t 'NN)))))
(define (wnc-cc! t)
  (let* ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((eqv? t +i) (fact 'cc-i-in) typ)
          ((or (and (number? t) (real? t)) (eq? t 'PI) (dk-asm? (list 'IN t 'RR)) (dk-asm? (list 'IN t 'NN))
               (wnc-op? t 'succ 2)
               (wnc-op? t 'magnitude 2) (wnc-op? t 'real-part 2) (wnc-op? t 'imag-part 2))
           (wnc-rr! t) (fact 'rr-subset-cc t) typ)
          ((wnc-op? t '- 3) (wnc-cc! (cadr t)) (wnc-cc! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((wnc-op? t '- 2) (wnc-cc! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((wnc-op? t '+ 3) (wnc-cc! (cadr t)) (wnc-cc! (caddr t))
           (wnc-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((wnc-op? t '* 3) (wnc-cc! (cadr t)) (wnc-cc! (caddr t))
           (wnc-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((wnc-op? t 'power 3) (wnc-cc! (cadr t)) (wnc-nn! (caddr t))
           (wnc-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'NN)) (fact 'power-typing-nonneg (cadr t) (caddr t)) typ)
          ((wnc-op? t 'CC-EXP 2) (wnc-cc! (cadr t))
           (dk-split-all! (list (dk-cite! 'cc-exp-converges (cadr t)))) typ)
          ((wnc-op? t 'recip 2) (wnc-cc! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (error "wnc-cc!: land the non-vanishing first" (expression->string (cadr t))))
           (wnc-and! (list 'IN (cadr t) 'CC) (list 'NOT (list '= (cadr t) 0)))
           (fact 'cc-recip-closed (cadr t)) typ)
          (#t (dk-type! t 'CC)))))

;;; y in CC \ {z}: land y in CC, y /= z, y - z /= 0
(define (wnc-sub-nz! y z)
  (let* ((nz (list 'NOT (list '= (list '- y z) 0))))
    (dk-have! nz
      (lambda ()
        (di)
        (dk-cite! 'cc-sub-zero-eq y z)
        (ai (dk-ctx-form (list 'NOT (list '= y z))))))
    nz))
(define (wnc-steps . thunks)
  ;; run THUNKS in order while the leaf focused at the start stays open
  (let* ((leaf (proof-state-focus *ps*)))
    (let loop ((ts thunks))
      (if (and (pair? ts) (not (sequent-node-grounded? leaf)))
          (begin ((car ts)) (loop (cdr ts)))))))
(define (wnc-pz-open! z y)
  (let* ((iff (dk-cite! 'cc-punctured-membership z y)))
    (wnc-steps
      (lambda () (dk-have! (list 'IN y 'CC) (lambda () (wnc-only-prop! iff (list 'IN y (wnc-pz z))))))
      (lambda () (dk-have! (list 'NOT (list '= y z)) (lambda () (wnc-only-prop! iff (list 'IN y (wnc-pz z))))))
      (lambda () (wnc-sub-nz! y z)))))
(define (wnc-pz-in! z y)
  (let* ((iff (dk-cite! 'cc-punctured-membership z y)))
    (dk-have! (list 'IN y (wnc-pz z))
      (lambda () (wnc-only-prop! iff (list 'IN y 'CC) (list 'NOT (list '= y z)))))))
;;; the punctured plane: open (both spellings), a set
(define (wnc-pz-setup! z)
  (let* ((d (wnc-pz z)))
    (fact 'nf-cc-is-metric-space)
    (dk-cite! 'cc-punctured-open z)
    (let* ((iff (dk-cite! 'cc-ms-open-iff d)))
      (dk-have! (list 'IS-OPEN wnc-nfm d) (lambda () (wnc-only-prop! iff (list 'IS-OPEN 'CC-MS d)))))
    (fact 'cc-is-set)
    (dk-cite! 'difference-set 'CC (list 'SINGLETON z))
    (dk-cite! 'cc-open-subset-cc d)))
;;; (wnc-lam-typ! LAM DOM TYPER) -- LAM in FUN(DOM, CC); TYPER of the eigenvariable
(define (wnc-lam-typ! lam dom pre)
  (dk-have! (list 'IN lam (list 'FUN dom 'CC))
    (lambda ()
      (dk-lam-type! (lambda ()
                      (let* ((v (dk-di-var!)) (leaf (proof-state-focus *ps*)))
                        (wnc-steps
                          (lambda () (pre v))
                          (lambda () (if (dk--redex? (dk-goal)) (dk-lam-b!)))
                          (lambda () (if (not (dk-asm? (dk-goal))) (wnc-cc! (cadr (dk-goal)))))
                          (lambda () (ass)))))))))
;;; detach an implication whose antecedent THUNK proves
(define (wnc-detach! imp thunk)
  (if (and (pair? imp) (eq? (car imp) 'IMPLIES))
      (begin (dk-have! (cadr imp) thunk)
             (dk-landed-1 (lambda () (detach! imp))))
      imp))
(define (wnc-only-prop! . fs) (if (apply dk-only! fs) (prop)))
(define (wnc-lam-b-if!) (if (dk--redex? (dk-goal)) (dk-lam-b!)))
;;; subst, then ass on the SAME leaf unless the subst closed it
(define (wnc-subst-ass! eq)
  (let* ((leaf (proof-state-focus *ps*)))
    (subst eq)
    (if (not (sequent-node-grounded? leaf)) (ass))))
(define (wnc-R c) (list 'VNB-LAMBDA 'cifv_ (wnc-pz c) (list 'recip (list '- 'cifv_ c))))
(define (wnc-S c) (list 'VNB-LAMBDA 'cifv_ (wnc-pz c) (list '- 'cifv_ c)))
(define (wnc-P c n) (list 'VNB-LAMBDA 'cifv_ (wnc-pz c) (list 'power (list 'recip (list '- 'cifv_ c)) n)))
(define (wnc-pow-succ! a n)
  (wnc-cc! a) (wnc-nn! n)
  (wnc-and! (list 'IN a 'CC) (list 'IN n 'NN))
  (dk-cite! 'power-succ a n))
(define (wnc-Hk g k)
  (list 'VNB-LAMBDA 'aiw_ wnc-T (list '* (list g 'aiw_) (list 'power '(recip (- aiw_ c)) (list 'succ k)))))
(define (wnc-LI f) (list 'LINE-INT f 'pgam 'dgam 'a 'b))
(define (wnc-kern-setup! p)
  (let* ((dd (wnc-pz p)) (k (wnc-kern p)))
    (dk-cite! 'winding-integrand-holomorphic p)
    (dk-cite! 'holomorphic-on-in-fun dd k)
    (dk-cite! 'holomorphic-on-continuous dd k)
    (dk-cite! 'holomorphic-on-open dd k)
    (dk-cite! 'cc-open-subset-cc dd)))

;;; the road's trace and the kernel about p
(define wnc-T '(TRACE pgam a b))
(define (wnc-kern z) (list 'VNB-LAMBDA 'wnw_ (wnc-pz z) (list 'recip (list '- 'wnw_ z))))
(define (wnc-tpt! x . zs)
  (wnc-steps
    (lambda () (fact 'subset-mem-fwd wnc-T (wnc-pz 'c) x))
    (lambda () (wnc-pz-open! 'c x))
    (lambda () (for-each (lambda (z) (fact 'subset-mem-fwd wnc-T (wnc-pz z) x) (wnc-pz-open! z x)) zs))))

;;; ======================================================================
;;; (1) WINDING-DISC-CONSTANT
;;; ======================================================================
(define wnc-dist-h '(FORALL wcy_ (IMPLIES (IN wcy_ (TRACE pgam a b)) (<= r (magnitude (- wcy_ c))))))
;;; y in the trace: y in CC, y /= c, y /= z, y in CC \ {c}, CC \ {z}
(define wnc-dh #f)
(define (wnc-trace-pt! y)
  (let* ((m (list 'magnitude (list '- y 'c))))
    (wnc-steps
      (lambda () (fact 'subset-mem-fwd wnc-T 'CC y))
      (lambda () (dk-apply! wnc-dh y))
      (lambda () (wnc-rr! m))
      (lambda ()
        (dk-have! (list 'NOT (list '= y 'c))
          (lambda ()
            (di)
            (dk-have! (list '= m 0)
              (lambda () (subst (list '= y 'c))
                         (dk-have! '(= (- c c) 0) (lambda () (crs)))
                         (subst '(= (- c c) 0))
                         (fact 'cc-magnitude-zero)
                         (ass)))
            (dk-absurd! (list 'IN m 'RR) '(IN r RR) (list '= m 0) (list '<= 'r m) '(< 0 r)))))
      (lambda () (wnc-sub-nz! y 'c))
      (lambda () (wnc-pz-in! 'c y)))))
(define (wnc-trace-not-z! y)
  (wnc-steps
    (lambda ()
      (dk-have! (list 'NOT (list '= y 'z))
        (lambda ()
          (di)
          (dk-have! (list '<= 'r '(magnitude (- z c)))
            (lambda () (subst (list '= 'z y)) (ass)))
          (wnc-rr! '(magnitude (- z c)))
          (dk-absurd! '(IN (magnitude (- z c)) RR) '(IN r RR) '(<= r (magnitude (- z c))) '(< (magnitude (- z c)) r)))))
    (lambda () (wnc-sub-nz! y 'z))
    (lambda () (wnc-pz-in! 'z y))))
(define (wnc-trace-in-pz! p)
  (dk-have! (list 'SUBSET wnc-T (wnc-pz p))
    (lambda ()
      (let* ((y (subset-by-element!)) (leaf (proof-state-focus *ps*)))
        (wnc-trace-pt! y)
        (if (eq? p 'z) (wnc-trace-not-z! y))
        (if (not (sequent-node-grounded? leaf)) (ass))))))

(sp (make-wff (list 'FORALL 'pgam (list 'FORALL 'dgam (list 'FORALL 'a (list 'FORALL 'b
  (list 'IMPLIES '(IS-ROAD pgam dgam a b) (list 'IMPLIES '(= (pgam b) (pgam a))
    (list 'FORALL 'c (list 'IMPLIES '(IN c CC) (list 'FORALL 'r (list 'IMPLIES '(IN r RR) (list 'IMPLIES '(< 0 r)
      (list 'IMPLIES wnc-dist-h
        (list 'FORALL 'z (list 'IMPLIES '(IN z CC) (list 'IMPLIES '(< (magnitude (- z c)) r)
          '(= (WINDING pgam dgam a b z) (WINDING pgam dgam a b c)))))))))))))))))))
(dk-peel!)
(set! wnc-dh (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL) (dk-contains? fm 'wcy_))) "the distance hypothesis"))
(fact 'is-road-is-path 'pgam 'dgam 'a 'b)
(fact 'is-path-in-fun 'pgam 'a 'b)
(dk-cite! 'trace-subset-cc 'pgam 'a 'b)
(dk-split! (dk-fact! 'is-path-endpoints 'pgam 'a 'b))
(dk-split-all!)
(dk-have! '(<= 0 r) (lambda () (dk-ineq! '(< 0 r))))
(dk-cite! 'trace-is-set 'pgam 'a 'b)
(fact 'subset-refl wnc-T)
(wnc-pz-setup! 'c)
(wnc-pz-setup! 'z)
(wnc-kern-setup! 'c)
(wnc-kern-setup! 'z)
(wnc-trace-in-pz! 'c)
(wnc-trace-in-pz! 'z)
(fact 'cc-one-in)
(define wnc-wi-pair
  (dk-abstract! wnc-T 'CC (lambda (y) 1) (lambda (y) (ass))))
(define wnc-wi-g (car wnc-wi-pair))
(define wnc-wi-gv (cdr wnc-wi-pair))
(dk-cite! 'aif-cont-const wnc-T 1 wnc-wi-g)
(dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ wnc-T) '(<= r (magnitude (- aix_ c)))))
  (lambda () (let ((y (dk-di-var!))) (dk-apply! wnc-dh y) (dk-ass!))))
(define wnc-wi-ks (dk-cite! 'cauchy-kernel-integral-series wnc-T 'c 'r wnc-wi-g 'pgam 'dgam 'a 'b 'z))
(define wnc-wi-tt (cadr wnc-wi-ks))
(define wnc-wi-lz (caddr wnc-wi-ks))
;;; G(y) = 1 on the trace, as an equation at a point y of the trace
(define (wnc-wi-g1! y) (dk-apply! wnc-wi-gv y))
;;; a_0 = int 1/(w - c)
(define wnc-wi-h0 (wnc-Hk wnc-wi-g 0))
(wnc-lam-typ! wnc-wi-h0 wnc-T (lambda (v) (wnc-tpt! v) (wnc-wi-g1! v) (fact 'nn-zero-in) (fact 'nn-succ-closed 0)
                                   (wnc-lam-b-if!) (subst (list '== (list wnc-wi-g v) 1))))
(dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ wnc-T) (list '== (list wnc-wi-h0 'wnx_) (list (wnc-kern 'c) 'wnx_))))
  (lambda ()
    (let* ((x (dk-di-var!)) (ax (list 'recip (list '- x 'c))))
      (wnc-tpt! x)
      (wnc-wi-g1! x)
      (dk-lam-b!)
      (subst (list '== (list wnc-wi-g x) 1))
      (subst (wnc-pow-succ! ax 0))
      (subst (dk-cite! 'power-zero ax))
      (dk-have! (list '= (list '* 1 (list '* ax 1)) ax) (lambda () (crs)))
      (subst (list '= (list '* 1 (list '* ax 1)) ax))
      (qrfl))))
(define wnc-wi-a0
  (dk-cite! 'line-int-domain-congruence (wnc-pz 'c) (wnc-kern 'c) 'pgam 'dgam 'a 'b wnc-T wnc-wi-h0))
(dk-cite! 'line-int-in-cc (wnc-pz 'c) (wnc-kern 'c) 'pgam 'dgam 'a 'b)
;;; a_(q+1) = 0
(define wnc-wi-az
  (list 'FORALL 'cifq_ (list 'IMPLIES '(IN cifq_ NN) (list '= (wnc-LI (wnc-Hk wnc-wi-g '(succ cifq_))) 0))))
(dk-have! wnc-wi-az
  (lambda ()
    (let* ((q (dk-di-var!)) (sq (list 'succ q)) (ssq (list 'succ sq))
           (d (wnc-pz 'c)) (R (wnc-R 'c)) (P (wnc-P 'c ssq)) (H (wnc-Hk wnc-wi-g sq)))
      (fact 'nn-succ-closed q)
      (fact 'nn-succ-closed sq)
      (wnc-lam-typ! P d (lambda (v) (wnc-pz-open! 'c v)))
      (wnc-lam-typ! R d (lambda (v) (wnc-pz-open! 'c v)))
      (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ d) '(NOT (= aix_ c))))
        (lambda () (let* ((v (dk-di-var!))) (wnc-steps (lambda () (wnc-pz-open! 'c v)) ass))))
      (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ d) (list '== (list R 'aix_) '(recip (- aix_ c)))))
        (lambda () (let* ((v (dk-di-var!))) (wnc-pz-open! 'c v) (dk-lam-b!) (qrfl))))
      (dk-cite! 'aif-cont-recip-shift d 'c R)
      (dk-have! (list 'FORALL 'aix_ (list 'IMPLIES (list 'IN 'aix_ d) (list '== (list P 'aix_) (list 'power (list R 'aix_) ssq))))
        (lambda () (let* ((v (dk-di-var!))) (wnc-pz-open! 'c v) (dk-lam-b!) (qrfl))))
      (dk-cite! 'aif-cont-power-of d R ssq P)
      (wnc-lam-typ! H wnc-T (lambda (v) (wnc-tpt! v) (wnc-wi-g1! v)
                                 (wnc-lam-b-if!) (subst (list '== (list wnc-wi-g v) 1))))
      (dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ wnc-T) (list '== (list H 'wnx_) (list P 'wnx_))))
        (lambda ()
          (let* ((x (dk-di-var!)) (px (list 'power (list 'recip (list '- x 'c)) ssq)))
            (wnc-tpt! x)
            (wnc-wi-g1! x)
            (dk-lam-b!)
            (subst (list '== (list wnc-wi-g x) 1))
            (wnc-cc! px)
            (dk-have! (list '= (list '* 1 px) px) (lambda () (crs)))
            (subst (list '= (list '* 1 px) px))
            (qrfl))))
      (let* ((e1 (dk-cite! 'line-int-domain-congruence d P 'pgam 'dgam 'a 'b wnc-T H))
            (e2 (dk-cite! 'cif-recip-power-closed-zero q 'c 'pgam 'dgam 'a 'b)))
        (wnc-subst-ass! e1)))))
;;; every a_k is a complex number
(define wnc-wi-at
  (list 'FORALL 'cifk_ (list 'IMPLIES '(IN cifk_ NN) (list 'IN (wnc-LI (wnc-Hk wnc-wi-g 'cifk_)) 'CC))))
(dk-have! wnc-wi-at
  (lambda ()
    (let* ((k (dk-di-var!)))
      (use-cases (dk-fact! 'nn-zero-or-succ k)
        (lambda ()
          (subst (list '= k 0))
          (wnc-subst-ass! wnc-wi-a0))
        (lambda ()
          (let* ((q (dk-skolem! (dk-pick (dk-head? 'FORSOME) "the predecessor"))))
            (subst (list '= k (list 'succ q)))
            (fact 'cc-zero-in)
            (wnc-subst-ass! (dk-apply! (dk-ctx-form wnc-wi-az) q))))))))
(define (wnc-wi-typ-tt! lam)
  (wnc-lam-typ! lam 'NN (lambda (v) (dk-apply! (dk-ctx-form wnc-wi-at) v) (wnc-cc! '(- z c)))))
(wnc-wi-typ-tt! wnc-wi-tt)
(define wnc-wi-sz (dk-cite! 'cps-sum-at-zero wnc-wi-tt))
(dk-split-all! (list wnc-wi-sz))
(define wnc-wi-tt2 (cadr (dk-pick (dk-head? 'CC-SERIES-CONVERGES) "the series at 0")))
(wnc-wi-typ-tt! wnc-wi-tt2)
(dk-fun-ext! wnc-wi-tt wnc-wi-tt2 'NN 'CC #f #f
  (lambda (v)
    (dk-apply! (dk-ctx-form wnc-wi-at) v)
    (use-cases (dk-fact! 'nn-zero-or-succ v)
      (lambda ()
        (subst (list '= v 0))
        (fact 'nn-zero-in)
        (dk-lam-b!)
        (subst (dk-cite! 'power-zero 0))
        (wnc-cc! '(- z c))
        (subst (dk-cite! 'power-zero '(- z c)))
        (subst wnc-wi-a0)
        (crs))
      (lambda ()
        (let* ((q (dk-skolem! (dk-pick (dk-head? 'FORSOME) "the predecessor"))))
          (subst (list '= v (list 'succ q)))
          (fact 'nn-succ-closed q)
          (dk-lam-b!)
          (subst (dk-apply! (dk-ctx-form wnc-wi-az) q))
          (subst (dk-cite! 'power-zero-base q))
          (wnc-cc! '(- z c))
          (fact 'nn-succ-closed q)
          (wnc-cc! (list 'power '(- z c) (list 'succ q)))
          (crs))))))
(dk-have! (list 'CC-SERIES-CONVERGES-TO wnc-wi-tt2 wnc-wi-lz)
  (lambda () (wnc-subst-ass! (list '= wnc-wi-tt2 wnc-wi-tt))))
(fact 'cc-series-limit-converges-to wnc-wi-tt2)
(define wnc-wi-ps (list 'VNB-LAMBDA 'k 'NN (list 'CC-SERIES-PARTIAL-SUM wnc-wi-tt2 'k)))
(define wnc-wi-l2 (list 'CC-SERIES-LIMIT wnc-wi-tt2))
(dk-project! (list 'CONVERGES-TO 'CC-MS wnc-wi-ps wnc-wi-lz) 'cc-series-converges-to
             (list 'CC-SERIES-CONVERGES-TO wnc-wi-tt2 wnc-wi-lz))
(dk-project! (list 'CONVERGES-TO 'CC-MS wnc-wi-ps wnc-wi-l2) 'cc-series-converges-to
             (list 'CC-SERIES-CONVERGES-TO wnc-wi-tt2 wnc-wi-l2))
;;; the integral about z equals the integral about c
(define wnc-wi-hz (cadr wnc-wi-lz))
(wnc-lam-typ! wnc-wi-hz wnc-T (lambda (v) (wnc-tpt! v 'z) (wnc-wi-g1! v)
                                   (wnc-lam-b-if!) (subst (list '== (list wnc-wi-g v) 1))))
(dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ wnc-T) (list '== (list wnc-wi-hz 'wnx_) (list (wnc-kern 'z) 'wnx_))))
  (lambda ()
    (let* ((x (dk-di-var!)) (ax (list 'recip (list '- x 'z))))
      (wnc-tpt! x 'z)
      (wnc-wi-g1! x)
      (dk-lam-b!)
      (subst (list '== (list wnc-wi-g x) 1))
      (wnc-cc! ax)
      (dk-have! (list '= (list '* 1 ax) ax) (lambda () (crs)))
      (subst (list '= (list '* 1 ax) ax))
      (qrfl))))
(define wnc-wi-ez
  (dk-cite! 'line-int-domain-congruence (wnc-pz 'z) (wnc-kern 'z) 'pgam 'dgam 'a 'b wnc-T wnc-wi-hz))
(dk-cite! 'line-int-in-cc (wnc-pz 'z) (wnc-kern 'z) 'pgam 'dgam 'a 'b)
(dk-cite! 'metric-limit-unique 'CC-MS wnc-wi-ps wnc-wi-lz wnc-wi-l2)
(dk-have! (list '= (wnc-LI (wnc-kern 'z)) (wnc-LI (wnc-kern 'c)))
  (lambda ()
    (subst (list '= (wnc-LI (wnc-kern 'z)) wnc-wi-lz))
    (subst (list '= wnc-wi-lz wnc-wi-l2))
    (subst (list '= wnc-wi-l2 (list wnc-wi-tt 0)))
    (fact 'nn-zero-in)
    (dk-lam-b!)
    (wnc-cc! '(- z c))
    (subst (dk-cite! 'power-zero '(- z c)))
    (subst wnc-wi-a0)
    (crs)))
(dk-have! '(NOT (IN c (TRACE pgam a b)))
  (lambda ()
    (di)
    (fact 'subset-mem-fwd wnc-T (wnc-pz 'c) 'c)
    (wnc-pz-open! 'c 'c)
    (dk-have! '(= c c) (lambda () (rfl)))
    (ai '(NOT (= c c)))))
(dk-cite! 'winding-in-cc 'pgam 'dgam 'a 'b 'c)
(dk-have! '(== (WINDING pgam dgam a b z) (WINDING pgam dgam a b c))
  (lambda ()
    (mac 'WINDING)
    (subst (list '= (wnc-LI (wnc-kern 'z)) (wnc-LI (wnc-kern 'c))))
    (qrfl)))
(subst '(== (WINDING pgam dgam a b z) (WINDING pgam dgam a b c)))
(rfl)
(qed 'winding-disc-constant)

;;; ======================================================================
;;; (2) WINDING-LOCALLY-CONSTANT
;;; ======================================================================
;;; x in BALL(CC-MS, c, r) in context: land x in CC and |c - x| < r; return the latter
;;; (winding-number-laws.scm's wnd-ball-open!, copied)
(define (wnc-ball-open! c r x)
  (let* ((dcx (list '(DIST CC-MS) c x))
         (mag (list 'magnitude (list '- c x)))
         (iff (dk-cite! 'ball-membership 'CC-MS c r x))
         (cj  (list 'AND (list 'IN x '(PTS CC-MS)) (list 'AND (list '<= dcx r) (list 'NOT (list '= dcx r))))))
    (dk-have! cj (lambda () (dk-only! iff (list 'IN x (list 'BALL 'CC-MS c r))) (prop)))
    (dk-split-all! (list (dk-ctx-form cj)))
    (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
    (dk-have! (list 'IN x 'CC) (lambda () (subst '(= CC (PTS CC-MS))) (ass)))
    (dk-cite! 'cc-ms-dist c x)
    (wnc-rr! mag)
    (dk-have! (list 'AND (list '<= mag r) (list 'NOT (list '= mag r)))
      (lambda () (subst (list '= mag dcx)) (dk-conj-close! dk-ass!)))
    (dk-cite! 'rr-le-ne-lt mag r)))

(define (wnc-kp! . fs)
  (let ((node (proof-state-focus *ps*)))
    (apply keep fs)
    (if (not (sequent-node-grounded? node)) (prop))))
(define wnc-z0 'wnz_)
(sp (make-wff '(FORALL pgam (FORALL dgam (FORALL a (FORALL b (IMPLIES (IS-ROAD pgam dgam a b)
  (IMPLIES (= (pgam b) (pgam a))
    (FORALL wnz_ (IMPLIES (IN wnz_ CC) (IMPLIES (NOT (IN wnz_ (TRACE pgam a b)))
      (FORSOME wcr_ (AND (POS-RR wcr_)
        (FORALL wcz_ (IMPLIES (IN wcz_ (BALL CC-MS wnz_ wcr_))
          (AND (NOT (IN wcz_ (TRACE pgam a b)))
               (= (WINDING pgam dgam a b wcz_) (WINDING pgam dgam a b wnz_))))))))))))))))))
(dk-peel!)
(fact 'is-road-is-path 'pgam 'dgam 'a 'b)
(fact 'is-path-in-fun 'pgam 'a 'b)
(dk-cite! 'trace-subset-cc 'pgam 'a 'b)
(dk-split! (dk-fact! 'is-path-endpoints 'pgam 'a 'b))
(dk-split-all!)
(wnc-pz-setup! wnc-z0)
(wnc-kern-setup! wnc-z0)
;; the trace lies in CC \ {z0}
(dk-have! (list 'SUBSET wnc-T (wnc-pz wnc-z0))
  (lambda ()
    (let ((w (subset-by-element!)))
      (fact 'subset-mem-fwd wnc-T 'CC w)
      (dk-have! (list 'NOT (list '= w wnc-z0))
        (lambda () (di) (dk-have! (list 'IN wnc-z0 wnc-T) (lambda () (subst (list '= wnc-z0 w)) (dk-ass!)))
                   (ai (dk-ctx-form (list 'NOT (list 'IN wnc-z0 wnc-T))))))
      (wnc-pz-in! wnc-z0 w))))
;; a bound M of |1/(w - z0)| on the trace; N = M + 1; the radius 1/N
(define wnc-mm (dk-skolem! (dk-cite! 'aif-trace-bounded (wnc-pz wnc-z0) (wnc-kern wnc-z0) 'pgam 'a 'b)))
(dk-split-all!)
(define wnc-mb (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL) (dk-contains? fm wnc-mm))) "the bound"))
(define wnc-nn (list '+ wnc-mm 1))
(wnc-rr! wnc-nn)
(dk-have! (list '< 0 wnc-nn) (lambda () (dk-ineq! (list '<= 0 wnc-mm))))
(define wnc-r0 (list 'recip wnc-nn))
(wnc-rr! wnc-r0)
(dk-cite! 'rr-recip-pos wnc-nn)
(dk-cite! 'rr-pos-rr-of-lt wnc-r0)
;; every point of the trace is at distance >= 1/N from z0
(dk-have! (list 'FORALL 'wcy_ (list 'IMPLIES (list 'IN 'wcy_ wnc-T) (list '<= wnc-r0 (list 'magnitude (list '- 'wcy_ wnc-z0)))))
  (lambda ()
    (let* ((w (dk-di-var!))
           (d (list '- w wnc-z0))
           (md (list 'magnitude d))
           (rd (list 'recip md)))
      (fact 'subset-mem-fwd wnc-T (wnc-pz wnc-z0) w)
      (wnc-pz-open! wnc-z0 w)
      (dk-apply! wnc-mb w)
      (wnc-cc! d)
      (wnc-cc! (list 'recip d))
      (dk-have! (list '= (list (wnc-kern wnc-z0) w) (list 'recip d)) (lambda () (dk-lam-b!) (rfl)))
      (dk-cite! 'aif-magnitude-recip d)
      (wnc-rr! md)
      (dk-cite! 'cc-magnitude-nonneg d)
      (let ((iff (dk-cite! 'cc-magnitude-zero-iff d)))
        (dk-have! (list 'NOT (list '= 0 md))
          (lambda ()
            (di)
            (dk-have! (list '= md 0) (lambda () (subst (list '= md 0)) (rfl)))
            (wnc-kp! iff (list '= md 0) (list 'NOT (list '= d 0))))))
      (wnc-and! (list '<= 0 md) (list 'NOT (list '= 0 md)))
      (fact 'rr-zero-in)
      (dk-cite! 'rr-le-ne-lt 0 md)
      (wnc-rr! rd)
      (dk-cite! 'rr-recip-pos md)
      (dk-have! (list '<= rd wnc-nn)
        (lambda ()
          (wnc-cc! (list 'recip d))
          (dk-cite! 'cc-magnitude-closed (list 'recip d))
          (dk-have! (list '<= (list 'magnitude (list 'recip d)) wnc-mm)
            (lambda () (subst (list '= (list 'recip d) (list (wnc-kern wnc-z0) w))) (dk-ass!)))
          (subst (list '= rd (list 'magnitude (list 'recip d))))
          (dk-ineq! (list '<= (list 'magnitude (list 'recip d)) wnc-mm))))
      (dk-cite! 'rr-recip-antitone rd wnc-nn)
      (dk-cite! 'rr-recip-recip-pos md)
      (subst (list '= md (list 'recip rd)))
      (dk-ass!))))
(define wnc-lc-ball (list 'BALL 'CC-MS wnc-z0 wnc-r0))
(ew wnc-r0)
(dk-conj-close!
  (lambda ()
    (if (not (dk-ass!))
        (let* ((z (dk-di-var!))
               (lt (wnc-ball-open! wnc-z0 wnc-r0 z))
               (mz (list 'magnitude (list '- z wnc-z0))))
          (wnc-rr! mz)
          (dk-cite! 'cc-magnitude-sub-sym wnc-z0 z)
          (dk-have! (list '< mz wnc-r0)
            (lambda () (subst (list '= mz (list 'magnitude (list '- wnc-z0 z)))) (dk-ass!)))
          (dk-conj-close!
            (lambda ()
              (if (eq? (car (dk-goal)) 'NOT)
                  (begin
                    (di)
                    (let ((dh (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL) (dk-contains? fm 'wcy_))) "the distance bound")))
                      (dk-apply! dh z)
                      (dk-absurd! (list 'IN mz 'RR) (list 'IN wnc-r0 'RR) (list '<= wnc-r0 mz) (list '< mz wnc-r0))))
                  (let ((dh (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL) (dk-contains? fm 'wcy_))) "the distance bound")))
                    (dk-have! (list '< 0 wnc-r0) (lambda () (dk-ass!)))
                    (dk-cite! 'winding-disc-constant 'pgam 'dgam 'a 'b wnc-z0 wnc-r0 z)
                    (dk-ass!)))))))))
(qed 'winding-locally-constant)

;;; ======================================================================
;;; (3) WINDING-CONSTANT-ON-CONNECTED
;;; ======================================================================
(define wnc-road-closed '((IS-ROAD pgam dgam a b) (= (pgam b) (pgam a))))
(define (wnc-imps hs body) (if (null? hs) body (list 'IMPLIES (car hs) (wnc-imps (cdr hs) body))))
(define wnc-off-h '(FORALL wcx_ (IMPLIES (IN wcx_ wca_) (NOT (IN wcx_ (TRACE pgam a b))))))
(define wnc-wf '(VNB-LAMBDA wcv_ wca_ (WINDING pgam dgam a b wcv_)))
(sp (make-wff (list 'FORALL 'pgam (list 'FORALL 'dgam (list 'FORALL 'a (list 'FORALL 'b
  (wnc-imps wnc-road-closed
    (list 'FORALL 'wca_ (wnc-imps (list '(IS-CONNECTED CC-MS wca_) wnc-off-h)
      '(FORALL wcp_ (IMPLIES (IN wcp_ wca_) (FORALL wcq_ (IMPLIES (IN wcq_ wca_)
         (= (WINDING pgam dgam a b wcp_) (WINDING pgam dgam a b wcq_)))))))))))))))
(dk-peel!)
(define wnc-offu (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL) (eq? (cadr fm) 'wcx_))) "off the trace"))
(dk-project! '(SUBSET wca_ (PTS CC-MS)) 'IS-CONNECTED '(IS-CONNECTED CC-MS wca_))
(dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
(dk-have! '(SUBSET wca_ CC) (lambda () (subst '(= CC (PTS CC-MS))) (dk-ass!)))
(define (wnc-at-a! x)
  ;; x in A: x in CC, x off the trace
  (fact 'subset-mem-fwd 'wca_ 'CC x)
  (dk-apply! wnc-offu x))
(dk-have! (list 'FORALL 'mcx_ (list 'IMPLIES '(IN mcx_ wca_)
            (list 'FORSOME 'mcr_ (list 'AND '(POS-RR mcr_)
              (list 'FORALL 'mcy_ (list 'IMPLIES '(IN mcy_ wca_)
                (list 'IMPLIES '(IN mcy_ (BALL CC-MS mcx_ mcr_)) (list '= (list wnc-wf 'mcy_) (list wnc-wf 'mcx_)))))))))
  (lambda ()
    (let* ((x (dk-di-var!)))
      (wnc-at-a! x)
      (let* ((ex (dk-cite! 'winding-locally-constant 'pgam 'dgam 'a 'b x))
             (r (dk-skolem! ex 'top))
             (bu (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL) (dk-contains? fm (list 'BALL 'CC-MS x r))))
                          "the ball of constancy")))
        (ew r)
        (dk-conj-close!
          (lambda ()
            (if (not (dk-ass!))
                (let ((y (dk-di-var!)))
                  (di)
                  (dk-split-all! (list (dk-apply! bu y)))
                  (dk-lam-b!)
                  (dk-ass!)))))))))
(define wnc-cl (dk-cite! 'connected-locally-constant 'CC-MS 'wca_ wnc-wf))
(dk-apply! wnc-cl 'wcp_ 'wcq_)
(for-each (lambda (x) (wnc-at-a! x) (dk-cite! 'winding-in-cc 'pgam 'dgam 'a 'b x)) '(wcp_ wcq_))
(dk-have! (list '= (list wnc-wf 'wcp_) '(WINDING pgam dgam a b wcp_)) (lambda () (dk-lam-b!) (rfl)))
(dk-have! (list '= (list wnc-wf 'wcq_) '(WINDING pgam dgam a b wcq_)) (lambda () (dk-lam-b!) (rfl)))
(subst (list '= '(WINDING pgam dgam a b wcp_) (list wnc-wf 'wcp_)))
(subst (list '= '(WINDING pgam dgam a b wcq_) (list wnc-wf 'wcq_)))
(dk-ass!)
(qed 'winding-constant-on-connected)

;;; ======================================================================
;;; (4) WINDING-ZERO-UNBOUNDED
;;; ======================================================================
(sp (make-wff (list 'FORALL 'pgam (list 'FORALL 'dgam (list 'FORALL 'a (list 'FORALL 'b
  (wnc-imps wnc-road-closed
    (list 'FORALL 'c (wnc-imps '((IN c CC))
      (list 'FORALL 'r (wnc-imps '((IN r RR) (< 0 r) (SUBSET (TRACE pgam a b) (BALL CC-MS c r)))
        (list 'FORALL 'wca_ (wnc-imps (list '(IS-CONNECTED CC-MS wca_) wnc-off-h)
          '(FORALL wcu_ (IMPLIES (IN wcu_ wca_) (IMPLIES (NOT (IN wcu_ (BALL CC-MS c r)))
             (FORALL wcp_ (IMPLIES (IN wcp_ wca_) (= (WINDING pgam dgam a b wcp_) 0)))))))))))))))))))
(dk-peel!)
(dk-project! '(SUBSET wca_ (PTS CC-MS)) 'IS-CONNECTED '(IS-CONNECTED CC-MS wca_))
(dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
(dk-have! '(SUBSET wca_ CC) (lambda () (subst '(= CC (PTS CC-MS))) (dk-ass!)))
(fact 'subset-mem-fwd 'wca_ 'CC 'wcu_)
(dk-cite! 'winding-zero-outside-disc 'pgam 'dgam 'a 'b 'c 'r 'wcu_)
(dk-apply! (dk-cite! 'winding-constant-on-connected 'pgam 'dgam 'a 'b 'wca_) 'wcp_ 'wcu_)
(subst '(= (WINDING pgam dgam a b wcp_) (WINDING pgam dgam a b wcu_)))
(dk-ass!)
(qed 'winding-zero-unbounded)

;;; ======================================================================
;;; (5) WINDING-JUXTA and (6) WINDING-OPPOSITE: the winding number of a juxtaposition
;;; is the sum, of the opposite road the negative
;;; ======================================================================
(define wnc-tpi '(* (* 2 PI) +i))
(define (wnc-tpi!)
  (wnc-rr! '(* 2 PI))
  (dk-have! '(< 0 (* 2 PI)) (lambda () (dk-ineq! '(< 0 PI))))
  (dk-cite! 'rr-pos-ne-zero '(* 2 PI))
  (wnc-cc! '(* 2 PI))
  (fact 'cc-i-in)
  (dk-have! '(NOT (= +i 0))
    (lambda ()
      (di)
      (fact 'cc-i-squared)
      (dk-have! '(= (* 0 0) -1) (lambda () (subst '(= 0 +i)) (ass)))
      (dk-have! '(NOT (= (* 0 0) -1)) (lambda () (arith)))
      (ai '(NOT (= (* 0 0) -1)))))
  (dk-cite! 'cc-mul-nonzero '(* 2 PI) +i)
  (wnc-cc! wnc-tpi)
  (wnc-cc! (list 'recip wnc-tpi)))
;;; the trace of the road P on [LO, HI] lies in CC \ {z} when z is off it
(define (wnc-trace-off! pg lo hi z)
  (let ((tr (list 'TRACE pg lo hi)))
    (dk-have! (list 'SUBSET tr (wnc-pz z))
      (lambda ()
        (let ((w (subset-by-element!)))
          (fact 'subset-mem-fwd tr 'CC w)
          (dk-have! (list 'NOT (list '= w z))
            (lambda () (di) (dk-have! (list 'IN z tr) (lambda () (subst (list '= z w)) (dk-ass!)))
                       (ai (dk-ctx-form (list 'NOT (list 'IN z tr))))))
          (wnc-pz-in! z w))))))
(define (wnc-road-basics! pg dg lo hi)
  (fact 'is-road-is-path pg dg lo hi)
  (fact 'is-path-in-fun pg lo hi)
  (dk-cite! 'trace-subset-cc pg lo hi)
  (dk-split! (dk-fact! 'is-path-endpoints pg lo hi))
  (dk-split-all!))

(sp (make-wff '(FORALL pgam1 (FORALL dgam1 (FORALL pgam2 (FORALL dgam2 (FORALL a (FORALL b (FORALL c
  (IMPLIES (IS-ROAD pgam1 dgam1 a b) (IMPLIES (IS-ROAD pgam2 dgam2 b c) (IMPLIES (= (pgam1 b) (pgam2 b))
    (FORALL wnz_ (IMPLIES (IN wnz_ CC)
      (IMPLIES (NOT (IN wnz_ (TRACE pgam1 a b))) (IMPLIES (NOT (IN wnz_ (TRACE pgam2 b c)))
        (= (WINDING (JUXTA pgam1 pgam2 a b c) (JUXTA dgam1 dgam2 a b c) a c wnz_)
           (+ (WINDING pgam1 dgam1 a b wnz_) (WINDING pgam2 dgam2 b c wnz_)))))))))))))))))))
(dk-peel!)
(let* ((z 'wnz_) (u (wnc-pz z)) (k (wnc-kern z))
       (l1 (list 'LINE-INT k 'pgam1 'dgam1 'a 'b))
       (l2 (list 'LINE-INT k 'pgam2 'dgam2 'b 'c))
       (l  (list 'LINE-INT k '(JUXTA pgam1 pgam2 a b c) '(JUXTA dgam1 dgam2 a b c) 'a 'c)))
  (wnc-road-basics! 'pgam1 'dgam1 'a 'b)
  (wnc-road-basics! 'pgam2 'dgam2 'b 'c)
  (wnc-pz-setup! z)
  (wnc-kern-setup! z)
  (wnc-trace-off! 'pgam1 'a 'b z)
  (wnc-trace-off! 'pgam2 'b 'c z)
  (dk-cite! 'line-int-juxta u k 'pgam1 'dgam1 'pgam2 'dgam2 'a 'b 'c)
  (dk-cite! 'line-int-in-cc u k 'pgam1 'dgam1 'a 'b)
  (dk-cite! 'line-int-in-cc u k 'pgam2 'dgam2 'b 'c)
  (wnc-tpi!)
  (mac 'WINDING)
  (subst (list '= l (list '+ l1 l2)))
  (let ((v (dk-name! (list 'recip wnc-tpi) 'CC)))
    (subst (list '= (list 'recip wnc-tpi) v))
    (crs)))
(qed 'winding-juxta)

(sp (make-wff "forall([pgam, dgam, a, b], is-road(pgam, dgam, a, b) implies
  forall([prgb_, prdb_], prgb_ in fun(ccint(a, b), cc) implies prdb_ in fun(ccint(a, b), cc) implies
    forall([pay_ in ccint(a, b)], prgb_(pay_) == pgam(a + b - pay_)) implies
    forall([pay_ in ccint(a, b)], prdb_(pay_) == -1 * dgam(a + b - pay_)) implies
    forall([wnz_ in cc], not(wnz_ in trace(pgam, a, b)) implies
      winding(prgb_, prdb_, a, b, wnz_) = -1 * winding(pgam, dgam, a, b, wnz_))))"))
(dk-peel!)
(let* ((z 'wnz_) (u (wnc-pz z)) (k (wnc-kern z))
       (l  (list 'LINE-INT k 'pgam 'dgam 'a 'b))
       (lo (list 'LINE-INT k 'prgb_ 'prdb_ 'a 'b)))
  (wnc-road-basics! 'pgam 'dgam 'a 'b)
  (wnc-pz-setup! z)
  (wnc-kern-setup! z)
  (wnc-trace-off! 'pgam 'a 'b z)
  (dk-apply! (dk-cite! 'line-int-opposite-road u k 'pgam 'dgam 'a 'b) 'prgb_ 'prdb_)
  (dk-cite! 'line-int-in-cc u k 'pgam 'dgam 'a 'b)
  (wnc-tpi!)
  (mac 'WINDING)
  (subst (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) '=) (equal? (cadr fm) lo))) "the opposite integral"))
  (let ((v (dk-name! (list 'recip wnc-tpi) 'CC)))
    (subst (list '= (list 'recip wnc-tpi) v))
    (crs)))
(qed 'winding-opposite)

