;;; winding-number-integer.scm -- THE WINDING NUMBER IS AN INTEGER (complex-analysis.pdf
;;; ch. 3, Proposition 3.27, first half), with the two pieces of road calculus it rests on.
;;; Agent CA-5 of week 3 of the October roadmap, 2026-10-04.
;;; Definitions: structure-library/winding-number.scm (WINDING, by the integral (73)).
;;;
;;; THE NOTES' PROOF.  For a closed path gamma on [a, b] and z off its trace put
;;; H(t) = int_a^t gamma'(s) / (gamma(s) - z) ds; then (gamma(t) - z) exp(-H(t)) has
;;; derivative 0, so it is constant; at t = b, since gamma(b) = gamma(a), exp(H(b)) = 1,
;;; and H(b) = 2 pi i ind(gamma, z) lies in 2 pi i ZZ.
;;;
;;; THE PROOF HERE has the same three steps, each a theorem:
;;;  (1) road-product-constant   two roads (P, dP), (Q, dQ) on [a, b] with
;;;                              dP Q + P dQ = 0 on [a, b] have P(b) Q(b) = P(a) Q(a).
;;;                              The product rule is applied COORDINATEWISE
;;;                              (Re(PQ) = Re P Re Q - Im P Im Q, `cc-re-mul'), with
;;;                              `has-deriv-at-product' on a window inside [a, b], off
;;;                              the union of the four exceptional sets; the constancy is
;;;                              `zero-deriv-off-countable-constant' (Dieudonne 8.5.1).
;;;  (2) line-int-primitive-road for f continuous on u, the road's trace in u: there is a
;;;                              road (H, h) on [a, b], h the line integral's integrand
;;;                              t |-> f(gamma(t)) gamma'(t), with
;;;                              LINE-INT(f, gamma, gamma', a, b) = H(b) - H(a).
;;;                              H is the notes' integral "as a function of its upper
;;;                              limit": its coordinates are primitives of the
;;;                              integrand's (`regulated-on-has-primitive').
;;;  (3) winding-number-integer  the closed road, z off the trace: WINDING = k, k in ZZ.
;;;                              The notes' (gamma - z) exp(-H) is replaced by
;;;                              exp(H) * 1/(gamma - z): both factors are images of
;;;                              roads under holomorphic maps (`road-holomorphic-image',
;;;                              exp on CC and w |-> 1/(w - z) on CC \ {z}), which is
;;;                              what (1) wants; no road difference or negation is needed.
;;;                              Then exp(H(b)) = exp(H(a)), exp(L) = 1 for the line
;;;                              integral L, and `cc-exp-one-iff'.
;;;
;;; STATEMENT CHECKS.  The roads are typed by IS-ROAD (which carries a < b, the reals a,
;;; b and the FUN typings).  (1) asks the derivative identity on the CLOSED interval, which
;;; is what (3) has; nothing is said about the endpoints' derivatives.  (2) is
;;; existential: H is not unique (a constant may be added), so no IOTA is formed.  (3)
;;; carries z in CC (SINGLETON z is defined only on a set) and not(z in TRACE), which
;;; puts the trace inside the integrand's domain CC \ {z}; closedness is pgam(b) = pgam(a)
;;; (a closed road has no name in the tree).  No strict `=' is asserted of a term that
;;; might not denote: LINE-INT's definedness is earned from the primitives
;;; (`line-int-value'), WINDING's from `winding-in-cc'.
;;;
;;; BINDERS: wzt_ (the hypothesis of (1)), the path-integral binders pat_, rgy_, hbz_,
;;; msy_, lft_ as in the laws cited.  No binder folds onto a class name or an accessor.
;;; Helper prefix wzi-.  NOTHING asserted; no definition here.
;;; LOAD WINDOW: lo = theorem-library/winding-number-laws (road-holomorphic-image,
;;; winding-integrand-holomorphic, cc-punctured-*), above cc-exp-kernel (cc-exp-one-iff),
;;; cc-exp, line-int-laws (line-int-value), regulated-algebra, regulated-has-primitive,
;;; zero-deriv-off-countable, has-deriv-at-more, interval-calculus-laws, cc-coords-laws,
;;; line-int-fundamental (cc-product-continuous-at).  hi: none.  Tactics: the early kit
;;; and dk-diff! / dk-holomorphic! (driver-kit).

;;; ======================================================================
;;; local helpers
;;; ======================================================================
(define wzi-cc '(CCINT a b))
(define wzi-scc (list 'SUBSPACE-MS 'RR-MS wzi-cc))
(define (wzi-plam body) (list 'VNB-LAMBDA 'pat_ wzi-cc body))
(define (wzi-crd proj f) (wzi-plam (list proj (list f 'pat_))))
(define (wzi-head g) (and (pair? g) (car g)))
(define (wzi-and! a b)
  (let ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! dk-ass!))))
    f))
;;; keep FS, then prop -- unless the keep already grounded the lane's leaf
(define (wzi-kp! . fs)
  (let ((node (proof-state-focus *ps*)))
    (apply keep fs)
    (if (not (sequent-node-grounded? node)) (prop))))
(define (wzi-pick-univ what . needles)
  (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL)
                             (let loop ((n needles))
                               (or (null? n) (and (dk-contains? fm (car n)) (loop (cdr n)))))))
           what))

;;; the interval and its subspace: the standing facts (a < b, a, b in RR in context)
(define (wzi-interval-setup!)
  (fact 'rr-is-metric-space)
  (fact 'rr-is-set)
  (dk-have! '(== (PTS RR-MS) RR) (lambda () (slot 'PTS) (qrfl)))
  (fact 'ccint-subset-rr 'a 'b)
  (fact 'subclass-of-set-is-set wzi-cc 'RR)
  (fact 'ooint-subset-ccint 'a 'b)
  (dk-have! (list 'SUBSET wzi-cc '(PTS RR-MS)) (lambda () (subst '(== (PTS RR-MS) RR)) (ass)))
  (fact 'subspace-is-metric-space 'RR-MS wzi-cc)
  (fact 'subspace-pts 'RR-MS wzi-cc)
  (fact 'rr-leq-reflexive 'a)
  (fact 'rr-leq-reflexive 'b)
  (fact 'rr-lt-implies-le 'a 'b)
  (for-each (lambda (z)
              (dk-have! (list 'IN z wzi-cc)
                (lambda () (mac 'ccint-membership) (dk-conj-close! dk-ass!))))
            '(a b)))

;;; y in [a, b] in context: f(y) in CC for each f of FS (members of FUN([a,b], CC)),
;;; with its two coordinates in RR
(define (wzi-cc-at! fs y)
  (for-each (lambda (f)
              (fact 'fun-apply-type-c f wzi-cc 'CC y)
              (fact 'real-part-in-rr (list f y))
              (fact 'imag-part-in-rr (list f y)))
            fs))

;;; ======================================================================
;;; (1) ROAD-PRODUCT-CONSTANT
;;; ======================================================================
(define wzi-r1 (wzi-plam '(real-part (* (pgam pat_) (qgam pat_)))))
(define wzi-i1 (wzi-plam '(imag-part (* (pgam pat_) (qgam pat_)))))

;;; at y in [a, b]: the four road values typed, the product typed with its coordinates
(define (wzi-pq-at! y)
  (wzi-cc-at! '(pgam qgam dgam dqgam) y)
  (let ((pq (list '* (list 'pgam y) (list 'qgam y))))
    (wzi-and! (list 'IN (list 'pgam y) 'CC) (list 'IN (list 'qgam y) 'CC))
    (fact 'cc-mul-closed (list 'pgam y) (list 'qgam y))
    (fact 'real-part-in-rr pq)
    (fact 'imag-part-in-rr pq)))

(define (wzi-pq-type! claim)
  (dk-have! claim
    (lambda ()
      (dk-lam-type! (lambda () (let ((y (dk-di-var!))) (wzi-pq-at! y)
                                 (if (dk--redex? (dk-goal)) (dk-lam-b!)) (ass))) ass))))

(sp (make-wff '(FORALL pgam (FORALL dgam (FORALL qgam (FORALL dqgam (FORALL a (FORALL b
  (IMPLIES (IS-ROAD pgam dgam a b) (IMPLIES (IS-ROAD qgam dqgam a b)
    (IMPLIES (FORALL wzt_ (IMPLIES (IN wzt_ (CCINT a b))
               (= (+ (* (dgam wzt_) (qgam wzt_)) (* (pgam wzt_) (dqgam wzt_))) 0)))
      (= (* (pgam b) (qgam b)) (* (pgam a) (qgam a))))))))))))))
(dk-peel!)
(define wzi-hyp (wzi-pick-univ "the derivative identity" 'wzt_ 'dqgam))
(for-each (lambda (pg dg)
            (fact 'is-road-is-path pg dg 'a 'b)
            (fact 'is-path-in-fun pg 'a 'b)
            (fact 'is-road-dgam-in-fun pg dg 'a 'b)
            (fact 'is-road-re-antiderivative pg dg 'a 'b)
            (fact 'is-road-im-antiderivative pg dg 'a 'b))
          '(pgam qgam) '(dgam dqgam))
(dk-split! (dk-fact! 'is-path-endpoints 'pgam 'a 'b))
(dk-split-all!)
(define wzi-pcont (dk-fact! 'is-path-continuous 'pgam 'a 'b))
(define wzi-qcont (dk-fact! 'is-path-continuous 'qgam 'a 'b))
(wzi-interval-setup!)
(wzi-pq-at! 'a)
(wzi-pq-at! 'b)
(wzi-pq-type! (list 'IN wzi-r1 (list 'FUN wzi-cc 'RR)))
(wzi-pq-type! (list 'IN wzi-i1 (list 'FUN wzi-cc 'RR)))

;;; ---- continuity of the two coordinates of PQ on [a, b]
(dk-have! (list 'IN wzi-r1 (list 'FUN (list 'PTS wzi-scc) 'RR))
  (lambda () (subst (list '== (list 'PTS wzi-scc) wzi-cc)) (ass)))
(dk-have! (list 'IN wzi-i1 (list 'FUN (list 'PTS wzi-scc) 'RR))
  (lambda () (subst (list '== (list 'PTS wzi-scc) wzi-cc)) (ass)))
(define (wzi-in-cc-of-pts! z)
  (dk-have! (list 'IN z wzi-cc)
    (lambda () (subst (list '= wzi-cc (list 'PTS wzi-scc))) (ass))))
(define (wzi-pq-cont! y)
  (wzi-pq-at! y)
  (dk-have! (list 'IN y (list 'PTS wzi-scc))
    (lambda () (subst (list '== (list 'PTS wzi-scc) wzi-cc)) (ass)))
  (dk-apply! wzi-pcont y)
  (dk-apply! wzi-qcont y)
  (let* ((r (dk-fact! 'cc-product-continuous-at wzi-scc 'pgam 'qgam y))
         (c (list-ref r 3)))
    (if (not (eq? (wzi-head r) 'IS-CONTINUOUS-AT))
        (error "wzi-pq-cont!: expected the product's continuity" (expression->string r)))
    (dk-have! (list 'IN c (list 'FUN (list 'PTS wzi-scc) 'CC))
      (lambda ()
        (fact 'ms-pts-is-set wzi-scc)
        (dk-lam-type! (lambda () (let ((z (dk-di-var!)))
                                   (wzi-in-cc-of-pts! z)
                                   (wzi-pq-at! z)
                                   (if (dk--redex? (dk-goal)) (dk-lam-b!))
                                   (ass))) ass)))
    (for-each
     (lambda (proj fl)
       (dk-have! (list 'FORALL 'u_ (list 'IMPLIES (list 'IN 'u_ (list 'PTS wzi-scc))
                   (list '= (list proj (list c 'u_)) (list fl 'u_))))
         (lambda ()
           (let ((z (dk-di-var!)))
             (wzi-in-cc-of-pts! z)
             (wzi-pq-at! z)
             (dk-lam-b!)
             (rfl)))))
     '(real-part imag-part) (list wzi-r1 wzi-i1))
    (let ((iff (dk-fact! 'cc-continuous-at-iff-coords wzi-scc c wzi-r1 wzi-i1 y)))
      (if (not (eq? (wzi-head iff) 'IFF))
          (error "wzi-pq-cont!: expected the coordinate iff" (expression->string iff)))
      (cons iff r))))
(define wzi-both-cont
  (list 'FORALL 'icp_ (list 'IMPLIES (list 'IN 'icp_ wzi-cc)
    (list 'AND (list 'IS-CONTINUOUS-AT wzi-scc 'RR-MS wzi-r1 'icp_)
               (list 'IS-CONTINUOUS-AT wzi-scc 'RR-MS wzi-i1 'icp_)))))
(dk-have! wzi-both-cont
  (lambda ()
    (let* ((y (dk-di-var!))
           (ir (wzi-pq-cont! y)))
      (keep (car ir) (cdr ir))
      (prop))))
(define (wzi-cont-on! fl)
  (dk-have! (list 'IS-CONTINUOUS-ON fl wzi-cc)
    (lambda ()
      (mac 'IS-CONTINUOUS-ON)
      (dk-conj-close!
       (lambda ()
         (if (not (eq? (wzi-head (dk-goal)) 'FORALL))
             (dk-ass!)
             (let ((y (dk-di-var!)))
               (dk-split-all! (list (dk-apply! (dk-ctx-form wzi-both-cont) y)))
               (dk-ass!))))))))
(wzi-cont-on! wzi-r1)
(wzi-cont-on! wzi-i1)

;;; ---- the exceptional set: the union of the four of the two roads
(define (wzi-exc! pf df proj)
  (let ((s (dk-skolem! (dk-fact! 'primitive-exceptional-set (wzi-crd proj pf) (wzi-crd proj df) 'a 'b))))
    (dk-split-all!)
    (cons s (wzi-pick-univ "a coordinate derivative universal" 'HAS-DERIV-AT s))))
(define wzi-e1 (wzi-exc! 'pgam 'dgam 'real-part))
(define wzi-e2 (wzi-exc! 'pgam 'dgam 'imag-part))
(define wzi-e3 (wzi-exc! 'qgam 'dqgam 'real-part))
(define wzi-e4 (wzi-exc! 'qgam 'dqgam 'imag-part))
(define wzi-u12 (list 'UNION (car wzi-e1) (car wzi-e2)))
(define wzi-u34 (list 'UNION (car wzi-e3) (car wzi-e4)))
(define wzi-un (list 'UNION wzi-u12 wzi-u34))
(fact 'countable-union-2 (car wzi-e1) (car wzi-e2))
(fact 'countable-union-2 (car wzi-e3) (car wzi-e4))
(fact 'countable-union-2 wzi-u12 wzi-u34)
(define (wzi-union-sub! s1 s2)
  (dk-have! (list 'SUBSET (list 'UNION s1 s2) wzi-cc)
    (lambda ()
      (let* ((w  (subset-by-element!))
             (um (dk-fact! 'union-membership s1 s2 w)))
        (fact 'subset-mem-fwd s1 wzi-cc w)
        (fact 'subset-mem-fwd s2 wzi-cc w)
        (keep um (list 'IN w (list 'UNION s1 s2))
              (list 'IMPLIES (list 'IN w s1) (list 'IN w wzi-cc))
              (list 'IMPLIES (list 'IN w s2) (list 'IN w wzi-cc)))
        (prop)))))
(wzi-union-sub! (car wzi-e1) (car wzi-e2))
(wzi-union-sub! (car wzi-e3) (car wzi-e4))
(wzi-union-sub! wzi-u12 wzi-u34)

;;; ---- THE DERIVATIVE of each coordinate of PQ is 0 off the union
(fact 'cc-zero-in)
(fact 'rr-zero-in)
(for-each
 (lambda (proj)
   (dk-have! (list '= (list proj 0) 0)
     (lambda ()
       (dk-have! '(= 0 (+ 0 (* 0 +i))) (lambda () (crs)))
       (dk-split-all! (list (dk-cite! 'cc-re-im-of 0 0 0)))
       (dk-ass!))))
 '(real-part imag-part))

;;; at the eigenvariable tv with the window nb = OOINT(tv - rad, tv + rad) inside [a, b]:
;;; restrict(h, nb) typed, for h a member of FUN([a, b], RR)
(define (wzi-restrict! h nb)
  (fact 'restrict-in-fun h wzi-cc 'RR nb))
;;; the product h of the coordinate lambdas F (of pgam) and G (of qgam), typed, with its
;;; derivative at tv landed in reduced form; F, G are (lambda . value-at-tv)
(define (wzi-prod! tv rad nb f g)
  (let* ((pf (car (cadddr (car f))))
         (pg (car (cadddr (car g))))
         (h  (wzi-plam (list '* (list pf '(pgam pat_)) (list pg '(qgam pat_)))))
         (fv (list pf (list 'pgam tv)))
         (gv (list pg (list 'qgam tv))))
    (dk-have! (list 'IN h (list 'FUN wzi-cc 'RR))
      (lambda ()
        (dk-lam-type! (lambda () (let ((y (dk-di-var!)))
                                   (wzi-pq-at! y)
                                   (if (dk--redex? (dk-goal)) (dk-lam-b!))
                                   (fact 'rr-mul-in-rr (list pf (list 'pgam y)) (list pg (list 'qgam y)))
                                   (dk-ass!))) ass)))
    (wzi-restrict! h nb)
    (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ nb)
                (list '== (list h 'hbx_) (list '* (list (car f) 'hbx_) (list (car g) 'hbx_)))))
      (lambda ()
        (let ((w (dk-di-var!)))
          (fact 'subset-mem-fwd nb wzi-cc w)
          (wzi-pq-at! w)
          (dk-lam-b!)
          (qrfl))))
    (let* ((r  (dk-fact! 'has-deriv-at-product rad (car f) (car g) h tv (cdr f) (cdr g)))
           (val (cadddr r))
           (nv (list '+ (list '* (cdr f) gv) (list '* (cdr g) fv))))
      (if (not (eq? (wzi-head r) 'HAS-DERIV-AT))
          (error "wzi-prod!: the product rule did not detach" (expression->string r)))
      (dk-have! (list '= (list (car g) tv) gv) (lambda () (dk-lam-b!) (rfl)))
      (dk-have! (list '= (list (car f) tv) fv) (lambda () (dk-lam-b!) (rfl)))
      (dk-have! (list 'HAS-DERIV-AT h tv nv)
        (lambda ()
          (dk-have! (list '= nv val)
            (lambda ()
              (subst (list '= gv (list (car g) tv)))
              (subst (list '= fv (list (car f) tv)))
              (rfl)))
          (subst (list '= nv val))
          (dk-ass!)))
      (cons h nv))))

;;; the coordinate PROJ of PQ as h1 -/+ h2 on the window, its derivative landed;
;;; returns the value
(define (wzi-coord-deriv! tv rad nb proj fl h1 h2 law op lawname)
  (wzi-restrict! fl nb)
  (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ nb)
              (list '== (list fl 'hbx_) (list op (list (car h1) 'hbx_) (list (car h2) 'hbx_)))))
    (lambda ()
      (let ((w (dk-di-var!)))
        (fact 'subset-mem-fwd nb wzi-cc w)
        (wzi-pq-at! w)
        (dk-lam-b!)
        (let ((eq (dk-cite! lawname (list 'pgam w) (list 'qgam w))))
          (subst eq)
          (qrfl)))))
  (let ((r (if (eq? op '-)
               (dk-fact! 'has-deriv-at-difference rad (car h1) (car h2) fl tv (cdr h1) (cdr h2))
               (dk-fact! 'has-deriv-at-sum rad (car h1) (car h2) fl tv (cdr h1) (cdr h2)))))
    (if (not (eq? (wzi-head r) 'HAS-DERIV-AT))
        (error "wzi-coord-deriv!: the sum/difference rule did not detach" (expression->string r)))
    (cadddr r)))

(define wzi-both-deriv
  (list 'FORALL 'lft_ (list 'IMPLIES '(IN lft_ (OOINT a b))
    (list 'IMPLIES (list 'NOT (list 'IN 'lft_ wzi-un))
      (list 'AND (list 'HAS-DERIV-AT wzi-r1 'lft_ 0)
                 (list 'HAS-DERIV-AT wzi-i1 'lft_ 0))))))
(dk-have! wzi-both-deriv
  (lambda ()
    (dk-peel!)
    (let* ((tv (cadr (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'IN)
                                                 (equal? (caddr fm) '(OOINT a b))))
                              "the point of the open interval")))
           (u1 (dk-fact! 'union-membership wzi-u12 wzi-u34 tv))
           (u2 (dk-fact! 'union-membership (car wzi-e1) (car wzi-e2) tv))
           (u3 (dk-fact! 'union-membership (car wzi-e3) (car wzi-e4) tv))
           (nots (map (lambda (e) (list 'NOT (list 'IN tv (car e)))) (list wzi-e1 wzi-e2 wzi-e3 wzi-e4))))
      (for-each (lambda (nf)
                  (dk-have! nf (lambda () (wzi-kp! u1 u2 u3 (list 'NOT (list 'IN tv wzi-un))))))
                nots)
      (fact 'subset-mem-fwd '(OOINT a b) wzi-cc tv)
      (wzi-pq-at! tv)
      (let* ((cds (map (lambda (e pf df proj)
                         (let* ((gl (wzi-crd proj pf)) (dl (wzi-crd proj df)) (dt (list df tv)))
                           (fact 'fun-apply-type-c dl wzi-cc 'RR tv)
                           (dk-apply! (cdr e) tv)
                           (dk-have! (list '= (list dl tv) (list proj dt)) (lambda () (dk-lam-b!) (rfl)))
                           (dk-have! (list 'HAS-DERIV-AT gl tv (list proj dt))
                             (lambda () (subst (list '= (list proj dt) (list dl tv))) (dk-ass!)))
                           (cons gl (list proj dt))))
                       (list wzi-e1 wzi-e2 wzi-e3 wzi-e4)
                       '(pgam pgam qgam qgam) '(dgam dgam dqgam dqgam)
                       '(real-part imag-part real-part imag-part)))
             (pr (list-ref cds 0)) (pim (list-ref cds 1))
             (qr (list-ref cds 2)) (qim (list-ref cds 3))
             (rad (dk-skolem! (dk-fact! 'ooint-inner-radius 'a 'b tv)))
             (nb  (list 'OOINT (list '- tv rad) (list '+ tv rad)))
             (x   (list 'dgam tv)) (y (list 'qgam tv))
             (p   (list 'pgam tv)) (dq (list 'dqgam tv))
             (xy  (list '* x y)) (pdq (list '* p dq))
             (ex  (list '+ xy pdq)))
        (dk-split-all!)
        (let* ((h1 (wzi-prod! tv rad nb pr qr))
               (h2 (wzi-prod! tv rad nb pim qim))
               (h3 (wzi-prod! tv rad nb pr qim))
               (h4 (wzi-prod! tv rad nb pim qr))
               (vr (wzi-coord-deriv! tv rad nb 'real-part wzi-r1 h1 h2 'cc-re-mul '- 'cc-re-mul))
               (vi (wzi-coord-deriv! tv rad nb 'imag-part wzi-i1 h3 h4 'cc-im-mul '+ 'cc-im-mul)))
          ;; the identity at tv, and its two coordinates
          (dk-apply! wzi-hyp tv)
          (wzi-and! (list 'IN x 'CC) (list 'IN y 'CC))
          (wzi-and! (list 'IN p 'CC) (list 'IN dq 'CC))
          (fact 'cc-mul-closed x y)
          (fact 'cc-mul-closed p dq)
          (for-each
           (lambda (proj addlaw mullaw v)
             (let* ((ea (dk-cite! addlaw xy pdq))
                    (e1 (dk-cite! mullaw x y))
                    (e2 (dk-cite! mullaw p dq))
                    (expd (list '+ (caddr e1) (caddr e2))))
               (dk-have! (list '= (list proj ex) 0)
                 (lambda () (subst (list '= ex 0)) (dk-ass!)))
               (dk-have! (list '= v 0)
                 (lambda ()
                   (dk-real! expd)
                   (dk-have! (list '= 0 expd)
                     (lambda ()
                       (subst (list '= 0 (list proj ex)))
                       (subst ea)
                       (subst e1)
                       (subst e2)
                       (rfl)))
                   (subst (list '= 0 expd))
                   (crs)))))
           '(real-part imag-part) '(cc-re-add cc-im-add) '(cc-re-mul cc-im-mul) (list vr vi))
          (dk-have! (list 'HAS-DERIV-AT wzi-r1 tv 0)
            (lambda () (subst (list '= 0 vr)) (dk-ass!)))
          (dk-have! (list 'HAS-DERIV-AT wzi-i1 tv 0)
            (lambda () (subst (list '= 0 vi)) (dk-ass!)))
          (dk-conj-close! dk-ass!))))))
(define (wzi-deriv-univ! fl)
  (dk-have! (list 'FORALL 'lft_ (list 'IMPLIES '(IN lft_ (OOINT a b))
              (list 'IMPLIES (list 'NOT (list 'IN 'lft_ wzi-un))
                    (list 'HAS-DERIV-AT fl 'lft_ 0))))
    (lambda ()
      (dk-peel!)
      (let ((tv (caddr (dk-goal))))
        (dk-split-all! (list (dk-apply! (dk-ctx-form wzi-both-deriv) tv)))
        (dk-ass!)))))
(wzi-deriv-univ! wzi-r1)
(wzi-deriv-univ! wzi-i1)

;;; ---- each coordinate of PQ takes the same value at b and at a
(define (wzi-const! fl proj)
  (let* ((u  (dk-fact! 'zero-deriv-off-countable-constant 'a 'b fl wzi-un))
         (e  (dk-apply! u 'b 'a))
         (pb (list '* '(pgam b) '(qgam b)))
         (pa (list '* '(pgam a) '(qgam a))))
    (if (not (eq? (wzi-head e) '=))
        (error "wzi-const!: the constancy did not detach" (expression->string e)))
    (dk-have! (list '= (list proj pb) (list proj pa))
      (lambda ()
        (dk-have! (list '= (list fl 'b) (list proj pb)) (lambda () (dk-lam-b!) (rfl)))
        (dk-have! (list '= (list fl 'a) (list proj pa)) (lambda () (dk-lam-b!) (rfl)))
        (subst (list '= (list proj pb) (list fl 'b)))
        (subst (list '= (list proj pa) (list fl 'a)))
        (dk-ass!)))))
(wzi-const! wzi-r1 'real-part)
(wzi-const! wzi-i1 'imag-part)
(let* ((pb '(* (pgam b) (qgam b)))
       (pa '(* (pgam a) (qgam a)))
       (db (dk-cite! 'cc-re-im-decompose pb))
       (da (dk-cite! 'cc-re-im-decompose pa)))
  (dk-have! (list '= (caddr db) (caddr da))
    (lambda ()
      (subst (list '= (list 'real-part pb) (list 'real-part pa)))
      (subst (list '= (list 'imag-part pb) (list 'imag-part pa)))
      (rfl)))
  (subst db)
  (subst da)
  (dk-ass!))
(qed 'road-product-constant)

;;; ======================================================================
;;; (2) LINE-INT-PRIMITIVE-ROAD
;;; ======================================================================
(define wzi-phi (wzi-plam '(* (f (pgam pat_)) (dgam pat_))))
(define wzi-fir (wzi-plam '(real-part (* (f (pgam pat_)) (dgam pat_)))))
(define wzi-fii (wzi-plam '(imag-part (* (f (pgam pat_)) (dgam pat_)))))
(define (wzi-cont-hyp u f)
  (list 'FORALL 'rgy_ (list 'IMPLIES (list 'IN 'rgy_ u)
    (list 'IS-CONTINUOUS-AT (list 'SUBSPACE-MS '(NF-METRIC-SPACE CC-NORMED-FIELD) u)
          '(NF-METRIC-SPACE CC-NORMED-FIELD) f 'rgy_))))

;;; y in [a, b]: gamma(y) in u, the integrand's value and its coordinates typed
(define wzi-pgu #f)
(define (wzi-fpt! y)
  (fact 'fun-apply-type-c 'pgam wzi-cc 'CC y)
  (if (not (dk-asm? (list 'IN (list 'pgam y) 'u))) (dk-apply! wzi-pgu y))
  (fact 'fun-apply-type-c 'f 'u 'CC (list 'pgam y))
  (fact 'fun-apply-type-c 'dgam wzi-cc 'CC y)
  (wzi-and! (list 'IN (list 'f (list 'pgam y)) 'CC) (list 'IN (list 'dgam y) 'CC))
  (let ((v (list '* (list 'f (list 'pgam y)) (list 'dgam y))))
    (fact 'cc-mul-closed (list 'f (list 'pgam y)) (list 'dgam y))
    (fact 'real-part-in-rr v)
    (fact 'imag-part-in-rr v)))

(sp (make-wff (list 'FORALL 'u (list 'FORALL 'f (list 'FORALL 'pgam (list 'FORALL 'dgam
  (list 'FORALL 'a (list 'FORALL 'b
  (list 'IMPLIES '(SUBSET u CC) (list 'IMPLIES '(IN f (FUN u CC)) (list 'IMPLIES (wzi-cont-hyp 'u 'f)
  (list 'IMPLIES '(IS-ROAD pgam dgam a b) (list 'IMPLIES '(SUBSET (TRACE pgam a b) u)
    (list 'FORSOME 'wzh_ (list 'AND (list 'IS-ROAD 'wzh_ wzi-phi 'a 'b)
                                     '(= (LINE-INT f pgam dgam a b) (- (wzh_ b) (wzh_ a))))))))))))))))))
(dk-peel!)
(fact 'is-road-is-path 'pgam 'dgam 'a 'b)
(fact 'is-path-in-fun 'pgam 'a 'b)
(fact 'is-road-dgam-in-fun 'pgam 'dgam 'a 'b)
(dk-split! (dk-fact! 'is-path-endpoints 'pgam 'a 'b))
(dk-split-all!)
(wzi-interval-setup!)
(dk-have! (list 'FORALL 'msy_ (list 'IMPLIES (list 'IN 'msy_ wzi-cc) '(IN (pgam msy_) u)))
  (lambda ()
    (let ((y (dk-di-var!)))
      (fact 'trace-value-in 'pgam 'a 'b y)
      (fact 'subset-mem-fwd '(TRACE pgam a b) 'u (list 'pgam y))
      (dk-ass!))))
(set! wzi-pgu (wzi-pick-univ "the trace lies in u" 'msy_ '(pgam msy_)))
(dk-split-all! (list (dk-cite! 'road-integrand-regulated 'u 'f 'pgam 'dgam 'a 'b)))
(define wzi-g1 (dk-skolem! (dk-fact! 'regulated-on-has-primitive 'a 'b wzi-fir)))
(define wzi-g2 (dk-skolem! (dk-fact! 'regulated-on-has-primitive 'a 'b wzi-fii)))
(define wzi-lv (dk-cite! 'line-int-value 'f 'pgam 'dgam 'a 'b wzi-g1 wzi-g2))
(fact 'primitive-in-fun wzi-g1 wzi-fir 'a 'b)
(fact 'primitive-in-fun wzi-g2 wzi-fii 'a 'b)
(fact 'primitive-continuous wzi-g1 wzi-fir 'a 'b)
(fact 'primitive-continuous wzi-g2 wzi-fii 'a 'b)
(fact 'primitive-integrand-in-fun wzi-g1 wzi-fir 'a 'b)
(fact 'primitive-integrand-in-fun wzi-g2 wzi-fii 'a 'b)
(fact 'cc-i-in)
(define wzi-hval (lambda (y) (list '+ (list wzi-g1 y) (list '* (list wzi-g2 y) '+i))))
(define wzi-h (wzi-plam (wzi-hval 'pat_)))
;;; y in [a, b]: H(y) typed, with its coordinates
(define (wzi-hpt! y)
  (let ((g1 (list wzi-g1 y)) (g2 (list wzi-g2 y)))
    (fact 'fun-apply-type-c wzi-g1 wzi-cc 'RR y)
    (fact 'fun-apply-type-c wzi-g2 wzi-cc 'RR y)
    (fact 'rr-subset-cc g1)
    (fact 'rr-subset-cc g2)
    (wzi-and! (list 'IN g2 'CC) '(IN +i CC))
    (fact 'cc-mul-closed g2 '+i)
    (wzi-and! (list 'IN g1 'CC) (list 'IN (list '* g2 '+i) 'CC))
    (fact 'cc-add-closed g1 (list '* g2 '+i))))
(wzi-hpt! 'a)
(wzi-hpt! 'b)
(dk-have! (list 'IN wzi-h (list 'FUN wzi-cc 'CC))
  (lambda () (dk-lam-type! (lambda () (let ((y (dk-di-var!))) (wzi-hpt! y)
                                        (if (dk--redex? (dk-goal)) (dk-lam-b!)) (dk-ass!))) ass)))
(for-each
  (lambda (proj gl)
    (dk-have! (list 'FORALL 'pay_ (list 'IMPLIES (list 'IN 'pay_ wzi-cc)
                (list '= (list proj (list wzi-h 'pay_)) (list gl 'pay_))))
      (lambda ()
        (let ((y (dk-di-var!)))
          (wzi-hpt! y)
          (dk-lam-b!)
          (dk-have! (list '= (wzi-hval y) (wzi-hval y)) (lambda () (rfl)))
          (dk-split-all! (list (dk-cite! 'cc-re-im-of (wzi-hval y) (list wzi-g1 y) (list wzi-g2 y))))
          (dk-ass!)))))
  '(real-part imag-part) (list wzi-g1 wzi-g2))
(dk-cite! 'is-path-of-coords 'a 'b wzi-h wzi-g1 wzi-g2)
;; the derivative: the integrand, a function on [a, b], regulated coordinatewise
(dk-cite! 'line-int-integrand-in-fun 'a 'b 'pgam 'dgam 'f 'u)
(define wzi-pr (wzi-plam (list 'real-part (list wzi-phi 'pat_))))
(define wzi-pim (wzi-plam (list 'imag-part (list wzi-phi 'pat_))))
(define wzi-hr (wzi-plam (list 'real-part (list wzi-h 'pat_))))
(define wzi-hi (wzi-plam (list 'imag-part (list wzi-h 'pat_))))
(for-each
  (lambda (il gl)
    (dk-have! (list 'IN il (list 'FUN wzi-cc 'RR))
      (lambda () (dk-lam-type! (lambda () (let ((y (dk-di-var!))) (wzi-fpt! y)
                                            (if (dk--redex? (dk-goal)) (dk-lam-b!)) (dk-ass!))) ass)))
    (dk-have! (list 'FORALL 'rgz_ (list 'IMPLIES (list 'IN 'rgz_ wzi-cc) (list '== (list il 'rgz_) (list gl 'rgz_))))
      (lambda () (let ((v (dk-di-var!))) (wzi-fpt! v) (if (not (dk-lam-b!)) (qrfl)))))
    (dk-cite! 'regulated-on-congruence il gl 'a 'b)
    (dk-fun-ext! il gl wzi-cc 'RR #f #f
                 (lambda (v) (wzi-fpt! v) (if (not (dk-lam-b!)) (rfl)))))
  (list wzi-pr wzi-pim) (list wzi-fir wzi-fii))
(for-each
  (lambda (hl gl)
    (dk-have! (list 'IN hl (list 'FUN wzi-cc 'RR))
      (lambda () (dk-lam-type! (lambda () (let ((y (dk-di-var!))) (wzi-hpt! y)
                                            (if (dk--redex? (dk-goal)) (dk-lam-b!))
                                            (fact 'real-part-in-rr (wzi-hval y))
                                            (fact 'imag-part-in-rr (wzi-hval y))
                                            (dk-ass!))) ass)))
    (dk-fun-ext! hl gl wzi-cc 'RR #f #f
                 (lambda (v) (wzi-hpt! v)
                   (dk-lam-b!)
                   (dk-have! (list '= (wzi-hval v) (wzi-hval v)) (lambda () (rfl)))
                   (dk-split-all! (list (dk-cite! 'cc-re-im-of (wzi-hval v) (list wzi-g1 v) (list wzi-g2 v))))
                   (dk-ass!))))
  (list wzi-hr wzi-hi) (list wzi-g1 wzi-g2))
(for-each
  (lambda (hl il gl fl)
    (dk-have! (list 'IS-PRIMITIVE hl il 'a 'b)
      (lambda () (subst (list '= hl gl)) (subst (list '= il fl)) (dk-ass!))))
  (list wzi-hr wzi-hi) (list wzi-pr wzi-pim) (list wzi-g1 wzi-g2) (list wzi-fir wzi-fii))
(define wzi-road (list 'IS-ROAD wzi-h wzi-phi 'a 'b))
(dk-have! wzi-road
  (lambda () (mac 'IS-ROAD) (dk-conj-close! dk-ass!)))
(define wzi-leq (list '= '(LINE-INT f pgam dgam a b) (list '- (list wzi-h 'b) (list wzi-h 'a))))
(dk-have! wzi-leq
  (lambda ()
    (for-each (lambda (z)
                (dk-have! (list '= (list wzi-h z) (wzi-hval z)) (lambda () (dk-lam-b!) (rfl)))
                (subst (list '= (list wzi-h z) (wzi-hval z))))
              '(b a))
    (subst wzi-lv)
    (crs)))
(ew wzi-h)
(dk-conj-close! dk-ass!)
(qed 'line-int-primitive-road)

;;; ======================================================================
;;; (3) WINDING-NUMBER-INTEGER
;;; ======================================================================
;;; copies of winding-number-laws.scm's wnd- typers (that file is not ours)
(define (wzi-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (wzi-rr! t)
  (let ((typ (list 'IN t 'RR)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'rr-zero-in) typ)
          ((eqv? t 1) (fact 'rr-one-in) typ)
          ((eq? t 'PI) (dk-split-all! (list (dk-cite! 'pi-pos))) typ)
          ((number? t) (dk-have! typ (lambda () (arith))) typ)
          ((wzi-op? t '* 3) (wzi-rr! (cadr t)) (wzi-rr! (caddr t)) (fact 'rr-mul-in-rr (cadr t) (caddr t)) typ)
          (#t (dk-real! t) typ))))
(define (wzi-cc! t)
  (let ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((eqv? t +i) (fact 'cc-i-in) typ)
          ((or (and (number? t) (real? t)) (eq? t 'PI) (dk-asm? (list 'IN t 'RR)))
           (wzi-rr! t) (fact 'rr-subset-cc t) typ)
          ((wzi-op? t '- 3) (wzi-cc! (cadr t)) (wzi-cc! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((wzi-op? t '- 2) (wzi-cc! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((wzi-op? t '+ 3) (wzi-cc! (cadr t)) (wzi-cc! (caddr t))
           (wzi-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((wzi-op? t '* 3) (wzi-cc! (cadr t)) (wzi-cc! (caddr t))
           (wzi-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((wzi-op? t 'CC-EXP 2) (wzi-cc! (cadr t))
           (dk-split-all! (list (dk-cite! 'cc-exp-converges (cadr t)))) typ)
          ((wzi-op? t 'recip 2) (wzi-cc! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (error "wzi-cc!: land the non-vanishing first" (expression->string (cadr t))))
           (wzi-and! (list 'IN (cadr t) 'CC) (list 'NOT (list '= (cadr t) 0)))
           (fact 'cc-recip-closed (cadr t)) typ)
          (#t (error "wzi-cc!: cannot type" (expression->string t))))))
(define (wzi-pz z) (list 'DIFFERENCE 'CC (list 'SINGLETON z)))
(define (wzi-kern z) (list 'VNB-LAMBDA 'wnw_ (wzi-pz z) (list 'recip (list '- 'wnw_ z))))
(define (wzi-sub-nz! y z)
  (let ((nz (list 'NOT (list '= (list '- y z) 0))))
    (dk-have! nz
      (lambda ()
        (di)
        (dk-cite! 'cc-sub-zero-eq y z)
        (ai (dk-ctx-form (list 'NOT (list '= y z))))))
    nz))
(define (wzi-pz-open! z y)
  (let ((iff (dk-cite! 'cc-punctured-membership z y)))
    (dk-have! (list 'IN y 'CC) (lambda () (wzi-kp! iff (list 'IN y (wzi-pz z)))))
    (dk-have! (list 'NOT (list '= y z)) (lambda () (wzi-kp! iff (list 'IN y (wzi-pz z)))))
    (wzi-sub-nz! y z)))
(define (wzi-pz-in! z y)
  (let ((iff (dk-cite! 'cc-punctured-membership z y)))
    (dk-have! (list 'IN y (wzi-pz z))
      (lambda () (wzi-kp! iff (list 'IN y 'CC) (list 'NOT (list '= y z)))))))
(define wzi-tpi '(* (* 2 PI) +i))
(define (wzi-tpi!)
  (wzi-rr! '(* 2 PI))
  (dk-have! '(< 0 (* 2 PI)) (lambda () (dk-ineq! '(< 0 PI))))
  (dk-cite! 'rr-pos-ne-zero '(* 2 PI))
  (wzi-cc! '(* 2 PI))
  (fact 'cc-i-in)
  (dk-have! '(NOT (= +i 0))
    (lambda ()
      (di)
      (fact 'cc-i-squared)
      (dk-have! '(= (* 0 0) -1) (lambda () (subst '(= 0 +i)) (ass)))
      (dk-have! '(NOT (= (* 0 0) -1)) (lambda () (arith)))
      (ai '(NOT (= (* 0 0) -1)))))
  (dk-cite! 'cc-mul-nonzero '(* 2 PI) +i)
  (wzi-cc! wzi-tpi))
;;; x in CC, x /= 0: name v = recip(x), land x * v = 1; return v
(define (wzi-inv! x)
  (wzi-and! (list 'IN x 'CC) (list 'NOT (list '= x 0)))
  (fact 'cc-recip-closed x)
  (dk-cite! 'cc-recip-inverse x)
  (let ((v (dk-name! (list 'recip x) 'CC)))
    (dk-have! (list '= (list '* x v) 1)
      (lambda () (subst (list '= v (list 'recip x))) (dk-ass!)))
    v))

(define wzi-nfm '(NF-METRIC-SPACE CC-NORMED-FIELD))
(define wzi-ee '(VNB-LAMBDA cexy_ CC (CC-EXP cexy_)))

(sp (make-wff '(FORALL pgam (FORALL dgam (FORALL a (FORALL b (IMPLIES (IS-ROAD pgam dgam a b)
  (IMPLIES (= (pgam b) (pgam a))
    (FORALL wnz_ (IMPLIES (IN wnz_ CC) (IMPLIES (NOT (IN wnz_ (TRACE pgam a b)))
      (FORSOME wzk_ (AND (IN wzk_ ZZ) (= (WINDING pgam dgam a b wnz_) wzk_))))))))))))))
(dk-peel!)
(define wzi-z 'wnz_)
(define wzi-u (wzi-pz wzi-z))
(define wzi-k (wzi-kern wzi-z))
(fact 'is-road-is-path 'pgam 'dgam 'a 'b)
(fact 'is-path-in-fun 'pgam 'a 'b)
(fact 'is-road-dgam-in-fun 'pgam 'dgam 'a 'b)
(dk-split! (dk-fact! 'is-path-endpoints 'pgam 'a 'b))
(dk-split-all!)
(wzi-interval-setup!)
;; the kernel on CC \ {z}
(dk-cite! 'winding-integrand-holomorphic wzi-z)
(dk-cite! 'holomorphic-on-in-fun wzi-u wzi-k)
(dk-cite! 'holomorphic-on-continuous wzi-u wzi-k)
(dk-cite! 'holomorphic-on-open wzi-u wzi-k)
(dk-cite! 'cc-open-subset-cc wzi-u)
(dk-cite! 'cc-punctured-open wzi-z)
(fact 'cc-is-set)
(fact 'subclass-of-set-is-set wzi-u 'CC)
;; the trace lies in CC \ {z}
(dk-have! (list 'SUBSET '(TRACE pgam a b) wzi-u)
  (lambda ()
    (let ((w (subset-by-element!)))
      (fact 'trace-subset-cc 'pgam 'a 'b)
      (fact 'subset-mem-fwd '(TRACE pgam a b) 'CC w)
      (dk-have! (list 'NOT (list '= w wzi-z))
        (lambda () (di) (dk-have! (list 'IN wzi-z '(TRACE pgam a b)) (lambda () (subst (list '= wzi-z w)) (dk-ass!)))
                   (ai (dk-ctx-form (list 'NOT (list 'IN wzi-z '(TRACE pgam a b)))))))
      (wzi-pz-in! wzi-z w))))
(dk-have! (list 'FORALL 'msy_ (list 'IMPLIES (list 'IN 'msy_ wzi-cc) (list 'IN '(pgam msy_) wzi-u)))
  (lambda ()
    (let ((y (dk-di-var!)))
      (fact 'trace-value-in 'pgam 'a 'b y)
      (fact 'subset-mem-fwd '(TRACE pgam a b) wzi-u (list 'pgam y))
      (dk-ass!))))
(define wzi-pgu3 (wzi-pick-univ "the trace lies in CC \\ {z}" 'msy_ '(pgam msy_)))
;; the non-vanishing dk-diff! owes, on CC \ {z}
(define wzi-dz (list 'FORALL 'dkdoy_ (list 'IMPLIES (list 'IN 'dkdoy_ wzi-u)
                     (list 'NOT (list '= (list '- 'dkdoy_ wzi-z) 0)))))
(dk-have! wzi-dz (lambda () (let ((y (dk-di-var!))) (wzi-pz-open! wzi-z y) (dk-ass!))))
(define wzi-dz2 (list 'FORALL 'dkdoy_ (list 'IMPLIES (list 'IN 'dkdoy_ wzi-u)
                     (list 'NOT (list '= (list '* (list '- 'dkdoy_ wzi-z) (list '- 'dkdoy_ wzi-z)) 0)))))
(dk-have! wzi-dz2
  (lambda () (let* ((y (dk-di-var!)) (d (list '- y wzi-z)))
               (wzi-pz-open! wzi-z y)
               (wzi-cc! d)
               (dk-cite! 'cc-mul-nonzero d d)
               (dk-ass!))))

;;; ---- H: the integral as a function of its upper limit (2)
(define wzi-ex (dk-fact! 'line-int-primitive-road wzi-u wzi-k 'pgam 'dgam 'a 'b))
(define wzi-hh (dk-skolem! wzi-ex))
(define wzi-phik (wzi-plam (list '* (list wzi-k '(pgam pat_)) '(dgam pat_))))
(define wzi-lint (list 'LINE-INT wzi-k 'pgam 'dgam 'a 'b))
(fact 'is-road-is-path wzi-hh wzi-phik 'a 'b)
(fact 'is-path-in-fun wzi-hh 'a 'b)
(fact 'trace-subset-cc wzi-hh 'a 'b)

;;; ---- A = exp o H, a road (road-holomorphic-image on CC)
(fact 'cc-exp-holomorphic)
(dk-cite! 'holomorphic-on-in-fun 'CC wzi-ee)
(dk-have! (list 'FORALL 'hbz_ (list 'IMPLIES '(IN hbz_ CC)
            (list 'IS-DIFF-ON 'CC-NORMED-FIELD 'CC wzi-ee 'hbz_ (list wzi-ee 'hbz_))))
  (lambda ()
    (let ((y (dk-di-var!)))
      (dk-cite! 'cc-exp-deriv y)
      (wzi-cc! (list 'CC-EXP y))
      (dk-have! (list '= (list wzi-ee y) (list 'CC-EXP y)) (lambda () (dk-lam-b!) (rfl)))
      (subst (list '= (list wzi-ee y) (list 'CC-EXP y)))
      (dk-ass!))))
(dk-have! (list 'FORALL 'rgy_ (list 'IMPLIES '(IN rgy_ CC)
            (list 'IS-CONTINUOUS-AT (list 'SUBSPACE-MS wzi-nfm 'CC) wzi-nfm wzi-ee 'rgy_)))
  (lambda () (let ((y (dk-di-var!))) (dk-cite! 'cc-exp-continuous y) (dk-ass!))))
(define wzi-ra (dk-fact! 'road-holomorphic-image 'CC wzi-ee wzi-ee wzi-hh wzi-phik 'a 'b))
(if (not (eq? (wzi-head wzi-ra) 'IS-ROAD)) (error "wzi: road-holomorphic-image (exp) did not detach" (expression->string wzi-ra)))

;;; ---- B = (w |-> 1/(w - z)) o gamma, a road
(define wzi-dk (list 'VNB-LAMBDA 'wnw_ wzi-u (list '- (list 'recip (list '* (list '- 'wnw_ wzi-z) (list '- 'wnw_ wzi-z))))))
(define (wzi-dk-at! y)
  (let ((d (list '- y wzi-z)))
    (wzi-pz-open! wzi-z y)
    (wzi-cc! d)
    (dk-cite! 'cc-mul-nonzero d d)
    (wzi-cc! (list '- (list 'recip (list '* d d))))))
(dk-have! (list 'IN wzi-dk (list 'FUN wzi-u 'CC))
  (lambda () (dk-lam-type! (lambda () (let ((y (dk-di-var!))) (wzi-dk-at! y)
                                        (if (dk--redex? (dk-goal)) (dk-lam-b!)) (dk-ass!))) ass)))
(dk-have! (list 'FORALL 'hbz_ (list 'IMPLIES (list 'IN 'hbz_ wzi-u)
            (list 'IS-DIFF-ON 'CC-NORMED-FIELD wzi-u wzi-k 'hbz_ (list wzi-dk 'hbz_))))
  (lambda ()
    (let* ((y (dk-di-var!))
           (d (list '- y wzi-z))
           (v (list '- (list 'recip (list '* d d)))))
      (wzi-dk-at! y)
      (dk-diff! wzi-u wzi-k y)
      (dk-have! (list '= (list wzi-dk y) v) (lambda () (dk-lam-b!) (rfl)))
      (subst (list '= (list wzi-dk y) v))
      (dk-ass!))))
(dk-have! (list 'HOLOMORPHIC-ON wzi-u wzi-dk) (lambda () (dk-holomorphic! wzi-u wzi-dk)))
(dk-cite! 'holomorphic-on-continuous wzi-u wzi-dk)
(define wzi-rb (dk-fact! 'road-holomorphic-image wzi-u wzi-k wzi-dk 'pgam 'dgam 'a 'b))
(if (not (eq? (wzi-head wzi-rb) 'IS-ROAD)) (error "wzi: road-holomorphic-image (kernel) did not detach" (expression->string wzi-rb)))
;;; ---- the product A B has derivative 0: road-product-constant
(define wzi-a (cadr wzi-ra))
(define wzi-da (caddr wzi-ra))
(define wzi-b (cadr wzi-rb))
(define wzi-db (caddr wzi-rb))
;;; y in [a, b]: the values typed, gamma(y) - z /= 0, H(y) in CC; returns
;;; (e k d w) with e = exp(H y), k = recip(gamma y - z), d = gamma'(y), w = gamma y - z
(define (wzi-abpt! y)
  (let* ((w (list '- (list 'pgam y) wzi-z))
         (k (list 'recip w))
         (hy (list wzi-hh y))
         (e (list 'CC-EXP hy))
         (d (list 'dgam y)))
    (fact 'fun-apply-type-c 'pgam wzi-cc 'CC y)
    (fact 'fun-apply-type-c 'dgam wzi-cc 'CC y)
    (fact 'fun-apply-type-c wzi-hh wzi-cc 'CC y)
    (dk-apply! wzi-pgu3 y)
    (wzi-pz-open! wzi-z (list 'pgam y))
    (wzi-cc! w) (wzi-cc! k) (wzi-cc! e)
    (dk-cite! 'cc-mul-nonzero w w)
    (wzi-cc! (list '- (list 'recip (list '* w w))))
    (wzi-cc! (list '* k d))
    (list e k d w)))
(dk-have! (list 'FORALL 'wzt_ (list 'IMPLIES (list 'IN 'wzt_ wzi-cc)
            (list '= (list '+ (list '* (list wzi-da 'wzt_) (list wzi-b 'wzt_))
                              (list '* (list wzi-a 'wzt_) (list wzi-db 'wzt_))) 0)))
  (lambda ()
    (let* ((y (dk-di-var!))
           (ekdw (wzi-abpt! y))
           (e (car ekdw)) (k (cadr ekdw)) (d (caddr ekdw)) (w (cadddr ekdw)))
      (dk-lam-b!)

      (dk-cite! 'cc-recip-mul w w)
      (subst (list '= (list 'recip (list '* w w)) (list '* k k)))
      (let ((kv (dk-name! k 'CC)) (ev (dk-name! e 'CC)))
        (subst (list '= k kv))
        (subst (list '= e ev))
        (crs)))))
(define wzi-pc (dk-fact! 'road-product-constant wzi-a wzi-da wzi-b wzi-db 'a 'b))
;;; ---- read off: exp(H b) / (gamma b - z) = exp(H a) / (gamma a - z)
;;; from (= (* x c) (* y c)) and (= (* ci c) 1) in context, c and ci free of recip:
;;; land (= x y)
(define (wzi-cancel! x y c ci)
  (for-each (lambda (t)
              (dk-have! (list '= (list '* (list '* t c) ci) (list '* t (list '* ci c))) (lambda () (crs)))
              (dk-have! (list '= (list '* (list '* t c) ci) t)
                (lambda ()
                  (subst (list '= (list '* (list '* t c) ci) (list '* t (list '* ci c))))
                  (subst (list '= (list '* ci c) 1))
                  (crs))))
            (list x y))
  (dk-have! (list '= x y)
    (lambda ()
      (subst (list '= x (list '* (list '* x c) ci)))
      (subst (list '= (list '* x c) (list '* y c)))
      (dk-ass!))))
(define wzi-kk #f)
(define (wzi-pick-univ-eq lint)
  (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) '=) (equal? (cadr fm) lint))) "the line integral as H(b) - H(a)"))
(let* ((pa (wzi-abpt! 'a)) (pb (wzi-abpt! 'b))
       (ea (car pa)) (ka (cadr pa)) (wa (cadddr pa))
       (eb (car pb)) (kb (cadr pb))
       (ha (list wzi-hh 'a)) (hb (list wzi-hh 'b))
       (lint wzi-lint)
       (el (list 'CC-EXP lint)))
  (for-each (lambda (z e k)
              (dk-have! (list '= (list wzi-a z) e) (lambda () (dk-lam-b!) (rfl)))
              (dk-have! (list '= (list wzi-b z) k) (lambda () (dk-lam-b!) (rfl))))
            '(a b) (list ea eb) (list ka kb))
  (dk-have! (list '= kb ka) (lambda () (subst '(= (pgam b) (pgam a))) (rfl)))
  (dk-cite! 'cc-recip-inverse wa)
  (let ((kv (dk-name! ka 'CC)))
    (dk-have! (list '= (list '* wa kv) 1) (lambda () (subst (list '= kv ka)) (dk-ass!)))
    (dk-have! (list '= kv (list wzi-b 'b))
      (lambda () (subst (list '= (list wzi-b 'b) kb)) (subst (list '= kb ka)) (dk-ass!)))
    (dk-have! (list '= kv (list wzi-b 'a))
      (lambda () (subst (list '= (list wzi-b 'a) ka)) (dk-ass!)))
    (for-each (lambda (z e)
                (dk-have! (list '= (list '* e kv) (list '* (list wzi-a z) (list wzi-b z)))
                  (lambda () (subst (list '= (list wzi-a z) e)) (subst (list '= (list wzi-b z) kv)) (rfl))))
              '(b a) (list eb ea))
    (dk-have! (list '= (list '* eb kv) (list '* ea kv))
      (lambda ()
        (subst (list '= (list '* eb kv) (list '* (list wzi-a 'b) (list wzi-b 'b))))
        (subst (list '= (list '* ea kv) (list '* (list wzi-a 'a) (list wzi-b 'a))))
        (dk-ass!)))
    (wzi-cancel! eb ea kv wa)))
;;; ---- exp(L) = 1, L in 2 pi i ZZ, WINDING = k
(let* ((ha (list wzi-hh 'a)) (hb (list wzi-hh 'b))
       (ea (list 'CC-EXP ha)) (eb (list 'CC-EXP hb))
       (lint wzi-lint)
       (el (list 'CC-EXP lint))
       (leq (wzi-pick-univ-eq lint)))
  (dk-have! (list 'IN lint 'CC)
    (lambda () (subst leq) (wzi-cc! (list '- hb ha)) (dk-ass!)))
  (wzi-cc! el)
  (dk-have! (list '= (list '+ ha lint) hb) (lambda () (subst leq) (crs)))
  (dk-cite! 'cc-exp-add ha lint)
  (dk-have! (list '= eb (list '* ea el))
    (lambda () (subst (list '= hb (list '+ ha lint))) (dk-ass!)))
  (dk-cite! 'cc-exp-nonzero ha)
  (let ((ev (wzi-inv! ea)))
    (dk-have! (list '= (list '* ev ea) (list '* ea ev)) (lambda () (crs)))
    (dk-have! (list '= (list '* ev ea) 1)
      (lambda () (subst (list '= (list '* ev ea) (list '* ea ev))) (dk-ass!)))
    (dk-have! (list '= (list '* el ea) (list '* 1 ea))
      (lambda ()
        (dk-have! (list '= (list '* el ea) eb) (lambda () (subst (list '= eb (list '* ea el))) (crs)))
        (subst (list '= (list '* el ea) eb))
        (subst (list '= eb ea))
        (crs)))
    (wzi-cancel! el 1 ea ev))
  ;; the kernel of exp
  (let* ((iff (dk-cite! 'cc-exp-one-iff lint))
         (ex  (caddr iff)))
    (dk-have! ex (lambda () (wzi-kp! iff (list '= el 1))))
    (let* ((k (dk-skolem! (dk-ctx-form ex)))
           (keq (list '= lint (list '* k wzi-tpi))))
      (fact 'zz-in-rr k)
      (fact 'rr-subset-cc k)
      (wzi-tpi!)
      (let ((tv (wzi-inv! wzi-tpi)))
        (ew k)
        (dk-conj-close!
         (lambda ()
           (if (dk-ass!)
               #t
               (begin
                 (mac 'WINDING)
                 (subst keq)
                 (subst (list '= (list 'recip wzi-tpi) tv))
                 (dk-have! (list '= (list '* tv (list '* k wzi-tpi)) (list '* k (list '* wzi-tpi tv))) (lambda () (crs)))
                 (subst (list '= (list '* tv (list '* k wzi-tpi)) (list '* k (list '* wzi-tpi tv))))
                 (subst (list '= (list '* wzi-tpi tv) 1))
                 (crs)))))))))
(qed 'winding-number-integer)

