;;; winding-number-laws.scm -- CAUCHY ON A DISC, THE WINDING NUMBER, THE CIRCLE AS A ROAD
;;; (complex-analysis.pdf ch. 3: Corollary 3.9 for a disc inside an open set; Definition
;;; 3.26 and the disc case of Corollary 3.30; Example 3.13 at the centre).
;;; Agent CA-1 of the October roadmap (docs/roadmap-2026-10-03.md, line (a), decisions 1-2),
;;; 2026-10-03.  The definitions are structure-library/winding-number.scm.
;;;
;;; THE SURVEY (what the tree had on 2026-10-03, before this file).
;;; * A PRIMITIVE ON A CONVEX SET: `cauchy-convex-primitive' (goursat.scm, the notes'
;;;   Prop 3.8: f holomorphic on a convex U has a holomorphic g with g' = f on U) and
;;;   `cauchy-convex-primitive-except' (goursat-exceptional.scm, one exceptional point of
;;;   mere continuity).  There is NO separate theorem for a disc: a disc is convex, and
;;;   that fact was missing (`cc-ball-is-convex', below).  The antiderivable-* files are the
;;;   REAL calculus (calculus.pdf Def 4.6, functions of a real variable), not a complex
;;;   local primitive.
;;; * CAUCHY FOR A CLOSED ROAD IN A CONVEX SET WAS ALREADY PROVEN: `cauchy-convex-closed'
;;;   (goursat.scm, Cor 3.9) and `cauchy-convex-closed-except'.  What was missing is the
;;;   form the notes use from 3.5 on: f holomorphic on an open U, the road in a convex open
;;;   (or a disc) INSIDE U (`cauchy-convex-sub', `cauchy-disc', below).
;;; * A CLOSED ROAD HAS NO NAME: closedness is the hypothesis (= (pgam b) (pgam a)), as in
;;;   `cauchy-convex-closed' and `line-int-closed-road-of-derivative'.
;;; * CONCATENATION: JUXTA(p, q, a, b, c) (structure-library/road-juxtaposition.scm),
;;;   Dieudonne's juxtaposition on ADJACENT parameter intervals [a, b], [b, c]
;;;   (`juxta-is-road', `line-int-juxta'); `line-int-concat' shifts the second road's
;;;   interval first.  The opposite road: `opposite-is-road', `line-int-opposite-road'.
;;; * THE FUNDAMENTAL THEOREM: `line-int-of-derivative' (Prop 3.2) and its closed form
;;;   `line-int-closed-road-of-derivative'.  The circle was not in the tree; the segment
;;;   is (SEG-PATH, `segment-is-road'), and so is the AFFINE reparametrisation
;;;   (`road-affine-reparam').  exp, PI, i: CC-EXP, PI (cc-pi.scm), the literal +i.
;;;
;;; CONTENTS.
;;;  (1) cc-ball-is-convex                 an open disc of CC-MS is convex
;;;  (2) line-int-domain-congruence        LINE-INT sees only the values on the trace
;;;  (3) holomorphic-on-restrict           holomorphy restricts to an open subset
;;;  (4) cauchy-convex-sub                 Cor 3.9, the convex open set inside U
;;;  (5) cauchy-disc                       Cor 3.9 for a disc B(c, r) inside U
;;;  (6) cc-punctured-membership, cc-punctured-open      CC \ {z}
;;;  (7) winding-integrand-holomorphic     w |-> 1/(w - z) is holomorphic on CC \ {z}
;;;  (8) winding-in-cc                     the winding number is a complex number, z off the trace
;;;  (9) winding-zero-outside-disc         ... and 0 about z outside a disc containing a closed road
;;; (10) winding-circle-center             the circle about its centre: 1 (Example 3.13)
;;; (11) road-holomorphic-image            (f o gamma, (f' o gamma) gamma') is a road, f' continuous
;;; (12) circle-is-road                    the circle on [0, 2 pi] is a road
;;; (10) does not need (12): line-int-value takes the two primitives of the integrand's
;;; coordinates, and on the circle about its centre the integrand is the constant i.
;;;
;;; STATEMENT CHECKS.  Every point at which the definitions or the laws might fail to
;;; denote carries a hypothesis: the radius r is real and positive where the disc is
;;; used (a disc of radius <= 0 is empty and the road could not lie in it); z is typed
;;; (IN z CC) wherever SINGLETON(z) is instantiated (since 2026-10-01 a singleton is
;;; defined only on a set, primitive-inferences.scm); the trace lies in CC \ {z} by
;;; `not(z in trace)'.  `cauchy-disc' asks B(c, r) subset U, an OPEN disc: the notes'
;;; "closure of the disc in U" is the stronger hypothesis and is not needed.
;;;
;;; NOTHING asserted, no definition here.  Helper prefixes wnd- and wnr- (the second for
;;; the copy of line-int-fundamental.scm's lfn- helpers); binders wn*_ (none used
;;; elsewhere in the tree); u, f, df, rgy_, hbz_, pgam, dgam, a, b, pat_ as in the laws
;;; they cite.
;;; LOAD WINDOW: lo = theorem-library/cc-exp-kernel (load.scm:3532; `pi-pos'), above
;;; theorem-library/cc-exp (3525: cc-exp-converges, cc-exp-nonzero, cc-exp-zero,
;;; cex-exp-comb-deriv), goursat (3517: cauchy-convex-closed, cc-open-subset-cc,
;;; holomorphic-on-continuous), line-int-reparam (3511: road-affine-reparam), line-int-laws
;;; (3507: line-int-value, cc-int-congruence), regulated-algebra (3497: line-int-exists,
;;; line-int-in-cc, road-integrand-regulated, regulated-on-congruence),
;;; line-int-fundamental (3487: holomorphic-chain); and after
;;; structure-library/winding-number, which must load after structure-library/cc-pi
;;; (3530).  hi: none.  Tactics: the early kit only (dk-*, use-em, prop, crs, ineq).

;;; ======================================================================
;;; local helpers (goursat-exceptional.scm's gox- typers, copied: that file is not ours)
;;; ======================================================================
(define (wnd-op? t op n) (and (pair? t) (eq? (car t) op) (= (length t) n)))
(define (wnd-and! a b)
  (let ((f (list 'AND a b)))
    (if (not (dk-asm? f)) (dk-have! f (lambda () (dk-conj-close! dk-ass!))))
    f))

(define (wnd-rr! t)
  (let ((typ (list 'IN t 'RR)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'rr-zero-in) typ)
          ((eqv? t 1) (fact 'rr-one-in) typ)
          ((eq? t 'PI) (dk-split-all! (list (dk-cite! 'pi-pos))) typ)
          ((number? t) (dk-have! typ (lambda () (arith))) typ)
          ((wnd-op? t '* 3) (wnd-rr! (cadr t)) (wnd-rr! (caddr t)) (fact 'rr-mul-in-rr (cadr t) (caddr t)) typ)
          ((wnd-op? t '+ 3) (wnd-rr! (cadr t)) (wnd-rr! (caddr t)) (fact 'rr-add-in-rr (cadr t) (caddr t)) typ)
          ((wnd-op? t '- 3) (wnd-rr! (cadr t)) (wnd-rr! (caddr t)) (fact 'rr-sub-in-rr (cadr t) (caddr t)) typ)
          ((wnd-op? t '- 2) (wnd-rr! (cadr t)) (fact 'rr-neg-closed (cadr t)) typ)
          ((wnd-op? t 'magnitude 2) (wnd-cc! (cadr t)) (fact 'cc-magnitude-closed (cadr t)) typ)
          ((wnd-op? t 'real-part 2) (wnd-cc! (cadr t)) (fact 'real-part-in-rr (cadr t)) typ)
          ((wnd-op? t 'imag-part 2) (wnd-cc! (cadr t)) (fact 'imag-part-in-rr (cadr t)) typ)
          ((wnd-op? t 'abs 2) (wnd-rr! (cadr t)) (fact 'rr-abs-closed (cadr t)) typ)
          (#t (dk-real! t) typ))))

(define (wnd-cc! t)
  (let ((typ (list 'IN t 'CC)))
    (cond ((dk-asm? typ) typ)
          ((eqv? t 0) (fact 'cc-zero-in) typ)
          ((eqv? t +i) (fact 'cc-i-in) typ)
          ((or (and (number? t) (real? t)) (eq? t 'PI) (dk-asm? (list 'IN t 'RR))
               (wnd-op? t 'magnitude 2) (wnd-op? t 'real-part 2) (wnd-op? t 'imag-part 2))
           (wnd-rr! t) (fact 'rr-subset-cc t) typ)
          ((wnd-op? t '- 3) (wnd-cc! (cadr t)) (wnd-cc! (caddr t)) (fact 'cc-sub-in-cc (cadr t) (caddr t)) typ)
          ((wnd-op? t '- 2) (wnd-cc! (cadr t)) (fact 'cc-neg-closed (cadr t)) typ)
          ((wnd-op? t '+ 3) (wnd-cc! (cadr t)) (wnd-cc! (caddr t))
           (wnd-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-add-closed (cadr t) (caddr t)) typ)
          ((wnd-op? t '* 3) (wnd-cc! (cadr t)) (wnd-cc! (caddr t))
           (wnd-and! (list 'IN (cadr t) 'CC) (list 'IN (caddr t) 'CC)) (fact 'cc-mul-closed (cadr t) (caddr t)) typ)
          ((wnd-op? t 'CC-EXP 2) (wnd-cc! (cadr t))
           (dk-split-all! (list (dk-cite! 'cc-exp-converges (cadr t)))) typ)
          ((wnd-op? t 'recip 2) (wnd-cc! (cadr t))
           (if (not (dk-asm? (list 'NOT (list '= (cadr t) 0))))
               (error "wnd-cc!: land the non-vanishing first" (expression->string (cadr t))))
           (wnd-and! (list 'IN (cadr t) 'CC) (list 'NOT (list '= (cadr t) 0)))
           (fact 'cc-recip-closed (cadr t)) typ)
          (#t (error "wnd-cc!: cannot type" (expression->string t))))))

;;; x in BALL(CC-MS, c, r) in context: land x in CC and |c - x| < r; return the latter
(define (wnd-ball-open! c r x)
  (let* ((dcx (list '(DIST CC-MS) c x))
         (mag (list 'magnitude (list '- c x)))
         (iff (dk-cite! 'ball-membership 'CC-MS c r x))
         (cj  (list 'AND (list 'IN x '(PTS CC-MS)) (list 'AND (list '<= dcx r) (list 'NOT (list '= dcx r))))))
    (dk-have! cj (lambda () (dk-only! iff (list 'IN x (list 'BALL 'CC-MS c r))) (prop)))
    (dk-split-all! (list (dk-ctx-form cj)))
    (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
    (dk-have! (list 'IN x 'CC) (lambda () (subst '(= CC (PTS CC-MS))) (ass)))
    (dk-cite! 'cc-ms-dist c x)
    (wnd-rr! mag)
    (dk-have! (list 'AND (list '<= mag r) (list 'NOT (list '= mag r)))
      (lambda () (subst (list '= mag dcx)) (dk-conj-close! dk-ass!)))
    (dk-cite! 'rr-le-ne-lt mag r)))

;;; ======================================================================
;;; (1) AN OPEN DISC IS CONVEX
;;; ======================================================================
(sp (make-wff '(FORALL c (IMPLIES (IN c CC) (FORALL r (IMPLIES (IN r RR)
  (IS-CONVEX (BALL CC-MS c r))))))))
(dk-peel!)
(mac 'IS-CONVEX)
(dk-peel!)
(let* ((pt (cadr (dk-goal)))
       (x  (cadr pt))
       (tt (cadr (caddr pt)))
       (y  (cadr (caddr (caddr pt))))
       (ball '(BALL CC-MS c r)))
  (wnd-ball-open! 'c 'r x)
  (wnd-ball-open! 'c 'r y)
  (fact 'ccint-elt-in-rr 0 1 tt)
  (dk-have! (list 'AND (list '<= 0 tt) (list '<= tt 1))
    (lambda () (mac-h 'ccint-membership (list 'IN tt '(CCINT 0 1))) (dk-split-all!)
               (dk-conj-close! dk-ass!)))
  (dk-split-all!)
  (wnd-cc! pt)
  (use-em (list '= 0 tt)
    (lambda ()
      (dk-have! (list '= pt x) (lambda () (subst (list '= tt 0)) (crs)))
      (subst (list '= pt x))
      (ass))
    (lambda ()
      (let* ((dx (list 'magnitude (list '- 'c x)))
             (dy (list 'magnitude (list '- 'c y)))
             (s  (begin (wnd-rr! (list '- 1 tt)) (dk-name! (list '- 1 tt))))
             (cz (list '- 'c pt))
             (u1 (list '* s (list '- 'c x)))
             (u2 (list '* tt (list '- 'c y)))
             (dd (list '+ (list '* s dx) (list '* tt dy))))
        (wnd-rr! s)
        (dk-have! (list '< 0 tt)
          (lambda () (wnd-and! (list '<= 0 tt) (list 'NOT (list '= 0 tt))) (dk-cite! 'rr-le-ne-lt 0 tt) (ass)))
        (dk-have! (list '<= 0 s) (lambda () (dk-ineq! (list '= s (list '- 1 tt)) (list '<= tt 1))))
        (wnd-cc! u1) (wnd-cc! u2) (wnd-cc! cz)
        (dk-have! (list '= cz (list '+ u1 u2)) (lambda () (subst (list '= s (list '- 1 tt))) (crs)))
        ;; |c - z| <= s |c - x| + t |c - y|
        (wnd-and! (list 'IN u1 'CC) (list 'IN u2 'CC))
        (dk-cite! 'cc-magnitude-triangle u1 u2)
        (fact 'rr-subset-cc s) (fact 'rr-subset-cc tt)
        (wnd-and! (list 'IN s 'CC) (list 'IN (list '- 'c x) 'CC))
        (wnd-and! (list 'IN tt 'CC) (list 'IN (list '- 'c y) 'CC))
        (dk-cite! 'cc-magnitude-mul s (list '- 'c x))
        (dk-cite! 'cc-magnitude-mul tt (list '- 'c y))
        (dk-cite! 'rr-magnitude-is-abs s) (dk-cite! 'rr-magnitude-is-abs tt)
        (dk-cite! 'rr-abs-of-nonneg s) (dk-cite! 'rr-abs-of-nonneg tt)
        (wnd-rr! (list 'magnitude cz)) (wnd-rr! dd)
        (for-each (lambda (k d)
                    (wnd-rr! (list 'magnitude k))
                    (dk-have! (list '= (list '* (list 'magnitude k) d) (list '* k d))
                      (lambda () (subst (list '= (list 'magnitude k) (list 'abs k)))
                                 (subst (list '= (list 'abs k) k)) (rfl))))
                  (list s tt) (list dx dy))
        (wnd-rr! (list 'magnitude u1)) (wnd-rr! (list 'magnitude u2))
        (wnd-rr! (list '* (list 'magnitude s) dx)) (wnd-rr! (list '* (list 'magnitude tt) dy))
        (wnd-rr! (list 'magnitude (list '+ u1 u2)))
        (dk-have! (list '<= (list 'magnitude cz) dd)
          (lambda ()
            (subst (list '= cz (list '+ u1 u2)))
            (dk-ineq! (list '<= (list 'magnitude (list '+ u1 u2)) (list '+ (list 'magnitude u1) (list 'magnitude u2)))
                      (list '= (list 'magnitude u1) (list '* (list 'magnitude s) dx))
                      (list '= (list 'magnitude u2) (list '* (list 'magnitude tt) dy))
                      (list '= (list '* (list 'magnitude s) dx) (list '* s dx))
                      (list '= (list '* (list 'magnitude tt) dy) (list '* tt dy)))))
        ;; s |c - x| + t |c - y| < r
        (wnd-rr! (list '* s dx)) (wnd-rr! (list '* tt dy)) (wnd-rr! (list '* 'r s)) (wnd-rr! (list '* 'r tt))
        (dk-have! (list '<= dx 'r) (lambda () (dk-ineq! (list '< dx 'r))))
        (dk-cite! 'rr-mul-le-right dx 'r s)
        (dk-have! (list '= (list '* dx s) (list '* s dx)) (lambda () (crs)))
        (wnd-rr! (list '* dx s))
        (wnd-rr! (list '- 'r dy))
        (dk-have! (list '< 0 (list '- 'r dy)) (lambda () (dk-ineq! (list '< dy 'r))))
        (dk-cite! 'rr-mul-pos (list '- 'r dy) tt)
        (let ((p (begin (wnd-rr! (list '* (list '- 'r dy) tt)) (dk-name! (list '* (list '- 'r dy) tt)))))
          (dk-have! (list '< 0 p) (lambda () (subst (list '= p (list '* (list '- 'r dy) tt))) (ass)))
          (dk-have! (list '= p (list '- (list '* 'r tt) (list '* tt dy)))
            (lambda () (subst (list '= p (list '* (list '- 'r dy) tt))) (crs)))
          (dk-have! (list '= 'r (list '+ (list '* 'r s) (list '* 'r tt)))
            (lambda () (subst (list '= s (list '- 1 tt))) (crs)))
          (dk-have! (list '< dd 'r)
            (lambda ()
              (dk-ineq! (list '<= (list '* dx s) (list '* 'r s))
                        (list '= (list '* dx s) (list '* s dx))
                        (list '< 0 p)
                        (list '= p (list '- (list '* 'r tt) (list '* tt dy)))
                        (list '= 'r (list '+ (list '* 'r s) (list '* 'r tt)))))))
        ;; back into the ball
        (fact 'cc-is-metric-space)
        (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
        (dk-have! (list 'IN 'c '(PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
        (dk-have! (list 'IN pt '(PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
        (dk-cite! 'cc-ms-dist 'c pt)
        (dk-have! (list '<= (list '(DIST CC-MS) 'c pt) dd)
          (lambda () (subst (list '= (list '(DIST CC-MS) 'c pt) (list 'magnitude cz))) (ass)))
        (let ((cj (list 'AND (list 'IN pt '(PTS CC-MS)) (list 'AND (list 'IN dd 'RR) (list 'AND (list 'IN 'r 'RR)
                    (list 'AND (list '<= (list '(DIST CC-MS) 'c pt) dd) (list '< dd 'r)))))))
          (dk-have! cj (lambda () (dk-conj-close! dk-ass!)))
          (dk-cite! 'ball-mem-from-le 'CC-MS 'c pt dd 'r)
          (ass))))))
(qed 'cc-ball-is-convex)

;;; ======================================================================
;;; (2) THE LINE INTEGRAL SEES ONLY THE VALUES ON THE TRACE
;;; (the road form of goursat-exceptional's seg-int-congruence, the same proof)
;;; ======================================================================
(define wnd-nfm '(NF-METRIC-SPACE CC-NORMED-FIELD))
(define (wnd-cont u f)
  (list 'FORALL 'rgy_ (list 'IMPLIES (list 'IN 'rgy_ u)
    (list 'IS-CONTINUOUS-AT (list 'SUBSPACE-MS wnd-nfm u) wnd-nfm f 'rgy_))))
(define (wnd-imps hyps body)
  (if (null? hyps) body (list 'IMPLIES (car hyps) (wnd-imps (cdr hyps) body))))
(define wnd-tr '(TRACE pgam a b))
(define wnd-road '(IS-ROAD pgam dgam a b))
(define (wnd-all vars body)
  (if (null? vars) body (list 'FORALL (car vars) (wnd-all (cdr vars) body))))

(sp (make-wff (wnd-all '(u f)
  (wnd-imps (list '(SUBSET u CC) '(IN f (FUN u CC)) (wnd-cont 'u 'f))
    (wnd-all '(pgam dgam a b)
      (wnd-imps (list wnd-road (list 'SUBSET wnd-tr 'u))
        (wnd-all '(wnv_)
          (list 'FORALL 'wng_ (wnd-imps (list '(IN wng_ (FUN wnv_ CC)) (list 'SUBSET wnd-tr 'wnv_)
                   (list 'FORALL 'wnx_ (list 'IMPLIES (list 'IN 'wnx_ wnd-tr) '(== (wng_ wnx_) (f wnx_)))))
            '(= (LINE-INT wng_ pgam dgam a b) (LINE-INT f pgam dgam a b)))))))))))
(dk-peel!)
(let ((hyp (dk-pick (lambda (fm) (and (wnd-op? fm 'FORALL 3) (dk-contains? fm 'wng_) (dk-contains? fm '==)))
                    "the values agree on the trace")))
  (fact 'is-road-is-path 'pgam 'dgam 'a 'b)
  (fact 'is-path-in-fun 'pgam 'a 'b)
  (fact 'is-road-dgam-in-fun 'pgam 'dgam 'a 'b)
  (dk-split-all! (list (dk-cite! 'is-path-endpoints 'pgam 'a 'b)))
  (subst (dk-cite! 'line-int-unfold 'wng_ 'pgam 'dgam 'a 'b))
  (subst (dk-cite! 'line-int-unfold 'f 'pgam 'dgam 'a 'b))
  (let* ((g (dk-goal))
         (psi (cadr (cadr g)))
         (phi (cadr (caddr g)))
         (ex (dk-cite! 'line-int-exists 'u 'f 'pgam 'dgam 'a 'b))
         (p1 (dk-skolem! ex))
         (p2 (dk-skolem! (dk-pick (lambda (fm) (and (wnd-op? fm 'FORSOME 3) (dk-contains? fm p1))) "the second primitive"))))
    (dk-cite! 'line-int-integrand-in-fun 'a 'b 'pgam 'dgam 'wng_ 'wnv_)
    (dk-have! (list 'FORALL 'liy_ (list 'IMPLIES '(IN liy_ (CCINT a b)) (list '== (list phi 'liy_) (list psi 'liy_))))
      (lambda ()
        (let ((y (dk-di-var!)))
          (dk-lam-b!)
          (dk-cite! 'trace-value-in 'pgam 'a 'b y)
          (subst (dk-apply! hyp (list 'pgam y)))
          (qrfl))))
    (subst (dk-cite! 'cc-int-congruence phi psi 'a 'b p1 p2))
    (rfl)))
(qed 'line-int-domain-congruence)

;;; ======================================================================
;;; (3) HOLOMORPHY RESTRICTS TO AN OPEN SUBSET
;;; ======================================================================
(sp (make-wff '(FORALL u (FORALL f (IMPLIES (HOLOMORPHIC-ON u f)
  (FORALL wnv_ (IMPLIES (IS-OPEN (NF-METRIC-SPACE CC-NORMED-FIELD) wnv_)
    (IMPLIES (SUBSET wnv_ u) (HOLOMORPHIC-ON wnv_ (RESTRICT f wnv_))))))))))
(dk-peel!)
(dk-cite! 'holomorphic-on-in-fun 'u 'f)
(mac 'HOLOMORPHIC-ON)
(dk-conj-close!
  (lambda ()
    (let ((g (dk-goal)))
      (cond ((dk-asm? g) (ass))
            ((wnd-op? g 'IN 3) (dk-cite! 'restrict-in-fun 'f 'u 'CC 'wnv_) (ass))
            (#t
             (let ((a (dk-di-var!)))
               (fact 'subset-mem-fwd 'wnv_ 'u a)
               (let* ((l (dk-skolem! (dk-apply! (dk-cite! 'holomorphic-on-diff 'u 'f) a))))
                 (dk-cite! 'diff-on-shrink 'CC-NORMED-FIELD 'u 'f a l 'wnv_)
                 (ew l)
                 (ass))))))))
(qed 'holomorphic-on-restrict)

;;; ======================================================================
;;; (4) CAUCHY FOR A CLOSED ROAD IN AN OPEN CONVEX SUBSET OF THE DOMAIN
;;; (Corollary 3.9 with f holomorphic on a LARGER open set: the form 3.5-3.8 use)
;;; ======================================================================
(sp (make-wff '(FORALL u (FORALL f (IMPLIES (HOLOMORPHIC-ON u f)
  (FORALL wnv_ (IMPLIES (IS-OPEN (NF-METRIC-SPACE CC-NORMED-FIELD) wnv_)
    (IMPLIES (IS-CONVEX wnv_) (IMPLIES (SUBSET wnv_ u)
      (FORALL pgam (FORALL dgam (FORALL a (FORALL b
        (IMPLIES (IS-ROAD pgam dgam a b) (IMPLIES (SUBSET (TRACE pgam a b) wnv_)
          (IMPLIES (= (pgam b) (pgam a)) (= (LINE-INT f pgam dgam a b) 0)))))))))))))))))
(dk-peel!)
(let* ((rf '(RESTRICT f wnv_)))
  (dk-cite! 'holomorphic-on-restrict 'u 'f 'wnv_)
  (dk-cite! 'holomorphic-on-in-fun 'wnv_ rf)
  (dk-cite! 'holomorphic-on-in-fun 'u 'f)
  (dk-cite! 'holomorphic-on-open 'u 'f)
  (dk-cite! 'cc-open-subset-cc 'u)
  (dk-cite! 'holomorphic-on-continuous 'u 'f)
  (dk-cite! 'subset-trans '(TRACE pgam a b) 'wnv_ 'u)
  (dk-cite! 'cauchy-convex-closed 'wnv_ rf 'pgam 'dgam 'a 'b)
  (dk-have! (list 'FORALL 'wnx_ (list 'IMPLIES '(IN wnx_ (TRACE pgam a b)) (list '== (list rf 'wnx_) '(f wnx_))))
    (lambda ()
      (let ((z (dk-di-var!)))
        (fact 'subset-mem-fwd '(TRACE pgam a b) 'wnv_ z)
        (dk-cite! 'restrict-apply 'f 'wnv_ z)
        (ass))))
  (let ((eq (dk-cite! 'line-int-domain-congruence 'u 'f 'pgam 'dgam 'a 'b 'wnv_ rf)))
    (subst (list '= '(LINE-INT f pgam dgam a b) (list 'LINE-INT rf 'pgam 'dgam 'a 'b)))
    (ass)))
(qed 'cauchy-convex-sub)

;;; ======================================================================
;;; (5) CAUCHY ON A DISC: f holomorphic on U, the open disc B(c, r) inside U, a closed
;;; road in the disc: the integral is 0
;;; ======================================================================
(sp (make-wff '(FORALL u (FORALL f (IMPLIES (HOLOMORPHIC-ON u f)
  (FORALL c (IMPLIES (IN c CC) (FORALL r (IMPLIES (IN r RR) (IMPLIES (< 0 r)
    (IMPLIES (SUBSET (BALL CC-MS c r) u)
      (FORALL pgam (FORALL dgam (FORALL a (FORALL b
        (IMPLIES (IS-ROAD pgam dgam a b) (IMPLIES (SUBSET (TRACE pgam a b) (BALL CC-MS c r))
          (IMPLIES (= (pgam b) (pgam a)) (= (LINE-INT f pgam dgam a b) 0)))))))))))))))))))
(dk-peel!)
(let ((bl '(BALL CC-MS c r)))
  (fact 'cc-is-metric-space)
  (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
  (dk-have! '(IN c (PTS CC-MS)) (lambda () (subst '(= (PTS CC-MS) CC)) (ass)))
  (dk-have! '(<= 0 r) (lambda () (dk-ineq! '(< 0 r))))
  (dk-have! '(NOT (= 0 r)) (lambda () (fact 'rr-zero-in) (dk-split-all! (list (dk-cite! 'pw-lt-ne 0 'r))) (ass)))
  (wnd-and! '(IN r RR) (wnd-and! '(<= 0 r) '(NOT (= 0 r))))
  (dk-cite! 'ball-is-open 'CC-MS 'c 'r)
  (dk-split-all! (list (dk-cite! 'cc-ms-open-iff bl)))
  (dk-have! (list 'IS-OPEN wnd-nfm bl) (lambda () (prop)))
  (dk-cite! 'cc-ball-is-convex 'c 'r)
  (dk-cite! 'cauchy-convex-sub 'u 'f bl 'pgam 'dgam 'a 'b)
  (ass))
(qed 'cauchy-disc)

;;; ======================================================================
;;; (6) THE PUNCTURED PLANE CC \ {z}: membership and openness
;;; ======================================================================
(define (wnd-pz z) (list 'DIFFERENCE 'CC (list 'SINGLETON z)))

(sp (make-wff (list 'FORALL 'wnz_ (list 'IMPLIES '(IN wnz_ CC) (list 'FORALL 'wny_
  (list 'IFF (list 'IN 'wny_ (wnd-pz 'wnz_)) '(AND (IN wny_ CC) (NOT (= wny_ wnz_)))))))))
(dk-peel!)
(fact 'difference-membership 'CC '(SINGLETON wnz_) 'wny_)
(fact 'singleton-membership 'wnz_ 'wny_)
(fact 'membership-implies-sethood 'wny_ 'CC)
(prop)
(qed 'cc-punctured-membership)

;;; y in CC \ {z}: land y in CC, y /= z, y - z /= 0
(define (wnd-pz-open! z y)
  (let ((iff (dk-cite! 'cc-punctured-membership z y)))
    (dk-have! (list 'IN y 'CC) (lambda () (dk-only! iff (list 'IN y (wnd-pz z))) (prop)))
    (dk-have! (list 'NOT (list '= y z)) (lambda () (dk-only! iff (list 'IN y (wnd-pz z))) (prop)))
    (wnd-sub-nz! y z)))

;;; y, z in CC, y /= z in context: land y - z /= 0
(define (wnd-sub-nz! y z)
  (let ((nz (list 'NOT (list '= (list '- y z) 0))))
    (dk-have! nz
      (lambda ()
        (di)
        (dk-cite! 'cc-sub-zero-eq y z)
        (ai (dk-ctx-form (list 'NOT (list '= y z))))))
    nz))

;;; y in CC, y /= z in context: land y in CC \ {z}
(define (wnd-pz-in! z y)
  (let ((iff (dk-cite! 'cc-punctured-membership z y)))
    (dk-have! (list 'IN y (wnd-pz z))
      (lambda () (dk-only! iff (list 'IN y 'CC) (list 'NOT (list '= y z))) (prop)))))

(sp (make-wff (list 'FORALL 'wnz_ (list 'IMPLIES '(IN wnz_ CC) (list 'IS-OPEN 'CC-MS (wnd-pz 'wnz_))))))
(dk-peel!)
(fact 'cc-is-metric-space)
(dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl)))
(mac 'IS-OPEN)
(dk-conj-close!
  (lambda ()
    (let ((g (dk-goal)))
      (cond ((dk-asm? g) (ass))
            ((wnd-op? g 'SUBSET 3)
             (let ((w (subset-by-element!)))
               (wnd-pz-open! 'wnz_ w)
               (subst '(= (PTS CC-MS) CC))
               (ass)))
            (#t
             (let* ((y (dk-di-var!)))
               (wnd-pz-open! 'wnz_ y)
               (wnd-cc! (list '- y 'wnz_))
               (let* ((mg (list 'magnitude (list '- y 'wnz_))))
                 (fact 'cc-magnitude-closed (list '- y 'wnz_))
                 (fact 'cc-magnitude-nonneg (list '- y 'wnz_))
                 (fact 'cc-magnitude-zero-iff (list '- y 'wnz_))
                 (dk-have! (list 'NOT (list '= 0 mg))
                   (lambda () (di) (fact 'eq-sym 0 mg)
                              (dk-only! (list '= mg 0) (list 'NOT (list '= (list '- y 'wnz_) 0))
                                        (dk-ctx-form (list 'IFF (list '= mg 0) (list '= (list '- y 'wnz_) 0))))
                              (prop)))
                 (dk-have! (list 'AND (list '<= 0 mg) (list 'NOT (list '= 0 mg))))
                 (fact 'rr-le-ne-lt 0 mg)
                 (let ((m (dk-name! mg)))
                   (dk-have! (list '< 0 m) (lambda () (subst (list '= m mg)) (ass)))
                   (dk-cite! 'rr-pos-rr-of-lt m)
                   (ew m)
                   (dk-conj-close!
                     (lambda ()
                       (if (dk-asm? (dk-goal))
                           (ass)
                           (let ((w (subset-by-element!)))
                             (let ((lt (wnd-ball-open! y m w)))
                               (dk-have! (list 'NOT (list '= w 'wnz_))
                                 (lambda ()
                                   (di)
                                   (dk-have! (list '< mg m)
                                     (lambda () (subst (list '= 'wnz_ w)) (ass)))
                                   (dk-absurd! (list '< mg m) (list '= m mg))))
                               (wnd-pz-in! (quote wnz_) w))))))))))))))
(qed 'cc-punctured-open)

;;; ======================================================================
;;; (7) THE WINDING INTEGRAND w |-> 1/(w - z) IS HOLOMORPHIC ON CC \ {z}
;;; ======================================================================
(define (wnd-kern z) (list 'VNB-LAMBDA 'wnw_ (wnd-pz z) (list 'recip (list '- 'wnw_ z))))

(sp (make-wff (list 'FORALL 'wnz_ (list 'IMPLIES '(IN wnz_ CC)
  (list 'HOLOMORPHIC-ON (wnd-pz 'wnz_) (wnd-kern 'wnz_))))))
(dk-peel!)
(let* ((z 'wnz_) (dd (wnd-pz z))
       (sl (list 'VNB-LAMBDA 'wnw_ dd (list '- 'wnw_ z)))
       (id (list 'VNB-LAMBDA 'hbx_ dd 'hbx_))
       (cs (list 'VNB-LAMBDA 'hbx_ dd (list '- z))))
  (dk-cite! 'cc-punctured-open z)
  (fact 'cc-is-set)
  (dk-cite! 'difference-set 'CC (list 'SINGLETON z))
  (wnd-cc! (list '- z))
  (dk-cite! 'holomorphic-identity dd)
  (dk-cite! 'holomorphic-const dd (list '- z))
  ;; the typing of the two lambdas
  (for-each
    (lambda (lam body-typer)
      (dk-have! (list 'IN lam (list 'FUN dd 'CC))
        (lambda ()
          (for-each
            (lambda (leaf)
              (dk-focus! leaf)
              (let ((g (dk-goal)))
                (cond ((dk-asm? g) (ass))
                      ((wnd-op? g 'FORALL 3)
                       (let ((w (dk-di-var!)))
                         (wnd-pz-open! z w)
                         (body-typer w)
                         (ass)))
                      (#t (error "wnd: unexpected lam-t leaf" (expression->string g))))))
            (dk-opened (lambda () (lam-t)))))))
    (list sl (wnd-kern z))
    (list (lambda (w) (wnd-cc! (list '- w z)))
          (lambda (w) (wnd-cc! (list 'recip (list '- w z))))))
  (dk-have! (list 'FORALL 'hbx_ (list 'IMPLIES (list 'IN 'hbx_ dd)
              (list '== (list sl 'hbx_) (list '+ (list id 'hbx_) (list cs 'hbx_)))))
    (lambda ()
      (let ((w (dk-di-var!)))
        (dk-lam-b!)
        (wnd-pz-open! z w)
        (dk-have! (list '= (list '- w z) (list '+ w (list '- z))) (lambda () (crs)))
        (subst (list '= (list '- w z) (list '+ w (list '- z))))
        (qrfl))))
  (dk-cite! 'holomorphic-sum dd id cs sl)
  (dk-have! (list 'FORALL 'cry_ (list 'IMPLIES (list 'IN 'cry_ dd) (list 'NOT (list '= (list sl 'cry_) 0))))
    (lambda ()
      (let ((w (dk-di-var!)))
        (wnd-pz-open! z w)
        (dk-lam-b!)
        (ass))))
  (dk-have! (list 'FORALL 'cry_ (list 'IMPLIES (list 'IN 'cry_ dd)
              (list '== (list (wnd-kern z) 'cry_) (list 'recip (list sl 'cry_)))))
    (lambda ()
      (let ((w (dk-di-var!)))
        (dk-lam-b!)
        (qrfl))))
  (dk-cite! 'holomorphic-recip-of dd sl (wnd-kern z))
  (ass))
(qed 'winding-integrand-holomorphic)

;;; ======================================================================
;;; (8) THE WINDING NUMBER IS A COMPLEX NUMBER FOR z OFF THE TRACE
;;; ======================================================================
;;; 2 pi i: in CC and non-zero
(define wnd-tpi '(* (* 2 PI) +i))
(define (wnd-tpi!)
  (wnd-rr! '(* 2 PI))
  (dk-have! '(< 0 (* 2 PI)) (lambda () (dk-ineq! '(< 0 PI))))
  (dk-cite! 'rr-pos-ne-zero '(* 2 PI))
  (wnd-cc! '(* 2 PI))
  (fact 'cc-i-in)
  (dk-have! '(NOT (= +i 0))
    (lambda ()
      (di)
      (fact 'cc-i-squared)
      (dk-have! '(= (* 0 0) -1) (lambda () (subst '(= 0 +i)) (ass)))
      (dk-have! '(NOT (= (* 0 0) -1)) (lambda () (arith)))
      (ai '(NOT (= (* 0 0) -1)))))
  (dk-cite! 'cc-mul-nonzero '(* 2 PI) +i)
  (wnd-cc! wnd-tpi)
  (wnd-cc! (list 'recip wnd-tpi)))

;;; the trace of a road off z lies in CC \ {z}
(define (wnd-trace-in-pz! z)
  (dk-have! (list 'SUBSET '(TRACE pgam a b) (wnd-pz z))
    (lambda ()
      (let ((w (subset-by-element!)))
        (fact 'trace-subset-cc 'pgam 'a 'b)
        (fact 'subset-mem-fwd '(TRACE pgam a b) 'CC w)
        (dk-have! (list 'NOT (list '= w z))
          (lambda () (di) (dk-have! (list 'IN z '(TRACE pgam a b)) (lambda () (subst (list '= z w)) (ass)))
                     (ai (dk-ctx-form (list 'NOT (list 'IN z '(TRACE pgam a b)))))))
        (wnd-pz-in! z w)))))

;;; the standing facts about the integrand on CC \ {z}: subset, typing, continuity
(define (wnd-kern-setup! z)
  (let ((dd (wnd-pz z)) (k (wnd-kern z)))
    (dk-cite! 'winding-integrand-holomorphic z)
    (dk-cite! 'holomorphic-on-in-fun dd k)
    (dk-cite! 'holomorphic-on-continuous dd k)
    (dk-cite! 'holomorphic-on-open dd k)
    (dk-cite! 'cc-open-subset-cc dd)))

(sp (make-wff '(FORALL pgam (FORALL dgam (FORALL a (FORALL b (IMPLIES (IS-ROAD pgam dgam a b)
  (FORALL wnz_ (IMPLIES (IN wnz_ CC) (IMPLIES (NOT (IN wnz_ (TRACE pgam a b)))
    (IN (WINDING pgam dgam a b wnz_) CC)))))))))))
(dk-peel!)
(fact 'is-road-is-path 'pgam 'dgam 'a 'b)
(fact 'is-path-in-fun 'pgam 'a 'b)
(wnd-kern-setup! 'wnz_)
(wnd-trace-in-pz! 'wnz_)
(dk-cite! 'line-int-in-cc (wnd-pz 'wnz_) (wnd-kern 'wnz_) 'pgam 'dgam 'a 'b)
(wnd-tpi!)
(mac 'WINDING)
(wnd-cc! (cadr (dk-goal)))
(ass)
(qed 'winding-in-cc)

;;; ======================================================================
;;; (9) THE WINDING NUMBER VANISHES ABOUT A POINT OUTSIDE A DISC CONTAINING THE
;;; ROAD (the disc case of Corollary 3.30: Cauchy on the disc for 1/(w - z))
;;; ======================================================================
(sp (make-wff '(FORALL pgam (FORALL dgam (FORALL a (FORALL b (IMPLIES (IS-ROAD pgam dgam a b)
  (IMPLIES (= (pgam b) (pgam a))
    (FORALL c (IMPLIES (IN c CC) (FORALL r (IMPLIES (IN r RR) (IMPLIES (< 0 r)
      (IMPLIES (SUBSET (TRACE pgam a b) (BALL CC-MS c r))
        (FORALL wnz_ (IMPLIES (IN wnz_ CC) (IMPLIES (NOT (IN wnz_ (BALL CC-MS c r)))
          (= (WINDING pgam dgam a b wnz_) 0))))))))))))))))))
(dk-peel!)
(let* ((z 'wnz_) (dd (wnd-pz z)) (k (wnd-kern z)) (bl '(BALL CC-MS c r)))
  (wnd-kern-setup! z)
  (dk-have! (list 'SUBSET bl dd)
    (lambda ()
      (let ((w (subset-by-element!)))
        (wnd-ball-open! 'c 'r w)
        (dk-have! (list 'NOT (list '= w z))
          (lambda () (di) (dk-have! (list 'IN z bl) (lambda () (subst (list '= z w)) (ass)))
                     (ai (dk-ctx-form (list 'NOT (list 'IN z bl))))))
        (wnd-pz-in! z w))))
  (dk-cite! 'cauchy-disc dd k 'c 'r 'pgam 'dgam 'a 'b)
  (wnd-tpi!)
  (mac 'WINDING)
  (subst (list '= (list 'LINE-INT k 'pgam 'dgam 'a 'b) 0))
  (let ((v (dk-name! (list 'recip wnd-tpi) 'CC)))
    (subst (list '= (list 'recip wnd-tpi) v))
    (crs)))
(qed 'winding-zero-outside-disc)

;;; ======================================================================
;;; (10) THE CIRCLE ABOUT ITS CENTRE: WINDING NUMBER 1 (Example 3.13 with
;;; [alpha, beta] = [0, 2 pi]: the integrand is i on the circle)
;;; ======================================================================
(define wnd-tp '(* 2 PI))
(define wnd-iv (list 'CCINT 0 wnd-tp))

;;; at a parameter y in [0, 2 pi] of the circle of centre c, radius r (r in RR, r /= 0
;;; in context): land the point's typings and the integrand's value i, in reduced form;
;;; return X = r exp(i y)
(define (wnd-circ-pt! c r y)
  (let* ((e  (list 'CC-EXP (list '* '+i y)))
         (x0 (list '* r e))
         (pt (list '+ c x0)))
    (fact 'ccint-elt-in-rr 0 wnd-tp y)
    (wnd-cc! x0)
    (dk-cite! 'cc-exp-nonzero (list '* '+i y))
    (dk-cite! 'cc-mul-nonzero r e)
    (wnd-cc! pt)
    (dk-have! (list 'NOT (list '= pt c))
      (lambda ()
        (di)
        (dk-have! (list '= x0 0)
          (lambda ()
            (dk-have! (list '= x0 (list '- pt c)) (lambda () (crs)))
            (subst (list '= x0 (list '- pt c)))
            (subst (list '= pt c))
            (crs)))
        (ai (dk-ctx-form (list 'NOT (list '= x0 0))))))
    (wnd-pz-in! c pt)
    (wnd-cc! (list 'recip x0))
    (dk-have! (list '= (list '* (list 'recip (list '- pt c)) (list '* '+i x0)) '+i)
      (lambda ()
        (dk-have! (list '= (list '- pt c) x0) (lambda () (crs)))
        (subst (list '= (list '- pt c) x0))
        (wnd-and! (list 'IN x0 'CC) (list 'NOT (list '= x0 0)))
        (dk-cite! 'cc-recip-inverse x0)
        (let ((v (dk-name! (list 'recip x0) 'CC)))
          (subst (list '= (list 'recip x0) v))
          (dk-have! (list '= (list '* x0 v) 1) (lambda () (subst (list '= v (list 'recip x0))) (ass)))
          (dk-have! (list '= (list '* v (list '* '+i x0)) (list '* '+i (list '* x0 v))) (lambda () (crs)))
          (subst (list '= (list '* v (list '* '+i x0)) (list '* '+i (list '* x0 v))))
          (subst (list '= (list '* x0 v) 1))
          (crs))))
    x0))

(sp (make-wff '(FORALL c (IMPLIES (IN c CC) (FORALL r (IMPLIES (IN r RR) (IMPLIES (< 0 r)
  (= (WINDING (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI) c) 1))))))))
(dk-peel!)
(mac 'WINDING)
(mac 'CIRCLE-PATH)
(mac 'CIRCLE-DERIV)
(let* ((g   (dk-goal))
       (lint (caddr (cadr g)))
       (k   (cadr lint)) (pp (caddr lint)) (dp (cadddr lint))
       (body (list '* (list k (list pp 'pat_)) (list dp 'pat_)))
       (rel (list 'VNB-LAMBDA 'pat_ wnd-iv (list 'real-part body)))
       (iml (list 'VNB-LAMBDA 'pat_ wnd-iv (list 'imag-part body)))
       (g1  (list 'VNB-LAMBDA 'wns_ wnd-iv '(+ 0 (* 0 wns_))))
       (g2  (list 'VNB-LAMBDA 'wns_ wnd-iv '(+ 0 (* 1 wns_)))))
  (fact 'rr-zero-in) (fact 'rr-one-in)
  (wnd-rr! wnd-tp)
  (dk-have! (list '< 0 wnd-tp) (lambda () (dk-ineq! '(< 0 PI))))
  (fact 'rr-is-set)
  (fact 'ccint-subset-rr 0 wnd-tp)
  (fact 'subclass-of-set-is-set wnd-iv 'RR)
  (fact 'rr-subset-cc 'r)
  (dk-have! '(NOT (= r 0)) (lambda () (dk-cite! 'rr-pos-ne-zero 'r) (ass)))
  (fact 'cc-i-in)
  ;; real-part(i) = 0, imag-part(i) = 1
  (wnd-cc! '(+ 0 (* 1 +i)))
  (dk-have! '(= +i (+ 0 (* 1 +i))) (lambda () (crs)))
  (dk-split! (dk-cite! 'cc-re-im-of '+i 0 1))
  (for-each
    (lambda (e)
      (dk-have! (list 'IN e wnd-iv)
        (lambda () (mac 'ccint-membership)
                   (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (dk-ineq! (list '< 0 wnd-tp))))))))
    (list 0 wnd-tp))
  ;; the two primitives and the two coordinate integrands
  (for-each
    (lambda (lam proj val)
      (dk-have! (list 'IN lam (list 'FUN wnd-iv 'RR))
        (lambda ()
          (dk-lam-type!
            (lambda ()
              (let ((y (dk-di-var!)))
                (if (memq proj '(real-part imag-part))
                    (begin (wnd-circ-pt! 'c 'r y)
                           (dk-lam-b!)
                           (subst (list '= (list '* (list 'recip (list '- (list '+ 'c (list '* 'r (list 'CC-EXP (list '* '+i y)))) 'c))
                                                       (list '* '+i (list '* 'r (list 'CC-EXP (list '* '+i y)))))
                                        '+i))
                           (subst (list '= (list proj '+i) val))
                           (ass))
                    (begin (fact 'ccint-elt-in-rr 0 wnd-tp y)
                           (wnd-rr! (cadr (dk-goal)))
                           (ass)))))))))
    (list rel iml g1 g2) (list 'real-part 'imag-part 'none 'none) (list 0 1 0 0))
  (for-each
    (lambda (gl pl m)
      (dk-have! (list 'FORALL 'pay_ (list 'IMPLIES (list 'IN 'pay_ wnd-iv)
                  (list '== (list gl 'pay_) (list '+ 0 (list '* m 'pay_)))))
        (lambda () (dk-di-var!) (dk-lam-b!) (qrfl)))
      (dk-have! (list 'FORALL 'pay_ (list 'IMPLIES (list 'IN 'pay_ wnd-iv) (list '== (list pl 'pay_) m)))
        (lambda ()
          (let ((y (dk-di-var!)))
            (wnd-circ-pt! 'c 'r y)
            (dk-lam-b!)
            (subst (list '= (list '* (list 'recip (list '- (list '+ 'c (list '* 'r (list 'CC-EXP (list '* '+i y)))) 'c))
                                     (list '* '+i (list '* 'r (list 'CC-EXP (list '* '+i y)))))
                         '+i))
            (subst (list '= (list (if (eqv? m 0) 'real-part 'imag-part) '+i) m))
            (qrfl))))
      (dk-cite! 'pw-affine-antiderivative 0 wnd-tp 0 m gl pl))
    (list g1 g2) (list rel iml) (list 0 1))
  (subst (dk-cite! 'line-int-value k pp dp 0 wnd-tp g1 g2))
  (dk-lam-b!)
  (begin
    (wnd-tpi!)
    (dk-have! (list '= (caddr (cadr (dk-goal))) wnd-tpi) (lambda () (crs)))
    (subst (list '= (caddr (cadr (dk-goal))) wnd-tpi))
    (wnd-and! (list 'IN wnd-tpi 'CC) (list 'NOT (list '= wnd-tpi 0)))
    (dk-cite! 'cc-recip-inverse wnd-tpi)
    (wnd-and! (list 'IN (list 'recip wnd-tpi) 'CC) (list 'IN wnd-tpi 'CC))
    (dk-cite! 'cc-mul-comm (list 'recip wnd-tpi) wnd-tpi)
    (subst (list '= (list '* (list 'recip wnd-tpi) wnd-tpi) (list '* wnd-tpi (list 'recip wnd-tpi))))
    (ass)))
(qed 'winding-circle-center)

;;; ======================================================================
;;; (11) THE IMAGE OF A ROAD UNDER A HOLOMORPHIC MAP IS A ROAD
;;; (f holomorphic on U with a CONTINUOUS derivative df: (f o gamma, (df o gamma) gamma')
;;; is a road).  The proof is line-int-fundamental.scm's proof of Proposition 3.2 up to
;;; the primitives (its lfn- helpers copied as wnr-: that file is not ours), followed by
;;; the assembly of the six conjuncts of IS-ROAD.
;;; ======================================================================
(define wnr-nfc '(NF-METRIC-SPACE CC-NORMED-FIELD))

(define (wnr-head g) (and (pair? g) (car g)))
;;; the base facts about the two spellings of the complex plane.
(define (wnr-cc-setup!)
  (fact 'cc-is-normed-field)
  (fact 'cc-is-metric-space)
  (fact 'nf-cc-is-metric-space)
  (fact 'nf-cc-agree-pts)
  (fact 'nf-cc-agree-dist)
  (fact 'ms-agree-pts-sym 'CC-MS wnr-nfc)
  (fact 'ms-agree-dist-sym 'CC-MS wnr-nfc)
  (fact 'cc-nf-carr)
  (dk-have! '(== (PTS CC-MS) CC) (lambda () (slot 'PTS) (qrfl))))

(define (wnr-cite! pred what . args)
  (let ((r (apply dk-fact! args)))
    (if (not (pred r))
        (error (string-append "wnr-cite!: expected " what ", landed")
               (expression->string r)))
    r))
(define (wnr-and! a b)
  (dk-have! (list 'AND a b) (lambda () (dk-conj-close! dk-ass!))))
(define (wnr-lam-b-if!) (if (dk--redex? (dk-goal)) (dk-lam-b!)))
(define wnr-cc '(CCINT a b))
(define wnr-scc (list 'SUBSPACE-MS 'RR-MS wnr-cc))
(define (wnr-plam body) (list 'VNB-LAMBDA 'pat_ wnr-cc body))
(define wnr-pgr (wnr-plam '(real-part (pgam pat_))))
(define wnr-pgi (wnr-plam '(imag-part (pgam pat_))))
(define wnr-pdr (wnr-plam '(real-part (dgam pat_))))
(define wnr-pdi (wnr-plam '(imag-part (dgam pat_))))
(define wnr-pfr (wnr-plam '(real-part (f (pgam pat_)))))
(define wnr-pfi (wnr-plam '(imag-part (f (pgam pat_)))))

;;; the road and its image: Q = f o gamma, DQ = (df o gamma) * dgamma
(define wnr-q (wnr-plam '(f (pgam pat_))))
(define wnr-dq (wnr-plam '(* (df (pgam pat_)) (dgam pat_))))
(sp (make-wff (wnd-all '(u f df pgam dgam a b)
  (wnd-imps (list '(HOLOMORPHIC-ON u f) '(IN df (FUN u CC))
                  '(FORALL hbz_ (IMPLIES (IN hbz_ u) (IS-DIFF-ON CC-NORMED-FIELD u f hbz_ (df hbz_))))
                  (wnd-cont 'u 'df)
                  '(IS-ROAD pgam dgam a b) '(SUBSET (TRACE pgam a b) u))
    (list 'IS-ROAD wnr-q wnr-dq 'a 'b)))))
(dk-peel!)
(define wnr-dfu
  (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL) (dk-contains? fm 'IS-DIFF-ON)))
           "the derivative of f on u"))
(wnr-cc-setup!)
(fact 'rr-is-metric-space)
(fact 'rr-is-set)
(dk-have! '(== (PTS RR-MS) RR) (lambda () (slot 'PTS) (qrfl)))
(fact 'holomorphic-on-in-fun 'u 'f)
(fact 'holomorphic-on-open 'u 'f)
(dk-project! (list 'SUBSET 'u (list 'PTS wnr-nfc)) 'IS-OPEN (list 'IS-OPEN wnr-nfc 'u))
(dk-have! '(SUBSET u CC)
  (lambda ()
    (subst '(= CC (PTS CC-MS)))
    (subst (list '= '(PTS CC-MS) (list 'PTS wnr-nfc)))
    (ass)))
(fact 'is-road-is-path 'pgam 'dgam 'a 'b)
(fact 'is-path-in-fun 'pgam 'a 'b)
(fact 'is-road-dgam-in-fun 'pgam 'dgam 'a 'b)
(dk-split! (dk-fact! 'is-path-endpoints 'pgam 'a 'b))
(dk-split-all!)
(define wnr-pcont (dk-fact! 'is-path-continuous 'pgam 'a 'b))
(fact 'is-road-re-antiderivative 'pgam 'dgam 'a 'b)
(fact 'is-road-im-antiderivative 'pgam 'dgam 'a 'b)
(fact 'ccint-subset-rr 'a 'b)
(fact 'subclass-of-set-is-set wnr-cc 'RR)
(fact 'ooint-subset-ccint 'a 'b)
(dk-have! (list 'SUBSET wnr-cc '(PTS RR-MS)) (lambda () (subst '(== (PTS RR-MS) RR)) (ass)))
(fact 'subspace-is-metric-space 'RR-MS wnr-cc)
(fact 'subspace-pts 'RR-MS wnr-cc)
(fact 'rr-leq-reflexive 'a)
(fact 'rr-leq-reflexive 'b)
(fact 'rr-lt-implies-le 'a 'b)
(define (wnr-endpoint! z)
  (dk-have! (list 'IN z wnr-cc)
    (lambda () (mac 'ccint-membership) (dk-conj-close! dk-ass!))))
(wnr-endpoint! 'a)
(wnr-endpoint! 'b)

;;; the trace lies in u, pointwise.
(dk-have! (list 'FORALL 'msy_ (list 'IMPLIES (list 'IN 'msy_ wnr-cc) '(IN (pgam msy_) u)))
  (lambda ()
    (let ((y (dk-di-var!)))
      (fact 'trace-value-in 'pgam 'a 'b y)
      (fact 'subset-mem-fwd '(TRACE pgam a b) 'u (list 'pgam y))
      (ass))))
(define wnr-pgu
  (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL) (dk-contains? fm 'msy_)
                             (dk-contains? fm '(pgam msy_))))
           "the trace lies in u"))
(define (wnr-pt! y)
  (fact 'fun-apply-type-c 'pgam wnr-cc 'CC y)
  (if (not (dk-ctx-form (list 'IN (list 'pgam y) 'u))) (dk-apply! wnr-pgu y))
  (fact 'fun-apply-type-c 'f 'u 'CC (list 'pgam y))
  (fact 'fun-apply-type-c 'df 'u 'CC (list 'pgam y))
  (fact 'fun-apply-type-c 'dgam wnr-cc 'CC y)
  (fact 'real-part-in-rr (list 'f (list 'pgam y)))
  (fact 'imag-part-in-rr (list 'f (list 'pgam y)))
  (wnr-and! (list 'IN (list 'df (list 'pgam y)) 'CC) (list 'IN (list 'dgam y) 'CC))
  (fact 'cc-mul-closed (list 'df (list 'pgam y)) (list 'dgam y))
  (fact 'real-part-in-rr (list '* (list 'df (list 'pgam y)) (list 'dgam y)))
  (fact 'imag-part-in-rr (list '* (list 'df (list 'pgam y)) (list 'dgam y))))
(wnr-pt! 'a)
(wnr-pt! 'b)

;;; the coordinates of F = f o gamma are functions on [a,b].
(define (wnr-ptype! claim)
  (dk-have! claim
    (lambda ()
      (dk-lam-type! (lambda () (let ((y (dk-di-var!))) (wnr-pt! y) (wnr-lam-b-if!) (ass))) ass))))
(wnr-ptype! (list 'IN wnr-pfr (list 'FUN wnr-cc 'RR)))
(wnr-ptype! (list 'IN wnr-pfi (list 'FUN wnr-cc 'RR)))

;;; ---- F = f o gamma is continuous on [a,b], coordinatewise.
(dk-have! (list 'FORALL 'msy_ (list 'IMPLIES (list 'IN 'msy_ (list 'PTS wnr-scc))
            '(IN (pgam msy_) u)))
  (lambda ()
    (let ((y (dk-di-var!)))
      (dk-have! (list 'IN y wnr-cc)
        (lambda () (subst (list '= wnr-cc (list 'PTS wnr-scc))) (ass)))
      (dk-apply! wnr-pgu y)
      (ass))))
(dk-have! '(IN pgam (FUN (PTS (SUBSPACE-MS RR-MS (CCINT a b))) CC))
  (lambda () (subst (list '== (list 'PTS wnr-scc) wnr-cc)) (ass)))
(define (wnr-f-cont! y)
  (wnr-pt! y)
  (dk-have! (list 'IN y (list 'PTS wnr-scc))
    (lambda () (subst (list '== (list 'PTS wnr-scc) wnr-cc)) (ass)))
  (dk-apply! wnr-pcont y)
  (dk-apply! wnr-dfu (list 'pgam y))
  (fact 'diff-on-implies-continuous 'CC-NORMED-FIELD 'u 'f (list 'pgam y)
        (list 'df (list 'pgam y)))
  (let* ((r (wnr-cite! (lambda (r) (and (pair? r) (eq? (car r) 'IS-CONTINUOUS-AT)))
                       "the continuity of f o gamma"
                       'cc-compose-continuous-at wnr-scc 'u 'pgam 'f y))
         (c (list-ref r 3)))
    (dk-have! (list 'IN c (list 'FUN (list 'PTS wnr-scc) 'CC))
      (lambda ()
        (fact 'ms-pts-is-set wnr-scc)
        (dk-lam-type! (lambda () (let ((z (dk-di-var!)))
                 (dk-have! (list 'IN z wnr-cc)
                   (lambda () (subst (list '= wnr-cc (list 'PTS wnr-scc))) (ass)))
                 (wnr-pt! z)
                 (ass))) ass)))
    (dk-have! (list 'IN wnr-pfr (list 'FUN (list 'PTS wnr-scc) 'RR))
      (lambda () (subst (list '== (list 'PTS wnr-scc) wnr-cc)) (ass)))
    (dk-have! (list 'IN wnr-pfi (list 'FUN (list 'PTS wnr-scc) 'RR))
      (lambda () (subst (list '== (list 'PTS wnr-scc) wnr-cc)) (ass)))
    (for-each
     (lambda (proj fl)
       (dk-have! (list 'FORALL 'u_ (list 'IMPLIES (list 'IN 'u_ (list 'PTS wnr-scc))
                   (list '= (list proj (list c 'u_)) (list fl 'u_))))
         (lambda ()
           (let ((z (dk-di-var!)))
             (dk-have! (list 'IN z wnr-cc)
               (lambda () (subst (list '= wnr-cc (list 'PTS wnr-scc))) (ass)))
             (wnr-pt! z)
             (dk-lam-b!)
             (rfl)))))
     '(real-part imag-part) (list wnr-pfr wnr-pfi))
    (let ((iff (wnr-cite! (lambda (r) (and (pair? r) (eq? (car r) 'IFF)))
                          "the coordinate iff for f o gamma"
                          'cc-continuous-at-iff-coords wnr-scc c wnr-pfr wnr-pfi y)))
      (cons iff r))))
;;; ONE lane for both coordinates.  Run twice, the second run's `dk-only!'
;;; weakens onto the sequent the first run grounded (the eigenvariable is the
;;; same `icp_' in both lanes), the focus drifts to the MAIN leaf and the
;;; weakening continues there -- the `dk-only!' defect CLAUDE.md lists.
(define wnr-both-cont
  (list 'FORALL 'icp_ (list 'IMPLIES (list 'IN 'icp_ wnr-cc)
    (list 'AND (list 'IS-CONTINUOUS-AT wnr-scc 'RR-MS wnr-pfr 'icp_)
               (list 'IS-CONTINUOUS-AT wnr-scc 'RR-MS wnr-pfi 'icp_)))))
(dk-have! wnr-both-cont
  (lambda ()
    (let* ((y (dk-di-var!))
           (ir (wnr-f-cont! y)))
      ;; the goal IS the conjunction the iff delivers
      (dk-only! (car ir) (cdr ir))
      (prop))))
(define (wnr-cont-on! fl)
  (dk-have! (list 'IS-CONTINUOUS-ON fl wnr-cc)
    (lambda ()
      (mac 'IS-CONTINUOUS-ON)
      (dk-conj-close!
       (lambda ()
         (if (not (eq? (wnr-head (dk-goal)) 'FORALL))
             (ass)
             (let ((y (dk-di-var!)))
               (dk-split-all! (list (dk-apply! (dk-ctx-form wnr-both-cont) y)))
               (ass))))))))
(wnr-cont-on! wnr-pfr)
(wnr-cont-on! wnr-pfi)

;;; ---- the goal, unfolded: CC-INT's two coordinate integrals.
;;; ---- the two coordinates of DQ, in the shape IS-ROAD reads them.
(define wnr-ir (wnr-plam (list 'real-part (list wnr-dq 'pat_))))
(define wnr-ii (wnr-plam (list 'imag-part (list wnr-dq 'pat_))))
(wnr-ptype! (list 'IN wnr-ir (list 'FUN wnr-cc 'RR)))
(wnr-ptype! (list 'IN wnr-ii (list 'FUN wnr-cc 'RR)))

;;; ---- the exceptional set: the union of the two of the road.
(define wnr-s1 (dk-skolem! (dk-fact! 'primitive-exceptional-set wnr-pgr wnr-pdr 'a 'b)))
(dk-split-all!)
(define wnr-d1 (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL)
                                          (dk-contains? fm 'HAS-DERIV-AT)
                                          (dk-contains? fm wnr-s1)))
                        "the derivative universal of re gamma"))
(define wnr-s2 (dk-skolem! (dk-fact! 'primitive-exceptional-set wnr-pgi wnr-pdi 'a 'b)))
(dk-split-all!)
(define wnr-d2 (dk-pick (lambda (fm) (and (pair? fm) (eq? (car fm) 'FORALL)
                                          (dk-contains? fm 'HAS-DERIV-AT)
                                          (dk-contains? fm wnr-s2)))
                        "the derivative universal of im gamma"))
(define wnr-un (list 'UNION wnr-s1 wnr-s2))
(fact 'countable-union-2 wnr-s1 wnr-s2)
(dk-have! (list 'SUBSET wnr-un wnr-cc)
  (lambda ()
    (let* ((w  (subset-by-element!))
           (um (dk-fact! 'union-membership wnr-s1 wnr-s2 w)))
      (fact 'subset-mem-fwd wnr-s1 wnr-cc w)
      (fact 'subset-mem-fwd wnr-s2 wnr-cc w)
      (dk-only! um
                (list 'IN w wnr-un)
                (list 'IMPLIES (list 'IN w wnr-s1) (list 'IN w wnr-cc))
                (list 'IMPLIES (list 'IN w wnr-s2) (list 'IN w wnr-cc)))
      (prop))))

;;; ---- THE DERIVATIVE of each coordinate of F, off the union: the chain rule.
(define wnr-both-deriv
  (list 'FORALL 'lft_ (list 'IMPLIES '(IN lft_ (OOINT a b))
    (list 'IMPLIES (list 'NOT (list 'IN 'lft_ wnr-un))
      (list 'AND (list 'HAS-DERIV-AT wnr-pfr 'lft_ (list wnr-ir 'lft_))
                 (list 'HAS-DERIV-AT wnr-pfi 'lft_ (list wnr-ii 'lft_)))))))
(dk-have! wnr-both-deriv
  (lambda ()
    (dk-peel!)
    (let* ((tv (cadr (cadr (dk-goal))))
           (tv (caddr (cadr (dk-goal))))
           (um (dk-fact! 'union-membership wnr-s1 wnr-s2 tv))
           (dt (list 'dgam tv))
           (dft (list 'df (list 'pgam tv))))
      (dk-have! (list 'AND (list 'NOT (list 'IN tv wnr-s1)) (list 'NOT (list 'IN tv wnr-s2)))
        (lambda () (dk-only! um (list 'NOT (list 'IN tv wnr-un))) (prop)))
      (dk-split-all!)
      (fact 'subset-mem-fwd '(OOINT a b) wnr-cc tv)
      (wnr-pt! tv)
      (fact 'fun-apply-type-c wnr-pdr wnr-cc 'RR tv)
      (fact 'fun-apply-type-c wnr-pdi wnr-cc 'RR tv)
      (dk-apply! wnr-d1 tv)
      (dk-apply! wnr-d2 tv)
      (fact 'real-part-in-rr dt)
      (fact 'imag-part-in-rr dt)
      (for-each
       (lambda (gl dl pj)
         (dk-have! (list '= (list dl tv) (list pj dt)) (lambda () (dk-lam-b!) (rfl)))
         (dk-have! (list 'HAS-DERIV-AT gl tv (list pj dt))
           (lambda () (subst (list '= (list pj dt) (list dl tv))) (ass))))
       (list wnr-pgr wnr-pgi) (list wnr-pdr wnr-pdi) '(real-part imag-part))
      (dk-apply! wnr-pcont tv)
      (dk-apply! wnr-dfu (list 'pgam tv))
      (dk-split-all!
       (list (dk-apply! (dk-fact! 'holomorphic-chain wnr-cc 'pgam tv) 'u 'f dft dt)))
      (for-each
       (lambda (il pj)
         (dk-have! (list '= (list il tv) (list pj (list '* dft dt)))
           (lambda () (dk-lam-b!) (rfl))))
       (list wnr-ir wnr-ii) '(real-part imag-part))
      (subst (list '= (list wnr-ir tv) (list 'real-part (list '* dft dt))))
      (subst (list '= (list wnr-ii tv) (list 'imag-part (list '* dft dt))))
      (dk-conj-close! dk-ass!))))
(define (wnr-deriv-univ! fl il)
  (dk-have! (list 'FORALL 'lft_ (list 'IMPLIES '(IN lft_ (OOINT a b))
              (list 'IMPLIES (list 'NOT (list 'IN 'lft_ wnr-un))
                    (list 'HAS-DERIV-AT fl 'lft_ (list il 'lft_)))))
    (lambda ()
      (dk-peel!)
      (let ((tv (caddr (dk-goal))))
        (dk-split-all! (list (dk-apply! (dk-ctx-form wnr-both-deriv) tv)))
        (ass)))))
(wnr-deriv-univ! wnr-pfr wnr-ir)
(wnr-deriv-univ! wnr-pfi wnr-ii)

;;; ---- each coordinate of F is a primitive (IS-PRIMITIVE) of the
;;; corresponding coordinate of the integrand.
(define (wnr-pw! fl il)
  (dk-have! (list 'IS-PRIMITIVE fl il 'a 'b)
    (lambda ()
      (mac 'IS-PRIMITIVE)
      (dk-conj-close!
       (lambda ()
         (if (not (eq? (wnr-head (dk-goal)) 'FORSOME))
             (ass)
             (begin
               (ew wnr-un)
               (dk-conj-close! dk-ass!))))))))
(wnr-pw! wnr-pfr wnr-ir)
(wnr-pw! wnr-pfi wnr-ii)
;;; ---- ASSEMBLY: the six conjuncts of IS-ROAD(Q, DQ, a, b).
(define wnr-qr (wnr-plam (list 'real-part (list wnr-q 'pat_))))
(define wnr-qi (wnr-plam (list 'imag-part (list wnr-q 'pat_))))
(dk-have! (list 'IN wnr-q (list 'FUN wnr-cc 'CC))
  (lambda () (dk-lam-type! (lambda () (let ((y (dk-di-var!))) (wnr-pt! y) (wnr-lam-b-if!) (ass))) ass)))
(for-each
  (lambda (ql pl)
    (wnr-ptype! (list 'IN ql (list 'FUN wnr-cc 'RR)))
    (dk-fun-ext! ql pl wnr-cc 'RR #f #f
                 (lambda (v) (wnr-pt! v) (if (not (dk-lam-b!)) (rfl)))))
  (list wnr-qr wnr-qi) (list wnr-pfr wnr-pfi))
;; the path: its coordinates are those of f o gamma
(for-each
  (lambda (proj pl)
    (dk-have! (list 'FORALL 'pay_ (list 'IMPLIES (list 'IN 'pay_ wnr-cc)
                (list '= (list proj (list wnr-q 'pay_)) (list pl 'pay_))))
      (lambda () (let ((v (dk-di-var!))) (wnr-pt! v) (if (not (dk-lam-b!)) (rfl))))))
  '(real-part imag-part) (list wnr-pfr wnr-pfi))
(dk-cite! 'is-path-of-coords 'a 'b wnr-q wnr-pfr wnr-pfi)
;; the derivative: a function on [a, b], regulated coordinatewise
(dk-cite! 'line-int-integrand-in-fun 'a 'b 'pgam 'dgam 'df 'u)
(dk-split-all! (list (dk-cite! 'road-integrand-regulated 'u 'df 'pgam 'dgam 'a 'b)))
(for-each
  (lambda (il proj)
    (let ((gl (wnr-plam (list proj '(* (df (pgam pat_)) (dgam pat_))))))
      (dk-have! (list 'FORALL 'rgz_ (list 'IMPLIES (list 'IN 'rgz_ wnr-cc) (list '== (list il 'rgz_) (list gl 'rgz_))))
        (lambda () (let ((v (dk-di-var!))) (wnr-pt! v) (if (not (dk-lam-b!)) (qrfl)))))
      (dk-cite! 'regulated-on-congruence il gl 'a 'b)))
  (list wnr-ir wnr-ii) '(real-part imag-part))
(mac 'IS-ROAD)
(dk-conj-close!
  (lambda ()
    (let ((g (dk-goal)))
      (cond ((dk-asm? g) (ass))
            ((and (pair? g) (eq? (car g) 'IS-PRIMITIVE))
             (if (dk-contains? g wnr-qr) (subst (list '= wnr-qr wnr-pfr)))
             (if (dk-contains? g wnr-qi) (subst (list '= wnr-qi wnr-pfi)))
             (ass))
            (#t (error "road-holomorphic-image: unexpected conjunct" (expression->string g)))))))
(qed 'road-holomorphic-image)

;;; ======================================================================
;;; (12) THE CIRCLE IS A ROAD (Example 3.13: "gamma is a smooth path and
;;; gamma'(t) = R i exp(i t)").  The segment <0, 2 pi i> on [0, 1] (segment-is-road),
;;; carried by F(w) = r exp(1 w) + c exp(0 w) (cex-exp-comb-deriv: F' is of the same
;;; family, so it is continuous) through road-holomorphic-image, then reparametrised onto
;;; [0, 2 pi] by t |-> t / (2 pi) (road-affine-reparam).
;;; ======================================================================
(define (wnd-in-ccint! v lo hi prems)
  (dk-have! (list 'IN v (list 'CCINT lo hi))
    (lambda () (mac 'ccint-membership)
               (dk-conj-close! (lambda () (if (dk-asm? (dk-goal)) (ass) (apply dk-ineq! prems)))))))

;; at a parameter z of [0, 2 pi]: s = 0 + v z lies in [0, 1], and the values
(define (wnd-cr-pt! v vt tt z)
  (let* ((s  (list '+ 0 (list '* v z)))
         (x  (list '+ 0 (list '* s tt)))
         (ez (list 'CC-EXP (list '* '+i z))))
    (fact 'ccint-elt-in-rr 0 wnd-tp z)
    (dk-have! (list 'AND (list '<= 0 z) (list '<= z wnd-tp))
      (lambda () (mac-h 'ccint-membership (list 'IN z wnd-iv)) (dk-split-all!) (dk-conj-close! dk-ass!)))
    (dk-split-all!)
    (wnd-rr! s)
    (dk-have! (list '<= 0 v) (lambda () (dk-ineq! (list '< 0 v))))
    (wnd-and! (list 'IN v 'RR) (list 'IN z 'RR))
    (wnd-and! (list '<= 0 v) (list '<= 0 z))
    (dk-cite! 'rr-leq-mul-nonneg v z)
    (dk-cite! 'rr-mul-le-right z wnd-tp v)
    (wnd-rr! (list '* v z)) (wnd-rr! (list '* z v)) (wnd-rr! (list '* wnd-tp v))
    (dk-have! (list '= (list '* z v) (list '* v z)) (lambda () (crs)))
    (dk-have! (list '= (list '* wnd-tp v) vt) (lambda () (crs)))
    (wnd-in-ccint! s 0 1 (list (list '<= 0 (list '* v z)) (list '<= (list '* z v) (list '* wnd-tp v))
                               (list '= (list '* z v) (list '* v z)) (list '= (list '* wnd-tp v) vt)
                               (list '= vt 1)))
    (wnd-cc! x) (wnd-cc! (list '* 1 x)) (wnd-cc! (list '* 0 x))
    (wnd-cc! (list 'CC-EXP (list '* 1 x))) (wnd-cc! (list 'CC-EXP (list '* 0 x)))
    (wnd-cc! ez) (wnd-cc! (list '* '+i z))
    (fact 'rr-subset-cc v)
    (dk-have! (list '= (list '* 1 x) (list '* '+i z))
      (lambda ()
        (dk-have! (list '= (list '* 1 x) (list '* vt (list '* '+i z))) (lambda () (crs)))
        (subst (list '= (list '* 1 x) (list '* vt (list '* '+i z))))
        (subst (list '= vt 1))
        (crs)))
    (dk-congr! (list '= (list '* 1 x) (list '* '+i z)) (lambda (w) (list 'CC-EXP w)))
    (dk-have! (list '= (list '* 0 x) 0) (lambda () (crs)))
    (fact 'cc-exp-zero)
    (dk-congr! (list '= (list '* 0 x) 0) (lambda (w) (list 'CC-EXP w)))
    (list s x ez)))

(define (wnd-cr-close! lhs rhs)
  ;; lhs == rhs after the exp rewrites: by crs, with v (2 pi) = 1
  (let ((eq (list '= rhs lhs)))
    (dk-have! eq (lambda () (crs)))
    (subst eq)
    (qrfl)))

(sp (make-wff '(FORALL c (IMPLIES (IN c CC) (FORALL r (IMPLIES (IN r RR)
  (IS-ROAD (CIRCLE-PATH c r) (CIRCLE-DERIV c r) 0 (* 2 PI))))))))
(dk-peel!)
(mac 'CIRCLE-PATH)
(mac 'CIRCLE-DERIV)
(let* ((g   (dk-goal))
       (cp  (cadr g)) (cd (caddr g))
       (tt  wnd-tpi)
       (sg  (list 'VNB-LAMBDA 'psx_ '(CCINT 0 1) (list '+ 0 (list '* 'psx_ tt))))
       (dsg (list 'VNB-LAMBDA 'psx_ '(CCINT 0 1) tt))
       (ca  '(* r 1)) (cb '(* c 0))
       (ff  (list 'VNB-LAMBDA 'cexy_ 'CC (list '+ (list '* 'r '(CC-EXP (* 1 cexy_))) (list '* 'c '(CC-EXP (* 0 cexy_))))))
       (df  (list 'VNB-LAMBDA 'cexy_ 'CC (list '+ (list '* ca '(CC-EXP (* 1 cexy_))) (list '* cb '(CC-EXP (* 0 cexy_))))))
       (q   (list 'VNB-LAMBDA 'pat_ '(CCINT 0 1) (list ff (list sg 'pat_))))
       (dq  (list 'VNB-LAMBDA 'pat_ '(CCINT 0 1) (list '* (list df (list sg 'pat_)) (list dsg 'pat_)))))
  (fact 'rr-zero-in) (fact 'rr-one-in) (fact 'cc-zero-in) (fact 'cc-i-in)
  (wnd-tpi!)
  (wnd-cc! 1)
  (fact 'rr-subset-cc 'r)
  (wnd-cc! ca) (wnd-cc! cb)
  ;; the segment
  (dk-cite! 'segment-is-road 0 tt)
  (fact 'is-road-is-path sg dsg 0 1)
  (fact 'is-path-in-fun sg 0 1)
  (dk-cite! 'trace-subset-cc sg 0 1)
  ;; F and its derivative
  (dk-have! (list 'FORALL 'hbz_ (list 'IMPLIES '(IN hbz_ CC) (list 'IS-DIFF-ON 'CC-NORMED-FIELD 'CC ff 'hbz_ (list df 'hbz_))))
    (lambda ()
      (let* ((z (dk-di-var!))
             (val (list '+ (list '* 'r (list '* 1 (list 'CC-EXP (list '* 1 z))))
                           (list '* 'c (list '* 0 (list 'CC-EXP (list '* 0 z)))))))
        (dk-cite! 'cex-exp-comb-deriv 'r 'c 1 0 z)
        (wnd-cc! (list 'CC-EXP (list '* 1 z))) (wnd-cc! (list 'CC-EXP (list '* 0 z)))
        (dk-lam-b!)
        (dk-have! (list '= (list-ref (dk-goal) 5) val) (lambda () (crs)))
        (subst (list '= (list-ref (dk-goal) 5) val))
        (ass))))
  (let ((d1 (dk-cite! 'cex-exp-comb-deriv 'r 'c 1 0 0)))
    (dk-cite! 'diff-on-open 'CC-NORMED-FIELD 'CC ff 0 (list-ref d1 5)))
  (dk-have! (list 'HOLOMORPHIC-ON 'CC ff)
    (lambda ()
      (mac 'HOLOMORPHIC-ON)
      (dk-conj-close!
        (lambda ()
          (let ((g (dk-goal)))
            (cond ((dk-asm? g) (ass))
                  ((wnd-op? g 'IN 3)
                   (fact 'cc-is-set)
                   (dk-lam-type! (lambda () (let ((z (dk-di-var!))) (wnd-cc! (cadr (dk-goal))) (ass))) ass))
                  (#t (let ((z (dk-di-var!)))
                        (dk-apply! (dk-ctx-form (list 'FORALL 'hbz_ (list 'IMPLIES '(IN hbz_ CC)
                                       (list 'IS-DIFF-ON 'CC-NORMED-FIELD 'CC ff 'hbz_ (list df 'hbz_)))))
                                   z)
                        (ew (list df z))
                        (ass)))))))))
  (fact 'cc-is-set)
  (dk-have! (list 'IN df '(FUN CC CC))
    (lambda () (dk-lam-type! (lambda () (let ((z (dk-di-var!))) (wnd-cc! (cadr (dk-goal))) (ass))) ass)))
  (dk-have! (wnd-cont 'CC df)
    (lambda ()
      (let* ((z (dk-di-var!))
             (d1 (dk-cite! 'cex-exp-comb-deriv ca cb 1 0 z)))
        (dk-cite! 'diff-on-implies-continuous 'CC-NORMED-FIELD 'CC df z (list-ref d1 5))
        (ass))))
  (dk-cite! 'road-holomorphic-image 'CC ff df sg dsg 0 1)
  ;; the reparametrisation t |-> v t, v = 1 / (2 pi)
  (dk-have! (list 'NOT (list '= wnd-tp 0)) (lambda () (dk-cite! 'rr-pos-ne-zero wnd-tp) (ass)))
  (wnd-and! (list 'IN wnd-tp 'RR) (list 'NOT (list '= wnd-tp 0)))
  (dk-cite! 'rr-recip-closed wnd-tp)
  (dk-cite! 'rr-recip-inverse wnd-tp)
  (dk-cite! 'rr-recip-pos wnd-tp)
  (let* ((v (dk-name! (list 'recip wnd-tp)))
         (vt (list '* v wnd-tp)))
    (dk-have! (list '< 0 v) (lambda () (subst (list '= v (list 'recip wnd-tp))) (ass)))
    (dk-have! (list '= vt 1)
      (lambda () (dk-have! (list '= vt (list '* wnd-tp v)) (lambda () (crs)))
                 (subst (list '= vt (list '* wnd-tp v))) (subst (list '= v (list 'recip wnd-tp))) (ass)))
    (dk-have! (list '= (list '+ 0 (list '* v 0)) 0) (lambda () (crs)))
    (dk-have! (list '= (list '+ 0 (list '* v wnd-tp)) 1) (lambda () (subst (list '= (list '* v wnd-tp) 1)) (crs)))
    (wnd-rr! vt)
    (fact 'rr-is-set)
    (fact 'ccint-subset-rr 0 wnd-tp)
    (fact 'subclass-of-set-is-set wnd-iv 'RR)
    (dk-cite! 'road-affine-reparam 0 1 0 wnd-tp v 0)
    (dk-have! (list 'IN cp (list 'FUN wnd-iv 'CC))
      (lambda () (dk-lam-type! (lambda () (let ((z (dk-di-var!))) (wnd-cr-pt! v vt tt z) (wnd-cc! (cadr (dk-goal))) (ass))) ass)))
    (dk-have! (list 'IN cd (list 'FUN wnd-iv 'CC))
      (lambda () (dk-lam-type! (lambda () (let ((z (dk-di-var!))) (wnd-cr-pt! v vt tt z) (wnd-cc! (cadr (dk-goal))) (ass))) ass)))
    (dk-have! (list 'FORALL 'lrpz_ (list 'IMPLIES (list 'IN 'lrpz_ wnd-iv)
                (list '== (list cp 'lrpz_) (list q (list '+ 0 (list '* v 'lrpz_))))))
      (lambda ()
        (let* ((z (dk-di-var!)) (pr (wnd-cr-pt! v vt tt z)) (x (cadr pr)) (ez (caddr pr)))
          (dk-lam-b!)
          (subst (list '= (list 'CC-EXP (list '* 1 x)) ez))
          (subst (list '= (list 'CC-EXP (list '* 0 x)) '(CC-EXP 0)))
          (subst '(= (CC-EXP 0) 1))
          (wnd-cr-close! (cadr (dk-goal)) (caddr (dk-goal))))))
    (dk-have! (list 'FORALL 'lrpz_ (list 'IMPLIES (list 'IN 'lrpz_ wnd-iv)
                (list '== (list cd 'lrpz_) (list '* v (list dq (list '+ 0 (list '* v 'lrpz_)))))))
      (lambda ()
        (let* ((z (dk-di-var!)) (pr (wnd-cr-pt! v vt tt z)) (x (cadr pr)) (ez (caddr pr)))
          (dk-lam-b!)
          (subst (list '= (list 'CC-EXP (list '* 1 x)) ez))
          (subst (list '= (list 'CC-EXP (list '* 0 x)) '(CC-EXP 0)))
          (subst '(= (CC-EXP 0) 1))
          (let* ((rhs (caddr (dk-goal)))
                 (mid (list '* vt (list '* '+i (list '* 'r ez)))))
            (dk-have! (list '= rhs mid) (lambda () (crs)))
            (subst (list '= rhs mid))
            (subst (list '= vt 1))
            (wnd-cr-close! (cadr (dk-goal)) (caddr (dk-goal)))))))
    (dk-cite! 'road-affine-reparam 0 1 0 wnd-tp v 0 q dq cp cd)
    (ass)))
(qed 'circle-is-road)
