(verify-proofs!)
(display "\n## deriv-identity ##\n")
(sp '(FORALL a (IMPLIES (IN a RR) (IS-DIFF-AT (VNB-LAMBDA x x) a 1))))
(grind) (mac 'IS-DIFF-AT) (fact 'rr-one-in)
(di) (lam-t) (grind) (ass)
(di) (ass)
(di) (ass)
(ew '(VNB-LAMBDA x 1))
(di) (lam-t) (grind) (ass)
(di) (bc* 'const-continuous-at () (ass) (ass))
(di) (lam-b) (rfl)
(grind) (lam-b) (crs)
(display "identity DONE? ") (display (proof-done? *ps*)) (newline)

(display "\n## deriv-const ##\n")
(sp '(FORALL c (FORALL a (IMPLIES (AND (IN c RR) (IN a RR)) (IS-DIFF-AT (VNB-LAMBDA x c) a 0)))))
(grind) (mac 'IS-DIFF-AT) (fact 'rr-zero-in)
(di) (lam-t) (grind) (ass)
(di) (ass)
(di) (ass)
(ew '(VNB-LAMBDA x 0))
(di) (lam-t) (grind) (ass)
(di) (bc* 'const-continuous-at () (ass) (ass))
(di) (lam-b) (rfl)
(grind) (lam-b) (crs)
(display "const DONE? ") (display (proof-done? *ps*)) (newline)
