(define (gl tag) (display "  >> ") (display tag) (display ": ")
  (if (proof-done? *ps*) (display "DONE")
    (write (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))) (newline))
(sp '(FORALL a (IMPLIES (IN a RR) (IS-DIFF-AT (VNB-LAMBDA x x) a 1))))
(grind) (mac 'IS-DIFF-AT) (fact 'rr-one-in)
(di) (lam-t) (grind) (ass)
(di) (ass)
(di) (ass)
(ew '(VNB-LAMBDA x 1))
(di) (lam-t) (grind) (ass)
(di) (bc* 'const-continuous-at) (di) (ass-all) (gl "after E close")
(di) (lam-b) (rfl) (gl "after F close")
(grind) (lam-b) (crs) (gl "after G close")
