(verify-proofs!)
(define (gl tag) (display "  >> ") (display tag) (display ": ")
  (if (proof-done? *ps*) (display "DONE")
    (write (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))) (newline))
(display "\n## isolate F ##\n")
(sp '(FORALL a (IMPLIES (IN a RR) (= ((VNB-LAMBDA x 1) a) 1))))
(grind) (gl "goal")
(lam-b) (gl "after lam-b")
(rfl) (gl "after rfl")
