(define (gf) (and *ps* (not (proof-done? *ps*)) (wff-formula (sequent-node-assertion (proof-state-focus *ps*)))))
(sp '(FORALL f (== (NTH-DERIV f 1) (VNB-LAMBDA x (DERIV f x)))))
(grind)
(cut '(= 1 (succ 0))) (arith) (subst '(= 1 (succ 0)))
(fact 'nn-zero-in)
(mac 'nth-deriv-succ) (display ";; after succ: ") (write (or (gf) 'DONE)) (newline)
(mac 'nth-deriv-zero) (display ";; after zero: ") (write (or (gf) 'DONE)) (newline)
(qrfl) (display ";; nth-deriv-one DONE? ") (display (proof-done? *ps*)) (newline)
