;;; scratch-perm-inv.scm -- developing sum-ag-permutation-invariance.
;;;
;;;   n in NN, ag abelian, g,h : NN -> A(ag), phi a bijection of ORD-SEGMENT(n),
;;;   and  h(i) = g(phi(i))  for i in ORD-SEGMENT(n)
;;;     =>  SUM-AG(ag,g,n) = SUM-AG(ag,h,n).
;;;
;;; Proof: NN induction on n.
;;;   Base n=0:  both sums are E(ag)  (sum-ag-zero).
;;;   Step n->succ n:  let k = phi(n).
;;;     - sum-ag-succ:  SUM-AG(h,succ n) = MUL(SUM-AG(h,n), h(n)),  h(n)=g(k).
;;;     - sum-ag-splice-out on g at k:
;;;         SUM-AG(g,succ n) = MUL(SUM-AG(DELETE-AT g k, n), g(k))
;;;       discharging AGREE1 by delete-at-below-k, AGREE2 by delete-at-above-k.
;;;     - so the goal reduces to  SUM-AG(DELETE-AT g k, n) = SUM-AG(h, n),
;;;       which is the IH at  g' = DELETE-AT g k,  h' = h,  with induced
;;;       permutation  phi' = INVERSE-BIJ(DELETE-AT inv k, os n, os n),
;;;       inv = INVERSE-BIJ(phi, os(succ n), os(succ n)).
;;;       The agreement  h(i) = (DELETE-AT g k)(phi'(i))  holds by a
;;;       below-k / at-or-above-k case split (see notes).
(load "load.scm")

(define pinv-goal
  '(FORALL n (IMPLIES (IN n NN)
     (FORALL ag (IMPLIES (IS-ABELIAN-GROUP ag)
     (FORALL g (IMPLIES (IN g (FUN NN (A ag)))
     (FORALL h (IMPLIES (IN h (FUN NN (A ag)))
     (FORALL phi (IMPLIES (IN phi (BIJECTION (ORD-SEGMENT n) (ORD-SEGMENT n)))
     (IMPLIES (FORALL i (IMPLIES (IN i (ORD-SEGMENT n)) (= (h i) (g (phi i)))))
       (= (SUM-AG ag g n) (SUM-AG ag h n))))))))))))))

(sp (make-wff pinv-goal))
(ni)
(display "--- after (ni) ---\n") (show)

;;; ===== BASE CASE  n = 0 =====
(di) (di) (di) (di)           ; peel ag,g,h,phi + assume IS-AG/funs/bij/agree
(display "--- base: after di-peeling ---\n") (show)
(mac 'sum-ag-zero)            ; both sums -> E(ag)
(rfl)
(display "--- base: DONE ---\n") (show)

;;; ===== STEP CASE  n -> succ n =====
(define sv *fresh-counter*)
(define nv   (eigen-name 'n   sv))
(define agv  (eigen-name 'ag  (+ sv 1)))
(define gv   (eigen-name 'g   (+ sv 2)))
(define hv   (eigen-name 'h   (+ sv 3)))
(define phiv (eigen-name 'phi (+ sv 4)))
(di) (di) (di) (di) (di) (di)   ; intro n, assume IH, peel ag/g/h/phi + asms
(display "--- step: after di-peeling ---\n") (show)

;;; term abbreviations
(define osSn `(ORD-SEGMENT (succ ,nv)))
(define osn  `(ORD-SEGMENT ,nv))
(define K    `(,phiv ,nv))                       ; the spliced index
(define inv  `(INVERSE-BIJ ,phiv ,osSn ,osSn))   ; phi inverse
(define dgk  `(DELETE-AT ,gv ,K))                ; g with index K spliced out
(define dik  `(DELETE-AT ,inv ,K))               ; induced permutation
(define AGREE
  `(FORALL i (IMPLIES (IN i ,osSn) (= (,hv i) (,gv (,phiv i))))))

;;; fact 1:  succ n in NN
(cut `(IN (succ ,nv) NN))
(define u-snn (last-node))
  (ta 'nn-succ-closed)
  (inst '(FORALL n (IMPLIES (IN n NN) (IN (succ n) NN))) nv)
  (bc `(IMPLIES (IN ,nv NN) (IN (succ ,nv) NN)))
  (ass)
(refocus! u-snn)

;;; fact 2:  n in os(succ n)
(cut `(IN ,nv ,osSn))
(define u-ninSn (last-node))
  (mac 'ord-segment-nn-succ)        ; -> (OR (IN n os(n)) (= n n))
  (oi-r)
  (rfl)
(refocus! u-ninSn)

;;; fact 3:  phi in FUN(os(succ n), os(succ n))
(cut `(IN ,phiv (FUN ,osSn ,osSn)))
(define u-phifun (last-node))
  (ta 'bijection-in-fun)
  (inst `(FORALL X (FORALL Y (FORALL phi
            (IMPLIES (IN phi (BIJECTION X Y)) (IN phi (FUN X Y)))))) osSn)
  (inst `(FORALL Y (FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn Y)) (IN phi (FUN ,osSn Y))))) osSn)
  (inst `(FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn ,osSn)) (IN phi (FUN ,osSn ,osSn))))
        phiv)
  (bc `(IMPLIES (IN ,phiv (BIJECTION ,osSn ,osSn)) (IN ,phiv (FUN ,osSn ,osSn))))
  (ass)
(refocus! u-phifun)

;;; fact 4:  K = phi(n) in os(succ n)
(cut `(IN ,K ,osSn))
(define u-Kin (last-node))
  (ta 'fun-apply-type)
  (inst '(FORALL f (FORALL A (FORALL B (FORALL x
            (IMPLIES (AND (IN f (FUN A B)) (IN x A)) (IN (f x) B)))))) phiv)
  (inst `(FORALL A (FORALL B (FORALL x
            (IMPLIES (AND (IN ,phiv (FUN A B)) (IN x A)) (IN (,phiv x) B))))) osSn)
  (inst `(FORALL B (FORALL x
            (IMPLIES (AND (IN ,phiv (FUN ,osSn B)) (IN x ,osSn)) (IN (,phiv x) B))))
        osSn)
  (inst `(FORALL x (IMPLIES (AND (IN ,phiv (FUN ,osSn ,osSn)) (IN x ,osSn))
                            (IN (,phiv x) ,osSn))) nv)
  (bc `(IMPLIES (AND (IN ,phiv (FUN ,osSn ,osSn)) (IN ,nv ,osSn))
                (IN ,K ,osSn)))
  (di)
  (define u-Kin2 (last-node))
    (ass)                           ; phi in FUN
  (refocus! u-Kin2)
    (ass)                           ; n in os(succ n)
(refocus! u-Kin)

;;; fact 5:  inv in BIJECTION(os(succ n), os(succ n))
(cut `(IN ,inv (BIJECTION ,osSn ,osSn)))
(define u-invbij (last-node))
  (ta 'inverse-bij-is-bijection)
  (inst `(FORALL X (FORALL Y (FORALL phi
            (IMPLIES (IN phi (BIJECTION X Y))
                     (IN (INVERSE-BIJ phi X Y) (BIJECTION Y X)))))) osSn)
  (inst `(FORALL Y (FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn Y))
                     (IN (INVERSE-BIJ phi ,osSn Y) (BIJECTION Y ,osSn))))) osSn)
  (inst `(FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn ,osSn))
                     (IN (INVERSE-BIJ phi ,osSn ,osSn) (BIJECTION ,osSn ,osSn))))
        phiv)
  (bc `(IMPLIES (IN ,phiv (BIJECTION ,osSn ,osSn))
                (IN ,inv (BIJECTION ,osSn ,osSn))))
  (ass)
(refocus! u-invbij)

;;; fact 6:  inv(K) = n   (inverse-bij-left: dom/cod-named)
(cut `(= (,inv ,K) ,nv))
(define u-invK (last-node))
  (ta 'inverse-bij-left)
  (inst '(FORALL dom (FORALL cod (FORALL phi
            (IMPLIES (IN phi (BIJECTION dom cod))
              (FORALL x (IMPLIES (IN x dom)
                (= ((INVERSE-BIJ phi dom cod) (phi x)) x))))))) osSn)
  (inst `(FORALL cod (FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn cod))
              (FORALL x (IMPLIES (IN x ,osSn)
                (= ((INVERSE-BIJ phi ,osSn cod) (phi x)) x)))))) osSn)
  (inst `(FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn ,osSn))
              (FORALL x (IMPLIES (IN x ,osSn)
                (= ((INVERSE-BIJ phi ,osSn ,osSn) (phi x)) x))))) phiv)
  (cut `(FORALL x (IMPLIES (IN x ,osSn) (= (,inv (,phiv x)) x))))
  (define u-invK2 (last-node))
    (bc `(IMPLIES (IN ,phiv (BIJECTION ,osSn ,osSn))
            (FORALL x (IMPLIES (IN x ,osSn) (= (,inv (,phiv x)) x)))))
    (ass)
  (refocus! u-invK2)
  (inst `(FORALL x (IMPLIES (IN x ,osSn) (= (,inv (,phiv x)) x))) nv)
  (bc `(IMPLIES (IN ,nv ,osSn) (= (,inv ,K) ,nv)))
  (ass)
(refocus! u-invK)

;;; fact 7:  dik = DELETE-AT(inv,K) in BIJECTION(os n, os n)
(cut `(IN ,dik (BIJECTION ,osn ,osn)))
(define u-dikbij (last-node))
  (ta 'delete-at-is-bijection)
  (inst '(FORALL n (FORALL k (FORALL h
            (IMPLIES (AND (IN n NN)
                     (AND (IN k (ORD-SEGMENT (succ n)))
                     (AND (IN h (BIJECTION (ORD-SEGMENT (succ n))
                                           (ORD-SEGMENT (succ n))))
                          (= (h k) n))))
                     (IN (DELETE-AT h k)
                         (BIJECTION (ORD-SEGMENT n) (ORD-SEGMENT n))))))) nv)
  (inst `(FORALL k (FORALL h
            (IMPLIES (AND (IN ,nv NN)
                     (AND (IN k ,osSn)
                     (AND (IN h (BIJECTION ,osSn ,osSn)) (= (h k) ,nv))))
                     (IN (DELETE-AT h k) (BIJECTION ,osn ,osn))))) K)
  (inst `(FORALL h
            (IMPLIES (AND (IN ,nv NN)
                     (AND (IN ,K ,osSn)
                     (AND (IN h (BIJECTION ,osSn ,osSn)) (= (h ,K) ,nv))))
                     (IN (DELETE-AT h ,K) (BIJECTION ,osn ,osn)))) inv)
  (bc `(IMPLIES (AND (IN ,nv NN)
                (AND (IN ,K ,osSn)
                (AND (IN ,inv (BIJECTION ,osSn ,osSn)) (= (,inv ,K) ,nv))))
                (IN ,dik (BIJECTION ,osn ,osn))))
  (di)                              ; split AND -> [n in NN] [AND ...]
  (define u-dik-a2 (last-node))
    (ass)                           ; n in NN
  (refocus! u-dik-a2)
  (di)                              ; split -> [K in osSn] [AND ...]
  (define u-dik-a3 (last-node))
    (ass)                           ; K in os(succ n)
  (refocus! u-dik-a3)
  (di)                              ; split -> [inv in BIJ] [inv(K)=n]
  (define u-dik-a4 (last-node))
    (ass)                           ; inv in BIJECTION
  (refocus! u-dik-a4)
    (ass)                           ; inv(K) = n
(refocus! u-dikbij)

;;; fact 8:  dgk = DELETE-AT(g,K) in FUN(NN, A(ag))
(cut `(IN ,dgk (FUN NN (A ,agv))))
(define u-dgkfun (last-node))
  (ta 'delete-at-in-fun)
  (inst '(FORALL B (FORALL h (FORALL k
            (IMPLIES (IN h (FUN NN B)) (IN (DELETE-AT h k) (FUN NN B))))))
        `(A ,agv))
  (inst `(FORALL h (FORALL k
            (IMPLIES (IN h (FUN NN (A ,agv)))
                     (IN (DELETE-AT h k) (FUN NN (A ,agv)))))) gv)
  (inst `(FORALL k (IMPLIES (IN ,gv (FUN NN (A ,agv)))
                            (IN (DELETE-AT ,gv k) (FUN NN (A ,agv))))) K)
  (bc `(IMPLIES (IN ,gv (FUN NN (A ,agv))) (IN ,dgk (FUN NN (A ,agv)))))
  (ass)
(refocus! u-dgkfun)

;;; fact 9:  h(n) = g(K)
(cut `(= (,hv ,nv) (,gv ,K)))
(define u-hn (last-node))
  (inst AGREE nv)
  (bc `(IMPLIES (IN ,nv ,osSn) (= (,hv ,nv) (,gv (,phiv ,nv)))))
  (ass)
(refocus! u-hn)

;;; FACT-H:  SUM-AG(h,succ n) = MUL(SUM-AG(h,n), h(n))
(cut `(= (SUM-AG ,agv ,hv (succ ,nv))
         ((MUL ,agv) (SUM-AG ,agv ,hv ,nv) (,hv ,nv))))
(define u-factH (last-node))
  (ta 'sum-ag-succ)
  (inst '(FORALL ag (FORALL f (FORALL n (IMPLIES (IN n NN)
            (= (SUM-AG ag f (succ n))
               ((MUL ag) (SUM-AG ag f n) (f n))))))) agv)
  (inst `(FORALL f (FORALL n (IMPLIES (IN n NN)
            (= (SUM-AG ,agv f (succ n))
               ((MUL ,agv) (SUM-AG ,agv f n) (f n)))))) hv)
  (inst `(FORALL n (IMPLIES (IN n NN)
            (= (SUM-AG ,agv ,hv (succ n))
               ((MUL ,agv) (SUM-AG ,agv ,hv n) (,hv n))))) nv)
  (bc `(IMPLIES (IN ,nv NN)
          (= (SUM-AG ,agv ,hv (succ ,nv))
             ((MUL ,agv) (SUM-AG ,agv ,hv ,nv) (,hv ,nv)))))
  (ass)
(refocus! u-factH)
(display "--- step: facts 1-9 + FACT-H established ---\n") (show)

;;; capture-free substitution, for building instantiation intermediates
(define (S v t f) (subst-free v t f))

;;; fact 4b:  K in NN
(cut `(IN ,K NN))
(define u-Knn (last-node))
  (ta 'ord-segment-nn-subset)
  (inst '(FORALL m (IMPLIES (IN m NN)
            (FORALL k (IMPLIES (IN k (ORD-SEGMENT m)) (IN k NN)))))
        `(succ ,nv))
  (cut `(FORALL k (IMPLIES (IN k ,osSn) (IN k NN))))
  (define u-Knn2 (last-node))
    (bc `(IMPLIES (IN (succ ,nv) NN)
            (FORALL k (IMPLIES (IN k ,osSn) (IN k NN)))))
    (ass)
  (refocus! u-Knn2)
  (inst `(FORALL k (IMPLIES (IN k ,osSn) (IN k NN))) K)
  (bc `(IMPLIES (IN ,K ,osSn) (IN ,K NN)))
  (ass)
(refocus! u-Knn)

;;; ===== FACT-G:  SUM-AG(g,succ n) = MUL(SUM-AG(DELETE-AT g K,n), g(K)) =====
(define spliceout
  '(FORALL n (IMPLIES (IN n NN)
     (FORALL ag (FORALL g (FORALL k (FORALL gp
       (IMPLIES (IS-ABELIAN-GROUP ag)
       (IMPLIES (IN g (FUN NN (A ag)))
       (IMPLIES (IN gp (FUN NN (A ag)))
       (IMPLIES (IN k (ORD-SEGMENT (succ n)))
       (IMPLIES (FORALL i (IMPLIES (IN i (ORD-SEGMENT k)) (= (gp i) (g i))))
       (IMPLIES (FORALL i (IMPLIES (AND (IN i (ORD-SEGMENT n))
                                        (NOT (IN i (ORD-SEGMENT k))))
                                   (= (gp i) (g (succ i)))))
         (= (SUM-AG ag g (succ n))
            ((MUL ag) (SUM-AG ag gp n) (g k))))))))))))))))
(define G-tmpl     ; splice-out's inner 6-implication, n/ag/g/k/gp generic
  '(IMPLIES (IS-ABELIAN-GROUP ag)
   (IMPLIES (IN g (FUN NN (A ag)))
   (IMPLIES (IN gp (FUN NN (A ag)))
   (IMPLIES (IN k (ORD-SEGMENT (succ n)))
   (IMPLIES (FORALL i (IMPLIES (IN i (ORD-SEGMENT k)) (= (gp i) (g i))))
   (IMPLIES (FORALL i (IMPLIES (AND (IN i (ORD-SEGMENT n))
                                    (NOT (IN i (ORD-SEGMENT k))))
                               (= (gp i) (g (succ i)))))
     (= (SUM-AG ag g (succ n)) ((MUL ag) (SUM-AG ag gp n) (g k))))))))))
(define G5 (S 'n nv G-tmpl))
(define BODY-nv `(FORALL ag (FORALL g (FORALL k (FORALL gp ,G5)))))
(define G4 (S 'ag agv G5))
(define BODY-ag `(FORALL g (FORALL k (FORALL gp ,G4))))
(define G3 (S 'g gv G4))
(define BODY-g `(FORALL k (FORALL gp ,G3)))
(define G2 (S 'k K G3))
(define BODY-k `(FORALL gp ,G2))
(define impl6 (S 'gp dgk G2))
(define GT2 (caddr impl6))
(define GT3 (caddr GT2))
(define GT4 (caddr GT3))
(define GT5 (caddr GT4))
(define GT6 (caddr GT5))
(define G-AGREE2 (cadr GT6))
(define FACT-G (caddr GT6))

(cut FACT-G)
(define u-factG (last-node))
  ;; AGREE1:  delete-at-below-k at h:=g, k:=K
  (ta 'delete-at-below-k)
  (inst '(FORALL h (FORALL k (FORALL i
            (IMPLIES (IN i (ORD-SEGMENT k)) (= ((DELETE-AT h k) i) (h i))))))
        gv)
  (inst `(FORALL k (FORALL i
            (IMPLIES (IN i (ORD-SEGMENT k))
                     (= ((DELETE-AT ,gv k) i) (,gv i))))) K)
  ;; AGREE2:  sub-proof from delete-at-above-k
  (cut G-AGREE2)
  (define u-spag (last-node))
    (define ci2 *fresh-counter*)
    (define iv2 (eigen-name 'i ci2))
    (di) (di)                  ; intro i, assume (AND i in os(n), i notin os(K))
    (ai `(AND (IN ,iv2 (ORD-SEGMENT ,nv)) (NOT (IN ,iv2 (ORD-SEGMENT ,K)))))
    (cut `(IN ,iv2 NN))
    (define u-iNN (last-node))
      (ta 'ord-segment-nn-subset)
      (inst '(FORALL m (IMPLIES (IN m NN)
                (FORALL k (IMPLIES (IN k (ORD-SEGMENT m)) (IN k NN))))) nv)
      (cut `(FORALL k (IMPLIES (IN k (ORD-SEGMENT ,nv)) (IN k NN))))
      (define u-iNN2 (last-node))
        (bc `(IMPLIES (IN ,nv NN)
                (FORALL k (IMPLIES (IN k (ORD-SEGMENT ,nv)) (IN k NN)))))
        (ass)
      (refocus! u-iNN2)
      (inst `(FORALL k (IMPLIES (IN k (ORD-SEGMENT ,nv)) (IN k NN))) iv2)
      (bc `(IMPLIES (IN ,iv2 (ORD-SEGMENT ,nv)) (IN ,iv2 NN)))
      (ass)
    (refocus! u-iNN)
    (ta 'delete-at-above-k)
    (inst '(FORALL h (FORALL k (FORALL i
              (IMPLIES (AND (IN i NN)
                       (AND (IN k NN) (NOT (IN i (ORD-SEGMENT k)))))
                       (= ((DELETE-AT h k) i) (h (succ i))))))) gv)
    (inst `(FORALL k (FORALL i
              (IMPLIES (AND (IN i NN)
                       (AND (IN k NN) (NOT (IN i (ORD-SEGMENT k)))))
                       (= ((DELETE-AT ,gv k) i) (,gv (succ i)))))) K)
    (inst `(FORALL i
              (IMPLIES (AND (IN i NN)
                       (AND (IN ,K NN) (NOT (IN i (ORD-SEGMENT ,K)))))
                       (= ((DELETE-AT ,gv ,K) i) (,gv (succ i))))) iv2)
    (bc `(IMPLIES (AND (IN ,iv2 NN)
                  (AND (IN ,K NN) (NOT (IN ,iv2 (ORD-SEGMENT ,K)))))
                  (= (,dgk ,iv2) (,gv (succ ,iv2)))))
    (di)                       ; split AND -> [i in NN] [AND ...]
    (define u-spagb (last-node))
      (ass)
    (refocus! u-spagb)
    (di)                       ; -> [K in NN] [i notin os(K)]
    (define u-spagc (last-node))
      (ass)
    (refocus! u-spagc)
      (ass)
  (refocus! u-spag)
  ;; instantiate splice-out
  (ta 'sum-ag-splice-out)
  (inst spliceout nv)
  (cut BODY-nv)
  (define u-Gbnv (last-node))
    (bc `(IMPLIES (IN ,nv NN) ,BODY-nv))
    (ass)
  (refocus! u-Gbnv)
  (inst BODY-nv agv)
  (inst BODY-ag gv)
  (inst BODY-g  K)
  (inst BODY-k  dgk)
  (cut GT2) (define uG2 (last-node)) (bc impl6) (ass) (refocus! uG2)
  (cut GT3) (define uG3 (last-node)) (bc GT2)   (ass) (refocus! uG3)
  (cut GT4) (define uG4 (last-node)) (bc GT3)   (ass) (refocus! uG4)
  (cut GT5) (define uG5 (last-node)) (bc GT4)   (ass) (refocus! uG5)
  (cut GT6) (define uG6 (last-node)) (bc GT5)   (ass) (refocus! uG6)
  (bc GT6) (ass)
(refocus! u-factG)
(display "--- step: FACT-G established ---\n") (show)

;;; ===== FACT-IND:  SUM-AG(h,n) = SUM-AG(DELETE-AT g K, n)  via the IH =====
(define INNER-tmpl
  '(FORALL ag (IMPLIES (IS-ABELIAN-GROUP ag)
     (FORALL g (IMPLIES (IN g (FUN NN (A ag)))
     (FORALL h (IMPLIES (IN h (FUN NN (A ag)))
     (FORALL phi (IMPLIES (IN phi (BIJECTION (ORD-SEGMENT n) (ORD-SEGMENT n)))
     (IMPLIES (FORALL i (IMPLIES (IN i (ORD-SEGMENT n)) (= (h i) (g (phi i)))))
       (= (SUM-AG ag g n) (SUM-AG ag h n))))))))))))
(define IH       (S 'n nv INNER-tmpl))
(define I1       (S 'ag agv (caddr IH)))
(define IH-Fg    (caddr I1))
(define I2       (S 'g hv (caddr IH-Fg)))
(define IH-Fh    (caddr I2))
(define I3       (S 'h dgk (caddr IH-Fh)))
(define IH-Fphi  (caddr I3))
(define I4       (S 'phi dik (caddr IH-Fphi)))
(define IH-P5C   (caddr I4))
(define AGREE-prime (cadr IH-P5C))
(define FACT-IND (caddr IH-P5C))

;;; shared facts for AGREE-prime:  inv typing and the inverse-bij-right form
(cut `(IN ,inv (FUN ,osSn ,osSn)))
(define u-invfun (last-node))
  (ta 'bijection-in-fun)
  (inst `(FORALL X (FORALL Y (FORALL phi
            (IMPLIES (IN phi (BIJECTION X Y)) (IN phi (FUN X Y)))))) osSn)
  (inst `(FORALL Y (FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn Y)) (IN phi (FUN ,osSn Y))))) osSn)
  (inst `(FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn ,osSn)) (IN phi (FUN ,osSn ,osSn))))
        inv)
  (bc `(IMPLIES (IN ,inv (BIJECTION ,osSn ,osSn)) (IN ,inv (FUN ,osSn ,osSn))))
  (ass)
(refocus! u-invfun)

(define invright `(FORALL y (IMPLIES (IN y ,osSn) (= (,phiv (,inv y)) y))))
(cut invright)
(define u-invr (last-node))
  (ta 'inverse-bij-right)
  (inst '(FORALL dom (FORALL cod (FORALL phi
            (IMPLIES (IN phi (BIJECTION dom cod))
              (FORALL y (IMPLIES (IN y cod)
                (= (phi ((INVERSE-BIJ phi dom cod) y)) y))))))) osSn)
  (inst `(FORALL cod (FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn cod))
              (FORALL y (IMPLIES (IN y cod)
                (= (phi ((INVERSE-BIJ phi ,osSn cod) y)) y)))))) osSn)
  (inst `(FORALL phi
            (IMPLIES (IN phi (BIJECTION ,osSn ,osSn))
              (FORALL y (IMPLIES (IN y ,osSn)
                (= (phi ((INVERSE-BIJ phi ,osSn ,osSn) y)) y))))) phiv)
  (bc `(IMPLIES (IN ,phiv (BIJECTION ,osSn ,osSn)) ,invright))
  (ass)
(refocus! u-invr)

(cut FACT-IND)
(define u-factIND (last-node))
  (inst IH agv)
  (cut IH-Fg)   (define uI1 (last-node)) (bc I1) (ass) (refocus! uI1)
  (inst IH-Fg hv)
  (cut IH-Fh)   (define uI2 (last-node)) (bc I2) (ass) (refocus! uI2)
  (inst IH-Fh dgk)
  (cut IH-Fphi) (define uI3 (last-node)) (bc I3) (ass) (refocus! uI3)
  (inst IH-Fphi dik)
  (cut IH-P5C)  (define uI4 (last-node)) (bc I4) (ass) (refocus! uI4)
  (bc IH-P5C)                 ; goal FACT-IND -> AGREE-prime
  ;; ----- prove AGREE-prime:  forall i in os(n). dgk(i) = h(dik(i)) -----
  (define ci3 *fresh-counter*)
  (define iv3 (eigen-name 'i ci3))
  (di)                        ; intro i, assume i in os(n)
  ;; shared per-i facts
  (cut `(IN ,iv3 ,osSn))
  (define u-i3Sn (last-node))
    (mac 'ord-segment-nn-succ) (oi-l) (ass)
  (refocus! u-i3Sn)
  (cut `(IN ,iv3 NN))
  (define u-i3NN (last-node))
    (ta 'ord-segment-nn-subset)
    (inst '(FORALL m (IMPLIES (IN m NN)
              (FORALL k (IMPLIES (IN k (ORD-SEGMENT m)) (IN k NN))))) nv)
    (cut `(FORALL k (IMPLIES (IN k (ORD-SEGMENT ,nv)) (IN k NN))))
    (define u-i3NN2 (last-node))
      (bc `(IMPLIES (IN ,nv NN)
              (FORALL k (IMPLIES (IN k (ORD-SEGMENT ,nv)) (IN k NN)))))
      (ass)
    (refocus! u-i3NN2)
    (inst `(FORALL k (IMPLIES (IN k (ORD-SEGMENT ,nv)) (IN k NN))) iv3)
    (bc `(IMPLIES (IN ,iv3 (ORD-SEGMENT ,nv)) (IN ,iv3 NN)))
    (ass)
  (refocus! u-i3NN)
  ;; excluded middle on  P := i in os(K)
  (cut `(OR (IN ,iv3 (ORD-SEGMENT ,K)) (NOT (IN ,iv3 (ORD-SEGMENT ,K)))))
  (define u-em (last-node))
    (pbc)                     ; assume H = NOT(OR P (NOT P)), goal FALSITY
    (cut `(NOT (IN ,iv3 (ORD-SEGMENT ,K))))
    (define u-em2 (last-node))
      (di)                    ; assume P, goal FALSITY
      (cut `(OR (IN ,iv3 (ORD-SEGMENT ,K)) (NOT (IN ,iv3 (ORD-SEGMENT ,K)))))
      (define u-em3 (last-node))
        (oi-l) (ass)
      (refocus! u-em3)
      (ai `(NOT (OR (IN ,iv3 (ORD-SEGMENT ,K))
                    (NOT (IN ,iv3 (ORD-SEGMENT ,K))))))
    (refocus! u-em2)
    (cut `(OR (IN ,iv3 (ORD-SEGMENT ,K)) (NOT (IN ,iv3 (ORD-SEGMENT ,K)))))
    (define u-em4 (last-node))
      (oi-r) (ass)
    (refocus! u-em4)
    (ai `(NOT (OR (IN ,iv3 (ORD-SEGMENT ,K))
                  (NOT (IN ,iv3 (ORD-SEGMENT ,K))))))
  (refocus! u-em)
  (ai `(OR (IN ,iv3 (ORD-SEGMENT ,K)) (NOT (IN ,iv3 (ORD-SEGMENT ,K)))))
  (define caseNP (last-node))
    ;; ===== case P:  i in os(K) =====
    ;; db:  dgk(i) = g(i)
    (cut `(= (,dgk ,iv3) (,gv ,iv3)))
    (define u-db (last-node))
      (ta 'delete-at-below-k)
      (inst '(FORALL h (FORALL k (FORALL i
                (IMPLIES (IN i (ORD-SEGMENT k))
                         (= ((DELETE-AT h k) i) (h i)))))) gv)
      (inst `(FORALL k (FORALL i
                (IMPLIES (IN i (ORD-SEGMENT k))
                         (= ((DELETE-AT ,gv k) i) (,gv i))))) K)
      (inst `(FORALL i (IMPLIES (IN i (ORD-SEGMENT ,K))
                         (= (,dgk i) (,gv i)))) iv3)
      (bc `(IMPLIES (IN ,iv3 (ORD-SEGMENT ,K)) (= (,dgk ,iv3) (,gv ,iv3))))
      (ass)
    (refocus! u-db)
    ;; di:  dik(i) = inv(i)
    (cut `(= (,dik ,iv3) (,inv ,iv3)))
    (define u-di (last-node))
      (ta 'delete-at-below-k)
      (inst '(FORALL h (FORALL k (FORALL i
                (IMPLIES (IN i (ORD-SEGMENT k))
                         (= ((DELETE-AT h k) i) (h i)))))) inv)
      (inst `(FORALL k (FORALL i
                (IMPLIES (IN i (ORD-SEGMENT k))
                         (= ((DELETE-AT ,inv k) i) (,inv i))))) K)
      (inst `(FORALL i (IMPLIES (IN i (ORD-SEGMENT ,K))
                         (= (,dik i) (,inv i)))) iv3)
      (bc `(IMPLIES (IN ,iv3 (ORD-SEGMENT ,K)) (= (,dik ,iv3) (,inv ,iv3))))
      (ass)
    (refocus! u-di)
    ;; inv(i) in os(succ n)
    (cut `(IN (,inv ,iv3) ,osSn))
    (define u-invi (last-node))
      (ta 'fun-apply-type)
      (inst '(FORALL f (FORALL A (FORALL B (FORALL x
                (IMPLIES (AND (IN f (FUN A B)) (IN x A)) (IN (f x) B)))))) inv)
      (inst `(FORALL A (FORALL B (FORALL x
                (IMPLIES (AND (IN ,inv (FUN A B)) (IN x A))
                         (IN (,inv x) B))))) osSn)
      (inst `(FORALL B (FORALL x
                (IMPLIES (AND (IN ,inv (FUN ,osSn B)) (IN x ,osSn))
                         (IN (,inv x) B)))) osSn)
      (inst `(FORALL x (IMPLIES (AND (IN ,inv (FUN ,osSn ,osSn)) (IN x ,osSn))
                                (IN (,inv x) ,osSn))) iv3)
      (bc `(IMPLIES (AND (IN ,inv (FUN ,osSn ,osSn)) (IN ,iv3 ,osSn))
                    (IN (,inv ,iv3) ,osSn)))
      (di) (define u-invi2 (last-node)) (ass) (refocus! u-invi2) (ass)
    (refocus! u-invi)
    ;; pr1:  phi(inv(i)) = i
    (cut `(= (,phiv (,inv ,iv3)) ,iv3))
    (define u-pr1 (last-node))
      (inst invright iv3)
      (bc `(IMPLIES (IN ,iv3 ,osSn) (= (,phiv (,inv ,iv3)) ,iv3)))
      (ass)
    (refocus! u-pr1)
    ;; ag1:  h(inv(i)) = g(phi(inv(i)))
    (cut `(= (,hv (,inv ,iv3)) (,gv (,phiv (,inv ,iv3)))))
    (define u-ag1 (last-node))
      (inst AGREE `(,inv ,iv3))
      (bc `(IMPLIES (IN (,inv ,iv3) ,osSn)
                    (= (,hv (,inv ,iv3)) (,gv (,phiv (,inv ,iv3))))))
      (ass)
    (refocus! u-ag1)
    ;; combine
    (subst `(= (,dgk ,iv3) (,gv ,iv3)))
    (subst `(= (,dik ,iv3) (,inv ,iv3)))
    (subst `(= (,hv (,inv ,iv3)) (,gv (,phiv (,inv ,iv3)))))
    (subst `(= (,phiv (,inv ,iv3)) ,iv3))
    (rfl)
  (refocus! caseNP)
    ;; ===== case NOT P:  i notin os(K) =====
    ;; db2:  dgk(i) = g(succ i)
    (cut `(= (,dgk ,iv3) (,gv (succ ,iv3))))
    (define u-db2 (last-node))
      (ta 'delete-at-above-k)
      (inst '(FORALL h (FORALL k (FORALL i
                (IMPLIES (AND (IN i NN)
                         (AND (IN k NN) (NOT (IN i (ORD-SEGMENT k)))))
                         (= ((DELETE-AT h k) i) (h (succ i))))))) gv)
      (inst `(FORALL k (FORALL i
                (IMPLIES (AND (IN i NN)
                         (AND (IN k NN) (NOT (IN i (ORD-SEGMENT k)))))
                         (= ((DELETE-AT ,gv k) i) (,gv (succ i)))))) K)
      (inst `(FORALL i
                (IMPLIES (AND (IN i NN)
                         (AND (IN ,K NN) (NOT (IN i (ORD-SEGMENT ,K)))))
                         (= ((DELETE-AT ,gv ,K) i) (,gv (succ i))))) iv3)
      (bc `(IMPLIES (AND (IN ,iv3 NN)
                    (AND (IN ,K NN) (NOT (IN ,iv3 (ORD-SEGMENT ,K)))))
                    (= (,dgk ,iv3) (,gv (succ ,iv3)))))
      (di) (define u-db2b (last-node)) (ass) (refocus! u-db2b)
      (di) (define u-db2c (last-node)) (ass) (refocus! u-db2c) (ass)
    (refocus! u-db2)
    ;; di2:  dik(i) = inv(succ i)
    (cut `(= (,dik ,iv3) (,inv (succ ,iv3))))
    (define u-di2 (last-node))
      (ta 'delete-at-above-k)
      (inst '(FORALL h (FORALL k (FORALL i
                (IMPLIES (AND (IN i NN)
                         (AND (IN k NN) (NOT (IN i (ORD-SEGMENT k)))))
                         (= ((DELETE-AT h k) i) (h (succ i))))))) inv)
      (inst `(FORALL k (FORALL i
                (IMPLIES (AND (IN i NN)
                         (AND (IN k NN) (NOT (IN i (ORD-SEGMENT k)))))
                         (= ((DELETE-AT ,inv k) i) (,inv (succ i)))))) K)
      (inst `(FORALL i
                (IMPLIES (AND (IN i NN)
                         (AND (IN ,K NN) (NOT (IN i (ORD-SEGMENT ,K)))))
                         (= ((DELETE-AT ,inv ,K) i) (,inv (succ i))))) iv3)
      (bc `(IMPLIES (AND (IN ,iv3 NN)
                    (AND (IN ,K NN) (NOT (IN ,iv3 (ORD-SEGMENT ,K)))))
                    (= (,dik ,iv3) (,inv (succ ,iv3)))))
      (di) (define u-di2b (last-node)) (ass) (refocus! u-di2b)
      (di) (define u-di2c (last-node)) (ass) (refocus! u-di2c) (ass)
    (refocus! u-di2)
    ;; succ i in os(succ n)
    (cut `(IN (succ ,iv3) ,osSn))
    (define u-si (last-node))
      (ta 'ord-segment-succ-monotone)
      (inst '(FORALL n (IMPLIES (IN n NN)
                (FORALL i (IMPLIES (IN i (ORD-SEGMENT n))
                  (IN (succ i) (ORD-SEGMENT (succ n))))))) nv)
      (cut `(FORALL i (IMPLIES (IN i (ORD-SEGMENT ,nv))
                (IN (succ i) ,osSn))))
      (define u-si2 (last-node))
        (bc `(IMPLIES (IN ,nv NN)
                (FORALL i (IMPLIES (IN i (ORD-SEGMENT ,nv))
                  (IN (succ i) ,osSn)))))
        (ass)
      (refocus! u-si2)
      (inst `(FORALL i (IMPLIES (IN i (ORD-SEGMENT ,nv))
                (IN (succ i) ,osSn))) iv3)
      (bc `(IMPLIES (IN ,iv3 (ORD-SEGMENT ,nv)) (IN (succ ,iv3) ,osSn)))
      (ass)
    (refocus! u-si)
    ;; inv(succ i) in os(succ n)
    (cut `(IN (,inv (succ ,iv3)) ,osSn))
    (define u-invsi (last-node))
      (ta 'fun-apply-type)
      (inst '(FORALL f (FORALL A (FORALL B (FORALL x
                (IMPLIES (AND (IN f (FUN A B)) (IN x A)) (IN (f x) B)))))) inv)
      (inst `(FORALL A (FORALL B (FORALL x
                (IMPLIES (AND (IN ,inv (FUN A B)) (IN x A))
                         (IN (,inv x) B))))) osSn)
      (inst `(FORALL B (FORALL x
                (IMPLIES (AND (IN ,inv (FUN ,osSn B)) (IN x ,osSn))
                         (IN (,inv x) B)))) osSn)
      (inst `(FORALL x (IMPLIES (AND (IN ,inv (FUN ,osSn ,osSn)) (IN x ,osSn))
                                (IN (,inv x) ,osSn))) `(succ ,iv3))
      (bc `(IMPLIES (AND (IN ,inv (FUN ,osSn ,osSn)) (IN (succ ,iv3) ,osSn))
                    (IN (,inv (succ ,iv3)) ,osSn)))
      (di) (define u-invsi2 (last-node)) (ass) (refocus! u-invsi2) (ass)
    (refocus! u-invsi)
    ;; pr2:  phi(inv(succ i)) = succ i
    (cut `(= (,phiv (,inv (succ ,iv3))) (succ ,iv3)))
    (define u-pr2 (last-node))
      (inst invright `(succ ,iv3))
      (bc `(IMPLIES (IN (succ ,iv3) ,osSn)
                    (= (,phiv (,inv (succ ,iv3))) (succ ,iv3))))
      (ass)
    (refocus! u-pr2)
    ;; ag2:  h(inv(succ i)) = g(phi(inv(succ i)))
    (cut `(= (,hv (,inv (succ ,iv3))) (,gv (,phiv (,inv (succ ,iv3))))))
    (define u-ag2 (last-node))
      (inst AGREE `(,inv (succ ,iv3)))
      (bc `(IMPLIES (IN (,inv (succ ,iv3)) ,osSn)
                    (= (,hv (,inv (succ ,iv3)))
                       (,gv (,phiv (,inv (succ ,iv3)))))))
      (ass)
    (refocus! u-ag2)
    ;; combine
    (subst `(= (,dgk ,iv3) (,gv (succ ,iv3))))
    (subst `(= (,dik ,iv3) (,inv (succ ,iv3))))
    (subst `(= (,hv (,inv (succ ,iv3))) (,gv (,phiv (,inv (succ ,iv3))))))
    (subst `(= (,phiv (,inv (succ ,iv3))) (succ ,iv3)))
    (rfl)
(refocus! u-factIND)
(display "--- step: FACT-IND established ---\n") (show)

;;; ===== assemble =====
(subst FACT-G)
(subst `(= (SUM-AG ,agv ,hv (succ ,nv))
           ((MUL ,agv) (SUM-AG ,agv ,hv ,nv) (,hv ,nv))))
(subst `(= (,hv ,nv) (,gv ,K)))
(subst FACT-IND)
(rfl)
(display "--- step: DONE ---\n") (show)

