;;; vnb-cmd-gen.el --- auto-derive interactive commands for no-arg tactics -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; Slice 2 of the two-surfaces convergence work (keep the interactive surface
;; tracking the script-driven one).
;;
;; The Scheme side emits its command registry (*tactic-help* + *command-aux*)
;; to emacs/vnb-commands.lisp via (write-vnb-commands), which runs on every
;; prover load.  Each entry is  (NAME (ARG ...) "gloss").
;;
;; This file reads that catalog and, for every command whose argument list is
;; EMPTY -- the "kind-0", no-argument tactics (di, pbc, rfl, arith, crs,
;; split-ands!, ...) -- defines an interactive Emacs command
;;
;;     M-x vnb-cmd-NAME
;;
;; that sends "(NAME)" to the running prover.  The command's docstring is the
;; catalog gloss, so C-h f vnb-cmd-NAME explains the tactic.  It also builds a
;; "No-arg Tactics" menu of them, installable into a keymap.
;;
;; Why generated rather than hand-written: this is the answer to case (1) of
;; the design -- "any proof command with no arguments should correspond to a
;; button press or an M-x command".  Generation guarantees EVERY no-arg tactic
;; gets one, with zero hand-maintenance and no drift from the (tactics) menu:
;; add a tactic to the Scheme registry, reload the prover (regenerates
;; vnb-commands.lisp), reload Emacs, and its command + menu entry appear.
;;
;; Arg-taking tactics (kind N/H/T/K) keep their curated hand-written
;; `vnb-pf-*' front-ends with guided prompts and scarce single-key bindings;
;; this file deliberately does not touch those.

;;; Code:

(require 'easymenu)

(defvar vnb-cmd--catalog-file
  (expand-file-name "vnb-commands.lisp"
                    (file-name-directory
                     (or load-file-name buffer-file-name default-directory)))
  "Path to the generated command catalog `vnb-commands.lisp'.")

(defvar vnb-cmd--catalog nil
  "Command catalog as read from `vnb-cmd--catalog-file'.
A list of entries (NAME (ARG ...) DOC).")

(defvar vnb-cmd--generated nil
  "Symbols of the interactive commands generated by `vnb-cmd-generate-noarg'.")

(defun vnb-cmd--load-catalog ()
  "Read the command catalog into `vnb-cmd--catalog'.  Returns it, or nil."
  (when (file-readable-p vnb-cmd--catalog-file)
    (with-temp-buffer
      (insert-file-contents vnb-cmd--catalog-file)
      (setq vnb-cmd--catalog (read (current-buffer))))))

(defun vnb-cmd--noarg-entries ()
  "Catalog entries whose argument list is empty (the no-arg tactics).
Catalog order is preserved, which keeps the registry's logical grouping."
  (let (acc)
    (dolist (e vnb-cmd--catalog (nreverse acc))
      (when (and (consp e) (null (cadr e)))
        (push e acc)))))

(defun vnb-cmd--short-gloss (doc)
  "First sentence of DOC (up to the first period), for menu labels."
  (if (and (stringp doc) (string-match "\\." doc))
      (substring doc 0 (match-end 0))
    (or doc "")))

;;;###autoload
(defun vnb-cmd-generate-noarg ()
  "(Re)generate an interactive command for every no-arg tactic in the catalog.
Each no-arg tactic NAME becomes  \\[execute-extended-command] vnb-cmd-NAME,
which sends \"(NAME)\" to the prover.  Returns the list of command symbols."
  (interactive)
  (vnb-cmd--load-catalog)
  (setq vnb-cmd--generated nil)
  (dolist (e (vnb-cmd--noarg-entries))
    (let* ((name (car e))
           (doc  (or (caddr e) ""))
           (sexp (format "(%s)" name))
           (sym  (intern (format "vnb-cmd-%s" name))))
      (defalias sym
        (lambda ()
          (interactive)
          (if (fboundp 'vnb-launch--send-tactic)
              (vnb-launch--send-tactic sexp)
            (user-error "VNB launcher not loaded: cannot send %s" sexp)))
        (format "%s\n\nNo-argument VNB tactic; sends `%s' to the prover.\n\
Auto-generated by vnb-cmd-gen.el from the command registry." doc sexp))
      (push sym vnb-cmd--generated)))
  (setq vnb-cmd--generated (nreverse vnb-cmd--generated)))

(defun vnb-cmd--menu-spec ()
  "Build the easy-menu item list for the generated no-arg commands."
  (mapcar (lambda (e)
            (let* ((name (car e))
                   (sym  (intern (format "vnb-cmd-%s" name))))
              (vector (format "%-16s %s" name (vnb-cmd--short-gloss (caddr e)))
                      sym
                      :help (or (caddr e) ""))))
          (vnb-cmd--noarg-entries)))

;;;###autoload
(defun vnb-cmd-install-menu (&optional map)
  "Install a \"No-arg Tactics\" menu of generated commands into MAP.
MAP defaults to `vnb-proof-mode-map' if bound.  Safe to call repeatedly."
  (interactive)
  (let ((map (or map (and (boundp 'vnb-proof-mode-map) vnb-proof-mode-map))))
    (when (and map (vnb-cmd--noarg-entries))
      (easy-menu-define nil map "VNB no-argument tactics"
        (cons "No-arg Tactics" (vnb-cmd--menu-spec))))))

;; Generate the commands at load time (no dependency on the launcher yet --
;; `vnb-launch--send-tactic' is resolved when a command is actually invoked).
(vnb-cmd-generate-noarg)

(provide 'vnb-cmd-gen)

;;; vnb-cmd-gen.el ends here
