;;; vnb-cmd-gen.el --- auto-derive interactive commands for no-arg tactics -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; Slice 2 of the two-surfaces convergence work (keep the interactive surface
;; tracking the script-driven one).
;;
;; The Scheme side emits its command registry (*tactic-help* + *command-aux*)
;; to emacs/vnb-commands.lisp via (write-vnb-commands), which runs on every
;; prover load.  Each entry is  (NAME (ARG ...) "gloss").
;;
;; This file reads that catalog and defines an interactive Emacs command
;;
;;     M-x vnb-cmd-NAME
;;
;; for EVERY tactic in it, so the `vnb-cmd-' M-x namespace mirrors the
;; `(tactics)' menu completely (no more "only a subset completes").  Three
;; tiers, by argument shape:
;;
;;   * no-arg tactic (di, pbc, arith, split-ands!, ...) -> sends "(NAME)";
;;   * tactic with a curated `vnb-pf-*' front-end (mac, mac-h, ta, bc*, inst,
;;     ai, ...) -> vnb-cmd-NAME is an ALIAS of that front-end, so the rich
;;     prompts (name-index completion, #N assumption picking, bc*'s
;;     undetermined-var handling) are preserved -- see `vnb-cmd--delegate-map';
;;   * any other arg-taking tactic (cut, wk, ui, ce, iota-d, if-true, the
;;     tacticals, ...) -> prompts for its arguments in surface syntax and sends
;;     the form (`vnb-cmd--send-raw').  When the tactic's first argument is a
;;     FORMULA or a TERM, it is read on its own prompt and quoted on the way
;;     out -- see `vnb-cmd--formula-arg-names' for why an unquoted answer is
;;     not merely unparsed but misread, by MIT Scheme's reader.
;;
;; The command's docstring is the catalog gloss, so C-h f vnb-cmd-NAME explains
;; the tactic.  A "No-arg Tactics" menu of the no-arg commands is also built
;; (a one-keypress palette; arg-taking ones are M-x, which prompts).
;;
;; Why generated rather than hand-written: zero hand-maintenance and no drift
;; from the (tactics) menu -- add a tactic to the Scheme registry, reload the
;; prover (regenerates vnb-commands.lisp), reload Emacs, and its vnb-cmd-NAME
;; appears.  The internal entry points are `vnb-cmdgen-rebuild' /
;; `vnb-cmdgen-install-menu' -- named OFF the `vnb-cmd-' prefix so they do not
;; pollute `M-x vnb-cmd-' completion (which is reserved for tactics).

;;; Code:

(require 'easymenu)

(defvar vnb-cmd--catalog-file
  (expand-file-name "vnb-commands.lisp"
                    (file-name-directory
                     (or load-file-name buffer-file-name default-directory)))
  "Path to the generated command catalog `vnb-commands.lisp'.")

(defvar vnb-cmd--catalog nil
  "Command catalog as read from `vnb-cmd--catalog-file'.
A list of entries (NAME (ARG ...) DOC).")

(defvar vnb-cmd--generated nil
  "Symbols of the interactive commands generated by `vnb-cmdgen-rebuild'.")

(defun vnb-cmd--load-catalog ()
  "Read the command catalog into `vnb-cmd--catalog'.  Returns it, or nil."
  (when (file-readable-p vnb-cmd--catalog-file)
    (with-temp-buffer
      (insert-file-contents vnb-cmd--catalog-file)
      (setq vnb-cmd--catalog (read (current-buffer))))))

(defun vnb-cmd--noarg-entries ()
  "Catalog entries whose argument list is empty (the no-arg tactics).
Catalog order is preserved, which keeps the registry's logical grouping."
  (let (acc)
    (dolist (e vnb-cmd--catalog (nreverse acc))
      (when (and (consp e) (null (cadr e)))
        (push e acc)))))

(defun vnb-cmd--short-gloss (doc)
  "First sentence of DOC (up to the first period), for menu labels."
  (if (and (stringp doc) (string-match "\\." doc))
      (substring doc 0 (match-end 0))
    (or doc "")))

(defvar vnb-cmd--delegate-map
  '((mac     . vnb-pf-rewrite)
    (mac-h   . vnb-pf-rewrite-hyp)
    (ta      . vnb-pf-theorem)
    ;; `fact' is variadic -- (fact 'thm term ...) -- and its front-end reads the
    ;; instantiation terms one at a time until an empty RET.  Without this entry
    ;; it fell to `vnb-cmd--send-raw', which splices what you type straight into
    ;; (fact %s): the theorem name then had to carry its own quote, since
    ;; cmd-fact (proof-commands.scm) looks it up by `symbol?' and an unquoted
    ;; name is evaluated by the Scheme reader instead.
    (fact    . vnb-pf-fact)
    (inst    . vnb-pf-instantiate)
    (ai      . vnb-pf-antecedent-inference)
    (sep-me  . vnb-pf-sep-elim)
    (comp-me . vnb-pf-comp-elim)
    (bu-me   . vnb-pf-bigunion-elim)
    (ew      . vnb-pf-exists-witness)
    (bc      . vnb-pf-backchain)
    (bc*     . vnb-pf-backchain-star)
    (focus   . vnb-pf-focus)
    (qed     . vnb-pf-qed)
    ;; The two pool searches.  Without these they fall to `vnb-cmd--send-raw',
    ;; i.e. a bare read-string with no completion -- on the commands whose whole
    ;; job is finding a name you cannot remember.  Their argument is a SUBSTRING,
    ;; so the front-ends complete without requiring a match.
    (find-thm . vnb-pf-find-theorem)
    (find-mac . vnb-pf-find-macete))
  "Tactics whose argument-gathering already has a curated `vnb-pf-*' front-end.
For these, vnb-cmd-NAME is made an ALIAS of that front-end, so the M-x
`vnb-cmd-' namespace covers them WITH the rich prompts intact (name-index
completion, #N assumption picking, bc*'s undetermined-var handling, ...).")

(defun vnb-cmd--arglist-sig (name args)
  "Reconstruct a display signature \"(name arg ...)\" for prompts."
  (if args
      (format "(%s %s)" name (mapconcat #'symbol-name args " "))
    (format "(%s)" name)))

(defvar vnb-cmd--formula-arg-names
  '(goal formula claim impl term mem target w t c1 l0 hint)
  "Catalog argument names denoting a piece of SURFACE SYNTAX -- a formula or
a term -- as opposed to a theorem name, an assumption index or a thunk.
When the FIRST argument of a tactic is one of these, it is read on a prompt of
its own and QUOTED on the way out (`vnb-cmd--send-quoted'): the user types the
surface text bare and never has to think about the quotes at all.

Unquoted surface text does not reach VNB's parser at all: the argument
string is spliced into `(NAME ...)' and read by MIT Scheme first, where a
`,' is unquote and a `'' is quote.  So `cut b = union(a, complement-in(b,a))'
failed with \";Special keyword can't be expanded: (unquote complement-in)\"
-- a message that names a symbol the user did type and blames a reader they
did not know was involved.  Quoting is what `->raw-formula' (interactive.scm)
dispatches on: a string is handed to `parse-string', anything else is taken
as a raw S-expression.

Deliberately EXCLUDED: `hyp' (ce, te, ie, ue, wk, lam-b-h -- these accept a
bare assumption index `#N' as well as a formula, so a quote is as often
wrong as right); `ineq' (the argument of `prep' is a TACTIC name, not an
inequality); `name' / `thm' / `acc' (symbols); `k' / `n' / `i1' (indices).")

(defun vnb-cmd--send-quoted (name sig args)
  "Prompt for a tactic whose FIRST argument is surface syntax, and QUOTE it.
The user types the formula or term bare; elisp adds the double quotes on the
way out, with `%S', which also escapes any quote inside the text.  Quotes the
user typed anyway are stripped first by `vnb-launch--dequote', so typing them
is harmless rather than doubled.

Any REMAINING arguments are read separately and spliced raw: they are indices,
thunks or names, for which a quote would be wrong.  This is why the first
argument gets its own prompt instead of the whole line being wrapped -- a
tactic like `have!' takes a formula AND a thunk, and one pair of quotes round
the pair of them would be nonsense."
  (let* ((a1   (vnb-launch--dequote
                (vnb-launch--read-required
                 (format "%s  --  %s, surface syntax, no quotes needed (empty cancels): "
                         sig (car args)))))
         (rest (if (cdr args)
                   (read-string
                    (format "%s  --  %s (empty = none): " sig
                            (mapconcat #'symbol-name (cdr args) " ")))
                 "")))
    (vnb-launch--send-tactic
     (if (string-match-p "\\`[ \t]*\\'" rest)
         (format "(%s %S)" name a1)
       (format "(%s %S %s)" name a1 rest)))))

(defun vnb-cmd--send-raw (name sig &optional args)
  "Prompt for the arguments of arg-taking tactic NAME and send the form.
The user types the arguments in Scheme surface syntax -- an assumption number
bare, a tactic thunk like `di' for a tactical -- exactly what would go after
the head in the Scratch Workspace.  ARGS is the tactic's catalog argument
list; when its first element is in `vnb-cmd--formula-arg-names', that argument
is read on its own and QUOTED by `vnb-cmd--send-quoted'.
The universal fallback for tactics without a curated `vnb-pf-*' front-end."
  (unless (fboundp 'vnb-launch--send-tactic)
    (user-error "VNB launcher not loaded"))
  (if (and (consp args) (memq (car args) vnb-cmd--formula-arg-names))
      (vnb-cmd--send-quoted name sig args)
    (let ((argstr (vnb-launch--read-required
                   (format "%s  --  arguments after `%s' (empty cancels): "
                           sig name))))
      (vnb-launch--send-tactic (format "(%s %s)" name argstr)))))

;;;###autoload
(defun vnb-cmdgen-rebuild ()
  "(Re)generate `vnb-cmd-NAME' for EVERY tactic in the catalog, so the
`vnb-cmd-' M-x namespace mirrors the `(tactics)' menu completely.  Three tiers:
no-arg sends \"(NAME)\"; a tactic in `vnb-cmd--delegate-map' becomes an alias of
its curated `vnb-pf-*' front-end; any other arg-taking tactic prompts for its
arguments (`vnb-cmd--send-raw').  Returns the list of generated symbols."
  (interactive)
  (vnb-cmd--load-catalog)
  (setq vnb-cmd--generated nil)
  (dolist (e vnb-cmd--catalog)
    (when (consp e)
      (let* ((name  (car e))
             (args  (cadr e))
             (doc   (or (caddr e) ""))
             (sym   (intern (format "vnb-cmd-%s" name)))
             (deleg (cdr (assq name vnb-cmd--delegate-map))))
        (cond
         ;; tier 2: curated front-end exists -> alias to it (resolves at call
         ;; time, so it is fine that the vnb-pf-* are defined later in load).
         (deleg
          (defalias sym deleg))
         ;; tier 1: no-arg -> send (NAME)
         ((null args)
          (let ((sexp (format "(%s)" name)))
            (defalias sym
              (lambda ()
                (interactive)
                (if (fboundp 'vnb-launch--send-tactic)
                    (vnb-launch--send-tactic sexp)
                  (user-error "VNB launcher not loaded: cannot send %s" sexp)))
              (format "%s\n\nNo-argument VNB tactic; sends `%s' to the prover.\n\
Auto-generated by vnb-cmd-gen.el from the command registry." doc sexp))))
         ;; tier 3: arg-taking, no front-end -> prompt for arguments
         (t
          (let ((sig (vnb-cmd--arglist-sig name args)))
            (defalias sym
              (lambda ()
                (interactive)
                (vnb-cmd--send-raw name sig args))
              (format "%s\n\nVNB tactic `%s'; prompts for its arguments and \
sends the form.\nAuto-generated by vnb-cmd-gen.el from the command registry."
                      doc sig)))))
        (push sym vnb-cmd--generated))))
  (setq vnb-cmd--generated (nreverse vnb-cmd--generated)))

(defun vnb-cmd--menu-spec ()
  "Build the easy-menu item list for the no-arg generated commands."
  (mapcar (lambda (e)
            (let* ((name (car e))
                   (sym  (intern (format "vnb-cmd-%s" name))))
              (vector (format "%-16s %s" name (vnb-cmd--short-gloss (caddr e)))
                      sym
                      :help (or (caddr e) ""))))
          (vnb-cmd--noarg-entries)))

;;;###autoload
(defun vnb-cmdgen-install-menu (&optional map)
  "Install a \"No-arg Tactics\" menu of the generated no-arg commands into MAP.
MAP defaults to `vnb-proof-mode-map' if bound.  Safe to call repeatedly.
The menu stays no-arg -- a one-keypress palette; arg-taking tactics are
\\[execute-extended-command] vnb-cmd-NAME, which prompts."
  (interactive)
  (let ((map (or map (and (boundp 'vnb-proof-mode-map) vnb-proof-mode-map))))
    (when (and map (vnb-cmd--noarg-entries))
      (easy-menu-define nil map "VNB no-argument tactics"
        (cons "No-arg Tactics" (vnb-cmd--menu-spec))))))

;; Generate the commands at load time (no dependency on the launcher yet --
;; `vnb-launch--send-tactic' and the `vnb-pf-*' alias targets are resolved
;; when a command is actually invoked).
(vnb-cmdgen-rebuild)

(provide 'vnb-cmd-gen)

;;; vnb-cmd-gen.el ends here
