#!/usr/bin/env python3
r"""Generate the manual's glossary appendix (app-glossary-generated.tex) from the
prover-generated reference/GLOSSARY.md.

GLOSSARY.md is emitted from the live registries on every prover load
(glossary.scm), so it is always current: every structure, refinement, instance,
view, predicate, functoid, accessor, defined constant, kernel head and tactic,
in one alphabetical list.  This converter renders it as a two-column LaTeX
glossary -- one paragraph per name, its kind, its reading, and where it is
declared -- so the manual carries the vocabulary itself rather than sending the
reader to the browser.

The RESULTS (theorems, axioms, supports) are deliberately absent, here as in the
.md: there are some 3200 of them and they have their own catalogs.

Run:   python3 docs/gen-glossary.py
Emits: docs/app-glossary-generated.tex   (\input by manual.tex, after ch-source)
"""
import os, re

# makeindex and LaTeX each have their own special characters, and VNB names hit
# both: `warrant!' ends in ! (makeindex's subentry separator), `card-star(a_)'
# contains _ (LaTeX math-mode shift).  An index entry is  sortkey@printedform ,
# so the two halves need DIFFERENT escaping -- the sort key is plain text
# makeindex compares, the printed form is LaTeX it typesets.
_IDX_CTRL = '!@|"'                       # makeindex control characters
_TEX_ESC = {'\\': '\\textbackslash{}', '{': '\\{', '}': '\\}', '$': '\\$',
            '&': '\\&', '#': '\\#', '^': '\\^{}', '_': '\\_',
            '%': '\\%', '~': '\\~{}'}

def _idx_quote(s):                       # protect makeindex's own metacharacters
    return ''.join(('"' + c) if c in _IDX_CTRL else c for c in s)

def idx(name, note=''):
    key = _idx_quote(name)                                   # sorts on the bare name
    shown = _idx_quote(''.join(_TEX_ESC.get(c, c) for c in name))
    tail = (' (%s)' % note) if note else ''
    return '\\index{%s@\\texttt{%s}%s}' % (key, shown, tail)


HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC  = os.path.join(ROOT, "reference", "GLOSSARY.md")
OUT  = os.path.join(HERE, "app-glossary-generated.tex")


def esc(s):
    """LaTeX-escape prose.  Backtick and apostrophe are left as-is (they render
    as quotes), matching gen-tactics-ref.py."""
    out = []
    for c in s:
        out.append({'\\': r'\textbackslash{}', '&': r'\&', '%': r'\%', '$': r'\$',
                    '#': r'\#', '_': r'\_', '{': r'\{', '}': r'\}',
                    '~': r'\textasciitilde{}', '^': r'\textasciicircum{}'}.get(c, c))
    return ''.join(out)


def code_spans(s):
    r"""Markdown `x` -> \texttt{x}, everything else escaped."""
    parts = re.split(r'`([^`]*)`', s)
    out = []
    for i, p in enumerate(parts):
        out.append(r'\texttt{' + esc(p) + '}' if i % 2 else esc(p))
    return ''.join(out)


ENTRY = re.compile(r'^### `([^`]+)`\s+\*\((\w[\w-]*)\)\*\s*$')


def parse(md):
    """[(letter, [(name, kind, [detail-line, ...]), ...]), ...] in file order."""
    sections, cur_letter, cur_entries, cur = [], None, [], None

    def flush_entry():
        if cur is not None:
            cur_entries.append(cur)

    def flush_section():
        flush_entry()
        if cur_letter and cur_entries:
            sections.append((cur_letter, list(cur_entries)))

    for line in md.splitlines():
        m = re.match(r'^## (.+?)\s*$', line)
        if m:
            flush_section()
            cur_letter, cur_entries, cur = m.group(1), [], None
            continue
        if cur_letter is None:
            continue                      # preamble: the kind table and index
        m = ENTRY.match(line)
        if m:
            flush_entry()
            cur = (m.group(1), m.group(2), [])
            continue
        if cur is not None and line.strip():
            cur[2].append(line.rstrip())
    flush_section()
    return sections


HEAD = r"""%% app-glossary-generated.tex -- GENERATED by docs/gen-glossary.py from
%% reference/GLOSSARY.md.  Do not edit; re-run `make gen' in docs/.

\chapter{Glossary: every name, A to Z}
\label{app:glossary}

Every other listing in this manual and in the browser reference is grouped by
something: operators by class, structures by structure, tactics by task.  This
one has the ordering nobody has to learn.  It carries the whole
\emph{vocabulary} -- %(counts)s -- and no results: the theorems, axioms and
supports are catalogued in \texttt{THEOREMS.md}, \texttt{BY-OPERATOR.md} and
\texttt{PROOF-DEBT.md}, and each entry here says how many of them mention it.

At the REPL, \texttt{(glossary 'NAME)} prints one entry and
\texttt{(glossary "pat")} every name containing \texttt{pat}.

\begingroup
\small
\setlength{\parindent}{0pt}
"""

TAIL = r"""\endgroup
"""


def main():
    md = open(SRC, encoding="utf-8").read()
    counts = ""
    m = re.search(r'^Auto-generated by .*?\.\s+(\d+ names:.*?), in one alphabetical list\.',
                  md, re.M | re.S)
    if m:
        counts = esc(' '.join(m.group(1).split()))
    sections = parse(md)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEAD % {"counts": counts or "the system's names"})
        for letter, entries in sections:
            f.write("\n\\section*{%s}\n" % esc(letter))
            f.write("\\addcontentsline{toc}{section}{%s}\n\n" % esc(letter))
            for name, kind, detail in entries:
                f.write("\\noindent\\textbf{\\texttt{%s}}\\quad\\textit{%s}%s\\\\\n"
                        % (esc(name), esc(kind), idx(name)))
                # Emit the entry's lines IN ORDER, switching to a verbatim quote
                # for the fenced blocks (the characterizing axiom's statement).
                chunk, in_code = [], False
                def flush_prose():
                    if chunk:
                        f.write(" \\\\\n".join(chunk) + "\n")
                        chunk.clear()
                for d in detail:
                    if d.strip().startswith("```"):
                        if not in_code:
                            flush_prose()
                            f.write("\\begin{quote}\\ttfamily\\footnotesize\\noindent\n")
                        else:
                            f.write("\\end{quote}\n")
                        in_code = not in_code
                        continue
                    if in_code:
                        f.write(esc(d) + "\n")
                        continue
                    # a browser cross-reference becomes plain prose in print
                    d = re.sub(r"\[mentioned by (\d+) result\(s\)\]\([^)]*\)",
                               r"mentioned by \1 result(s)", d)
                    # markdown *(kind)* -> italics.  AFTER code_spans, whose
                    # esc() would otherwise escape the backslash we insert.
                    chunk.append(re.sub(r"\*\(([^)]*)\)\*",
                                        r"\\textit{(\1)}", code_spans(d)))
                if in_code:
                    f.write("\\end{quote}\n")
                flush_prose()
                f.write("\n\\smallskip\n\n")
        f.write(TAIL)
    n = sum(len(e) for _, e in sections)
    print("gen-glossary: %d names, %d sections -> %s"
          % (n, len(sections), os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
