#!/usr/bin/env python3
r"""Generate the "Source file overview" appendix (app-source-generated.tex) from
the actual source tree.

The manual's source appendix used to be hand-written and went badly stale (it
listed ~12 of ~80 structure files and called theorem-library/ "just axioms.scm").
This emitter harvests the one-line `;;; <name>.scm -- <description>` header that
nearly every source file already carries, so the appendix is regenerated from the
tree and cannot drift.

  Enumerated with descriptions:  root *.scm  and  structure-library/*.scm
  Summarized (too many to list): theorem-library/ (~proof scripts),
                                 calculus/ (probes, not in load.scm)
  The exhaustive per-structure / per-theorem indexes live in the generated
  browser docs (reference/STRUCTURE-INDEX.md, THEOREMS.md, BY-TOPIC.md).

Run:  python3 docs/gen-source-appendix.py
Emits: docs/app-source-generated.tex  (\input by ch-source.tex)
"""
import os, re, glob

HERE  = os.path.dirname(os.path.abspath(__file__))
ROOT  = os.path.dirname(HERE)                       # ~/prover
OUT   = os.path.join(HERE, "app-source-generated.tex")

HEADER_RE = re.compile(r'^;;;\s*(?P<name>[\w.-]+)\s*(?:--|—|-)\s*(?P<desc>.*\S)\s*$')

def latex_escape(s):
    # Escape the LaTeX specials that appear in header prose.  Arrows like -> and
    # <= are left as literal text (T1 fontenc renders them fine).
    repl = {'\\': r'\textbackslash{}', '&': r'\&', '%': r'\%', '$': r'\$',
            '#': r'\#', '_': r'\_', '{': r'\{', '}': r'\}',
            '~': r'\textasciitilde{}', '^': r'\textasciicircum{}'}
    return ''.join(repl.get(c, c) for c in s)

def harvest(path):
    """Return the one-line description from a file's `;;; name -- desc` header,
    or '' if none.  Reads only the first handful of comment lines."""
    base = os.path.basename(path)
    try:
        with open(path, encoding='utf-8', errors='replace') as f:
            for _ in range(8):
                line = f.readline()
                if not line:
                    break
                m = HEADER_RE.match(line.rstrip('\n'))
                if m and m.group('name').lower() == base.lower():
                    desc = m.group('desc').rstrip('.')
                    # keep it to one clause: cut at the first sentence break
                    for stop in ('.  ', '; ', ' -- '):
                        i = desc.find(stop)
                        if 0 < i < 160:
                            desc = desc[:i]
                            break
                    if len(desc) > 160:
                        desc = desc[:157].rstrip() + '…'
                    return desc
    except OSError:
        pass
    return ''

def files_in(subdir):
    d = os.path.join(ROOT, subdir) if subdir else ROOT
    pat = os.path.join(d, '*.scm')
    return sorted(glob.glob(pat), key=lambda p: os.path.basename(p).lower())

def longtable(files):
    rows = []
    for p in files:
        base = os.path.basename(p)
        desc = harvest(p) or '\\textit{(no header)}'
        if not desc.startswith('\\textit'):
            desc = latex_escape(desc)
            desc = re.sub(r'"([^"]*)"', r"``\1''", desc)   # straight -> LaTeX quotes
        rows.append(r'\texttt{%s} & %s \\' % (latex_escape(base), desc))
    return ('\\begin{longtable}{@{}p{0.30\\textwidth}p{0.63\\textwidth}@{}}\n'
            '\\toprule\n\\textbf{File} & \\textbf{Description} \\\\\n\\midrule\n'
            '\\endhead\n' + '\n'.join(rows) + '\n\\bottomrule\n\\end{longtable}\n')

def main():
    root_files = [p for p in files_in('') ]
    struct     = files_in('structure-library')
    n_thm      = len(files_in('theorem-library'))
    n_calc     = len(files_in('calculus'))
    emacs      = sorted(glob.glob(os.path.join(ROOT, 'emacs', '*')),
                        key=lambda p: os.path.basename(p).lower())

    with open(OUT, 'w', encoding='utf-8') as o:
        o.write('%% AUTO-GENERATED by docs/gen-source-appendix.py -- do not edit by hand.\n')
        o.write('%% Regenerate:  python3 docs/gen-source-appendix.py\n')
        o.write('%% Descriptions are harvested from each file\'s `;;; name -- desc\' header.\n\n')

        o.write('\\section{Kernel and subsystems (\\texttt{\\textasciitilde/prover/})}\n')
        o.write('\\label{sec:src-root}\n')
        o.write('The %d Scheme files at the root of the tree: the proof kernel, the '
                'reader, the theory record, the interactive command layer, and the '
                'documentation / proof-printing / driver subsystems.\n\n' % len(root_files))
        o.write(longtable(root_files))

        o.write('\n\\section{\\texttt{structure-library/}}\n')
        o.write('\\label{sec:src-structure-library}\n')
        o.write('The %d files that install definitions, structures, vocabulary, and '
                'warranted supports.  One file per structure or cluster; the always-current '
                'per-structure listing (declaration, slots, parent, theorems) is the '
                'generated \\texttt{reference/STRUCTURE-INDEX.md}.\n\n' % len(struct))
        o.write(longtable(struct))

        o.write('\n\\section{\\texttt{theorem-library/} and \\texttt{calculus/}}\n')
        o.write('\\label{sec:src-libraries}\n')
        o.write('\\texttt{theorem-library/} holds %d proof scripts, each reaching '
                '\\texttt{(qed \\ldots)} and gated into the library load; by convention '
                '\\texttt{X-proof.scm} proves \\texttt{X}.  \\texttt{calculus/} holds %d '
                'probes and stress tests that are \\emph{not} in \\texttt{load.scm}.  '
                'Rather than enumerate them here, the theorems they prove are indexed, '
                'with statements and per-file links, in the generated browser references '
                '\\texttt{reference/THEOREMS.md} (flat) and \\texttt{reference/BY-TOPIC.md} '
                '(grouped like a textbook table of contents).\n\n' % (n_thm, n_calc))

        o.write('\\section{Emacs interface (\\texttt{emacs/}) and generated docs}\n')
        o.write('\\label{sec:src-emacs}\n')
        o.write('The workspace front end lives in \\texttt{emacs/}:\n')
        o.write('\\begin{itemize}[label=$\\circ$, leftmargin=0.85cm]\n')
        for p in emacs:
            base = os.path.basename(p)
            o.write('\\item \\texttt{%s}\n' % latex_escape(base))
        o.write('\\end{itemize}\n')
        o.write('The \\texttt{reference/} directory is entirely \\emph{generated} on '
                'prover load (\\texttt{STRUCTURE-INDEX}, \\texttt{TACTICS}, '
                '\\texttt{OPERATORS}, \\texttt{THEOREMS}, \\texttt{BY-TOPIC}, '
                '\\texttt{PROOF-DEBT}, \\ldots) as \\texttt{.md}, converted to the browser '
                'HTML by \\texttt{reference/build-reference-html.py}; it is never '
                'hand-edited.\n')

    n = len(root_files) + len(struct)
    print('wrote %s  (%d files enumerated: %d root + %d structure-library; '
          '%d theorem-library + %d calculus summarized)'
          % (os.path.relpath(OUT, ROOT), n, len(root_files), len(struct), n_thm, n_calc))

if __name__ == '__main__':
    main()
