#!/usr/bin/env python3
r"""gen-kernel-ops.py -- emit docs/ch-kernel-ops-generated.tex, the list of KERNEL OPERATIONS,
from the registry *kernel-rule-tags* in ../tactics-help.scm.

That registry is the list the system itself checks at every start: `kernel-rules-audit'
compares it, in both directions, with the rule names actually recorded during the load.  The
manual's list is generated from it so that the two cannot disagree.  Each entry of the registry
is  (name kind "gloss")  with kind one of schema / logic / rewrite / oracle.

It also emits \VNBaxiomcount, the number of entries under "Axioms -- the fixed VNB base" in
reference/THEOREMS.md (the catalog the prover writes at every load), so that the manual never
carries a hand-typed axiom count; and it warns when reference/KERNEL.md states a different one."""
import re, os, sys
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)
src = open(os.path.join(here, '..', 'tactics-help.scm')).read()
a = src.index('(define *kernel-rule-tags*')
b = src.index('(define (kernel-rules-documented)')
block = src[a:b]
entries = re.findall(r'\(([a-z0-9-]+)\s+(schema|logic|rewrite|oracle)\s+"((?:[^"\\]|\\.)*)"\)', block)
if len(entries) < 60:
    sys.exit("gen-kernel-ops: only %d entries parsed from *kernel-rule-tags*" % len(entries))

def tex(s):
    s = s.replace('\\"', '"')
    out = []
    for ch in s:
        out.append({'&': r'\&', '%': r'\%', '#': r'\#', '_': r'\_', '{': r'\{', '}': r'\}',
                    '<': r'\textless{}', '>': r'\textgreater{}', '^': r'\^{}', '~': r'\~{}'}.get(ch, ch))
    return ''.join(out)

def axiom_count():
    """Entries under '### Axioms' in reference/THEOREMS.md, up to the next '###' heading.
    Each entry is a list item of the form  - `name` -- statement."""
    path = os.path.join(root, 'reference', 'THEOREMS.md')
    n, inside = 0, False
    for line in open(path):
        if line.startswith('### '):
            inside = line.startswith('### Axioms')
        elif inside and line.startswith('- `'):
            n += 1
    if n == 0:
        sys.exit('gen-kernel-ops: no axioms found under "### Axioms" in reference/THEOREMS.md')
    return n

def kernel_md_axiom_count():
    """The count reference/KERNEL.md states in its part (c), or None.  KERNEL.md is written
    by hand, so the two can drift; the warning is the only thing that notices."""
    path = os.path.join(root, 'reference', 'KERNEL.md')
    try:
        text = open(path).read()
    except OSError:
        return None
    m = re.search(r'provenance `primitive`:\s*([0-9]+)\s+of them', text)
    return int(m.group(1)) if m else None

GROUPS = [('logic',   'Logic, equality, induction and the structure eliminators'),
          ('schema',  'Set formation, descriptions and functions'),
          ('rewrite', 'Rewriting'),
          ('oracle',  'Oracles')]
naxioms = axiom_count()
lines = ['%% GENERATED by gen-kernel-ops.py from *kernel-rule-tags* (tactics-help.scm).  Do not edit.',
         '\\newcommand{\\VNBkernelopcount}{%d}' % len(entries),
         '\\newcommand{\\VNBaxiomcount}{%d}' % naxioms]
for kind, _ in GROUPS:
    n = sum(1 for e in entries if e[1] == kind)
    lines.append('\\newcommand{\\VNBkernelopcount%s}{%d}' % (kind, n))
lines.append('\\newcommand{\\VNBkerneloptable}{%')
lines.append('\\begin{longtable}{@{}p{0.34\\textwidth}p{0.62\\textwidth}@{}}')
for kind, title in GROUPS:
    es = [e for e in entries if e[1] == kind]
    lines.append('\\multicolumn{2}{@{}l}{\\textbf{%s} (%d)}\\\\[2pt]' % (title, len(es)))
    for name, _, gloss in es:
        lines.append('\\texttt{%s}\\index{%s@\\texttt{%s} (kernel operation)} & %s\\\\' % (tex(name), name, tex(name), tex(gloss)))
    lines.append('\\\\[-4pt]')
lines.append('\\end{longtable}}')
open(os.path.join(here, 'ch-kernel-ops-generated.tex'), 'w').write('\n'.join(lines) + '\n')
print("gen-kernel-ops: %d kernel operations (%s); %d axioms" % (len(entries),
      ', '.join('%s %d' % (k, sum(1 for e in entries if e[1] == k)) for k, _ in GROUPS),
      naxioms))
stated = kernel_md_axiom_count()
if stated is not None and stated != naxioms:
    print("*** WARNING: reference/KERNEL.md part (c) says %d axioms; THEOREMS.md has %d."
          % (stated, naxioms))
    print("***   KERNEL.md is written by hand.  Correct the number there.")
