#!/usr/bin/env python3
r"""Generate the manual's pre-loaded-structures listing (app-structures-generated.tex)
from the prover-generated reference/STRUCTURE-INDEX.md.

STRUCTURE-INDEX.md is emitted on every prover load with, per structure, the real
`declare-structure` form (correct slots/accessors), the defining `is-X` predicate,
and the theorems quantifying over it.  This converter renders a curated core set to
LaTeX: each structure's declaration (verbatim, so no escaping) plus its
characteristic theorem names, with the full statements left to the browser index.

Names are shown as STORED (lower-case): VNB folds case, so `MONOID` = `monoid`.

Run:   python3 docs/gen-structures.py
Emits: docs/app-structures-generated.tex   (\input by ch-defs.tex)
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC  = os.path.join(ROOT, "reference", "STRUCTURE-INDEX.md")
OUT  = os.path.join(HERE, "app-structures-generated.tex")

# Curated core chain, in reading order, with display titles.
CURATED = [
    ("semigroup",     "Semigroup"),
    ("monoid",        "Monoid"),
    ("comm-monoid",   "Commutative monoid"),
    ("group",         "Group"),
    ("abelian-group", "Abelian group"),
    ("ring",          "Ring"),
    ("metric-space",  "Metric space"),
]
MAX_THMS = 6

def esc(s):
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'),
                 ('$', r'\$'), ('#', r'\#'), ('_', r'\_'), ('{', r'\{'),
                 ('}', r'\}'), ('~', r'\textasciitilde{}'), ('^', r'\textasciicircum{}')]:
        s = s.replace(a, b)
    return s

def parse(md):
    """name -> {'file':.., 'decl':.., 'thms':[names]}"""
    entries = {}
    blocks = re.split(r'^### (?=\S)', md, flags=re.M)
    for b in blocks[1:]:
        name = b.splitlines()[0].strip()
        fm = re.search(r'\*Declared in\* \[`([^`]+)`\]', b)
        dm = re.search(r'```scheme\n(.*?)\n```', b, re.S)
        thms = re.findall(r'^- `([^`]+)` — ', b, flags=re.M)
        thms = [t for t in thms if not t.endswith('-rev')]   # drop auto reverse companions
        entries[name] = {'file': fm.group(1) if fm else None,
                         'decl': dm.group(1) if dm else None,
                         'thms': thms}
    return entries

def render(entries):
    o = ['%% AUTO-GENERATED by docs/gen-structures.py from reference/STRUCTURE-INDEX.md -- do not edit.',
         '%% Regenerate:  python3 docs/gen-structures.py   (after a prover load refreshes STRUCTURE-INDEX.md)',
         '']
    for key, title in CURATED:
        e = entries.get(key)
        if not e or not e['decl']:
            continue
        o.append(r'\subsubsection{%s}' % esc(title))
        if e['file']:
            o.append(r'Declared in \texttt{%s}.' % esc(e['file']))
        o.append(r'\begin{VNBcode}')
        o.append(e['decl'])            # verbatim: no escaping
        o.append(r'\end{VNBcode}')
        o.append(r'The characteristic laws are the \texttt{(property \ldots)} clauses; the '
                 r'theorems quantifying over \texttt{is-%s}, with statements, are in '
                 r'\texttt{reference/STRUCTURE-INDEX.md} and \texttt{reference/BY-TOPIC.md}.'
                 % esc(key))
        o.append('')
    return '\n'.join(o)

def main():
    md = open(SRC, encoding='utf-8').read()
    entries = parse(md)
    txt = render(entries)
    open(OUT, 'w', encoding='utf-8').write(txt + '\n')
    got = [k for k, _ in CURATED if k in entries and entries[k]['decl']]
    print('wrote %s  (%d structures: %s)'
          % (os.path.relpath(OUT, ROOT), len(got), ', '.join(got)))

if __name__ == '__main__':
    main()
