#!/usr/bin/env python3
r"""Generate the manual's categories listing (app-categories-generated.tex) from the
prover-generated reference/CATEGORIES.md.

CATEGORIES.md is written on every prover load by (write-categories-md) in
interactive.scm: the default category of every structure (its arrows, how they are
defined, the status of the three category laws), the categories declared beside a
structure with declare-category!, and the inclusions between categories, found by
the shape of the theorems.  This converter renders the same three parts as LaTeX:
a table of the default categories, a paragraph per declared category with its
defining equivalence verbatim, and the list of inclusions.

Names are shown as STORED (lower-case): VNB folds case.

Run:   python3 docs/gen-categories.py
Emits: docs/app-categories-generated.tex   (\input by ch-defs.tex)
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC  = os.path.join(ROOT, "reference", "CATEGORIES.md")
OUT  = os.path.join(HERE, "app-categories-generated.tex")

def esc(s):
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'),
                 ('$', r'\$'), ('#', r'\#'), ('_', r'\_'), ('{', r'\{'),
                 ('}', r'\}'), ('~', r'\textasciitilde{}'), ('^', r'\textasciicircum{}'),
                 ('<', r'\textless{}'), ('>', r'\textgreater{}')]:
        s = s.replace(a, b)
    return s

def inline(md):
    """Markdown inline -> LaTeX: `code` becomes \texttt, [text](url) its text, the rest escaped."""
    md = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', md)
    out, i = [], 0
    for m in re.finditer(r'`([^`]*)`', md):
        out.append(esc(md[i:m.start()]))
        out.append(r'\texttt{%s}' % esc(m.group(1)))
        i = m.end()
    out.append(esc(md[i:]))
    txt = ''.join(out).replace(' -- ', ' --- ')
    # *emphasis* (the source links read "*Declared in* ...")
    return re.sub(r'\*([^*]+)\*', r'\\emph{\1}', txt)

def section(md, heading):
    m = re.search(r'^## %s\n(.*?)(?=^## |\Z)' % re.escape(heading), md, re.S | re.M)
    return m.group(1) if m else ''

def render_defaults(body):
    rows = []
    for line in body.splitlines():
        if not line.startswith('| `'): continue
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if len(cells) != 7: continue
        rows.append(cells)
    o = [r'\begin{longtable}{@{}p{3.1cm}p{5.2cm}p{2.9cm}p{2.2cm}@{}}',
         r'\toprule', r'structure & arrows & defined & laws \\', r'\midrule', r'\endhead']
    for st, arrows, how, hs, idl, comp, inset in rows:
        laws = []
        for lab, cell in (('id', idl), ('compose', comp), ('in-set', inset)):
            status = cell.split(' -- ')[-1] if ' -- ' in cell else cell
            laws.append((lab, status))
        if all(s == 'proven' for _, s in laws):
            lawtxt = 'proven'
        else:
            lawtxt = '; '.join('%s: %s' % (l, s) for l, s in laws)
        how = how.replace('declared by `declare-hom!`', r'\texttt{declare-hom!}')
        how = how.replace('generated from the slot list', 'generated')
        how = re.sub(r'refinement of `([^`]+)`: its parent.s arrows', r'refinement of `\1`', how)
        o.append(r'%s & %s & %s & %s \\' % (inline(st), inline(arrows), inline(how), esc(lawtxt)))
    o += [r'\bottomrule', r'\end{longtable}']
    return '\n'.join(o)

def render_declared(body):
    o = []
    blocks = re.split(r'^### ', body, flags=re.M)
    for b in blocks[1:]:
        lines = b.splitlines()
        head = lines[0].strip()
        m = re.match(r'`([^`]+)`, a category on `([^`]+)`', head)
        title = ('%s, on %s' % (m.group(1), m.group(2))) if m else head
        o.append(r'\paragraph{\texttt{%s}}' % esc(title))
        rest = '\n'.join(lines[1:])
        code = re.search(r'```\n(.*?)\n```', rest, re.S)
        prose = re.sub(r'```\n.*?\n```', '', rest, flags=re.S)
        for para in [p.strip() for p in prose.split('\n\n') if p.strip()]:
            if para.startswith('Definition ('):
                o.append(inline(para))
                if code:
                    o.append(r'\begin{VNBsnip}')
                    o.append(code.group(1))
                    o.append(r'\end{VNBsnip}')
            else:
                o.append(inline(para))
            o.append('')
    return '\n'.join(o)

def render_inclusions(body):
    items = [l[2:].strip() for l in body.splitlines() if l.startswith('- ')]
    if not items: return 'None.'
    o = [r'\begin{itemize}']
    for it in items:
        m = re.match(r'`([^`]+)` \(([^)]*)\): `(.*)`$', it)
        if m:
            o.append(r'\item \texttt{%s} (%s): \texttt{%s}' % (esc(m.group(1)), esc(m.group(2)), esc(m.group(3))))
        else:
            o.append(r'\item ' + inline(it))
    o.append(r'\end{itemize}')
    return '\n'.join(o)

def main():
    md = open(SRC, encoding='utf-8').read()
    o = ['%% AUTO-GENERATED by docs/gen-categories.py from reference/CATEGORIES.md -- do not edit.',
         '%% Regenerate:  python3 docs/gen-categories.py   (after a prover load refreshes CATEGORIES.md)',
         '',
         r'\subsubsection{The default categories}',
         'One per structure with a morphism predicate.  The laws column reads ``proven\'\' when '
         'the identity law, the composition law and the sethood of the hom-set are all proven theorems; '
         'otherwise it names the law and its status.',
         '',
         render_defaults(section(md, 'Default categories')),
         '',
         r'\subsubsection{The declared categories}',
         '',
         render_declared(section(md, 'Declared categories')),
         r'\subsubsection{Inclusions}',
         r'Theorems of the form $P(a, b, f) \Rightarrow Q(a, b, f)$ for two arrow predicates, or '
         r'$H_1(a, b) \subseteq H_2(a, b)$ for two hom-sets, found by shape.',
         '',
         render_inclusions(section(md, 'Inclusions')),
         '']
    open(OUT, 'w', encoding='utf-8').write('\n'.join(o))
    n_def = len([l for l in section(md, 'Default categories').splitlines() if l.startswith('| `')])
    n_cat = section(md, 'Declared categories').count('\n### ')
    print('wrote %s  (%d default categories, %d declared)' % (os.path.relpath(OUT, ROOT), n_def, n_cat))

if __name__ == '__main__':
    main()
