;;; actproof.scm -- drive elem-f-action (3-way column split).  Loads AFTER load.scm.
(define (mlast) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (mfoc! n) (set-proof-state-focus! *ps* n))
(define (mgoal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mdi*) (let lp () (let* ((g (mgoal))(h (and (pair? g)(car g))))
                 (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (mprobe tag) (display ";; --- ")(display tag)(display " ---")(newline)
  (display ";; GOAL: ")(write (mgoal))(newline))
(define (mem P)
  (cut `(OR ,P (NOT ,P)))
  (let ((uo (mlast)))
    (pbc)(cut `(NOT ,P))
    (let ((un (mlast)))
      (di)(cut `(OR ,P (NOT ,P)))
      (let ((u2 (mlast)))(oi-l)(ass)(mfoc! u2))
      (ai `(NOT (OR ,P (NOT ,P))))(mfoc! un))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (mlast)))(oi-r)(ass)(mfoc! u3))
    (ai `(NOT (OR ,P (NOT ,P))))(mfoc! uo)))
(define (mcases P) (mem P)(ai `(OR ,P (NOT ,P)))(mlast))

(define RAG '(RING-ADDITIVE-AG A))
(define INT '(INTERVAL 1 n))
(define FFF '(VNB-LAMBDA j ((MUL A) (ENTRY P i j) (ENTRY (ELEM-F A n k l) j c))))
(set! *vnb-quiet* #t)

;; a single-support column collapse: goal (= (FINSUM RAG FFF INT) (ENTRY P i ROW)),
;; support at j0=ROW, off-support PSS `offpss' (applied as (fact offpss A n k l jz c)),
;; at-support PSS `atpss' (applied as (fact atpss A n k l c)) giving F_{ROW,c}=ONE.
(define (collapse-at ROW offpss atpss)
  (cut `(FORALL jz (IMPLIES (IN jz ,INT)
          (IMPLIES (NOT (= jz ,ROW)) (= (,FFF jz) (IDEN ,RAG))))))
  (let ((mn (mlast)))
    (di)(di)(di)
    (lam-b)
    (fact offpss 'A 'n 'k 'l 'jz 'c)
    (subst `(= (ENTRY (ELEM-F A n k l) jz c) (ZERO A)))
    (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i 'jz)
    (fact 'ring-mul-zero-right 'A '(ENTRY P i jz))
    (subst `(= ((MUL A) (ENTRY P i jz) (ZERO A)) (ZERO A)))
    (fact 'ras-id 'A)
    (subst `(= (IDEN (RING-ADDITIVE-AG A)) (ZERO A)))
    (rfl)
    (mfoc! mn))
  (fact 'finsum-single-support RAG INT FFF ROW)
  (subst `(= (FINSUM ,RAG ,FFF ,INT) (,FFF ,ROW)))
  (lam-b)
  (fact atpss 'A 'n 'k 'l 'c)
  (subst `(= (ENTRY (ELEM-F A n k l) ,ROW c) (ONE A)))
  (fact 'entry-in-carrier 'm 'n '(CARR A) 'P 'i ROW)
  (fact 'ring-mul-right-id 'A `(ENTRY P i ,ROW))
  (subst `(= ((MUL A) (ENTRY P i ,ROW) (ONE A)) (ENTRY P i ,ROW)))
  (rfl))

(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL m (FORALL n (FORALL P (FORALL k (FORALL l
       (IMPLIES (IN P (MAT m n (CARR A)))
       (IMPLIES (IN k (INTERVAL 1 n))
       (IMPLIES (IN l (INTERVAL 1 n))
       (IMPLIES (NOT (= k l))
       (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
       (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
         (= (ENTRY (MATMUL A P (ELEM-F A n k l)) i c)
            (IF (= c k) (ENTRY P i l)
                (IF (= c l) (ENTRY P i k) (ENTRY P i c)))))))))))))))))))))
(mdi*)
(fact 'elem-f-type 'A 'n 'k 'l)
(fact 'matmul-entry 'A 'm 'n 'n 'P '(ELEM-F A n k l) 'i 'c)
(subst `(= (ENTRY (MATMUL A P (ELEM-F A n k l)) i c) (FINSUM ,RAG ,FFF ,INT)))
(fact 'ring-additive-ag-is-abelian-group 'A)
(fact 'interval-in-set 1 'n)
(fact 'interval-card-in-nn 1 'n)
(fact 'matprod-summand-type 'A 'm 'n 'n 'P '(ELEM-F A n k l) 'i 'c)
(mprobe "f: after setup")

(define fnotk (mcases '(= c k)))
;; ---- c = k : RHS = P_{il}, support at row l ----
(if-true '(IF (= c k) (ENTRY P i l) (IF (= c l) (ENTRY P i k) (ENTRY P i c))))
(define frk (mlast)) (ass) (mfoc! frk)
(subst '(= (IF (= c k) (ENTRY P i l) (IF (= c l) (ENTRY P i k) (ENTRY P i c))) (ENTRY P i l)))
(collapse-at 'l 'elem-f-ck-off 'elem-f-ck-at)
(mprobe "f: c=k done")

;; ---- c /= k ----
(mfoc! fnotk)
(if-false '(IF (= c k) (ENTRY P i l) (IF (= c l) (ENTRY P i k) (ENTRY P i c))))
(define frnk (mlast)) (ass) (mfoc! frnk)
(subst '(= (IF (= c k) (ENTRY P i l) (IF (= c l) (ENTRY P i k) (ENTRY P i c)))
           (IF (= c l) (ENTRY P i k) (ENTRY P i c))))
(define fnotl (mcases '(= c l)))
;; ---- c = l : RHS = P_{ik}, support at row k ----
(if-true '(IF (= c l) (ENTRY P i k) (ENTRY P i c)))
(define frl (mlast)) (ass) (mfoc! frl)
(subst '(= (IF (= c l) (ENTRY P i k) (ENTRY P i c)) (ENTRY P i k)))
(collapse-at 'k 'elem-f-cl-off 'elem-f-cl-at)
(mprobe "f: c=l done")
;; ---- c /= k, c /= l : RHS = P_{ic}, support at row c ----
(mfoc! fnotl)
(if-false '(IF (= c l) (ENTRY P i k) (ENTRY P i c)))
(define frnl (mlast)) (ass) (mfoc! frnl)
(subst '(= (IF (= c l) (ENTRY P i k) (ENTRY P i c)) (ENTRY P i c)))
(collapse-at 'c 'elem-f-co-off 'elem-f-co-at)

(newline)
(display (if (proof-done? *ps*)
             ";; *** elem-f-action: PROOF COMPLETE ***"
             ";; !!! elem-f-action: STILL OPEN"))
(newline)
