;;; scratchpad/beb.scm -- bordered-eq-border: C with cleared row1/col1 = BORDER(C11, SUBMAT C).
(set! *vnb-quiet* #t)
(define (bm-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (bm-di*) (let lp () (let* ((g (bm-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (bm-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (bm-foc! n) (set-proof-state-focus! *ps* n))
(define (bm-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (bm-find pred) (let lp ((as (bm-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (bm-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))
(define (impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))
(define (bm-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((use-or (bm-last)))
    (pbc) (cut `(NOT ,P))
    (let ((use-notp (bm-last)))
      (di) (cut `(OR ,P (NOT ,P)))
      (let ((u2 (bm-last))) (oi-l) (ass) (bm-foc! u2))
      (ai `(NOT (OR ,P (NOT ,P)))) (bm-foc! use-notp))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (bm-last))) (oi-r) (ass) (bm-foc! u3))
    (ai `(NOT (OR ,P (NOT ,P)))) (bm-foc! use-or)))
(define (bm-cases P) (bm-em P) (ai `(OR ,P (NOT ,P))) (bm-last))

(define C11 '(ENTRY C 1 1))
(define SC '(SUBMAT C p q))
(define BC (list 'BORDER 'A C11 SC 'p 'q))
(define ROWH (list 'FORALL 'j (impl* (list '(IN j (INTERVAL 1 (succ q))) '(NOT (= j 1)))
                    (list '= '(ENTRY C 1 j) '(ZERO A)))))
(define COLH (list 'FORALL 'i (impl* (list '(IN i (INTERVAL 1 (succ p))) '(NOT (= i 1)))
                    (list '= '(ENTRY C i 1) '(ZERO A)))))

(sp (make-wff (list 'FORALL 'A (list 'IMPLIES '(IS-RING A) (fa* '(p q C)
    (impl* (list '(IN p NN) '(IN q NN) '(IN C (MAT (succ p) (succ q) (CARR A))) ROWH COLH)
      (list '= 'C BC)))))))
(bm-di*)
(fact 'submat-type 'A 'p 'q 'C)
(fact 'one-in-interval 'p) (fact 'one-in-interval 'q)   ; 1 in interval(1,succ p/q) -> makes C11-in-carr + border-type bare
(fact 'entry-in-carrier '(succ p) '(succ q) '(CARR A) 'C 1 1)
(fact 'border-type 'A C11 SC 'p 'q)
;; ROWH/COLH are the literal cleared-row/col hypotheses -- use them directly.
;; (bm-find on cadr='j/'i mis-grabbed the entry-in-carrier typing lemma's forall ancestor.)
(define ROWHc ROWH)
(define COLHc COLH)
(cut (fa* '(row) (impl* '((IN row (INTERVAL 1 (succ p))))
       (fa* '(col) (impl* '((IN col (INTERVAL 1 (succ q))))
         (list '= (list 'ENTRY 'C 'row 'col) (list 'ENTRY BC 'row 'col)))))))
(bm-di*)
(fact 'interval-elt-in-nn 1 '(succ p) 'row) (fact 'interval-lo 1 '(succ p) 'row)
(fact 'interval-elt-in-nn 1 '(succ q) 'col) (fact 'interval-lo 1 '(succ q) 'col)
(call-with-output-file "scratchpad/DBG.txt" (lambda(port)
  (for-each (lambda(a)(let ((w (expression->string (wff-formula a))))
     (when (or (substring? "in interval" w)(substring? "= entry" w)) (display w port)(newline port))))
    (sequent-node-assumptions (proof-state-focus *ps*)))
  (display (list 'GOAL (expression->string (bm-goal))) port)(newline port)))
(define NEQi1 (bm-cases '(= row 1)))
;; ---- row = 1 ----
(subst '(= row 1))
(define NEQj1a (bm-cases '(= col 1)))
;; row=1,col=1
(subst '(= col 1))
(fact 'border-entry-11 'A C11 SC 'p 'q) (subst (list '= (list 'ENTRY BC 1 1) C11)) (rfl)
(bm-foc! NEQj1a)
;; row=1,col/=1 : both 0
(fact 'border-entry-1j 'A C11 SC 'p 'q 'col) (subst (list '= (list 'ENTRY BC 1 'col) '(ZERO A)))
(inst+ ROWHc 'col) (ass)
;; ---- row /= 1 ----
(bm-foc! NEQi1)
(define NEQj1b (bm-cases '(= col 1)))
;; row/=1,col=1 : both 0
(subst '(= col 1))
(fact 'border-entry-i1 'A C11 SC 'p 'q 'row) (subst (list '= (list 'ENTRY BC 'row 1) '(ZERO A)))
(inst+ COLHc 'row) (ass)
(bm-foc! NEQj1b)
;; row/=1,col/=1 : block = SUBMAT_{row-1,col-1} = C_{row,col}
(fact 'border-entry-block2 'A C11 SC 'p 'q 'row 'col)
(subst (list '= (list 'ENTRY BC 'row 'col) (list 'ENTRY SC '(NN-MINUS row 1) '(NN-MINUS col 1))))
(fact 'pred-in-interval 'p 'row) (fact 'pred-in-interval 'q 'col)
(fact 'entry-of-submat 'C 'p 'q '(NN-MINUS row 1) '(NN-MINUS col 1))
(subst (list '= (list 'ENTRY SC '(NN-MINUS row 1) '(NN-MINUS col 1))
             (list 'ENTRY 'C '(succ (NN-MINUS row 1)) '(succ (NN-MINUS col 1)))))
(fact 'succ-nn-minus-1 'row) (subst '(= (succ (NN-MINUS row 1)) row))
(fact 'succ-nn-minus-1 'col) (subst '(= (succ (NN-MINUS col 1)) col))
(fact 'entry-in-carrier '(succ p) '(succ q) '(CARR A) 'C 'row 'col)
(rfl)
;; ---- extensionality ----
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) 'C))))
(fact 'matrix-entry-extensionality '(succ p) '(succ q) '(CARR A) 'C BC)
(ass)

(call-with-output-file "scratchpad/RESULT.txt" (lambda (port)
  (display (list 'done (proof-done? *ps*) 'open (length (proof-leaves))) port)(newline port)
  (for-each (lambda (s)(newline port)(display "GOAL: " port)
     (display (expression->string (wff-formula (sequent-node-assertion s))) port)(newline port)
     (when (substring? "1, col) = zero" (expression->string (wff-formula (sequent-node-assertion s))))
       (for-each (lambda (a)(let ((w (expression->string (wff-formula a))))
          (when (or #t)
            (display "   - " port)(display w port)(newline port)))) (sequent-node-assumptions s))))
   (proof-leaves))))
(display (list 'DONE (proof-done? *ps*) 'leaves (length (proof-leaves))))(newline)
