;;; scratchpad/bordering.scm -- bordering: G = BORDER(b,W), MAT-EQUIV(W,E)
;;;   =>  G ~ BORDER(b, E).   (W = block, G = full matrix, b = corner; W/G named to
;;;   avoid case-fold collision with MAT-EQUIV's params m/C.)
(set! *vnb-quiet* #t)
(define (bm-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (bm-di*) (let lp () (let* ((g (bm-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (bm-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (bm-foc! n) (set-proof-state-focus! *ps* n))
(define (bm-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (bm-find pred) (let lp ((as (bm-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (bm-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))
(define (impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))

(define BCE (list 'BORDER 'A 'b 'E 'p 'q))
(define GBORD (list 'BORDER 'A 'b 'W 'p 'q))

(sp (make-wff (list 'FORALL 'A (list 'IMPLIES '(IS-RING A) (fa* '(p q b W G E)
    (impl* (list '(IN p NN) '(IN q NN) '(IN b (CARR A))
                 '(IN W (MAT p q (CARR A)))
                 '(IN G (MAT (succ p) (succ q) (CARR A)))
                 (list '= 'G GBORD)
                 '(MAT-EQUIV A p q W E))
      (list 'MAT-EQUIV 'A '(succ p) '(succ q) 'G BCE)))))))
(bm-di*)
(mac-h 'MAT-EQUIV '(MAT-EQUIV A p q W E))
(ai 1) (ai 1) (ai 1) (ai 1)
(define EEQ (bm-find (lambda (z) (and (pair? z) (eq? (car z) '=) (eq? (cadr z) 'E)))))
(define RHS (caddr EEQ))                            ; (MATMUL A (MATMUL A U' W) V')
(define INNER (caddr RHS))                          ; (MATMUL A U' W)
(define UP (caddr INNER))                           ; U'
(define VP (cadddr RHS))                            ; V'
(define BU (list 'BORDER 'A '(ONE A) UP 'p 'p))
(define BV (list 'BORDER 'A '(ONE A) VP 'q 'q))
(fact 'border-invertible 'A 'p UP)
(fact 'border-invertible 'A 'q VP)
(fact 'ring-one-in 'A)
(fact 'invertible-mat-is-mat 'A 'p UP)
(fact 'invertible-mat-is-mat 'A 'q VP)
(mac 'MAT-EQUIV)
(ew BU) (di)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'IS-INVERTIBLE-MAT) (equal? (cadddr g) BU)))) (ass)
(bm-foc-goal! (H? 'FORSOME))
(ew BV) (di)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'IS-INVERTIBLE-MAT) (equal? (cadddr g) BV)))) (ass)
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) BCE))))
(subst (list '= 'G GBORD))
(fact 'border-mult 'A 'p 'p 'q UP 'W '(ONE A) 'b)
(subst (list '= (list 'MATMUL 'A BU GBORD)
             (list 'BORDER 'A (list '(MUL A) '(ONE A) 'b) (list 'MATMUL 'A UP 'W) 'p 'q)))
(fact 'ring-mul-left-id 'A 'b)
(subst (list '= (list '(MUL A) '(ONE A) 'b) 'b))
(fact 'matmul-type 'A 'p 'p 'q UP 'W)
(fact 'border-mult 'A 'p 'q 'q (list 'MATMUL 'A UP 'W) VP 'b '(ONE A))
(subst (list '= (list 'MATMUL 'A (list 'BORDER 'A 'b (list 'MATMUL 'A UP 'W) 'p 'q) BV)
             (list 'BORDER 'A (list '(MUL A) 'b '(ONE A)) (list 'MATMUL 'A (list 'MATMUL 'A UP 'W) VP) 'p 'q)))
(fact 'ring-mul-right-id 'A 'b)
(subst (list '= (list '(MUL A) 'b '(ONE A)) 'b))
(subst EEQ)
(fact 'matmul-type 'A 'p 'q 'q (list 'MATMUL 'A UP 'W) VP)   ; (U'.W).V' : p x q
(fact 'border-type 'A 'b (list 'MATMUL 'A (list 'MATMUL 'A UP 'W) VP) 'p 'q)
(rfl)

(call-with-output-file "scratchpad/RESULT.txt" (lambda (port)
  (display (list 'done (proof-done? *ps*) 'open (length (proof-leaves))) port)(newline port)
  (for-each (lambda (s)(newline port)(display "GOAL: " port)
     (display (expression->string (wff-formula (sequent-node-assertion s))) port)(newline port))
   (proof-leaves))))
(display (list 'DONE (proof-done? *ps*) 'leaves (length (proof-leaves))))(newline)
