;;; scratchpad/borderid.scm -- border-identity: BORDER(A,1,I_p,p,p) = I_{succ p}.
(set! *vnb-quiet* #t)
(define (bm-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (bm-di*) (let lp () (let* ((g (bm-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (bm-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (bm-foc! n) (set-proof-state-focus! *ps* n))
(define (bm-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))
(define (impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))
(define (bm-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((use-or (bm-last)))
    (pbc) (cut `(NOT ,P))
    (let ((use-notp (bm-last)))
      (di) (cut `(OR ,P (NOT ,P)))
      (let ((u2 (bm-last))) (oi-l) (ass) (bm-foc! u2))
      (ai `(NOT (OR ,P (NOT ,P)))) (bm-foc! use-notp))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (bm-last))) (oi-r) (ass) (bm-foc! u3))
    (ai `(NOT (OR ,P (NOT ,P)))) (bm-foc! use-or)))
(define (bm-cases P) (bm-em P) (ai `(OR ,P (NOT ,P))) (bm-last))

(define BI '(BORDER A (ONE A) (IDENTMAT A p) p p))
(define IM '(IDENTMAT A (succ p)))
(define IP '(IDENTMAT A p))

(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-RING A) (list 'FORALL 'p (list 'IMPLIES '(IN p NN)
    (list '= BI IM)))))))
(bm-di*)
(fact 'ring-one-in 'A)
(fact 'identmat-type 'A 'p)
(fact 'border-type 'A '(ONE A) IP 'p 'p)
(fact 'identmat-type 'A '(succ p))
(cut (fa* '(i) (impl* '((IN i (INTERVAL 1 (succ p))))
       (fa* '(j) (impl* '((IN j (INTERVAL 1 (succ p))))
         (list '= (list 'ENTRY BI 'i 'j) (list 'ENTRY IM 'i 'j)))))))
(bm-di*)
(fact 'entry-of-identmat 'A '(succ p) 'i 'j)
(define RIF '(IF (= i j) (ONE A) (ZERO A)))
(subst (list '= (list 'ENTRY IM 'i 'j) RIF))
;; interval facts for i,j
(fact 'interval-elt-in-nn 1 '(succ p) 'i) (fact 'interval-lo 1 '(succ p) 'i)
(fact 'interval-elt-in-nn 1 '(succ p) 'j) (fact 'interval-lo 1 '(succ p) 'j)

;; ===== EM on (= i j) =====
(define NEQij (bm-cases '(= i j)))
;; ---- i = j : RHS = ONE, LHS = ONE ----
(if-true RIF) (define c1 (bm-last)) (ass) (bm-foc! c1)
(subst (list '= RIF '(ONE A)))
(subst '(= i j))                                  ; collapse i -> j everywhere
;; now goal (= (ENTRY BI j j) (ONE A))
(define NEQj1a (bm-cases '(= j 1)))
;; j=1 (so i=j=1): border-entry-11 = ONE
(subst '(= j 1))
(fact 'border-entry-11 'A '(ONE A) IP 'p 'p) (subst (list '= (list 'ENTRY BI 1 1) '(ONE A))) (rfl)
(bm-foc! NEQj1a)
;; j/=1: block = IDENTMAT(p)_{j-1,j-1} = ONE
(fact 'border-entry-block2 'A '(ONE A) IP 'p 'p 'j 'j)
(subst (list '= (list 'ENTRY BI 'j 'j) (list 'ENTRY IP '(NN-MINUS j 1) '(NN-MINUS j 1))))
(fact 'pred-in-interval 'p 'j)
(fact 'entry-of-identmat 'A 'p '(NN-MINUS j 1) '(NN-MINUS j 1))
(define DIF (list 'IF (list '= '(NN-MINUS j 1) '(NN-MINUS j 1)) '(ONE A) '(ZERO A)))
(subst (list '= (list 'ENTRY IP '(NN-MINUS j 1) '(NN-MINUS j 1)) DIF))
(if-true DIF) (define c2 (bm-last)) (rfl) (bm-foc! c2)
(subst (list '= DIF '(ONE A))) (rfl)

;; ---- i /= j : RHS = ZERO, LHS = ZERO ----
(bm-foc! NEQij)
(if-false RIF) (define c3 (bm-last)) (ass) (bm-foc! c3)
(subst (list '= RIF '(ZERO A)))
(define NEQi1 (bm-cases '(= i 1)))
;; i=1 (so j/=1): border-entry-1j = ZERO
(subst '(= i 1))
(fact 'neq-sym 'i 'j)                             ; NOT(=j i) from NOT(=i j)
(cut '(NOT (= j 1)))
(define k1 (bm-last))
(fact 'eq-sym 'i 1) (subst '(= 1 i)) (ass)        ; goal NOT(=j 1) -> NOT(=j i)
(bm-foc! k1)
(fact 'border-entry-1j 'A '(ONE A) IP 'p 'p 'j) (subst (list '= (list 'ENTRY BI 1 'j) '(ZERO A))) (rfl)
(bm-foc! NEQi1)
;; i/=1
(define NEQj1b (bm-cases '(= j 1)))
;; j=1: border-entry-i1 = ZERO
(subst '(= j 1))
(fact 'border-entry-i1 'A '(ONE A) IP 'p 'p 'i) (subst (list '= (list 'ENTRY BI 'i 1) '(ZERO A))) (rfl)
(bm-foc! NEQj1b)
;; i/=1, j/=1: block = IDENTMAT(p)_{i-1,j-1} = ZERO (i-1 /= j-1)
(fact 'border-entry-block2 'A '(ONE A) IP 'p 'p 'i 'j)
(subst (list '= (list 'ENTRY BI 'i 'j) (list 'ENTRY IP '(NN-MINUS i 1) '(NN-MINUS j 1))))
(fact 'pred-in-interval 'p 'i) (fact 'pred-in-interval 'p 'j)
(fact 'entry-of-identmat 'A 'p '(NN-MINUS i 1) '(NN-MINUS j 1))
(define DIF2 (list 'IF (list '= '(NN-MINUS i 1) '(NN-MINUS j 1)) '(ONE A) '(ZERO A)))
(subst (list '= (list 'ENTRY IP '(NN-MINUS i 1) '(NN-MINUS j 1)) DIF2))
(fact 'nn-minus-1-inj 'i 'j)
(if-false DIF2) (define c4 (bm-last)) (ass) (bm-foc! c4)
(subst (list '= DIF2 '(ZERO A))) (rfl)

;; ===== back to main goal =====
(bm-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) BI))))
(fact 'matrix-entry-extensionality '(succ p) '(succ p) '(CARR A) BI IM)
(ass)

(call-with-output-file "scratchpad/RESULT.txt" (lambda (port)
  (display (list 'proof-done? (proof-done? *ps*) 'open (length (proof-leaves))) port)(newline port)
  (for-each (lambda (s)(newline port)(display "GOAL: " port)
     (display (expression->string (wff-formula (sequent-node-assertion s))) port)(newline port))
   (proof-leaves))))
(display (list 'DONE (proof-done? *ps*) 'leaves (length (proof-leaves))))(newline)
