(newline)(display "@@@ CLOBBER-CHECK")(newline)
(define (chk nm v)
  (display "@@@ ")(display nm)(display " => ")
  (if (procedure? v) (display "procedure") (begin (display "CLOBBERED: ") (write v)))
  (newline))
(chk 'bc bc) (chk 'bc* bc*) (chk 'inst inst) (chk 'inst+ inst+)
(chk 'ni ni) (chk 'di di) (chk 'ai ai) (chk 'ass ass)
(chk 'mac mac) (chk 'fact fact) (chk 'cut cut) (chk 'ew ew)
(chk 'subst subst) (chk 'sp sp) (chk 'qed qed)
(display "@@@ END")(newline)(%exit 0)
