;; For every view-specialized companion, report the provenance of its SOURCE.
(define views (map car (hash-table->alist *view-as-table*)))
(display ";; views: ") (write views) (newline)
(define bad '())
(for-each
 (lambda (v)
   (let* ((suffix (string-append "-" (string-downcase (symbol->string v)))))
     (for-each
      (lambda (entry)
        (let* ((nm (symbol->string (car entry))))
          (when (and (> (string-length nm) (string-length suffix))
                     (string=? suffix (substring nm (- (string-length nm) (string-length suffix))
                                                 (string-length nm))))
            (let* ((src (string->symbol (substring nm 0 (- (string-length nm) (string-length suffix))))))
              (when (hash-table-ref/default *theorem-table* src #f)
                (let ((psrc (provenance-of src)) (pcomp (provenance-of (car entry))))
                  (when (not (eq? psrc 'definitional))
                    (set! bad (cons (list (car entry) 'source: src 'src-prov: psrc 'comp-prov: pcomp) bad)))))))))
      (hash-table->alist *theorem-table*))))
 views)
(display ";; companions whose SOURCE is not definitional: ") (display (length bad)) (newline)
(for-each (lambda (b) (display ";;   ") (write b) (newline)) (sort bad (lambda (a b) (string<? (symbol->string (car a)) (symbol->string (car b))))))
