(load "load.scm")
(set! *vnb-quiet* #t)
(define (mq-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mq-di*) (let lp () (let* ((g (mq-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (report nm)
  (call-with-output-file "/tmp/claude-1000/-home-ubuntu/423ebffe-e6fe-4caf-8686-2808e8178391/scratchpad/RESULT.txt"
    (lambda (p) (write (list nm (proof-done? *ps*)
      (map (lambda (s) (wff-formula (sequent-node-assertion s))) (proof-leaves))) p))))
(sp (make-wff '(FORALL R (IMPLIES (IS-RING R) (FORALL m (FORALL n (FORALL A (FORALL U (FORALL V (IMPLIES (IN A (MAT m n (CARR R))) (IMPLIES (IS-INVERTIBLE-MAT R m U) (IMPLIES (IS-INVERTIBLE-MAT R n V) (MAT-EQUIV R m n A (MATMUL R (MATMUL R U A) V))))))))))))))
(mq-di*)
(fact 'invertible-mat-is-mat 'R 'm 'U)
(fact 'matmul-type 'R 'm 'm 'n 'U 'A)
(fact 'mat-equiv-left-mult 'R 'm 'n 'A 'U)
(fact 'mat-equiv-right-mult 'R 'm 'n '(MATMUL R U A) 'V)
(fact 'mat-equiv-trans 'R 'm 'n 'A '(MATMUL R U A) '(MATMUL R (MATMUL R U A) V))
(ass)
(report 'equiv-mul-both)
(%exit 0)
