;;; eucdiv.scm -- develop euclidean-division (Brick B2 core).
(set! *vnb-quiet* #t)
(define (ed-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (ed-di*) (let lp () (let* ((g (ed-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(sp (make-wff '(FORALL s (IMPLIES (IS-EUCLIDEAN-RING s) (FORALL a (IMPLIES (IN a (CARR s)) (FORALL b (IMPLIES (IN b (CARR s)) (IMPLIES (NOT (= b (ZERO s))) (FORSOME q (AND (IN q (CARR s)) (FORSOME r (AND (IN r (CARR s)) (AND (= a ((ADD s) ((MUL s) q b) r)) (OR (= r (ZERO s)) (<= (succ ((GAUGE s) r)) ((GAUGE s) b)))))))))))))))))
(ed-di*)
(fact 'gauge-is-degree 's)
(ai 1)
(mac-h 'HAS-DIV-REMAINDER '(HAS-DIV-REMAINDER s (GAUGE s)))
(inst+ '(FORALL a_ (IMPLIES (IN a_ (CARR s)) (FORALL b (IMPLIES (IN b (CARR s)) (IMPLIES (NOT (= b (ZERO s))) (FORSOME q (AND (IN q (CARR s)) (FORSOME r (AND (IN r (CARR s)) (AND (= a_ ((ADD s) ((MUL s) q b) r)) (OR (= r (ZERO s)) (<= (succ ((GAUGE s) r)) ((GAUGE s) b))))))))))))) 'a)
(inst+ '(FORALL b (IMPLIES (IN b (CARR s)) (IMPLIES (NOT (= b (ZERO s))) (FORSOME q (AND (IN q (CARR s)) (FORSOME r (AND (IN r (CARR s)) (AND (= a ((ADD s) ((MUL s) q b) r)) (OR (= r (ZERO s)) (<= (succ ((GAUGE s) r)) ((GAUGE s) b))))))))))) 'b)
(ass)
(display "euclidean-division proof-done? ") (display (proof-done? *ps*)) (newline)
(%exit 0)
