(set! *vnb-quiet* #t)
(define (mq-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mq-di*) (let lp () (let* ((g (mq-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (mq-foc! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (rep nm) (display nm)(display " done? ")(display (proof-done? *ps*))(newline)
  (when (not (proof-done? *ps*))
    (for-each (lambda (s) (display "  OPEN: ")(write (wff-formula (sequent-node-assertion s)))(newline)) (proof-leaves))))
(sp (make-wff (quote (FORALL A (IMPLIES (IS-RING A) (FORALL n (FORALL r (FORALL s (FORALL k (FORALL l (IMPLIES (IN s (CARR A)) (IMPLIES (= r s) (= (ELEM-G A n r k l) (ELEM-G A n s k l))))))))))))))
(mq-di*) (subst '(= r s)) (fact 'elem-g-type 'A 'n 's 'k 'l) (rfl)
(rep 'elem-g-param-cong) (qed 'elem-g-param-cong)
(sp (make-wff (quote (FORALL A (IMPLIES (IS-RING A) (FORALL n (FORALL r (FORALL k (FORALL l (IMPLIES (IN r (CARR A)) (IMPLIES (IN k (INTERVAL 1 n)) (IMPLIES (IN l (INTERVAL 1 n)) (IMPLIES (NOT (= k l)) (IS-INVERTIBLE-MAT A n (ELEM-G A n r k l)))))))))))))))
(mq-di*)
(fact 'ring-neg-in-carr 'A 'r) (fact 'ring-neg-in-carr 'A '((NEG A) r))
(fact 'elem-g-type 'A 'n 'r 'k 'l) (fact 'elem-g-type 'A 'n '((NEG A) r) 'k 'l)
(fact 'elem-g-inverse 'A 'n 'r 'k 'l) (fact 'elem-g-inverse 'A 'n '((NEG A) r) 'k 'l)
(fact 'ring-neg-neg 'A 'r) (fact 'eq-sym '((NEG A) ((NEG A) r)) 'r)
(fact 'elem-g-param-cong 'A 'n 'r '((NEG A) ((NEG A) r)) 'k 'l)
(mac 'IS-INVERTIBLE-MAT) (di) (mq-foc! (H? 'FORSOME)) (ew '(ELEM-G A n ((NEG A) r) k l)) (di) (mq-foc! (H? 'AND)) (di)
(mq-foc! (lambda (g) (and (pair? g) (eq? (car g) '=) (pair? (cadr g)) (eq? (car (cadr g)) 'MATMUL)
                          (let ((ff (caddr (cadr g)))) (and (pair? ff) (eq? (car ff) 'ELEM-G) (pair? (list-ref ff 3)))))))
(subst '(= (ELEM-G A n r k l) (ELEM-G A n ((NEG A) ((NEG A) r)) k l)))
(ass-all)
(rep 'elem-g-invertible)
(%exit 0)
