(load "load.scm")
;; after abort we are in the error REPL; try make-wff on the g form directly
(display "=== testing g wff ===\n")
(define gw '(FORALL A (IMPLIES (IS-RING A)
     (FORALL m (FORALL n (FORALL P (FORALL r (FORALL k (FORALL l
       (IMPLIES (IN P (MAT m n (CARR A)))
       (IMPLIES (IN r (CARR A))
       (IMPLIES (IN k (INTERVAL 1 m))
       (IMPLIES (IN l (INTERVAL 1 m))
       (IMPLIES (NOT (= k l))
       (FORALL i (IMPLIES (IN i (INTERVAL 1 m))
       (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
         (= (ENTRY (MATMUL A (ELEM-G A m r k l) P) i c)
            (IF (= i k)
                ((ADD A) (ENTRY P k c) ((MUL A) r (ENTRY P l c)))
                (ENTRY P i c))))))))))))))))))))))))
(define r (ignore-errors (make-wff gw)))
(display (if (condition? r) (string-append "MAKE-WFF ERROR: " (condition/report-string r)) "make-wff OK"))
(newline)
(%exit 0)
