;;; scratchpad/helpers.scm -- prove mat-equiv-cod-is-mat + classmin-transport
(set! *vnb-quiet* #t)
(define (h-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (h-di*) (let lp () (let* ((g (h-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (h-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (h-find pred) (let lp ((as (h-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))

;; ===== mat-equiv-cod-is-mat =====
(sp (make-wff '(FORALL A (IMPLIES (IS-RING A) (FORALL m (FORALL n (FORALL X (FORALL Y
    (IMPLIES (IN X (MAT m n (CARR A)))
    (IMPLIES (MAT-EQUIV A m n X Y)
      (IN Y (MAT m n (CARR A)))))))))))))
(h-di*)
(mac-h 'MAT-EQUIV '(MAT-EQUIV A m n X Y))
(ai 1) (ai 1) (ai 1) (ai 1)
(define YEQ (h-find (lambda (z) (and (pair? z) (eq? (car z) '=) (eq? (cadr z) 'Y)))))
;; YEQ = (= Y (MATMUL A (MATMUL A U X) V))
(define RHS (caddr YEQ))                      ; (MATMUL A (MATMUL A U X) V)
(define INNER (caddr RHS))                    ; (MATMUL A U X)
(define U (caddr INNER))                       ; U
(define V (cadddr RHS))                        ; V
(fact 'invertible-mat-is-mat 'A 'm U)
(fact 'invertible-mat-is-mat 'A 'n V)
(fact 'matmul-type 'A 'm 'm 'n U 'X)
(fact 'matmul-type 'A 'm 'n 'n INNER V)
(subst YEQ)
(ass)
(display (list 'cod-is-mat (proof-done? *ps*)))(newline)
(when (proof-done? *ps*) (qed 'mat-equiv-cod-is-mat)(category! 'mat-equiv-cod-is-mat 'plumbing))

;; ===== classmin-transport =====
(define (pcm P)
  (list 'FORALL 'C (list 'IMPLIES (list 'MAT-EQUIV 'A 'm 'n P 'C)
    (list 'FORALL 'ii (list 'FORALL 'jj
      (list 'IMPLIES '(IN ii (INTERVAL 1 m)) (list 'IMPLIES '(IN jj (INTERVAL 1 n))
        (list 'IMPLIES (list 'NOT (list '= '(ENTRY C ii jj) '(ZERO A)))
          (list '<= (list '(GAUGE A) (list 'ENTRY P 1 1)) '((GAUGE A) (ENTRY C ii jj)))))))))))
(define (h-impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))
(define (h-fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))
(sp (make-wff
  (list 'FORALL 'A (list 'IMPLIES '(IS-RING A)
    (h-fa* '(m n P Q)
      (h-impl* (list '(IN P (MAT m n (CARR A)))
                     '(MAT-EQUIV A m n P Q)
                     '(= (ENTRY Q 1 1) (ENTRY P 1 1))
                     (pcm 'P))
               (pcm 'Q)))))))
(h-di*)
(define GG (h-goal))                          ; (<= (gauge Q11) (gauge (ENTRY C II JJ)))
(define ECIJ (cadr (caddr GG)))               ; (ENTRY C II JJ)
(define TC (cadr ECIJ)) (define TII (caddr ECIJ)) (define TJJ (cadddr ECIJ))
(define PCMH (h-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'C)
              (let ((b (caddr z))) (and (pair? b) (eq? (car b) 'IMPLIES)
                (equal? (list-ref (cadr b) 4) 'P)))))))  ; MAT-EQUIV A m n P C
(fact 'mat-equiv-trans 'A 'm 'n 'P 'Q TC)
(inst+ PCMH TC)
(define PII (h-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'ii)))))
(inst+ PII TII)
(define PJJ (h-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'jj)))))
(inst+ PJJ TJJ)
(subst '(= (ENTRY Q 1 1) (ENTRY P 1 1)))
(ass)
(display (list 'classmin-transport (proof-done? *ps*)))(newline)
(when (proof-done? *ps*) (qed 'classmin-transport)(category! 'classmin-transport 'algebra))

(call-with-output-file "scratchpad/RESULT.txt"
  (lambda (port) (display "helpers done" port)(newline port)))
