;;; invproof.scm -- drive elem-f-inverse.  Loads AFTER load.scm.
(define (mlast) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (mfoc! n) (set-proof-state-focus! *ps* n))
(define (mgoal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mdi*) (let lp () (let* ((g (mgoal))(h (and (pair? g)(car g))))
                 (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (mprobe tag) (display ";; --- ")(display tag)(display " ---")(newline)
  (display ";; GOAL: ")(write (mgoal))(newline))
(define (mem P)
  (cut `(OR ,P (NOT ,P)))
  (let ((uo (mlast)))
    (pbc)(cut `(NOT ,P))
    (let ((un (mlast)))
      (di)(cut `(OR ,P (NOT ,P)))
      (let ((u2 (mlast)))(oi-l)(ass)(mfoc! u2))
      (ai `(NOT (OR ,P (NOT ,P))))(mfoc! un))
    (cut `(OR ,P (NOT ,P)))
    (let ((u3 (mlast)))(oi-r)(ass)(mfoc! u3))
    (ai `(NOT (OR ,P (NOT ,P))))(mfoc! uo)))
(define (mcases P) (mem P)(ai `(OR ,P (NOT ,P)))(mlast))
(set! *vnb-quiet* #t)

(define FKL '(ELEM-F A n k l))
(define FLK '(ELEM-F A n l k))
(define PROD `(MATMUL A ,FKL ,FLK))
(define ARHS `(IF (= c l) (ENTRY ,FKL i k) (IF (= c k) (ENTRY ,FKL i l) (ENTRY ,FKL i c))))
(define INNER `(IF (= c k) (ENTRY ,FKL i l) (ENTRY ,FKL i c)))

(sp (make-wff
  '(FORALL A (IMPLIES (IS-RING A)
     (FORALL n (FORALL k (FORALL l
       (IMPLIES (IN k (INTERVAL 1 n))
       (IMPLIES (IN l (INTERVAL 1 n))
       (IMPLIES (NOT (= k l))
         (= (MATMUL A (ELEM-F A n k l) (ELEM-F A n l k)) (IDENTMAT A n))))))))))))
(mdi*)
(cut '(NOT (= l k)))
(define fm0 (mlast)) (di) (fact 'eq-sym 'l 'k) (ai '(NOT (= k l))) (mfoc! fm0)
(fact 'elem-f-type 'A 'n 'k 'l)
(fact 'elem-f-type 'A 'n 'l 'k)
(fact 'matmul-type 'A 'n 'n 'n FKL FLK)
(fact 'identmat-type 'A 'n)
(cut `(FORALL i (IMPLIES (IN i (INTERVAL 1 n))
        (FORALL c (IMPLIES (IN c (INTERVAL 1 n))
          (= (ENTRY ,PROD i c) (ENTRY (IDENTMAT A n) i c)))))))
(define fmain (mlast))
  (di) (di) (di) (di)
  (fact 'elem-f-action 'A 'n 'n FKL 'l 'k 'i 'c)
  (subst `(= (ENTRY ,PROD i c) ,ARHS))
  (fact 'entry-of-identmat 'A 'n 'i 'c)
  (subst '(= (ENTRY (IDENTMAT A n) i c) (IF (= i c) (ONE A) (ZERO A))))
  (mprobe "f-inv entry leaf")
  (define fnotcl (mcases '(= c l)))
  ;; ===== c = l : LHS -> F_ik = IF(=i l)(ONE)(ZERO) = RHS =====
  (if-true ARHS)
  (define fu1 (mlast)) (ass) (mfoc! fu1)
  (subst `(= ,ARHS (ENTRY ,FKL i k)))
  (fact 'elem-f-col-k 'A 'n 'k 'l 'i)
  (subst `(= (ENTRY ,FKL i k) (IF (= i l) (ONE A) (ZERO A))))
  (subst '(= c l))
  (rfl)
  ;; ===== c /= l =====
  (mfoc! fnotcl)
  (if-false ARHS)
  (define fu2 (mlast)) (ass) (mfoc! fu2)
  (subst `(= ,ARHS ,INNER))
  (define fnotck (mcases '(= c k)))
  ;; --- c = k : LHS -> F_il = IF(=i k)(ONE)(ZERO) = RHS ---
  (if-true INNER)
  (define fu3 (mlast)) (ass) (mfoc! fu3)
  (subst `(= ,INNER (ENTRY ,FKL i l)))
  (fact 'elem-f-col-l 'A 'n 'k 'l 'i)
  (subst `(= (ENTRY ,FKL i l) (IF (= i k) (ONE A) (ZERO A))))
  (subst '(= c k))
  (rfl)
  ;; --- c /= k, c /= l : LHS -> F_ic = IF(=i c)(ONE)(ZERO) = RHS ---
  (mfoc! fnotck)
  (if-false INNER)
  (define fu4 (mlast)) (ass) (mfoc! fu4)
  (subst `(= ,INNER (ENTRY ,FKL i c)))
  (fact 'elem-f-col-other 'A 'n 'k 'l 'i 'c)
  (subst `(= (ENTRY ,FKL i c) (IF (= i c) (ONE A) (ZERO A))))
  (rfl)
(mfoc! fmain)
(fact 'matrix-entry-extensionality 'n 'n '(CARR A) PROD '(IDENTMAT A n))
(ass)

(newline)
(display (if (proof-done? *ps*)
             ";; *** elem-f-inverse: PROOF COMPLETE ***"
             ";; !!! elem-f-inverse: STILL OPEN"))
(newline)
