(set! *vnb-quiet* #t)
(define (mq-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mq-di*) (let lp () (let* ((g (mq-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (mq-foc! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(sp (make-wff '(FORALL A (IMPLIES (IS-RING A) (FORALL n (IS-INVERTIBLE-MAT A n (IDENTMAT A n)))))))
(mq-di*) (fact 'identmat-type 'A 'n) (fact 'identmat-left-identity 'A 'n 'n '(IDENTMAT A n))
(mac 'IS-INVERTIBLE-MAT) (di) (mq-foc! (H? 'FORSOME)) (ew '(IDENTMAT A n)) (di) (mq-foc! (H? 'AND)) (di) (ass-all)
(qed 'identmat-invertible)
(sp (make-wff '(FORALL A (IMPLIES (IS-RING A) (FORALL m (FORALL n (FORALL C (FORALL V
     (IMPLIES (IN C (MAT m n (CARR A))) (IMPLIES (IS-INVERTIBLE-MAT A n V)
       (MAT-EQUIV A m n C (MATMUL A C V))))))))))))
(mq-di*)
(fact 'identmat-left-identity 'A 'm 'n 'C) (fact 'identmat-invertible 'A 'm)
(mac 'MAT-EQUIV)
(display "goal after mac: ") (write (mq-goal)) (newline)
(ew '(IDENTMAT A m))
(display "goal after ew IDENTMAT: ") (write (mq-goal)) (newline)
(di)
(display "leaves after di: ") (for-each (lambda (s) (display "[") (write (car (wff-formula (sequent-node-assertion s)))) (display "]")) (proof-leaves)) (newline)
(mq-foc! (H? 'FORSOME)) (ew 'V) (di)
(mq-foc! (H? '=))
(subst '(= (MATMUL A (IDENTMAT A m) C) C))
(display "after subst: ") (write (mq-goal)) (newline)
(rfl)
(ass-all)
(display "right-mult done? ") (display (proof-done? *ps*)) (newline)
(for-each (lambda (s) (display "OPEN: ") (write (wff-formula (sequent-node-assertion s))) (newline)) (proof-leaves))
(%exit 0)
