;;; opcensus-probe.scm -- inspect how operators are registered/classified.
(load "load.scm")
(set! *vnb-quiet* #t)

(define (theorem-head-subject n)
  ;; crude: strip foralls/implies, return head of first term-ish subject
  (let loop ((f (lookup-theorem n)))
    (cond ((not (pair? f)) f)
          ((memq (car f) '(FORALL FORSOME)) (loop (caddr f)))
          ((eq? (car f) 'IMPLIES) (loop (caddr f)))
          (else f))))

;; Registry contents grouped by kind.
(newline)
(display "=== *constant-registry* by kind ===\n")
(let ((by-kind (make-equal-hash-table)))
  (for-each (lambda (k)
              (let ((kind (hash-table-ref *constant-registry* k #f)))
                (hash-table-set! by-kind kind
                  (cons k (hash-table-ref/default by-kind kind '())))))
            (hash-table-keys *constant-registry*))
  (for-each (lambda (kind)
              (let ((names (sort (hash-table-ref by-kind kind '())
                                 (lambda (a b) (string<? (symbol->string a)(symbol->string b))))))
                (display kind) (display " (") (display (length names)) (display "): ")
                (write names) (newline)))
            (hash-table-keys by-kind)))

(newline)
(display "=== spotlight operators ===\n")
(for-each
 (lambda (h)
   (display h) (display "\n")
   (display "  registry-kind: ") (write (hash-table-ref/default *constant-registry* h #f)) (newline)
   (display "  provenance   : ") (write (provenance-of h)) (newline)
   (display "  in functoid-registry?: ")
   (write (and (hash-table-ref/default *functoid-registry* h #f) #t)) (newline)
   (display "  in theory-definitions?: ")
   (write (and (assq h (theory-definitions *current-theory*)) #t)) (newline)
   ;; theorems whose stripped subject head is h
   (let ((hits (filter (lambda (n)
                         (let ((s (theorem-head-subject n)))
                           (and (pair? s)
                                (let find ((x s))
                                  (cond ((and (pair? x) (eq? (car x) h)) #t)
                                        ((pair? x) (or (find (car x)) (find (cdr x))))
                                        (else #f))))))
                       (hash-table-keys *theorem-table*))))
     (display "  #theorems mentioning it: ") (display (length hits)) (newline)
     (display "  sample char axioms: ")
     (write (list-head hits (min 6 (length hits)))) (newline)))
 '(MATRIX MAT ENTRY MATOF MATMUL SIZE INTERVAL COMB-KK RING-POWER MPOW CHOOSE ZZ-ACT
   ELEM-F IDENTMAT CARR ADD SUM CARD ESUP DIST-SEQ EMBED CLASS QUOTIENT COMPLETION))

(newline)
(display "=== functoid-registry keys ===\n")
(write (sort (hash-table-keys *functoid-registry*)
             (lambda (a b) (string<? (symbol->string a)(symbol->string b)))))
(newline)
(display "=== theory-definitions keys ===\n")
(write (sort (map car (theory-definitions *current-theory*))
             (lambda (a b) (string<? (symbol->string a)(symbol->string b)))))
(newline)
(%exit 0)
