(load "load.scm")
(set! *vnb-quiet* #t)
(define (mq-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mq-di*) (let lp () (let* ((g (mq-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (mq-foc! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (mq-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (mq-find pred) (let lp ((as (mq-asms))) (cond ((null? as) #f)((pred (car as))(car as))(else (lp (cdr as))))))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(sp (make-wff '(FORALL A (IMPLIES (IS-EUCLIDEAN-RING A) (FORALL m (FORALL n (FORALL P (IMPLIES (IN P (MAT m n (CARR A))) (IMPLIES (IN 1 (INTERVAL 1 m)) (IMPLIES (IN 1 (INTERVAL 1 n)) (IMPLIES (FORSOME i0 (FORSOME j0 (AND (IN i0 (INTERVAL 1 m)) (AND (IN j0 (INTERVAL 1 n)) (NOT (= (ENTRY P i0 j0) (ZERO A))))))) (FORSOME B (AND (MAT-EQUIV A m n P B) (AND (NOT (= (ENTRY B 1 1) (ZERO A))) (FORALL i (FORALL j (IMPLIES (IN i (INTERVAL 1 m)) (IMPLIES (IN j (INTERVAL 1 n)) (IMPLIES (NOT (= (ENTRY P i j) (ZERO A))) (<= ((GAUGE A) (ENTRY B 1 1)) ((GAUGE A) (ENTRY P i j))))))))))))))))))))))
(mq-di*)
(fact 'min-degree-entry 'A 'm 'n 'P)
(ai 1)(ai 1)(ai 1)(ai 1)(ai 1)
;; capture istar,jstar from the (NOT (= (ENTRY P istar jstar)(ZERO A))) assumption
(define NEasm (mq-find (lambda (z)(and (pair? z)(eq?(car z)'NOT)(pair?(cadr z))(eq?(car(cadr z))'=)
                                       (pair?(cadr(cadr z)))(eq?(car(cadr(cadr z)))'ENTRY)))))
(define istar (list-ref (cadr (cadr NEasm)) 2))
(define jstar (list-ref (cadr (cadr NEasm)) 3))
(define MINIM (mq-find (lambda (z)(and (pair? z)(eq?(car z)'FORALL)))))
;; coerce euclidean -> ring
(fact 'euclidean-ring-is-integral-domain 'A)
(fact 'integral-domain-is-commutative-ring 'A)
(fact 'commutative-ring-is-ring 'A)
;; place istar,jstar at (1,1)
(fact 'swap-to-corner-gen 'A 'm 'n 'P istar jstar)
(ai 1)(ai 1)
(define B0eq (mq-find (lambda (z)(and (pair? z)(eq?(car z)'MAT-EQUIV)))))
(define B0 (list-ref B0eq 5))
(define B0val (list '= (list 'ENTRY B0 1 1) (list 'ENTRY 'P istar jstar)))
(ew B0) (di)
(mq-foc! (H? 'MAT-EQUIV)) (ass)
(mq-foc! (H? 'AND)) (di)
;; NE leaf: (NOT (= (ENTRY B0 1 1)(ZERO A)))
(mq-foc! (H? 'NOT))
(subst B0val) (ass)
;; minimality leaf
(mq-foc! (H? 'FORALL))
(mq-di*)
(subst B0val)
(inst+ MINIM 'i)
(define MINj (mq-find (lambda (z)(and (pair? z)(eq? (car z) 'FORALL)(eq? (cadr z) 'j))))) 
(inst+ MINj 'j)
(ass)
(call-with-output-file "/tmp/claude-1000/-home-ubuntu/423ebffe-e6fe-4caf-8686-2808e8178391/scratchpad/RESULT.txt" (lambda (p) (write (list 'place-min-pivot (proof-done? *ps*)
   (map (lambda (s) (wff-formula (sequent-node-assertion s))) (proof-leaves))) p)))
(%exit 0)
