(set! *vnb-quiet* #t)
(define (mq-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mq-di*) (let lp () (let* ((g (mq-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (mq-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (mq-find pred) (let lp ((as (mq-asms))) (cond ((null? as) #f)((pred (car as))(car as))(else (lp (cdr as))))))
(define (mq-foc! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (rep nm) (display nm)(display " done? ")(display (proof-done? *ps*))(newline)
  (when (not (proof-done? *ps*))
    (for-each (lambda (s) (display "  OPEN: ")(write (wff-formula (sequent-node-assertion s)))(newline)) (proof-leaves))))
(define IDEN '(IDENTMAT A n))

(sp (make-wff '(FORALL A (IMPLIES (IS-RING A) (FORALL n (FORALL U1 (FORALL U2
     (IMPLIES (IS-INVERTIBLE-MAT A n U1) (IMPLIES (IS-INVERTIBLE-MAT A n U2)
       (IS-INVERTIBLE-MAT A n (MATMUL A U1 U2)))))))))))
(mq-di*)
(fact 'invertible-mat-is-mat 'A 'n 'U1) (fact 'invertible-mat-is-mat 'A 'n 'U2)
(mac-h 'IS-INVERTIBLE-MAT '(IS-INVERTIBLE-MAT A n U1)) (ai 1)(ai 1)(ai 1)(ai 1)
(define eq1 (mq-find (lambda (z)(and (pair? z)(eq?(car z)'=)(pair?(cadr z))(eq?(car(cadr z))'MATMUL)(eq?(caddr(cadr z))'U1)))))
(define V1 (cadddr (cadr eq1)))
(mac-h 'IS-INVERTIBLE-MAT '(IS-INVERTIBLE-MAT A n U2)) (ai 1)(ai 1)(ai 1)(ai 1)
(define eq2 (mq-find (lambda (z)(and (pair? z)(eq?(car z)'=)(pair?(cadr z))(eq?(car(cadr z))'MATMUL)(eq?(caddr(cadr z))'U2)))))
(define V2 (cadddr (cadr eq2)))
(display "V1=")(write V1)(display " V2=")(write V2)(newline)
;; the four unit equations (reconstructed)
(define U1V1 (list '= (list 'MATMUL 'A 'U1 V1) IDEN))
(define V1U1 (list '= (list 'MATMUL 'A V1 'U1) IDEN))
(define U2V2 (list '= (list 'MATMUL 'A 'U2 V2) IDEN))
(define V2U2 (list '= (list 'MATMUL 'A V2 'U2) IDEN))
;; typings
(fact 'matmul-type 'A 'n 'n 'n 'U1 'U2)
(fact 'matmul-type 'A 'n 'n 'n V2 V1)
(fact 'identmat-type 'A 'n)
(mac 'IS-INVERTIBLE-MAT) (di) (mq-foc! (H? 'FORSOME)) (ew (list 'MATMUL 'A V2 V1)) (di) (mq-foc! (H? 'AND)) (di)
;; L5 : (U1U2)(V2V1) = I  -- first factor caddr = U1
(mq-foc! (lambda (g)(and (pair? g)(eq?(car g)'=)(pair?(cadr g))(eq?(car(cadr g))'MATMUL)
                         (let ((ff (caddr (cadr g))))(and (pair? ff)(eq?(car ff)'MATMUL)(eq?(caddr ff)'U1))))))
(fact 'matmul-assoc-rev 'A 'n 'n 'n 'n '(MATMUL A U1 U2) V2 V1)
(subst (list '= (list 'MATMUL 'A '(MATMUL A U1 U2)(list 'MATMUL 'A V2 V1))
                (list 'MATMUL 'A (list 'MATMUL 'A '(MATMUL A U1 U2) V2) V1)))
(fact 'matmul-assoc 'A 'n 'n 'n 'n 'U1 'U2 V2)
(subst (list '= (list 'MATMUL 'A '(MATMUL A U1 U2) V2) (list 'MATMUL 'A 'U1 (list 'MATMUL 'A 'U2 V2))))
(subst U2V2)
(fact 'identmat-right-identity 'A 'n 'n 'U1)
(subst '(= (MATMUL A U1 (IDENTMAT A n)) U1))
(subst U1V1)
(rfl)
;; L6 : (V2V1)(U1U2) = I  -- first factor caddr = V2
(mq-foc! (lambda (g)(and (pair? g)(eq?(car g)'=)(pair?(cadr g))(eq?(car(cadr g))'MATMUL)
                         (let ((ff (caddr (cadr g))))(and (pair? ff)(eq?(car ff)'MATMUL)(equal?(caddr ff) V2))))))
(fact 'matmul-assoc-rev 'A 'n 'n 'n 'n (list 'MATMUL 'A V2 V1) 'U1 'U2)
(subst (list '= (list 'MATMUL 'A (list 'MATMUL 'A V2 V1) '(MATMUL A U1 U2))
                (list 'MATMUL 'A (list 'MATMUL 'A (list 'MATMUL 'A V2 V1) 'U1) 'U2)))
(fact 'matmul-assoc 'A 'n 'n 'n 'n V2 V1 'U1)
(subst (list '= (list 'MATMUL 'A (list 'MATMUL 'A V2 V1) 'U1) (list 'MATMUL 'A V2 (list 'MATMUL 'A V1 'U1))))
(subst V1U1)
(fact 'identmat-right-identity 'A 'n 'n V2)
(subst (list '= (list 'MATMUL 'A V2 '(IDENTMAT A n)) V2))
(subst V2U2)
(rfl)
(ass-all)
(qed 'product-of-invertibles-is-invertible)

;; ---- mat-equiv-trans ----
(define (mm a b) (list 'MATMUL 'A a b))
(sp (make-wff '(FORALL A (IMPLIES (IS-RING A) (FORALL m (FORALL n (FORALL C (FORALL D (FORALL E
     (IMPLIES (IN C (MAT m n (CARR A)))
     (IMPLIES (MAT-EQUIV A m n C D) (IMPLIES (MAT-EQUIV A m n D E)
       (MAT-EQUIV A m n C E)))))))))))))
(mq-di*)
(mac-h 'MAT-EQUIV '(MAT-EQUIV A m n C D)) (ai 1)(ai 1)(ai 1)(ai 1)
(define eqD (mq-find (lambda(z)(and (pair? z)(eq?(car z)'=)(eq?(cadr z)'D)))))
(define rhsD (caddr eqD)) (define U1 (caddr (caddr rhsD))) (define V1 (cadddr rhsD))
(mac-h 'MAT-EQUIV '(MAT-EQUIV A m n D E)) (ai 1)(ai 1)(ai 1)(ai 1)
(define eqE (mq-find (lambda(z)(and (pair? z)(eq?(car z)'=)(eq?(cadr z)'E)))))
(define rhsE (caddr eqE)) (define U2 (caddr (caddr rhsE))) (define V2 (cadddr rhsE))
(display "U1=")(write U1)(display " V1=")(write V1)(display " U2=")(write U2)(display " V2=")(write V2)(newline)
;; typings
(fact 'invertible-mat-is-mat 'A 'm U1) (fact 'invertible-mat-is-mat 'A 'm U2)
(fact 'invertible-mat-is-mat 'A 'n V1) (fact 'invertible-mat-is-mat 'A 'n V2)
(fact 'matmul-type 'A 'm 'm 'm U2 U1)          ; U2U1 : m x m
(fact 'matmul-type 'A 'n 'n 'n V1 V2)          ; V1V2 : n x n
(fact 'matmul-type 'A 'm 'n 'n 'C V1)          ; CV1 : m x n
(fact 'matmul-type 'A 'm 'm 'n (mm U2 U1) 'C)  ; (U2U1)C : m x n
;; invertibility of the composed factors
(fact 'product-of-invertibles-is-invertible 'A 'm U2 U1)
(fact 'product-of-invertibles-is-invertible 'A 'n V1 V2)
(mac 'MAT-EQUIV) (ew (mm U2 U1)) (di) (mq-foc! (H? 'FORSOME)) (ew (mm V1 V2)) (di)
(mq-foc! (H? '=))
;; substitute the two equivalence equations, then reassociate to the target
(subst eqE) (subst eqD)
(fact 'matmul-assoc 'A 'm 'm 'n 'n U1 'C V1)
(subst (list '= (mm (mm U1 'C) V1) (mm U1 (mm 'C V1))))
(fact 'matmul-assoc-rev 'A 'm 'm 'm 'n U2 U1 (mm 'C V1))
(subst (list '= (mm U2 (mm U1 (mm 'C V1))) (mm (mm U2 U1) (mm 'C V1))))
(fact 'matmul-assoc-rev 'A 'm 'm 'n 'n (mm U2 U1) 'C V1)
(subst (list '= (mm (mm U2 U1) (mm 'C V1)) (mm (mm (mm U2 U1) 'C) V1)))
(fact 'matmul-assoc 'A 'm 'n 'n 'n (mm (mm U2 U1) 'C) V1 V2)
(subst (list '= (mm (mm (mm (mm U2 U1) 'C) V1) V2) (mm (mm (mm U2 U1) 'C) (mm V1 V2))))
(rfl)
(ass-all)
(rep 'mat-equiv-trans)
(%exit 0)
