;;; scratchpad/rowupto.scm -- drive clear-row-upto (ni induction iterating pivot-clears-col)
(set! *vnb-quiet* #t)
(define (cc-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (cc-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (cc-foc! n) (set-proof-state-focus! *ps* n))
(define (cc-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (cc-find pred) (let lp ((as (cc-asms)))
  (cond ((null? as) #f) ((pred (car as)) (car as)) (else (lp (cdr as))))))
(define (cc-foc-goal! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (cc-leaf-asms s) (map wff-formula (sequent-node-assumptions s)))
(define (cc-foc-by-asm! f)
  (let ((s (any-pred (lambda (s) (member f (cc-leaf-asms s))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (H? h) (lambda (g) (and (pair? g) (eq? (car g) h))))
(define (di4) (di)(di)(di)(di))
(define (cc-em P)
  (cut `(OR ,P (NOT ,P)))
  (let ((use-or (cc-last)))
    (pbc)
    (cut `(NOT ,P))
    (let ((use-notp (cc-last)))
      (di)
      (cut `(OR ,P (NOT ,P)))
      (let ((use-or2 (cc-last))) (oi-l) (ass) (cc-foc! use-or2))
      (ai `(NOT (OR ,P (NOT ,P))))
      (cc-foc! use-notp))
    (cut `(OR ,P (NOT ,P)))
    (let ((use-or3 (cc-last))) (oi-r) (ass) (cc-foc! use-or3))
    (ai `(NOT (OR ,P (NOT ,P))))
    (cc-foc! use-or)))
(define (cc-cases P) (cc-em P) (ai `(OR ,P (NOT ,P))) (cc-last))
(define (impl* gs concl) (fold-right (lambda (g acc) (list 'IMPLIES g acc)) concl gs))
(define (fa* vs body) (fold-right (lambda (v acc) (list 'FORALL v acc)) body vs))

(define (CLEARED Q kk)
  (list 'FORALL 'j (impl* (list '(IN j (INTERVAL 1 n)) '(NOT (= j 1)) (list '<= 'j kk))
                          (list '= (list 'ENTRY Q 1 'j) '(ZERO A)))))
(define (BODY kk)
  (list 'FORSOME 'Q (list 'AND '(MAT-EQUIV A m n P Q)
    (list 'AND '(= (ENTRY Q 1 1) (ENTRY P 1 1)) (CLEARED 'Q kk)))))
(define PCM
  '(FORALL C (IMPLIES (MAT-EQUIV A m n P C)
      (FORALL ii (FORALL jj (IMPLIES (IN ii (INTERVAL 1 m)) (IMPLIES (IN jj (INTERVAL 1 n))
        (IMPLIES (NOT (= (ENTRY C ii jj) (ZERO A)))
          (<= ((GAUGE A) (ENTRY P 1 1)) ((GAUGE A) (ENTRY C ii jj)))))))))))
(define STMT
  (list 'FORALL 'A (list 'IMPLIES '(IS-EUCLIDEAN-RING A)
    (fa* '(m n P)
      (impl* (list '(IN P (MAT m n (CARR A))) '(IN 1 (INTERVAL 1 m))
                   '(IN 1 (INTERVAL 1 n)) '(NOT (= (ENTRY P 1 1) (ZERO A))) PCM)
             (list 'FORALL 'k (list 'IMPLIES '(IN k NN) (BODY 'k))))))))

(sp (make-wff STMT))
;; strip fixed hyps down to (FORALL k (IMPLIES (IN k NN) ...))
(let lp () (let* ((g (cc-goal)) (h (and (pair? g) (car g))))
  (when (and (memq h '(FORALL IMPLIES)) (not (and (eq? h 'FORALL) (eq? (cadr g) 'k))))
    (di) (lp))))
(define PCMH (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'C)))))
;; coerce euclidean -> ring (shared by both induction leaves)
(fact 'euclidean-ring-is-integral-domain 'A)
(fact 'integral-domain-is-commutative-ring 'A)
(fact 'commutative-ring-is-ring 'A)
(ni)
(display 'CK-ni)(newline)

;; ===================== BASE : BODY(0), witness Q=P =====================
(cc-foc-goal! (H? 'FORSOME))
(ew 'P) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (fact 'mat-equiv-refl 'A 'm 'n 'P) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) '(ENTRY P 1 1)))))
(fact 'entry-in-carrier 'm 'n '(CARR A) 'P 1 1) (rfl)
(display 'CK-base-eq)(newline)
;; CLEARED(0): j in [1,n], j/=1, j<=0 -> contradiction
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'j))))
(di4)
(define BJ (list-ref (cadr (cc-goal)) 3))          ; the renamed j
(fact 'interval-elt-in-nn 1 'n BJ)
(fact 'interval-lo 1 'n BJ)
(fact 'nn-not-le-zero-pos BJ)
(ai (list 'NOT (list '<= BJ 0)))

(display 'CK-base-done)(newline)
;; ===================== STEP : BODY(k) => BODY(succ k) =====================
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'k))))
(di) (di) (di)                                     ; k ; IN k NN ; IH=BODY(k)
;; decompose IH
(define IH (cc-find (H? 'FORSOME)))
(ai IH) (ai 1) (ai 1)                              ; exists Qw ; and-elims
(define QwEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
              (eq? (car (cadr z)) 'ENTRY) (equal? (caddr z) '(ENTRY P 1 1))))))
(define Qw (cadr (cadr QwEQ)))                     ; witness matrix
(define CLK (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'j)))))
(define VALID (list 'AND (list 'IN '(succ k) '(INTERVAL 1 n)) (list 'NOT (list '= '(succ k) 1))))

(display 'CK-ih-decomposed)(newline)(display (list 'Qw Qw))(newline)
(define NOTV (cc-cases VALID))

;; ---------- VALIDCOL TRUE : apply pivot-clears-col at column (succ k) ----------
(fact 'mat-equiv-cod-is-mat 'A 'm 'n 'P Qw)         ; IN Qw MAT
(fact 'classmin-transport 'A 'm 'n 'P Qw)           ; Qw-classmin
;; Qw_{11} /= 0
(cut (list 'NOT (list '= (list 'ENTRY Qw 1 1) '(ZERO A))))
(define TV-CONT (cc-last))
(subst QwEQ) (ass)
(cc-foc! TV-CONT)
;; extract VALID conjuncts + flip the disequality
(ai VALID)
(fact 'neq-sym '(succ k) 1)                         ; NOT(= 1 (succ k))
(fact 'pivot-clears-col 'A 'm 'n Qw '(succ k))
(ai 1) (ai 1) (ai 1) (ai 1)                         ; exists Qp ; and-elims (4 levels)
(call-with-output-file "scratchpad/DBG.txt" (lambda (port)
  (for-each (lambda (a) (display (expression->string (wff-formula a)) port)(newline port))
            (sequent-node-assumptions (proof-state-focus *ps*)))))
(define QpEQ (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
              (eq? (car (cadr z)) 'ENTRY) (equal? (caddr z) (list 'ENTRY Qw 1 1))))))
(define Qp (cadr (cadr QpEQ)))
(define QpZERO (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (pair? (cadr z))
                (eq? (car (cadr z)) 'ENTRY) (equal? (cadr (cadr z)) Qp)
                (equal? (caddr z) '(ZERO A))))))
(define COLS (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'ii)
              (let ((b (caddr z))) (and (pair? b)(eq?(car b)'FORALL)))))))
;; witness BODY(succ k) with Qp
(display 'CK-pcc-decomposed)(newline)(display (list 'Qp Qp))(newline)
(call-with-output-file "scratchpad/DBG5.txt" (lambda(p)(for-each (lambda(a)(display (expression->string (wff-formula a)) p)(newline p)) (sequent-node-assumptions (proof-state-focus *ps*)))))
(ew Qp) (di)
(cc-foc-goal! (H? 'MAT-EQUIV)) (fact 'mat-equiv-trans 'A 'm 'n 'P Qw Qp) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY Qp 1 1)))))
(subst QpEQ) (ass)
;; CLEARED(succ k) for Qp
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'j))))
(di4)
(define TJ (list-ref (cadr (cc-goal)) 3))
(fact 'interval-elt-in-nn 1 'n TJ)
(fact 'nn-le-succ-cases 'k TJ)
(define TOR (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'OR) (equal? (caddr z) (list '= TJ '(succ k)))))))
(ai TOR)
;; branch j<=k : Qp_1j = Qw_1j (colspres) = 0 (IH cleared)
(cc-foc-by-asm! (list '<= TJ 'k))
(fact 'nn-le-imp-neq-succ 'k TJ)
(inst+ COLS 1)
(define COLSj (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'FORALL) (eq? (cadr z) 'c)))))
(inst+ COLSj TJ)
(inst+ CLK TJ)
(define CPRES (cc-find (lambda (z) (and (pair? z) (eq? (car z) '=) (equal? (cadr z) (list 'ENTRY Qp 1 TJ))))))
(subst CPRES)
(ass)
;; branch j = succ k : Qp_1j = Qp_1,succ k = 0
(cc-foc-by-asm! (list '= TJ '(succ k)))
(subst (list '= TJ '(succ k)))
(ass)

(display 'CK-truebranch-done)(newline)
;; ---------- VALIDCOL FALSE : witness Q = Qw unchanged ----------
(cc-foc! NOTV)
(ew Qw) (di)
(cc-foc-by-asm! (list 'NOT VALID))                 ; stay in the false branch
(cc-foc-goal! (H? 'MAT-EQUIV)) (ass)
(cc-foc-goal! (H? 'AND)) (di)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) '=) (equal? (cadr g) (list 'ENTRY Qw 1 1)))))
(ass)
(cc-foc-goal! (lambda (g) (and (pair? g) (eq? (car g) 'FORALL) (eq? (cadr g) 'j))))
(di4)
(define FJ (list-ref (cadr (cc-goal)) 3))
(fact 'interval-elt-in-nn 1 'n FJ)
(fact 'nn-le-succ-cases 'k FJ)
(define FOR (cc-find (lambda (z) (and (pair? z) (eq? (car z) 'OR) (equal? (caddr z) (list '= FJ '(succ k)))))))
(ai FOR)
;; branch j<=k : IH cleared
(cc-foc-by-asm! (list '<= FJ 'k))
(inst+ CLK FJ)
(ass)
;; branch j=succ k : contradicts VALIDCOL false
(cc-foc-by-asm! (list '= FJ '(succ k)))
(cut VALID)
(define FV-CONT (cc-last))
(di)
(fact 'eq-sym FJ '(succ k))                        ; (= (succ k) FJ)
(cc-foc-goal! (H? 'IN)) (subst (list '= '(succ k) FJ)) (ass)
(cc-foc-goal! (H? 'NOT)) (subst (list '= '(succ k) FJ)) (ass)
(cc-foc! FV-CONT)
(ai (list 'NOT VALID))

(call-with-output-file "scratchpad/RESULT.txt"
  (lambda (port)
    (display (list 'proof-done? (proof-done? *ps*)) port) (newline port)
    (display (list 'open-leaves (length (proof-leaves))) port) (newline port)
    (for-each (lambda (s)
       (newline port) (display "GOAL: " port)
       (display (expression->string (wff-formula (sequent-node-assertion s))) port) (newline port)
       (display "ASMS:" port)(newline port)
       (for-each (lambda (a)(display "  - " port)(display (expression->string (wff-formula a)) port)(newline port))
                 (sequent-node-assumptions s)))
     (proof-leaves))))
(display (list 'DONE (proof-done? *ps*)))(newline)
