(sp (make-wff '(FORALL md (IMPLIES (IS-MODULE md)
  (FORALL n (IMPLIES (IN n NN)
   (FORALL c (IMPLIES (IN c (MAT 1 n (CARR (SCAL md))))
    (FORALL r (IMPLIES (IN r (CARR (SCAL md)))
      (IN (SNOC-ROW c n r) (MAT 1 (succ n) (CARR (SCAL md))))))))))))))
(di)(di)(di)(di)(di)(di)(di)(di)
(display ";; goal: ")(write (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))(newline)
(fact 'snoc-row-type '(CARR (SCAL md)) 'n 'c 'r)
(display ";; after fact, done? ")(display (proof-done? *ps*))(newline)
(if (proof-done? *ps*) (display ";; SNOC-ROW-TYPE FIRES\n") (begin (ass) (display ";; done after ass? ")(display (proof-done? *ps*))(newline)))
