(sp (make-wff '(FORALL md (IMPLIES (IS-MODULE md)
  (FORALL n (IMPLIES (IN n NN)
   (FORALL c (IMPLIES (IN c (MAT 1 n (CARR (SCAL md))))
    (FORALL u (IMPLIES (IN u (MAT n 1 (VEC md)))
     (FORALL r (IMPLIES (IN r (CARR (SCAL md)))
      (FORALL x (IMPLIES (IN x (VEC md))
        (= (ENTRY (MATACT md (SNOC-ROW c n r) (SNOC-COL u n x)) 1 1)
           ((VADD md) (ENTRY (MATACT md c u) 1 1) ((ACT md) r x)))))))))))))))))
(do ((k 0 (+ k 1))) ((= k 12)) (di))
(fact 'module-scalar-ring 'md)
(fact 'snoc-row-type '(CARR (SCAL md)) 'n 'c 'r)
(fact 'snoc-col-type '(VEC md) 'n 'u 'x)
(fact 'one-in-interval-1)
(define (dump tag) (display ";;; ")(display tag)(display " ctx-has-matact-eq? ")
  (display (any (lambda (a) (let ((f (wff-formula a))) (and (pair? f) (eq? (car f) '=)
     (pair? (cadr f)) (eq? (car (cadr f)) 'ENTRY)
     (pair? (cadr (cadr f))) (eq? (car (cadr (cadr f))) 'MATACT))))
     (sequent-node-assumptions (proof-state-focus *ps*)))) (newline))
(fact 'matact-entry 'md 1 '(succ n) 1 '(SNOC-ROW c n r) '(SNOC-COL u n x) 1 1)
(dump "after matact-entry(snoc)")
(fact 'matact-entry 'md 1 'n 1 'c 'u 1 1)
(dump "after matact-entry(c,u)")
