(sp (make-wff '(FORALL md (IMPLIES (IS-MODULE md)
  (FORALL n (IMPLIES (IN n NN)
   (FORALL c (IMPLIES (IN c (MAT 1 n (CARR (SCAL md))))
    (FORALL u (IMPLIES (IN u (MAT n 1 (VEC md)))
     (FORALL r (IMPLIES (IN r (CARR (SCAL md)))
      (FORALL x (IMPLIES (IN x (VEC md))
        (= (ENTRY (MATACT md (SNOC-ROW c n r) (SNOC-COL u n x)) 1 1) (VZERO md))))))))))))))))
(do ((k 0 (+ k 1))) ((= k 12)) (di))
(fact 'snoc-row-type '(CARR (SCAL md)) 'n 'c 'r)
(fact 'snoc-col-type '(VEC md) 'n 'u 'x)
(fact 'one-in-interval-1)
(display ";;; --- assumptions with SNOC or IS-MODULE or INTERVAL 1 1 ---")(newline)
(for-each (lambda (a) (let ((f (wff-formula a)))
   (when (or (memq 'IS-MODULE (list (and (pair? f)(car f))))
             (and (pair? f) (eq? (car f) 'IN) (pair? (caddr f)) (eq? (car (caddr f)) 'MAT)))
     (display ";;; ")(write f)(newline))))
  (sequent-node-assumptions (proof-state-focus *ps*)))
