(sp (make-wff '(FORALL md (IMPLIES (IS-MODULE md)
  (FORALL n (IMPLIES (IN n NN)
   (FORALL u (IMPLIES (IN u (MAT n 1 (VEC md)))
    (FORALL x (IMPLIES (IN x (VEC md))
      (IN (SNOC-COL u n x) (MAT (succ n) 1 (VEC md)))))))))))))
(do ((k 0 (+ k 1))) ((= k 8)) (di))
(fact 'snoc-col-type '(VEC md) 'n 'u 'x)
(display ";;; done after snoc-col-type fact? ")(display (proof-done? *ps*))(newline)
(fact 'nn-succ-closed 'n)
(fact 'snoc-col-type '(VEC md) 'n 'u 'x)
(display ";;; done after +nn-succ-closed? ")(display (proof-done? *ps*))(newline)
(if (not (proof-done? *ps*)) (begin (ass) (display ";;; done after ass? ")(display (proof-done? *ps*))(newline)))
