(sp (make-wff '(FORALL md (IMPLIES (IS-MODULE md)
  (FORALL n (IMPLIES (IN n NN)
   (FORALL c (IMPLIES (IN c (MAT 1 n (CARR (SCAL md))))
    (FORALL r (IMPLIES (IN r (CARR (SCAL md)))
      (IN (SNOC-ROW c n r) (MAT 1 (succ n) (CARR (SCAL md))))))))))))))
(do ((k 0 (+ k 1))) ((= k 8)) (di))
(fact 'snoc-row-type '(CARR (SCAL md)) 'n 'c 'r)
(for-each (lambda (a) (let ((f (wff-formula a)))
   (when (and (pair? f) (eq? (car f) 'IN) (pair? (cadr f)) (eq? (car (cadr f)) 'SNOC-ROW))
     (display ";;; CTX: ")(write f)(newline))))
  (sequent-node-assumptions (proof-state-focus *ps*)))
(display ";;; GOAL: ")(write (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))(newline)
