(load "load.scm")
(set! *vnb-quiet* #t)
(define (mq-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mq-di*) (let lp () (let* ((g (mq-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (mq-last) (car (reverse (dg-sequent-nodes (proof-state-dg *ps*)))))
(define (mq-node! n) (set-proof-state-focus! *ps* n))
(define (mq-foc! pred)
  (let ((s (any-pred (lambda (s) (pred (wff-formula (sequent-node-assertion s)))) (proof-leaves))))
    (and s (set-proof-state-focus! *ps* s) s)))
(define (mq-asms) (map wff-formula (sequent-node-assumptions (proof-state-focus *ps*))))
(define (mq-find pred) (let lp ((as (mq-asms))) (cond ((null? as) #f)((pred (car as))(car as))(else (lp (cdr as))))))
(define (mq-em P)
  (cut (list 'OR P (list 'NOT P)))
  (let ((uo (mq-last)))
    (pbc) (cut (list 'NOT P))
    (let ((un (mq-last)))
      (di) (cut (list 'OR P (list 'NOT P)))
      (let ((u2 (mq-last))) (oi-l) (ass) (mq-node! u2))
      (ai (list 'NOT (list 'OR P (list 'NOT P)))) (mq-node! un))
    (cut (list 'OR P (list 'NOT P)))
    (let ((u3 (mq-last))) (oi-r) (ass) (mq-node! u3))
    (ai (list 'NOT (list 'OR P (list 'NOT P)))) (mq-node! uo)))
(define (mq-cases P) (mq-em P) (ai (list 'OR P (list 'NOT P))) (mq-last))
(define (foc-meq! B) (mq-foc! (lambda (g)(and (pair? g)(eq?(car g)'MAT-EQUIV)(equal?(list-ref g 5) B)))))
(define (foc-val! B) (mq-foc! (lambda (g)(and (pair? g)(eq?(car g)'=)(pair?(cadr g))(eq?(car(cadr g))'ENTRY)(equal?(cadr(cadr g)) B)))))

(define Fm '(ELEM-F R m 1 i0))
(define Fn '(ELEM-F R n 1 j0))
(define Bri (list 'MATMUL 'R 'A Fn))
(define Ble (list 'MATMUL 'R Fm 'A))

(sp (make-wff '(FORALL R (IMPLIES (IS-RING R) (FORALL m (FORALL n (FORALL A (FORALL i0 (FORALL j0 (IMPLIES (IN A (MAT m n (CARR R))) (IMPLIES (IN 1 (INTERVAL 1 m)) (IMPLIES (IN 1 (INTERVAL 1 n)) (IMPLIES (IN i0 (INTERVAL 1 m)) (IMPLIES (IN j0 (INTERVAL 1 n)) (FORSOME B (AND (MAT-EQUIV R m n A B) (= (ENTRY B 1 1) (ENTRY A i0 j0))))))))))))))))))
(mq-di*)
(fact 'entry-in-carrier 'm 'n '(CARR R) 'A 'i0 'j0)
(fact 'entry-in-carrier 'm 'n '(CARR R) 'A 1 1)
;; ===== case (= 1 i0) =====
(define NOTi (mq-cases '(= 1 i0)))
  (define NOTj-a (mq-cases '(= 1 j0)))
    ;; both =1 : B = A
    (fact 'mat-equiv-refl 'R 'm 'n 'A) (fact 'eq-sym 1 'i0) (fact 'eq-sym 1 'j0)
    (ew 'A) (di)
    (foc-meq! 'A) (ass)
    (foc-val! 'A) (subst '(= i0 1)) (subst '(= j0 1)) (rfl)
  (mq-node! NOTj-a)
    ;; i0=1, NOT j0=1 : B = A.F[1,j0]
    (fact 'elem-f-invertible 'R 'n 1 'j0)
    (fact 'mat-equiv-right-mult 'R 'm 'n 'A Fn) (fact 'eq-sym 1 'i0)
    (ew Bri) (di)
    (foc-meq! Bri) (ass)
    (foc-val! Bri)
    (fact 'elem-f-action 'R 'm 'n 'A 1 'j0 1 1)
    (define IFa (list 'IF '(= 1 1) '(ENTRY A 1 j0) (list 'IF '(= 1 j0) '(ENTRY A 1 1) '(ENTRY A 1 1))))
    (subst (list '= (list 'ENTRY Bri 1 1) IFa))
    (if-true IFa) (define ca (mq-last)) (rfl) (mq-node! ca)
    (subst (list '= IFa '(ENTRY A 1 j0)))
    (subst '(= i0 1)) (rfl)
;; ===== case NOT (= 1 i0) =====
(mq-node! NOTi)
(define NOTj-b (mq-cases '(= 1 j0)))
    ;; NOT i0=1, j0=1 : B = F[1,i0].A
    (fact 'elem-f-invertible 'R 'm 1 'i0)
    (fact 'mat-equiv-left-mult 'R 'm 'n 'A Fm) (fact 'eq-sym 1 'j0)
    (ew Ble) (di)
    (foc-meq! Ble) (ass)
    (foc-val! Ble)
    (fact 'elem-f-row-action 'R 'm 'n 'A 1 'i0 1 1)
    (define IFb (list 'IF '(= 1 1) '(ENTRY A i0 1) (list 'IF '(= 1 i0) '(ENTRY A 1 1) '(ENTRY A 1 1))))
    (subst (list '= (list 'ENTRY Ble 1 1) IFb))
    (if-true IFb) (define cb (mq-last)) (rfl) (mq-node! cb)
    (subst (list '= IFb '(ENTRY A i0 1)))
    (subst '(= j0 1)) (rfl)
  (mq-node! NOTj-b)
    ;; NOT i0=1, NOT j0=1 : swap-to-corner
    (fact 'swap-to-corner 'R 'm 'n 'A 'i0 'j0)
    (ai 1) (ai 1)
    (define B0eq (mq-find (lambda (z) (and (pair? z)(eq?(car z)'MAT-EQUIV)))))
    (define B0 (list-ref B0eq 5))
    (ew B0) (di)
    (foc-meq! B0) (ass)
    (foc-val! B0) (ass)
(call-with-output-file "/tmp/claude-1000/-home-ubuntu/423ebffe-e6fe-4caf-8686-2808e8178391/scratchpad/RESULT.txt" (lambda (p) (write (list 'swap-to-corner-gen (proof-done? *ps*)
   (map (lambda (s) (wff-formula (sequent-node-assertion s))) (proof-leaves))) p)))
(%exit 0)
