;;; submat.scm -- entry-of-submat.
(set! *vnb-quiet* #t)
(define (mq-goal) (wff-formula (sequent-node-assertion (proof-state-focus *ps*))))
(define (mq-di*) (let lp () (let* ((g (mq-goal)) (h (and (pair? g) (car g))))
                   (when (memq h '(FORALL IMPLIES)) (di) (lp)))))
(define (rep nm) (display nm)(display " done? ")(display (proof-done? *ps*))(newline)
  (when (not (proof-done? *ps*))
    (for-each (lambda (s) (display "  OPEN: ")(write (wff-formula (sequent-node-assertion s)))(newline)) (proof-leaves))))
(sp (make-wff '(FORALL P (FORALL p (FORALL q (FORALL i (FORALL j (IMPLIES (IN i (INTERVAL 1 p)) (IMPLIES (IN j (INTERVAL 1 q)) (= (ENTRY (SUBMAT P p q) i j) (ENTRY P (succ i) (succ j))))))))))))
(mq-di*)
(mac 'SUBMAT)
(fact 'entry-of-matof 'p 'q '(VNB-LAMBDA (LIST i j) (ENTRY P (succ i) (succ j))) 'i 'j)
(subst (list '= '(ENTRY (MATOF p q (VNB-LAMBDA (LIST i j) (ENTRY P (succ i) (succ j)))) i j) '((VNB-LAMBDA (LIST i j) (ENTRY P (succ i) (succ j))) i j)))
(display "goal before lam-b: ")(write (mq-goal))(newline)
(lam-b)
(display "goal after lam-b: ")(write (mq-goal))(newline)
(rep 'entry-of-submat)
(%exit 0)
